### ISSUE TITLE
errno = 1600

### ISSUE THREAD

**Issue by tr3x33** [Azure/azure-storage-fuse#100]
Hello, I have next error:

$ blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/username/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

invalid padding character found in base64 string
Creating blob client failed: errno = 1600.

Could you please suggest what can be wrong here? If found no information for 'errno = 1600.'

I tried to check strace and tried creation of '/etc/gcrypt/fips_enabled' and '/etc/system-fips', but that didn't help.

Could you please suggest something?

**Comment by seguler** [comment]
This happens if your account key is wrong in connection.cfg

Are you sure it is in a valid format ?

**Comment by seguler** [comment]
Closing as there was no response.
