### ISSUE TITLE
Cached files are not invalidated if the file size is identical to the previous file after upload

### ISSUE THREAD

**Issue by kojot1234** [Azure/azure-storage-fuse#1000]
### Which version of blobfuse was used?
both v1 and v2 (latest) seem to suffer from the same issue

### Which OS distribution and version are you using?
Nginx 1.23 (debian 11)

### If relevant, please share your mount command.
PV mounted via Helm chart using blob.csi.azure.com driver
```---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-blob
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - -o allow_other
    - -o ro
    - --virtual-directory=true
  csi:
    driver: blob.csi.azure.com
    readOnly: true
    volumeHandle: {{ .Release.Namespace }}-storage
    volumeAttributes:
      containerName: {{ .Values.BLOB_CONTAINER }}
      protocol: fuse2
```
### What was the issue encountered?
Cached files are not invalidated if they are the exact same size, if a file has a different size everything works as expected

### Have you found a mitigation/solution?
I have not found a workaround, tried `--streaming=true` but the file is still cached. Also tried the below attribute caching options with same result
```
    # - -o attr_timeout=10
    # - -o entry_timeout=10
    # - -o negative_timeout=10
    # - --attr-cache-timeout=10
```

**Comment by vibhansa-msft** [comment]
- Blobfuse file-caching does not work on size or LMT of file. A file once downloaded will remain in cache till the file-cache-timeout expires. Kindly check what value you have put up for this, default is 2 minutes.
- In case of small files, kernel will hold the contents of files in page-cache and no matter what you read it will be served from there and call will not even reach blobfuse. This is resolved in blobfuse2 with fuse3 combination. As long as you are on a system where fuse2 is supported, this will not work.
- When streaming is enabled, blobfuse does not download any file. Your observation "file is still cached" is mostly due to some invalid config.

**Comment by kojot1234** [comment]
Thanks for the prompt response. At this point I think we've tried all possible configuration options and the result seems to be the same. When I navigate to the mounted directory via bash, when I list the files, I can see the last modified date on the file has changed, however when editing the file (nano) it's still the old copy. Keep in mind if the file size is different everything works as expected and cache timeout configuration is taken into account.

The only option we had to enabled in v2 is `--virtual-directory=true` because nginx would return 404s for deeply nested files.

As a side note, we also noticed the exact same problem in Azure Web Service/App when the storage account is mounted to the App Service via Mount Path configuration. Files are cache for 120 seconds (assuming default) if the size it different, however if the file size is identical to the previously uploaded file, it sometimes stays in cache for 10-20+ minutes.

**Comment by vibhansa-msft** [comment]
Can you confirm whether you are on fuse2 compliant system or fuse3. Just try "fusermount3 --v" if this complains about command does not present then you are using fuse2 as of now. Fuse2 suffers with kernel caching issue where user has to manually clear the kernel cache to refresh the contents of the file. You can try doing 'ls' on mount path and see if the file LMT or size is getting updated or not and still contents are older than its kernel cache issue for sure. If you are on fuse3 compliant system, then file-cache-timeout you might want to set to 0 to refresh every time you open the file.

**Comment by vibhansa-msft** [comment]
Even if you upgrade the CSI driver, this will will be resolved only with blobfuse2 as legacy blobfuse works only with fuse2.

**Comment by vibhansa-msft** [comment]
If you wish to manually clear the page cache use command : "sysctl -w vm.drop_caches=3"

**Comment by kojot1234** [comment]
I would suggest including a mention of this issue in Known Limitations, I'm surprised more people didn't run into this problem.

Thank you Vikas, appreciate your help.

**Comment by vibhansa-msft** [comment]
Kerenel caching with fuse2 is a well-known issue and most customers are aware that they need to manually clear the page-cache to get the new content. Will see if thats documented in wiki or not. If not, will add it there.
