### ISSUE TITLE
configs file is loaded after VersionCheck(), so proxy settings are not used when calling beginDetectNewVersion()

### ISSUE THREAD

**Issue by sebgir** [Azure/azure-storage-fuse#1002]
### Which version of blobfuse was used?
version 2.0.1

### Which OS distribution and version are you using?
Ubuntu 18.04

### If relevant, please share your mount command.
n/a

### What was the issue encountered?
Using the mount command :

Proxy settings are not used when doing the new version detection (they are loaded from yaml file only at line 226) and the resultings errors in the http GETs will interupt the mount command.  It's not easy to debug since only one line will be visible in log saying : `dial tcp: lookup blobfuse2.blob.core.windows.net: no such host`

VersionCheck should be an optionnal step or proxy settings should be used when calling `blobfuse2.blob.core.windows.net`

### Have you found a mitigation/solution?
use --disable-version-check=true will fix issue, but versionCheck will be disabled.

**Comment by gapra-msft** [comment]
Thanks @sebgir for this find. 

We will plan to get a fix around for this as soon as we can. 

Until then, the --disable-version-check flag should help mitigate the problem until then.

**Comment by vibhansa-msft** [comment]
Are you configuring proxy in blobfuse2 config or environment variable. Try exporting proxy config in standard Linux env variables "https_proxy". If Linux env variable is configured properly then there is no need to mention the same in blobfuse config file.

**Comment by sebgir** [comment]
> Are you configuring proxy in blobfuse2 config or environment variable. Try exporting proxy config in standard Linux env variables "https_proxy". If Linux env variable is configured properly then there is no need to mention the same in blobfuse config file.

Thank you Vikas for the other great workaround.

I will disable version check until V2.0.2 or so.  The solution is working perfectly this way.

**Comment by vibhansa-msft** [comment]
@sebgir : can you confirm setting linux environment variables worked for you. As it's not a workaround rather a solution for proxy based environments. We can update our documentation saying if env variable is set no need to provide config parameter to blobfuse.

**Comment by sebgir** [comment]
> @sebgir : can you confirm setting linux environment variables worked for you. As it's not a workaround rather a solution for proxy based environments. We can update our documentation saying if env variable is set no need to provide config parameter to blobfuse.

I will only be able to test it in a few days.

We generaly avoid using enviroment variables when we can use configs files for maintainability and deployment.  The VersionCheck() method should at least be non fatal when exceptions are raised inside IMHO. A warning about setting that environment variable or --disable-version-check should be shown if possible.  I'm not a huge fan of documentation reading ;)

Thank you all for your support

**Comment by vibhansa-msft** [comment]
Config parsing is happening in parallel to the version check and hence it's not possible for this flow to take dependency on the config options. Changing the order/flow will need some code churn and good testing cycles, which we are not prioritizing at this moment. Best option here is to either disable the version check (which does not impact any functionality) or provide the proxy settings in environment variables.

**Comment by vibhansa-msft** [comment]
To add to my above comment, there are commands which do not take any config file as input like "blobfuse2 version --check" which execute the same flow of version check.

**Comment by vibhansa-msft** [comment]
"VersionCheck() method should at least be non-fatal when exceptions are raised inside IMHO": as per code its non-fatal only and it just spits out a log saying host is not reachable, but the mount continues. Are you observing something else here?
