### ISSUE TITLE
 CentOS/RHEL Logrotate Parameters Incorrect

### ISSUE THREAD

**Issue by jgregorcmh** [Azure/azure-storage-fuse#1006]
### Which version of blobfuse was used?

blobfuse2 v2.0.1

### Which OS distribution and version are you using?

RHEL 8.7 from Azure marketplace, RedHat:RHEL:8_7:latest (currently version 8.7.2022112201).  
Kernel version: 4.18.0-425.3.1.el8.x86_64
rsyslog version: 8.2102.0-10.el8.x86_64
logrotate version: 3.14.0-4.el8.x86_64

### If relevant, please share your mount command.

Not relevant; error occurs outside of mounting storage.

### What was the issue encountered?

Install of blobfuse2-2.0.1-1 from Microsoft Prod repo (https://packages.microsoft.com/rhel/8/prod) creates a logrotate record at /etc/logrotate.d/blobfuse2 which includes the line "su root syslog".  This produces errors from logrotate that forces skipping of the rotate as the RHEL rsyslog package does not create a syslog group.

### Have you found a mitigation/solution?

Line one of the [logrotate file](https://github.com/Azure/azure-storage-fuse/blob/main/setup/blobfuse2-logrotate) specifies root user and syslog group for Ubuntu support.  CentOS/RHEL 7 & 8 do not have a syslog group.   Introduce in the build process for rpm to remove the line or substitute a different logrotate file; retain the current configuration for deb build.  As a mitigation, a user can edit the logrotate post-install to set `su root root` or omit line one and avoid the error.

### Please share logs if available.

```
/etc/cron.daily/logrotate:

error: blobfuse2:1 unknown group 'syslog'
error: found error in file blobfuse2, skipping
```

**Comment by vibhansa-msft** [comment]
Does removing this line from logrotate create any issue for RHEL/CentOS as per your experiments?

**Comment by jgregorcmh** [comment]
Not that I have found.
