### ISSUE TITLE
mount all with MSI encounters throttling limits

### ISSUE THREAD

**Issue by StefanHauser** [Azure/azure-storage-fuse#1008]
### Which version of blobfuse was used?
2.0.1

### Which OS distribution and version are you using?
SLES 15 SP1

### If relevant, please share your mount command.
blobfuse2 mount all /home/<myuser>/ --config-file=/home/<myuser>/fuse_config.yaml

### What was the issue encountered?
The storage account contains 22 containers. When running the command only around 5-10 random containers are mounted. The others fail with this log output:

`zAuthBlobMSI::getCredential : Failed to get credential [failed to get token from msi, status code: 429]`

It seems that for every mount, one authentication request is sent, which leads to throttling limits on MSI site.

### Have you found a mitigation/solution?
Rerunning the command several times leads to all containers mounted in the end. I have tried configuring the `retry-backoff-sec` to 15 seconds but this doesn't seem to affect authentication but only mounting itself. Has no effect for me.

### Please share logs if available.
```
azAuthBlobMSI::getCredential : Failed to get credential [failed to get token from msi, status code: 429]
Thu Dec 22 10:47:51 UTC 2022 : blobfuse2[3901] : LOG_ERR [block_blob.go (145)]: BlockBlob::getCredential : Failed to get credential
Thu Dec 22 10:47:51 UTC 2022 : blobfuse2[3901] : LOG_ERR [block_blob.go (179)]: BlockBlob::SetupPipeline : Failed to get credential
Thu Dec 22 10:47:51 UTC 2022 : blobfuse2[3901] : LOG_ERR [azstorage.go (140)]: AzStorage::configureAndTest : Failed to create container URL [failed to get credential]
Thu Dec 22 10:47:51 UTC 2022 : blobfuse2[3901] : LOG_ERR [azstorage.go (100)]: AzStorage::Configure : Failed to validate storage account [failed to get credential]
Thu Dec 22 10:47:51 UTC 2022 : blobfuse2[3901] : LOG_ERR [pipeline.go (69)]: Pipeline: error creating pipeline component azstorage [failed to get credential]
Thu Dec 22 10:47:51 UTC 2022 : blobfuse2[3901] : LOG_ERR [mount.go (368)]: mount : failed to initialize new pipeline [failed to get credential]
```

**Comment by vibhansa-msft** [comment]
Blobfuse does not cache the token so if you have 30 containers to mount, each instance will go and fetch a new token from server for authentication. Might be some limit is getting hit there to generate tokens so frequently.
Just to validate this theory can you use account key or SAS and see if that gets through.

**Comment by vibhansa-msft** [comment]
With MSI even if you mount, there will be another throttle hit when each instance tries to refresh the token. So, using MSI for this is not a suitable solution.

**Comment by StefanHauser** [comment]
> Blobfuse does not cache the token across instances so if you have 30 containers to mount, each instance will go and fetch a new token from server for authentication. If limits are hit on the OAuth server better to try with account key or service-level SAS.
I am very reluctant to use shared key or sas for security reasons. 

I assume that same issue is persists for user assinged managed identity? 

Moreover, is it advisable to mount the containers one by one with msi? Are the token refreshness intervalls centrally managed by the blobfuse installation or relative to the mounting time? 

Is there a plan to omplement the caching of the acquired token in one of the future versions?

**Comment by vibhansa-msft** [comment]
As of now there is no plan to cache the token. Just to clear the doubt "mount all" internally runs multiple instances of blobfuse  (one per container) and they all run as independent processes. If one process is managing all containers, then it makes sense to hold a single token. Hence, I suggested to use other auth mode for "mount all" case.
Each instance on start will acquire a token using OAuth, and around the expiry time it will refresh it on its own (independent of other instances running in parallel).

**Comment by vibhansa-msft** [comment]
Closing this as blobfuse cannot cache the token across multiple instances. You can use storage key or SAS as a workaround. Feel free to post any queries here.
