### ISSUE TITLE
BlobFuse2 Windows Equivalent?

### ISSUE THREAD

**Issue by yusuf-jkhan1** [Azure/azure-storage-fuse#1009]
Sorry for not following the proper ticket structure.

I just wanted to know what the best practice equivalent workflow would be in Windows 10?

Right now I'm using a slightly janky hack that runs rclone mount as a windows service via nssm. It is not great. 

What would be the best way to do this for Windows 10? Would using WSL2 enable this?

**Comment by vibhansa-msft** [comment]
Blobfuse does not support Windows natively, so the best way is to enable WSL2 and mount using that. In case you wish to use the mounted folder through windows you can either setup SMB or WSL qualified path. You can use [this](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-WSL) for reference.
