### ISSUE TITLE
Subfolders in a container are not getting listed after mounting

### ISSUE THREAD

**Issue by lijithomas88** [Azure/azure-storage-fuse#1010]
### Which version of blobfuse was used?
2.0.1

### Which OS distribution and version are you using?
Ubuntu, 
20.04.5 LTS 
### If relevant, please share your mount command.
blobfuse2 mount all /opt/sdv/datalake --config-file=/opt/sdv/config.yaml  --log-level=log_debug --log-file-path=/opt/sdv/bobfuse2b.log
### What was the issue encountered?
There are no errors shown in mounting. But not able to see the subfolders inside container after mounting. Only the files which are there directly in the container are shown. 

### Have you found a mitigation/solution?

No
### Please share logs if available.

![image](https://user-images.githubusercontent.com/56118477/209909180-ae7426d4-2ce3-4f01-98d0-8f06b514a215.png)
![image](https://user-images.githubusercontent.com/56118477/209909644-853b9d67-801c-45b2-b709-eb796b7cf8a0.png)

config.yaml
---------------

allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 8
  blocks-per-file: 3
  cache-size-mb: 1024

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: XXX
  tenantid: 
  clientid: 
  clientsecret: 
  endpoint: https://XXX.blob.core.windows.net
  mode: spn
  container: tenant102178

**Comment by vibhansa-msft** [comment]
This storage account is HNS enabled?

**Comment by vibhansa-msft** [comment]
Instead of "mount all" can you try just mounting this container and see if it differs?

**Comment by lijithomas88** [comment]
> This storage account is HNS enabled?

yes

**Comment by lijithomas88** [comment]
> Instead of "mount all" can you try just mounting this container and see if it differs?

blobfuse2 mount /opt/sdv/datalake --config-file=/opt/sdv/config.yaml  --log-level=log_debug --log-file-path=/opt/sdv/bobfuse2b.log
tried this command.

![image](https://user-images.githubusercontent.com/56118477/209914426-7e77a8c1-7d1e-4bf8-a4d9-967cafb21ee9.png)

**Comment by vibhansa-msft** [comment]
For HNS enable account, remove "endpoint: https://xxx.blob.core.windows.net/" from your config file and set "type: adls" instead of "block". You can refer to master config file to understand what each flag means:
https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml

**Comment by lijithomas88** [comment]
It seems to be working now. Thanks for the guidance.

**Comment by vibhansa-msft** [comment]
Closing this. Feel free to post here in case you have any further questions.
