### ISSUE TITLE
Blobfuse2 and Async IO

### ISSUE THREAD

**Issue by ramosubr** [Azure/azure-storage-fuse#1013]
Does blobfuse2 supports async IO? My requirement is to backup Oracle Database using RMAN in a storage account using blobfuse. When i trigger the backup now it fails with the following message with blobfuse:

Starting backup at 20-DEC-22
using target database control file instead of recovery catalog
allocated channel: ORA_DISK_1
channel ORA_DISK_1: SID=1832 device type=DISK
channel ORA_DISK_1: starting full datafile backup set
channel ORA_DISK_1: specifying datafile(s) in backup set
input datafile file number=00001 name=/var/dbdata/EMO_DB00/datafile/o1_mf_system_ks5zl49j_.dbf
channel ORA_DISK_1: starting piece 1 at 20-DEC-22
RMAN-00571: ===========================================================
RMAN-00569: =============== ERROR MESSAGE STACK FOLLOWS ===============
RMAN-00571: ===========================================================
RMAN-03009: failure of backup command on ORA_DISK_1 channel at 12/20/2022 07:36:28
ORA-19504: failed to create file "/var/dbarchive/blobfuse/backup/EMO_0a1fr8np_1123918585.bak"
ORA-27044: unable to write the header block of file
Linux-x86_64 Error: 22: Invalid argument
Additional information: 3

I read an article in Oracle Support and Async IO required for RMAN backups when filesystemio_options=SETALL on the DB side.

**Comment by vibhansa-msft** [comment]
Blobfuse does not support Async IO, just like most network attached file-systems. Try adding " ignore-open-flags: true" to your "libfuse:" section in config file and retry.

**Comment by ramosubr** [comment]
Tried downloading blobfuse2 using the below options. But it did not go through.
1. sudo rpm -Uvh https://packages.microsoft.com/rhel/7/prod/blobfuse2-2.0.1-RHEL-7.8-x86_64.rpm

Retrieving https://packages.microsoft.com/rhel/7/prod/blobfuse2-2.0.1-RHEL-7.8-x86_64.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://packages.microsoft.com/rhel/7/prod/blobfuse2-2.0.1-RHEL-7.8-x86_64.rpm - transfer failed

2. # sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
Retrieving https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:packages-microsoft-prod-1.0-1.el7################################# [100%]
# yum install blobfuse2
Loaded plugins: langpacks, product-id, search-disabled-repos
Repository packages-microsoft-com-prod is listed more than once in the configuration
No package blobfuse2 available.
Error: Nothing to do

**Comment by ramosubr** [comment]
Trying to download blobfuse2 as i believe "ignore-open-flags: true" is not available in blobfuse.

**Comment by vibhansa-msft** [comment]
"ignore-open-flags: true" is not available in blobfuse 1.x. To download blobfuse2 instead of using "rhel/7" in your url put the exact RHEL version like "7.5" or "7.8" or "8.0" and try.

**Comment by ramosubr** [comment]
I am using RHEL 7.9. But i don't see blobfuse2 available for RHEL 7.9

**Comment by ramosubr** [comment]
I am not able to download. Pls advice.

#rpm -Uvh https://packages.microsoft.com/rhel/8.0/prod/blobfuse2-2.0.1-RHEL-8.0-x86_64.rpm
Retrieving https://packages.microsoft.com/rhel/8.0/prod/blobfuse2-2.0.1-RHEL-8.0-x86_64.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://packages.microsoft.com/rhel/8.0/prod/blobfuse2-2.0.1-RHEL-8.0-x86_64.rpm - transfer failed
# rpm -Uvh https://packages.microsoft.com/rhel/8/prod/blobfuse2-2.0.1-RHEL-8.0-x86_64.rpm
Retrieving https://packages.microsoft.com/rhel/8/prod/blobfuse2-2.0.1-RHEL-8.0-x86_64.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://packages.microsoft.com/rhel/8/prod/blobfuse2-2.0.1-RHEL-8.0-x86_64.rpm - transfer failed

**Comment by vibhansa-msft** [comment]
We do not release binary for 7.9. [RHEL 7.8](https://packages.microsoft.com/rhel/7.8/prod/blobfuse2-2.0.1-RHEL-7.8-x86-64.rpm) will be compatible for this which you can download from 

[RHEL 8.2](https://packages.microsoft.com/rhel/8.2/prod/blobfuse2-2.0.1-RHEL-8.2-x86-64.rpm) is also avilable. You can use similar path for 8.1 as well.

**Comment by ramosubr** [comment]
URL is not working for 7.8 as well. 

#rpm -Uvh https://packages.microsoft.com/rhel/7.8/prod/blobfuse2-2.0.1-RHEL-7.8-x86_64.rpm
Retrieving https://packages.microsoft.com/rhel/7.8/prod/blobfuse2-2.0.1-RHEL-7.8-x86_64.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://packages.microsoft.com/rhel/7.8/prod/blobfuse2-2.0.1-RHEL-7.8-x86_64.rpm - transfer failed

# rpm -Uvh https://packages.microsoft.com/rhel/7/prod/blobfuse2-2.0.1-RHEL-7.8-x86_64.rpm
Retrieving https://packages.microsoft.com/rhel/7/prod/blobfuse2-2.0.1-RHEL-7.8-x86_64.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://packages.microsoft.com/rhel/7/prod/blobfuse2-2.0.1-RHEL-7.8-x86_64.rpm - transfer failed

**Comment by vibhansa-msft** [comment]
https://packages.microsoft.com/rhel/7.8/prod/blobfuse2-2.0.1-RHEL-7.8-x86-64.rpm

**Comment by vibhansa-msft** [comment]
https://packages.microsoft.com/rhel/8.2/prod/blobfuse2-2.0.1-RHEL-8.2-x86-64.rpm

**Comment by vibhansa-msft** [comment]
x86-64 and not x86_64. Try with the above URLs that I have shared.

**Comment by vibhansa-msft** [comment]
Were you able to try out the correct binary?

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Feel free to reopen in case you have any further questions.

**Comment by ramosubr** [comment]
I was able to download and install blobfuse2 successfully. 
But when i try to mount i get the following error. 

Wed Jan 18 05:19:27 UTC 2023 : blobfuse2[20967] : LOG_ERR [libfuse_handler.go (178)]: Libfuse::initFuse : failed to mount fuse
Wed Jan 18 05:19:27 UTC 2023 : blobfuse2[20967] : LOG_ERR [libfuse.go (150)]: Libfuse::Start : Failed to init fuse [failed to mount fuse]
Wed Jan 18 05:19:27 UTC 2023 : blobfuse2[20967] : LOG_ERR [mount.go (462)]: mount: error unable to start pipeline [failed to mount fuse]

**Comment by ramosubr** [comment]
fuse3-3.6.1-4.el7.x86_64
fuse3-libs-3.6.1-4.el7.x86_64
blobfuse2-2.0.1-1.x86_64
fuse-2.9.2-11.el7.x86_64

OS: RHEL 7.9

blobfuse2-2.0.1-RHEL-7.8-x86-64.rpm was installed.
