### ISSUE TITLE
Logs of repeated error messages

### ISSUE THREAD

**Issue by cvvz** [Azure/azure-storage-fuse#1016]
### Which version of blobfuse was used?
blobfuse2 version 2.0.1

### Which OS distribution and version are you using?
Ubuntu 22.04

### If relevant, please share your mount command.
blobfuse2 mount /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/a45a1958a856c3aa56d78a5b485feb218d61673d0ed773a2367adaa6bf90fc4c/globalmount -o allow_other --file-cache-timeout-in-seconds=120 --use-attr-cache=true --cancel-list-on-mount-seconds=10 -o attr_timeout=120 -o entry_timeout=120 -o negative_timeout=120 --log-level=LOG_WARNING --cache-size-mb=1000 --container-name=pvc-45e0990f-bd6b-4cbe-baed-2e927981c7db --pre-mount-validate=true --use-https=true --empty-dir-check=false --tmp-path=/mnt/mc_weizhichen_weizhichen125_eastus#fuse74833b66893742a894d#pvc-45e0990f-bd6b-4cbe-baed-2e927981c7db##default#

### What was the issue encountered?
many repeated error messages in the log file:

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/44308864/210508943-3ae71031-80ee-4d9e-a5ec-89c1ed3b3e0a.png">

```shell
Jan  4 07:49:09 aks-nodepool1-16062421-vmss000001 blobfuse2[47882]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
```

why would this happen? I can execute `du` successfully. 
And what's the impact?

**Comment by vibhansa-msft** [comment]
Blobfuse is not able to find "du" utility in standard path and hence the error. This does not impact any regular work flow, its just that early cache eviction on disk getting full will not happen. For some reason, "du" is not available to blobfuse to execute.
