### ISSUE TITLE
Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.

### ISSUE THREAD

**Issue by mahaling** [Azure/azure-storage-fuse#1018]
### Which version of blobfuse was used?
blobfuse 1.4.5

### Which OS distribution and version are you using?
Ubuntu 20.04.4 (an azure vm cpu compute)

### If relevant, please share your mount command.
sudo blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=./fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --use-adls=true --container-name=hpa-cell-image-classification --log-level=LOG_DEBUG

### What was the issue encountered?
Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Unmounting blobfuse.
Unmounted blobfuse successfully.

### Have you found a mitigation/solution?
NO

### Please share logs if available.

followed the tutorial exactly as in here https://learn.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux

1. I have the cfg file with all the credentials pulled in from the storage account appropriately. 
2. Even tried az login --identity from the cli.

Any solution to this would be really helpful. Thanks

**Comment by xzizka** [comment]
Check this link for a quite detailed description of how I mounted blobfuse2 in Azure VM:
[https://github.com/Azure/azure-storage-fuse/issues/1007](https://github.com/Azure/azure-storage-fuse/issues/1007)

**Comment by mahaling** [comment]
Thanks for the response. My role is listed as Virtual Machine Contributor. Trying blobfuse2 gives the error as listed in #1007.

**Comment by vibhansa-msft** [comment]
We recommend you upgrade to blobfuse2. You need 'storage blob data contributor' role for blobfuse to work. Let me know if you face any other issue with that or need any help understanding how to configure blobfuse2.

**Comment by mahaling** [comment]
@vibhansa-msft I am fine with using blobfuse2, but can you please explain about the role. Does it have to be set for the storage account or the container alone or the vm-compute.
This is a team maintained resource group, so I do not have privileges to make any changes to the role assignment, but my understanding is that the roles have been assigned in such a way that blobfuse v1 or v2 mounts should work. Thanks

**Comment by vibhansa-msft** [comment]
For blobfuse to mount listing of blobs at a given container level shall be allowed. When you wish to transfer data, it will need read/write access to container level and this is where "storage blob data contributor" role comes in. If you have a identity assigned to your vm, have this role assigned to your identity for the storage container you wish to mount.

**Comment by mahaling** [comment]
All of these settings were already there, but was getting the error consistently. 
Added "authType Key" to the config file and it worked. just FYI

**Comment by qmr1cob** [comment]
Hello mahaling,
I'm facing the same issue. I have given the necessary permissions for the container(Storage blob data contributor - User Assigned Managed Identity).

Could you eloborate how you fixed it or where to add this authType Key.

**Comment by vibhansa-msft** [comment]
"authType Key" you need to add to blobfuse config file. However, this is for blobfuse 1.x. If you are using Blobfuse2 there is no need, based on the auth config provided it can autodetect the authType.
