### ISSUE TITLE
Blobfuse v1 vs v2 performance

### ISSUE THREAD

**Issue by mortenjoenby** [Azure/azure-storage-fuse#1026]
### Which version of blobfuse was used?
1.4.5 and 2.0.1 (2.0.0.preview.4)

### Which OS distribution and version are you using?
Oracle Linux 8.4

### If relevant, please share your mount command.
Mounted on pod using AKS 1.24.3, CSI driver 1.18.0.

### What was the issue encountered?
Based on some read and write testing using a small Java application, it seems that Blobfuse 1.4.5 is slightly faster than 2.0.x, which is not what the readme claims. It should be the opposite.

### Have you found a mitigation/solution?
No

### Please share logs if available.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

  | blobfuse1 | blobfuse2 | cifs
-- | -- | -- | --
avg 8KB write (ms) | 15,944 | 25,732 | 60,362
avg 8KB read (ms) | 0,082 | 7,342 | 21,154
avg 1MB write (ms) | 75,284 | 88,814 | 110,066
avg 1MB read (ms) | 5,222 | 20,14 | 46,662
avg 10MB write (ms) | 220,666 | 249,016 | 261,364
avg 10MB read (ms) | 38,082 | 81,12 | 153,078
avg 100MB write (ms) | 1598,26 | 2488,62 | 2169,24
avg 100MB read (ms) | 349,36 | 566,06 | 1238,8
avg 1GB write (ms) | 16417,26 | 14706,82 | 27159,02
avg 1GB read (ms) | 4212,82 | 5268,98 | 21890,68
</body>
</html>

**Comment by mortenjoenby** [comment]
Hi @andyzhangx .
Me again with the performance question that we agreed I would create here and not in the csi-driver repo.

**Comment by mortenjoenby** [comment]
The test first writes and then reads the files.
For small files (8KB, 1MB and 10MB) it's 5x100 writes/reads and for large files (100MB and 1GB) it's 5x10 writes/reads.
4 threads in parallel.
It's the exact same test used in all 3 tests in above table. In general v1 is slightly faster, but especially the 8KB read seems strangely low on v1. Could of course be our test, but since it's the same, then could it be some cache setting that's different?

**Comment by mortenjoenby** [comment]
BTW .... Storage account is general purpose v2 LRS. Azure Files (cifs) is Premium file storage.
I was surprised to see that when using ZRS the performance is actually almost 3x worse. I did not expect that.

**Comment by vibhansa-msft** [comment]
Can you also share the config file and mount cli that you are using for this test. We have similar tests in our pipeline as well and those report v2 being better compared to v1.

**Comment by mortenjoenby** [comment]
Hi @vibhansa-msft .
As you know we are using it in AKS through the CSI blob driver.
The only options we currently set at the mount options:
mountOptions:
    - -o default_permissions
    - -o allow_other
    - -o umask=007
    - -o gid=1000
    - -o uid=1000
    
On v2 of course without the UID/GID as that didn't work.
So everything else is default. If you need these, then let me know how to get them.

**Comment by mortenjoenby** [comment]
I believe these are the options - from the csi-blob-node container log:

```
volumeId testk8sdev1-perftest01-blob2
context map[containerName:background-processarea-blobv2 protocol:fuse2]
mountflags [-o default_permissions -o allow_other -o umask=007]
mountOptions [-o default_permissions -o allow_other -o umask=007 --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false --tmp-path=/mnt/testk8sdev1-perftest01-blob2 --container-name=background-processarea-blobv2]
```

**Comment by vibhansa-msft** [comment]
Can you try removing all these options other than "allow_other". In our trials we do not use these so not sure if they are making anything worse here.

- -o default_permissions
- -o umask=007
- -o gid=1000
- -o uid=1000
- 
In mount command also just give mount path, tmp path, container name, allow_other and leave everything to its default.

**Comment by gapra-msft** [comment]
Hi @mortenjoenby Does your system support fuse3 and is that the underlying fuse fs for blobfuse2? Our performance benefits stem from taking advantage of fuse3.

**Comment by mortenjoenby** [comment]
> Hi @mortenjoenby Does your system support fuse3 and is that the underlying fuse fs for blobfuse2? Our performance benefits stem from taking advantage of fuse3.

Hi @gapra-msft .
We are using Blobfuse2 in k8s using the CSI Blob driver. 
How do I check if we are using fuse3 protocol? Documentation is a bit confusing, but says "fuse" and "fuse2":
https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/driver-parameters.md

So how to I know which is used?

**Comment by vibhansa-msft** [comment]
This is based on the OS distro you are using. Refer to [this](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Supported-Platforms) to understand what is supported on which distro.
fuse/fuse2 are used interchangeably and both means you are using libfuse 2.x.
Blobfuse2 will give you performance boost with fuse3 (libfuse version 3.x). To check you have fuse3 installed in your container or not you can try running "fusermount3 --v" command check your libfuse version. If this does not work try "fusermount --v" and if that works, you are on fuse 2.x.

**Comment by mortenjoenby** [comment]
Hi @vibhansa-msft / @gapra-msft .
Documentation is rather confusing. Would be nice if you could update it and make it clear what's support on which versions - which is then also related to the AKS / Kubernetes version!
The link I dropped above doesn't list "fuse3" as an option at all (which I guess should be the protocol version to use - if supported?).

I checked the csi-blob-node container and it does seem like it's only version 2:

```
# fusermount --v
fusermount version: 2.9.9

# fusermount3 --v
sh: 2: fusermount3: not found

# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# uname -a
Linux aks-stepxl01-15526097-vmss00000E 5.4.0-1098-azure #104~18.04.2-Ubuntu SMP Tue Nov 29 12:13:35 UTC 2022 x86_64 GNU/Linux
```

According to your link - https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Supported-Platforms - I can only use fuse2 on Ubuntu 18.04, meaning that I need to go to Kubernetes v1.26.x to get a newer version of Ubuntu - correct? I believe this was just released.
I also assume that when "(fuse2)" is NOT listed on that page, it means fuse3 ? Please confirm.

Thanks,
Morten

**Comment by vibhansa-msft** [comment]
@mortenjoenby : Yes your assumptions are correct. In our wiki if "fuse2" is written then it means those systems support libfuse 2.x driver and rest all are libfuse 3.x compliant (default offering for blobfuse2, fuse2 is just for backward compatibility). 
In your case as its Ubn-18, fuse3 is not supported. As mentioned earlier most of the optimizations are done for fuse3 specific system as going forward all latest linux distros are fuse3 compliant.

**Comment by mortenjoenby** [comment]
Thanks for confirming @vibhansa-msft.
I guess we will have to wait until we upgrade to Kubernetes 1.26.x (which will be our next upgrade beginning of April).
I assume the fuse3 will be automatically used then, when we start using Ubuntu 22.04 on Kubernets 1.26?

**Comment by vibhansa-msft** [comment]
Yes Ubn-22 will have fuse3 compliant blobfuse2 binary.

**Comment by vibhansa-msft** [comment]
Shall be resolved once you move to fuse3. Open a new item if you still observe performance gaps.
