### ISSUE TITLE
Blobfuse2 - performance of blob rename

### ISSUE THREAD

**Issue by mortenjoenby** [Azure/azure-storage-fuse#1027]
### Which version of blobfuse was used?
2.0.0.preview.4 (AKS CSI driver 1.18.0)

### Which OS distribution and version are you using?
Oracle Linux 8.4

### What was the issue encountered?
We have been using Azure Files mounted w/ CIFS for some application storage. Due to mainly cost of Blob storage (being 1/10th of Azure Premium Files), we want to get away from using Files. We have been testing Blobfuse2 vs CIFS mounted Files. It's almost twice as fast in most cases.
We have one case though (within our application) where the output file from a batch process is renamed at the end. This renaming is much slower than when using CIFS.
Can you please explain (or refer to some docs) why it is much slower with Blobfuse2?
I assume it has to do with the file having to be downloaded to the cache first and then re-uploaded or something, but it would be pretty cool if there were a "rename blob" function that would make it at least as quick as using CIFS/Files or faster.

### Have you found a mitigation/solution? No.

**Comment by vibhansa-msft** [comment]
Is this HNS storage account or non-HNS. In case of non-HNS (flat name space) account there is no rename operation supported by backend. To support rename we copy the source file to destination path and then delete the source. As this is more of copy and delete combination it will take some time to complete based on the file size. If its HNS account, there shall not be any issue.
If it's just rename operation you are doing, then there is no local copy happening. We copy on the backend and delete source.  Any operation that involves opening a file will download the file.

**Comment by vibhansa-msft** [comment]
Was the above information helpful. If you query has been addressed kindly close this issue report.

**Comment by mortenjoenby** [comment]
Hi @vibhansa-msft .
Is this valid for HNS account only?
> If it's just rename operation you are doing, then there is no local copy happening.

I will look into the difference between HNS and non-HNS. I am not too familiar with the details. 
Is HNS "acting" more like a filesystem?

**Comment by vibhansa-msft** [comment]
https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-namespace

**Comment by mortenjoenby** [comment]
Thanks @vibhansa-msft .
We will test this out and see how it works compared to non-HNS.
