### ISSUE TITLE
After update to version 2.0.1 my folders dissapeared

### ISSUE THREAD

**Issue by xStin** [Azure/azure-storage-fuse#1028]
### Which version of blobfuse was used?
blobfuse2 version 2.0.1

### Which OS distribution and version are you using?
Debian GNU/Linux 11 (bullseye)

### What was the issue encountered?
After update blobfuse2 from 2.0.0.preview4 to 2.0.1 my folders disappeared.
Here the root case

1. No one folders after update
![5  bf2 0 1 FolderView](https://user-images.githubusercontent.com/9377197/211836884-d45b12b6-2755-4a6e-90a0-492db0da6f17.png)
2. Downgrade blobfuse2 to 2.0.0.preview4
![6  ReinstallBF2 0 0 preview4](https://user-images.githubusercontent.com/9377197/211837049-94c248bb-28f3-4793-a0ce-ee570e502ab3.png)
3. Check folders
![7  bf2 0 0 preview4 FolderView](https://user-images.githubusercontent.com/9377197/211837117-63643623-13f1-41cf-88dc-e6e391783f5b.png)

Here my yaml
![2  yaml](https://user-images.githubusercontent.com/9377197/211837341-9c8227a4-3c5f-448e-a648-dde7851f0b19.png)

### Have you found a mitigation/solution?
No

**Comment by gapra-msft** [comment]
Hi @xStin 

There was a change between v1 and v2 of blobfuse where directories in flat namespace accounts are only recognized by default if a marker directory exists at the location of directories. To work around this default, we have added a new option azstorage.virtual-directory to make it behave just like v1.

Could you please set azstorage.virtual-directory to true in your config file?

**Comment by xStin** [comment]
Hi @gapra-msft. Thanks for your reply
After set virtual-directory to true nothing changed.
Btw, I use v2. 
blobfuse2 2.0.0.preview4 has no ploblem with dir list
blobfuse2 2.0.1 - doesn't show folders

**Comment by gapra-msft** [comment]
@xStin Could you please share your updated config file after adding virtual-directory? Is your account a flat namespace or hierarchical namespace account?

**Comment by gapra-msft** [comment]
Could you please enable logging and share the log file with us? [Here ](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Logging#overview)is more information on logging 
I would recommend the file based logging approach as it is the easiest. 
Config options for logging can be seen [here](https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml#L40).

**Comment by xStin** [comment]
Hm...when virtual-directory set to true I cant copy files
![errorCopyFile](https://user-images.githubusercontent.com/9377197/211918374-2fbd47aa-8733-4fe3-903d-c2ff6cb49cf1.png)
Ok, enabling logging...

**Comment by xStin** [comment]
Here config
![EnableLogging](https://user-images.githubusercontent.com/9377197/211919960-ed64af86-d65a-4466-bd72-7caf5fd42491.png)
Here logs
[blobfuse2.log](https://github.com/Azure/azure-storage-fuse/files/10396034/blobfuse2.log)

**Comment by gapra-msft** [comment]
Thank you for sharing the logs. I think I have an understanding of what is happening here. I will write some developer notes here for when we validate the understanding and make a fix. 

This issue seems to happen if we have a virtual subdirectory in a virtual directory. [This](https://github.com/Azure/azure-storage-fuse/blob/e02acffd388092b6a88394799c863da9db870f25/component/azstorage/block_blob.go#L622) line needs to be changed to call bb.GetAttr instead of bb.getAttrUsingRest.

**Comment by vibhansa-msft** [comment]
> bb.GetA

Can you enable sdk-trace in your config and share the log-debug results again. To enable this "sdk-trace: true" to your "azstorage" section in config file.

**Comment by xStin** [comment]
Hi, @vibhansa-msft 
Here log file
[blobfuse2+SDKTrace).log](https://github.com/Azure/azure-storage-fuse/files/10399302/blobfuse2%2BSDKTrace.log)

**Comment by vibhansa-msft** [comment]
@xStin : I looked at the detailed logs that you have shared. As per logs blobfuse calls the listBlob API to get a list of blobs from the container. This API is not returning anything back in blobItems. This means you do not have any file at the root (for folders blobfuse looks for a stub file which is also not there at root). In this case blobfuse then goes and checks if there are some virtual directories in the path (as directory is not a supported feature in flat namespace account). In this list we get 3 items, which represent your directory.  
If a stub file exists for a directory, then in the first step of listing blobs, we should have retrieved it. But that is not the case here. So, to validate this scenario we do a GetAttribute call for the stub file, which is expected to fail. If we get back a 404 from server, we will construct a dummy property stub for that folder. But in your case this GetAttribute call is returning with success (200 OK) which is not an expected case. Hence blobfuse ignores this from the listing resutls.

Can you confirm your account is HNS enabled or flat name space account. If its HNS you might need to put that up in your configuration file. Can you also share a image from your portal on how the root of container looks like and these 3 directories that you mention are empty or having some files/directories inside it.

**Comment by xStin** [comment]
@vibhansa-msft 
Thank you for your reply
1. Yes, NHS enabled
![23  AccountSettings](https://user-images.githubusercontent.com/9377197/212054726-39e850cf-cba9-4201-b82c-ba2343c75786.png)
2. Container contains 3 folder. All folders not empty
![21  Portal view](https://user-images.githubusercontent.com/9377197/212054900-432ee82f-1d27-4a16-8e65-4386398f83e5.png)
![22  TestFolder view](https://user-images.githubusercontent.com/9377197/212054910-5c186909-aedd-4614-bfc6-f5115679a9bd.png)

About " If its HNS you might need to put that up in your configuration file". I don't understand what I need to do

P.S. Let me remind you that the blobfuse2 2.0.0.preview4 displays everything correctly without any changes in config file

**Comment by vibhansa-msft** [comment]
To mount HNS account correctly, in your config file under "azstorage" config add " type: adls".
I guess this shall solve your issue as well.

**Comment by vibhansa-msft** [comment]
alos, do not specify the endpoint in your config file. Blobfuse will auto create it based on account type.

**Comment by vibhansa-msft** [comment]
just for your reference, your config shall look something like: (for azstorage section)
azstorage:
   account-name: <>
   type: adls
   account-key: <>
   container: <>
   tier: cool

**Comment by xStin** [comment]
Yes, after add "type:adls" my ploblem is solved
Thank you very much!

For future maybe write about this in description (https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml#L40)? 
Because it not obvious

**Comment by xStin** [comment]
Hm... With "type:adls" a new problem appeared. I cant copy any files to directory using Samba

**Comment by xStin** [comment]
> Hm... With "type:adls" a new problem appeared. I cant copy any files to directory using Samba
> 
> Copy-Item : Access to the path '\_*****_\TestFolder\TestBackup.backup' is denied.

I figured out what the problem is.
When I add "type:adls" then default permissions for folders in container doesn't apply.
Do we have some attributes for default permissions?

If I add 
libfuse:
  default-permission: 
then folder disappeared again

**Comment by vibhansa-msft** [comment]
if you wish to have wider access policy then you need to set correct ACLs in your storage account at container/folder/file level

**Comment by vibhansa-msft** [comment]
Closing this issue as original folder not-shown is fixed with correction in config. If you face permission related issue feel free to create a new item here.
