### ISSUE TITLE
Lots of small files are orders of magnitude slower than the same files as an archive

### ISSUE THREAD

**Issue by guysoft** [Azure/azure-storage-fuse#103]
Hey,
So we have about ~3000 files that we need to copy regularly taking a few kb each.
Copying them takes about 5 minutes. However archiving them and copying them as an archive takes seconds.
We are basically aiming this to work with hundreds of thousands of files.

Searching I only found how to improve this in the [.net framework as explains here](https://stackoverflow.com/questions/13158893/performance-when-copying-many-small-files-from-an-azure-vm-temporary-disk-to-azu).

Is there any other way to fix this?

Thanks,

**Comment by seguler** [comment]
Yes - this is because remote storage (Blobs) have 10s of millisecond latency. If you serialize your requests (as in upload files sequentially using ```cp * /destdir```), then it will take (10ms * 3000 files / 1000) seconds to copy all files. The right solution here is therefore is to run operations concurrently. If you have 3000 files, copy them 100 by 100. It should give you much better throughput. You can accomplish this via a simple bash script, or using GNU Parallel, or a Python script to open files concurrently. 

Here is a very simple bash script to do it:
Say you have files named from file1 to file100;
```
cp file1* /destdir &
cp file2* /destdir &
cp file3* /destdir &
cp file4* /destdir &
cp file5* /destdir &
cp file6* /destdir &
cp file7* /destdir &
cp file8* /destdir &
cp file9* /destdir &
wait
```

**Comment by guysoft** [comment]
I tried with parallel -j 20. For 1500 files it took 1 minute (not fast enough for us).  As a zip it took 6 seconds. Also tried -j 200 and still took a mintue.

**Comment by guysoft** [comment]
I tried with parallel -j 20. For 1500 files it took 1 minute (not fast enough for us).  As a zip it took 6 seconds. Also tried -j 200 and still took a mintue.

I tried it with a different tool (will update comment in a few mins). So will try and report

**Comment by guysoft** [comment]
Hey, so I tried this but its still slow.

```
time parallel -j200 cp {} /srv/blobfuse ::: $(find /path/to/7000/files -type f)
...
real    0m36.666s
user    0m9.644s
sys     0m14.692s
```

Compared to:
```
time zip -qr /tmp/test.zip $(find /path/to/7000/files -type f) ; time cp /tmp/test.zip  /srv/blobfuse

real    0m5.336s
user    0m1.980s
sys     0m0.792s

real    0m1.004s
user    0m0.000s
sys     0m0.028s

```

50-200 seemed like the sweet spot, more went slower, lower was about the same

**Comment by seguler** [comment]
It looks very slow to me; both the zip upload and parallel upload. Do you have 3k or 7k files in total ?

Is your VM and storage account collocated in the same region ?

In my tests I can go up to 200-300 files per second on a DS14 VM. 

We also have a feature item to improve the small file performance by about at least 30% but it is still a few weeks away. Even then I don't think we can ever beat a single zip upload - this is valid for any program that talks to Blob storage.

**Comment by guysoft** [comment]
I have hundred of thousands. They come in batches of ~7000 per 'job'.
VM is in the same region in US east.
Its a 16 core machine,  I think A series. I can check.
Is there any way to benchmark this?

**Comment by seguler** [comment]
7000 / 36 seconds is right around 200 files per second, which I think is good. You may be able to achieve better by tweaking the following parameter (concurrent tcp connections) which is set to 20 at the moment: https://github.com/Azure/azure-storage-fuse/blob/master/blobfuse/blobfuse.cpp#L282

At this moment the biggest blocker for better performance is the fact that filesystem calls getattr for each file which results in a HEAD request to the service (about 3-10ms latency). This will be eliminated by use of an attribute cache which is currently in development. Until then, this may be the fastest you can get.

**Comment by densto88** [comment]
> 50-200 seemed like the sweet spot, more went slower, lower was about the same

Azure VM's and Disks each have both Throughput and IOPS limits that depend on the size of each. Larger VM Role Sizes will have higher overall limits and larger (premium storage based) Disks also have increased limits. By doing more IO in parallel to maximize throughput you're likely pushing up against the IOPS limits. If you're using standard storage you're capped out at 500 IOPS / 60MBps per disk. If you're trying to squeeze every bit of performance out of something like this you'll also need to be aware of the different types of caching and how throttling is applied to cached and uncached requests as well as the local temp disk.

Here's a good place to start:
[Azure VM Storage Performance and Throttling Demystify](https://blogs.technet.microsoft.com/xiangwu/2017/05/14/azure-vm-storage-performance-and-throttling-demystify/ )

And this one is a bit old but may be very useful still for more linux specific guidance:
[Azure Storage Secrets and Linux IO Optimizations](https://blogs.msdn.microsoft.com/igorpag/2014/10/23/azure-storage-secrets-and-linux-io-optimizations/)

**Comment by guysoft** [comment]
@Dennis Stone not the case because we also have self-hosted nfs on azure
which takes seconds, read above :)

**Comment by densto88** [comment]
@guysoft Sorry, I must have misunderstood something along the way, which part is not the case?

**Comment by seguler** [comment]
This is being improved in blobfuse 1.1 with the attribute cache feature. Attributes are now cached from the list operations, and the blobfuse is able to go up to 2K (small) Files per second read throughput as opposed to around 300 small files in blobfuse 1.0.
