### ISSUE TITLE
Streaming write does not working on SMB and very slow localy

### ISSUE THREAD

**Issue by xStin** [Azure/azure-storage-fuse#1030]
### Which version of blobfuse was used?
blobfuse2 version 2.0.1
blobfuse2 version 2.0.0.preview4

### Which OS distribution and version are you using?
Debian GNU/Linux 11 (bullseye)

### If relevant, please share your mount command.
blobfuse2 mount /opt/blobfuse/fuse_container/ --config-file=/opt/blobfuse/fuse_connection.yaml

### What was the issue encountered?
Stream write works with errors or very very slow
So, here root case

1. Samba config
![4  SMBconfig](https://user-images.githubusercontent.com/9377197/211838923-68fb4439-c92a-4740-8e78-0ca04d82568b.png)
2. Yaml
![2  yaml](https://user-images.githubusercontent.com/9377197/211920571-c1241564-c984-4df2-9fdb-31e067428e29.png)

3. Trying to copy items with 280Gb and 70 Mb
![8  Copy files](https://user-images.githubusercontent.com/9377197/211840194-4303d29c-15a7-488a-8bb0-772cc16eae8e.png)

I try do this on 2.0.4.preview4 version and have the same bug. Also I try to copy files with different size. Its not working with file larger than 100Mb

But, all of this test use Samba. Let's check without share

1. Copy 1Gb
![9  LocalCopy1Gb](https://user-images.githubusercontent.com/9377197/211844096-6c6a0c4d-8b29-4ba7-88d7-3a191e204f07.png)
2. After few minutes no one errors, but the speed critically slow down
![10 SpeedSlowDown](https://user-images.githubusercontent.com/9377197/211844284-ced49cd6-1269-4a68-8218-c2d9b06726b4.png)
3. Look into the folder via portal. Folder is busy
![11  PortalBusy](https://user-images.githubusercontent.com/9377197/211845048-2fcd484d-79d6-4d40-97de-e85d4093d7e2.png)

So, I wait around 10 miuntes. Speed approx. 800Kb/sec (I have 12 Gbit network throughput), Folder busy...
When I use file_cache then I have no problems

Just look into Zabbix
![12  Zabbix](https://user-images.githubusercontent.com/9377197/211847679-de5b30b3-60e9-408e-82d8-798788717286.png)

Do we have any proposal or maybe you need some logs. I can reproduce anytime
### Have you found a mitigation/solution?
No

**Comment by tasherif-msft** [comment]
Hi @xStin it appears your streaming config is using outdated parameters, this causes some of the values to be set to 0 and therefore pure streaming happens which will be EXTREMELY slow. The new parameters are now:
```
  block-size-mb: <for read only mode:: size of each block to be cached in memory while streaming (in MB). For read/write:: size of newly created blocks. Default - 0 MB>
  max-buffers: <total number of buffers to store blocks in. Default - 0 MB>
  buffer-size-mb: <size for each buffer. Default - 0>
  file-caching: <read/write mode file level caching or handle level caching. Default - false (handle level caching ON)>
```

so in your case you can have the following:

```
  block-size-mb: 1
  max-buffers: 1000
  buffer-size-mb: 4
  file-caching: true/false <<<<<<(this one is up to you)>>>>>
```

let me know if this improves your performance and resolves the issue.

**Comment by xStin** [comment]
Hi @tasherif-msft thank you for your reply. Yes this is help and solve my problem
About performance, yep, speed is up and depends on attribute values. Now I can make some experiments

Thanks a lot!
