### ISSUE TITLE
runtime error on "blobfuse2 mount all"

### ISSUE THREAD

**Issue by williamohara** [Azure/azure-storage-fuse#1032]
### Which version of blobfuse was used?
2

### Which OS distribution and version are you using?
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

running through WSL

### If relevant, please share your mount command.
blobfuse2 mount all /mnt/azstorage

### What was the issue encountered?
runtime error
```
panic: runtime error: index out of range [4] with length 4

goroutine 1 [running]:
github.com/Azure/azure-storage-fuse/v2/cmd.mountAllContainers(0xc00009e960, 0x2, 0x2, 0x0, 0x0, 0x7ffe7fbe3956, 0xe, 0x0, 0xe79982, 0x9)
        /mnt/vss/_work/1/s/azure-storage-fuse/cmd/mount_all.go:321 +0xf12
github.com/Azure/azure-storage-fuse/v2/cmd.processCommand(0x0, 0x0)
        /mnt/vss/_work/1/s/azure-storage-fuse/cmd/mount_all.go:180 +0x599
github.com/Azure/azure-storage-fuse/v2/cmd.glob..func9(0x149b920, 0xc00034b270, 0x1, 0x1, 0x0, 0x0)
        /mnt/vss/_work/1/s/azure-storage-fuse/cmd/mount_all.go:82 +0x9f
github.com/spf13/cobra.(*Command).execute(0x149b920, 0xc00034b250, 0x1, 0x1, 0x149b920, 0xc00034b250)
        /home/cloudtest/go/pkg/mod/github.com/gapra-msft/cobra@v1.4.1-0.20220411185530-5b83e8ba06dd/command.go:882 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x149c100, 0x3, 0x3, 0xc00040a7c0)
        /home/cloudtest/go/pkg/mod/github.com/gapra-msft/cobra@v1.4.1-0.20220411185530-5b83e8ba06dd/command.go:1000 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/cloudtest/go/pkg/mod/github.com/gapra-msft/cobra@v1.4.1-0.20220411185530-5b83e8ba06dd/command.go:928
github.com/Azure/azure-storage-fuse/v2/cmd.Execute(0xffffffff, 0xc000042118)
        /mnt/vss/_work/1/s/azure-storage-fuse/cmd/root.go:262 +0x8d
main.main()
        /mnt/vss/_work/1/s/azure-storage-fuse/main.go:45 +0x25
```

### Have you found a mitigation/solution?
I looked at the code and it seems that the logic is expecting there to be 5 cli parms when there is only 4 in my command here...
https://github.com/Azure/azure-storage-fuse/blob/main/cmd/mount_all.go#L321

So I added an innocuous param (for me at least) `--disable-version-check=true`  and it seems to work now. 

I would expect an error message of some kind if it is missing a required parm rather than a runtime error

**Comment by vibhansa-msft** [comment]
"blobfuse2 mount all /mnt/azstorage"
Mount all needs a config file containing the azure storage account configuration. If it's not provided, then you shall have correct environment variables exported for the same.
Also, in your mount command you do not have tmp-path set. Kindly use correct command syntax. We will look into doing a graceful termination in case required inputs are not provided.

**Comment by souravgupta-msft** [comment]
Thanks for reporting this issue. The fix has been merged and will be part of our next release.
