### ISSUE TITLE
How to use file-caching in stream mode instead of memory

### ISSUE THREAD

**Issue by xStin** [Azure/azure-storage-fuse#1033]
### Which version of blobfuse was used?
blobfuse2 2.0.1

### Which OS distribution and version are you using?
Debian GNU/Linux 11 (bullseye)

### What was the issue encountered?
According to comment https://github.com/Azure/azure-storage-fuse/issues/1030#issuecomment-1381071553, namely about "file-caching" I try turn on caching, but I don't understand how it's work
Let me explain background of issue. I have VM with few disks, one of them - NVMe, also VM has low RAM. When I use "file_cache" instead of "stream" I have speed around 200MB/sec and low RAM utilization. When I use stream mode - I have 50MB/sec and high memory utilization.
So, I want to use stream mode with file-caching on disk instead of memory and don't understand how to specify cache folder

**Comment by vibhansa-msft** [comment]
As of now streaming does not work with cache on disk. You can either use file-cache or streaming, as they are mutually exclusive.

**Comment by xStin** [comment]
Ok, thank you for your response
