### ISSUE TITLE
Libfuse::Start : Failed to init fuse

### ISSUE THREAD

**Issue by brosahay** [Azure/azure-storage-fuse#1035]
### Which version of blobfuse was used?
    $ blobfuse2 -V
    blobfuse2 version 2.0.1
    $ fusermount -V
    fusermount3 version: 3.9.0

### Which OS distribution and version are you using?
    Linux 5.15.0-1031-azure #38~20.04.1-Ubuntu SMP Mon Jan 9 18:23:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=20.04
    DISTRIB_CODENAME=focal
    DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

### If relevant, please share your mount command.
    export AZURE_STORAGE_ACCOUNT=<>
    export AZURE_STORAGE_AUTH_TYPE=Key
    export AZURE_STORAGE_ACCESS_KEY=<>
    /usr/bin/blobfuse2 mount /home/AzureUser/mntblobfuse --tmp-path=/home/AzureUser/tmpblobfuse --config-file=/home/AzureUser/azure-storage-fuse/blobfuse2.yaml --log-level=LOG_DEBUG

```yaml
foreground: 'false'

read-only: false
allow-other: false
nonempty: true

dynamic-profile: false

components:
  - libfuse

libfuse:
  default-permission: 0644
```

### What was the issue encountered?
    Mount of the storage blob quietly fails

### Have you found a mitigation/solution?
    Using the blobfuse instead of the updated version

### Please share logs if available.
```log
Jan 18 14:28:20 localhost blobfuse2[79369]: LOG_CRIT [mount.go (364)]: Starting Blobfuse2 Mount : 2.0.1 on [Ubuntu 20.04.5 LTS]
Jan 18 14:28:20 localhost blobfuse2[79369]: LOG_CRIT [mount.go (365)]: Logging level set to : LOG_DEBUG
Jan 18 14:28:20 localhost blobfuse2[79369]: LOG_TRACE [libfuse.go (220)]: Libfuse::Configure : libfuse
Jan 18 14:28:20 localhost blobfuse2[79369]: LOG_INFO [libfuse.go (260)]: Libfuse::Configure : read-only false, allow-other false, default-perm 420, entry-timeout 120, attr-time 120, negative-timeout 120, ignore-open-flags: false, nonempty true
Jan 18 14:28:20 localhost blobfuse2[79369]: LOG_INFO [mount.go (372)]: mount: Mounting blobfuse2 on /home/AzureUser/mntblobfuse
Jan 18 14:28:20 localhost blobfuse2[79369]: LOG_DEBUG [mount.go (390)]: mount: foreground disabled, child = false
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_CRIT [mount.go (364)]: Starting Blobfuse2 Mount : 2.0.1 on [Ubuntu 20.04.5 LTS]
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_CRIT [mount.go (365)]: Logging level set to : LOG_DEBUG
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_TRACE [libfuse.go (220)]: Libfuse::Configure : libfuse
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_INFO [libfuse.go (260)]: Libfuse::Configure : read-only false, allow-other false, default-perm 420, entry-timeout 120, attr-time 120, negative-timeout 120, ignore-open-flags: false, nonempty true
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_INFO [mount.go (372)]: mount: Mounting blobfuse2 on /home/AzureUser/mntblobfuse
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_DEBUG [mount.go (390)]: mount: foreground disabled, child = true
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_DEBUG [mount.go (456)]: Mount::runPipeline : blobfuse2 pid = 79375, transfer pipe = /tmp/transferPipe_79375, polling pipe = /tmp/pollPipe_79375
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_TRACE [libfuse.go (136)]: Libfuse::Start : Starting component libfuse
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_TRACE [libfuse_handler.go (116)]: Libfuse::initFuse : Initializing FUSE3
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_TRACE [libfuse_handler.go (159)]: Libfuse::initFuse : Registering fuse callbacks
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_TRACE [libfuse_handler.go (163)]: Libfuse::initFuse : Populating fuse arguments
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_TRACE [libfuse_handler.go (187)]: Libfuse::populateFuseArgs
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : blobfuse2
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : /home/AzureUser/mntblobfuse
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -o
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : entry_timeout=120,attr_timeout=120,negative_timeout=120,nonempty
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -f
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -ofsname=blobfuse2
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -okernel_cache
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_INFO [libfuse_handler.go (175)]: Libfuse::initFuse : Mounting with fuse3 library
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_ERR [libfuse_handler.go (178)]: Libfuse::initFuse : failed to mount fuse
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_ERR [libfuse.go (150)]: Libfuse::Start : Failed to init fuse [failed to mount fuse]
Jan 18 14:28:21 localhost blobfuse2[79375]: LOG_ERR [mount.go (462)]: mount: error unable to start pipeline [failed to mount fuse]
```

**Comment by vibhansa-msft** [comment]
I see two issues in your pipeline.
You have "allow_other" flag set to true, this works only if libfuse has been configured with allow_other. Check your "/etc/fuse.conf" file and ensure allow_other is enabled there as well. This is just one time operation and no reboots required.
Another issue with pipeline is it just has "libfuse" component set in pipeline which is not correct. Kindly check our sample config files in github and add other required components.

**Comment by brosahay** [comment]
> I see two issues in your pipeline.
> You have "allow_other" flag set to true, this works only if libfuse has been configured with allow_other. Check your "/etc/fuse.conf" file and ensure allow_other is enabled there as well. This is just one time operation and no reboots required.
> Another issue with pipeline is it just has "libfuse" component set in pipeline which is not correct. Kindly check our sample config files in github and add other required components.

What are the must-have components in the pipeline?

Additionally, why should I have allow_other enabled? I do not want to extend the permission to other users on the system.

Attached below is that command on blob fuse which is working as a `.service` file.
```sh
ExecStart=/usr/bin/blobfuse ${BlobMountingPoint} --container-name=${ContainerName} --tmp-path=${BlobTmp} --use-https=${BlobUseHttps} --file-cache-timeout-in-seconds=${BlobFileCacheTimeOutInSeconds} --log-level=${BlobLogLevel} --use-attr-cache=${BlobUseAttrCache} --use-attr-cache=${BlobUseAttrCache} -o attr_timeout=${attr_timeout} -o entry_timeout=${entry_timeout} -o negative_timeout=${negative_timeout}
```

**Comment by vibhansa-msft** [comment]
Yes if you do not wish other users to have access to mount point then you can keep it allow_other=false and in that case you can skip updating /etc/fuse.conf file. However, even if you update that your blobfuse config will not enable that feature on your mount so later if you wish to enable it will be easier if you have that change ready.
For minimal components that you need is "libfuse" and "azstorage".  file-cache and attr-cache are recommended to have but then it depends on your use-case. If you are just trying out blobfuse for the first time I would request you to have all 4 of these and be careful as order is important here. Kindly refer [this](https://github.com/Azure/azure-storage-fuse/blob/main/sampleFileCacheConfig.yaml) file.

**Comment by vibhansa-msft** [comment]
in case you wish to enable "#user_allow_other" in /etc/fuse.conf. just remove '#' in the start of this line.

**Comment by brosahay** [comment]
I tried following the configuration file, still same error I am getting. I included all the options that have been mentioned on the file.

```yaml
# Daemon configuration
foreground: 'false'

# Common configurations
read-only: false
allow-other: false
nonempty: true

# Dynamic profiler related configuration. This helps to root-cause high memory/cpu usage related issues.
dynamic-profile: false

# Pipeline configuration. Choose components to be engaged. The order below is the priority order that needs to be followed.
components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

# Libfuse configuration
libfuse:
  default-permission: 0644
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /home/AzureUser/tmpblobfuse
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: <>
  account-key: <>
  endpoint: https://<account-name>.blob.core.windows.net
  mode: key
  container: <>
```

`blobfuse2 mount /home/AzureUser/mntblobfuse --config-file=/home/AzureUser/azure-storage-fuse/blobfuse2.yaml --log-level=LOG_DEBUG`

**Comment by brosahay** [comment]
UPDATE: `nonempty: true` is causing the issue with the pipeline, the mount location currently is empty, but might not be empty while I bring up the server after maintenance.

**Comment by vibhansa-msft** [comment]
Folder on which you try to mount shall be empty. Using nonempty flag you can mount on a non-empty directory but in past we have seen customers having wrong expectations with that. If you have anything in the folder before you mount those files will never be synced or updated by blobfuse. Those will be totally invisible to blobfuse and hence we suggest to always mount on a empty folder. This flag was given just have a compatibility with legacy code but not recommended.

**Comment by vibhansa-msft** [comment]
Also, any flag which is set to false you can remove from your config file as default is false for all flags. It will just help you make your config file smaller and easier to manage.
