### ISSUE TITLE
blobfuse2: error while loading shared libraries: libfuse3.so.3

### ISSUE THREAD

**Issue by jmjclaessen** [Azure/azure-storage-fuse#1039]
### Which version of blobfuse was used?
blobfuse2-2.0.1-1.x86_64

### Which OS distribution and version are you using?
Red Hat Enterprise Linux 8.4 , Linux 4.18.0-305.72.1.el8_4.x86_64

### If relevant, please share your mount command.
Nothing mounted yet

### What was the issue encountered?
I installed blobfuse2, using yum install blobfuse2. When starting blobfuse2 i get blobfuse2: error while loading shared libraries: libfuse3.so.3: cannot open shared object file: No such file or directory. I ran yum install libfuse3.so.3 it installed fuse3-libs-3.2.1-12.el8.i686 and glibc-2.28-151. I see the same error for Ubuntu but are running RHEL 8.4, on a Azure Linux vm. Repositories are the standard Azure repositories.

### Have you found a mitigation/solution?
No

### Please share logs if available.
No info in logs

**Comment by vibhansa-msft** [comment]
Kindly install "libfuse3".

**Comment by vibhansa-msft** [comment]
I went through your comments again and it appears you tried installing libfuse3 already. Can you run "fusermount3 --v" command and share the output. If libfuse3 is properly installed this shall return 3.x version.

**Comment by jmjclaessen** [comment]
Hi the result of fusermount3 --v is fusermount3 version: 3.2.1

**Comment by jmjclaessen** [comment]
Hi i solved the issue, the first time i ran yum install fuse3-libs it installed fuse3-libs-3.2.1-12.el8.i686, the second time i ran it it installed fuse3-libs-3.2.1-12.el8.x86_64.rpm, thereafter it works, so issue is solved. So default the 32 bit version is installed secondly the 64 bit version is added.

[root@vm-0001352-0007 ~]# yum install fuse3-libs
Repository packages-microsoft-com-prod is listed more than once in the configuration
Last metadata expiration check: 15:38:09 ago on Tue 24 Jan 2023 08:41:49 AM MST.
Package fuse3-libs-3.2.1-12.el8.i686 is already installed.
Dependencies resolved.
=============================================================================================================================================================================================================================================================
 Package                                                Architecture                                       Version                                                  Repository                                                                          Size
=============================================================================================================================================================================================================================================================
Installing:
 fuse3-libs                                             x86_64                                             3.2.1-12.el8                                             rhel-8-for-x86_64-baseos-eus-rhui-rpms                                              94 k

Transaction Summary
=============================================================================================================================================================================================================================================================
Install  1 Package

Total download size: 94 k
Installed size: 279 k
Is this ok [y/N]: y
Downloading Packages:
fuse3-libs-3.2.1-12.el8.x86_64.rpm                                                                                                                                                                                           328 kB/s |  94 kB     00:00
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                                        326 kB/s |  94 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                                                                     1/1
  Installing       : fuse3-libs-3.2.1-12.el8.x86_64                                                                                                                                                                                                      1/1
  Running scriptlet: fuse3-libs-3.2.1-12.el8.x86_64                                                                                                                                                                                                      1/1
  Verifying        : fuse3-libs-3.2.1-12.el8.x86_64                                                                                                                                                                                                      1/1
Installed products updated.

Installed:
  fuse3-libs-3.2.1-12.el8.x86_64

Complete!
[root@vm-0001352-0007 ~]# blobfuse2
Error: missing command options

Did you mean this?
        blobfuse2 mount

Run 'blobfuse2 --help' for usage

**Comment by vibhansa-msft** [comment]
fuse3-libs is generally needed only when you try to build the code base of blobfuse. If you are trying to only execute the pre-built binary, just installing "fuse3" shall be good enough. Closing this as issue is resolved.
