### ISSUE TITLE
Cannot create directory Input/output error

### ISSUE THREAD

**Issue by olegshv** [Azure/azure-storage-fuse#1041]
### Which version of blobfuse was used?
blobfuse2 version 2.0.0-preview.3

### Which OS distribution and version are you using?
Debian GNU/Linux 11 (bullseye)

### If relevant, please share your mount command.
blobfuse2 mount /opt/blobfuse/fuse_container/ --config-file=/opt/blobfuse/fuse_connection.yaml

### What was the issue encountered?
Linux: mkdir: cannot create directory ‘/opt/blobfuse/fuse_container/TestFolder/test01’: Input/output error (command from root)
Windows: 
![image](https://user-images.githubusercontent.com/9905160/214667457-a72dcc52-8d21-440a-81c2-9911cdbe8d52.png)

1.Samba config
![image](https://user-images.githubusercontent.com/9905160/214668297-b6d711f4-4848-4da4-8596-0c0a253c67fc.png)
2.Yaml
![image](https://user-images.githubusercontent.com/9905160/214668700-8b5b73e1-1a6c-46f1-9053-a97bed44745a.png)

### Have you found a mitigation/solution?
No, but creation was working.

### Please share logs if available.
![image](https://user-images.githubusercontent.com/9905160/214670483-473a7dc1-9f06-4c71-9680-4a7bd2f18c07.png)

**Comment by vibhansa-msft** [comment]
Can you remove "tier: cool" configuration from your config file and try again. As per the error posted above server is failing to set tier as "cool" for directories. Can you also confirm your account is HNS or not.

**Comment by olegshv** [comment]
Thank you very much! It's working without "tier: cool" in yaml. And yes, we use HNS.

**Comment by vibhansa-msft** [comment]
As you account is HNS, add "type: adls" in your config file under "azstorage" section. "tier: cool" shall also work fine once this is added.

**Comment by vibhansa-msft** [comment]
I have verified it from my end, for HNS account specifying "type: adls" is must and with that "tier" is also working fine. You are hitting the error as you have mounted HNS account as a non-adls account in blobfuse and trying to create directory with tier set which is not supported on backend.

**Comment by olegshv** [comment]
It's interesting, but when I use type: adls, I have an error:
failed to mount : failed to authenticate credentials for azstorage
![image](https://user-images.githubusercontent.com/9905160/215047865-d1a0b4b3-dcc3-4c2a-8578-eb719204e493.png)
![image](https://user-images.githubusercontent.com/9905160/215047999-078bbee0-11cb-4965-bfba-9b5325ef022a.png)

**Comment by vibhansa-msft** [comment]
Can you share latest config again after the changes.

**Comment by vibhansa-msft** [comment]
For ADLS endpoint shall come as *.dfs.core.windows.net. Remove "endpoint" config from your config file as its still pointing to blob endpoint which is not correct. You can let blobfuse auto create the endpoints unless you are using private endpoints.

**Comment by olegshv** [comment]
With this config it's mounting, but now we have "Permission denied" problem from linux and windows servers, from blobfuse server, all ok.
![image](https://user-images.githubusercontent.com/9905160/215067171-ed5642a2-5917-47f3-8fe5-932daad6032a.png)
![image](https://user-images.githubusercontent.com/9905160/215067259-6c57cbbb-7241-4889-8519-ee4282ff828b.png)
![image](https://user-images.githubusercontent.com/9905160/215068071-b969a089-115a-44c7-92b2-6c9af8266691.png)

We can enter into the container, but not in folders. I have checked samba config, and I have all permission.

**Comment by vibhansa-msft** [comment]
On windows it might not work directly unless you setup SMB for that folder or you are using WSL2.
In case of linux, the user who mounts shall have full access. If you mount using "root" other user might not have access to folder/files, depending upon the ACL set at blob and directory level in your storage account.  You can check the permissions to file/folder using "ls -l <mount path>" and validate you are accessing it correctly or not.

**Comment by olegshv** [comment]
Yes, it was ACL, now all working. Previously we mounted non-adls account and there was no any problems (if I understood you correctly).

**Comment by vibhansa-msft** [comment]
In case of non-HNS account, by default permissions are 755 and if user has given "allow_other" cli option then it will be 777. In case of HNS account there are no default permissions, it always what user has set as ACL permissions on the blob or folder.
For HNS accounts, if you wish other users to have access to your mounted files, you need to set correct permissions on the storage via portal or other means.
