### ISSUE TITLE
Blobfuse2 failed to connect to private endpoint in adls connection type but works in block type.

### ISSUE THREAD

**Issue by kostinalexey** [Azure/azure-storage-fuse#1042]
### Which version of blobfuse was used?
blobfuse2 version 2.0.1

### Which OS distribution and version are you using?
Ubuntu 20.04.5 LTS

### If relevant, please share your mount command.
blobfuse2 mount azure_data --config-file=./fuse2_conf4.yaml
blobfuse2 mount azure_data --config-file ./fuse2_conf4_block.yaml

### What was the issue encountered?
The blob storage with hierarchical namespace can be mounted with type "block"
![image](https://user-images.githubusercontent.com/16543334/214928994-7e55406f-19ac-4c4a-b99d-f5173754563c.png)
But no directories visible

With type adls mount fails completely
![image](https://user-images.githubusercontent.com/16543334/214929844-ba829629-d089-4b1c-91f7-3c9c341a4616.png)

blobfuse v1 mounts this without problem and shows directory too
![image](https://user-images.githubusercontent.com/16543334/214931741-3665775c-4120-4aef-9255-98533764d0f0.png)

Storage account properties
![image](https://user-images.githubusercontent.com/16543334/214932193-9d6edf62-3759-4adb-a764-e20a22fdc2c6.png)

Networking for the storage account
![image](https://user-images.githubusercontent.com/16543334/214932391-cb6ff998-c0c8-476a-93a7-78745d7c1778.png)

![image](https://user-images.githubusercontent.com/16543334/214932561-02b9bbd2-6544-4b77-8ba5-06f5c3fdc307.png)

If I enable public access for my VNET in Networking (firewall and virtual networks), then mount with adls type starts to work. But this is not a suitable solution because we need to make all work through the private endpoint.

### Have you found a mitigation/solution?
No

**Comment by kostinalexey** [comment]
Redacted log file when mount failed in adls
[blobfuse2.log](https://github.com/Azure/azure-storage-fuse/files/10512990/blobfuse2.log)

**Comment by jcbane** [comment]
I'm experiencing the same issue

**Comment by vibhansa-msft** [comment]
"endpoint" under "azstorage" section in your config-file is the place to define private endpoints. I see in your config its pointing to public cloud endpoint "*.blob.core.windows.net" only in both adls and non-adls cases. If your accounts are not on private endpoints, you can skip putting that configuration in config-file as adls and non-adls needs different endpoints which blobfuse2 can auto configure. In case you are using private-endpoints kindly put the correct endpoint url in that config.
Also, to your question on directory no visible in non-adls account. FNS account do not have a concept of a physical directory and to simulate that blobfuse expects a special 0 byte blob with directory name (directory stub) to exist. If its not there in your storage account you need to put "virtual-directory: true" config in your "azstorage" section of config file.

**Comment by kostinalexey** [comment]
Thanks for looking into this. I was watching this video https://www.youtube.com/watch?v=57ZwdztCx2w
which explains how DNS works in Azure and it seems that using https://opt4.blob.core.windows.net/ as endpoint should be correct always. The "magic" of switching between private and public endpoints happening on a DNS server
In my VM the resolution seems to be correct:
![image](https://user-images.githubusercontent.com/16543334/215050295-f60f7f61-0d14-4587-901c-a28ff25253fa.png)
When you say "put the correct endpoint url" I am a bit confused now. I think it is correct.

**Comment by vibhansa-msft** [comment]
Can you try putting ".privatelink" url in the endpoint and check if it works.

**Comment by kostinalexey** [comment]
![image](https://user-images.githubusercontent.com/16543334/215071123-bb32d06e-80d8-4fea-921e-4820dcb3245b.png)
![image](https://user-images.githubusercontent.com/16543334/215071325-dff606ba-371a-4693-99e7-204866442790.png)
[blobfuse2.log](https://github.com/Azure/azure-storage-fuse/files/10518170/blobfuse2.log)

**Comment by vibhansa-msft** [comment]
Enable log_debug and share the log file to check if we get some error details from backend.
Also, can you try connecting to your storage account through other means then blobfuse. Just to make sure there is no obvious connection related issue here. You can try with azcli or postman or something.

**Comment by kostinalexey** [comment]
I just found the root of the problem. It seems that in ADLS mode Blobfuse2 need 2 endpoints: one for blob service (https://opt4.blob.core.windows.net/) and another for data lake storage (https://opt4.dfs.core.windows.net/) I have create a second private endpoint for DLS and all works now. It seems that endpoint URL in config file is not properly appreciated and gets modified by Blobfuse2. Even if I change the endpoint in config to https://opt4.dfs.core.windows.net/, in the logs I can see that Blobfuse2 still uses blob endpoint. This probably needs to be documented somehow or fixed to use only one endpoint.

**Comment by kostinalexey** [comment]
The log_debug was always enabled (see the config) and blobfuse2.log files were attached to the posts.
Here is the log file for the case when 2 private endponts are created and all seems to work. You can see that 2 endpoint URLs are present in the log
[blobfuse2.log](https://github.com/Azure/azure-storage-fuse/files/10518413/blobfuse2.log)

**Comment by vibhansa-msft** [comment]
Yes, your observation is correct. If user provides a blob endpoint in config, blobfuse will autocorrect it to dfs endpoint if account type was set to ADLS. 
You are also correct that blobfuse needs both dfs and blob endpoint. This is because not all operations are done over dfs endpoint. All upload/downloads are done on blob endpoint whille list and getproperties are done over dfs endpoints. This is to ensure cross protocol compatibility so that data can be read through any other means as well. This is a design choice that we made and for this reason you will need to expose your blob endpoint as well over private link.

**Comment by vibhansa-msft** [comment]
We need to improve our documentation in this regard. Thanks for bringing this up.

**Comment by vibhansa-msft** [comment]
If you issue is resolved kindly close this bug report. I will update the wiki regarding private endpoints.
