### ISSUE TITLE
No access to docker image in container registry

### ISSUE THREAD

**Issue by inno-steffg** [Azure/azure-storage-fuse#1048]
I've tried to use the prebuilt blobfuse2 docker container, mentioned in your [Wiki](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Docker-Container#docker-command-to-pull-pre-built-container-image).
The command was:
`docker pull blobfuse2containers.azurecr.io/azure-blobfuse2.2.0.0-preview.4`
but it breaks with an "unauthorized" error message.
It seems, that the reference image registry blobfuse2containers.azurecr.io requires authentication.

How to get access?

More information:
- Docker Desktop for Windows v4.16.3
- Windows 10
- Access via company HTTP proxy

![grafik](https://user-images.githubusercontent.com/5442481/215987021-ee670d52-4aaa-4d61-b599-c5bf923cd4a5.png)

**Comment by vibhansa-msft** [comment]
There was some policy change at global level. I have enabled anonymous access again; can you retry and update here.

**Comment by inno-steffg** [comment]
Works now (I guessed the image-name): `docker pull blobfuse2containers.azurecr.io/azure-blobfuse2.2.0.1`

Still "unauthorized": `docker pull blobfuse2containers.azurecr.io/azure-blobfuse2.2.0.0-preview.4`

**Comment by vibhansa-msft** [comment]
Yes preview.4 image is taken off after our GA.
