### ISSUE TITLE
provide a standalone blobfuse binary

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#105]
Is there any compile parameters that could make blobfuse use static lib, if I use official installation way, I will get following error:
```
# bin/blobfuse
bin/blobfuse: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory

# ./blobfuse
./blobfuse: error while loading shared libraries: libgnutls.so.30: cannot open shared object file: No such file or directory
```
Such a blobfuse binary using static lib would be quite useful in container.

**Comment by andyzhangx** [comment]
@seguler this is blocking issue in the development of k8s flex vol driver, we use a restricted `hyperkube`  image to invoke blobfuse, we cannot install libcurl or libgnutls modules in that image as it's a standard k8s image, make blobfuse use  static lib is a must for k8s flex vol driver.

**Comment by seguler** [comment]
Closing this. We were able to build blobfuse on kyberkube image by installing libcurl-gnutls-dev package.

**Comment by pareshverma91** [comment]
+1
We are trying to azure blob fuse on CoreOs, and the os is missing gnutls libraries. Having a static binary would be helpful for us too.

**Comment by andyzhangx** [comment]
If we could make a standalone blobfuse binary, then the deployment on a lot of VMs would be much easier. @seguler Is there still any possiblity to do this?

**Comment by seguler** [comment]
@asorrin-msft for advice on this.

I don't know - but the licenses disallow us to statically link with OpenSSL. As I understand we can't package the gnutls into our static library either.

@andyzhangx - I don't exactly understand why it would be easier for you. Can you not simply install blobfuse from the package repositories ? Not sure why a single binary is easier for you.

@pareshverma91 - are you saying GnuTLS is not available for CoreOS at all ? Or is it just a matter of the missing versions? Have you tried building blobfuse from source code ?

**Comment by andyzhangx** [comment]
@seguler do you have blobfuse standalone binary for Ubuntu 16.04, so that I could run a k8s daemonset to    put that binary on all agent nodes. `simply install blobfuse from the package repositories`  is not a good way if we have dozens of agent nodes.

**Comment by seguler** [comment]
Single binary is not possible due to the dependency and their licenses, therefore closing this

**Comment by pareshverma91** [comment]
FYI, we tried building static binary for this, and had to resort to using musl c library and were able to make some progress. However, we decided to stop progressing in that direction, and instead started running blobfuse in a docker container, sharing the mount point created in the container with the host or with other containers.

**Comment by andyzhangx** [comment]
@pareshverma91 that should be the way how CSI driver works, I plan to write such a CSI driver for blobfuse when I completed the alpha version for azure disk CSI driver.
