### ISSUE TITLE
Mount all option not working with shell script in fstab

### ISSUE THREAD

**Issue by jmjclaessen** [Azure/azure-storage-fuse#1053]
### Which version of blobfuse was used?
blobfuse2 version 2.0.1

### Which OS distribution and version are you using?
Red Hat Enterprise Linux 8.4 Linux 4.18.0-305.72.1.el8_4.x86_64

### If relevant, please share your mount command.
fstab:
/blob/config/blobfuse2.sh /blob/sftp fuse defaults,_netdev,--config-file=/blob/config/config.yaml 0 0
shell:
blobfuse2 mount all /blob/sftp --config-file=/blob/config/config.yaml

### What was the issue encountered?
Mount all option not working 

### Have you found a mitigation/solution?
No

### Please share logs if available.
I am trying to use the mount all option, to mount several containers. Because of the option mount all i'am using a shell script: blobfuse2 mount all /blob/sftp --config-file=/blob/config/config.yaml and added /blob/config/blobfuse2.sh /blob/sftp fuse defaults,_netdev,--config-file=/blob/config/config.yaml 0 0 to the fstab. 
When i run the command: blobfuse2 mount all /blob/sftp --config-file=/blob/config/config.yaml all 8 containers are mounted. If i use the mount -a option i get error : Failed to mount container 
In the blobfuse2.log i cannot find an error, see attachment.

If i mount the individual containers in the fstab:
#/blob/config/blobfuse3.sh /blob/sftp/carlo fuse defaults,_netdev,--config-file=/blob/config/configcarlo.yaml 0 0
#/blob/config/blobfuse4.sh /blob/sftp/nxf71138 fuse defaults,_netdev,--config-file=/blob/config/confignxf71138.yaml 0 0
#/blob/config/blobfuse5.sh /blob/sftp/tdc11 fuse defaults,_netdev,--config-file=/blob/config/configtdc11.yaml 0 0
and individual shell scripts they get mounted without any error: 
blobfuse2 mount /blob/sftp/carlo --config-file=/blob/config/configcarlo.yaml
blobfuse2 mount /blob/sftp/nxf71138 --config-file=/blob/config/confignxf71138.yaml
blobfuse2 mount /blob/sftp/tdc11 --config-file=/blob/config/configtdc11

[blobfuse2 log.txt](https://github.com/Azure/azure-storage-fuse/files/10675276/blobfuse2.log.txt)
![Mount all](https://user-images.githubusercontent.com/123465921/217253544-caf44197-8e1b-430f-8c91-fdfb2bff698d.JPG)

**Comment by vibhansa-msft** [comment]
If I understand correctly, you are saying using /etc/fstab to run a script which does mount-all fails, but if you manually execute mount all command it works fine. Can you execute the script manually and see if that works fine or not. Only difference I see here is /etc/fstab will be running under "root" user and may be there are some permission related issues on the mount path or config file. Can you share your config file as well.

**Comment by jmjclaessen** [comment]
Yoy are correct if i copy the command in the fstab: /blob/config/blobfuse2.sh /blob/sftp fuse defaults,_netdev,--config-file=/blob/config/config.yaml 0 0 and run it it works fine 9 containers are mounted. When i run mount -a (with the command in the fstab it fails) with failed to mount container. I run the command also as root. see attachment for the config.yaml file
[config yaml.txt](https://github.com/Azure/azure-storage-fuse/files/10675916/config.yaml.txt)

**Comment by vibhansa-msft** [comment]
I tried to reproduce this locally but I am not hitting it.

```
/azure-storage-fuse$ sudo mount -a
Mounting container : test-cnt-ubn-20 to path  /usr/blob_mnt/test-cnt-ubn-20
Mounting container : test-cnt-ubn-20-msi to path  /usr/blob_mnt/test-cnt-ubn-20-msi
Mounting container : test-cnt-ubn-22 to path  /usr/blob_mnt/test-cnt-ubn-22
3 of 3 containers were successfully mounted

/azure-storage-fuse$ ./blobfuse2 list
1 : /usr/blob_mnt/test-cnt-ubn-20
2 : /usr/blob_mnt/test-cnt-ubn-20-msi
3 : /usr/blob_mnt/test-cnt-ubn-22
```

**Comment by vibhansa-msft** [comment]
Can you validate that shell script that you run, mount path and temp cache path have all the required permissions. May be just set all these paths to 777 once and try.

**Comment by jmjclaessen** [comment]
Permissions mount path and temp cache all set to 777, still the same error, also i cannot find any error in any logfile, why mount is failing

**Comment by vibhansa-msft** [comment]
When you run the shell script manually then it works, which points to some sort of access or privilege issue on why it's not working with /etc/fstab. Can you try running the script with and without sudo and see if you observe any difference.

**Comment by jmjclaessen** [comment]
mount -a option can only be used by root or with root priviliges

**Comment by jmjclaessen** [comment]
Digging through several logfiles i managed to get the below error, so somewhere i get a protocol error 
[FAILED] Failed to mount /blob/sftp.
See 'systemctl status blob-sftp.mount' for details.

systemctl status blob-sftp.mount
● blob-sftp.mount - /blob/sftp
   Loaded: loaded (/etc/fstab; generated)
   Active: failed (Result: protocol) since Mon 2023-02-13 07:13:14 MST; 1min 45s ago
    Where: /blob/sftp
     What: /blob/config/blobfuse2.sh
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)


[root@vm-0001352-0007 config]# ./blobfuse2.sh
Mounting container : carlo to path  /blob/sftp/carlo

Mounting container : ey201 to path  /blob/sftp/ey201

Mounting container : hans to path  /blob/sftp/hans

Mounting container : nxf71138 to path  /blob/sftp/nxf71138

Mounting container : spil to path  /blob/sftp/spil

Mounting container : tdc11 to path  /blob/sftp/tdc11

Mounting container : test to path  /blob/sftp/test

Mounting container : asekht to path  /blob/sftp/asekht

8 of 8 containers were successfully mounted
[root@vm-0001352-0007 config]#
[root@vm-0001352-0007 config]#
[root@vm-0001352-0007 config]# systemctl status blob-sftp.mount
● blob-sftp.mount - /blob/sftp
   Loaded: loaded (/etc/fstab; generated)
   Active: failed (Result: protocol) since Mon 2023-02-13 07:13:14 MST; 6min ago
    Where: /blob/sftp
     What: /blob/config/blobfuse2.sh
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)

Feb 13 07:13:14 vm-0001352-0007 mount[1721]: Mounting container : carlo to path  /blob/sftp/carlo
Feb 13 07:13:14 vm-0001352-0007 mount[1721]: Failed to mount container carlo :
Feb 13 07:13:14 vm-0001352-0007 mount[1721]: Mounting container : ey201 to path  /blob/sftp/ey201
Feb 13 07:13:14 vm-0001352-0007 mount[1721]: Failed to mount container ey201 :
Feb 13 07:13:14 vm-0001352-0007 mount[1721]: Mounting container : hans to path  /blob/sftp/hans
Feb 13 07:13:14 vm-0001352-0007 mount[1721]: Failed to mount container hans :
Feb 13 07:13:14 vm-0001352-0007 mount[1721]: 0 of 8 containers were successfully mounted
Feb 13 07:13:14 vm-0001352-0007 systemd[1]: blob-sftp.mount: Mount process finished, but there is no mount.
Feb 13 07:13:14 vm-0001352-0007 systemd[1]: blob-sftp.mount: Failed with result 'protocol'.
Feb 13 07:13:14 vm-0001352-0007 systemd[1]: Failed to mount /blob/sftp.

**Comment by vibhansa-msft** [comment]
Even in case of successful mount its showing the same result:
"systemctl status blob-sftp.mount
● blob-sftp.mount - /blob/sftp
Loaded: loaded (/etc/fstab; generated)
Active: failed (Result: protocol) s"

**Comment by vibhansa-msft** [comment]
Is it resolved for you or still hitting? Any update or learning you wish to share.

**Comment by jmjclaessen** [comment]
I 'am still having the issue trying to find an error or something, but cannot find it anywhere, also blobfuse2.log and blobfuse2-rest.log don't give an error. To solve the issue i need to know what is wrong. As a test a deployed a new vm and configured it with blobfuse, but still get the same error. Is there a specifics log i need to check i already have logging log_debug and sdk-trace: true enabled.

**Comment by vibhansa-msft** [comment]
I was trying this thing out yesterday in my local environment and I was not able to run 'mount all' from fstab as well. While the same script when executed manually works fine. I believe this has something to do with the 'mount all' trying to do a execute process on a new shell for every mount. I was not able to see any logs from the individual mounts and that points to the fact that it never got executed. Not able to figure out anything on the linux documentation on whether from fstab this kind of workflow is allowed or not. Have some other idea which I need to explore before suggesting it to you.

**Comment by vibhansa-msft** [comment]
I see this has something to do with privillages. When we mention a script in /etc/fstab we use "sudo mount -a" to execute that script. From the script if we just run "blobfuse2' command its not running under the sudo so modifying the script to have "sudo blobfuse2 mount all ......." works well and I am able to mount with fstab now. Can you validate this solution works well for you as well.

**Comment by jmjclaessen** [comment]
Adding  "sudo mount -a" solves the issue
