### ISSUE TITLE
Can operarte small size data from blobfuse v1 mount point, but can't for large size file

### ISSUE THREAD

**Issue by huanghaiqing1** [Azure/azure-storage-fuse#1056]
### Which version of blobfuse was used?
blobfuse/focal,now 1.4.5 amd64 [installed]

### Which OS distribution and version are you using?
Ubuntu 20.04.4 LTS

### If relevant, please share your mount command.
blobfuse ~/${a[2]}.container.$TIMESTAMP --tmp-path=/tmp/ramdisk.$TIMESTAMP/blobfusetmp.$TIMESTAMP --config-file=$Azure_cfg_PATH

blobfuse /HPCC/$5_$containerName --log-level=LOG_DEBUG --tmp-path=/tmp/ramdisk --config-file=$Azure_cfg_PATH --file-cache-timeout-in-seconds=0 --max-concurrency=20 --invalidate-on-sync=true -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o nonempty -o rw  

### What was the issue encountered?
It's ok to upload/download small size file, but failed for upload/download large size file. like a 3GB size iso file upload/download.
The error info from syslog:
Feb 09 03:32:27 cn-iris02.aptivchina.partner.onmschina.cn blobfuse[11737]: get_chunk_to_stream_async failure in download_blob_to_file.  container = hhq, blob = debian-11.3.0-amd64-DVD-1.iso1, destPath = /tmp/ramdisk/root/debian-11.3.0-amd64-DVD-1.iso1, offset = 1565471544, range = 193586791.
Feb 09 03:32:27 cn-iris02.aptivchina.partner.onmschina.cn blobfuse[11737]:  ==> REQUEST/RESPONSE :: GET https://bmwtestdata.blob.core.chinacloudapi.cn/hhq/debian-11.3.0-amd64-DVD-1.iso1?se=2023-02-10T00%3A00Z&sp=racwdl&spr=https&sv=2021-06-08&sr=c&sig=REDACTED?&x-ms-range=bytes=2583737147-2600514362&User-Agent=azure-storage-fuse/1.4.5&x-ms-date=Thu, 09 Feb 2023 03:32:26 GMT&x-ms-version=2018-11-09&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 206 :: REQ ID : 57ac0b74-401e-003c-2537-3ccdad000000

### Have you found a mitigation/solution?
no. It's ok before.

**Comment by vibhansa-msft** [comment]
Form the GET request, response code 206 look ok and there was no error. Can you ensure your local disk is not running out of space. In such cases the donwload will fail as blobfuse tries to cache the entire file locally.
I would also encourage you to upgrade to Blobfuse2, which has better performance and host of new features. You can checkout the README in main branch in this repo for the same. And Wiki section talks about how to install and configure.

**Comment by huanghaiqing1** [comment]
<img width="771" alt="20230209 1" src="https://user-images.githubusercontent.com/30017444/217724698-bb4ad2bf-d627-4e11-956d-3bdea65adbcf.PNG">

**Comment by huanghaiqing1** [comment]
Looks the local OS, which is also located in Azure's file systems are ok. We plan to download a 3.8GB size iso file from mount point: /HPCC/haiqing.huang_hhq/

**Comment by huanghaiqing1** [comment]
<img width="755" alt="20230209 2" src="https://user-images.githubusercontent.com/30017444/217724993-ac86d8f7-118c-4276-9b01-29ab636d1aa5.PNG">

**Comment by vibhansa-msft** [comment]
As per above output, your temp-cache path configured in blobfuse "/tmp/ramdisk" is only 1GB in size, while you are trying to download a file of 3x size. Can you increase your /tmp/ramdisk to may be 4-5GB and try again. Also, if you are downloading multiple files in parallel then /tmp/ramdisk size shall be good enough to hold all of them together.

**Comment by huanghaiqing1** [comment]
<img width="707" alt="20230209 3" src="https://user-images.githubusercontent.com/30017444/217727494-7c44b761-155b-455b-a728-86055cb389f9.PNG">

**Comment by huanghaiqing1** [comment]
After I adjusted the /tmp/ramdisk to 5GB, the copy broke and the mount point is gone.

**Comment by huanghaiqing1** [comment]
ramdisk size looks to be one reason. Because I test blobfuse v1 on both opensuse 15.4 and ubuntu OS. When set as 1GB size, return same error. When adjust to 5GB, my opensuse OS looks ok for data copy of 3.8GB size iso. But same iso copy failed in the ubuntu OS.

**Comment by huanghaiqing1** [comment]
The problem looks solved after I increase physical memory of the VM in Azure from 4GB to 8GB.
