### ISSUE TITLE
Blob files not visible in mounted drive

### ISSUE THREAD

**Issue by StuartMarshall56** [Azure/azure-storage-fuse#1058]
### Which version of blobfuse was used?
2.0.1

### Which OS distribution and version are you using?
Ubuntu 22.04

### If relevant, please share your mount command.
sudo blobfuse2 mount ~/mycontainer --config-file=/home/vsts/work/1/s/config.yaml

### What was the issue encountered?
I can write a file to the ~/mycontainer folder using the following command

        echo "CD TO MYCONTAINER"
        cd /home/vsts/mycontainer
        echo "CURRENT DIR: $(pwd)"
        
        echo "MAKE FILE IN CONTAINER"
        sudo touch text.txt

But i can't see it in my Azure Storage Account. It doesn't seem to be uploading the file. I also can't read any of the files currently on my Azure blob container. I'm not sure if the mount has actually worked? The logs look fine.

The ls command below only lists the new file i created and the copy command fails when trying to copy a file from the blob store

        echo "LIST FILES IN CONTAINER"
        ls -l /home/vsts/mycontainer   
        
        echo "COPY FILE FROM BLOB" 
        cp '/home/vsts/mycontainer/g412_information.rst' '$(Build.ArtifactStagingDirectory)' 

OUTPUT OF THESE COMMANDS SHOWN BELOW

       LIST FILES IN CONTAINER
       total 0
      -rw-r--r-- 1 root root 0 Feb 14 10:38 text.txt
       COPY FILE FROM BLOB
       cp: cannot stat '/home/vsts/mycontainer/g412_information.rst': No such file or directory
       ##[error]Bash exited with code '1'.

### Have you found a mitigation/solution?
No

### Please share logs if available.
Log
[blobfuse2.log](https://github.com/Azure/azure-storage-fuse/files/10731617/blobfuse2.log)

Config file (changed to .txt)
[config.txt](https://github.com/Azure/azure-storage-fuse/files/10731622/config.txt)

**Comment by vibhansa-msft** [comment]
Kindly add "--ignore-open-flags=true" in your mount command. If this is a block-blob account (non HNS) then add "--virtual-directory=true" as well.

**Comment by vibhansa-msft** [comment]
To test your mount went successful or not just run 'df' command and see if you have the mount point listed there. Another option for the same is to use "blobfuse2 mount list" command.

**Comment by StuartMarshall56** [comment]
Hi Vibhansa,

Thanks for the quick response. 

The blobfuse2 mount list command didn't return anything (see below)

    NEEDRESTART-VER: 3.5
    NEEDRESTART-KCUR: 5.15.0-1031-azure
    NEEDRESTART-KEXP: 5.15.0-1031-azure
    NEEDRESTART-KSTA: 1
    MAKE DIRS
    MY USER NAME IS: vsts
    RUN BLOBFUSE2
    **LIST MOUNTS**
    FILES IN VAR/LOG

I've attached the  blobfuse2.log file below
[blobfuse2 (1).log](https://github.com/Azure/azure-storage-fuse/files/10731910/blobfuse2.1.log)

**Comment by vibhansa-msft** [comment]
I do not see much of event happening in the log file. Maybe you are missing something here. I see in the original post that config file is shared is '.txt' it shall be '.yaml', ignore if it was renamed just to share.
Also, in that config file I see 'allow-other: true' this option will work only if it's enabled on libfuse. Edit /etc/fuse.conf file and make sure you have allow-other enabled there as well.

**Comment by StuartMarshall56** [comment]
I changed to .txt just to share,

Can i edit the /etc/fuse.conf file in bash? I'm running this all in a azure pipeline.

**Comment by vibhansa-msft** [comment]
On your local vm you can edit it with 'sudo' permissions. If you are using azure pipeline either you can remove "allow-other" from your config file or try using "echo "user_allow_other" >> /etc/fuse.conf" from a script with sudo.

**Comment by StuartMarshall56** [comment]
Removing allow-others from the config.yaml file didn't change anything.

I don't have write permissions to the /etc/fuse.conf file even if i use the command with sudo....

    echo "EDIT FUSE"
    sudo echo "user_allow_other" >> /etc/fuse.conf

OUTPUT

    EDIT FUSE
    /home/vsts/work/_temp/cd744cde-253e-4ae8-b00f-1e0d451a8258.sh: line 17: /etc/fuse.conf: Permission denied

Any other ideas??

**Comment by vibhansa-msft** [comment]
Instead of running into pipeline directly, can you try with same config and mount command locally and see if that works. In our testing we run mount inside a auto created VM and things work fine. Before starting anything we run these two steps to make sure all required stuffs are installed.
 ```
 sudo apt-get update --fix-missing
 sudo apt-get install fuse3 -y
```

**Comment by vibhansa-msft** [comment]
Can you share what you wish to achieve using pipeline. We generally wait for 5-7 seconds after firing the mount command as mount is done by a child process sometimes it takes time so immediatly exiting after mount and checking for it might not work.

**Comment by StuartMarshall56** [comment]
It seems to have worked! I added a pause of 10 seconds after the mount command and also replaced fuse3 with libfuse3. One of them changes has fixed it!

Thanks for your help, much appreciated

**Comment by vibhansa-msft** [comment]
Mostly the sleep might have fixed it. Will close this issue here, feel free to post here if you have any further questions.
