### ISSUE TITLE
Does blobfuse support for oracle solaris server?

### ISSUE THREAD

**Issue by ArulkumarPonnusamy** [Azure/azure-storage-fuse#1059]

**Comment by vibhansa-msft** [comment]
Blobfuse does support any linux distro that has libfuse support. We officially release only for Oracle 8.1. In case you are using any other distro you can build it from source code yourself. Let me know if you need any help with that.

**Comment by vibhansa-msft** [comment]
Oh sorry my bad, missing the Solaris part. We have not tried on Solaris so far from our end and we do not have a setup where we can try this out. You can try building from source on it.

**Comment by vibhansa-msft** [comment]
you just need to checkout the code, install libfuse3, libfuse3-dev and go 1.16. There is a build script in the root of workspace and once installation is done you can just run "./build.sh". libfuse3 if not available try "fuse3" and "fuse3-dev".

**Comment by vibhansa-msft** [comment]
Were you able to build form source?

**Comment by vibhansa-msft** [comment]
I am not sure about solaris and we officially do not release for that platform as well. You need to check by installing the package from standard solaris repo only.

**Comment by vibhansa-msft** [comment]
As of now there is no plan to support this platform. We have added this item to our backlog and will pick it up based on how many customers really need this support. For now, you can take the source code and compile it locally.
