### ISSUE TITLE
Blobfuse2 unable to save changes in some text editors

### ISSUE THREAD

**Issue by jfantinhardesty** [Azure/azure-storage-fuse#1060]
### Which version of blobfuse was used?

2.0.1

### Which OS distribution and version are you using?

Ubuntu 20.04.5

### If relevant, please share your mount command.

blobfuse2 mount ./mount --config-file=./config.yaml

### What was the issue encountered?

I am unable to save changes to files in certain text editors.

I opened an existing text file using gedit in my mounted container. When I save the edited file I see the following error: "Unexpected error: Error renaming temporary file: Input/output error" and so I am unable to save the changes to the file. It seems this issue can be replicated with any editor that saves to a temporary file and does a rename like gedit does.

### Have you found a mitigation/solution?

No.

### Please share logs if available.

Log file
[blobfuse2.txt](https://github.com/Azure/azure-storage-fuse/files/10746020/blobfuse2.txt)

Config file as a text file
[config.txt](https://github.com/Azure/azure-storage-fuse/files/10746042/config.txt)

**Comment by vibhansa-msft** [comment]
Add "--ignore-open-flags=true" to your mount command and retry.

**Comment by jfantinhardesty** [comment]
I tried that in the mount command and got the same error. I also had that set to true originally in my config file.

**Comment by vibhansa-msft** [comment]
As per logs, editor is creating a temperory file and doing chmod on it and later renaming it to original file name. As the temporary file is not yet uploaded to the container the rename command fails. Blobfuse uploads a file only on close, and here we do not see any close call before the rename. One possible workaround to get out of this situation is to instruct blobfuse to create a file on storage whenever application creates a file on mount path.
Add "create-empty-file: true" under "file-cache" section in your config file and that shall unblock you. I will try to reproduce this locally and investigate if we can do something better here.

**Comment by vibhansa-msft** [comment]
Were you able to edit the file using above suggested config changes?

**Comment by vibhansa-msft** [comment]
Closing this as this is resolved.
