### ISSUE TITLE
blobfuse v1.4.5 enable allow_other in /etc/fstab still not able to see mount point when switch to normal user

### ISSUE THREAD

**Issue by huanghaiqing1** [Azure/azure-storage-fuse#1061]
### Which version of blobfuse was used?
v1.4.5

### Which OS distribution and version are you using?
centos 7.8 created from Azure image

### If relevant, please share your mount command.
blobfuse /mnt/cn/projects/BMW-SRR/2-Sim fuse --log-level=LOG_DEBUG,--tmp-path=/tmp/tmpfs_2sim,attr_timeout=240,entry_timeout=240,negative_timeout=120,--config-file=/root/fuse_connection_silreprocesseddata2.cfg,allow_other,--file-cache-timeout-in-seconds=0,nonempty 0 0
blobfuse /mnt/cn/projects/BMW-SRR/4-Resim-JIRA fuse --log-level=LOG_DEBUG,--tmp-path=/tmp/tmpfs_2sim_output,--config-file=/root/silreprocesseddata.cfg,--file-cache-timeout-in-seconds=0,attr_timeout=240,entry_timeout=240,negative_timeout=120,allow_other,nonempty,noauto 0 0

### What was the issue encountered?
Above strings are set in /etc/fstab. Only can see mount points by root user. Not able to see when switch to normal user.
in /etc/fuse.conf, we have un-comment "user_allow_other". But still not ok. When use blobfuse mount by command mode, same issue. Only root user can see the mount points. When we pasate the command to another centos server, it works.

### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
"When we paste the command to another centos server, it works." : Can you check any difference in terms of privileges that user have on the VM where you do not see the mount.
Also, when other users are not able to see the mount, can you validate blobfuse is still running and root is able to see the mount point.

**Comment by huanghaiqing1** [comment]
Here I can confirm blobfuse is still running and accessable by root and be able to see by root, which switch to another normal user. I didn't see any normal user's profile level umount about blobfuse mounts when su to the normal user.

**Comment by vibhansa-msft** [comment]
If allow_other is provided and is enable in /etc/fuse.conf then it should have worked for all users. Can you check the mount path and the temp cache path have "777" permissions set.

**Comment by vibhansa-msft** [comment]
We have also seen in some customer scenarios that they had both fuse2 and fuse3 installed and this created two fuse config files in /etc, just want you to validate that you have enable allow_other in correct file.

**Comment by vibhansa-msft** [comment]
Were you able to make it work or still stuck with this?

**Comment by tasherif-msft** [comment]
Hi @huanghaiqing1 we will close this issue in the meantime, if you're still encountering the problem please reopen
