### ISSUE TITLE
Blobfuse2 not running as expected in docker container

### ISSUE THREAD

**Issue by StuartMarshall56** [Azure/azure-storage-fuse#1062]
### Which version of blobfuse was used?
Blobfuse 2.0.1

### Which OS distribution and version are you using?
Ubuntu 22.04

### If relevant, please share your mount command.
blobfuse2 mount /mycontainer --config-file=./project/config.yaml --ignore-open-flags=true --virtual-directory=true

### What was the issue encountered?
I can't seem to get blobfuse2 to work in a docker container.

My Docker file is shown below. This builds nicely.

    FROM ubuntu:22.04

    RUN apt-get update && apt-get install -y software-properties-common gcc && \
        add-apt-repository -y ppa:deadsnakes/ppa
    
    RUN apt-get update && apt-get install -y python3.6 python3-distutils python3-pip python3-apt \
        && apt-get install -y wget \
    	&& rm -rf /var/lib/apt/lists/*
    		
    RUN echo "INSTALL BLOB FUSE"
    RUN wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
    RUN dpkg -i packages-microsoft-prod.deb
    RUN apt-get update
    RUN apt install -y blobfuse2        
    
    COPY ./startup.sh .
    RUN chmod u+x ./startup.sh   
    
    # Create when running docker (seems more sensible as other mounts created at runtime) 
    CMD ["/bin/bash","-c","./startup.sh"]

I have created a startup.sh script that is running the CMD commands (see below). I've added a pause to wait for blobfuse2 to work (you suggested this in the following issue https://github.com/Azure/azure-storage-fuse/issues/1058)

    #! /bin/bash
    echo "CURRENT DIR IS $PWD"
    
    echo "MAKE DIRS"
    mkdir -p /mnt/ramdisk
    mkdir -p /mnt/ramdisk/blobfuse2tmp
    mkdir -p /mycontainer 
    
    echo "RUN BLOBFUSE"
    blobfuse2 mount /mycontainer --config-file=./project/config.yaml --ignore-open-flags=true --virtual-directory=true
    echo "PAUSE 60"
    sleep 60
    echo "RESUME"
    
    echo "WRITE TO MYCONTAINER"
    cd /mycontainer
    echo "CURRENT DIR IS $PWD"
    
    echo "WRITE TO CONTAINER"
    touch text_in_docker.txt
    
    cd /project
    echo "CURRENT DIR IS $PWD"
    
    python3 ./linux.py

Basically the touch text_in_docker.txt command isn't creating the file in the repo so i'm not sure that the blobfuse command is doing anything? If i pass it an invalid config.yaml file - it fails so i'm sure all the packages have installed (the docker build logs look fine). Have you got any experience of installing/using blobfuse in a docker container?

### Have you found a mitigation/solution?
Yes - mount blob store in a VM using blobfuse2 and then mount that drive in the docker run command. We want to avoid having to spin up a VM to use the container.

### Please share logs if available.
Docker build log
[docker-build-log.txt](https://github.com/Azure/azure-storage-fuse/files/10759108/docker-build-log.txt)

pipeline run log
[pipeline-log.txt](https://github.com/Azure/azure-storage-fuse/files/10759114/pipeline-log.txt)

**Comment by vibhansa-msft** [comment]
By default Blobfuse runs as a background process. Mount command merely starts a child process that will take care of mount. This means your mount command exists once the child process is created. For containers this means the command execution is complete and it will exit the shell. When you run blobfuse inside a container, you need to run it as a foreground process. Add "--foreground=true" in your mount command and check if that works for you.  For the reference you can check our standard [dockerfile](https://github.com/Azure/azure-storage-fuse/blob/main/docker/Dockerfile).

**Comment by vibhansa-msft** [comment]
We also have a published docker image for blobfuse2, Kindly refer to [this](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Docker-Container) document.

**Comment by StuartMarshall56** [comment]
Hi,

Thanks for the quick response again.

I added the --foreground=true command but the mount failed with the following error

    RUN BLOBFUSE
    fuse: device not found, try 'modprobe fuse' first
    Error: unable to start pipeline [failed to mount fuse]

I added a --privileged arg to my docker run command. Now it is running (i think) but has been going for about 20 mins now. Any ideas what is happening?

**Comment by vibhansa-msft** [comment]
As blobfuse is mounted in foreground the shell will not return back when you launch the blobfuse. You need to unmount the blobfuse through other shell over container to gracefully close this container. Once you run the container create another shell to that container and that will give you access to your mount path.

'docker ps' will list all running containers
'docker exec -it 0c6fe0f5dc76 bash' : will start a new bash for the same container. Here id of the container is retrieved by docker ps in above step. On this bash you can go to your mount path and use it.

**Comment by vibhansa-msft** [comment]
Just to explain the context here. When you run a container you provide a command to execute. If the command given here is to just mount then as soon as mount completes the container will exit (as the command has exited). This means you mount and you exit your container which remove the mount point as well. Hence in case of container you need to wait untill user unmounts the Blobfuse. This is not possible for a binary running in background so you provide "--foreground" option in mount cli which means Blobfuse will wait untill someone explicitly unmount it. 
This blocks your container on the mount command. Now to access your mount path you need to create another shell to that container from where you can either access the path or unmoun Blobfuse. Once you unmount your mount command will exit and your container will terminate.

**Comment by vibhansa-msft** [comment]
If you do not wish to run in this mode, another way is to run your container in interactive mode and create a shell there. Once you are on shell you can manually mount inside container and use it, Once you are done unmount and exit the shell which internally will terminate your container as well.

**Comment by StuartMarshall56** [comment]
I'm a little confused as to why this worked before when mounting in a VM. I didn't use the foreground command and instead waited for 10 seconds until the mount command has worked. I need to do this as i'm running in a pipeline and the next command is executing a script with inputs from the blob store. Ideally, when the docker image is run, i want it to mount the blob storage using blobfuse2 , then get some files from the blob storage, then execute a scripts using the files. Like i said, this worked fine when running directly on a VM but just struggling with the docker container!

**Comment by StuartMarshall56** [comment]
UPDATE: The longer pause, adding install fuse3 or adding  --privileged --cap-add=SYS_ADMIN --device /dev/fuse has sorted my issue. Thanks for your help again

**Comment by vibhansa-msft** [comment]
Closing this as your issue is resolved. Feel free to reopen in case you have any futher questions.
