### ISSUE TITLE
File not visible after mounting on ubuntu 18.04

### ISSUE THREAD

**Issue by evhen14** [Azure/azure-storage-fuse#1063]
### Which version of blobfuse was used?
blobfue2

### Which OS distribution and version are you using?
ubuntu18.04 from AKS

### If relevant, please share your mount command.
--allow-other --file-cache-timeout=10 -o nonempty

### What was the issue encountered?
Doesn't see file in subfolders on Azure Blob

### Have you found a mitigation/solution?
No. however, it's reproducible in 90% of cases

### Please share logs if available.

logs are coming from blob-csi-driver, however, I believe the issue is not with the driver but rather with blobfuse2 (see more after logs)
```
csi-blob-node-nxbng blob
csi-blob-node-nxbng blob volumeId unique-handle-3a7c5836e09f464ca7d11a7d50be51d1
csi-blob-node-nxbng blob context map[containerName:0378cd5e-be61-4016-a237-c5cd25484c2e protocol:fuse2 resourceGroup:SECRET-dev storageAccount:SECRET]
csi-blob-node-nxbng blob mountflags [--allow-other --file-cache-timeout=10 -o nonempty]
csi-blob-node-nxbng blob mountOptions [--allow-other --file-cache-timeout=10 -o nonempty --tmp-path=/mnt/unique-handle-3a7c5836e09f464ca7d11a7d50be51d1 --container-name=0378cd5e-be61-4016-a237-c5cd25484c2e --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false]
csi-blob-node-nxbng blob args /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pr-23-cz-b763bdd8-77f6-43ba-aaf3-aeb34dbf5ab0-025400/globalmount --allow-other --file-cache-timeout=10 -o nonempty --tmp-path=/mnt/unique-handle-3a7c5836e09f464ca7d11a7d50be51d1 --container-name=0378cd5e-be61-4016-a237-c5cd25484c2e --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false
csi-blob-node-nxbng blob serverAddress SECRET.blob.core.windows.net
csi-blob-node-nxbng blob I0217 02:54:12.224532   10827 nodeserver.go:144] mouting using blobfuse proxy
csi-blob-node-nxbng blob I0217 02:54:12.225187   10827 nodeserver.go:158] calling BlobfuseProxy: MountAzureBlob function
csi-blob-node-nxbng blob I0217 02:54:12.689976   10827 nodeserver.go:397] volume(unique-handle-3a7c5836e09f464ca7d11a7d50be51d1) mount on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pr-23-cz-b763bdd8-77f6-43ba-aaf3-aeb34dbf5ab0-025400/globalmount" succeeded
csi-blob-node-nxbng blob I0217 02:54:12.690027   10827 utils.go:82] GRPC response: {}
csi-blob-node-nxbng blob I0217 02:54:12.705351   10827 utils.go:75] GRPC call: /csi.v1.Node/NodePublishVolume
csi-blob-node-nxbng blob I0217 02:54:12.705382   10827 utils.go:76] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pr-23-cz-b763bdd8-77f6-43ba-aaf3-aeb34dbf5ab0-025400/globalmount","target_path":"/var/lib/kubelet/pods/9e39c926-2f42-4bf2-bbc2-2fa5c9332c2d/volumes/kubernetes.io~csi/pr-23-cz-b763bdd8-77f6-43ba-aaf3-aeb34dbf5ab0-025400/mount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["--allow-other","--file-cache-timeout=10","-o nonempty"]}},"access_mode":{"mode":5}},"volume_context":{"containerName":"0378cd5e-be61-4016-a237-c5cd25484c2e","csi.storage.k8s.io/ephemeral":"false","csi.storage.k8s.io/pod.name":"SECRET-b763bdd8-77f6-43ba-aaf3-aeb34dbf5ab0-025401-tq6pb","csi.storage.k8s.io/pod.namespace":"pr-23","csi.storage.k8s.io/pod.uid":"9e39c926-2f42-4bf2-bbc2-2fa5c9332c2d","csi.storage.k8s.io/serviceAccount.name":"default","protocol":"fuse2","resourceGroup":"SECRET-dev","storageAccount":"SECRET"},"volume_id":"unique-handle-3a7c5836e09f464ca7d11a7d50be51d1"}
csi-blob-node-nxbng blob I0217 02:54:12.706406   10827 nodeserver.go:122] NodePublishVolume: volume unique-handle-3a7c5836e09f464ca7d11a7d50be51d1 mounting /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pr-23-cz-b763bdd8-77f6-43ba-aaf3-aeb34dbf5ab0-025400/globalmount at /var/lib/kubelet/pods/9e39c926-2f42-4bf2-bbc2-2fa5c9332c2d/volumes/kubernetes.io~csi/pr-23-cz-b763bdd8-77f6-43ba-aaf3-aeb34dbf5ab0-025400/mount with mountOptions: [bind]
csi-blob-node-nxbng blob I0217 02:54:12.706461   10827 mount_linux.go:219] Mounting cmd (mount) with arguments ( -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pr-23-cz-b763bdd8-77f6-43ba-aaf3-aeb34dbf5ab0-025400/globalmount /var/lib/kubelet/pods/9e39c926-2f42-4bf2-bbc2-2fa5c9332c2d/volumes/kubernetes.io~csi/pr-23-cz-b763bdd8-77f6-43ba-aaf3-aeb34dbf5ab0-025400/mount)
```

There is nothing wrong I see in the logs. Also, I considered reporting that to csi-volume, but decided that it's probably a problem with the implementation rather than configuring for containers. Might be wrong here.

More info:
- Unfortunately AKS only supports ubuntu18.04 (fuse2 from your versions page) and blobfuse2 is primarily targeting fuse3. 
-  when using blobfuse v1, the issue is still there but very hard to reproduce, from our clients, it happens about once in 1000 times. 
- using blobfuse v1 we don't have to provide `-o nonempty` option.

**Comment by vibhansa-msft** [comment]
Hi @evhen14, Thanks for reaching out to Blobfuse team.
"-o nonempty" shall not have any relation to the issue you observe. This flag merely controls that blobfuse can mount on a non-empty directory or not. In past we have seen customers having wrong expectations with this and hence we decided to remove this option in blobfuse2,
For the other part where you observe folders are not visible can you confirm it's a HNS account or not. For non-HNS account blobfuse looks for special marker files to identify directories and in case of their absence fails to list directories correctly. To overcome this, you need to pass down"--virtual-directory=true" cli option. Can you validate this solves your issue. If not, you need to share blobfuse logs to investigate this.

**Comment by vibhansa-msft** [comment]
Also, Blobfuse2 can be used with fuse2 as well, just the performance improvements are mostly targeted to fuse3 as that's the default offering with latest Linux distros.

**Comment by evhen14** [comment]
@vibhansa-msft  thanks a lot for the prompt response. I can confirm that the `--virtual-directory=true` resolves my issue.
