### ISSUE TITLE
Docker image listed in documentation does not exist

### ISSUE THREAD

**Issue by florianpiesche** [Azure/azure-storage-fuse#1075]
### Which version of blobfuse was used?

- 2.0.2 (attempted)

### Which OS distribution and version are you using?

- macOS 13.0 "Ventura"

### If relevant, please share your mount command.

```bash
$ docker pull blobfuse2containers.azurecr.io/azure-blobfuse2.2.0.0-preview.4
Using default tag: latest
Error response from daemon: manifest for blobfuse2containers.azurecr.io/azure-blobfuse2.2.0.0-preview.4:latest not found: manifest unknown: manifest tagged by "latest" is not found
```

### What was the issue encountered?

Docker image fails to pull as per documentation (https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Docker-Container)

### Have you found a mitigation or workaround?

The currently correct image is `blobfuse2containers.azurecr.io/azure-blobfuse2.2.0.2`. I would suggest there should be a `latest` tag, and generally better use of tags rather than new repositories for new versions (e.g. make it `blobfuse2containers.azurecr.io/azure-blobfuse2:2.0.2` instead of `blobfuse2containers.azurecr.io/azure-blobfuse2.2.0.2`).

**Comment by vibhansa-msft** [comment]
I have updated the documentation to point to 2.0.2 instead. We will look at your suggestion of having the latest tag.
