### ISSUE TITLE
There is a blobfuse process in the azure virtual machine that consumes 58% of the memory

### ISSUE THREAD

**Issue by ZHASONG** [Azure/azure-storage-fuse#1076]
### Which version of blobfuse was used?
2

### Which OS distribution and version are you using?
centos7.7

### If relevant, please share your mount command.
![WechatIMG9](https://user-images.githubusercontent.com/58546663/222713095-efaba192-98b2-4865-92c9-4452c5cee344.png)

### Please share logs if available.

please see attuchment
![WechatIMG20](https://user-images.githubusercontent.com/58546663/222714811-643d673b-4377-4b61-b30d-b5551c32af70.jpeg)

**Comment by vibhansa-msft** [comment]
Kindly share your mount command and config file. Is user application opening a lot of files for read/write operation on this mount point or container having large number of blobs?

**Comment by vibhansa-msft** [comment]
Kindly provide the requested inputs.

**Comment by vibhansa-msft** [comment]
Closing this issue as there are no updates, feel free to reopen once requested data is available.
