### ISSUE TITLE
LOG_ERR [libfuse_handler.go (178)]: Libfuse::initFuse : failed to mount fuse

### ISSUE THREAD

**Issue by luffjr** [Azure/azure-storage-fuse#1083]
### Which version of blobfuse was used?
blobfuse2 version 2.0.2

### Which OS distribution and version are you using?
Ubuntu 20.04.3 LTS (Focal Fossa)

### If relevant, please share your mount command.
blobfuse2 mount /home/ipvadmin/fusemount --config-file=./fuseconfig.yaml

### What was the issue encountered?
mount fails with error Libfuse::initFuse : failed to mount fuse

### Have you found a mitigation/solution?
No. I tried in both "key" mode, as well as "sas".

Config file:
`allow-other: true`

`logging:`
`  type: syslog`
`  level: log_debug`

`components:`
`  - libfuse`
`  - azstorage`

`libfuse:`
`  attribute-expiration-sec: 120`
`  entry-expiration-sec: 120`
`  negative-entry-expiration-sec: 120`

`azstorage:`
`  type: block`
`  account-name: <my storage account name>`
`  container: <the name of a container within my storage account>`
`  endpoint: https://<my storage account name>.blob.core.windows.net`
`  mode: key`
`  account-key: <my storage account access key>`

I also modified /etc/fuse.conf to enable user_allow_other

### Please share logs if available.
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_CRIT [mount.go (384)]: Starting Blobfuse2 Mount : 2.0.2 on [Ubuntu 20.04.3 LTS]
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_CRIT [mount.go (385)]: Logging level set to : LOG_DEBUG
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [libfuse.go (220)]: Libfuse::Configure : libfuse
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_INFO [libfuse.go (260)]: Libfuse::Configure : read-only false, allow-other true, default-perm 511, entry-timeout 120, attr-time 120, negative-timeout 120, ignore-open-flags: true, nonempty false
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [config.go (270)]: ParseAndValidateConfig : Parsing config
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_INFO [config.go (372)]: ParseAndValidateConfig : using the following proxy address from the config file:
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_INFO [config.go (376)]: ParseAndValidateConfig : sdk logging from the config file: false
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [config.go (479)]: ParseAndReadDynamicConfig : Reparsing config
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [config.go (383)]: ParseAndValidateConfig : Getting auth type
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_INFO [config.go (467)]: ParseAndValidateConfig : Account: <snip>, Container: <snip>, AccountType: BLOCK, Auth: KEY, Prefix: , Endpoint: https://<snip>.blob.core.windows.net/, ListBlock: 0, MD5 : false false, Virtual Directory: true
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_INFO [config.go (471)]: ParseAndValidateConfig : Retry Config: Retry count 5, Max Timeout 900, BackOff Time 4, Max Delay 60
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [azauth.go (79)]: azAuth::getAzAuth : Account: <snip>, AccountType: BLOCK, Protocol: https, Endpoint: https://<storage acct name>.blob.core.windows.net/
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_INFO [mount.go (392)]: mount: Mounting blobfuse2 on /home/ipvadmin/fusemount
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [mount.go (410)]: mount: foreground disabled, child = true
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [mount.go (477)]: Mount::runPipeline : blobfuse2 pid = 1429, transfer pipe = /tmp/transferPipe_1429, polling pipe = /tmp/pollPipe_1429
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [azstorage.go (164)]: AzStorage::Start : Starting component azstorage
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [libfuse.go (136)]: Libfuse::Start : Starting component libfuse
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [libfuse_handler.go (116)]: Libfuse::initFuse : Initializing FUSE3
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [libfuse_handler.go (159)]: Libfuse::initFuse : Registering fuse callbacks
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [libfuse_handler.go (163)]: Libfuse::initFuse : Populating fuse arguments
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_TRACE [libfuse_handler.go (187)]: Libfuse::populateFuseArgs
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : blobfuse2
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : /home/ipvadmin/fusemount
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -o
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : entry_timeout=120,attr_timeout=120,negative_timeout=120,allow_other
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -f
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -ofsname=blobfuse2
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -okernel_cache
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_INFO [libfuse_handler.go (175)]: Libfuse::initFuse : Mounting with fuse3 library
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_ERR [libfuse_handler.go (178)]: Libfuse::initFuse : failed to mount fuse
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_ERR [libfuse.go (150)]: Libfuse::Start : Failed to init fuse [failed to mount fuse]
Tue Mar 14 14:49:09 GMT 2023 : blobfuse2[1429] : LOG_ERR [mount.go (483)]: mount: error unable to start pipeline [failed to mount fuse]

**Comment by vibhansa-msft** [comment]
You have used "allow-other: true" in your config, kindly ensure this feature is enable at libfuse level in /etc/fuse.conf file.

**Comment by luffjr** [comment]
> You have used "allow-other: true" in your config, kindly ensure this feature is enable at libfuse level in /etc/fuse.conf file.

Firstly, thanks for coming back to me vibhansa, I see you are very active on here for some time and your efforts are appreciated.

I specified in my original post just under the config that I'd already modified the /etc/fuse.conf file to uncomment the "user_allow_other" line.

**Comment by vibhansa-msft** [comment]
Can you supply "--foreground -d" option on your cli and share the console logs. This is failing due to some error at libfuse level.

**Comment by vibhansa-msft** [comment]
Great to hear that it is resolved for you.
