### ISSUE TITLE
file corruption (under heavy workload/throttling) during large files downloading from multiple nodes

### ISSUE THREAD

**Issue by AlexanderYukhanov** [Azure/azure-storage-fuse#109]
In our tests, we are starting a cluster with 8 NC24r nodes. And submitting a job with following command line "mpirun -mca btl_tcp_if_exclude docker0,lo --allow-run-as-root --hostfile $AZ_BATCHAI_MPI_HOST_FILE sha1sum /mnt/batch/tasks/shared/LS_root/mounts/blob/ImageNet/test/train.zip && mpirun -mca btl_tcp_if_exclude docker0,lo --allow-run-as-root --hostfile $AZ_BATCHAI_MPI_HOST_FILE sha1sum /mnt/batch/tasks/shared/LS_root/mounts/blob/ImageNet/test/val.zip" where train.zip is ~ 140Gb and  val.zip is about 6 Gb.
mpi run starts 32 processes (4 on each node).
We are observing that on one of the nodes (randomly) a downloaded file got corrupted (the wrong sha1sum is reported). Note, there is no io error reported.

**Comment by seguler** [comment]
It is not yet very clear whether this is data corruption, right ? There may be an error reported by blobfuse - which we haven't validated yet ?

**Comment by AlexanderYukhanov** [comment]
With a large number of nodes, I am observing two issues:
1. seems to be a dup of https://github.com/Azure/azure-storage-fuse/issues/71. In this case, download_blob_to_file returns 1600 (interesting, where are we getting those fancy codes like 1506 and 1600) and fuse reports 0 to the client. In this case, client reports that file is not found (because if download_blob_to_fire sets errno, blobfuse deletes the file before returning). 
2. still investigating. sha1sum mentioned in the original issue description will not report sha1 for non-existing file, so the file exists and it's corrupted. most probably, we are ignoring an error somewhere inside of blobfuse.

**Comment by AlexanderYukhanov** [comment]
I instrumented the code a bit more and added the following check into download_blob_to_file:
                            std::ofstream output(destPath.c_str(), std::ios_base::out |  std::ios_base::in);
                            output.seekp(offset);
                            auto chunk = m_blobClient->get_chunk_to_stream_sync(container, blob, offset, range, output);
+                            auto actual = output.tellp() - offset;
+                            if (actual != range) {
+                               std::cout << blob << " wrong size read " << actual << " expected " << range << " for offset " << offset << std::endl;
+                             }

During stress testing I see lot's of "wrong size read" messages with actual size == 0 and chuck.success() == true.
After a quick look at the code, I suspect that blob_client.cpp makes a decision about operation success based only on HTTP status code without checking if the body was successfully received or not.

**Comment by seguler** [comment]
I think we should implement the retry for the HTTP body within get_chunk_to_stream_sync in blob_client.cpp. This is where we synchronously wait for all the body; and we should be able to check body size and compare to the expected size, and retry based on the configured retry policy. 

https://github.com/Azure/azure-storage-fuse/blob/master/azure-storage-cpp-lite/src/blob/blob_client.cpp#L61

**Comment by AlexanderYukhanov** [comment]
The current idea is:
1. return curl_easy_perform result from CurlEasyRequest::perform(). https://github.com/Azure/azure-storage-fuse/blob/master/azure-storage-cpp-lite/src/http/libcurl_http_client.cpp#L54
2. propagate this error information into the callback
3. in callback reset the output stream
4. reuse retry mechanism which is already in place for http status codes

**Comment by AlexanderYukhanov** [comment]
testing...

**Comment by AlexanderYukhanov** [comment]
Oh... there was another issue - after the first error the state of the curl was changed to write into error stream instead of the body -) So, after retry the body was empty -)

**Comment by AlexanderYukhanov** [comment]
With https://github.com/Azure/azure-storage-fuse/pull/112 the tests are passed and I was able to run distributed alexnet against imagenet on 16 NC24r.

**Comment by seguler** [comment]
Fixed in blobfuse 0.3
