### ISSUE TITLE
Blobfuse2 fstab in red hat 8.7

### ISSUE THREAD

**Issue by gruizcr** [Azure/azure-storage-fuse#1091]
### Which version of blobfuse was used?
Blobfuse2

### Which OS distribution and version are you using?
Red hat 8.7

### If relevant, please share your mount command.
blobfuse2 /gil fuse defaults,_netdev,nofail,--tmp-path=/mnt/resource/blobfusetmp,--config-file=/home/azureuser/config.yaml,--log-level=LOG_DEBUG,allow_other 0 0

### What was the issue encountered?
https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Installation#centos--redhat-1
In this section we need also fuse, just like this:

 sudo yum install fuse3 fuse3-libs blobfuse2 fuse

### Have you found a mitigation/solution?
Yes,

### Please share logs if available.

tail -f /var/log/messages
Mar 22 14:43:09 redhat87vm1 kernel: fuse: Unknown parameter '--tmp-path'
Mar 22 14:47:15 redhat87vm1 systemd-logind[784]: New session 204 of user azureuser.
Mar 22 14:47:15 redhat87vm1 systemd[1]: Started Session 204 of user azureuser.

**Comment by gruizcr** [comment]
Yes, this is an update:

In this link: https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Installation#centos--redhat-1
***@***.***

                We need to add the word "fuse" in the previous line,  like this:

                                sudo yum install fuse fuse3 fuse3-devel



Gilberto Ruiz
Support Escalation Engineer, Azure Rapid Response
[MSFT_logo_Gray DE sized SIG1.png]

**Comment by vibhansa-msft** [comment]
If your system is fuse3 compliant you dont need to install fuse. Fuse3 is an upgrade over fuse. In your fstab entry replace "fuse" with "fuse3" and let us know if that works for you.

**Comment by vibhansa-msft** [comment]
Closing this as for fuse3 compliant system fstab entry shall mention fuse3 and not fuse.
