### ISSUE TITLE
Directory listing not correct for append-blobs

### ISSUE THREAD

**Issue by salami738** [Azure/azure-storage-fuse#1093]
### Which version of blobfuse was used?
blobfuse2containers.azurecr.io/azure-blobfuse2.2.0.2

### Which OS distribution and version are you using?
OS from base image (see above) in Docker

### If relevant, please share your mount command.
blobfuse2 mount "${MOUNT_PATH}" --config-file=/usr/share/blobfuse2/config.yaml --attr-cache-timeout 10 --attr-timeout 10 --foreground=true

### What was the issue encountered?
Hi, we have a problem with append-blobs.
When a blob is initially mounted, the contents of the directory are up to date.
If the blob is then updated e.g. via REST API, then we do not see the change in the mounted directory structure,
even after the configured cache lifetime has expired.
Azure Storage Explorer displays the listing correctly.

Is this a bug or a configuration issue on our end?

### Have you found a mitigation/solution?
No. Listing is only updated on complete docker container restart.

### Please share logs if available.
No logs available

**Comment by salami738** [comment]
Can you please add a note to the documentation that append-blobs are not currently supported? This will help users like me not to waste time debugging this case.

**Comment by vibhansa-msft** [comment]
Will update the documentation, however as of now this feature is not on priority for us.
