### ISSUE TITLE
blobfuse: version `GLIBC_2.29' not found (required by blobfuse)

### ISSUE THREAD

**Issue by ahsanklam** [Azure/azure-storage-fuse#1103]
### Which version of blobfuse was used?
hostname:~ # rpm -qa | grep blob
blobfuse-1.4.5-1.x86_64

hostname:~ # blobfuse --version
blobfuse: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by blobfuse)

### Which OS distribution and version are you using?
SLES for SAP, SUSE 15 SP 2

### If relevant, please share your mount command.
It looks like there is an issue with the blobfuse and the glibc compatibility. SUSE provide glibc up to 2.26 and Blobfuse is demanding 2.29. So I am not sure if the mount command is relevant anymore. However here it is:

blobfuse /backup --tmp-path=/mnt/resource/blobfusetmp  --config-file=/etc/smbcredentials/backup.cred -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o nonempty

### What was the issue encountered?
Every time I try to mount it, I see the following error:

blobfuse: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by blobfuse)

### Have you found a mitigation/solution?
No

### Please share logs if available.
No information in the log file related to this issue.

**Comment by vibhansa-msft** [comment]
As blobfuse is unable to start there is nothing you will find in logs. This is a missing dependency on the system. Have you installed it from our standard SUSE 15 release?
If no, kindly reinstall from there.
If yes, you might need to manually upgrade your GLIBC. Our SUSE release is done from a SUSE VM supported by Azure and this might be potentially be a SUSE version difference.

**Comment by vibhansa-msft** [comment]
You can also try to upgrade to blobfuse2 which is our latest offering and SUSE builds are available for that as well. For 1.4.5 if you are not able to resolve the dependency then best bet is for you is to take the code and build it locally on your system.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Feel free to reopen if the issue persists or you were not able to follow the steps shared above.
