### ISSUE TITLE
container-name is always required when using `-o` notation, even when using `mountall`

### ISSUE THREAD

**Issue by saulobejo** [Azure/azure-storage-fuse#1108]
### Which version of blobfuse was used?
blobfuse2 version 2.0.2

### Which OS distribution and version are you using?
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:          22.04
Codename:     jammy

Linux 5.15.0-1035-azure #42-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

### If relevant, please share your mount command.

this works

`blobfuse2 mount all /home/localuser/data/bejotmp --config-file=config.yaml`

this does not work:

`blobfuse2 mount all /home/localuser/data/bejotmp -o 'ro,--config-file=config.yaml`

but this works (xxxxxxx is a valid container)

`blobfuse2 mount all /home/localuser/data/bejotmp -o 'ro,--config-file=config.yaml,--container-name=xxxxxxx'`

### What was the issue encountered?

the `-o` notation is the notation used by `fstab`, therefore, I'm not able to run a `mount all` in fstab without repeating the name of one container.

### Have you found a mitigation/solution?

add the name of a valid container to the `container-name`

### Please share logs if available.

```
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_CRIT [mount_all.go (155)]: Starting Blobfuse2 Mount All: 2.0.2
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_CRIT [mount_all.go (156)]: Logging level set to : LOG_DEBUG
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_TRACE [config.go (270)]: ParseAndValidateConfig : Parsing config
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_WARNING [config.go (331)]: ParseAndValidateConfig : account endpoint not provided, assuming the default .core.windows.net style endpoint
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_INFO [config.go (372)]: ParseAndValidateConfig : using the following proxy address from the config file:
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_INFO [config.go (376)]: ParseAndValidateConfig : sdk logging from the config file: false
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_TRACE [config.go (479)]: ParseAndReadDynamicConfig : Reparsing config
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_DEBUG [config.go (383)]: ParseAndValidateConfig : Getting auth type
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_INFO [config.go (467)]: ParseAndValidateConfig : Account: AAAAAAA, Container: , AccountType: BLOCK, Auth: SAS, Prefix: , Endpoint: https://AAAAAAA.blob.core.windows.net/, ListBlock: 0, MD5 : false false, Virtual Directory: true
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_INFO [config.go (471)]: ParseAndValidateConfig : Retry Config: Retry count 5, Max Timeout 900, BackOff Time 4, Max Delay 60
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_DEBUG [azauth.go (79)]: azAuth::getAzAuth : Account: AAAAAAA, AccountType: BLOCK, Protocol: https, Endpoint: https://AAAAAAA.blob.core.windows.net/
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_TRACE [block_blob.go (209)]: BlockBlob::TestPipeline : Validating
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_TRACE [azstorage.go (164)]: AzStorage::Start : Starting component azstorage
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_TRACE [block_blob.go (238)]: BlockBlob::ListContainers : Listing containers
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150097] : LOG_TRACE [azstorage.go (177)]: AzStorage::Stop : Stopping component azstorage
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_CRIT [mount.go (384)]: Starting Blobfuse2 Mount : 2.0.2 on [Ubuntu 22.04.2 LTS]
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_CRIT [mount.go (385)]: Logging level set to : LOG_DEBUG
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_TRACE [libfuse.go (220)]: Libfuse::Configure : libfuse
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_INFO [libfuse.go (260)]: Libfuse::Configure : read-only true, allow-other false, default-perm 493, entry-timeout 120, attr-time 120, negative-timeout 120, ignore-open-flags: true, nonempty false
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_TRACE [file_cache.go (197)]: FileCache::Configure : file_cache
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_INFO [file_cache.go (272)]: FileCache::Configure : Using default eviction policy
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_INFO [file_cache.go (291)]: FileCache::Configure : create-empty false, cache-timeout 120, tmp-path /mnt/blobfuse/AAAAAAA, max-size-mb 0, high-mark 80, low-mark 60
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_TRACE [attr_cache.go (121)]: AttrCache::Configure : attr_cache
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_INFO [attr_cache.go (145)]: AttrCache::Configure : cache-timeout 120, symlink false, cache-on-list true
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_TRACE [config.go (270)]: ParseAndValidateConfig : Parsing config
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_ERR [azstorage.go (94)]: AzStorage::Configure : Config validation failed [container name not provided]
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_ERR [pipeline.go (69)]: Pipeline: error creating pipeline component azstorage [config error in azstorage [container name not provided]]
Tue Apr 11 13:17:43 UTC 2023 : blobfuse2[2150134] : LOG_ERR [mount.go (388)]: mount : failed to initialize new pipeline [config error in azstorage [container name not provided]]
```

**Comment by vibhansa-msft** [comment]
'mount all' can not be used in fstab. 'fstab' signature does not allow us to explicitly provide a sub command option and the second literal has to be the mount path.
Only way to performa mount all from fstab is to run a script from fstab and then execute your mount all command from the script instead. While writing down your mount command in your script, there is no need to specify -o options other then for 'ro'.

**Comment by saulobejo** [comment]
@vibhansa-msft 

I've used a script 

And, to make a generic script, I used `$@` to get all variables from the fstab

This means that `mount all` will receive the `-o` notation.

So, the only thing i'm asking is that the `mount all` does not require `container-name` when using the `-o` notation, the same behavior as with the full parameter parsing. Just some consistency in behaviour.

**Comment by vibhansa-msft** [comment]
when you are using the script there is no need to take dependency on fstab and you can write your mount command with all option in script itself. fstab entry could be very generic just to run the script.

**Comment by saulobejo** [comment]
Hi @vibhansa-msft 

this is not ideal because then I need one script per config file

by getting all options from fstab I have a single script and all configuration in fstab.

`/usr/bin/blobfuse2all`

```
#!/bin/bash

set -xeu

echo $@

mkdir -p /mnt/blobfuse/tmp/

sudo blobfuse2 mount all $@
```

`fstab`

```
/usr/bin/blobfuse2all /home/user/data/folder fuse ro,delay_connect,defaults,_netdev,allow_other,--config-file=/home/user/.blobfuse2/folder.yaml 0 0
```

With my solution, I just need to change the config file each line in `fstab`

with your solution I have to hard-code every single bash script with a config file and all parameters.

**Comment by vibhansa-msft** [comment]
We have also observed in past that 'mount all' does not work with fstab well. In mount all we need to fork multiple instances of blobfuse (one per container) and when binary is started through fstab it was not able to start those child processes successfully. So I doubt 'mount all' is a good candidate here for fstab. My suggestion will rather be starting script from fstab and in script have separate mount commands.

**Comment by saulobejo** [comment]
@vibhansa-msft 

I was able to run it successfully by using `sudo blobfuse2` (as referenced by another issue).

It only limitation was that it can only mount 120 containers.

And `mount -a` mounts new containers present in the config file. which is great.

**Comment by vibhansa-msft** [comment]
Again just a word of caution here. Mount all will start an instance of blobfuse per container. So even when you say you were able to mount 120 containers successfully it means there are 120 instances of blobfuse running on your system. We have not tested impact of this on system with this scale so far. If you wish to mount only selective containers, then there is a allow/reject filters to filter the containers before you decide to mount.

**Comment by vibhansa-msft** [comment]
Can you also share the link to the bug where "sudo" was mentioned as a solution to do mount all from fstab.

**Comment by saulobejo** [comment]
> If you wish to mount only selective containers, then there is a allow/reject filters to filter the containers before you decide to mount

That's exactly what I've done :)

**Comment by saulobejo** [comment]
> Can you also share the link to the bug where "sudo" was mentioned as a solution to do mount all from fstab.

#1053

**Comment by vibhansa-msft** [comment]
"mount all" from fstab will not work so we are not pursing this as of now. 
-o container name is something that does not make sense for mount all command so I do not understand what issue are we chasing here. When you run mount all from fstab its not able to parse the command correctly and it assumes its a mount command and hence it asks for container name. But when you run it from script it will work just fine.

**Comment by saulobejo** [comment]
@vibhansa-msft 

As discussed before, I want to be able to run a helping scrip, as it is supported, but wit mount all I stead of mount because I have 30 containers to mount at boot time and make 30 fstab entries and 30 helping scripts seems like a maintenance nightmare.

Furthermore, I ask the tool to be self consistent on its parameters requirements.

**Comment by vibhansa-msft** [comment]
I see there is some misunderstanding here.
in /etc/fstab you will have only one entry to run a script.
in script you will have only one command "blobfuse mount all <path> --config-file=<config.yaml>"
you do not need to provide any container name anywhere in this case. In the cofig file you can put accept/reject filters to mount only selective containers.
If you are using 30 entries in the fstab or 30 entries in script then you are mounting them individually and there is no question of "mount all" in that case.
-------------------------------------------
If you are mounting each container through a separate command (30 commands in your case) and config file for each of them differ then you can provide the container name in the config file itself.
Another option for the same is to pass the container name through cli which does not need any "-o" semantics and only setting --container-name shall be good enough. If "--container-name" is provided in fstab then automatically it will go with "-o" option (for which you don't have to do anything special).
