### ISSUE TITLE
Large file upload is slow via blobfuse2 streaming

### ISSUE THREAD

**Issue by cl33n** [Azure/azure-storage-fuse#1109]
### Which version of blobfuse was used?
blobfuse2 version: 2.0.2

### Which OS distribution and version are you using?
Rhel 6
2.6.32-754.49.1.el6.x86_64

### If relevant, please share your mount command.

blobfuse2 mount /var/azureblobmount --tmp-path /mnt/ramdisk/blobfuse2tmp/blobfuse2tmp --config-file=/usr/bin/azure-storage-fuse/setup/baseConfig.yaml

### What was the issue encountered?

File transfer process is very slow with rsync from on-prem storage to blob storage. It seems to upload at around 100kbps. This behavior is only observed with blobfuse; uploads via https to the same container are fine elsewhere on this network. 

Is there a better way to put files in the mount folder? 

See screenshot below. 

### Have you found a mitigation/solution?

Not yet - I can't get any helpful info from health monitor. Changing the cache and block sizes does not seem to help. 

### Please share logs if available.

# config yaml:

allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 10
  blocks-per-file: 3
  cache-size-mb: 1024

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: redacted
  container: redacted
  endpoint: https://redacted.blob.core.windows.net/
  mode: key
  account-key: redacted

health_monitor:
  enable-monitoring: true
  stats-poll-interval-sec: 10
  process-monitor-interval-sec: 30
  output-path: /usr/bin/azure-storage-fuse/
  monitor-disable-list:
    - memory_profiler

# screenshot of iftop during single file transfer (file is 171M)

Not sure what is happening here - could someone help explain this behavior or how to best troubleshoot? Should we expect blobfuse2 streaming to handle this any faster? 

The 20.150.43.196 IP is Microsoft - 

<img width="1722" alt="Screen Shot 2023-04-11 at 12 23 30 PM" src="https://user-images.githubusercontent.com/60489589/231241328-b84a47e3-35e4-4fa4-a92e-d77ac7a78d54.png">

**Comment by vibhansa-msft** [comment]
If your files are not very big in size you can use 'file-cache' instead of 'stream' mode. This will keep files in local cache and then upload/download in parallel. If the file size run into 100s of GB+ then you have to stick to your current config only.

**Comment by cl33n** [comment]
Thanks - I will update my config and post results.

**Comment by vibhansa-msft** [comment]
Did you get a chance to try this out, do let us know about the results.

**Comment by cl33n** [comment]
Hi - switching to file cache mode dramatically improved performance for my use case, uploads are now appropriate for the bandwidth. It seems that file cache mode is the way to go for users with many small files. Thank you! Sent from my iPhoneOn Apr 19, 2023, at 12:19 AM, Vikas Bhansali ***@***.***> wrote:﻿
Did you get a chance to try this out, do let us know about the results.

**Comment by vibhansa-msft** [comment]
Thanks @cl33n to confirm this. Yes file-cache is the way when you have small files to deal with. Streaming as a solution is applied only when you do not have enough of disk space to hold your files or files are too large and you are interested only in portion of it for your application processing.
