### ISSUE TITLE
How to correctly configure preparing configuration in Ephemeral OS Disks for Azure VM

### ISSUE THREAD

**Issue by jaelys** [Azure/azure-storage-fuse#1111]
### Which version of blobfuse was used?
v2

### Which OS distribution and version are you using?
ubuntu 22.04

### If relevant, please share your mount command.
/etc/fstab
omit ...
blobfuse2 /datadisk/video fuse defaults, _netdev, --config-file=/home/username/config.yaml, allow_other 0 0
/dev/disk/cloud/azure_resource-part1	/mnt	auto	defaults,nofail,x-systemd.requires=cloud-init.service,_netdev,comment=cloudconfig	0	2

### What was the issue encountered?

using Ephemeral OS disks for Azure VM and  always fail after reboot VM reboot, 

this/dev/disk/cloud/azure_resource-part1	/mnt ....	
This line will always be added to the last line after the reboot

### Have you found a mitigation/solution?

Using streaming config can succeed. 
But i can't use the Streaming config , because the streaming video cannot be written normally
Using File Cache config always fails. 
Maybe the reason is that it is impossible to create a cache folder?

### Please share logs if available.

allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /mnt/blobfuse2tmp
  timeout-sec: 0
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: xxxxxx
  account-key: xxxxxxxxx
  endpoint: xxxxxx.xxx.xxx
  mode: key
  container: video

**Comment by vibhansa-msft** [comment]
in file-cache config there is temp-path which you configure as your local disk-cache. In code we check if this path exists or not, and try to create it when it doesn't. As long as you have correct permissions on the path, blobfuse2 shall be able to create the path for itself on start. (/mnt/blobfuse2tmp)

**Comment by vibhansa-msft** [comment]
If the /mnt directory is getting created later (is what I understand from your description) then one possible way here might be to schedule a script on startup to get executed after some time which eventually executes the blobfuse mount.

**Comment by jaelys** [comment]
> If the /mnt directory is getting created later (is what I understand from your description) then one possible way here might be to schedule a script on startup to get executed after some time which eventually executes the blobfuse mount.

Can you guide me on how to write sh correctly, wait for Azure VM reboot Ephemeral OS Disks to be automatically mounted, and then execute blobfuse2 mount in /etc/fstab ?

I've tried but can't work out, I'm not very good at it .

Thanks for your reply.

**Comment by vibhansa-msft** [comment]
There are couple of ways to achieve what you are looking for
- in /etc/fstab mark blobfuse entry with "noauto". This means the mount will not be done automatically and once your system is fully up you just need to execute "sudo mount -a" and then whatever was left during reboot will execute resulting into blobfuse mount
- You can create a service for blobfuse. Sample service file is provided under ./setup directory in this repo. Creating a service is just few simple steps and you can easily find them on net. Use this service file as a sample and configure it according to your requirements. In the service file towards the end you will see "ExecStart" which actually executes the blobfuse mount command. Here you can replace it with "sleep 600 && blobfuse2 mount <other params that you give in mount>". This means when this service starts it will sleep for 600 seconds and then execute the mount command. This 600 seconds will give you buffer time to let your disk come online.

**Comment by jaelys** [comment]
Thank you very much for your help. I will implement your suggestions, but I face this directory when I face other container services, so many time difference problems must be solved.

I hope that Blobfuse2 can support automatic mounting on "Ephemeral OS DISKS for Azure VM" in the future,

Microsoft Azure document recommends BlobFuse2 Settings Substation

Thank you again, I turn off this Issue

**Comment by vibhansa-msft** [comment]
Blobfuse does not understand what base disk you are mounting it on so for us its just a regular path user has provided. It behaves like any regular file-system driver will behave. I do understand your concern with mounting here but being a general purpose tool we have no logic here to handle certain storage types in different manner.
To solve your problem one solution that i can propose in Blobfuse is to have some sort of delay parameter where mount will be done after some time compared to when mount is executed.
