### ISSUE TITLE
Unable to get blobfuse2 to work with Oracle RMAN backups

### ISSUE THREAD

**Issue by NYKoop** [Azure/azure-storage-fuse#1113]
Note: Commands and configuration were redacted below from their original values.

### Which version of blobfuse was used?
blobfuse2-2.0.2-1.x86_64
fuse3-3.6.1-4.el7.x86_64
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.16.0.0.0

### Which OS distribution and version are you using?
Red Hat 7.9
Kernel 3.10.0-1160.88.1.el7.x86_64

### If relevant, please share your mount command.
Blobfuse 1 command (this works): /usr/bin/blobfuse 'mount point' --container-name='container' --tmp-path='tmp path' --file-cache-timeout-in-seconds=0 -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o nonempty -o allow_root

Blobfuse2 command: blobfuse2 mount 'mount point' --config-file blobfuse2-config-filecache.yml
Blobfuse2 config file:
logging:
  type: base
  level: log_debug
  file-path: 'log path'

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: 'tmp path'
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: 'storage account'
  account-key: 'redacted'
  endpoint: https://'storage account'.blob.core.windows.net
  mode: key
  container: 'redacted

### What was the issue encountered?
I have been trying to get Oracle RMAN to work with blobfuse2. Originally I tried with a blobfuse2 stream configuration as I hoping to get away from using the tmp path and the stream mount is suggested for larger files. While I could mount, read/write files from the OS as the oracle user (same user that's running the blobfuse commands), RMAN didn't work when restoring and showed the error as shown below. So I tried with the file cache config to try to mimic the blobfuse1 mount. Exact tmp-path, container and keys were used, but shows the same error as below. RMAN is also run as user oracle so there should be any permission issues. However, oracle just can't seem to read them. As soon as I unmount and remount using blobfuse 1, it works fine. I'm hoping this is just something I need to add to my blobfuse2 config. There was no config file used for blobfuse1, just the command line args and environment variables set for the container and storage account settings.

### Have you found a mitigation/solution?
I have not other than to rollback to blobfuse 1.

### Please share logs if available.

**Here's the output from RMAN when trying to restore from the controlfile with blobfuse2:**
RMAN>  restore controlfile from 'path to control file';

 

Starting restore at 18-APR-23
using target database control file instead of recovery catalog
allocated channel: ORA_DISK_1
channel ORA_DISK_1: SID=3488 device type=DISK

 

RMAN-00571: ===========================================================
RMAN-00569: =============== ERROR MESSAGE STACK FOLLOWS ===============
RMAN-00571: ===========================================================
RMAN-03002: failure of restore command at 04/18/2023 13:48:38
RMAN-06172: no AUTOBACKUP found or specified handle is not a valid copy or piece

**Comment by vibhansa-msft** [comment]
Kindly share blobfuse log file to analyze this.

**Comment by vibhansa-msft** [comment]
In blobfuse2 logs I do not see any failure. There is one file which was opened and later closed successfully. Other than that there not much in logs. Is there any rman level logs clearly stating which file open/close/read/write was hit with failure or any reason it prints for failure.

**Comment by vibhansa-msft** [comment]
Config and mount command also looks clean to me. If you are not able to figure out the issue can you add "disable-writeback-cache: true" under 'libfuse' section in config file and try again.

**Comment by NYKoop** [comment]
Yes, I will give that setting a try as well.

Another thing I found is that while doing an ls in the blobfuse mount while mounted with blobfuse1, the original DB directory created while mounted as blobfuse2 stream shows up as a file and not a directory when mounted as blobfuse1 file cache. You also see 2 instances of the same filename.

-rwxrwx--- 1 oracle dba    0 Apr 13 13:58 DBNAME   <-- Created while mounted with blobfuse2 stream
-rwxrwx--- 1 oracle dba    0 Apr 13 13:58 DBNAME
drwxrwx--- 2 oracle dba 4096 Apr 18 11:46 DBNAME.temp <-- Created with blobfuse 1 file cache. The DBA can read the control file under this directory fine while mounted as blobfuse1 file cache.

Not to confuse things, but if I mount this container with blobfuse2 stream or file cache, I see DBNAME and DBNAME.temp as directories.

**Comment by vibhansa-msft** [comment]
Blobfuse 1/2 does not play around with any file/directory names. It will create it with the name it has recevied from kernel. So if you observe some difference here, may be for some reason your RMAN app is behaving different.

**Comment by vibhansa-msft** [comment]
"Tue Apr 18 13:46:17 EDT 2023 : blobfuse2[6900] : LOG_TRACE [libfuse_handler.go (415)]: Libfuse::libfuse_opendir : DBNAME.temp/" : As per this log application asked to open DBANE.temp directory only.

**Comment by NYKoop** [comment]
That opendir is from when I was doing an ls on that dir and not from RMAN. Furthermore, I did a sha256sum on the control file that was in there to make sure it was the same as the source. At that point, the file was cached. When RMAN went to read the file, there wasn't anything incremental in the log as the file was already in cache.

The "disable-writeback-cache: true" setting did not resolve the issue unfortunately.

**Comment by NYKoop** [comment]
Also, I asked if there was anything additional in the RMAN logs on this, but the DBA said no.

**Comment by vibhansa-msft** [comment]
can you add "-o allow_other" to mount command. This will allow any user to have access to that mount path and in case you are hitting any permission related issues, it might just work.

**Comment by NYKoop** [comment]
We tried with the allow-other set to true and it worked this time with blobfuse2. However, the rman command is being as user oracle, just like the blobfuse2 command is, so it doesn't really make sense why that would allow it to work. Is allow-other is doing something else besides exposing the mount to all users and setting the permissions to 777?

One thing we had enabled with blobfuse1 is allow_root. There doesn't appear to be such an option with blobfuse2 at least in the config file. Not sure if that has anything to do with why it is working with blobfuse1. I does look like allow_root is valid for fuse3 though.

Thanks again.

**Comment by NYKoop** [comment]
Also, I should be clear in that I don't want to have allow_other enabled. As a general security practice, we shouldn't be using mode 777, but I was fine with it for a test. I did also play around with the default-permissions setting, setting to 775, but that didn't work either.

**Comment by NYKoop** [comment]
Absolutely, I would love to build that and test it out.

**Comment by vibhansa-msft** [comment]
Do let me know if that fix works. I will merge the code changes after your confirmation only.

**Comment by NYKoop** [comment]
I pulled down your branch and am attempting to build now. I'll let you know how it goes.

git clone -b vibhansa/v2/allow_root https://github.com/Azure/azure-storage-fuse.git

**Comment by NYKoop** [comment]
Good news, that seemed to do the trick. I set allow-root to true in the config file. The DBA could do the restore with either stream or file cache mode with the compiled blobfuse2 binary. One thing to note, the mount directory itself becomes mode 777 with allow-root, but the files and directories in it are mode 775. Previously in blobfuse1, the mount dir was mode 775 as well with allow root. Just wondering if that's expected behavior.

Thank you!

**Comment by vibhansa-msft** [comment]
@NYKoop thats great. Thanks for giving a quick try and confirming that it works fine. Mount dir's permission shall not be an issue as file level permissions and libfuse settings will block other users. I will investigate on why mount dir permissions difference is there. I will go ahead and merge my PR and this part I can take care separately as this does not block anything.
