### ISSUE TITLE
Chown support for ADLS

### ISSUE THREAD

**Issue by mstair** [Azure/azure-storage-fuse#1117]
### Which version of blobfuse was used?
v2

### Which OS distribution and version are you using?
20.04

### If relevant, please share your mount command.
N/A

### What was the issue encountered?
Question about chown support for adls, the comment below suggests that it's on some roadmap (unclear if waiting on support  change on Azure storage side). Is there a possibility in the future that chown will work for adls mounts?

https://github.com/Azure/azure-storage-fuse/blob/e02acffd388092b6a88394799c863da9db870f25/component/attr_cache/attr_cache.go#L547 

### Have you found a mitigation/solution?
N/A

### Please share logs if available.
N/A

**Comment by vibhansa-msft** [comment]
If request here is to set 'x-ms-owner' and 'x-ms-group' blob properties for HNS account, then yes its in roadmap. Will look into how trivial it is to support this.

**Comment by vibhansa-msft** [comment]
I looked at the REST APIs, backend supports only GUID to be set as owner and group. In linux owner/group are integer values so there is co-relation here. If we somehow mask integer values to a random guid, on portal that guid might represent some SPN/user/resource and it might represent some invalid resource.

**Comment by vibhansa-msft** [comment]
I have the code changes to set the owner and group but due to backend limitation and no-relation between guid and user id in linux not able to complete the changeset.

**Comment by mstair** [comment]
Thank you for investigating. If `x-ms-owner` requires the AzureAD GUID, I wonder if conditional support could work if using AADSSHLoginForLinux for Azure VM user accounts. The AzureAD GUID for the user is available in `/etc/aadpasswd` (perhaps more elegantly through one of the adduser commands).

**Comment by vibhansa-msft** [comment]
Even if that works Blobfuse will have no way to get that. In linux when we try to get current user id or chown command is used to set a user:group the ids are integer numbers and not guids.

**Comment by mstair** [comment]
Understood. I tested out the setAccessControl REST with using user UPN (john.doe@contoso), which will be the username on the host, but as you note, the Linux id has no mapping. Attempting to pass the Linux id as `x-ms-owner` results in `The owner or group is not valid` error. Thanks again for the time.

**Comment by vibhansa-msft** [comment]
As this is not supported by the backend itself as of now, I will close this here. Once backend has the support we will revisit it.
