### ISSUE TITLE
Not able to read files written from blobfuse v2 mounted directory in blobfuse v1 mounted directory for same Blob storage

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [Azure/azure-storage-fuse#1119]
### Which version of blobfuse was used?
Both v1 and v2

### Which OS distribution and version are you using?
Ubuntu 20.04 for v2 and Ubuntu18.04 for v1

### What was the issue encountered?
I mounted the same blob container on 2 different machines. Files were written to the directory mounted with blobfuse v2 to directory: X/2.0_0/gen.json

When I attempt to read the same file from directory mounted in v1, it says the file doesn't exist. On checking for existence of X/2.0_0, the same error is raised. However, X exists, but doing ```ls X``` errors with "X is not a directory"

### Have you found a mitigation/solution?
I believe the issue is most likely the same as the one mentioned in https://github.com/Azure/azure-storage-fuse/pull/1065, however, the blobfuse v1 mounts are created automatically, and not under my control. So is there any way apart from the configuration to resolve this issue?

**Comment by vibhansa-msft** [comment]
This is because kernel is doing page caching and the subsequent read requests will not even land on blobfuse. To make this work you need both sides to have Ubn-20 distro running blobfuse2. Also, disable all kind of attribute, file and fuse related caching settings (set to 0). Let me know if that works for you.

**Comment by LakshyAAAgrawal** [comment]
Thanks a lot for your response.

In my particular situation, I do not have control over the VMs having Ubuntu 18 and blobfuse v1. I could try to create mount with different settings though.

Is there any way that this could work with blobfuse v1 or is it the case that once a blob container has been used with blobfuse v2, it becomes incompatible with blobfuse v1?

**Comment by vibhansa-msft** [comment]
With v1 there is no way to disable or explicitly clear the kernel cache. Only way there would be to manually execute a cli command to wipe out all the kernel cache when you wish to refresh the contents. "sysctl -w vm.drop_caches=3" is command to do the same.

**Comment by LakshyAAAgrawal** [comment]
Please correct me if I am wrong, but the kernel cache should only cause issues when a blobfuse v1 mount already exists, and new file is created, which is answered using the cache, and therefore giving the wrong output.

In my scenario, the VM is a newly created VM, with a new mount point with blobfuse1, and at the time the mount was created, the file X/2.0_0/gen.json already existed in the bob storage, verified by checking the Azure Data explorer.

**Comment by vibhansa-msft** [comment]
Once a mount is done and a file is read, kernel will cache the contents of file and next time you try to open and read the file it will be served from kernel cache. This cache will persist until kernel runs out of page cache or blobfuse is unmounted.
If you are starting a new vm and/or mounting blobfuse every time you read, then these cache issues shall not be the one you are hitting.

**Comment by LakshyAAAgrawal** [comment]
Thanks!

So apart from the kernel issue, could you suggest what are the potential ways I could resolve this under the given constraint that I have to use blobfuse v1 on Ubuntu 18.04?

**Comment by vibhansa-msft** [comment]
If your mount persists, then there are only two ways to clear the cache either manually using the command I posted earlier or by unmounting and remounting the blobfuse.

**Comment by LakshyAAAgrawal** [comment]
But as we just discussed, the issue cannot be due to the cache issues, since the VM in which this issue is occuring is a freshly created VM and therefore does not have the cache.

Could you please suggest if https://github.com/Azure/azure-storage-fuse/pull/1065 might be the underlying issue?

**Comment by vibhansa-msft** [comment]
'virtual-directory' is just to detect the directory and not related to any sort of content caching.
So when you say VM is newly created, does it mean VM is created and even for the first time when you try to read the file you get older contents? That should not happen. If first read was ok and any follow on reads results back with older contents then kernel has cached contents read as part of older contents. If you feel this is what happened then you can execute the command once to clear kernel cache and see contents are refreshed or not. Also, ensure all caching realted configs are set to 0 like "file-cache-timeout, attr-timeout, negative-timeout etc"

**Comment by LakshyAAAgrawal** [comment]
The scenario is as follows:
There is an existing blob storage account, on which a file has been created with the name X/2.0_0/gen.json, from blobfuse v2.

After this file has been created, I launch a fresh new VM, and mount the same blob storage using blobfuse v1. I expect that the file X/2.0_0/gen.json should be available in this machine, however, it says that the path doesn't exist. Further "X" is reported to be a file and not a directory.

> when you say VM is newly created, does it mean VM is created and even for the first time when you try to read the file you get older contents?

For the first read, the file is reported as non-existent by "Path does not exist". Its parent directory is reported to be a file. Doing "cat X" prints nothing. So in summary, in the fresh VM, even the first read of the file fails

**Comment by vibhansa-msft** [comment]
Is this HNS account or non-HNS. If HNS you need to configure both v1 and v2 with "--use-adls=true" flag. If non-hns then you need to configure v2 with "virtual-directory: true".
Also, from v2 when you write the file and upload can you see the file in portal or through any other means can you validate that file was indeed uploaded.

**Comment by LakshyAAAgrawal** [comment]
> Is this HNS account or non-HNS
In my blob storage settings: ```Hierarchical namespace Disabled```

> Also, from v2 when you write the file and upload can you see the file in portal or through any other means can you validate that file was indeed uploaded.
Yes, I am able to view the same file from other blobfuse v2 mounts across different machines, as well as in Azure Storage Explorer

> If non-hns then you need to configure v2 with "virtual-directory: true".
Sure! But what about the files that have already been written with the default configuration. Specifically, X/2.0_0/gen.json is a file created with blobfuse v2 mount, without the flag "virtual-directory: true". Is there any way to read this from v1?

**Comment by vibhansa-msft** [comment]
When you see "X/2.0_0/gen.json" from portal, can you validate if there is a blob called 'X' and inside 'X' a blob called '2.0_0' with a metadata called "hdi_isfolder: true"?

**Comment by vibhansa-msft** [comment]
you shall see both the directory and same name file in the portal, if not you can execute 'mkdir -p X/2.0_0' command on the v2 front where this container is mounted.

**Comment by vibhansa-msft** [comment]
Is this problem resolved or you are still hitting the issue.
