### ISSUE TITLE
Not able to rename a file after creation. 

### ISSUE THREAD

**Issue by michaelss7** [Azure/azure-storage-fuse#1125]
### Which version of blobfuse was used?
blobfuse2

### Which OS distribution and version are you using?
Rocky Linux 9

### If relevant, please share your mount command.
blobfuse2 /data/brazildata fuse delay_connect,defaults,--config-file=/usr/share/blobfuse2/brazildata_filecache_config.yaml

### What was the issue encountered?
Blob is mounted to Linux server using blobfuse2 and then shared via samba. When Samba share is accessed and a new file created it can't be renamed.  

### Have you found a mitigation/solution?
no solution found

### Please share logs if available.
This is the blobfuse2.log
Apr 27 09:14:26 vmprlbf03 blobfuse2[26355]: LOG_TRACE [datalake.go (328)]: Datalake::RenameFile : New Text Document (7).txt -> test.txt
Apr 27 09:14:26 vmprlbf03 blobfuse2[26355]: 2023/04/27 09:14:26 ==> REQUEST/RESPONSE (Try=1/1.937267ms, OpTime=2.0
08673ms) -- RESPONSE STATUS CODE ERROR#012   PUT https://storageaccountname.dfs.core.windows.net/brazildata/test.txt?mode=legacy&timeout=901#012   Authorization: REDACTED#012   User-Agent: [Azure-Storage-Fuse/2.0.2 (Rocky Linux 9
.1 (Blue Onyx)) Azure-Storage/0.1 (go1.16.2; linux)]#012   X-Ms-Client-Request-Id: [94aa5b10-f090-42e7-54b8-de0542
34d06e]#012   X-Ms-Rename-Source: [/brazildata/New Text Document (7).txt?]#012   X-Ms-Version: [2018-11-09]#012
x-ms-date: [Thu, 27 Apr 2023 09:14:26 GMT]#012   -----------------------------------------------------------------
---------------#012   RESPONSE Status: 400 The source URI is invalid.#012   Content-Length: [159]#012   Content-Type: [application/json;charset=utf-8]#012   Date: [Thu, 27 Apr 2023 09:14:25 GMT]#012   Server: [Windows-Azure-HDFS
/1.0 Microsoft-HTTPAPI/2.0]#012   X-Ms-Error-Code: [InvalidSourceUri]#012   X-Ms-Request-Id: [567eeb11-601f-0075-4
0e8-787c88000000]#012   X-Ms-Version: [2018-11-09]#012Response Details: {"error":{"code":"InvalidSourceUri","message":"The source URI is invalid.\nRequestId:567eeb11-601f-0075-40e8-787c88000000\nTime:2023-04-27T09:14:26.0749805Z
"}}
Apr 27 09:14:26 vmprlbf03 blobfuse2[26355]: LOG_ERR [datalake.go (342)]: Datalake::RenameFile : Failed to rename f
ile New Text Document (7).txt to test.txt [-> github.com/Azure/azure-storage-azcopy/v10/azbfs.newStorageError, /ho
me/cloudtest/go/pkg/mod/github.com/!azure/azure-storage-azcopy/v10@v10.13.1-0.20211218014522-24209b81028e/azbfs/zc
_storage_error.go:41#012===== RESPONSE ERROR (ServiceCode=InvalidSourceUri) =====#012Description=400 The source UR
I is invalid., Details: (none)#012   PUT https://storangeaccountname.dfs.core.windows.net/brazildata/test.txt?mode=l
egacy&timeout=901#012   Authorization: REDACTED#012   User-Agent: [Azure-Storage-Fuse/2.0.2 (Rocky Linux 9.1 (Blue
 Onyx)) Azure-Storage/0.1 (go1.16.2; linux)]#012   X-Ms-Client-Request-Id: [94aa5b10-f090-42e7-54b8-de054234d06e]#
012   X-Ms-Date: [Thu, 27 Apr 2023 09:14:26 GMT]#012   X-Ms-Rename-Source: [/brazildata/New Text Document (7).txt?
]#012   X-Ms-Version: [2018-11-09]#012   -------------------------------------------------------------------------
-------#012

The windows client produces the error
an unexpected error is keeeping you from renaming the folder. if you continue to receive this error, you can use the error code to search for heelp with this problem. 

Error0x8007045D; The request could not be performed because of an I/O device error.

The blobfuse2.yaml is
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /cache
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: adls
  account-name: accountname
  account-key: account key 
  endpoint: https://endpointname
  mode: key
  container: brazildata 

smb.conf
[global]
security = ads
idmap gid = 10000-3000000
idmap uid = 10000-3000000
template shell = /bin/bash
template homedir = /home/%U@%D
winbind enum users = yes
winbind enum groups = yes
winbind use default domain = yes
encrypt passwords = yes
log file = /var/log/samba/log.%m
max log size = 1000
dns proxy = no
workgroup = S7
realm = REALM
log level = 5

[brazil]
path = /data/brazildata
valid users = @"S7\Domain Users"
read list = @"S7\Domain Users"
write list = @"S7\Domain Users"
read only = no
browseable = yes
writable = yes
create mask = 0777
directory mask = 0777
inherit permissions = yes
force create mode = 0777
force directory mode = 0777

**Comment by vibhansa-msft** [comment]
are you able to rename from linux / WSL side and not from windows ? Can you just confirm the same failure is hit from linux shell as well.

**Comment by vibhansa-msft** [comment]
Is your account HNS enable or not ?

**Comment by vibhansa-msft** [comment]
I have verified rename flow works with HNS or non-HNS account fine, no errrors seen. This might be some permission related issue on Samba or windows-linux cross over. Kindly validate it works directly through linux shell.

**Comment by michaelss7** [comment]
thanks for the comments. I got it working. Not 100% sure what was wrong it was something in the Samba config I know that. I could write on the Linux server. It is a HNS enabled account.

**Comment by vibhansa-msft** [comment]
Great to hear it worked out for you. Thanks for the update.
