### ISSUE TITLE
blobfuse2 mount crashes when running vi

### ISSUE THREAD

**Issue by minhtrieu-aemo** [Azure/azure-storage-fuse#1127]
### Which version of blobfuse was used?
blobfuse2-2.0.3

### Which OS distribution and version are you using?
RHEL 8.6

### If relevant, please share your mount command.
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /mnt/resource/blobfuse2tmp_xxxxxx
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: adls
  account-name: xxxxxxxxxxx
  container: xxxxxxx
  endpoint: https://xxxxxxxxxxx.dfs.core.windows.net
  mode: msi
  objid: xxxxx-xxx-xxx-xx-xxxxx

### What was the issue encountered?
Server crashes when running "vi filename.txt" while on the  blobfuse2 mount. 
This does not happen with blobfuse 1.3
Storage account has Hierarchical namespace enabled. 

### Have you found a mitigation/solution?
None. Restart Server

**Comment by vibhansa-msft** [comment]
Just quickly tried to repeat the same test case with HNS account, not able to hit any crash. For me editing of file works fine.

```
vikas@vibhansa-ubn-vm:/usr/blob_mnt$ vim abcd.txt
vikas@vibhansa-ubn-vm:/usr/blob_mnt$ cat abcd.txt
sdf
asdf
asdf
asdf
```

When you say its working with blobfuse 1.3 can you check it was working with blobfuse2 2.0.2 also.

**Comment by vibhansa-msft** [comment]
If VIM is working and not vi, then it might be some permissions issue. Can you enable log debug and run this case with 2.0.3 where vi crashes just wanted to see what the log have to say about the flow.

**Comment by minhtrieu-aemo** [comment]
It appears to be random. I tried to vi a few times and it worked then I tried "vi boost.txt" it tried to save file then the server started to hang and become un-usable. I had to reboot. Attached is an extract of the log file when i was running "vi boost.txt" 
[blobfuselogfiles.txt](https://github.com/Azure/azure-storage-fuse/files/11352665/blobfuselogfiles.txt)

**Comment by vibhansa-msft** [comment]
What mode of auth you are using. In your log files I see a lot of auth related issues

```
Apr 28 20:14:13 sydprdinsrst01 blobfuse2[13401]: 2023/04/28 20:14:13 ==> REQUEST/RESPONSE (Try=1/10.572659ms, OpTime=10.677861ms) -- RESPONSE STATUS CODE ERROR#012   PUT https://storageaccountxxxxxx.dfs.core.windows.net/backup/minh/.boost.txt.swx?action=setAccessControl&timeout=901#012   Authorization: REDACTED#012   Use
r-Agent: [Azure-Storage-Fuse/2.0.3 (Red Hat Enterprise Linux 8.6 (Ootpa)) Azure-Storage/0.1 (go1.16.2; linux)]#012   X-Http-Method-Override: [PATCH]#012   X-Ms-Client-Request-Id: [d8dda6ff-1ab3-454f-7784-3ce8f2e42b72]#012   X-Ms-Group: []#012   X-Ms-Owner: []#012   X-Ms-Permissions: [rw-------]#012   X-Ms-Version: [2018-1
1-09]#012   --------------------------------------------------------------------------------#012   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.#012   Content-Length: [227]#012   Content-Type: [application/json;charset=utf-8]#012   Date: [Fri, 28 Apr 2023 10:14:13 GMT
]#012   Server: [Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0]#012   X-Ms-Error-Code: [AuthorizationPermissionMismatch]#012   X-Ms-Request-Id: [4ff91954-501f-0031-3eba-79929f000000]#012   X-Ms-Version: [2018-11-09]#012Response Details: {"error":{"code":"AuthorizationPermissionMismatch","message":"This request is not autho
rized to perform this operation using this permission.\nRequestId:4ff91954-501f-0031-3eba-79929f000000\nTime:2023-04-28T10:14:13.5357025Z"}}
```

**Comment by vibhansa-msft** [comment]
As per original thread you are using MSI I believe. Ensure you have "Storage blob data contributor" role assigned to this identity on your storage account.

**Comment by minhtrieu-aemo** [comment]
The user assigned managed identity does have the "Storage blob data contributor" role assigned to the storage account. 
The Linux server has 2 user-assigned managed identity and the objid has the correct managed identity object id matching the identity used to access the storage account.

**Comment by vibhansa-msft** [comment]
Closing this as there are no updates. If you were able to resolve the issue kindly share the resolution here to help other users facing the same issue.

**Comment by Raibows** [comment]
I have the same issue. Any vim/rsync operations with the files in blobfuse2, the container is going to crash, where I'm using the Azure ITP service. I cannot easily get the log of blobfuse2 because the container has already crashed if you do these operations. 😭

Any advice? Thanks @vibhansa-msft

**Comment by vibhansa-msft** [comment]
Can you collect core dump or trace logs to debug this further. If container is crashing then try mounting on the host vm and collect the logs.
