### ISSUE TITLE
Unable to mount blobfuse2 using fstab

### ISSUE THREAD

**Issue by minhtrieu-aemo** [Azure/azure-storage-fuse#1128]
### Which version of blobfuse was used?
blobfuse2-2.0.3

### Which OS distribution and version are you using?
RHEL 8.6

### If relevant, please share your mount command.
blobfuse config file: 

allow-other: true

logging:
type: syslog
level: log_debug

components:

libfuse
file_cache
attr_cache
azstorage
libfuse:
attribute-expiration-sec: 120
entry-expiration-sec: 120
negative-entry-expiration-sec: 240

file_cache:
path: /mnt/blobfuse2tmp_backup
timeout-sec: 120
max-size-mb: 4096

attr_cache:
timeout-sec: 7200

azstorage:
type: adls
account-name: xxxxxxxxxxx
container: xxxxxxx
endpoint: https://xxxxxxxxxxx.dfs.core.windows.net/
mode: msi
objid: xxxxx-xxx-xxx-xx-xxxxx

### What was the issue encountered?
I have already reviewed https://github.com/Azure/azure-storage-fuse/issues/921 and still cant get it to work.

When running "mount /backup" or "mount -a" i get the following error
mount: /backup: wrong fs type, bad option, bad superblock on blobfuse2, missing codepage or helper program, or other error.

/etc/fstab file contains 
blobfuse2 /backup fuse defaults,_netdev,--config-file=/etc/blobfuse2/backup.yaml,allow_other 0 0

If i run the following command in the shell it works. 
blobfuse2 /backup --config-file=/etc/blobfuse2/backup.yaml

### Have you found a mitigation/solution?
No solution found yet.

**Comment by vibhansa-msft** [comment]
blobfuse2 /backup **_fuse3_** defaults,_netdev,--config-file=/etc/blobfuse2/backup.yaml,allow_other 0 0
Can you make this change and give it a try.

**Comment by minhtrieu-aemo** [comment]
Fantastic, its working! Thanks!
