### ISSUE TITLE
Blobfuse2 in AKS not working

### ISSUE THREAD

**Issue by sarav-ks** [Azure/azure-storage-fuse#1134]
### Which version of blobfuse was used?
blobfuse2 version 2.0.3
fusermount3 version 3.9.0

### Which OS distribution and version are you using?
Ubuntu 20.04
AKS version 1.24.10
packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
apt-get libfuse3-dev fuse3

### If relevant, please share your mount command.
blobfuse2 --foreground -d mount /home/usb/azblob --config-file=/home/usb/fuse-config.yaml --log-level=LOG_DEBUG

### What was the issue encountered?
```
FUSE library version: 3.9.0
nullpath_ok: 0
fuse: device not found, try 'modprobe fuse' first
Error: unable to start pipeline [failed to mount fuse]
```

### Have you found a mitigation/solution?
No solution 

### Please share logs if available.

$ ls -ltr /home/usb
drwxrwxrwx 1 usb usb 4096 May 7 15:08 azblob

$ls -ltr /tmp/
drwxrwxrwx 1 usb usb 4096 May 7 15:08 blobfuse

**Config**

```
allow-other: true

logging:

  type: syslog

  level: log_debug

components:

  - libfuse

  - file_cache

  - attr_cache

  - azstorage

 

libfuse:

  attribute-expiration-sec: 120

  entry-expiration-sec: 120

  negative-entry-expiration-sec: 240

  fuse-trace: true

file_cache:

  path: /tmp/blobfuse

  timeout-sec: 120

  max-size-mb: 4096

attr_cache:

  timeout-sec: 7200

azstorage:

  type: block

  account-name: sasdxxxaks01

  container: storage

  endpoint: https://sasxxxxxks01.blob.core.windows.net/

  mode: spn

  tenantid: eef9573xxxxx1ddff9335b5b

  clientid: ec17ca0c-xxxx86-40a8fcb7d3cd

  sdk-trace: true

  clientsecret: <replace-with-akv>
```

**Logs:**

```
Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_CRIT [mount.go (401)]: Starting Blobfuse2 Mount : 2.0.3 on [Ubuntu 20.04.1 LTS]

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_CRIT [mount.go (402)]: Logging level set to : LOG_TRACE

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [libfuse.go (234)]: Libfuse::Configure : libfuse

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [libfuse.go (226)]: Libfuse::Validate : UID 1000, GID 1000

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [libfuse.go (280)]: Libfuse::Configure : read-only false, allow-other true, allow-root false, default-perm 511, entry-timeout 120, attr-time 120, negative-timeout 240, ignore-open-flags: true, nonempty false

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [file_cache.go (199)]: FileCache::Configure : file_cache

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [file_cache.go (275)]: FileCache::Configure : Using default eviction policy

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [file_cache.go (297)]: FileCache::Configure : create-empty false, cache-timeout 120, tmp-path /tmp/blobfuse, max-size-mb 4096, high-mark 80, low-mark 60

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [attr_cache.go (121)]: AttrCache::Configure : attr_cache

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [attr_cache.go (145)]: AttrCache::Configure : cache-timeout 7200, symlink false, cache-on-list true

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [config.go (271)]: ParseAndValidateConfig : Parsing config

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [config.go (373)]: ParseAndValidateConfig : using the following proxy address from the config file:

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [config.go (377)]: ParseAndValidateConfig : sdk logging from the config file: true

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [config.go (480)]: ParseAndReadDynamicConfig : Reparsing config

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [config.go (468)]: ParseAndValidateConfig : Account: sasxxxaks01, Container: storageupat, AccountType: BLOCK, Auth: SPN, Prefix: , Endpoint: https://sasxxxxx1.blob.core.windows.net/, ListBlock: 0, MD5 : false false, Virtual Directory: true, Disable Compression: false

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [config.go (472)]: ParseAndValidateConfig : Retry Config: Retry count 5, Max Timeout 900, BackOff Time 4, Max Delay 60

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [block_blob.go (209)]: BlockBlob::TestPipeline : Validating

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [utils.go (222)]: SDK : ==> OUTGOING REQUEST (Try=1)

   GET https://sasxxxxaks01.blob.core.windows.net/storageupat?comp=list&delimiter=%2F&maxresults=2&restype=container&timeout=901

   Authorization: REDACTED

   User-Agent: [Azure-Storage-Fuse/2.0.3 (Ubuntu 20.04.1 LTS) Azure-Storage/0.14 (go1.16.2; linux)]

   X-Ms-Client-Request-Id: [c6c7c7-d0a88c800c33]

   X-Ms-Version: [2020-08-04]

 

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [utils.go (222)]: SDK : ==> REQUEST/RESPONSE (Try=1/68.873006ms, OpTime=96.536232ms) -- RESPONSE SUCCESSFULLY RECEIVED

   GET [https://sasxxxxaks01.blob.core.windows.net/storageupat?comp=list&delimiter=%2F&maxresults=2&restype=container&timeout=901](https://sasdlc1zaks01dudsreaks01.blob.core.windows.net/storageupat?comp=list&delimiter=%2F&maxresults=2&restype=container&timeout=901)

   Authorization: REDACTED

   User-Agent: [Azure-Storage-Fuse/2.0.3 (Ubuntu 20.04.1 LTS) Azure-Storage/0.14 (go1.16.2; linux)]

   X-Ms-Client-Request-Id: [c6c7c7758c800c33]

   X-Ms-Version: [2020-08-04]

   --------------------------------------------------------------------------------

   RESPONSE Status: 200 OK

   Content-Type: [application/xml]

   Date: [Sun, 07 May 2023 15:49:31 GMT]

   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]

   X-Ms-Client-Request-Id: [c6c7c775-d0a88c800c33]

   X-Ms-Request-Id: [e78840e3-803c33000000]

   X-Ms-Version: [2020-08-04]

 

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [mount.go (411)]: mount: Mounting blobfuse2 on /home/usb/azblob

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [azstorage.go (164)]: AzStorage::Start : Starting component azstorage

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [attr_cache.go (103)]: AttrCache::Start : Starting component attr_cache

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [file_cache.go (142)]: Starting component : file_cache

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [lru_policy.go (108)]: lruPolicy::StartPolicy

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [libfuse.go (140)]: Libfuse::Start : Starting component libfuse

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [libfuse_handler.go (117)]: Libfuse::initFuse : Initializing FUSE3

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [lru_policy.go (261)]: lruPolicy::ClearCache

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [libfuse_handler.go (160)]: Libfuse::initFuse : Registering fuse callbacks

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [libfuse_handler.go (164)]: Libfuse::initFuse : Populating fuse arguments

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_TRACE [libfuse_handler.go (188)]: Libfuse::populateFuseArgs

**Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_INFO [libfuse_handler.go (176)]: Libfuse::initFuse : Mounting with fuse3 library

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_ERR [libfuse_handler.go (179)]: Libfuse::initFuse : failed to mount fuse

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_ERR [libfuse.go (154)]: Libfuse::Start : Failed to init fuse [failed to mount fuse]

Sun May  7 15:49:32 UTC 2023 : blobfuse2[42] : LOG_ERR [mount.go (546)]: mount: error unable to start pipeline [failed to mount fuse]**
```

**Comment by sarav-ks** [comment]
$ ls -ltr `which blobfuse2`
-rwxr-xr-x 1 root root 24241884 Apr 27 09:39 /usr/bin/blobfuse2

$ ls -ltr `which fusermount`
lrwxrwxrwx 1 root root 11 Mar 7 2020 /usr/bin/fusermount --> fusermount3

**Comment by sarav-ks** [comment]
after installing 'modprobe' .. i run the below

```
$ modprobe fuse
modprobe: FATAL: Module fuse not found in directory /lib/modules/5.4.0-1104-azure
```

**Comment by vibhansa-msft** [comment]
What error do you get on console when the mount fails. As per the logs you have shared above, blobfuse is not able to initialize the fuse driver so there shall be some issue with installation or configuration of that.  you can add "fuse-trace: true" under libfuse config in config file and "foreground: true" on top of the config file. This will enable libfuse traces and run the binary in foreground so your shell will start showing errors coming from libfuse as well. Press "ctrl + c" if you feel your shell is stuck even after error has been reported on the console.

**Comment by vibhansa-msft** [comment]
Oh my bad, I see you have tried this already and its saying "modprobe fuse" not found. Can you try installing both fuse and fuse3 on the system and then give it a try, may be something wrong with the installation part here.

**Comment by sarav-ks** [comment]
@vibhansa-msft  Thanks a lot for your reply . To give some additional context , i am running the 'blobfuse2' command manually with in the kubernetes pod  using the 'kubectl exec' command .

Because the 'modprobe' command above mentioned the missing '5.4.0-1104-azure' , i installed the below manually 

`apt-get install linux-image-5.4.0-1104-azure`

I will add the 'fuse' along with 'fuse3 ' and will update the result shortly .

**Comment by sarav-ks** [comment]
@vibhansa-msft  , i am getting the below error when trying to install 'fuse' and 'fuse3' on the same docker image

```
The following packages have unmet dependencies
 fuse3 : Breaks :  fuse
```

Below is my dockerfile content ..

```
RUN apt-get update
RUN apt-get install sudo wget dpkg
RUN sudo wget --no-check-certificate https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
RUN sudo dpkg -i packages-microsoft-prod.deb
RUN sudo apt-get install libfuse3-dev fuse3 fuse kmod linux-image-5.4.0-1104-azure
RUN sudo apt-get install blobfuse2
```

**Comment by sarav-ks** [comment]
After the changes , i am still getting the same error . Below are the latest error and the logs 

**Error** 
```
$ blobfuse2  mount /home/usb/azblob --config-file=/home/usb/fuse-config.yaml --log-level=LOG_DEBUG --foreground
FUSE library version: 3.9.0
nullpath_ok: 0
fuse: device not found, try 'modprobe fuse' first
Error: unable to start pipeline [failed to mount fuse]
```
**Logs**

$ cat /home/usb/.blobfuse2/blobfuse2.log
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_CRIT [mount.go (401)]: Starting Blobfuse2 Mount : 2.0.3 on [Ubuntu 20.04.1 LTS]
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_CRIT [mount.go (402)]: Logging level set to : LOG_DEBUG
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [libfuse.go (234)]: Libfuse::Configure : libfuse
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [libfuse.go (226)]: Libfuse::Validate : UID 1000, GID 1000
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [libfuse.go (280)]: Libfuse::Configure : read-only false, allow-other true, allow-root false, default-perm 511, entry-timeout 120, attr-time 120, negative-timeout 240, ignore-open-flags: true, nonempty false
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [file_cache.go (199)]: FileCache::Configure : file_cache
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [file_cache.go (275)]: FileCache::Configure : Using default eviction policy
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [file_cache.go (297)]: FileCache::Configure : create-empty false, cache-timeout 120, tmp-path /tmp/blobfuse, max-size-mb 4096, high-mark 80, low-mark 60
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [attr_cache.go (121)]: AttrCache::Configure : attr_cache
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [attr_cache.go (145)]: AttrCache::Configure : cache-timeout 7200, symlink false, cache-on-list true
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [config.go (271)]: ParseAndValidateConfig : Parsing config
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [config.go (373)]: ParseAndValidateConfig : using the following proxy address from the config file:
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [config.go (377)]: ParseAndValidateConfig : sdk logging from the config file: true
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [config.go (480)]: ParseAndReadDynamicConfig : Reparsing config
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [config.go (384)]: ParseAndValidateConfig : Getting auth type
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [config.go (468)]: ParseAndValidateConfig : Account: sasxxxxks01, Container: storageupat, AccountType: BLOCK, Auth: SPN, Prefix: , Endpoint: https://sasxxxxxxaks01.blob.core.windows.net/, ListBlock: 0, MD5 : false false, Virtual Directory: true, Disable Compression: false
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [config.go (472)]: ParseAndValidateConfig : Retry Config: Retry count 5, Max Timeout 900, BackOff Time 4, Max Delay 60
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [azauth.go (79)]: azAuth::getAzAuth : Account: sasxxxxxxaks01, AccountType: BLOCK, Protocol: https, Endpoint: https://sasxxxxxxxxeaks01.blob.core.windows.net/
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [azauthspn.go (105)]: azAuthBlobSPN::getCredential : SPN Token retrieved xxxxxxxx
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [block_blob.go (209)]: BlockBlob::TestPipeline : Validating
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [utils.go (222)]: SDK : ==> OUTGOING REQUEST (Try=1)
   GET https://sasdxxxxxreaks01.blob.core.windows.net/storageupat?comp=list&delimiter=%2F&maxresults=2&restype=container&timeout=901
  Authorization: REDACTED
   User-Agent: [Azure-Storage-Fuse/2.0.3 (Ubuntu 20.04.1 LTS) Azure-Storage/0.14 (go1.16.2; linux)]
   X-Ms-Client-Request-Id: [xxxxxxx]
   X-Ms-Version: [2020-08-04]

Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [utils.go (222)]: SDK : ==> REQUEST/RESPONSE (Try=1/23.906387ms, OpTime=48.992513ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET https://sasdlcxxxxxxxaks01.blob.core.windows.net/storageupat?comp=list&delimiter=%2F&maxresults=2&restype=container&timeout=901
   Authorization: REDACTED
   User-Agent: [Azure-Storage-Fuse/2.0.3 (Ubuntu 20.04.1 LTS) Azure-Storage/0.14 (go1.16.2; linux)]
   X-Ms-Client-Request-Id: [xxxxxx]
   X-Ms-Version: [2020-08-04]

   --------------------------------------------------------------------------------

   RESPONSE Status: 200 OK
   Content-Type: [application/xml]
   Date: [Mon, 08 May 2023 14:00:50 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [xxxxx]
   X-Ms-Request-Id: [xxxxxxx]
   X-Ms-Version: [2020-08-04]

Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [mount.go (411)]: mount: Mounting blobfuse2 on /home/usb/azblob
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [mount.go (500)]: mount: foreground enabled
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [mount.go (540)]: Mount::runPipeline : blobfuse2 pid = 34, transfer pipe = /tmp/transferPipe_34, polling pipe = /tmp/pollPipe_34
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [azstorage.go (164)]: AzStorage::Start : Starting component azstorage
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [attr_cache.go (103)]: AttrCache::Start : Starting component attr_cache
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [file_cache.go (142)]: Starting component : file_cache
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [lru_policy.go (108)]: lruPolicy::StartPolicy
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [lru_policy.go (261)]: lruPolicy::ClearCache
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [libfuse.go (140)]: Libfuse::Start : Starting component libfuse
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [libfuse_handler.go (117)]: Libfuse::initFuse : Initializing FUSE3
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [libfuse_handler.go (160)]: Libfuse::initFuse : Registering fuse callbacks
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [libfuse_handler.go (164)]: Libfuse::initFuse : Populating fuse arguments
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_TRACE [libfuse_handler.go (188)]: Libfuse::populateFuseArgs
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [libfuse_handler.go (229)]: Libfuse::populateFuseArgs : opts : blobfuse2
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [libfuse_handler.go (229)]: Libfuse::populateFuseArgs : opts : /home/usb/azblob
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [libfuse_handler.go (229)]: Libfuse::populateFuseArgs : opts : -o
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [libfuse_handler.go (229)]: Libfuse::populateFuseArgs : opts : entry_timeout=120,attr_timeout=120,negative_timeout=240,allow_other
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [libfuse_handler.go (229)]: Libfuse::populateFuseArgs : opts : -f
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [libfuse_handler.go (229)]: Libfuse::populateFuseArgs : opts : -ofsname=blobfuse2
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [libfuse_handler.go (229)]: Libfuse::populateFuseArgs : opts : -okernel_cache
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_DEBUG [libfuse_handler.go (229)]: Libfuse::populateFuseArgs : opts : -d
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_INFO [libfuse_handler.go (176)]: Libfuse::initFuse : Mounting with fuse3 library
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_ERR [libfuse_handler.go (179)]: Libfuse::initFuse : failed to mount fuse
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_ERR [libfuse.go (154)]: Libfuse::Start : Failed to init fuse [failed to mount fuse]
Mon May  8 14:00:51 UTC 2023 : blobfuse2[34] : LOG_ERR [mount.go (546)]: mount: error unable to start pipeline [failed to mount fuse]

**Comment by sarav-ks** [comment]
@vibhansa-msft  , is it mandatory to run the kubernetes deployment in 'privilaged' for 'blobfuse2' to work ?

i tried running the below with 'sudo' , still getting the same error ..

```
`$ sudo blobfuse2  mount /home/usb/azblob --config-file=/home/usb/fuse-config.yaml --log-level=LOG_DEBUG --foreground
`
FUSE library version: 3.9.0
nullpath_ok: 0
fuse: device not found, try 'modprobe fuse' first
Error: unable to start pipeline [failed to mount fuse]
```

**Comment by andyzhangx** [comment]
> @vibhansa-msft , is it mandatory to run the kubernetes deployment in 'privilaged' for 'blobfuse2' to work ?
> 
> i tried running the below with 'sudo' , still getting the same error ..
> 
> ```
> `$ sudo blobfuse2  mount /home/usb/azblob --config-file=/home/usb/fuse-config.yaml --log-level=LOG_DEBUG --foreground
> `
> FUSE library version: 3.9.0
> nullpath_ok: 0
> fuse: device not found, try 'modprobe fuse' first
> Error: unable to start pipeline [failed to mount fuse]
> ```

@sarav-ks I think you could try kubectl-enter, ssh to the node
```
sudo wget https://raw.githubusercontent.com/andyzhangx/demo/master/dev/kubectl-enter
sudo chmod a+x ./kubectl-enter
./kubectl-enter <node-name>
```

**Comment by sarav-ks** [comment]
@andyzhangx , Thanks for the reply . Is it mandatory to have 'SYS_ADMIN' **OR** privileged access  for 'blobfuse2' to work in kubernetes ? 

If that is the case, then we can't use 'blobfuse2' in our cluster since the policy will block privileged access . 

can someone confirm if they are able to use 'blobfuse2' with out requiring 'privileged' access in AKS ?

**Comment by sarav-ks** [comment]
No , i am not using the 'csi' driver . Instead i am running the below command on my 'init-container' to mount the blob

`blobfuse2  mount /home/usb/azblob --config-file=/home/usb/fuse-config.yaml --log-level=LOG_DEBUG --foreground
`

which is when i am getting the below error , full log attached in my earlier message above 

```
FUSE library version: 3.9.0
nullpath_ok: 0
fuse: device not found, try 'modprobe fuse' first
Error: unable to start pipeline [failed to mount fuse]
```

**Comment by andyzhangx** [comment]
@sarav-ks it requires privilege permission, refer to blob csi driver setting: https://github.com/kubernetes-sigs/blob-csi-driver/blob/025414bd5f68dc34ff2a3ea96b531832036134fc/deploy/csi-blob-node.yaml#L158-L159

**Comment by sarav-ks** [comment]
Thanks for the confirmation about the 'csi' driver , since i am not using the CSI driver and directly executing the 'blobfuse2' command as a init command inside the container .  Do i still need 'privilege permission' ?

**Comment by andyzhangx** [comment]
@sarav-ks I think yes, you could try on one testing cluster to verify first.

**Comment by vibhansa-msft** [comment]
'SYS_ADMIN' is mandatory to run blobfuse inside any sort of container, otherwise the container will not get privilege to interact with fuse driver module.

**Comment by vibhansa-msft** [comment]
Yes its possible, as its showing its not able to find out fuse module. Did you try adding SYS_ADMIN privileges ?

**Comment by sarav-ks** [comment]
Since running the k8 workload with SYS_ADMIN privilege is a big NO NO in many of production environment due the security risks , I am really surprised about this requirement .

I have seen other AKS discussions in this forum like [this](https://github.com/Azure/azure-storage-fuse/issues/1079) , wondering if they also running with 'SYS_ADMIN' privilege

**Comment by vibhansa-msft** [comment]
AKS would already be running with SYS_ADMIN to support blobfuse. @andyzhangx that's correct assumption, right?

**Comment by andyzhangx** [comment]
> AKS would already be running with SYS_ADMIN to support blobfuse. @andyzhangx that's correct assumption, right?

that's correct.

**Comment by sarav-ks** [comment]
@vibhansa-msft  @andyzhangx  It is NOT about AKS have cluster has the admin rights , it is about pod / deployment that is going to mount the storage account using 'blobfuse' need SYS_ADMIN privilege or not ?

For example , i am **not** allowed to add the below to **my** pod / deployment 

```
          securityContext:
            privileged: true
```

**Comment by andyzhangx** [comment]
> @vibhansa-msft @andyzhangx It is NOT about AKS have cluster has the admin rights , it is about pod / deployment that is going to mount the storage account using 'blobfuse' need SYS_ADMIN privilege or not ?
> 
> For example , i am **not** allowed to add the below to **my** pod / deployment
> 
> ```
>           securityContext:
>             privileged: true
> ```

@sarav-ks yes, that's what I mean. And blob csi driver has this setting the driver pod deployment, so it works.

**Comment by sarav-ks** [comment]
Can you please add the 'SYS_ADMIN' privilege requirement as a prerequisite for 'blobfuse2' at https://github.com/Azure/azure-storage-fuse#limitations

**Comment by vibhansa-msft** [comment]
[like]  Vikas Bhansali reacted to your message:
________________________________

**Comment by sarav-ks** [comment]
@vibhansa-msft  @andyzhangx  I wanted to add another usecase where 'blobfuse2' is NOT working even with 'root' user on a Docker container .

For example , i build a docker image with **'root' user** as below 

```
From ubuntu:20.04
User root

RUN apt-get update
RUN apt-get install sudo wget dpkg
RUN sudo wget --no-check-certificate https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
RUN sudo dpkg -i packages-microsoft-prod.deb
RUN sudo apt-get install libfuse3-dev fuse3 fuse kmod linux-image-5.4.0-1104-azure
RUN sudo apt-get install blobfuse2
```

I use the above image and create a K8 pod , and 'exec' into the pod and run the below command 

`blobfuse2  mount /home/usb/azblob --config-file=/home/usb/fuse-config.yaml --log-level=LOG_DEBUG`

Still getting the below error ..

```
FUSE library version: 3.9.0
nullpath_ok: 0
fuse: device not found, try 'modprobe fuse' first
Error: unable to start pipeline [failed to mount fuse]
```

In this usecase , even if the user root has all the SYS_ADMIN privilege , still the mount is not working ..

**Comment by vibhansa-msft** [comment]
Can you refer to [this](https://github.com/Azure/azure-storage-fuse/blob/main/docker/buildandruncontainer.sh) file, which shows how to mount manually on a container, and validate you are passing down all correct options.

**Comment by andyzhangx** [comment]
> @vibhansa-msft @andyzhangx I wanted to add another usecase where 'blobfuse2' is NOT working even with 'root' user on a Docker container .
> 
> For example , i build a docker image with **'root' user** as below
> 
> ```
> From ubuntu:20.04
> User root
> 
> RUN apt-get update
> RUN apt-get install sudo wget dpkg
> RUN sudo wget --no-check-certificate https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
> RUN sudo dpkg -i packages-microsoft-prod.deb
> RUN sudo apt-get install libfuse3-dev fuse3 fuse kmod linux-image-5.4.0-1104-azure
> RUN sudo apt-get install blobfuse2
> ```
> 
> I use the above image and create a K8 pod , and 'exec' into the pod and run the below command
> 
> `blobfuse2 mount /home/usb/azblob --config-file=/home/usb/fuse-config.yaml --log-level=LOG_DEBUG`
> 
> Still getting the below error ..
> 
> ```
> FUSE library version: 3.9.0
> nullpath_ok: 0
> fuse: device not found, try 'modprobe fuse' first
> Error: unable to start pipeline [failed to mount fuse]
> ```
> 
> In this usecase , even if the user root has all the SYS_ADMIN privilege , still the mount is not working ..

it needs following k8s config to make it work:
 ```
           securityContext:
             privileged: true
 ```
