### ISSUE TITLE
Weird interaction between rsync and blobfuse2

### ISSUE THREAD

**Issue by dwr-psandhu** [Azure/azure-storage-fuse#1138]
### Which version of blobfuse was used?
2.0.3

### Which OS distribution and version are you using?
Centos 8

### What was the issue encountered?
As rsync is running the statistics using Storage Explorere on the blob directory show that the blobs are being copied, however it shows a similar number of deleted blobs of around the same size ??
![rsync_blobfuse2_interaction](https://github.com/Azure/azure-storage-fuse/assets/11561317/81913d35-5938-4da5-a76c-bc71e7c997e7)

Another perhaps unrelated issue. The cache size keeps growing beyond the specification in the config. In this case its 32 G but it has grown to 35G already.

### Have you found a mitigation/solution?
Don't use rsync and use cp instead?

**Comment by vibhansa-msft** [comment]
This is an application behavior and not something controlled by Blobfuse. Blobfuse being a file-system driver just respond back to the filesystem calls it gets from kernel. If application asks it to rename or delete a file, it will execute corresponding REST call on storage. You might want to check on the expectations from your application/rsync here.

**Comment by dwr-psandhu** [comment]
That is quite right. According to rysnc https://rsync.samba.org/how-rsync-works.html, it copies to temporary file on receiver and then does a rename at the end resulting in the above behavior

@vibhansa-msft What about the temporary cache growing beyond the specified size ? It causes the disk to fill up. Only happens with rsync and not with say cp.

**Comment by vibhansa-msft** [comment]
When the configured disk size reaches 80% we start evicting files from cache early. But all cache eviction logic in blobfuse works only if there are no open handles for any given file. So if your application keeps the file handles open then those files can not be deleted. As and when you create/open a new file those files will be created in temp cache in addition and hence you might see that we are overrunning the configured cache. You need to check from the application side on why files are kept open.
