### ISSUE TITLE
AKS mount out of sync

### ISSUE THREAD

**Issue by rmacian** [Azure/azure-storage-fuse#1139]
### Which version of blobfuse was used?

Aks blob csi driver
### Which OS distribution and version are you using?

```
NAME                                 STATUS   ROLES   AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-common-42199410-vmss00000b       Ready    agent   4h8m   v1.25.6   10.240.0.111   <none>        Ubuntu 22.04.2 LTS   5.15.0-1036-azure   containerd://1.6.18+azure-1
```

### If relevant, please share your mount command.
Is mounted with a persitent volume 
```
  csi:
    driver: blob.csi.azure.com
    nodeStageSecretRef:
      name: blob-logger
      namespace: nt-system
    volumeAttributes:
      containerName: databricks-logs
    volumeHandle: blob-logger-databricks-logs
  mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
```

### What was the issue encountered?
I am using a blob container to store logs from Azure Databricks and mounting it inside an AKS pod. When the databricks jobs end I can see the last logged line in the blob container but inside the mount  I am missing the last lines. I thought it might be some caching but after an hour the last lines are not seen.

### Have you found a mitigation/solution?
Restarting the pod with the mount seems to sync the blob and I can see the previous missing lines

**Comment by vibhansa-msft** [comment]
You will need to disable attribute caching both at kernel level and at blobfuse level otherwise kernel will keep reflecting the older data only. Add below cli options and then try it out:
"-o attr_timeout=0, -o entry_timeout=0, -o negative_timeout=0, --use-attr-cache=false, --file-cache-timeout=0"

**Comment by rmacian** [comment]
Hi, thank you for the quick response. I modified my persistent volume and it looks like this now:

```
  mountOptions:
  - -o allow_other
  - -o attr_timeout=0
  - -o entry_timeout=0
  - -o negative_timeout=0
  - --use-attr-cache=false
  - --file-cache-timeout=0
  - --file-cache-timeout-in-seconds=120
```
I restarted my pod using this pv but the same happens. I don't know if I am missing something. What I have to do to apply those mount options?

**Comment by vibhansa-msft** [comment]
"- --file-cache-timeout=0
  - --file-cache-timeout-in-seconds=120" : these two are contradictory, just use the first one and remove second one completly from your cli options. Can you also confirm what OS distro you are using. If you are running on a fuse2 compatible system then kernel page cache will not get invalidated automatically while on fuse3 compatible system it might work. If you are not sure about what system you are running you can enable log_debug on blobfuse and logs will point what fuse version is being used.

**Comment by vibhansa-msft** [comment]
Closing this assuming this is sorted out. Feel free to reopen if the issue still persists.

**Comment by rmacian** [comment]
After disabling caches we are incurring in high transactions on the storage account and Azure charged us a huge bill because of the List and Create container operations.

We have seen over 40.000 transactions over 5 minutes and the cost is not assumible.

We have tried to go back to caches and the transactions decreased an order of mangitude but We are now lossing again the last lines of each log file

**Comment by vibhansa-msft** [comment]
Disabling cache will result into high number of calls to storage and that means higher $ value in bill.
If you observe its just the listing which is causing more issues you can keep the attribute cache for a shorter expiry time so that every single call does not hit the storage.

**Comment by rmacian** [comment]
I am on 1.25.6 and I have read some similar issues like https://github.com/Azure/azure-storage-fuse/issues/1171
which parameters will be a compromise for not having listing excesive charges. I can live with up to a 10 minutes delay in logs but I need that they come in. With 
`  mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120`
The logs from the blob don't appear even after the two minutes and this sounds to me like the issue commented above

**Comment by vibhansa-msft** [comment]
Kindly upgrade to blobfuse2 for new host of features and performance optimizations. If you wish to supress automatic listing on mount then giving a timeout of few seconds for "--cancel-list-on-mount-seconds=<timeout>" CLI option shall be good enough. 
File-cache timeout is a different thing and it governs for how long files locally cached on your system stays valid.

**Comment by rmacian** [comment]
As the issue commented above fuse2 does not fix the issue. I have tested on 2.0.5

**Comment by vibhansa-msft** [comment]
Can you upgrade to 2.1.0 version and use fuse3, couple of direct_io based issues were fixed in this verison.

**Comment by rmacian** [comment]
The problem is that We are using this on AKS. AKS nodes have their internal "kernel image" which is basically the snapshot of a Ubuntu image that have a specific package versioning provided by Azure.

For example the latest node image at this moment is 5.15.0-10342-azure which has fuse 2.0.5.
My working nodes have fuse 2.0.2 and I should know "upgrade" all nodes to have the latest version which was not planned for our production environments at this moment.

It's the direct_io the only way to have this working ? with 2.0.5 it will run fine ?

**Comment by vibhansa-msft** [comment]
with direct_io and 2.1.0 image you shall get the contents updated as expected. However 2.1.0 is not yet released on the AKS side so you might need to wait for their next release. Till that time if you can figure out a way to upgrade blobfuse on node to 2.1.0 atleast you can try out your test case. Its Ubuntu image only so "sduo apt install blobfuse2" shall work I beleieve, otherwise you can reach out to AKS team if they can provide anyother way to upgrade explicitly.

**Comment by rmacian** [comment]
I can confirm with that this is not working for me. Data is written to the storage account in azure every 5 minutes. I can see the data created the first time but when data is updated on the storage account this is not refreshed in my pod. A sync over the file updates the content but I cannot do that every time I need to read the logs.

 config on my persistentVolume:
```
...
   volumeAttributes:
      containerName: databricks-logs
      protocol: fuse2
    volumeHandle: blob-logger-databricks-logs
  mountOptions:
  - -o allow_other
  - -o attr_timeout=0
  - -o entry_timeout=0
  - -o negative_timeout=0
  - -o direct_io
  - --use-attr-cache=false
  - --file-cache-timeout=0
  - --cancel-list-on-mount-seconds=10
  - --log-level=LOG_WARNING
```
using fuse 2.0.5 in AKS v1.25.6 with latest node image, at this moment, 5.15.0-1042-azure

**Comment by vibhansa-msft** [comment]
with 2.0.5 direct_io has some issues. As conveyed earlier you need to try it out with 2.1.0. Either you can manually upgrade it (if possible) or only other way is to clone the code and build it locally.

**Comment by rmacian** [comment]
At this moment the azure support recomendation is 'use nfs instead'
I

**Comment by Nemeczek** [comment]
> At this moment the azure support recomendation is 'use nfs instead'

Hey did you get any further than that? My airflow dags are failling after around 15 days claiming files are missing from the PV, PVC in AKS. I tried the same config you posted to no avail xD

**Comment by vibhansa-msft** [comment]
Can you try with latest AKS and blobfuse version and see if that solves the issue. There were issues related to direct_io which have been fixed off late.

**Comment by Nemeczek** [comment]
> Can you try with latest AKS and blobfuse version and see if that solves the issue. There were issues related to direct_io which have been fixed off late.

if we have:
```
 "storageProfile": {
          "blobCSIDriver": {
            "enabled": true
          },
```
and we are on stable ClusterUpgradeChannel do we need to take any action to have it upgraded?
