### ISSUE TITLE
Very slow cross-region upload performance using Stream mode for large files

### ISSUE THREAD

**Issue by pk-rescale** [Azure/azure-storage-fuse#1141]
### Which version of blobfuse was used?
Blobfuse2 2.0.3

### Which OS distribution and version are you using?
Centos 7.9

### If relevant, please share your mount command.
blobfuse2 mount /blob_mount --config-file=config.yaml

### What was the issue encountered?
When mounting cross-region (Azure US east VM mounting blob on Azure US west or vice-versa), uploads (VM to blob) specifically for large files are very slow (200-500 KB/s) with blobfuse2.  This is only true for uploads + cross-region with large files (multiple GBs size and up).  Downloads + cross-region are fine and much faster (20-50 MB/s as expected) for the same files and same two regions.

I don't see this discrepancy for uploads within-region, only uploads + cross-region.  Also, uploads seem to be very "jumpy"; the upload speed will be 0 for a while, and then suddenly show a large jump. This suggests to me that maybe latency is somehow is the culprit?  Since cross-region downloads with blobfuse2 are reasonably fast, can we somehow get comparable performance for cross-region uploads?

I've tried cp, rsync, etc.; all transfer methods show the same poor cross-region large-file upload performance.

VM = Azure D8s v3 (4 vcpus, 16 GiB memory).  Scaling up the VM to a more powerful machine does not seem to help.

### Have you found a mitigation/solution?
No

Here is my config.yaml file:

Begin config.yaml:
----------------
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 64
  max-buffers: 128
  buffer-size-mb: 64
  blocks-per-file: 5
  cache-size-mb: 4096

attr_cache:
  timeout-sec: 120
  no-cache-on-list: true
  no-symlinks: true

azstorage:
  max-concurrency: 4
  type: block
  account-name: *******
  account-key: *******
  endpoint: ********
  mode: key
  container: ******

**Comment by vibhansa-msft** [comment]
yes you can give it a try.

**Comment by pk-rescale** [comment]
Does my config.yaml file look OK as far as stream options?  Anything I can change that might improve upload performance?

I'll post the blobfuse log contents and azcopy test results shortly.

**Comment by vibhansa-msft** [comment]
yes streaming config looks ok to me. Streaming option is inherently slow in blobfuse as of now, so you shall expect slow upload/download speeds with this. This feature is to be used only when the file sizes are very large like 100s of GBs. If you have enough disk space to hold your files, better to use file-cache.

**Comment by pk-rescale** [comment]
Thanks, just a quick update -- I'm going to directly compare 3 methods for large ~(10-100 GB) size files:

- Blobfuse2 w/ Stream mode
- Blobfuse2 w/ Cache mode
- Azcopy

I'll report the results back here.

**Comment by vibhansa-msft** [comment]
Closing this as this requires some perf testing. Feel free to reopen when the required data is available.
