### ISSUE TITLE
Chown does not change the owner of mount point for ADLS gen 2 account

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-storage-fuse#1147]
### Which version of blobfuse was used?
blobfuse2

### Which OS distribution and version are you using?
Ubuntu20, RHEL 7.9

### If relevant, please share your mount command.
sudo blobfuse2 mount ~/mycontainer --config-file=./config.yaml

allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage
libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /var/blobfuse2
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:

  type: adls
  account-name: yangsheneastus111
  account-key: XXXXXpHL+Q/HhyTRjaRZ6vv/Nv6NUCC6CdCaEZQ8+ASt2XKKzA==
  endpoint: https://yangsheneastus111.dfs.core.windows.net
  mode: key
  container: container1
  virtual-directory: true

### What was the issue encountered?

According to document, dfs endpoint should support chown. 
https://learn.microsoft.com/en-us/azure/storage/blobs/blobfuse2-what-is

I tried to run cmd "chown myftp ./mycontainer", it does not throw any error but the owner of the directory did not change.

### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
'chown' is not supported by backend (to change ownership of the files) and hence blobfuse just ignores that operation. Its documented in the README on this repo. To get error you can configure a flag which says "return error for unsupported operations" which is meant to fail chmod and chown in unsupported scenarios. Reason to keep this behind a flag and not return error always is, there are tools (like git clone) which executes this command and fails if we return failure while most customers are ok to ignore these errors.
