### ISSUE TITLE
Failure of `mount all` (Error: accepts 1 arg(s), received 2)

### ISSUE THREAD

**Issue by luc-j-bourhis** [Azure/azure-storage-fuse#1150]
### Which version of blobfuse was used?
2.0.3

### Which OS distribution and version are you using?
Ubuntu 20.04.5 LTS

### If relevant, please share your mount command.
```
blobfuse2 mount all --config-file=/etc/azure.yaml /media/azure/
```

### What was the issue encountered?
```
Mounting container : XXXX to path  /media/azure/XXXX
Failed to mount container XXXX : Error: accepts 1 arg(s), received 2

Mounting container : YYYY to path  /media/azure/YYYY
Failed to mount container YYYY : Error: accepts 1 arg(s), received 2
```

### Have you found a mitigation/solution?
No

### Please share logs if available.
```
May 24 12:44:09 LimmatPC blobfuse[2476177]: Using syscall to detect directory is already mounted or not
May 24 12:44:09 LimmatPC blobfuse[2476177]: Account name found
May 24 12:44:09 LimmatPC blobfuse[2476177]: Account Key found
May 24 12:44:09 LimmatPC blobfuse[2476177]: Container name found
May 24 12:44:09 LimmatPC blobfuse[2476177]: Setting logging level to : LOG_WARNING
May 24 12:44:09 LimmatPC blobfuse[2476177]: ** Delaying tls init to post fork for older libcurl version
May 24 12:44:09 LimmatPC blobfuse[2476177]: ** Delaying authentication to post fork for older curl versions
May 24 12:44:09 LimmatPC blobfuse[2476180]: ** Post fork authentication for older libcurl version
```

### Configuration file (`/etc/azure.yaml` above)
```
logging:
  type: syslog
  level: log_info

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /var/cache/azure
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: AAAA
  account-key: KKKK
  endpoint: https://AAAA.blob.core.windows.net/
  mode: key
```

### Further information
If I add a line `container: test` to section `azurestorage` in the configuration file above, then
```
blobfuse2 mount --config-file=/etc/azure.yaml /media/azure/test
```
works fine.

**Comment by luc-j-bourhis** [comment]
Complement of information: in `/media/azure` above, the `mount all` command did create the directories corresponding to the blob containers. All of them. But they are empty.

**Comment by vibhansa-msft** [comment]
There are few things we need to sort-out before we jump on the actual issue:
- Logs shared are from blobfuse (v1) and not blobfuse2 so they do not provide any hint on why it failed. Kindly share correct logs.
- When you say "blobfuse2 mount --config-file=/etc/azure.yaml /media/azure/test" works, this is mounting only one container and not all, so this is bound to work.
- Emptry directories for each container will be created before we start mounting each container individually so those emptry directories are expected.

What we need to check here is why mount all is failing. Can you try "blobfuse2 mount all /media/azure/ --config-file=/etc/azure.yaml" instead and see if that works. We expect the mount path to be the first argument always in mount and mount all commands.

**Comment by luc-j-bourhis** [comment]
`blobfuse2 mount all /media/azure/ --config-file=/etc/azure.yaml` works! Thanks for solving the problem. But then I would suggest you fail early if an option appears before a non-option because the error message I got is frankly not telling me what is the actual problem.

As for the log, I had tried blobfuse v1 just before and got confused about the time. There is nothing in syslog then from blobfuse v2. I guess because I set the level too low. Thanks again!

**Comment by vibhansa-msft** [comment]
Command help string would have given you hint on the error. However, the command parsing is done through cobra library (third party) and we do not have much control over it. Will look if we can provide some log/error in case options are in wrong order.

**Comment by andmis** [comment]
You seem to really like the "user error" tag.

**Comment by vibhansa-msft** [comment]
Just help us collect statistics on how many bugs we really fixed (out of closed ones) vs how many could have been solved with better documentation. If there is anything that you want blobfuse to fix you can always argue over the tag and in past we have converted a 'user-error' to 'bug'.
