### ISSUE TITLE
[Issue]: `Unmount` command fails to unmount mounts

### ISSUE THREAD

**Issue by Lddeiva** [Azure/azure-storage-fuse#1151]
### Which version of blobfuse was used?
[BlobFuse2](https://github.com/Azure/azure-storage-fuse/releases/download/blobfuse2-2.0.3/blobfuse2-2.0.3-RHEL-7.5.x86_64.rpm)

### Which OS distribution and version are you using?
RHEL 7.7

### If relevant, please share your mount command.
sudo blobfuse2 unmount all

### What was the issue encountered?
![image](https://github.com/Azure/azure-storage-fuse/assets/61077834/d1d4a58c-943d-4673-8e6d-84d4f628b8ff)

### Have you found a mitigation/solution?
No. It worked in one of the mounts but didn't work in this mount. Tried running command as user, sudo and root.

### Please share logs if available.
NA

> The blob fuse logs must throw more understandable errors to troubleshoot the errors.

**Comment by vibhansa-msft** [comment]
Instead of "unmount all" can you try just unmounting this particular mount point and see what error it reports.
Generally we have seen if there is a console connected to the mount path then it fails to unmount.

**Comment by Lddeiva** [comment]
@vibhansa-msft , We have seen this error when tried unmounting a single mount. We used the command `sudo blobfuse2 unmount ~/mycontainer`.

![image](https://github.com/Azure/azure-storage-fuse/assets/61077834/baf376e7-66bb-47bf-a931-d83f0556a6c9)

Can the blobfuse2 driver display more detailed errors?
