### ISSUE TITLE
Unavailability of blobfuse2 package for RHEL 7.x on the Microsoft package repository

### ISSUE THREAD

**Issue by Lddeiva** [Azure/azure-storage-fuse#1155]
### Which version of blobfuse was used?
blobfuse2

### Which OS distribution and version are you using?
![image](https://github.com/Azure/azure-storage-fuse/assets/61077834/4f028df6-61ff-4254-857a-a166e40e6ca2)

### What was the issue encountered?
Package `blobfuse2` is not available for RHEL 7 on the Microsoft package repository. It is mentioned in the documentation https://learn.microsoft.com/en-us/azure/storage/blobs/blobfuse2-how-to-deploy?tabs=RHEL that it is available while it is not.

### Have you found a mitigation/solution?
Yes, I had to download the rpm package from https://github.com/Azure/azure-storage-fuse/releases and install it manually.

### Please share logs if available.

![image](https://github.com/Azure/azure-storage-fuse/assets/61077834/bb3219ac-7d5c-4aa0-850b-5fa59c7dc5e4)

> Can the `blobfuse2` package be published to RHEL 7 editions in the Microsoft package repository?https://packages.microsoft.com/config/rhel/

**Comment by vibhansa-msft** [comment]
We do not publish to 7.4 version, you can take image from 7.5 or 7.8 path. Or try using "7".

**Comment by Lddeiva** [comment]
I tried with 7 before opening this issue but it didn't work. Then, I used 7.4 but the error remains same.

Also, I am unable to find 7.5 and 7.8.
![image](https://github.com/Azure/azure-storage-fuse/assets/61077834/63e68169-dd95-44e9-a5f7-01f0c12b4980)

![image](https://github.com/Azure/azure-storage-fuse/assets/61077834/241c5357-7876-401c-bb83-8a110f52df69)

**Comment by souravgupta-msft** [comment]
@Lddeiva, can you follow the steps mentioned [here](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Installation#install-from-aptyum-package-repositories). Let me know if this works or not.

**Comment by Lddeiva** [comment]
> @Lddeiva, can you follow the steps mentioned [here](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Installation#install-from-aptyum-package-repositories). Let me know if this works or not.

No, it doesn't work.
![image](https://github.com/Azure/azure-storage-fuse/assets/61077834/57cb3848-0e45-4c78-be24-b7a54006f450)

**Comment by souravgupta-msft** [comment]
You can get the binary for RHEL 7.5 from [here](https://packages.microsoft.com/rhel/7.5/prod/Packages/b/blobfuse2-2.0.3.x86_64.rpm).

**Comment by souravgupta-msft** [comment]
@Lddeiva, kindly check the previous step and let us know if it works or not.

**Comment by souravgupta-msft** [comment]
Closing this as the binary can be downloaded from the shared link. Feel free to reopen if the issue persists.
