### ISSUE TITLE
Copying 10GB file into mounted volume (from the WSL2 host) results in Out of Memory error

### ISSUE THREAD

**Issue by luffjr** [Azure/azure-storage-fuse#1158]
### Which version of blobfuse was used?
2.0.3

### Which OS distribution and version are you using?
Microsoft Windows Server 2022 Datacenter Azure Edition
WSL2
Ubuntu 22.04.2 LTS

### If relevant, please share your mount command.
blobfuse2 mount /home/ipvadmin/fusemount --config-file=./blobfuseconfig.yaml --foreground -d

Config:
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 10
  blocks-per-file: 3
  cache-size-mb: 512

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: redacted
  container: redacted
  endpoint: https://redacted.blob.core.windows.net
  mode: key
  account-key: redacted

health_monitor:
  enable-monitoring: true
  stats-poll-interval-sec: 10
  process-monitor-interval-sec: 30
  output-path: /home/ipvadmin/blobfuse2logs/

### What was the issue encountered?
I get an out of memory error when copying a 10GB bin file from the host to the mount via WSL, the error is almost immediate from when the copy starts. It works fine when copying a 1GB bin file.

My server (host) only has 8GB memory total, but it crashes with 1.2GB free available memory.
![image](https://github.com/Azure/azure-storage-fuse/assets/29471937/bf8ea495-0135-4088-8067-b06462393f87)

What's interesting is the copy still appears to be going but if I refresh the mount from the host side I get an error, CPU usage on the linux side is still relatively high and the memory on the linux side continues to drop to about 100MB free.
![image](https://github.com/Azure/azure-storage-fuse/assets/29471937/ee271e9c-3063-441b-a5f3-2baa7d60ba06)

### Have you found a mitigation/solution?
No. I tried lowering the cache-size-mb from 1024MB to 512MB

### Please share logs if available.
FUSE library version: 3.10.5
nullpath_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.34
flags=0x33fffffb
max_readahead=0x00020000
   INIT: 7.31
   flags=0x0041f039
   max_readahead=0x00400000
   max_write=0x00100000
   max_background=128
   congestion_threshold=96
   time_gran=1
   unique: 2, success, outsize: 80
unique: 4, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 103
getattr[NULL] /
   unique: 4, success, outsize: 120
unique: 6, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 103
opendir flags: 0x28000 /
   opendir[824644936832] flags: 0x28000 /
   unique: 6, success, outsize: 32
unique: 8, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 103
opendir flags: 0x28000 /
   opendir[824644936960] flags: 0x28000 /
   unique: 8, success, outsize: 32
unique: 10, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
releasedir[824644936832] flags: 0x0
   unique: 10, success, outsize: 16
unique: 12, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 103
opendir flags: 0x28000 /
   opendir[824644937088] flags: 0x28000 /
   unique: 12, success, outsize: 32
unique: 14, opcode: READDIRPLUS (44), nodeid: 1, insize: 80, pid: 110
readdirplus[824644936960] from 0
   unique: 14, success, outsize: 216
unique: 16, opcode: READDIRPLUS (44), nodeid: 1, insize: 80, pid: 110
readdirplus[824644936960] from 1
   unique: 16, success, outsize: 16
unique: 18, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 103
readdir[824644936960] from 1
   unique: 18, success, outsize: 16
unique: 20, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 103
getattr[NULL] /
   unique: 20, success, outsize: 120
unique: 22, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
releasedir[824644936960] flags: 0x0
   unique: 22, success, outsize: 16
unique: 24, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
releasedir[824644937088] flags: 0x0
   unique: 24, success, outsize: 16
unique: 26, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 110
opendir flags: 0x28000 /
   opendir[824638103680] flags: 0x28000 /
   unique: 26, success, outsize: 32
unique: 28, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
releasedir[824638103680] flags: 0x0
   unique: 28, success, outsize: 16
unique: 30, opcode: LOOKUP (1), nodeid: 1, insize: 51, pid: 206
LOOKUP /10GB-3.bin
getattr[NULL] /10GB-3.bin
   unique: 30, success, outsize: 144
unique: 32, opcode: CREATE (35), nodeid: 1, insize: 67, pid: 206
create flags: 0x280c2 /10GB-3.bin 0100644 umask=0022
   create[139860509725248] flags: 0x280c2 /10GB-3.bin
getattr[139860509] /10GB-3.bin
   NODEID: 3
   unique: 32, success, outsize: 160
unique: 34, opcode: ACCESS (34), nodeid: 3, insize: 48, pid: 206
   unique: 34, error: -38 (Function not implemented), outsize: 16
unique: 36, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 206
getattr[NULL] /
   unique: 36, success, outsize: 120
unique: 38, opcode: STATFS (17), nodeid: 3, insize: 40, pid: 206
statfs /10GB-3.bin
   unique: 38, success, outsize: 96
unique: 40, opcode: OPEN (14), nodeid: 3, insize: 48, pid: 206
open flags: 0x28001 /10GB-3.bin
   open[139860509725280] flags: 0x28002 /10GB-3.bin
   unique: 40, success, outsize: 32
unique: 42, opcode: GETXATTR (22), nodeid: 3, insize: 68, pid: 206
   unique: 42, error: -38 (Function not implemented), outsize: 16
unique: 44, opcode: SETATTR (4), nodeid: 3, insize: 128, pid: 206
truncate[139860509] 10485760000
**fatal error: runtime: out of memory**

runtime stack:
runtime.throw(0xe8a333, 0x16)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sysMap(0xc004000000, 0x274000000, 0x1534b10)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x151b480, 0x271000000, 0x42fad7, 0x151b488)
        /usr/local/go/src/runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0x151b480, 0x138800, 0x0)
        /usr/local/go/src/runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0x151b480, 0x138800, 0xc000000100, 0x7f33e6ffc990)
        /usr/local/go/src/runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:910 +0x59
runtime.systemstack(0x7f33e6ffc9a8)
        /usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1246

**Comment by souravgupta-msft** [comment]
Hi @luffjr. Can you try the given operation using file cache component instead of stream and let me know how it goes. 
Also, can you disable the health monitor section (just for testing now) in your config. If this goes well, you can enable it back.

**Comment by luffjr** [comment]
Hi @souravgupta-msft , I changed my configuration to the below. When I copy a 10GB file over to /home/ipvadmin/blobfusecache/, blobfuse2 no longer crashes and I retain access to the WSL filesystem from within Windows. The file appears in my /fusemount/ location (which is mounted to Azure Blob Storage) almost straight away after the copy starts but the file never gets synced to Azure Blob Storage. For my implementation to function correctly, I need to make sure that the file is synchronised to Azure Blob Storage as soon as possible as I will have several other nodes with this set up, any of which could require access to the file that has been created/copied to Azure Blob Storage.

allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /home/ipvadmin/blobfusecache/
  timeout-sec: 120
  max_size_mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: redacted
  container: redacted
  endpoint: redacted
  mode: key
  account-key: redacted

**Comment by souravgupta-msft** [comment]
> When I copy a 10GB file over to /home/ipvadmin/blobfusecache/, blobfuse2 no longer crashes and I retain access to the WSL filesystem from within Windows.

`/home/ipvadmin/blobfusecache/` is your local cache directory. You should copy the file to your mounted directory `/home/ipvadmin/fusemount` and not your cache.

**Comment by luffjr** [comment]
Thanks @souravgupta-msft - I had doubts as blobfuse2 started crashing again so I switched to copying to the cache - but now it's working fairly well as far as I can tell. I'll run some more tests tomorrow and close this issue if all okay.

**Comment by souravgupta-msft** [comment]
@luffjr, can you confirm if the suggested changes are working well.

**Comment by souravgupta-msft** [comment]
Closing this as it is not an issue anymore. Feel free to reopen if issue persists.
