### ISSUE TITLE
Issues writing to blob storage: corrupt data

### ISSUE THREAD

**Issue by trexx00** [Azure/azure-storage-fuse#1159]
### Which version of blobfuse was used?
blobfuse2 version: 2.0.3

### Which OS distribution and version are you using?
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

### If relevant, please share your mount command.
sudo blobfuse2 mount /mnt/devblobs/admirian  --config-file=/home/azureuser/configs/fuse_connection_devetlsa_admirian.yaml

### What was the issue encountered?
when writing files larger than trivail size (15g is this case) NULLs (/x00) characters are being writted to the file. Thus the line counts and data do not match.
I'm using an awk script to transform a file. Running it directly to the blobfuse mount gives the above error. Using a local target the file writes fine.
File is a pipe delimited csv

### Have you found a mitigation/solution?
No. Even after successfully generating the file locally, the cp command has the same issue and the destination file is invalid

### Please share logs if available.
Attaching current yaml config file. Tried various settings to no avail

**Comment by souravgupta-msft** [comment]
@trexx00, I have removed the config file attachment from the description since the access keys were exposed. Kindly rotate your storage account access key at the earliest and reshare the config after redacting the account credentials.

**Comment by souravgupta-msft** [comment]
Can you try the same operation using file cache instead of streaming. You can refer [this](https://github.com/Azure/azure-storage-fuse/blob/main/sampleFileCacheConfig.yaml) config file for adding the file_cache component.

**Comment by souravgupta-msft** [comment]
Also please share the logs if the operation fails.

**Comment by souravgupta-msft** [comment]
I am unable to replicate this. I tried the following steps:

1. Copy a 15 GB file from local to mounted directory.
2. Compute md5sum of the local file.
3. Cleared file cache directory.
4. Compute md5sum of the file in the mounted directory.
5. Compare the md5sum results. They were matching implying that upload was successful and there was no data corruption.

Can you also try to compute and compare the md5sum of the file in local and mounted directory.

**Comment by souravgupta-msft** [comment]
@trexx00, can you try the above steps and let me know how it goes.

**Comment by vibhansa-msft** [comment]
Closing this as there are no updates. Feel free to reopen once you have the required information.

**Comment by trexx00** [comment]
I went back and tested using the md5sum method. This  did work correctly. However I believe it lead me to the root cause of the issue.
The issue occurs when both the source and destination are both on the mounted drive. IT looks that both the source and destination files are cached. In my case, with the 30G root drive working with 1 15G file essentially had to cache it twice, cause a space failure. The 2 x 5G is bigger than the 29G available on the disk. The cache is cleared immediately after, so space looks fine immediately after error.
Can you confirm this is blobfuse behaviour ?

Also in my config file, the cache setting is:
file_cache:
  path: /datadisk1/tempcache
  timeout-sec: 120
  max-size-mb: 4096

Should this not limit cache to 4G, ? How to limit this caching size to control this issue ?
Thanks

**Comment by vibhansa-msft** [comment]
Yes, by default if the space available is 80%+ utilized then blobfuse will start deleting the files which are currently not in use. That being said there is a catch here. If you have allocated 4GB of disk space through config and try to open a file which is much beyond that size, blobfuse does not block that operation (assuming user needs this file). So it ends up downloading the file and then moment you try to access another file it will detect disk is over utilized then delete this big file. If the file handle to this big file is still open then blobfuse cannot delete it from the disk and it will remain. This kind of inflates the disk usage compared to what you have configured. In short, these things are expected by-design.
If you are trying to compare 2 15GB files then you shall always have space bigger than what it needs to accommodate both of them in disk.
