### ISSUE TITLE
How to refine syscall.EIO error message?

### ISSUE THREAD

**Issue by RobinLin666** [Azure/azure-storage-fuse#1160]
### Which version of blobfuse was used?
v1/v2

### Which OS distribution and version are you using?
Ubuntu 18.04/20.04

### What was the issue encountered?
When the http request error, such as 400/500 error, we will get an Input/Output error when use Python os API.
But I want to show the detail in python's exception, so I think I need refine or customize the error message of blobfuse, not just syscall.EIO.
How to do?

Thank you very much!

**Comment by souravgupta-msft** [comment]
Blobfuse being a CLI tool cannot display the entire stack trace or error details for 400/500 http responses. In your case, can parsing the log file help because logs contain the entire stack trace.

**Comment by RobinLin666** [comment]
Thanks for your reply, I cannot parse the log file because we don't know when users will call Python to read and write mounted files.

**Comment by souravgupta-msft** [comment]
I will discuss this internally with my team and let you know what can be done here.

**Comment by souravgupta-msft** [comment]
Blobfuse is a virtual file-system driver, so it has to return back standard errors to Linux kernel. We cannot send internal azure errors to console here. Only way is to check the logs.
