### ISSUE TITLE
Null Error: when attempting to mount a container

### ISSUE THREAD

**Issue by Sosby** [Azure/azure-storage-fuse#1164]
### Which version of blobfuse was used?
2.0.3

### Which OS distribution and version are you using?
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"

### If relevant, please share your mount command.
blobfuse2 mount /mnt/bfusetmp --config-file=$HOME/connection.yaml --tmp-path=/home/bfuse2-tmp --log-level=log_debug

Here's the config yaml 

components:
  `-` azstorage

file_cache:
  path: $HOME/bfuse2-tmp

azstorage:
  type: block
  account-name: saaccttest1
  container: upgrade7
  endpoint: https://redacted.blob.core.windows.net
  mode: msi
  sdk-trace: true

### What was the issue encountered?
Trying to mount a container but receiving an error but the error is not displayed.  Not sure why it's erroring at this point.  The logs don't reveal too much either.

 blobfuse2 mount /mnt/bfusetmp --config-file=$HOME/connection.yaml --tmp-path=/home/bfuse2-tmp --log-level=log_debug

Error: 

From the command line run, all thats output is what you see above, Error:

Now, if I add foreground: true to the config, I don't receive an error, I get a return code of 0 from the command, however, nothing is mounted and when I do a blobfuse2 mount list, no mounts are displayed.

### Have you found a mitigation/solution?
No workaround so far.

### Please share logs if available.

Jun 01 16:44:40  blobfuse2[17072]: LOG_CRIT [mount.go (401)]: Starting Blobfuse2 Mount : 2.0.3 on [Ubuntu 18.04.6 LTS]
Jun 01 16:44:40  blobfuse2[17072]: LOG_CRIT [mount.go (402)]: Logging level set to : LOG_DEBUG
Jun 01 16:44:40  blobfuse2[17072]: LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
Jun 01 16:44:40  blobfuse2[17072]: LOG_TRACE [config.go (271)]: ParseAndValidateConfig : Parsing config
Jun 01 16:44:40  blobfuse2[17072]: LOG_INFO [config.go (373)]: ParseAndValidateConfig : using the following proxy address from the config file:
Jun 01 16:44:40  blobfuse2[17072]: LOG_INFO [config.go (377)]: ParseAndValidateConfig : sdk logging from the config file: true
Jun 01 16:44:40  blobfuse2[17072]: LOG_TRACE [config.go (480)]: ParseAndReadDynamicConfig : Reparsing config
Jun 01 16:44:40  blobfuse2[17072]: LOG_DEBUG [config.go (384)]: ParseAndValidateConfig : Getting auth type
Jun 01 16:44:40  blobfuse2[17072]: LOG_INFO [config.go (468)]: ParseAndValidateConfig : Account: redacted, Container: upgrade7, AccountType: BLOCK, Auth: MSI, Prefix: , Endpoint: https://redacted.blob.core.windows.net/, ListBlock: 0, MD5 : false false, Virtual Directory: true, Disable Compression: false
Jun 01 16:44:40  blobfuse2[17072]: LOG_INFO [config.go (472)]: ParseAndValidateConfig : Retry Config: Retry count 5, Max Timeout 900, BackOff Time 4, Max Delay 60
Jun 01 16:44:40  blobfuse2[17072]: LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up
Jun 01 16:44:40  blobfuse2[17072]: LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential
Jun 01 16:44:40  blobfuse2[17072]: LOG_DEBUG [azauth.go (79)]: azAuth::getAzAuth : Account: redacted, AccountType: BLOCK, Protocol: https, Endpoint: https://redacted.blob.core.windows.net/
Jun 01 16:44:40  blobfuse2[17072]: LOG_DEBUG [azauthmsi.go (103)]: azAuthBlobMSI::getCredential : MSI Token retrieved <removed>
Jun 01 16:44:40  blobfuse2[17072]: LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path
Jun 01 16:44:40  blobfuse2[17072]: LOG_TRACE [block_blob.go (209)]: BlockBlob::TestPipeline : Validating
Jun 01 16:44:40  blobfuse2[17072]: LOG_INFO [utils.go (222)]: SDK : ==> OUTGOING REQUEST (Try=1)
Jun 01 16:44:40  blobfuse2[17072]: LOG_INFO [utils.go (222)]: SDK : ==> REQUEST/RESPONSE (Try=1/30.623051ms, OpTime=57.942174ms) -- RESPONSE SUCCESSFULLY RECEIVED
Jun 01 16:44:40  blobfuse2[17072]: LOG_INFO [mount.go (411)]: mount: Mounting blobfuse2 on /mnt/bfusetmp
Jun 01 16:44:40  blobfuse2[17072]: LOG_DEBUG [mount.go (449)]: mount: foreground disabled, child = false
Jun 01 16:44:40  blobfuse2[17084]: LOG_CRIT [mount.go (401)]: Starting Blobfuse2 Mount : 2.0.3 on [Ubuntu 18.04.6 LTS]
Jun 01 16:44:40  blobfuse2[17084]: LOG_CRIT [mount.go (402)]: Logging level set to : LOG_DEBUG
Jun 01 16:44:40  blobfuse2[17084]: LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
Jun 01 16:44:40  blobfuse2[17084]: LOG_TRACE [config.go (271)]: ParseAndValidateConfig : Parsing config
Jun 01 16:44:40  blobfuse2[17084]: LOG_INFO [config.go (373)]: ParseAndValidateConfig : using the following proxy address from the config file:
Jun 01 16:44:40  blobfuse2[17084]: LOG_INFO [config.go (377)]: ParseAndValidateConfig : sdk logging from the config file: true
Jun 01 16:44:40  blobfuse2[17084]: LOG_TRACE [config.go (480)]: ParseAndReadDynamicConfig : Reparsing config
Jun 01 16:44:40  blobfuse2[17084]: LOG_DEBUG [config.go (384)]: ParseAndValidateConfig : Getting auth type
Jun 01 16:44:40  blobfuse2[17084]: LOG_INFO [config.go (468)]: ParseAndValidateConfig : Account: redacted, Container: upgrade7, AccountType: BLOCK, Auth: MSI, Prefix: , Endpoint: https://redacted.blob.core.windows.net/, ListBlock: 0, MD5 : false false, Virtual Directory: true, Disable Compression: false
Jun 01 16:44:40  blobfuse2[17084]: LOG_INFO [config.go (472)]: ParseAndValidateConfig : Retry Config: Retry count 5, Max Timeout 900, BackOff Time 4, Max Delay 60
Jun 01 16:44:40  blobfuse2[17084]: LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up
Jun 01 16:44:40  blobfuse2[17084]: LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential
Jun 01 16:44:40  blobfuse2[17084]: LOG_DEBUG [azauth.go (79)]: azAuth::getAzAuth : Account: redacted, AccountType: BLOCK, Protocol: https, Endpoint: https://redacted.blob.core.windows.net/
Jun 01 16:44:40  blobfuse2[17084]: LOG_DEBUG [azauthmsi.go (103)]: azAuthBlobMSI::getCredential : MSI Token retrieved <removed>
Jun 01 16:44:40  blobfuse2[17084]: LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path
Jun 01 16:44:40  blobfuse2[17084]: LOG_INFO [mount.go (411)]: mount: Mounting blobfuse2 on /mnt/bfusetmp
Jun 01 16:44:40  blobfuse2[17084]: LOG_DEBUG [mount.go (449)]: mount: foreground disabled, child = true
Jun 01 16:44:40  blobfuse2[17084]: LOG_DEBUG [mount.go (540)]: Mount::runPipeline : blobfuse2 pid = 17084, transfer pipe = /tmp/transferPipe_17084, polling pipe = /tmp/pollPipe_17084
Jun 01 16:44:40  blobfuse2[17084]: LOG_TRACE [azstorage.go (164)]: AzStorage::Start : Starting component azstorage
Jun 01 16:44:40  blobfuse2[17084]: LOG_TRACE [azstorage.go (177)]: AzStorage::Stop : Stopping component azstorage
Jun 01 16:44:40  blobfuse2[17072]: LOG_INFO [mount.go (467)]: mount: Child [17084] terminated from /mnt/bfusetmp

**Comment by souravgupta-msft** [comment]
@Sosby, please update your config file like [this](https://github.com/Azure/azure-storage-fuse/blob/sourav/v2/direct_io/sampleFileCacheConfig.yaml) and retry the operation.

**Comment by Sosby** [comment]
That worked.  What part of the config was I missing?  I feel like the pieces I left out were optional.

**Comment by souravgupta-msft** [comment]
You were just having `azstorage` in the config. At the very least you should have `libfuse` component in your config.

**Comment by souravgupta-msft** [comment]
Closing this as it is not an issue anymore. If you have further questions, you can continue this thread.
