### ISSUE TITLE
Known limitation: FIO read is failing since blobfuse does not allow ftruncate with offset non-zero

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-fuse#117]
FIO read tests are failing as it seems to be truncating files to a specific offset. Currently blobfuse only supports ftruncate with 0 offset. This needs to be improved...

fio --name=randread --ioengine=libaio --iodepth=1 --rw=randread --bs=4k --direct=0 --size=512M --numjobs=8 --runtime=240 --group_reporting 
Errors out with "Operation not permitted"

**Comment by anhvoms** [comment]
There's some other issue with write as well
If you run this command: 
fio --name=randwrite --ioengine=libaio --iodepth=128 --rw=randwrite --bs=4k --direct=1 --size=512M --numjobs=8 --runtime=240 --group_reporting

You get these errors: 
io: io_u error on file randwrite.4.0: Invalid argument: write offset=46923776, buflen=4096
fio: io_u error on file randwrite.4.0: Invalid argument: write offset=399106048, buflen=4096
fio: pid=104140, err=22/file:io_u.c:1582, func=io_u error, error=Invalid argument
fio: io_u error on file randwrite.3.0: Invalid argument: write offset=409915392, buflen=4096
fio: io_u error on file randwrite.3.0: Invalid argument: write offset=374374400, buflen=4096
fio: io_u error on file randwrite.5.0: Invalid argument: write offset=350285824, buflen=4096
fio: io_u error on file randwrite.5.0: Invalid argument: write offset=394027008, buflen=4096
fio: pid=104141, err=22/file:io_u.c:1582, func=io_u error, error=Invalid argument
fio: pid=104139, err=22/file:io_u.c:1582, func=io_u error, error=Invalid argument

**Comment by seguler** [comment]
Fixed in 1.0-RC-preview release
