### ISSUE TITLE
Missing Updates and Outdated Mounted File when Reading Constantly Updated File from Azure Storage Container

### ISSUE THREAD

**Issue by makaras** [Azure/azure-storage-fuse#1179]
### Which version of blobfuse was used?

`blobfuse2 version: 2.0.3`

### Which OS distribution and version are you using?
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
### If relevant, please share your mount command.

Default command that is defined with `az aks update --enable-blob-driver` and options on k8s Persistence Volume creation:

```
    - -o allow_other
    - --use-attr-cache=false
    - --log-level=LOG_DEBUG
    - --no-symlinks=true
    - --invalidate-on-sync=true
    - --file-cache-timeout-in-seconds=0
    - --cache-size-mb=0
    - --disable-writeback-cache=true
```

### What was the issue encountered?

I have created a container within a Storage account that holds a JSON file which is continuously updated. Additionally, every hour, a new folder is created and a new file is added to that new folder, which is also constantly updated. This repetitive operation occurs on an hourly basis.

I'm experiencing an issue with a mounted file where it is unable to read a file from a storage container correctly. The problem occurs when it starts reading the file, e.g. from 12 AM, it reads the file properly for the first two minutes. However, after that, it stops updating the mounted file altogether.

Is there a recommended configuration or solution to ensure that the file is continuously read and updated without any interruptions?

### Have you found a mitigation/solution?

No, i have tried with no cache option listed above but no luck

### Please share logs if available.

No logs, result is that file is just not updated

**Comment by vibhansa-msft** [comment]
This is mostly due to kernel caching the file contents. You can try clearing kernel page cache manually to validate this theory.
We do have a solution in our main branch which will be released by end of this month. This fix will provide users an option to disable the kernel caching completely and then every read shall reflect the latest contents of the file from container.
