### ISSUE TITLE
O_DIRECT not working

### ISSUE THREAD

**Issue by anhvoms** [Azure/azure-storage-fuse#118]
Apparently you can open a file in O_DIRECT mode, but attempt to write/read to it will fail
I've attached a test program, supply size and path to the file to write
```C
#define _GNU_SOURCE
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

int main( int argc, char** argv )
{
    int fd;
    char* buffer;
    if( argc != 3 )
    {
        printf("Usage: program <size in bytes> <file path>\n");
        return -1;
    }
    fd = open(argv[2], O_DIRECT | O_CREAT | O_RDWR);
    if( fd == -1 )
    {
        printf("Failed top open %s\n", argv[2]);
        return errno;
    }
    // O_DIRECT requires alignment
    buffer = (char*)aligned_alloc(512,atoi(argv[1]));
    if( buffer == NULL )
    {
        printf("Failed to allocate buffer\n");
        close(fd);
        return -1;
    }
    if( write( fd, buffer, atoi(argv[1]) ) == -1 )
    {
        printf("Failed to write %s errno %d\n", argv[2], errno);
        free( buffer );
        close(fd);
        return errno;
    }
    free(buffer);
    close(fd);
    return 0;
}
```

**Comment by seguler** [comment]
What should be the behavior here ? Should O_DIRECT enable writing to the cache disk with direct_io, or simply push each and every write to Blob storage ?

**Comment by anhvoms** [comment]
I think either choice is acceptable because the only promise of O_DIRECT is that the read/write will bypass the kernel page cache. However, it has been the case that people apply this notion of direct io to a distribute file system to mean that any read/write with O_DIRECT should be visible immediately. 

However, given the position of blobfuse is that it should not be considered as a DFS and as such the choice to write to cache disk with direct-io is acceptable. You can always enable the pushing of every write to Blob with a mount option. I believe GlusterFS does something similar: it supports O_DIRECT but the file is still cached in the glusterfs client, if you want to file to not be cached at all by GlusterFS you have to mount with direct-io-enable=true flag

**Comment by seguler** [comment]
Ok - your suggestion sounds good to me.

Btw your sample program seems to be failing on the local filesystem with the exact same error... Does it work for you ?

```
seguler@seguler-sdk-test:~/test/direct_io$ ./a.out 32 /home/seguler/abc
Failed to write /home/seguler/abc errno 22
```

**Comment by anhvoms** [comment]
Yep - my test program was overly simplistic for read/write O_DIRECT. In reality we need to figure out the block size of the underlying device and allocate aligned buffer, and the read/write call will also need to be in multiples of block sizes

**Comment by seguler** [comment]
I see - we need to handle this in [here](https://github.com/Azure/azure-storage-fuse/blob/master/blobfuse/fileapis.cpp#L252) when O_DIRECT flag exists. Is this something you can send a PR for ?

**Comment by anhvoms** [comment]
Sure - I can send a PR for this. I might send a PR for the ftruncate as well since I did some code change for that to get a build that I could run some read test with fio

**Comment by NaraVen** [comment]
It appears to work now. I could modify files despite the flag. Closing this one.
