### ISSUE TITLE
Operation not supported (setReadOnly)

### ISSUE THREAD

**Issue by mortenjoenby** [Azure/azure-storage-fuse#1193]
### Which version of blobfuse was used?
2.0.x - using AKS / k8s 1.25.6 w/ Ubuntu 22.04.

### Which OS distribution and version are you using?
Ubuntu 22.04

### If relevant, please share your mount command.
Using AKS, so the blob CSI driver.

### What was the issue encountered?
When deleting files we (not sure why) call "setReadOnly(false) on the file first and this throws the "Operation not supported" exception.

### Have you found a mitigation/solution?
No.

### Please share logs if available.
`Caused by: java.io.IOException: Cannot delete file: /shared/workarea/background-processarea/Inbound/BGP_10200/mapped.xml
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1343)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:323)
	... 113 more
Caused by: org.apache.commons.io.IOExceptionList: /shared/workarea/background-processarea/Inbound/BGP_10200/mapped.xml
	at org.apache.commons.io.file.PathUtils.setReadOnly(PathUtils.java:944)
	at org.apache.commons.io.file.PathUtils.deleteFile(PathUtils.java:485)
	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:392)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1340)
	... 114 more
Caused by: java.nio.file.FileSystemException: /shared/workarea/background-processarea/Inbound/BGP_10200/mapped.xml: Operation not supported
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.LinuxDosFileAttributeView.updateDosAttribute(LinuxDosFileAttributeView.java:278)
	at java.base/sun.nio.fs.LinuxDosFileAttributeView.setReadOnly(LinuxDosFileAttributeView.java:191)
	at org.apache.commons.io.file.PathUtils.setReadOnly(PathUtils.java:919)
	... 117 more`

**Comment by mortenjoenby** [comment]
@andyzhangx, not sure if anything else is required here or issue should be created under the https://github.com/kubernetes-sigs/blob-csi-driver project.

**Comment by mortenjoenby** [comment]
In sun.nio.fs.LinuxDosFileAttributeView

`private void updateDosAttribute(int flag, boolean enable) throws IOException {
        this.file.checkWrite();
        int fd = -1;

        try {
            fd = this.file.openForAttributeAccess(this.followLinks);
            int oldValue = this.getDosAttribute(fd);
            int newValue;
            if (enable) {
                newValue = oldValue | flag;
            } else {
                newValue = oldValue & ~flag;
            }

            if (newValue != oldValue) {
                byte[] value = Util.toBytes("0x" + Integer.toHexString(newValue));
                NativeBuffer buffer = NativeBuffers.asNativeBuffer(value);

                try {
                    LinuxNativeDispatcher.fsetxattr(fd, DOS_XATTR_NAME_AS_BYTES, buffer.address(), value.length + 1);
                } finally {
                    buffer.release();
                }
            }
        } catch (UnixException var17) {
            var17.rethrowAsIOException(this.file);
        } finally {
            UnixNativeDispatcher.close(fd);
        }

    }`

**Comment by andyzhangx** [comment]
have you set `-o allow_other` mount option in the storage class or persistent volume? @mortenjoenby

**Comment by mortenjoenby** [comment]
Hi @andyzhangx .
I will check this, but isn't that the default?
When looking at https://github.com/Azure/azure-storage-fuse/tree/main#un-supported-file-system-operations, is says:
"Blobfuse2 does not support extended-attributes (x-attrs) operations"

This line of code:
`LinuxNativeDispatcher.fsetxattr(fd, DOS_XATTR_NAME_AS_BYTES, buffer.address(), value.length + 1);`

Is doing that I guess? setting extended attributes.
Perhaps you can confirm?

So if that's the case, will "-o allow_other" change that?

**Comment by mortenjoenby** [comment]
Checking the csi-blob-node container shows the mount flags and includes the allow_other:

blob I0704 09:21:05.978739    6690 utils.go:76] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/a01da90407da4855ff4a38f7b1154693edbf3d7327cbbe032dd59397d935a64a/globalmount","target_path":"/var/lib/kubelet/pods/8dc80fd0-0f4f-4a96-9673-451d47e3c8a7/volumes/kubernetes.io~csi/stiboqa-perf2-pv-cloud-fileshare-blobfuse/mount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["-o default_permissions","-o allow_other","-o umask=007"]}},"access_mode":{"mode":5}},"volume_context":{"containerName":"sharedstorage","csi.storage.k8s.io/ephemeral":"false","csi.storage.k8s.io/pod.name":"stiboqa-perf2-sftp-deployment-5d479d65fb-nwkjq","csi.storage.k8s.io/pod.namespace":"stiboqa-perf2","csi.storage.k8s.io/pod.uid":"8dc80fd0-0f4f-4a96-9673-451d47e3c8a7","csi.storage.k8s.io/serviceAccount.name":"default","protocol":"fuse3"},"volume_id":"stiboqa-perf2-blob"}

**Comment by mortenjoenby** [comment]
@andyzhangx  / @vibhansa-msft , any comments to this is highly appreciated :)

**Comment by vibhansa-msft** [comment]
XAttrs are not supported by Blobfuse. Also, as per original post you are trying to reset the read-only property of file which shall go as 'chmod' operation. This operation will work only when you mount a HNS enabled account mounted with adls option.

**Comment by vibhansa-msft** [comment]
By 'worse' if you mean its low on performance then yes. However, there are features that work only on HNS account, chmod being one of them as non-HNS accounts do not have ACL support. HNS accounts also support renaming a directory or deleteing a directory while in non-HNS account there is no concept of directory (in the backend). So, its feature vs performance based on your needs.

**Comment by mortenjoenby** [comment]
Hi @vibhansa-msft .
Being back from holidays I have just seen your comments. Thanks!
We are using the Apache Commons library, but we will change this to achieve what we want. I don't think we will be using a HNS enabled account, but I might have to test that again also.
Currently we use Azure Files (Premium Files), but performance is really bad. Any idea how performance is when comparing Azure Files vs. Blob (non-HNS) vs. Blob (HNS) ?

**Comment by vibhansa-msft** [comment]
We have not done such comparative study as of now, but in general I believe blob storage will have better performance compared to HNS or files. Do not have number to proove these assumptions as of now, but you can do experiments around as to what suits your needs better. Closing this here, feel free to reopen if you observe any performance deviation from the blobfuse end.
There is one difference clearly that blobfuse uploads/downloads entire file on open/close and NFS for files might be optimizing that cost.
