### ISSUE TITLE
Getting Input/Output error reading Append Blob, is it not supported?

### ISSUE THREAD

**Issue by paul-jebasingh** [Azure/azure-storage-fuse#1197]
### Which version of blobfuse was used?
Blobfuse2

### Which OS distribution and version are you using?
RedHat 7.9

### What was the issue encountered?
Mount was successful but cant read the file and getting Input/Output error

### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
Append blobs are not supported by blobfuse as of now.

**Comment by vibhansa-msft** [comment]
What is your workflow. If you just want to read a file you can use any of the Azure SDK and have a small application that can read from Append Blob.

**Comment by paul-jebasingh** [comment]
Classification: Public

Hi Vikas,

This is a logging data and we want this data expose to Appdynamics to read.

Thanks
Paul Jebasingh
Manager Consulting Expert| Downstream Sub BU | Cloud COP - E&U SPOC
Asia Pacific Energy and Utilities Delivery Center| CGI |
M: +91 9360898502 / 9600065303 |
***@***.******@***.***> | www.cgi.com<http://www.cgi.com/>

[Description: Description: Description: ***@***.***
Leave Plan: May 12th till May 25th

**Comment by vibhansa-msft** [comment]
Any particular reason to use append-blobs here ?

**Comment by paul-jebasingh** [comment]
Classification: Public

We have enabled Immutable policy and using API to write logs.

Thanks
Paul Jebasingh
Manager Consulting Expert| Downstream Sub BU | Cloud COP - E&U SPOC
Asia Pacific Energy and Utilities Delivery Center| CGI |
M: +91 9360898502 / 9600065303 |
***@***.******@***.***> | www.cgi.com<http://www.cgi.com/>

[Description: Description: Description: ***@***.***
Leave Plan: May 12th till May 25th

**Comment by vibhansa-msft** [comment]
If you have immutable policy set then how does append to a file goes through, immutable basically allows a file to be written only once. So in that case it shall not matter whether blob is append or block

**Comment by paul-jebasingh** [comment]
Classification: Public

Hi Vikas,

The immutable has a property to allow append blob which is enabled in our case, so initial write and append is allowed.

Thanks
Paul Jebasingh
Manager Consulting Expert| Downstream Sub BU | Cloud COP - E&U SPOC
Asia Pacific Energy and Utilities Delivery Center| CGI |
M: +91 9360898502 / 9600065303 |
***@***.******@***.***> | www.cgi.com<http://www.cgi.com/>

[Description: Description: Description: ***@***.***
Leave Plan: May 12th till May 25th

**Comment by vibhansa-msft** [comment]
Hi Paul,

So you set the immutable policy and that still allow you to add data to append blobs, but the same flow can not work with block blobs.
Understood your use case now, but unfortunately we do not support append blobs as of now. I can add this request to our backlog but no immediate relief or workaround is available on this front as present.

***@***.*** Charan ***@***.***> for the visibility on the ask.

Regards
Vikas Bhansali

**Comment by vibhansa-msft** [comment]
You can also evaluate AzCopy tool which is our data migration tool and does support append blob as well.

From: Vikas Bhansali
Sent: Friday, July 14, 2023 10:33 AM
To: ***@***.***; Azure/azure-storage-fuse ***@***.***>; Vishnu Charan TJ ***@***.***>
Cc: Comment ***@***.***>; Assign ***@***.***>; State change ***@***.***>; Subscribed ***@***.***>
Subject: RE: [Azure/azure-storage-fuse] Getting Input/Output error reading Append Blob, is it not supported? (Issue #1197)

Hi Paul,

So you set the immutable policy and that still allow you to add data to append blobs, but the same flow can not work with block blobs.
Understood your use case now, but unfortunately we do not support append blobs as of now. I can add this request to our backlog but no immediate relief or workaround is available on this front as present.

***@***.*** Charan ***@***.***> for the visibility on the ask.

Regards
Vikas Bhansali

**Comment by LeoandHenry** [comment]
@vibhansa-msft  This is a question from Azure CSS team, may I know if append blob is supported with blobfuse2 on AKS  now?

**Comment by vibhansa-msft** [comment]
No append blobs are not supported for writing. Reading you can do.

**Comment by LeoandHenry** [comment]
Hi  @vibhansa-msft ，Thank you for your reply. How to use reading and how to configure it? Is there any relevant documentation to explain it.

**Comment by vibhansa-msft** [comment]
For blobfuse you dont need to mention anything about blob type. Just mount your container and try reading the blobs. Reading of append blob shall work seamlessly. It's only writing part that differs in case of append-blob vs block-blob.

**Comment by LeoandHenry** [comment]
Got it, thank you very much.
