### ISSUE TITLE
Facing challenges when rsync destination folder is used as mount point in blobfuse2 mount configuration.

### ISSUE THREAD

**Issue by KuroAshi75** [Azure/azure-storage-fuse#1200]
### Which version of blobfuse was used?
2.0.3

### Which OS distribution and version are you using?
Ubuntu 22.04

### If relevant, please share your mount command.
blobfuse2 mount /home/user/box --tmp-path=/home/user/blobfuse2tmp --config-file=/home/user/config.yaml --allow-other --disable-version-check

### What was the issue encountered?

We have two ubuntu systems where in a child ubuntu can communicate only to parent(which has internet connectivity) over ssh. We have files in child system that are being synced to destination folder in parent over "rsync" package.

Blobfuse2 is installed in parent and configured to mount rsync destination folder to storage container so that files from child can be uploaded to storage account via parent. When blobfuse2 mount point is created in the parent rsync destination folder, the rsync command hangs.

Can blobfuse2 Linux file system folder which is mounted to storage container can be used as rsync destination folder? If so, could you please share the settings of config yaml which works for this scenario.

**Comment by vibhansa-msft** [comment]
To be honest we have not tried this scenario from our end so far. Based on your description its a fair assumption that it shall work. When you say its hung up it might be some authentication or listing related issue. If you can enable log_debug and share the log files I can suggest something based on the logs.

**Comment by vibhansa-msft** [comment]
With the ssh key sharing and auto login, its working now you mean ? Or you are still hitting the issue?
If ssh config was an issue then I doubt we will see anything significant in logs. Mostly it would not have received any call.

**Comment by KuroAshi75** [comment]
The sync issue is still there between the source directory and the target directory(blobfuse mounted), we meant that there was no issue related to login from one machine to another.

**Comment by vibhansa-msft** [comment]
Then we need logs from parent mount to confirm we are getting file upload/download requests there.

**Comment by KuroAshi75** [comment]
Let me give you more insights on our current set up, we have a nested edge set up where we are trying to rsync between local folder on child and a blobfuse2 mount folder on the parent.
the blobfuse2 mount folder is connected to 'Azure Blob Storage on IoT Edge'(https://azuremarketplace.microsoft.com/en-us/marketplace/apps/azure-blob-storage.edge-azure-blob-storage?tab=Overview) 
module hosted on the parent of nested edge set up. The 'Azure Blob Storage on IoT Edge' module then uploads the file to the blob storage on cloud.
Below are the two scenarios which we have tested for uploading the files using blobfuse2.
When the source directory of blobfuse2 is mounted to a cloud storage account directly instead of the 'Azure Blob Storage on IoT Edge' module, the rsync is working fine and the files are uploaded to cloud storage account.
When the source directory of blobfuse2 is mounted to 'Azure Blob Storage on IoT Edge' module, the rsync hangs and it doesn't come out of the process.
However we can see the files are getting uploaded to cloud storage account with duplicate files followed by different extensions.

**Comment by KuroAshi75** [comment]
I couldn't get permissions to extract the logs from the exact set up so i have tried  to replicate this in another scenario, there is just one small change, 'Azure Blob Storage on IoT Edge' module is running on the parent exactly as in original setup, but the rsync between the source directory(local folder) and target directory(blobfuse2 mounted)  are both on child. 
Sharing the log file along this comment.
[bloblogs.log](https://github.com/Azure/azure-storage-fuse/files/12050794/bloblogs.log)

**Comment by vibhansa-msft** [comment]
As per logs there are lot of 500 error which is returned back from server. There might be a chance that account is getting throttled for some reason or some other server internal errors are there. As server is busy the uploads are not working. This will delay the upload and from user end you may feel its taking extremely long to sync. Blobfuse has retry mechanism where in case of 5xx errors it will retry after an exponential back-offs. Untill all retries are done it will not declare failure.

**Comment by vibhansa-msft** [comment]
Also, when you say directly mounting blobfuse to Azure Storage works, why you wish to go through an extra hop of IOT Edge. Wouldn't that decrease your performance. As blobfuse is connected to IOT Edge there is a possibility that these 5xx errors are sent back from IOT Edge itself and not the Azure backend storage.

**Comment by KuroAshi75** [comment]
Apologies for the late reply.

Azure IoT Edge module for blob comes with deviceToCloudUpload and deviceAutoDelete features.

This functionality automatically uploads the data from your local blob storage to Azure with intermittent internet connectivity support.
It also has the capability to delete the files once uploaded to cloud storage account
More details can be found here.
https://learn.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-1.4

**Does blob fuse has functionality to handle intermittent network connectivity as well as delete the files from source after successful upload?**

Regarding 500 errors, if I understand correctly, server(Windows-Azure-Blob) part of Azure blob storage on IoT edge module has some problems?
Do you suspect the 500 errors we are seeing might be the cause for the rsync not terminating?
Would it be possible to share some more inputs regarding this or how we can identify the root cause of the problem.

**Comment by vibhansa-msft** [comment]
You can turn on the debug logging in blobfuse and also enable "sdk-trace: true" under 'azstorage" section in config file. This will give us details around what REST calls were done and what reply blobfuse received. Now question is if IoT Edge is sending 5xx or actual backend server. For this you might need to do some logging on the IoT Edge itself.

**Comment by KuroAshi75** [comment]
The previous logs i have shared has the "sdk-trace:true" enabled.

**Comment by vibhansa-msft** [comment]
Oh yes, I got it. From those logs only we found it was error coming from server end.
"   RESPONSE Status: 500 Server encountered an internal error. Please try again after some time." I see this in logs. So you need to confirm first whether IOT Edge is sending this error or the actual backend server.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update on this. Feel free to reopen when you have the required information available.
