### ISSUE TITLE
Unable to start blobfuse due to a lack of credentials.

### ISSUE THREAD

**Issue by HossamAmer12** [Azure/azure-storage-fuse#1203]
When I run blobfuse I get this
$Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Unmounting blobfuse.
Unmounted blobfuse successfully

I am doing export for AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_ACCESS_KEY

and that's my command:

```
blobfuse ./blobs/blob-deeplm2/ --tmp-path=/mnt/cache-mtcairogroup2 -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 \
    --container-name=longsheng --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120
```

And no logs in the `/var/log/syslog`

blobfuse version is 1.4.5. The same script worked on a different AML cluster, but surprisingly does not work on this cluster

Any ideas here, please?

**Comment by vibhansa-msft** [comment]
You can set logging to base and redirect blobfuse logs to a file to get details on why the mount is failing.

**Comment by HossamAmer12** [comment]
How do you set logging to base?

**Comment by HossamAmer12** [comment]
I updated my version from blob fuse 1.4.5 to blobfuse 2... Updated the command to blobfuse2 and get these logs:

> Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_CRIT [mount.go (402)]: Starting Blobfuse2 Mount : 2.0.4 on [Ubuntu 20.04.6 LTS]
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_CRIT [mount.go (403)]: Logging level set to : LOG_DEBUG
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_TRACE [libfuse.go (249)]: Libfuse::Configure : libfuse
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_INFO [libfuse.go (240)]: Libfuse::Validate : UID 0, GID 0
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_INFO [libfuse.go (295)]: Libfuse::Configure : read-only false, allow-other false, allow-root false, default-perm 493, entry-timeout 240, attr-time 240, negative-timeout 120, ignore-open-flags: true, nonempty false
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_TRACE [file_cache.go (205)]: FileCache::Configure : file_cache
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_INFO [file_cache.go (282)]: FileCache::Configure : Using default eviction policy
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_INFO [file_cache.go (304)]: FileCache::Configure : create-empty false, cache-timeout 120, tmp-path /mnt/cache-mtcairogroup2, max-size-mb 0, high-mark 80, low-mark 60, refresh-sec 0
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_TRACE [attr_cache.go (126)]: AttrCache::Configure : attr_cache
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_INFO [attr_cache.go (156)]: AttrCache::Configure : cache-timeout 120, symlink false, cache-on-list true
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_TRACE [azstorage.go (84)]: AzStorage::Configure : azstorage
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_TRACE [config.go (278)]: ParseAndValidateConfig : Parsing config
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_WARNING [config.go (339)]: ParseAndValidateConfig : account endpoint not provided, assuming the default .core.windows.net style endpoint
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_INFO [config.go (380)]: ParseAndValidateConfig : using the following proxy address from the config file: 
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_INFO [config.go (384)]: ParseAndValidateConfig : sdk logging from the config file: false
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_TRACE [config.go (487)]: ParseAndReadDynamicConfig : Reparsing config
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_DEBUG [config.go (391)]: ParseAndValidateConfig : Getting auth type
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_DEBUG [config.go (396)]: ParseAndValidateConfig : Auth type key
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_INFO [config.go (475)]: ParseAndValidateConfig : Account: deeplm, Container: longsheng, AccountType: BLOCK, Auth: KEY, Prefix: , Endpoint: https://deeplm.blob.core.windows.net/, ListBlock: 0, MD5 : false false, Virtual Directory: true, Max Results For List 2, Disable Compression: false
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_INFO [config.go (479)]: ParseAndValidateConfig : Retry Config: Retry count 5, Max Timeout 900, BackOff Time 4, Max Delay 60
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_DEBUG [azauth.go (79)]: azAuth::getAzAuth : Account: deeplm, AccountType: BLOCK, Protocol: https, Endpoint: https://deeplm.blob.core.windows.net/
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path 
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_TRACE [block_blob.go (209)]: BlockBlob::TestPipeline : Validating
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_INFO [mount.go (412)]: mount: Mounting blobfuse2 on /root/mounts/blobs/blob-deeplm2
Fri Jul 14 09:55:53 UTC 2023 : blobfuse2[3345] : LOG_DEBUG [mount.go (450)]: mount: foreground disabled, child = false
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_CRIT [mount.go (402)]: Starting Blobfuse2 Mount : 2.0.4 on [Ubuntu 20.04.6 LTS]
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_CRIT [mount.go (403)]: Logging level set to : LOG_DEBUG
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [libfuse.go (249)]: Libfuse::Configure : libfuse
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse.go (240)]: Libfuse::Validate : UID 0, GID 0
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse.go (295)]: Libfuse::Configure : read-only false, allow-other false, allow-root false, default-perm 493, entry-timeout 240, attr-time 240, negative-timeout 120, ignore-open-flags: true, nonempty false
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [file_cache.go (205)]: FileCache::Configure : file_cache
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [file_cache.go (282)]: FileCache::Configure : Using default eviction policy
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [file_cache.go (304)]: FileCache::Configure : create-empty false, cache-timeout 120, tmp-path /mnt/cache-mtcairogroup2, max-size-mb 0, high-mark 80, low-mark 60, refresh-sec 0
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [attr_cache.go (126)]: AttrCache::Configure : attr_cache
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [attr_cache.go (156)]: AttrCache::Configure : cache-timeout 120, symlink false, cache-on-list true
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [azstorage.go (84)]: AzStorage::Configure : azstorage
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [config.go (278)]: ParseAndValidateConfig : Parsing config
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_WARNING [config.go (339)]: ParseAndValidateConfig : account endpoint not provided, assuming the default .core.windows.net style endpoint
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [config.go (380)]: ParseAndValidateConfig : using the following proxy address from the config file: 
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [config.go (384)]: ParseAndValidateConfig : sdk logging from the config file: false
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [config.go (487)]: ParseAndReadDynamicConfig : Reparsing config
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [config.go (391)]: ParseAndValidateConfig : Getting auth type
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [config.go (396)]: ParseAndValidateConfig : Auth type key
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [config.go (475)]: ParseAndValidateConfig : Account: deeplm, Container: longsheng, AccountType: BLOCK, Auth: KEY, Prefix: , Endpoint: https://deeplm.blob.core.windows.net/, ListBlock: 0, MD5 : false false, Virtual Directory: true, Max Results For List 2, Disable Compression: false
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [config.go (479)]: ParseAndValidateConfig : Retry Config: Retry count 5, Max Timeout 900, BackOff Time 4, Max Delay 60
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [azauth.go (79)]: azAuth::getAzAuth : Account: deeplm, AccountType: BLOCK, Protocol: https, Endpoint: https://deeplm.blob.core.windows.net/
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path 
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [mount.go (412)]: mount: Mounting blobfuse2 on /root/mounts/blobs/blob-deeplm2
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [mount.go (450)]: mount: foreground disabled, child = true
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [mount.go (541)]: Mount::runPipeline : blobfuse2 pid = 3355, transfer pipe = /tmp/transferPipe_3355, polling pipe = /tmp/pollPipe_3355
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [azstorage.go (165)]: AzStorage::Start : Starting component azstorage
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [attr_cache.go (107)]: AttrCache::Start : Starting component attr_cache
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [file_cache.go (147)]: Starting component : file_cache
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [lru_policy.go (108)]: lruPolicy::StartPolicy
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [libfuse.go (146)]: Libfuse::Start : Starting component libfuse
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [libfuse_handler.go (119)]: Libfuse::initFuse : Initializing FUSE3
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [libfuse_handler.go (162)]: Libfuse::initFuse : Registering fuse callbacks
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [libfuse_handler.go (166)]: Libfuse::initFuse : Populating fuse arguments
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [libfuse_handler.go (190)]: Libfuse::populateFuseArgs
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [libfuse_handler.go (231)]: Libfuse::populateFuseArgs : opts : blobfuse2
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [libfuse_handler.go (231)]: Libfuse::populateFuseArgs : opts : /root/mounts/blobs/blob-deeplm2
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [lru_policy.go (261)]: lruPolicy::ClearCache
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [libfuse_handler.go (231)]: Libfuse::populateFuseArgs : opts : -o
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [libfuse_handler.go (231)]: Libfuse::populateFuseArgs : opts : entry_timeout=240,attr_timeout=240,negative_timeout=120
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [libfuse_handler.go (231)]: Libfuse::populateFuseArgs : opts : -f
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [libfuse_handler.go (231)]: Libfuse::populateFuseArgs : opts : -ofsname=blobfuse2
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_DEBUG [libfuse_handler.go (231)]: Libfuse::populateFuseArgs : opts : -okernel_cache
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse_handler.go (178)]: Libfuse::initFuse : Mounting with fuse3 library
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_TRACE [libfuse_handler.go (251)]: Libfuse::libfuse_init : init
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse_handler.go (253)]: Libfuse::NotifyMountToParent : Notifying parent for successful mount
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse_handler.go (260)]: Libfuse::libfuse_init : Kernel Caps : 52428763
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse_handler.go (267)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_PARALLEL_DIROPS
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse_handler.go (273)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_AUTO_INVAL_DATA
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse_handler.go (280)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_READDIRPLUS
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse_handler.go (286)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_ASYNC_READ
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse_handler.go (292)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_SPLICE_WRITE
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3355] : LOG_INFO [libfuse_handler.go (304)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_WRITEBACK_CACHE
Fri Jul 14 09:55:54 UTC 2023 : blobfuse2[3345] : LOG_INFO [mount.go (464)]: mount: Child [3355] mounted successfully at /root/mounts/blobs/blob-deeplm2

**Comment by HossamAmer12** [comment]
the problem was updating the version from `blobfuse 1.4.5` to `blobfuse 2`
