### ISSUE TITLE
Which azure VM type is best for testing performance of azure-storage-fuse ?

### ISSUE THREAD

**Issue by Tulsishah** [Azure/azure-storage-fuse#1204]
Hi,

I want to performance test read, write and different apis with azure-storage-fuse. Can anyone suggest the azure VM type and storage class?

Thanks,
Tulsi Shah

**Comment by vibhansa-msft** [comment]
You can go with any VM having min 8GB RAM and 4 Core CPU. Based on your use case and dataset you need to extend the configuration. From Blobfuse side there is no restriction on minimum config it all depends on your use case. In addition to this blobfuse works with local caching to depending upon the size of data you are operating on you need to have sufficient local disk space as well. Any file that you open to read/write will be downloaded locally so you shall always have enough of disk space to hold that file.
