### ISSUE TITLE
CentOS/RHEL Incorrect Logrotate Postrotate Command

### ISSUE THREAD

**Issue by jgregorcmh** [Azure/azure-storage-fuse#1207]
### Which version of blobfuse was used?
blobfuse2 version 2.0.3

### Which OS distribution and version are you using?
Red Hat Enterprise Linux 8.7
rsyslogd  8.2102.0-10.el8 (aka 2021.02)
logrotate 3.14.0

### If relevant, please share your mount command.
N/A

### What was the issue encountered?
During nightly logrotate, the installed /etc/logrotate.d/blobfuse2 script fails.  The error given is: 
`logrotate_script: line 1: /usr/lib/rsyslog/rsyslog-rotate: No such file or directory
error: error running shared postrotate script for '/var/log/blobfuse2.log
/var/log/bfusemon.log
/var/log/blobfuse2-rest.log`

In the RHEL8 distribution of rsyslogd there is no /usr/lib/rsyslog folder or rsyslog-rotate command.  This file I think is only found in the apt distribution of rsyslog.  Here are the contents of the /etc/logrotate.d/blobfuse2 file installed by the package:
```
/var/log/blobfuse2.log
/var/log/bfusemon.log
/var/log/blobfuse2-rest.log {
    rotate 10
        maxsize 100M
        daily
        missingok
        notifempty
        compress
        dateext
        delaycompress
        sharedscripts
        postrotate
                /usr/lib/rsyslog/rsyslog-rotate
        endscript
}
```

### Have you found a mitigation/solution?
 `/usr/bin/systemctl kill -s HUP rsyslog.service` is what the rsyslog-rotate file would perform on a systemd enabled machine like RHEL.  This is also the action performed in the syslog file (/etc/logrotate.d/syslog) on default RHEL8 distribution.  Contents of rsyslog-rotate from an Ubuntu 20.04 machine:
```
#!/bin/sh

if [ -d /run/systemd/system ]; then
    systemctl kill -s HUP rsyslog.service
else
    invoke-rc.d rsyslog rotate > /dev/null
fi
```

### Please share logs if available.

```
From root@<hostname>.localdomain  Tue Jul 18 03:41:02 2023
Return-Path: <root@<hostname>.localdomain>
X-Original-To: root
Delivered-To: root@<hostname>.localdomain
Received: by <hostname>.localdomain (Postfix, from userid 0)
        id AA98240271D; Tue, 18 Jul 2023 03:41:02 +0000 (UTC)
From: Anacron <root@<hostname>.localdomain>
To: root@<hostname>.localdomain
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Subject: Anacron job 'cron.daily' on <hostname>
Message-Id: <20230718034102.AA98240271D@<hostname>.localdomain>
Date: Tue, 18 Jul 2023 03:41:02 +0000 (UTC)

/etc/cron.daily/logrotate:

logrotate_script: line 1: /usr/lib/rsyslog/rsyslog-rotate: No such file or directory
error: error running shared postrotate script for '/var/log/blobfuse2.log
/var/log/bfusemon.log
/var/log/blobfuse2-rest.log
```

**Comment by vibhansa-msft** [comment]
If I get this right, on Ubuntu things will work fine but on RHEL or other distributions where this script is not found suggestion is to directly invoke "systemctl kill -s HUP rsyslog.service" command?
On RHEL based system can you share any other service's logrotate script as in what they do as part of "postrotate" actoin.

**Comment by jgregorcmh** [comment]
Yes, I think on Ubuntu it works fine.  Centos/RHEL (likely Almalinux and Rocky too) need another method to restart (r)syslog.  Here's a few samples I pulled of /etc/logrotate.d/syslog for comparison on restarting the service.

RHEL 8.7:
```
# cat /etc/logrotate.d/syslog
/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
{
    missingok
    sharedscripts
    postrotate
        /usr/bin/systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true
    endscript
}
```

Centos 7.9:
# cat /etc/logrotate.d/syslog
/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
{
    missingok
    sharedscripts
    postrotate
        /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
    endscript
}
