### ISSUE TITLE
Blobfuse Support for i386 arch.

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/azure-storage-fuse#121]
Hiya,

I followed the instruction, and downloaded/loaded the microsoft packages information. (mentioned here https://github.com/Azure/azure-storage-fuse/wiki/Installation)

* I think currently 14.04 is not supported by blobfuse? (is there any work around)
* Is there any way we can make blobfuse support available for 14.04 please.  _(I tried building the source but no luck so far.)_

Please note: My VirtualBox was Ubuntu with Locale NZ.

Screenshot below might help:

![image](https://user-images.githubusercontent.com/6233295/37062042-2c934414-21fa-11e8-9bf5-c75e12785ba1.png)

Idea behind this tool sounds great!

Will wait for your reply & thanks,
^Tats

**Comment by Tatsinnit** [comment]
Update: with local: Sydney, I am able to get the package `blobfuse` for `Ubuntu 14.04`. 

![image](https://user-images.githubusercontent.com/6233295/37066029-5e0f14f6-2208-11e8-82f5-54fa98c30a29.png)

**Comment by Tatsinnit** [comment]
Reopening this, I am able to generate the consistent failure for this with my personal PC so home network. 

* Image is : http://releases.ubuntu.com/14.04/ => **14.04.5 LTS i386**  **NOT** amd64

I followed the instruction, and downloaded/loaded the microsoft packages information. (mentioned here https://github.com/Azure/azure-storage-fuse/wiki/Installation)

![image](https://user-images.githubusercontent.com/6233295/37119857-a2b26558-22bd-11e8-919a-e81c5437717e.png)

**Comment by seguler** [comment]
We currently only have amd64 binaries.

**Comment by Tatsinnit** [comment]
:bulb: Cool, thank you @seguler this information explains the whole thing. I am unblocked with the finding. :) but yeah seems like good to have as enhancement for the toolset.

**Comment by seguler** [comment]
We'll not release binaries for non-x86 platforms, therefore closing this request. However, we can support anyone trying to build on non-x86 platforms.
