### ISSUE TITLE
Blobfuse2 version 2.0.4 - 100% cpu used 

### ISSUE THREAD

**Issue by MgWki** [Azure/azure-storage-fuse#1210]
### Which version of blobfuse was used?
Blobfuse blobfuse2 version 2.0.4

### Which OS distribution and version are you using?
Red Hat Enterprise Linux release 8.8 (Ootpa)

### If relevant, please share your mount command.
/usr/bin/blobfuse2 mount /mnt/BlobFuse --config-file /root/BlobParameters.yml

### What was the issue encountered?
We are using same software on many other Linux Server with same OS version, but with the BlobFuse versione 2.03
On new servers it is downloaded the latest 2.04 blobfuse release. 
It works but we noted a fixed 100% cpu occupancy for ever, also if it is doing nothing !
On the same server, disinstalling and re-installing previous Blobfuse Rel 2.0.3, the problem disappears

### Conf file
 cat /root/BlobParameters.yml
allow-other: true
logging:
  type: base
  level: log_err
  file-path: /var/log/blobfuse2.log
components:
  - libfuse
  - stream
  - file_cache
  - attr_cache
  - azstorage
libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240
file_cache:
  path: /asp/Backup/cache
  timeout-sec: 240
  max-size-mb: 0
  cleanup-on-start: true
  allow-non-empty-temp: true
attr_cache:
  timeout-sec: 7200
  no-cache-on-list: true
azstorage:
  type: block
  account-name: XXXX
  account-key: XXXX
  endpoint: XXXX
  mode: key
  container: XXXX
  block-size-mb: 512
  max-concurrency: 64
  tier: hot
  max-retries: 10

### Please share logs if available.
Nothing relevant we see in the logs:
cat /var/log/blobfuse2.log
Mon Jul 24 14:43:47 CEST 2023 : blobfuse2[1045530] : LOG_CRIT [mount.go (402)]: Starting Blobfuse2 Mount : 2.0.4 on [Oracle Linux Server 8.8]
Mon Jul 24 14:43:47 CEST 2023 : blobfuse2[1045530] : LOG_CRIT [mount.go (403)]: Logging level set to : LOG_ERR
Mon Jul 24 14:43:47 CEST 2023 : blobfuse2[1045571] : LOG_CRIT [mount.go (402)]: Starting Blobfuse2 Mount : 2.0.4 on [Oracle Linux Server 8.8]
Mon Jul 24 14:43:47 CEST 2023 : blobfuse2[1045571] : LOG_CRIT [mount.go (403)]: Logging level set to : LOG_ERR

###  TOP command
Tasks: 3447 total,   3 running, 3255 sleeping,   0 stopped, 189 zombie
%Cpu(s): 40.7 us, 12.6 sy, 39.7 ni,  4.8 id,  0.0 wa,  1.1 hi,  1.1 si,  0.0 st
MiB Mem :  47860.8 total,   2795.9 free,  16497.6 used,  28567.4 buff/cache
MiB Swap:   8076.0 total,   7749.5 free,    326.5 used.  30456.7 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1045571 root      20   0 1559740  26704  17000 R  98.1   0.1   0:51.77 blobfuse2

###  STRACE of Blobfuse process
[pid 1045571] read(0,  <unfinished ...>
[pid 1045572] <... sched_yield resumed>) = 0
[pid 1045571] <... read resumed>"", 4096) = 0
[pid 1045572] futex(0x167fcb8, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 1045571] read(0,  <unfinished ...>
[pid 1045572] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 1045571] <... read resumed>"", 4096) = 0
[pid 1045571] read(0, "", 4096)         = 0
[pid 1045572] <... nanosleep resumed>NULL) = 0
[pid 1045571] read(0,  <unfinished ...>
[pid 1045572] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 1045571] <... read resumed>"", 4096) = 0
[pid 1045571] read(0, "", 4096)         = 0
[pid 1045572] <... nanosleep resumed>NULL) = 0
[pid 1045571] read(0,  <unfinished ...>
[pid 1045572] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 1045571] <... read resumed>"", 4096) = 0
[pid 1045571] read(0, "", 4096)         = 0
[pid 1045572] <... nanosleep resumed>NULL) = 0
[pid 1045571] read(0,  <unfinished ...>
[pid 1045572] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 1045571] <... read resumed>"", 4096) = 0
[pid 1045571] read(0, "", 4096)         = 0
[pid 1045572] <... nanoslee^C[pid 1045571] <... read resumed>"", 4096) = 0

###  LSOF  lsof -p 1045571
COMMAND       PID USER   FD      TYPE             DEVICE SIZE/OFF      NODE NAME
blobfuse2 1045571 root  cwd       DIR              252,0      255       128 /
blobfuse2 1045571 root  rtd       DIR              252,0      255       128 /
blobfuse2 1045571 root  txt       REG              252,0 27365152     62925 /usr/bin/blobfuse2
blobfuse2 1045571 root  mem       REG              252,0    54352  33657575 /usr/lib64/libnss_files-2.28.so
blobfuse2 1045571 root  mem       REG              252,0  2090128  33557896 /usr/lib64/libc-2.28.so
blobfuse2 1045571 root  mem       REG              252,0   150248  33657578 /usr/lib64/libpthread-2.28.so
blobfuse2 1045571 root  mem       REG              252,0    92968  33657580 /usr/lib64/libresolv-2.28.so
blobfuse2 1045571 root  mem       REG              252,0    19128  33561011 /usr/lib64/libdl-2.28.so
blobfuse2 1045571 root  mem       REG              252,0   253872  34326411 /usr/lib64/libfuse3.so.3.3.0
blobfuse2 1045571 root  mem       REG              252,0  1062744  33734927 /usr/lib64/ld-2.28.so
blobfuse2 1045571 root    0r      CHR                1,3      0t0      3075 /dev/null
blobfuse2 1045571 root    1w      REG              252,0       65  67862874 /tmp/blobfuse2.1045530 (deleted)
blobfuse2 1045571 root    2w      REG              252,0       65  67862874 /tmp/blobfuse2.1045530 (deleted)
blobfuse2 1045571 root    3r      CHR                1,3      0t0      3075 /dev/null
blobfuse2 1045571 root    4u      REG              252,0        7  69355648 /root/.blobfuse2/_mnt_BlobFuse.pid
blobfuse2 1045571 root    5u      CHR             10,229      0t0      1669 /dev/fuse
blobfuse2 1045571 root    6u  a_inode               0,14        0     13876 [eventpoll]
blobfuse2 1045571 root    7r     FIFO               0,13      0t0 391974582 pipe
blobfuse2 1045571 root    8w     FIFO               0,13      0t0 391974582 pipe
blobfuse2 1045571 root    9u     unix 0xffff8ce3df0c0d80      0t0 391974583 type=DGRAM
blobfuse2 1045571 root   10r  a_inode               0,14        0     13876 inotify
blobfuse2 1045571 root   11w      REG              252,0      506 101741240 /var/log/blobfuse2.log

**Comment by vibhansa-msft** [comment]
100% cpu bug has been fixed in our main line, next release will have the fix. Will try to release at the earliest.
