### ISSUE TITLE
Incremental File Content is not showing in mounted path

### ISSUE THREAD

**Issue by arulkumaran456** [Azure/azure-storage-fuse#1215]
### Which version of blobfuse was used?
blobfuse2 version 2.0.0-preview.4

### Which OS distribution and version are you using?
RHEL 7.6

### If relevant, please share your mount command.
blobfuse2 mount /app/Log/ --config-file=config.yaml

### What was the issue encountered?
I am having issues while mounting increment mode file. Initially the file will have only the headers. after 30 or 40 seconds some content will be added to the same file. But the new content is not reflecting in mounted path. Only the old content is available 

**Config
------**
logging:
  type: syslog
  level: log_debug
  max-file-size-mb: 100
  file-count: 10
  track-time: true

components:
  - stream
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 40
  entry-expiration-sec: 40
  negative-entry-expiration-sec: 40

file_cache:
  path: /app/filebeat/blobfusetempfiles
  timeout-sec: 120
  create-empty-file: false
  cleanup-on-start: true
  refresh-seconds: 5
  max-size-mb: 4096

attr_cache:
  timeout-sec: 120
  no-cache-on-list: true

azstorage:
  type: block
  account-name: xxx
  container: xxx
  endpoint: xxx
  mode: xxx
  virtual-directory: true

### Have you found a mitigation/solution?
No

### Please share logs if available.

NA

**Comment by vibhansa-msft** [comment]
I see you are using RHEL 7.6 and there fuse3 might not be available so stay with fuse2 and that shall work as well.

**Comment by vibhansa-msft** [comment]
Did it work with Fuse3 and direct_io option for you ? If so, kindly close this issue report.

**Comment by arulkumaran456** [comment]
I have upgrade the blob fuse package to 2.0.5..

I am getting below error - Error: failed to initialize new pipeline [config error in Pipeline [component libfuse is out of order]]

**Comment by vibhansa-msft** [comment]
This means your pipeline config is invalid.  I see in the above comments
```
components:

stream
libfuse
file_cache
attr_cache
azstorage
```

This is incorrect. `libfuse` shall always be the first component. `stream` and `file_cache` can not co-exist so you need to remove `stream` if you are using local disk based caching. If you are running in stream mode then you need to remove `file_cache` and put `stream` in that place.

**Comment by arulkumaran456** [comment]
ok. I will make the config change and let you know

**Comment by arulkumaran456** [comment]
Still i could see the content mismatch in mounted path. The incremental content is not showing in mounted path

Version 2.0.5

Config
-------
logging:
  file-path: /app/blobfuse/test.log 
  type: base
  level: log_debug
  max-file-size-mb: 100
  file-count: 10
  track-time: true

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 0
  entry-expiration-sec: 0
  negative-entry-expiration-sec: 0
  direct-io: true
  ignore-open-flags: true

file_cache:
  path: /app/blobfusetempfiles
  timeout-sec: 0
  refresh-seconds: 5
  max-size-mb: 4096
  allow-non-empty-temp: true
  cleanup-on-start: true

attr_cache:
  timeout-sec: 0

azstorage:
  type: block
  account-name: xxxxx
  container: xxx
  endpoint: xxx
  mode: sas
  sas: xxxx

**Comment by arulkumaran456** [comment]
Hi Team, Any suggestion?

**Comment by arulkumaran456** [comment]
when i build the package i am getting undefined error

component/libfuse/libfuse.go:162:12: lf.initFuse undefined (type *Libfuse has no field or method initFuse)
component/libfuse/libfuse.go:174:9: lf.destroyFuse undefined (type *Libfuse has no field or method destroyFuse)

**Comment by arulkumaran456** [comment]
@vibhansa-msft any suggestion on the above build error

**Comment by vibhansa-msft** [comment]
you might be missing 'gcc' package. Install that package seperatly and then build. Also, install 'libfuse3-dev' package.

**Comment by vibhansa-msft** [comment]
With latest 2.1.0 release open issues with direct_io have been fixed. Try the new binary and reopen this report if your issue still persists.
