### ISSUE TITLE
Blobfuse2 performance extremely slow for copying small files 

### ISSUE THREAD

**Issue by sanket925** [Azure/azure-storage-fuse#1218]
### Which version of blobfuse was used?

blobfuse2 version 2.0.5

### Which OS distribution and version are you using?

Red Hat Enterprise Linux 8.7 (Ootpa)
### What was the issue encountered?
Blobfuse2 performance is extremely slow for copying/creating files. Command used cp -r <directory> <directory> it takes about 5 mins to copy 4mb of data as opposed to 40 sec for azure files. Storage account used is StorageV2 (general purpose v2) account.

### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
When you use 'cp' command files are not copied in parallel. One by one a file will be sent to Blobfuse. Also, if you are using file-cache model then first a copy of the file will be created in local cache and once its complete it will be uploaded to storage container. If you are using the streaming model then performance will be even lower (compared to file-cache). Let me know your config and if you can share debug logs from blobfuse, we can see if there is anything else hurting the performance.

**Comment by sanket925** [comment]
For Azure files we are using NFS. 

We have mounted a path on the linux using blobfuse. Now our application uses that directory for file I/O . For .eg an application uses this directory as a temporary storage, it can create a new directory and write log files in that directory. We see that if a directory is configured using azure files, it is giving better output that the directory using blobfuse. 

Another use case is : 
We have some data in local file system , we need to migrate that data into this blobfuse based directory mounted on linux, we are using linux cp command or rsync command to copy directory from local file system to blobfuse based directory

**Comment by vibhansa-msft** [comment]
For the migration story where you want to copy or sync data from local file-system to a storage container, Blobfuse is not the correct tool for such scenario. Instead you shall be looking at our other tool "AzCopy" which specialize in migration story.

For the NFS vs blobfuse perf query, local cache where file is created first in case of Blobfuse will be the difference maker here as NFS can directly read from source and upload but blobfuse does not support that. However, NFS and Blobfuse are still not comparable in some sense as they do not use the same protocol suite for data transfer.

**Comment by sanket925** [comment]
We have our apps and scripts dependent on filesystem commands as opposed to AZ commands API, hence we were thinking of using blobfuse. 

But are you saying blobfuse vs azure files could see a 3x performance degradation ?

**Comment by vibhansa-msft** [comment]
what is your use-case can you explain a bit so that I can suggest if there is anything we can optimize using config params.

**Comment by vibhansa-msft** [comment]
If you are using cp command then it will be sequential in nature and copy one file at a time. You can try AzCopy instead which is also a command line tool and specialize in data migration scenarios. This tool will need to mount anything it will just transfer the data from local system to your storage container and will be much faster if there are large amount of data to be synced or uploaded periodically.

Blobfuse is more suitable for flows where you want to mount, read/write some file and process the file.

**Comment by sanket925** [comment]
For cp command we are not worried for performance because this would only be used once when we migrate things. 

The use-case which we functionality wise is  : 
We have an application on cloud which needs a temporary directory. This temporary directory is mounted as blobfuse based azure container. Now as you said mostly our use-case is where this "application" would typically read/write and process files in the blobfuse directory and this is taking almost 2x-3x more time as compared to a file share based system

**Comment by vibhansa-msft** [comment]
Can you collect debug logs and share for me to look at where we are spending most of the time. 3X slower is someting wrong, it can't be that bad.

**Comment by sanket925** [comment]
Thanks a lot vibhansa, 

Sure give me some time I will get back to you with the logs.

**Comment by vibhansa-msft** [comment]
Closing this as there are no updates. Feel free to reopen once you have required inforamtion and log file.
