### ISSUE TITLE
du shows 0 sizes

### ISSUE THREAD

**Issue by ggrrll** [Azure/azure-storage-fuse#1222]
don't tell me that I cannot use basic commands like `du` ... 

### Which version of blobfuse was used?
 2.0.5

### Which OS distribution and version are you using?
Ubuntu 20.04.6 LTS

### If relevant, please share your mount command.
`sudo azure-storage-fuse/blobfuse2 -o direct_io mount poc_pipeline_blob/ --config-file=config.yaml`

### What was the issue encountered?
bash `du` shows 0 size for all directories 

### Have you found a mitigation/solution?
no

**Comment by ggrrll** [comment]
ok thanks
RIP `du`

**Comment by ggrrll** [comment]
btw, @vibhansa-msft what  do you think about  having a git repo in a blob ? is this gonna be also expensive? (with usual `git` operations  :`git status` ,...) 

thanks

**Comment by vibhansa-msft** [comment]
We have few customers using their git repo inside a container and building their code base on Azure VMs. Have not heard anyone complaining too much about the cost and all.
That being said, git creates a lot of temp files during git operations and then either renames them or delete them. When your git repo is cloned on a mounted path all such temp files will be uploaded and listed and later removed (when git asks us to do so). In that sense yes, there is a slightly higher cost involved in this scenario. If you are planning to just keep the codebase and not do much of git operations and its only about reading/writing files then it shall be ok.

**Comment by ggrrll** [comment]
thanks

this blob is not actually for the code base, but for the in/outputs (data versioning) -- working on testing also git LFS
