### ISSUE TITLE
mv a large container with complex nest of folders inside it cause data loss in Azure

### ISSUE THREAD

**Issue by huanghaiqing1** [Azure/azure-storage-fuse#1225]
### Which version of blobfuse was used?
blobfuse V1

### Which OS distribution and version are you using?
CentOS mount blobfuse mountpoint shared from Azure

### If relevant, please share your mount command.
blobfuse /mnt/cn/xxxxxxxx/ fuse --log-level=LOG_DEBUG,--tmp-path=/tmp/ramdisk_2sim_output_aptiv,--config-file=/root/xxxxxxx.cfg,--file-cache-timeout-in-seconds=0,attr_timeout=240,entry_timeout=240,negative_timeout=120,allow_other,nonempty,noauto

### What was the issue encountered?
When try to use linux command mv to move one big container with complex nest of folders with a new name in the same Azure storage account, the mount point is not accessable because of network issue, this cause mv command timeout and user checks left existing part and new moved part, they found a small part is missing on both sides. From Azure storage account tracing log, we can see there is a delete operation about the missing folder. Azure support says such kind of mv command for blobfuse mountpoint will trigger a local OS level cache for data handling. When unexpected condition happened, such as network timeout, will cause the part of cache can't be handled and then trigger a data loss. They also says another possible reason is not allowing multi sessions operats the moving part at the same time. We confirm we have crontab jobs aiming to the moving part, but only will create/read/write without any delete operations. 

### Have you found a mitigation/solution?
No

### Please share logs if available.
Wait for upload required one.

My question is mv in blobfuse mountpoint will trigger any data loss when unexpected conditions, such as "ctrl+c" quit, network timeout or powersupply loss during mv?

**Comment by vibhansa-msft** [comment]
Short answer is "yes" if blobfuse is terminated abruptly or copy command is cancelled there might be inconsistencies in container. There might be some files which are already uploaded while some might be in progress. Any file in progress will be left in between and will not be committed on destination so there might be some residual of that file.
When you say container is copied with a new name to same account, how are you using blobfuse for this. Something like "mv /mountpath/A /mountpath/B"? If the dataset is huge blobfuse might not be the ideal tool to do such huge operation as it will go one file at a time mode. Rename operations are not supported by backend on non-HNS accounts so rename here technically means we copy data with the new name and then delete the source file. You can either use HNS accounts if this operation is very frequent for you as it supports rename command directly. Or for large data copy jobs use AzCopy tool to copy the data and then delete it manually from source. Its highly parallel in nature and will take less amount of time to complete the job compared to blobfuse.

**Comment by vibhansa-msft** [comment]
Closing this assuming there is no further query on this topic. Feel free to reopen you have require any further assistance on this.
