### ISSUE TITLE
Cannot see directories, only files, in mounted blob location

### ISSUE THREAD

**Issue by pk-rescale** [Azure/azure-storage-fuse#1227]
### Which version of blobfuse was used?

blobfuse2 2.0.4

### Which OS distribution and version are you using?

Centos 7.9

### If relevant, please share your mount command.

blobfuse2 mount /mount_dir --config-file=~/config-filecache.yaml

Blobfuse config file:

***config file start***
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: ~/READ_ONLY_DO_NOT_EDIT/tempcache
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 360
  no-cache-on-list: false
  no-symlinks: false

azstorage:
  max-concurrency: 4
  type: block
  account-name: XXXXXXXXXX
  container: XXXXXXXXXXX
  endpoint: XXXXXXXXXXXX
  mode: spn
  tenantid: XXXXXXXXXX
  clientid: XXXXXXX
  clientsecret: XXXXXXXXXXXXX
***config file end***

### What was the issue encountered?

We cannot see directories (see attached screenshots) at or below the Container's root level when mounting the blob.  This only happens when ACL is in use.  We have the security principal being used  to mount the blob set to have 777-level permissions along with a contributer role.  All of the directories are non-empty.  Previously we did not have this issue in a different account/container wherein ACL was not in use.

<img width="1043" alt="Screenshot 2023-08-16 at 12 36 35 PM" src="https://github.com/Azure/azure-storage-fuse/assets/88114600/c795c32f-d0d6-4700-b442-25aa4b96fb0f">
<img width="1302" alt="Screenshot 2023-08-16 at 12 40 14 PM" src="https://github.com/Azure/azure-storage-fuse/assets/88114600/8162d72c-7e4d-491b-9196-553d396610fb">

### Have you found a mitigation/solution?

No, other than turning off ACL

**Comment by vibhansa-msft** [comment]
As you are interested in ACLs I assume your account is HNS enabled. If so, "type: block" shall be replaced with "type: adls" in "azstorage" section of your config file.

**Comment by pk-rescale** [comment]
That did the trick!  Thank you very much.
