### ISSUE TITLE
Blobfuse2 files do not update when files on the blob are updated

### ISSUE THREAD

**Issue by pk-rescale** [Azure/azure-storage-fuse#1228]
### Which version of blobfuse was used?
blobfuse2 2.0.4

### Which OS distribution and version are you using?
Centos 7.9

### If relevant, please share your mount command.
blobfuse2 mount /mount_dir --config-file=~/config-filecache.yaml

### Blobfuse config file:

#####config file start#####
allow-other: true

logging:
type: syslog
level: log_debug

components:

libfuse
file_cache
attr_cache
azstorage
libfuse:
attribute-expiration-sec: 120
entry-expiration-sec: 120
negative-entry-expiration-sec: 240

file_cache:
path: ~/READ_ONLY_DO_NOT_EDIT/tempcache
timeout-sec: 120
max-size-mb: 4096

attr_cache:
timeout-sec: 360
no-cache-on-list: false
no-symlinks: false

azstorage:
max-concurrency: 4
type: adls
account-name: XXXXXXXXXX
container: XXXXXXXXXXX
endpoint: XXXXXXXXXXXX
mode: spn
tenantid: XXXXXXXXXX
clientid: XXXXXXX
clientsecret: XXXXXXXXXXXXX
#####config file end######

### What was the issue encountered?

We are noticing that with this configuration, if files are updated on the blob through some non-blobfuse2 mechanism (i.e. say a user updates a file through the Azure API or portal) AFTER the blob has been mounted, the change to the file(s) is not reflected in the files on a mounted blobfuse2 directory.  Files accessed through a previously-mounted blobfuse2 mount will continue to show the old version of the file (for at least 5-10 hours or maybe more) and the blobfuse2 file is therefore out of date.  We think this is because locally cached files are not updating when a remote file on the blob changes.

Is there some way to "force" blobfuse2 to update files to stay in sync with what is currently on the blob more frequently?

<img width="1043" alt="Screenshot 2023-08-16 at 12 36 35 PM" src="https://github.com/Azure/azure-storage-fuse/assets/88114600/f838ea64-abd7-4d8a-a27d-ef5585e95ce6">

**Comment by vibhansa-msft** [comment]
You have set "timeout-sec: 120" which means once a file is downloaded it will be cached by blobfuse for 120 seconds. So, for next 2 minutes its not going to check the contents on container. On top of this kernel page cache will also hold the contents and you will keep getting old contents untill kernel flushes the cache (or you manually override it). Easiest way out of this is to disable both kernel and blobfuse cache. That being said, this means for every open now blobfuse has to download fresh contents from container and this will increase the cost as more storage calls are being done along with reducing the performance.
If you workflow needs immediate refresh of contents then set `timeout-sec: 0` in `file_cache` section of config file and use `-o direct_io` flag in your mount CLI.

**Comment by vibhansa-msft** [comment]
If above suggested options help, kindly close this issue.

**Comment by pk-rescale** [comment]
Thank you, I will try these suggestions.  Does adding -o direct_io change this behavior?

_

> kernel page cache will also hold the contents and you will keep getting old contents untill kernel flushes the cache

_

**Comment by vibhansa-msft** [comment]
direct_io is to mount a file-system with kernel cache in disabled mode.

**Comment by pk-rescale** [comment]
This looks to be working as intended.  Thanks very much @vibhansa-msft .

**Comment by cwu309** [comment]
I have a followup question to this. I had the same problem and this fix worked for me. However, I do still want some cacheing activated. Does using the flag "-o direct_io" overried the settings for file_cache? 

file_cache:
path: ~/READ_ONLY_DO_NOT_EDIT/tempcache
timeout-sec: 120
max-size-mb: 4096

Would this give me 2 minutes of cacheing even with the "-o direct_io" flag?
