### ISSUE TITLE
Unable to umask mountboption

### ISSUE THREAD

**Issue by fredspougne** [Azure/azure-storage-fuse#1234]
Hi,

I am trying to use umask option to mountban azure.blob.fuse in a container.
But I dont understand how the Mask  IS apply.
I want to obtain a file with 0600 with mask 0177 but I never obtained that.
Someone Can explain it?

Regards.

**Comment by vibhansa-msft** [comment]
Playing around with umask will be little tricky. If you are using a config file, easier way is to configure "default-permission: 0600" under "libfuse" section in your config file.
