### ISSUE TITLE
Blobfuse files do not sync after mounting in a container [ blobfuse2 version 2.1.0 ]

### ISSUE THREAD

**Issue by chicago7** [Azure/azure-storage-fuse#1235]
### Which version of blobfuse was used?

blobfuse2 version 2.1.0

### Which OS distribution and version are you using?

AKS node. this VM OS version : Ubuntu 22.04.2 LTS

root@aks-agentpool-23257322-vmss000000:/# chroot host
blobfuse2 --version
blobfuse2 version 2.1.0
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

### If relevant, please share your mount command.

I created a new storage class as detailed as follows:

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azureblob-fuse-premium
provisioner: blob.csi.azure.com
parameters:
  skuName: Standard_RAGRS  # available values: Standard_LRS, Premium_LRS, Standard_GRS, Standard_RAGRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=0
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10  # prevent billing charges on mounting
  - -o attr_timeout=0
  - -o entry_timeout=0
  - -o negative_timeout=0
  - --log-level=LOG_WARNING  # LOG_WARNING, LOG_INFO, LOG_DEBUG
  - --cache-size-mb=1000  # Default will be 80% of available memory, eviction will happen beyond that.
  - -o direct-io=true

PV yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=0
    - -o attr_timeout=0
    - -o entry_timeout=0
    - -o negative_timeout=0
    - -o direct-io=true
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # volumeid has to be unique for every identical storage blob container in the cluster
    # character `#` is reserved for internal use and cannot be used in volumehandle
    volumeHandle: unique-volumeid
    volumeAttributes:
      containerName: testnew
    nodeStageSecretRef:
      name: azure-secret08
      namespace: default

### What was the issue encountered?

 Normal   Scheduled    28s                default-scheduler  Successfully assigned default/nginx-blob to aks-agentpool-23257322-vmss000000
  Warning  FailedMount  12s (x6 over 28s)  kubelet            MountVolume.MountDevice failed for volume "pv-blob" : rpc error: code = Internal desc = Mount failed with error: rpc error: code = Unknown desc = exit status 1 Error: invalid FUSE options. Allowed FUSE configurations are: `-o attr_timeout=TIMEOUT`, `-o negative_timeout=TIMEOUT`, `-o entry_timeout=TIMEOUT` `-o allow_other`, `-o allow_root`, `-o umask=PERM, output:

when I created a pod, I encountered the above error message. The **direct-io** parameter is not supported according to the above error message. How should this problem be solved? Thanks.

### Please share logs if available.

**Comment by vibhansa-msft** [comment]
You need to correct your input to "-o direct_io". Also, this config shall be given in the PV config and that shall help you refresh the contents. Another issue that I observe here is "--use-attr-cache=true". When you use this blobfuse will cache the metadata of files and it will not look for any updates on the storage container. You need to make this cache "false" to work as per expectations.
One word of caution here : In direct io mode all caching are disabled and there will be more calls to storage container which means higher storage cost.

**Comment by chicago7** [comment]
@vibhansa-msft  Thanks for your response. I just test it. It works now. thanks again. But I observed that the sync is not real time, the sync is delayed by about 1 minute. How should this delayed issue be solved?

**Comment by vibhansa-msft** [comment]
With both direct_io set and attr-cache removed from config, you still observe 1 minute delay in sync of files you mean? You observe mismatch in metadata like size, LMT etc or the actual contents of the file.

I suspect still  some level of kernel caching happening here. Can you share debug logs from blobfuse end to see why the file was not downloaded again.

**Comment by chicago7** [comment]
The syslog is as follows. FYI. You can ignore the information[blobfuse2: A new version [2.1.0] is available]. I have already updated the version to 2.1.0. Thanks.
============================
# less /var/log/syslog|grep blobfuse
Sep  1 04:46:29 aks-agentpool-38757936-vmss000000 containerd[2205]: time="2023-09-01T04:46:29.010513713Z" level=info msg="CreateContainer within sandbox \"5eb29b4b8a83cb247eccac34bce8f3412a725cb94a90764f564a9088936afa53\" for container &ContainerMetadata{Name:install-blobfuse-proxy,Attempt:0,}"
Sep  1 04:46:29 aks-agentpool-38757936-vmss000000 containerd[2205]: time="2023-09-01T04:46:29.249633583Z" level=info msg="CreateContainer within sandbox \"5eb29b4b8a83cb247eccac34bce8f3412a725cb94a90764f564a9088936afa53\" for &ContainerMetadata{Name:install-blobfuse-proxy,Attempt:0,} returns container id \"a446c822a97827421f8a1d8d9c09afcb317d579af9be6c1813d6afbb0d4f284a\""
Sep  1 04:46:29 aks-agentpool-38757936-vmss000000 sync-container-logs.sh[3646]: Linking csi-blob-node-wh862_kube-system_install-blobfuse-proxy-a446c822a97827421f8a1d8d9c09afcb317d579af9be6c1813d6afbb0d4f284a.log
Sep  1 04:46:31 aks-agentpool-38757936-vmss000000 systemd[1]: Configuration file /lib/systemd/system/blobfuse-proxy.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Sep  1 04:46:31 aks-agentpool-38757936-vmss000000 systemd[1]: Configuration file /lib/systemd/system/blobfuse-proxy.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Sep  1 04:46:31 aks-agentpool-38757936-vmss000000 blobfuse-proxy[56032]: I0901 04:46:31.663857   56032 util.go:184] get OS info: &{Ubuntu 22.04}
Sep  1 04:46:31 aks-agentpool-38757936-vmss000000 blobfuse-proxy[56032]: I0901 04:46:31.663889   56032 server.go:125] proxy default using blobfuse V2 for mounting
Sep  1 04:46:31 aks-agentpool-38757936-vmss000000 blobfuse-proxy[56032]: I0901 04:46:31.663900   56032 main.go:60] Listening for connections on address: %v
Sep  1 04:46:31 aks-agentpool-38757936-vmss000000 blobfuse-proxy[56032]: /var/lib/kubelet/plugins/blob.csi.azure.com/blobfuse-proxy.sock
Sep  1 04:46:31 aks-agentpool-38757936-vmss000000 blobfuse-proxy[56032]: I0901 04:46:31.663941   56032 server.go:113] Start GRPC server at /var/lib/kubelet/plugins/blob.csi.azure.com/blobfuse-proxy.sock, TLS = false
Sep  1 04:50:13 aks-agentpool-38757936-vmss000000 blobfuse-proxy[56032]: I0901 04:50:13.880668   56032 server.go:67] received mount request: protocol: , server default blobfuseVersion: 1, mount args /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/6c02ffeec8bc86f5020d8c5925d8c73ea55e1a22d00fb3c067c55f0fdab20f76/globalmount -o allow_other --file-cache-timeout-in-seconds=0 -o attr_timeout=0 -o entry_timeout=0 -o negative_timeout=0 -o direct_io --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false --tmp-path=/mnt/unique-volumeid --container-name=testnew
Sep  1 04:50:13 aks-agentpool-38757936-vmss000000 blobfuse-proxy[56032]: I0901 04:50:13.880706   56032 server.go:76] append --ignore-open-flags=true to mount args
Sep  1 04:50:13 aks-agentpool-38757936-vmss000000 blobfuse-proxy[56032]: I0901 04:50:13.880749   56032 server.go:80] mount with v2, protocol: , args: mount /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/6c02ffeec8bc86f5020d8c5925d8c73ea55e1a22d00fb3c067c55f0fdab20f76/globalmount -o allow_other --file-cache-timeout-in-seconds=0 -o attr_timeout=0 -o entry_timeout=0 -o negative_timeout=0 -o direct_io --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false --tmp-path=/mnt/unique-volumeid --container-name=testnew --ignore-open-flags=true
Sep  1 04:50:19 aks-agentpool-38757936-vmss000000 blobfuse-proxy[56032]: I0901 04:50:19.082151   56032 server.go:93] successfully mounted
Sep  1 04:50:19 aks-agentpool-38757936-vmss000000 blobfuse-proxy[56032]: I0901 04:50:19.082172   56032 server.go:96] blobfuse output: *** blobfuse2: A new version [2.1.0] is available. Consider upgrading to latest version for bug-fixes & new features. ***
# blobfuse2 --version
blobfuse2 version 2.1.0
#

**Comment by vibhansa-msft** [comment]
Did you update blobfuse binary using package manager or installed directly by dowloadin the rpm/deb from github. This might be one reason why its complaining. You can update through package manager once as hash of the file might be different.

**Comment by chicago7** [comment]
Installation steps are as follows:
=======================
wget https://dashboarddiag.blob.core.chinacloudapi.cn/test20220609/blobfuse2-2.1.0-Ubuntu-22.04.x86_64.deb

dpkg -i blobfuse2-2.1.0-Ubuntu-22.04.x86_64.deb
(Reading database ... 64896 files and directories currently installed.)
Preparing to unpack blobfuse2-2.1.0-Ubuntu-22.04.x86_64.deb ...
Unpacking blobfuse2 (2.1.0) over (2.0.5) ...
Setting up blobfuse2 (2.1.0) ...
Processing triggers for rsyslog (8.2112.0-2ubuntu2.2) ...


sudo apt-get install blobfuse2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
blobfuse2 is already the newest version (2.1.0).
The following packages were automatically installed and are no longer required:
  bc python3-automat python3-bcrypt python3-click python3-colorama python3-constantly python3-hamcrest python3-hyperlink python3-incremental python3-pyasn1 python3-pyasn1-modules python3-service-identity
  python3-twisted python3-zope.interface
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.

**Comment by vibhansa-msft** [comment]
Can you try removing using "sudo apt remove blobfuse2" and then do not install using the wget, directly install using "sudo apt install blobfuse2" and check you get the same error or not.

**Comment by chicago7** [comment]
Thank you for your support. 

Storageclass configuration：
 
mountOptions:
  - '-o allow_other'
  - '--file-cache-timeout-in-seconds=0'
  - '--use-attr-cache=false'
  - '--cancel-list-on-mount-seconds=10'
  - '-o attr_timeout=0'
  - '-o entry_timeout=0'
  - '-o negative_timeout=0'
  - '--log-level=LOG_WARNING'
  - '--cache-size-mb=1000'
  - '-o direct_io'
 
PV configuration：
 
mountOptions:
    - '-o allow_other'
    - '--file-cache-timeout-in-seconds=0'
    - '-o attr_timeout=0'
    - '-o entry_timeout=0'
    - '-o negative_timeout=0'
    - '-o direct_io'


blobfuse version --check [there is no any warning info] 
---------------------------------------
wget https://dashboarddiag.blob.core.chinacloudapi.cn/test20220609/blobfuse2-2.1.0-Ubuntu-22.04.x86_64.deb
--2023-09-06 03:55:43--  https://dashboarddiag.blob.core.chinacloudapi.cn/test20220609/blobfuse2-2.1.0-Ubuntu-22.04.x86_64.deb
Resolving dashboarddiag.blob.core.chinacloudapi.cn (dashboarddiag.blob.core.chinacloudapi.cn)... 40.73.48.100
Connecting to dashboarddiag.blob.core.chinacloudapi.cn (dashboarddiag.blob.core.chinacloudapi.cn)|40.73.48.100|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15604716 (15M) [application/octet-stream]
Saving to: 'blobfuse2-2.1.0-Ubuntu-22.04.x86_64.deb'

blobfuse2-2.1.0-Ubuntu-22.04.x86_64.deb              100%[===================================================================================================================>]  14.88M  --.-KB/s    in 0.1s

2023-09-06 03:55:44 (120 MB/s) - 'blobfuse2-2.1.0-Ubuntu-22.04.x86_64.deb' saved [15604716/15604716]

dpkg -i blobfuse2-2.1.0-Ubuntu-22.04.x86_64.deb
(Reading database ... 64896 files and directories currently installed.)
Preparing to unpack blobfuse2-2.1.0-Ubuntu-22.04.x86_64.deb ...
Unpacking blobfuse2 (2.1.0) over (2.0.5) ...
Setting up blobfuse2 (2.1.0) ...
Processing triggers for rsyslog (8.2112.0-2ubuntu2.2) ...

sudo apt-get install blobfuse2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
blobfuse2 is already the newest version (2.1.0).
The following packages were automatically installed and are no longer required:
  bc python3-automat python3-bcrypt python3-click python3-colorama python3-constantly python3-hamcrest python3-hyperlink python3-incremental python3-pyasn1 python3-pyasn1-modules python3-service-identity
  python3-twisted python3-zope.interface
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.

 blobfuse2 version --check
blobfuse2 version: 2.1.0

**Comment by souravgupta-msft** [comment]
Can you update your PV mount options as below. Also, you can remove the mount options section from the storage class config.
```
'-o allow_other'
'-o direct_io'
'--file-cache-timeout-in-seconds=0'
'--use-attr-cache=false'
'--cancel-list-on-mount-seconds=10'
'-o attr_timeout=0'
'-o entry_timeout=0'
'-o negative_timeout=0'
'--log-level=LOG_DEBUG'
'--cache-size-mb=1000'
```
Please retry and let us know how it goes.

**Comment by chicago7** [comment]
@souravgupta-msft  thanks for your support. currently, it works now. the blobfuse2 version is still 2.0.5.

**Comment by souravgupta-msft** [comment]
Thanks for confirming. You can consider updating to [blobfuse2 2.1.0](https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.1.0) which contains a bug fix for the direct_io option.

**Comment by souravgupta-msft** [comment]
Closing this. If you have other questions, you can continue in this thread.
