### ISSUE TITLE
The timestamp of the mounted directory is still at 01/01/1970

### ISSUE THREAD

**Issue by Tolivier** [Azure/azure-storage-fuse#124]
Even when new files are created, the timestamp of the mounted directory is not changed.
I use Apache Nifi to treat files in the Azure Blob Storage and the processor "ListFile" considers that there is nothing to do because the timestamp is not updated.

**Comment by seguler** [comment]
There is no such thing as a directory on blob storage. Therefore we do not want to implement directory timestamps for the time-being. 

We can keep this issue open as a known limitation.

**Comment by rishabpoh** [comment]
This is by design for blobs, but for ADLS this will not happen.

**Comment by vibhansa-msft** [comment]
Azure storage only maintains last modified time. With version 1.3.1 timestamp issues have been fixed. However as do not maintain last change or access time, both will also be pointing to last modified time.
