### ISSUE TITLE
Cannot use blobfuse2 in Azure AKS 1.25.11

### ISSUE THREAD

**Issue by chicago7** [Azure/azure-storage-fuse#1241]
### Which version of blobfuse was used?

blobfuse2 version is 2.0.3

### Which OS distribution and version are you using?

AKSUbuntu-2204gen2containerd-202308.10.0

### If relevant, please share your mount command.

StorageClass:

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azureblob-fuse-premium2
provisioner: blob.csi.azure.com
parameters:
  skuName: Standard_RAGRS  # available values: Standard_LRS, Premium_LRS, Standard_GRS, Standard_RAGRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=0
  - --use-attr-cache=false
  - --cancel-list-on-mount-seconds=10  # prevent billing charges on mounting
  - -o attr_timeout=0
  - -o entry_timeout=0
  - -o negative_timeout=0
  - --log-level=LOG_WARNING  # LOG_WARNING, LOG_INFO, LOG_DEBUG
  - --cache-size-mb=1000  # Default will be 80% of available memory, eviction will happen beyond that.
  - -o direct_io

PV:

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob-kv-cdp
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-premium2
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=0
    - -o attr_timeout=0
    - -o entry_timeout=0
    - -o negative_timeout=0
    - -o direct_io
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # volumeid has to be unique for every identical storage blob container in the cluster
    # character `#` is reserved for internal use and cannot be used in volumehandle
    volumeHandle: dlscdpprodn3_cdp_01
    volumeAttributes:
      containerName: cdp
      keyVaultSecretName: dlscdpprodn3-xxxx-xx
      keyVaultURL: https://kv-xx-xxx-n3.vault.azure.cn/
      storageAccountName: dlscdpprodn3

### What was the issue encountered?

kubelet MountVolume.MountDevice failed for volume "pv-blob" : rpc error: code = Internal desc = Mount failed with error: rpc error: code = Unknown desc = exit status 1 Error: invalid FUSE options. Allowed FUSE configurations are: -o attr_timeout=TIMEOUT, -o negative_timeout=TIMEOUT, -o entry_timeout=TIMEOUT -o allow_other, -o allow_root, `-o umask=PERM,

**Comment by vibhansa-msft** [comment]
"direct_io" is not supported in Blobfuse2 2.0.3 version. You need to upgrade to 2.1.0 or skip providing this option in your mount options.
