### ISSUE TITLE
Is it possible to refresh SAS token without remounting?

### ISSUE THREAD

**Issue by sfc-gh-nalekseev** [Azure/azure-storage-fuse#1246]
This is more of a general question. I want to use blobfuse2 to mount a specific container. I am planning to use SAS tokens to grant access to only that specific container. The token would of course expire after a while. Is it possible to provide a newly generated token to blobfuse2 without remounting the directory?

**Comment by sfc-gh-nalekseev** [comment]
@vibhansa-msft do you know if that would work the same way when the token is passed as an env variable?

**Comment by vibhansa-msft** [comment]
No it will not. Blobfuse binary actively looks for file change notification and if config file is changed, some of the config settings are reloaded. SAS token is one such config.

**Comment by sherryhao** [comment]
@vibhansa-msft May I know what would happen to PV/PVC in AKS cluster if the secret has been updated? Should we restart the entire pods to load the new secret for blobfuse?

**Comment by vibhansa-msft** [comment]
Any auth or pipeline related config if you wish to change you have to unmount and remount to use the latest config.
