### ISSUE TITLE
Blobfuse2 uploading empty file on save using gedit

### ISSUE THREAD

**Issue by jfantinhardesty** [Azure/azure-storage-fuse#1259]
### Which version of blobfuse was used?
2.1.0

### Which OS distribution and version are you using?
Ubuntu 20.04.6

### If relevant, please share your mount command.
blobfuse2 mount ./mount --config-file=./config.yaml

### What was the issue encountered?
When saving changes to files in certain text editors a blank file is updated with no data in the file. Based on #1060 we set "create-empty-file: true" for the "file-cache" component. However, this results in files upload to Azure storage to be an empty file. The contents are saved in the file_cache so when reopening the file it appears to have the valid dat. But once the file_cache expires and we redownload the file, the file is empty.

It seems this issue can be replicated with any editor that saves to a temporary file and does a rename like gedit does.

### Have you found a mitigation/solution?
No.

### Please share logs if available.
Log file
[blobfuse2.txt](https://github.com/Azure/azure-storage-fuse/files/12897017/blobfuse2.txt)

Config file as a text file
[config.txt](https://github.com/Azure/azure-storage-fuse/files/12897021/config.txt)

**Comment by vibhansa-msft** [comment]
You understanding of the flag to create empty file is correct. When user creates a file using blobfuse, this flag defines whether an empty file shall be created on the storage as well or not. Actual contents of the file will be uploaded only when user closes the file handle i.e., close file from editor in your case. On next open if the file is truncated again by editor, you will see file with 0 bytes on storage as well. We will go through your config file and logs to understand the situation better.

**Comment by vibhansa-msft** [comment]
Which file are you talking about being corrupted from the logs you have shared.

I see couple of instances of opening "test.txt" and then closing the handles. At any of the close I do not see it getting uploaded, which means the file was not modified at all.

".goutputstream-1D0UC2" this file was created (and uploaded during creation).  Before closing the handle used to create this file, there were other handles created for the same. Then fsync was called on the original handle (one used to create).  Then its renamed "test.txt". Till this time file is empty only as I do not see any upload being done so far. So, on storage as well when this rename is hit, file is still empty.

Any issue you see here, not sure its the editor behavior or some other issue from your end. As per logs things went as expected (based on the sequence of calls coming in).

**Comment by jfantinhardesty** [comment]
The file is the text.txt file. When using gedit, and some other editors, on writes they write to a temporary file which is the ".goutputstream-1D0UC2" file and then rename to the original file. The issue I think is that the rename call happens before the close call to the ".goutputstream-1D0UC2" so the file that ends up getting uploaded is the empty file for ".goutputstream-1D0UC2" that was uploaded because the "create-empty-file" flag was set to true. This also makes sense since issue #1060 fails under this workload when "create-empty-file" flag is false and the write fails. I am fairly certain that the issue is with blobfuse2.

This is fairly easy to replicate. Mount a directory using blobfuse2 and create an empty file. Then use gedit to do write to the file and then download the file from the cloud, it will be empty. Reopening the file in the cache will show the correct data, because it writes correctly to the cache, but not to the cloud.

**Comment by vibhansa-msft** [comment]
If local file is renamed before the close then on container you will see only the empty file created being renamed. Later when handle closes there is no way to know file was renamed in the background or not and as the temp file will be later deleted or be non-existent it might not be visible on container at all. This kind of explains what might be happening and what logs indicate as well. Let me dig more tomorrow on this and see if I can reproduce this case myself.

**Comment by vibhansa-msft** [comment]
I was looking at the logs from scratch again to see if I have missed anything here. There is something interesting. Before the rename a fsync is called on the temp file. By default fsync call will delete the locally cached file but there was a feature request by one of our customers to overrride this functionality and instead of clearing the cache force upload a file to storage container. This feature has been merged in the main line. If you can take up the top of the main branch, build locally and verify that this feature solves your problem then may be we dont need to the other code change that was suggested. To enable this feature in "file_cache" section in config file add a flag "sync-to-flush: true". Do let me know if this works for you.

**Comment by jfantinhardesty** [comment]
I tried that and it did not work. I think the issue is that the "sync-to-flush" flag just sets the dirty file handle in the call to SyncFile and itself does not upload the file. It would work when there is a call to flush the file afterward but there is not a call to flush before the rename so this doesn't work. I have attached the logs from this attempt if that is helpful.
[sync-to-flush-log.txt](https://github.com/Azure/azure-storage-fuse/files/13219215/sync-to-flush-log.txt)

**Comment by vibhansa-msft** [comment]
Yes your observation is correct. As per code we just set the flag as dirty so that on close the file will be uploaded. Let me correct the code and instead force it to upload the file. Once I have the build ready with this change will share a path with you and you can validate your workflow with that private bits.

**Comment by vibhansa-msft** [comment]
Can you try out the branch mentioned in above PR which has the fix to force upload a file on fsync call.

**Comment by vibhansa-msft** [comment]
So with this changeset, original issue is also resolved with gedit?

**Comment by jfantinhardesty** [comment]
Yes with the change to the "sync-to-flush", this does fix the issue with gedit.
