### ISSUE TITLE
[feature request] support file/dir mode setting

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#126]
it looks like file_mode & dir_mode setting is not supported. if I make a new file, the default file mode is 0544(see below example), 0544 would not work for kubernetes containers, it's a show stopper.
Can we set default file_mode & dir_mode as 0777, that is what we do for azure file mounting. That is, user could not change azure file file_mode & dir_mode either after mounting, while usually user could set 0777 for every file & dir in the mounting process, that's a workaround for most cases. Can we do same for blobfuse?

Current blobfuse version: v0.2.4
```
root@nginx-flex-blobfuse:/data# echo z > z
root@nginx-flex-blobfuse:/data# ls -lt
total 20
-rw-r--r-- 1 root root    2 Mar  8 05:32 z
-rw-r--r-- 1 root root    2 Mar  8 05:32 b
-rwxrwx--- 1 root root    6 Mar  8 05:32 x
drwxrwx--- 2 root root 4096 Mar  8 05:28 andy
drwxrwx--- 2 root root 4096 Mar  8 05:25 fuse
drwxrwx--- 2 root root 4096 Jan  1  1970 a
-rwxrwx--- 1 root root    6 Jan  1  1970 hello.log
-rwxrwx--- 1 root root    6 Jan  1  1970 y
```

**Comment by andyzhangx** [comment]
@seguler

**Comment by andyzhangx** [comment]
If I remount the blobfuse, all dir_mode & file_mode changes to 0770 again, can we change this 0770 or 0544 to 0777 instead, 0777 would be most suitable in most cases.

After remount:
```
root@nginx-flex-blobfuse:/data# ls -lt
total 0
drwxrwx--- 2 root root 4096 Jan  1  1970 a
drwxrwx--- 3 root root 4096 Jan  1  1970 andy
-rwxrwx--- 1 root root    2 Jan  1  1970 b
drwxrwx--- 3 root root 4096 Jan  1  1970 fuse
-rwxrwx--- 1 root root    6 Jan  1  1970 hello.log
-rwxrwx--- 1 root root    6 Jan  1  1970 x
-rwxrwx--- 1 root root    6 Jan  1  1970 y
-rwxrwx--- 1 root root    2 Jan  1  1970 z
```

**Comment by seguler** [comment]
How did you create these files ? I thought we fixed those in 0.3 release, and all new created files should always get 770 permissions...

In regards to 770 vs 777; if you mount it with -o allow_other option, you'll get 777 permissions. If not, the permissions will be 770 (this is in the latest blobfuse 0.3 release)

**Comment by seguler** [comment]
Oh yeah - I haven't sent you a 0.3 binary for kubernetes yet.. Waiting for the 0.3.1 release which should happen tomorrow...

**Comment by andyzhangx** [comment]
@seguler  I am using 0.2.4 blobfuse binary, and I would use 0777 by default, could you provide an official place to download 0.3.1 blobfuse for k8s v1.7-v1.9?
Since azure file is too slow currently, I would recommend customer to use blobfuse driver if possible, while according file mode is one blocking issue here.

**Comment by seguler** [comment]
Yes - will provide you the binaries today.

**Comment by andyzhangx** [comment]
@seguler in blobfuse v1.0.2, `allow_other` could not be specified by default. Is it possible to set `user_allow_other` in `/etc/fuse.conf` by default, so we don't need to do extra configuration after deployment, and in k8s, it's difficult to do that.
```
$ ./blobfuse test --container-name=public --tmp-path=/tmp/blobfuse/ -o allow_other
fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf
```
