### ISSUE TITLE
File rename not working on HNS-enabled ADLS with User Delegation Key SAS token

### ISSUE THREAD

**Issue by Thibaultatdlw** [Azure/azure-storage-fuse#1264]
### Which version of blobfuse was used?
2.1.0

### Which OS distribution and version are you using?
Ubuntu Server 20.04 LTS

### If relevant, please share your mount command.
Mounting is automated through the Azure NodeJS SDK (@azure/batch) with a mount configuration.

### What was the issue encountered?
I am working on a NodeJS application which makes use of the Azure NodeJS SDK, specifically the @azure/batch package. When creating a batch job, I pass a mount configuration for mounting an Azure Storage Account container (HNS-enabled ADLS) to the Batch Job Node (VM running the job). This mount uses Blobfuse2. To authenticate with the Storage Container, the application uses the DefaultAzureCredential-class to get the Managed Identity. It will then use this credential to generate a User Delegation Key (BlobServiceClient.getUserDelegationKey()), finally it will use this User Delegation Key in the generateBlobSASQueryParameters()-method to generate a SAS URI. This SAS URI will then be used by Blobfuse2 for authenticating with the Storage Container.
Files in the mount of the Batch Node VM cannot be renamed when Blobfuse2 uses a User Delegated SAS token. When the SAS token is generated using the storage account key, like described in the FAQ (with az cli), Blobfuse2 is able to rename them.

Using the az cli to generate a SAS token for renaming is not possible in my case, SAS token generating is done automatically, and using an account key is a security risk.

### Have you found a mitigation/solution?
No.

### Please share logs if available.
Error when doing the mv command:
![2023-10-18_15-41-13](https://github.com/Azure/azure-storage-fuse/assets/145967720/601a028d-5ce2-46f8-9d5e-86d29bc02645)
Error in the logs (when I manually make the mount in a VM): 
![asdfasdf](https://github.com/Azure/azure-storage-fuse/assets/145967720/7d4c6a50-f8c0-4e24-b08f-e9f7fb3cdb31)

**Comment by vibhansa-msft** [comment]
This issue has been fixed and next release will have the fix. If you wish to try out the fix you can pull top of the main branch and build locally.
