### ISSUE TITLE
Support storage connection strings

### ISSUE THREAD

**Issue by DamienCassou** [Azure/azure-storage-fuse#1265]
The README and example config file mention several variables to configure to reach a given storage. I'm wondering if accepting a [storage connection string](https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string) would simplify usage.

### Which version of blobfuse was used?

2.1.0

### Which OS distribution and version are you using?

Fedora 38

**Comment by vibhansa-msft** [comment]
Depending on what kind of auth mode you are using those parameters are required. When you talk about using connection string then mostly you wish to use key based authentication and in that case you just need to configure "key" only. 
Account-name, auth param and container name are the only thing you need to configure to reach your storage account. If you choose SPN or MSI as auth mode then yes there are couple of parameters required and connection string will mostly not solve those cases. Let me know your view on this.

**Comment by vibhansa-msft** [comment]
Endpoint and mode can be skipped when you are using key based auth. So you just need to provide account-name and key value thats all. Storage explorer also gives you options that you can either use connection string or provide key separately. Also this will work only for key based auth but for SAS and SPN or other OAuth based auth you still need to provide remaining config params so this will not solve much of a hassle here.

**Comment by DamienCassou** [comment]
I understand. Feel free to close the issue.
