### ISSUE TITLE
Please document how to use fstab

### ISSUE THREAD

**Issue by DevopsMercenary** [Azure/azure-storage-fuse#1268]
It appears that Blobfuse2 can be used with an fstab configuration.  There are tickets that show some examples.

However, the Azure docs (https://learn.microsoft.com/en-us/azure/storage/blobs/blobfuse2-configuration)  nor the readme.md mentions anything about using Blobfuse2 with fstab.

**Comment by vibhansa-msft** [comment]
It's there in the wiki "https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Installation#persisting-mount".
Do let me know if you want more information to be added here.

**Comment by vibhansa-msft** [comment]
Feel free to reopen if you feel above documentation was not complete or did not make sense for you in your workflow.
