### ISSUE TITLE
Very slow directory listings in file browsers

### ISSUE THREAD

**Issue by chrisposito** [Azure/azure-storage-fuse#1274]
### Which version of blobfuse was used?
blobfuse2 2.1.0

### Which OS distribution and version are you using?
Ubuntu 22.04.3 (Desktop version, installed on bare metal, not AKS or container).

### If relevant, please share your mount command.
blobfuse2 mount $mountpoint --container-name=$AZURE_STORAGE_ACCOUNT_CONTAINER --log-level=LOG_DEBUG $ADDITIONAL_OPTIONS --tmp-path=$TMP_PATH --allow-other=true

### What was the issue encountered?
Browsing to directory containing large files with any GUI file browser hangs for several minutes before directory listing is provided, while files seem to be downloading to cache. Not sure why files are downloading for just a directory listing.
Have tried the following browsers: Nautilus (default), Thunar, Dolphin, Nemo with same behavior
I've made sure thumbnails, previews, etc are disabled in all cases, so I'm not sure why the files are being downloaded to the cache.
Is there a FUSE option or blobfuse2 option that would prevent this behavior of caching on directory listing before a file opened?

When listing the directory with the `ls` command, output is listed immediately.

### Have you found a mitigation/solution?
No

### Please share logs if available.
Log indicates GET command, where the file is downloaded even though it hasn't been opened:

Logs are attached (too long to include in issue body).

[blobfuse_folderlisting_debug.txt](https://github.com/Azure/azure-storage-fuse/files/13180044/blobfuse_folderlisting_debug.txt)

**Comment by vibhansa-msft** [comment]
Blobfuse does not list or download files on its own. When a directory listing is called, blobfuse retreives list of files/directories in the given path from storage which comes in batches of 5000 entries. If the list of files in your container or directory is huge then it will take some time to get the entire list.  On a typical CLI interface the list will be sent as and when we receive but the GUI interface will not render untill everything is retreived and that might be the reason why its taking time. Can you confirm the same on the CLI interface as well that it takes time or not.

For the download part, blobfuse will not download any file untill it receives a call to open the file. If the GUI or some other application does a file-open call then a download will start. 

I do see in logs that openFile is called and that triggered the download. This part you need to check on your application or GUI side. 

In addition I do see a lot of getAttr calls which means blobfuse is trying to get the properties of a file/folder. Can you share your config file as well, as I doubt there is something missing there. Kindly share your config file and all the CLI inputs that you provide while mounting.

**Comment by chrisposito** [comment]
From the command line, the ls command lists the directory near-instantly. It's only when using (any) file browser that I see the issue.

There aren't many files in the directory I'm try to list (15 files), but many of them are 100-400MB, so a full download of each of them to the cache takes a long time.

I'm not using a config file a the moment, instead just using CLI options and environmental variables:

These are the environmental variables set:
AZURE_STORAGE_ACCOUNT=REDACTED
AZURE_STORAGE_ACCOUNT_TYPE=block
AZURE_STORAGE_AUTH_TYPE=SAS

And this is the mount command being run:
blobfuse2 mount /mnt/azure --container-name=REDACTED --log-level=LOG_DEBUG --tmp-path=/tmp/azure --allow-other=true

**Comment by vibhansa-msft** [comment]
You shall add "--attr-timeout=120 --entry-timeout=120 --negative-timeout=120 --use-attr-cache=true" to your CLI command. Do let me know if this solves your problem of listing. The file download is not an issue from blobfuse end its the application/GUI asking us to open the file resulting into download and that will add extra network calls slowing down the whole workflow. You might need to tune in something from the GUI in this case.

**Comment by chrisposito** [comment]
I just tested with those options added, but I'm getting the same results in Nautilus, Dolphin, and Thunar. I also tried a timeout of 15 instead, just to see if maybe a directory listing would load upon hitting that 15 second threshold, but it still takes several minutes. As far as tuneables in the file browser apps, I'm not seeing much beyond disabling previews/thumbnails, which I've already disabled. 

I also looked at debug logs for Nautilus just to see if that gave any more info, but that doesn't give much info, just that it's starting a file list operation "async_job_start: ../src/nautilus-directory-async.c:350: starting file list in 0x5570da9617a0", a long hang, then after a few minutes a bunch of "Files added to window _path/to/each/file_" messages for each file, all within the span of a second.

**Comment by vibhansa-msft** [comment]
Can you share the logs with this config set. Do not strip the logs, I want all info from mount till you get the listing done on GUI. If you have not set log_debug so far set the log level to log_debug so that we can capture all deatils on what is going on in background.

**Comment by chrisposito** [comment]
Hi, yes, here are some fresh logs with the 120 timeouts and use-attr-cache mount options added. The logs start before mounting, until after the directory contents are displayed in the file browser (Ubuntu's default file browser Nautilus in this case).
It's much faster today, but still slow, taking about a minute to list the directory. (I'm on a fiber connection today vs. satellite yesterday.) I'd still like to make the performance as good as possible and avoid fetching full files until they're needed, since the folks using it may be working with satellite or LTE internet speeds.
[blobfuse2.log](https://github.com/Azure/azure-storage-fuse/files/13190741/blobfuse2.log)

**Comment by vibhansa-msft** [comment]
```
Oct 27 10:16:57 ubuntu-laptop blobfuse2[17077]: LOG_TRACE [libfuse_handler.go (452)]: Libfuse::libfuse_opendir : 
...
Oct 27 10:16:57 ubuntu-laptop blobfuse2[17077]: LOG_TRACE [libfuse_handler.go (478)]: Libfuse::libfuse_releasedir : , handle: 1
...
Oct 27 10:16:59 ubuntu-laptop blobfuse2[17077]: LOG_TRACE [libfuse_handler.go (452)]: Libfuse::libfuse_opendir : Perf_Test/
...
Oct 27 10:16:59 ubuntu-laptop blobfuse2[17077]: LOG_TRACE [libfuse_handler.go (478)]: Libfuse::libfuse_releasedir : , handle: 3
```
As per above logs listing of files in a directory never took long time. It's always withing a second boundary.
In logs I do not see any listing call getting more then 20 objects (which shall be roughly the number of files you have in Perf_Test directory.


Only long time wait I see is in downloading a file:
```
Oct 27 10:16:59 ubuntu-laptop blobfuse2[17077]: LOG_TRACE [block_blob.go (670)]: BlockBlob::ReadToFile : name Perf_Test/test1.bin, offset : 0, count 314572800
Oct 27 10:17:14 ubuntu-laptop blobfuse2[17077]: LOG_DEBUG [block_blob.go (696)]: BlockBlob::ReadToFile : Download complete of blob Perf_Test/test1.bin
...
Oct 27 10:17:14 ubuntu-laptop blobfuse2[17077]: LOG_TRACE [block_blob.go (670)]: BlockBlob::ReadToFile : name Perf_Test/test2.bin, offset : 0, count 296747008
Oct 27 10:17:29 ubuntu-laptop blobfuse2[17077]: LOG_DEBUG [block_blob.go (696)]: BlockBlob::ReadToFile : Download complete of blob Perf_Test/test2.bin
```

As per this part, its taking more time in downloading the files and not listing. For some reason your GUI is trying to open the files and that is causing the delay as things will be stuck till download completes. I see in the logs test1.bin, test2.bin and test3.bin being opened and resulting into their download. You need to check why GUI is trying to open these files.

**Comment by vibhansa-msft** [comment]
From logs, I do not see anything wrong from blobfuse side here. Will close this item as you might need to check why the GUI is trying to open the files. Once that is fixed and you see some issue on blobfuse end feel free to reopen this.

**Comment by pk-rescale** [comment]
This is an old issue, but I wanted to mention that I see the same behavior as @chrisposito and it is definitely limiting our ability to put blobfuse2 into more comprehensive production use (though blobfuse2 is still very useful for certain tasks).  I don't think this is user error per se so much as a current limitation of the technology blobfuse2 is using.

If it is possible to speed up the retrieval time, which seems doable in principal (perhaps by making fewer API calls since I suspect the long time is due to the sum of repeated calls being made to an API endpoint to get the list) this would make blobfuse2 significantly better / more useful.

**Comment by vibhansa-msft** [comment]
For the listing calls there are two reasons. If user or kernel sends a call to list a directory then those calls will be made. In one call backend can return only 5K elements so if there are high number of blobs in storage account you will see a lot of listBlob API calls hitting storage.'
Another use of blob listing call is to retrieve the blob properties. Here we have two options GetProperties and ListBlob api to get the blob properties. Due to some historic issues we rely more on listblob api then GetProperties (this is configurable though). Any time kernel asks for a properties of a file (which natually happens from kernel end quite often) we will have to get a latest properteis of that file from container. For every such call there will be a listBlob api call.

You can significantly reduce these numbers when you have attr_cache component plugged in your pipeline, so that blobfuse can cache the properties. Also, put a high value in attribute_timeout variable so that kernel can also cache the properties and does not send respective call every now and then.

**Comment by pk-rescale** [comment]
Thanks very much for the explanation @vibhansa-msft.  It sounds like maybe there is optimization potential here.  For reference I am using the file-cache method and the following attributes:

file_cache:
  path: XXXXXXXXXXXX
  timeout-sec: 0
  max-size-mb: 4096

attr_cache:
  timeout-sec: 360
  no-cache-on-list: false
  no-symlinks: false

**Comment by vibhansa-msft** [comment]
Can you set below cli parameters as well and see if that helps in reducing the storage calls:
```
--attr-timeout=<TIMEOUT IN SECONDS>: Time the kernel can cache inode attributes.
--entry-timeout=<TIMEOUT IN SECONDS>: Time the kernel can cache directory listing.
--negative-timeout=<TIMEOUT IN SECONDS>: Time the kernel can cache non-existance of file or directory.
```
