### ISSUE TITLE
Azure Blobfuse mount on AKS is not using fusermount 3

### ISSUE THREAD

**Issue by Sravani-K** [Azure/azure-storage-fuse#1289]
### Which version of blobfuse was used?
Blobfuse2, using blob-csi-driver release 1.22.3

### Which OS distribution and version are you using?
Ubuntu 22.04 

### If relevant, please share your mount command.
on AKS 1.26.6, 

Storage class:
Name:            azureblob-fuse-premium
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"k8s-storageclasses"},"name":"azureblob-fuse-premium"},"mountOptions":["-o allow_other","--file-cache-timeout-in-seconds=120","--use-attr-cache=true","--cancel-list-on-mount-seconds=10","-o attr_timeout=120","-o entry_timeout=120","-o negative_timeout=120","--log-level=LOG_WARNING","--cache-size-mb=1000"],"parameters":{"skuName":"Standard_GRS"},"provisioner":"blob.csi.azure.com","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}

Provisioner:           blob.csi.azure.com
Parameters:            skuName=Standard_GRS
AllowVolumeExpansion:  True
MountOptions:
  -o allow_other
  --file-cache-timeout-in-seconds=120
  --use-attr-cache=true
  --cancel-list-on-mount-seconds=10
  -o attr_timeout=120
  -o entry_timeout=120
  -o negative_timeout=120
  --log-level=LOG_WARNING
  --cache-size-mb=1000
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate

PV:
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xxxx-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse2-premium
  mountOptions:
    - '-o allow_other'
    # - '--tmp-path=/home/ubuntu/'
    # - '--enable-monitoring=true'
    - '--use-adls=true'
    # - '--file-cache-timeout-in-seconds=120'
    # - '--use-attr-cache=true'
    # - '-o attr_timeout=120'
    # - '-o entry_timeout=120'
    # - '-o negative_timeout=120'
    # - '--log-level=LOG_DEBUG'
    # - '--cache-size-mb=1000'
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: xxxxx-volumeID  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: rg-xxxx-westus2  # optional, only set this when storage account is not in the same resource group as node
      storageAccount: xxxxstorageaccount
      containerName: xxxx-blob
      protocol: fuse2
    nodeStageSecretRef:
      name: xxxxxsecret
      namespace: xxxxxnamespace

### What was the issue encountered?

Using the blob csi driver 1.22.3 , using protocol:fuse2 in PV definition, we expected fusermount 3.X, but, fusermount is still pointing to 2.9.9 in the pod. 

```
PS C:\Users\sravani> kubectl exec -it pod/csi-blob-node-pdjhh -c blob -- /bin/sh
# fusermount --version
fusermount version: 2.9.9
# fusermount3 --version
/bin/sh: 3: fusermount3: not found
```

**Comment by vibhansa-msft** [comment]
@andyzhangx there is some config to enable fuse3 on AKS if I remember correctly. Can you guide the user here.

**Comment by andyzhangx** [comment]
if you are using AKS managed blob csi driver, it's already using blobfuse-proxy, which does the blobfuse2 mount on the node, the  fusermount3 version you are checking is inside the blob csi driver container which is not used by this  managed blob csi driver on AKS. below are the fusermount3 on the node, that's the version used by AKS managed blob csi driver:

```console
root@aks-test-38956848-vmss000000:/# fusermount3 --version
fusermount3 version: 3.10.5
root@aks-test-38956848-vmss000000:/# fusermount --version
fusermount3 version: 3.10.5
```

**Comment by vibhansa-msft** [comment]
Closing this as from AKS or blobfuse side there is no issue here. Feel free to reopen or post on this if you feel otherwise.

**Comment by Sravani-K** [comment]
@andyzhangx @vibhansa-msft  thanks for the response.  We are using https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/charts helm chart to deploy csi driver. We have enabled node.enableBlobfuseProxy=true. On the node, we are getting the following.
```
root@aks-user-42893576-vmss00006G:/# fusermount --version
bash: fusermount: command not found
root@aks-user-42893576-vmss00006G:/# fusermount --version
bash: fusermount: command not found
root@aks-user-42893576-vmss00006G:/#
```
May be we are missing something here.  How do we make sure that the blobfuse mount on the Pod is using libfuse3.

**Comment by andyzhangx** [comment]
@Sravani-K
what is your aks node kernel version? The latest kernel (`5.15.0-1051-azure`) has fusermount3 installed by default.

```
root@aks-test-38956848-vmss000000:/# blobfuse2 version
blobfuse2 version: 2.1.0
root@aks-test-38956848-vmss000000:/# fusermount --version
fusermount3 version: 3.10.5
root@aks-test-38956848-vmss000000:/# fusermount3 --version
fusermount3 version: 3.10.5
root@aks-test-38956848-vmss000000:/# uname -a
Linux aks-test-38956848-vmss000000 5.15.0-1051-azure #59-Ubuntu SMP Wed Oct 11 18:49:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Sravani-K** [comment]
@andyzhangx 

Our aks node kernel version is 5.15.0-1041-azure. Can you please confirm if fusermount3 is not available on this kernel. 

We are referring to this release note  https://github.com/Azure/AKS/blob/2023-09-10/vhd-notes/aks-ubuntu/AKSUbuntu-2204/202309.06.0.txt and libfuse3, fuse3 seem to be available. Are we missing any config. 

Additional details. 
Ubuntu Version : Ubuntu 22.04.3 LTS   
Kernel Version : 5.15.0-1041-azure   
Containerd Version : containerd://1.7.5-1
Kubernetes Version: 1.26.6
NodeImageVersion : AKSUbuntu-2204gen2containerd-202309.06.0

**Comment by Sravani-K** [comment]
We created another cluster with latest node image version, but still cannot check fusermount --version. 

PS C:\Users\xxx> kubectl debug node/aks-user-11111-vmss000002 -it --image=mcr.microsoft.com/dotnet/runtime-deps:6.0
Creating debugging pod node-debugger-aks-user-34282362-11111-tlvjb with container debugger on node aks-user-11111-vmss000002.
If you don't see a command prompt, try pressing enter.
root@aks-user-34282362-vmss000002:/# uname -a
Linux aks-user-34282362-vmss000002 5.15.0-1051-azure #59-Ubuntu SMP Wed Oct 11 18:49:16 UTC 2023 x86_64 GNU/Linux
root@aks-user-34282362-vmss000002:/# blobfuse2 version
bash: blobfuse2: command not found
root@aks-user-34282362-vmss000002:/# fusermount --version
bash: fusermount: command not found
root@aks-user-34282362-vmss000002:/# fusermount3 --version
bash: fusermount3: command not found
root@aks-user-34282362-vmss000002:/#

**Comment by andyzhangx** [comment]
can you use following command to ssh to the node:
```
sudo wget https://raw.githubusercontent.com/andyzhangx/demo/master/dev/kubectl-enter
sudo chmod a+x ./kubectl-enter
./kubectl-enter <node-name>
```
