### ISSUE TITLE
Couldn't read whole append blob file when using vector agent or cat command in the blobfuse mount

### ISSUE THREAD

**Issue by Sandhiya15061997** [Azure/azure-storage-fuse#1290]
### Which version of blobfuse was used?
Blobfuse 2.1.1

### Which OS distribution and version are you using?
Ubuntu 22.04

### If relevant, please share your mount command.
blobfuse2 mount /mnt/blobfuse_mnt --config-file=/usr/share/blobfuse2/config.yaml --read-only --foreground=true

blobfuse2 mount /mnt/blobfuse_mnt --config-file=/usr/share/blobfuse2/config.yaml --ignore-open-flags --foreground=true

### What was the issue encountered?
While trying to read the log file (append blob type) from immutable policy (time based retention) storage account using vector agent or trying to do cat command at the blobfuse mount path, the log file doesn't get appended or updated with the latest log data. The understanding here is, once file is opened it is not getting updated/appended.

### Have you found a mitigation/solution?
No

### Please share logs if available.
NA

**Comment by vibhansa-msft** [comment]
Blobfuse does not support AppendBlobs as of now.

**Comment by vibhansa-msft** [comment]
When you are trying to read the file, are you updating the file in parallel through other means on container? Did not get what kind of update is expected is file is being read.
If you are updating the file (assuming logs are getting updated through other place) and you expect the file in mount path to reflect the latest content you need to use "-o direct_io" option in mount and set file-cache-timeout to 0. Also, remove attr-cache from your pipeline and set all libfuse related timeouts to 0. This will disable all sort of caching from blobfuse and kernel side and you will start getting the updated contents. Writing to this file will not work for the above reason that we do not support appendBlob natively, read might still work.

**Comment by Sandhiya15061997** [comment]
> When you are trying to read the file, are you updating the file in parallel through other means on container? Did not get what kind of update is expected is file is being read. If you are updating the file (assuming logs are getting updated through other place) and you expect the file in mount path to reflect the latest content you need to use "-o direct_io" option in mount and set file-cache-timeout to 0. Also, remove attr-cache from your pipeline and set all libfuse related timeouts to 0. This will disable all sort of caching from blobfuse and kernel side and you will start getting the updated contents. Writing to this file will not work for the above reason that we do not support appendBlob natively, read might still work.

It is appending in the container.
Thanks, with direct_io and timeouts to 0 I'm able to see the expected result while doing cat command. I am yet to check with vector agent.

**Comment by vibhansa-msft** [comment]
Reading shall work fine with the above-mentioned options. If you are trying to write to appendBlobs using blobfuse2 then that's an unsupported scenario.

**Comment by vibhansa-msft** [comment]
Kindly close this bug report if "direct_io" helped you achieve the instant sync of files while reading.

**Comment by Sandhiya15061997** [comment]
direct_io helped to sync files while reading(using cat). However it is not the same case with vector agent. When vector agent tried to read the file, the append stops.

Thank you.

**Comment by vibhansa-msft** [comment]
Officially we do not support append_blob writing so that not working is expected here.
How is this vector agent different or how its opening / syncing the files. If an application keeps the handle open for a given file, it will never be synced from container. All handles to a file must be closed from application side for all this refresh flow to work.
