### ISSUE TITLE
support on RHEL 7.9

### ISSUE THREAD

**Issue by leoliudan** [Azure/azure-storage-fuse#1318]
### Which version of blobfuse was used?
latest

### Which OS distribution and version are you using?
RHEL 7.5 or RHEL 7.8

### What was the issue encountered?
ELS for RHEL 7 is now available for 4 years, starting on July 1, 2024. Organizations must be on RHEL 7.9 to take advantage of this. 
https://www.redhat.com/en/blog/announcing-4-years-extended-life-cycle-support-els-red-hat-enterprise-linux-7

could we build up packages on RHEL7.9?

**Comment by vibhansa-msft** [comment]
We already build and release for 7.5 and it shall be compatible with 7.9 as well. There is an operation overhead for us to build and release for every single version as we need infra to build and test on those versions. If 7.5 binary is not working for 7.9 do let me know.

**Comment by leoliudan** [comment]
I verified that the package release for 7.8 could be installed in the RHEL 7.9 as well.
