### ISSUE TITLE
oracle rman duplicate database backup location fails

### ISSUE THREAD

**Issue by rwangwmata** [Azure/azure-storage-fuse#1323]
### Which version of blobfuse was used?
[oracle@azmxdbdv01-2 ~]$ blobfuse2 version
blobfuse2 version: 2.2.0

### Which OS distribution and version are you using?
[oracle@azmxdbdv01-2 ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.9 (Ootpa)

### If relevant, please share your mount command.
blobfuse2 mount /orabackup --config-file=/etc/blobfuseConfig.yaml

### What was the issue encountered?
oracle rman duplicate target database backup location failed

### Have you found a mitigation/solution?
no

### Please share logs if available.

[dup.log](https://github.com/Azure/azure-storage-fuse/files/14040538/dup.log)

**Comment by rwangwmata** [comment]
I have 2 storage accounts. One is standard blob storagev2, one is a premium blob.
test 1, 
1 i used nfs to mount premiumblob. 
2. i created a dummy database.  created a full set of backups using rman.  
3.  i trashed the database, (removed the datafile, redo logs, etc)
4. run the rman script in the log.  i was able to get the database up and running.
5. i tar zipped the backup file to a local file system.

test 2.
1. unmount the nfs mount.
2. mount the blobfuse storage account, 
3. trash the database ( remove datafile, redo logs, etc)
4. run the same rman script.i get this error msg:
 RMAN-05579: CONTROLFILE backup not found in /orabackup/mx76azd1

**Comment by rwangwmata** [comment]
here is the fuse config:

allow-other: true

logging:
  type: base
  file-path: /var/log/blobfuse2.log
  #type: syslog
  level: log_debug
  max-file-size-mb: 50
  file-count: 50

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  default-permission: 0777
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /staging/blobfusetmp
  timeout-sec: 30
  allow-non-empty-temp: true
  cleanup-on-start: true
  create-empty-file: true

attr_cache:
  timeout-sec: 3600

health_monitor:
  enable-monitoring: true
  stats-poll-interval-sec: 10
  process-monitor-interval-sec: 30
  output-path: /var/log

azstorage:
  type: adls
  account-name: xxx
  account-key: xxx
  endpoint: https://xxx.blob.core.windows.net
  mode: key
  container: xxx

**Comment by vibhansa-msft** [comment]
NFS and REST end-points are not cross compatible as of now. If you have enabled NFS on your account then avoid using tools which work on REST like Blobfuse, AzCopy or Storage explorer.

**Comment by rwangwmata** [comment]
I think you misunderstood.  My scenario is that I have 2 separate storage accounts.  One has NFS enabled, One is standard blob with blobfuse.  I used the same set of oracle backup sets to test the oracle db cloning operation.  NFS works fine.  but the one with blobfuse fails.

**Comment by vibhansa-msft** [comment]
Is your account HNS enabled (the one you are using with blobfuse)?

**Comment by rwangwmata** [comment]
yes, it is HNS enabled.  The weird thing is that the standard restore/recover operation works on the same host where backup is taken.  let's say, i have db1 on host1, i take a rman backup of db1 on host1.  then, i trash db1, i can use the rman backup to restore/recover db.  howerver, if i take the same backup to host2, and wants to clone the db to another db (db2), that does not work. it is the rman's duplicate database backup location operation.  it is having issue with.

**Comment by ashruti-msft** [comment]
Please make this change in your config :
Remove the endpoint written in azstorage and try again. 
This is because your account is of type adls and you have mentioned a blob endpoint. You don't need to mention an endpoint we can get that using your account details given.

**Comment by rwangwmata** [comment]
i made the change, same result.  here is the content:

# Refer ./setup/baseConfig.yaml for full set of config parameters

allow-other: true

logging:
  type: base
  file-path: /var/log/blobfuse2.log
  #type: syslog
  level: log_debug
  max-file-size-mb: 50
  file-count: 50

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  default-permission: 0777
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /staging/blobfusetmp
  timeout-sec: 30
  allow-non-empty-temp: true
  cleanup-on-start: true
  create-empty-file: true

attr_cache:
  timeout-sec: 3600

health_monitor:
  enable-monitoring: true
  stats-poll-interval-sec: 10
  process-monitor-interval-sec: 30
  output-path: /var/log

azstorage:
  type: adls
  account-name: xxx
  account-key: xxx
  mode: key
  container: azmxdbdv0x-2

**Comment by rwangwmata** [comment]
same backup.  if i switch to nfs mount, everything works.

however, we want Geo-redundancy, so, we cannot use nfs.  the only option is blobfuse.

**Comment by rwangwmata** [comment]
forgot to say, same problem with the new config file with endpoint removed.

**Comment by ashruti-msft** [comment]
Blobfuse and azcopy are the only tools for copying data between storage accounts. Please share the logs that blobfuse generated when the operation failed.

**Comment by rwangwmata** [comment]
[blobfuse2.log-20240131.log](https://github.com/Azure/azure-storage-fuse/files/14142661/blobfuse2.log-20240131.log)

**Comment by rwangwmata** [comment]
[oracle@azmxdbdv01-2 ~]$ rman @dup_path.scr | tee dup_path.log

Recovery Manager: Release 19.0.0.0.0 - Production on Fri Feb 2 11:16:04 2024
Version 19.20.0.0.0

Copyright (c) 1982, 2019, Oracle and/or its affiliates.  All rights reserved.

RMAN> connect auxiliary *
2> run {
3> allocate auxiliary channel t1 type disk;
4> allocate auxiliary channel t2 type disk;
5> allocate auxiliary channel t3 type disk;
6> duplicate target database to mx76azd1 backup location '/orabackup/mx76azd1';
7> }
8>
connected to auxiliary database: MX76AZD1 (not mounted)

allocated channel: t1
channel t1: SID=1105 device type=DISK

allocated channel: t2
channel t2: SID=1153 device type=DISK

allocated channel: t3
channel t3: SID=1177 device type=DISK

Starting Duplicate Db at 02-02-2024 11:16:05
released channel: t1
released channel: t2
released channel: t3
RMAN-00571: ===========================================================
RMAN-00569: =============== ERROR MESSAGE STACK FOLLOWS ===============
RMAN-00571: ===========================================================
RMAN-03002: failure of Duplicate Db command at 02/02/2024 11:16:05
RMAN-05501: aborting duplication of target database
RMAN-05579: CONTROLFILE backup not found in /orabackup/mx76azd1

Recovery Manager complete.
[oracle@azmxdbdv01-2 ~]$

**Comment by rwangwmata** [comment]
[oracle@azmxdbdv01-2 ~]$ cd /orabackup/mx76azd1
[oracle@azmxdbdv01-2 mx76azd1]$ ls -alrt
total 0
drwxr-x---. 2 root root 4096 Jan 24 09:57 2024-01-23
drwxr-x---. 2 root root 4096 Jan 25 10:41 2024-01-25
[oracle@azmxdbdv01-2 mx76azd1]$ ls -alrt 2024-01-23
total 0
-rw-------. 1 root root  10715136 Jan 24 09:57 MX76AZD-ctl-c-2978403184-20240123-01
-rw-------. 1 root root  10715136 Jan 24 09:57 MX76AZD-ctl-c-2978403184-20240123-00
-rw-------. 1 root root      5632 Jan 24 09:57 MX76AZD-arc-1-5-15-1159047447.bkp
-rw-------. 1 root root  10715136 Jan 24 09:57 MX76AZD-ctl-c-2978403184-20240123-02
-rw-------. 1 root root 462632960 Jan 24 09:57 MX76AZD-db-20240123-1159047229-012hba1t_1_1_1.bkp
-rw-------. 1 root root 210550784 Jan 24 09:57 MX76AZD-db-20240123-1159047275-022hba3b_2_1_1.bkp
-rw-------. 1 root root  53133312 Jan 24 09:57 MX76AZD-db-20240123-1159047275-032hba3b_3_1_1.bkp
-rw-------. 1 root root     25600 Jan 24 09:58 MX76AZD-db-20240123-1159047395-082hba73_8_1_1.bkp
-rw-------. 1 root root     16896 Jan 24 09:58 MX76AZD-db-20240123-1159047301-062hba45_6_1_1.bkp
-rw-------. 1 root root   1155072 Jan 24 09:58 MX76AZD-db-20240123-1159047275-052hba3b_5_1_1.bkp
-rw-------. 1 root root 102367232 Jan 24 09:58 MX76AZD-db-20240123-1159047275-042hba3b_4_1_1.bkp
-rw-------. 1 root root      6144 Jan 24 09:58 MX76AZD-db-20240123-1159047399-0d2hba77_13_1_1.bkp
-rw-------. 1 root root    106496 Jan 24 09:58 MX76AZD-db-20240123-1159047397-0c2hba75_12_1_1.bkp
-rw-------. 1 root root     90112 Jan 24 09:58 MX76AZD-db-20240123-1159047397-0b2hba75_11_1_1.bkp
-rw-------. 1 root root     57344 Jan 24 09:58 MX76AZD-db-20240123-1159047397-0a2hba75_10_1_1.bkp
-rw-------. 1 root root    163840 Jan 24 09:58 MX76AZD-db-20240123-1159047397-092hba75_9_1_1.bkp
[oracle@azmxdbdv01-2 mx76azd1]$ ls -alrt 2024-01-25
total 0
[oracle@azmxdbdv01-2 mx76azd1]$

**Comment by rwangwmata** [comment]
the files with the name, MX76AZD-ctl- are controlfile backups.  it is there.

**Comment by rwangwmata** [comment]
in the log file, start from here:
Fri Feb  2 11:16:05 EST 2024 : blobfuse2[1271387] : LOG_TRACE [libfuse_handler.go (457)]: Libfuse::libfuse_opendir : 

Feb  2 11:16:05 EST is when i issued the duplicate command.

**Comment by vibhansa-msft** [comment]
I do not see any error in the log file as such which can point us in direction of any possible return error to user application. can you share exactly what you see on console or any details of the error that you get. My guess here is RMAN is not dumping the exact error thrown by blobfuse to it and printing its own error message.

**Comment by vibhansa-msft** [comment]
timestamp when you say you have fired the listing command, as per logs it was able to retreive 4 objects from backend for this.
```
Fri Feb  2 11:16:05 EST 2024 : blobfuse2[1271387] : LOG_DEBUG [azstorage.go (305)]: AzStorage::StreamDir : Retrieved 4 objects with  marker for Path 
```

Do you expect only 4 objects on the root of the container or there were more files expected here?

**Comment by rwangwmata** [comment]
at the root of container, here is what is in there.
[oracle@azmxdbdv01-2 orabackup]$ ls -alrt
total 0
drwxr-x---. 2 root root 4096 Jan 19 14:44 mx76aza2
drwxr-x---. 2 root root 4096 Jan 19 15:32 mx76azb1
drwxr-x---. 2 root root 4096 Jan 23 13:51 mx76azd1_old
drwxr-x---. 2 root root 4096 Jan 24 09:57 mx76azd1

it has those 4 folders.  maybe it is the 4 object it found.  but dup command is duplicate target database to mx76azd1 backup location '/orabackup/mx76azd1';

**Comment by vibhansa-msft** [comment]
Sorry did not get that. If root has 4 folders expected and list command is showing those 4 then what is the issue here. I am not aware on how RMAN dup command works, but if it tries to copy the directory to a new location that shall work just fine.

**Comment by vibhansa-msft** [comment]
I was going through the thread again just to see in case I have missed something.
"we want the oracle rman backups replicated to a 2nd region automatically. " : If this is prime objective then blob's internal geo-replication is good enough why you want to backup and duplicate using RMAN. I mean if you have GRS account then anyway blobs will be backed up in another geo.

**Comment by rwangwmata** [comment]
Here is the issue:

we want to use Geo Redundancy, that means we have to use standard blob, and that means we have to use fuse to mount.  Now, we have oracle backups on blob.

Then, we use fuse to mount this storage account on a different host, and use the oracle backups on the storage account to create another database(rman duplicte).  this is where it is failing.

the storage account has backups from 4 different databases.  each db has a folder.

when you issue this command, it is supposed to traverse the tree down to /orabackup/mx76azd1, and find the controlfile backup.
"duplicate target database to mx76azd1 backup location '/orabackup/mx76azd1';"

it seems fuse stops at the top level at /orabackup.

==========
i have another storage account with the same backups from 4 databases, but i used NFS to mount it.  I used the same duplicate command, and it works.  However if I use nfs,  i don't have Geo Redundancy.

**Comment by vibhansa-msft** [comment]
Thansk for sharing the workflow here. As we were discussing earlier the directory listing was yeilding 4 objects, is that correct or there were more files which should have been listed. If the list is coming out correctly then I do not see any reason for it to fail to navigate through that given directory. Is it a case where you mount the storage account first and then create the backup from another system in parallle and come back here and restore or duplicate? Just thinking if its a sync related issue where same  account is being operated from two different places in parallel or something.

**Comment by rwangwmata** [comment]
the problem is that in the command, i specified /orabackup/mx76azd1.  fuse stopped at the top level.  it is supposed to traverse the path down to  /orabackup/mx76azd1. not stopping at the top.

**Comment by vibhansa-msft** [comment]
Can you manually try listing with "ls -lR" and see if it goes down to the bottom layer or not. If so, then it might the RMAN backup which is either ignoring something we send back or expect something that we are not sending.

**Comment by rwangwmata** [comment]
yes, if I do ls -lR, it goes down to the bottom layer.  I agree there is some hiccup between this rman duplicate and blob fuse.  so, this rman duplicate works with nfs or cifs, my guess is that it is expecting something that blob fuse is not sending.

We have decided to use Azure File as the solution to store oracle backups.  

In this link, https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/oracle/oracle-database-backup-strategies ,
it does say, to use smb or nfs for backup medium.  so, I guess we will stick with the recommendation.

Blobfuse is ubiquitous across Azure regions and works with all storage account types, including general-purpose v1/v2 and Azure Data Lake Storage Gen2. But it doesn't perform as well as alternative protocols. For suitability as the database backup medium, we recommend using the SMB or [NFS](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux) protocol to mount Azure Blob Storage.
