### ISSUE TITLE
linux du does not show size 

### ISSUE THREAD

**Issue by rwangwmata** [Azure/azure-storage-fuse#1324]
### Which version of blobfuse was used?
[root@azmxdbdv01-2 orabackup]# blobfuse2 version
blobfuse2 version: 2.2.0

### Which OS distribution and version are you using?
[root@azmxdbdv01-2 orabackup]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.9 (Ootpa)

### If relevant, please share your mount command.
blobfuse2 mount /orabackup --config-file=/etc/blobfuseConfig.yaml

### What was the issue encountered?
why doesn't du show any info?

[root@azmxdbdv01-2 orabackup]# du -hs *
0       mx76aza2
0       mx76azb1
0       mx76azd1
0       mx76azd1_old

### Have you found a mitigation/solution?
no.

**Comment by vibhansa-msft** [comment]
If you are expecting `du` to show your Azure Storage usage then that's something not supported. Couting total usage on the storage is a costly operation (both in terms of execution and $ value). If you have file-cache configured then "du" will show the usage of your temp cache (local cache) directory's mount point. What is your expectation here?

**Comment by rwangwmata** [comment]
ok. i understand the rational.
