### ISSUE TITLE
Access token is not refreshed when using MSI

### ISSUE THREAD

**Issue by leonardotbo** [Azure/azure-storage-fuse#1326]
### Which version of blobfuse was used?
blobfuse2-2.2.0 (also built directly from `main`)

### Which OS distribution and version are you using?
20.04.1-Ubuntu

### If relevant, please share your mount command.
`MSI_ENDPOINT=127.0.0.1: blobfuse2 mount --config-file=config.yaml mnt_folder`

The `MSI_ENDPOINT` is being set to `127.0.0.1:` to trigger the use of function [`fetchTokenFromCLI`](https://github.com/Azure/azure-storage-fuse/blob/main/component/azstorage/azauthmsi.go#L95), as explained on https://github.com/Azure/azure-storage-fuse/discussions/1322

### What was the issue encountered?
The mount works as expected, but the access token is not refreshed, leading to error on the mount. Trying to `ls` in the mounted folder leads to `ls: reading directory '.': Input/output error`.

Looking at the `blobfuse2.log` file I see the following:

```
Thu Jan 25 <redacted> UTC 2024 : blobfuse2[53519] : LOG_ERR [libfuse_handler.go (516)]: Libfuse::libfuse_readdir : Path , handle: 4, offset 0. Error in retrieval -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/cloudtest/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=InvalidAuthenticationInfo) =====
Description=Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId: <redacted>
Time:2024-01-25<redacted>, Details: 
   AuthenticationErrorDetail: Lifetime validation failed. The token is expired.
   Code: InvalidAuthenticationInfo
```

### Have you found a mitigation/solution?

My main hypothesis was that something was wrong in function [`getNextExpiryTimer`](https://github.com/Azure/azure-storage-fuse/blob/main/component/azstorage/azauthmsi.go#L64), so I put some log.Info there to try to find where the problem was coming from.

From all the values, that one that caught my attention was: `LOG_INFO [azauthmsi.go (65)]: azAuthBfsMSI::getNextExpiryTimer : Token.Expires() = 1969-12-31 23:00:00 +0000 UTC`. That meant that Token.Expires() was being setup improperly.

Looking at [`fetchTokenFromCLI`](https://github.com/Azure/azure-storage-fuse/blob/main/component/azstorage/azauthmsi.go#L95), I could see the following code block (from lines 143 to 157):

```golang
        // the Azure CLI's "expiresOn" is local time
	_, err = time.ParseInLocation("2006-01-02 15:04:05.999999", t.ExpiresOn, time.Local)
	if err != nil {
		return nil, fmt.Errorf("error parsing token expiration time %q: %v", t.ExpiresOn, err)
	}

	tokenInfo := &common.OAuthTokenInfo{
		Token: adal.Token{
			AccessToken:  t.AccessToken,
			RefreshToken: t.RefreshToken,
			ExpiresOn:    json.Number(t.ExpiresOn),
			Resource:     t.Resource,
			Type:         t.TokenType,
		},
	}
```

That lead me to believe that `ExpiresOn` was not being properly setup.
One way that I could get to make it work was by changing the previous code to:

```golang
        // I also added "strconv" to the "import" block on top of the file

        // the Azure CLI's "expiresOn" is local time
        expiresOn, err := time.ParseInLocation("2006-01-02 15:04:05.999999", t.ExpiresOn, time.Local)
        if err != nil {
                return nil, fmt.Errorf("error parsing token expiration time %q: %v", t.ExpiresOn, err)
        }

        tokenInfo := &common.OAuthTokenInfo{
                Token: adal.Token{
                        AccessToken:  t.AccessToken,
                        RefreshToken: t.RefreshToken,
                        ExpiresOn:    json.Number(strconv.FormatInt(expiresOn.Unix(), 10)),
                        Resource:     t.Resource,
                        Type:         t.TokenType,
                },
        }
```

Building the code with theses changes lead to the correct value of `LOG_INFO [azauthmsi.go (65)]: azAuthBfsMSI::getNextExpiryTimer : Token.Expires() = 2024-01-25 08:12:37 +0000 UTC`, which then lead to the correct refreshing of access token after it was expired.

This is my first experience with golang, so my code is most likely not the most optimised, but I think it gets the point across :)

**Comment by vibhansa-msft** [comment]
This sounds correct. You can go ahead and fire a PR with this changeset as you already have the change ready in your local build. The first suggestion "json.Number(strconv.FormatInt(expiresOn.Unix(), 10))" looks good to me.
"expires_on" is not a feild that we can rely on as it may not come sometimes in token.

**Comment by leonardotbo** [comment]
Great! Just created PR https://github.com/Azure/azure-storage-fuse/pull/1327 with the fix
