### ISSUE TITLE
Improve error message/handling when cache is not readable/writeable by process

### ISSUE THREAD

**Issue by DevopsMercenary** [Azure/azure-storage-fuse#1329]
Feature Suggestion:  I ran in to this issue where  all shares using blobfuse stopped working.  The error message made it appear the issue was a file permissions issue on the share.  Turns out that the folder I was using had its directory permissions re-set by the OS when the new ephemeral disk was refreshed. With the file directory permissions re-set for the cache, blob fuse couldn't write to it anymore and stopped working.  Unfortunately it took me a while to thing the issue was with blobfuse and looking in the logs I finally found the issue.

It would  be nice if some sort of error / issue behind the scenes would present a useful and explicit error to the user.

### Which version of blobfuse was used?

blobfuse2 version 2.2.0

### Which OS distribution and version are you using?

Ubuntu 22.04.3 LTS (GNU/Linux 6.2.0-1015-azure x86_64)

### What was the issue encountered?

Received 'Permission Denied' on files and folders when using a previously mounted blobstore.

```
tar -ztvf blobstore/analytics-analysis.tar
tar (child): blobstore/analytics-analysis.tar: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

### Have you found a mitigation/solution?

Looking at the logs finally I see that my cache folder is not writeable.  Updating the cache folder `chmod 777 /mnt` works but I would have spent less time with the issue had BlobFuse flat out told me that the cache was un-readable.

### Please share logs if available.

```
Jan 26 08:21:59 data-delivery-host blobfuse2[6678]: LOG_DEBUG [lru_policy.go (206)]: lruPolicy::IsCached : /mnt/analytics-analysis.tar, deleted:false
Jan 26 08:21:59 data-delivery-host blobfuse2[6678]: LOG_DEBUG [file_cache.go (779)]: FileCache::isDownloadRequired : /mnt/analytics-analysis.tar not present in local cache
Jan 26 08:21:59 data-delivery-host blobfuse2[6678]: LOG_TRACE [attr_cache.go (467)]: AttrCache::GetAttr : analytics-analysis.tar
Jan 26 08:21:59 data-delivery-host blobfuse2[6678]: LOG_DEBUG [attr_cache.go (486)]: AttrCache::GetAttr : analytics-analysis.tar served from cache
Jan 26 08:21:59 data-delivery-host blobfuse2[6678]: LOG_DEBUG [file_cache.go (846)]: FileCache::OpenFile : Need to re-download analytics-analysis.tar
Jan 26 08:21:59 data-delivery-host blobfuse2[6678]: LOG_ERR [file_cache.go (872)]: FileCache::OpenFile : error creating new file analytics-analysis.tar [open /mnt/analytics-analysis.tar: permission denied]
```

**Comment by vibhansa-msft** [comment]
Closing this as there is no action item on blobfuse as of now. Feel free to reopen if you think otherwise or have any suggestions in this regard.
