### ISSUE TITLE
Change AZURE_STORAGE_BLOB_ENDPOINT to point to AzureGovCloud

### ISSUE THREAD

**Issue by Yetienne-MSFT** [Azure/azure-storage-fuse#1330]
### Which version of blobfuse was used?
V1

### Which OS distribution and version are you using?

Ubuntu 20.04
### If relevant, please share your mount command.

sudo blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
### What was the issue encountered?
Attempting to mount in AzGovernment to reproduce a customer issue. 

Unsure where the environment name variable is being set or how to change it to usgovcloudapi.net 

See printenv output below

AzUser@UbuntuTest:~$ ls -l
ls: cannot access 'mycontainer': Permission denied
total 8
-rw------- 1 AzUser AzUser  172 Jan 27 01:34 fuse_connection.cfg
d????????? ? ?      ?         ?            ? mycontainer
-rw-r--r-- 1 root   root   3690 Oct 25  2022 packages-microsoft-prod.deb
AzUser@UbuntuTest:~$ Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Unmounting blobfuse.

### Have you found a mitigation/solution?
No

### Please share logs if available.

AzUser@UbuntuTest:/mnt/resource$ printenv
SHELL=/bin/bash
PWD=/mnt/resource
LOGNAME=AzUser
XDG_SESSION_TYPE=tty
MOTD_SHOWN=pam
HOME=/home/AzUser
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*
.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;
31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.j
peg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*
.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl
=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;
36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=10.10.1.4 34810 10.10.0.4 22
SGX_AESM_ADDR=1
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=linux
LESSOPEN=| /usr/bin/lesspipe %s
USER=AzUser
SHLVL=1
XDG_SESSION_ID=4
XDG_RUNTIME_DIR=/run/user/1000
SSH_CLIENT=10.10.1.4 34810 22
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
SSH_TTY=/dev/pts/0
_=/usr/bin/printenv
OLDPWD=/mnt

**Comment by ashruti-msft** [comment]
Hello, can you please enable logging in your config file using `logLevel LOG_DEBUG` and share the logs here. It will help us figure out the issue.
Thanks!

**Comment by Yetienne-MSFT** [comment]
Hi looks like even with the blob endpoint environment variable set.
It's still defaulting to Azure commercial. 

Jan 29 19:50:13 UbuntuTest blobfuse[50889]:  ==> REQUEST/RESPONSE :: GET https://blobfuse122312321312.blob.core.windows.net/mycontainer?comp=list&delimiter=/&include=metadata&maxresults=1&restype=container?&User-Agent=azure-storage-fuse/1.4.5&x
-ms-date=Mon, 29 Jan 2024 19:49:04 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 0 :: 
Jan 29 19:51:02 UbuntuTest blobfuse[50889]:  ==> REQUEST/RESPONSE :: GET https://blobfuse122312321312.blob.core.windows.net/mycontainer?comp=list&delimiter=/&include=metadata&maxresults=1&restype=container?&User-Agent=azure-storage-fuse/1.4.5&x
-ms-date=Mon, 29 Jan 2024 19:50:13 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 0 :: 
Jan 29 19:51:02 UbuntuTest blobfuse[50889]: Unable to start blobfuse. DNS server lookup failed errno=6
Jan 29 19:51:02 UbuntuTest blobfuse[50889]: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Jan 29 19:51:02 UbuntuTest blobfuse[50889]: Unmounting blobfuse.
Jan 29 20:19:59 UbuntuTest blobfuse[52030]: Using syscall to detect directory is already mounted or not
Jan 29 20:19:59 UbuntuTest blobfuse[52030]: Account name found
Jan 29 20:19:59 UbuntuTest blobfuse[52030]: Account Key found
Jan 29 20:19:59 UbuntuTest blobfuse[52030]: Container name found
Jan 29 20:19:59 UbuntuTest blobfuse[52030]: Auth type set as key
Jan 29 20:19:59 UbuntuTest blobfuse[52030]: Setting logging level to : LOG_WARNING
Jan 29 20:19:59 UbuntuTest blobfuse[52030]: ** Delaying tls init to post fork for older libcurl version
Jan 29 20:19:59 UbuntuTest blobfuse[52030]: ** Delaying authentication to post fork for older curl versions
Jan 29 20:19:59 UbuntuTest blobfuse[52032]: ** Post fork authentication for older libcurl version

Env Variable output: This occurs when I have the full endpoint or just the domain in the environment varaible
AzUser@UbuntuTest:~$ printenv
SHELL=/bin/bash
PWD=/home/AzUser
LOGNAME=AzUser
XDG_SESSION_TYPE=tty
MOTD_SHOWN=pam
HOME=/home/AzUser
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*
.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;
31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.j
peg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*
.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl
=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;
36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=10.10.1.5 60264 10.10.0.4 22
SGX_AESM_ADDR=1
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=linux
LESSOPEN=| /usr/bin/lesspipe %s
USER=AzUser
SHLVL=1
XDG_SESSION_ID=80
XDG_RUNTIME_DIR=/run/user/1000
SSH_CLIENT=10.10.1.5 60264 22
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
AZURE_STORAGE_BLOB_ENDPOINT=blobfuse122312321312.blob.core.usgovcloudapi.net
SSH_TTY=/dev/pts/0
_=/usr/bin/printenv

**Comment by ashruti-msft** [comment]
We've upgraded to Blobfuse v2, which comes with enhanced features and performance improvements. Kindly consider migrating to v2 and inform us if the issue persists.

**Comment by ashruti-msft** [comment]
Please give us an update on your issue,thanks!

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Feel free to reopen if issue persists, or post your comments here.
