### ISSUE TITLE
About the correct combination of blobfuse2 and fuse3

### ISSUE THREAD

**Issue by Tuheempbirs** [Azure/azure-storage-fuse#1333]
### Which version of blobfuse was used?
blobfuse2-2.1.2

### Which OS distribution and version are you using?
RHEL 8.6

### If relevant, please share your mount command.
blobfuse2 mount /xxxxxx --config-file=/blobfuse2.yaml --disable-version-check=true

blobfuse config file:
blobfuse2.yaml
------------------------------
azstorage:
    type: block
    account-name: xxxxxxxxxx
    container: xxxxxxxxxx
    endpoint: https://xxxxxxxxxx.blob.core.windows.net/
    mode: key
    account-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

allow-other: true
sdk-trace: true

libfuse:
    attribute-expiration-sec: 0
    entry-expiration-sec: 0
    negative-entry-expiration-sec: 0
    direct-io: true

file_cache:
    path: /Blob_Storage/RamDisk/LongTermLogs
    timeout-sec: 0
    create-empty-file: true

attr_cache:
    timeout-sec: 0
------------------------------

### What was the issue encountered?
I was using blobfuse2-2.1.0, but after updating to blobfuse2-2.1.2, I was unable to mount the storage with the following error.

> /var/log/blobfuse2.log
> Jan 31 15:45:18 ZAHSKD10-20231006 blobfuse2[2249]: LOG_CRIT [mount.go (403)]: Starting Blobfuse2 Mount : 2.1.2 on [Red Hat Enterprise Linux 8.6 (Ootpa)]
> Jan 31 15:45:18 ZAHSKD10-20231006 blobfuse2[2249]: LOG_CRIT [mount.go (404)]: Logging level set to : LOG_WARNING
> Jan 31 15:45:18 ZAHSKD10-20231006 blobfuse2[2254]: LOG_CRIT [mount.go (403)]: Starting Blobfuse2 Mount : 2.1.2 on [Red Hat Enterprise Linux 8.6 (Ootpa)]
> Jan 31 15:45:18 ZAHSKD10-20231006 blobfuse2[2254]: LOG_CRIT [mount.go (404)]: Logging level set to : LOG_WARNING
> Jan 31 15:45:18 ZAHSKD10-20231006 blobfuse2[2254]: LOG_ERR [libfuse_handler.go (183)]: Libfuse::initFuse : failed to mount fuse
> Jan 31 15:45:18 ZAHSKD10-20231006 blobfuse2[2254]: LOG_ERR [libfuse.go (166)]: Libfuse::Start : Failed to init fuse [failed to mount fuse]
> Jan 31 15:45:18 ZAHSKD10-20231006 blobfuse2[2254]: LOG_ERR [mount.go (548)]: mount: error unable to start pipeline [failed to mount fuse]

After looking at the error message and updating the version of fuse3, I was able to successfully mount the storage.
Is there a way to check the correct combination of blobfuse2 and fuse3?

Combinations I have confirmed

> blobfuse2-2.1.0-1.x86_64
> fuse3-3.3.0-15.el8.x86_64
> fuse3-libs-3.3.0-15.el8.x86_64
=> Mount Success

> blobfuse2-2.1.2-1.x86_64
> fuse3-3.3.0-15.el8.x86_64
> fuse3-libs-3.3.0-15.el8.x86_64
=> Mount Error (Failed to init fuse)

> blobfuse2-2.1.2-1.x86_64
> fuse3-3.3.0-16.el8.x86_64
> fuse3-libs-3.3.0-16.el8.x86_64
=> Mount Success

### Have you found a mitigation/solution?
After updating to blobfuse2-2.1.2, I updated fuse3 from 3.3.0-15 to 3.3.0-16.
But I don't know if this is the right combination.

**Comment by vibhansa-msft** [comment]
Latest of blobfuse and libfuse shall work fine in any combination. If you are encountering any specific problem with a specific version, then you need to enable fuse-trace through our config and share the log file. 
Also, you do not need to upgrade your fuse driver every time you upgrade blobfuse2. Just have a stable version available on your distro (latest version available for your Linux through package manager) and use blobfuse2 latest version.

**Comment by vibhansa-msft** [comment]
Closing this as there is no actionable item on this. Feel free to post any further queries here.
