### ISSUE TITLE
can't use git (probably an issue renaming a file)

### ISSUE THREAD

**Issue by scottporter** [Azure/azure-storage-fuse#1337]
### Which version of blobfuse was used?
blobfuse 2.2.2

### Which OS distribution and version are you using?
Ubuntu 20.4

### If relevant, please share your mount command.
blobfuse2 mountv1 /mnt/user-files --tmp-path=/local_disk0/blobfusecache3 -o allow_other -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/tmp/connection-homedir-config.cfg --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 --use-adls=true

### What was the issue encountered?
many git commands throw errors.  For example git init or git clone. 

The error is something like:

error: chmod on {filepath}/.git/config.lock failed: Permission denied
fatal: could not set 'core.filemode' to 'false'

I think git actually renames that config.lock, so underlying problem might be an inability to rename the file?

### Have you found a mitigation/solution?

We wanted to upgrade from blobfuse 1 to blobfuse 2 and were doing some testing.  In the meantime we have to stick with v1.

**Comment by vibhansa-msft** [comment]
Are you using a HNS enable account here?

**Comment by scottporter** [comment]
Yes we are.

**Comment by vibhansa-msft** [comment]
What kind of authentication are you using? As per the logs you have shared, you do not have authentication to change the permissions on a given file/folder/path. If you are using SPN or MSI (Identity) for authentication, kindly ensure you have "Storage Blob Data Contributor" role assigned to your identity/spn for the storage account.

**Comment by scottporter** [comment]
We are using a service principal, and that service principal generates a SAS token that gets used.  During testing our configs aren't in a very secure place... we're just saving out config files to /tmp something like this:

```
echo "accountName ${ACCOUNT_NAME}
sasToken ${HOMEDIR_SAS}
containerName user-files" > /tmp/connection-homedir-config.cfg
```

I'll double check with my tech contact that the service principal has that role assigned.

**Comment by scottporter** [comment]
And yes, we confirmed that the service principal has that role assigned.

**Comment by vibhansa-msft** [comment]
If you have a spn and you generated SAS from it then most likely you are using a user-delegation SAS model. In that case you will need to configure blobfuse to use the SAS auth mode and provide the SAS key (config file or env variables).
If you are concerned about security of the key/sas getting exposed then either you can use env variables (instead of a config file) or there is another feature where you can encrypt your config file using blobfuse2, delete the plain text file and then supply the encrypted file and passphrase to blobfuse which will decrypt the file in memory and extract the keys out of it.

**Comment by scottporter** [comment]
Isn't that what we're already doing here?  The SAS key is in an environment variable and I write it to the config file for blobfuse.

```
echo "accountName ${ACCOUNT_NAME}
sasToken ${HOMEDIR_SAS}
containerName user-files" > /tmp/connection-homedir-config.cfg
```

After we have it working, we can lock it down like you suggest.  But for now, I'm just trying to get it working.

**Comment by scottporter** [comment]
I haven't heard back from you.  By the following comment:

* _In that case you will need to configure blobfuse to use the SAS auth mode and provide the SAS key (config file or env variables)._


Did you mean something different than what we're doing?  If so, can you explain?

**Comment by vibhansa-msft** [comment]
Blobfuse2 takes a yaml config file as input and not a regular key-value pair file (which blobfuse-v1 used to take).
You can view some sample config files provided at our workspace root and then create one based on your config. If you do not wish to create a yaml config file then other way is to create some env variables. In our readme search for 'AZURE_STORAGE_AUTH_TYPE'. You will need to set this to 'sas' and then use other env variables defined in that file to point to your sas key and account name.

**Comment by ashruti-msft** [comment]
I can see you are using blobfuse2 2.2.2 version so try using this mount command instead:
blobfuse2 mount /mnt/user-files --tmp-path=/local_disk0/blobfusecache3 -o allow_other -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/tmp/connection-homedir-config.yaml --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 --use-adls=true
change `mountv1 `to `mount `and use a yaml file as your config, for example `--config-file=/tmp/connection-homedir-config.yaml` (refer the sample configs given by us : [file_cache.yaml](https://github.com/Azure/azure-storage-fuse/blob/main/sampleFileCacheConfig.yaml), [block_cache.yaml](https://github.com/Azure/azure-storage-fuse/blob/main/sampleBlockCacheConfig.yaml), [baseconfig.yaml](https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml))
Also please share your config file so we can see where can investigate further if required.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update on this. Feel free to reopen once required information is available.

**Comment by scottporter** [comment]
Sorry, I haven’t had a chance to figure out the yaml file approach yet.  As
soon as I do I will post.
