### ISSUE TITLE
chown and chmod does not work on the blobfuse2 mount

### ISSUE THREAD

**Issue by jhpark-ucla** [Azure/azure-storage-fuse#1344]
### Which version of blobfuse was used?
blobfuse2 version 2.2.0
Storage used: Azure BlockBlobStorage Premium

### Which OS distribution and version are you using?
CentOS Linux 7 

### If relevant, please share your mount command.
sudo blobfuse2 mount ./mnt/blob/ --config-file=./blobfuse/config.yaml

### What was the issue encountered?
We cannot chown or chmod on the mount (mnt/blob) even though documentations say that can be done.

### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
chmod or chown of the mount path itself is not supported. Anything under the mount path can is accessible for chmod only if you are mounting a HNS account. chown will not work in any case.

**Comment by vibhansa-msft** [comment]
Closing this as this is not supported by blobfuse2.

**Comment by jtviolet** [comment]
@vibhansa-msft are there any options for the directory to be owned by anything other than root, if chown is not supported?

**Comment by jainakanksha-msft** [comment]
@jtviolet  Avoid using sudo as it will operate with root user privileges.
Login in Linux with any other user.
And start your mount with that, it should work.

**Comment by jtviolet** [comment]
@jainakanksha-msft thanks so much for the reply! I ran it again without sudo, and it still mounted as owned by root:root.

Here's the directory before mounting:
```
drwxr-xr-x 2 outlineapp root  4096 Feb 12 13:31 filestorage/
```

Here's my command that I'm running:
```
blobfuse2 mount /opt/outline/filestorage --config-file=/opt/blobfuse/config.yaml
```

...and here is that directory after the command:
```
drwxrwxrwx 2 root   root  4096 Feb 13 18:17 filestorage/
```
