### ISSUE TITLE
Performance Issue's with Blobfuse2 on AKS Cluster

### ISSUE THREAD

**Issue by svelama** [Azure/azure-storage-fuse#1357]
I'm currently working on an application, the application creates pods with a specific programming language images on it, let's say the pod contains go image, upon `exec` into the pod, all the go development could be done inside the pod.

For persistance I'm using AZ Blob storage, with a `provisioner:blob.csi.azure.com` I can create blob containers dynamically by creating pv/pvc's and then its mounted with the pods.

Once the pods are created successfully, we can then `exec` into the pod, and I can see that a blobfuse2 volume is mounted, e.g.

```sh
> df
> blobfuse2  1024000. 14336  1009664. 2% /projects
```

Now, when I run a package manager at **/projects**, i.e. `micromamba to create a virtual environment and install java dependencies such as openjdk and maven`
```sh
> micromamba shell init -s bash -p /projects/micromamba
> source ~/.bashrc
> time micromamba env create -y -f ./env.yaml 
```
it took about **4m44s**

where as when i tried to do the same at `/tmp` path, it's much faster

it took only about **1m4s**

### Which version of blobfuse was used?
blobfuse2 version: 2.1.2

### Which OS distribution and version are you using?
AKS 1.28.5, 
Node Pool: Standard_E16s_v5
OS Disk: 100 GB

### If relevant, please share your mount command.
It's automatically mounted by the `blob.csi.azure.com` driver

### What was the issue encountered?
Performing file downloads at the **mounted path is extremely slow**, when compared to performing the same at **/tmp** path inside the pod, I've also noticed similar thing when I build the projects at _mounted path_ vs _/tmp path_ 

|  Test Type  |   Path  | total time   | 
| ----- | ----- | ----- |
| micromamba package downloads |  /projects - blobfuse2 mounted |  4m44s  |
| micromamba package downloads | /tmp. |  1m4s |
|  Java App - Full Install dependencies and build | /projects - blobfuse2 mounted | 101m25s |
| Java App -  Full Install dependencies and build | /tmp  | 1m26s |

### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
Performance of local drive can not be compared to a cloud storage mount. In case of application where large file system calls are made, in blobfuse these will all translate to REST calls to storage container and this will reduce the whole workflow due to network delays. Without AKS you can mount and validate this theory. Also, if you have logs collected from this run kindly share. I can look into the logs and share what kind of operations were done and how much network time it took. Kindly collect logs in log_debug mode and enable sdk-trace as well.

**Comment by svelama** [comment]
@vibhansa-msft - Thanks very much for getting back to me, the captured log file is well over 200 MB, and also it's on my work system, not sure how this can be shared here.

Can I raise a support ticket via azure, and take it from there? if so please suggest if I need to tag anything specific so that it reaches you/your team.

**Comment by vibhansa-msft** [comment]
Can you upload the log file here? Otherwise, you can upload it to your container and share a SAS based URL with me using which I will be able to download the log file. Have only read access to the SAS so that sharing it here does not hurt you in anyway.

**Comment by svelama** [comment]
@vibhansa-msft - Unfortunately it's not straight forward as it sounds to access the logs from the corporate system and sharing it here, also public access to SA Containers aren't allowed too, anyway we're going ahead with Prem. SSD Disk as a potential solution.

Thanks!

**Comment by vibhansa-msft** [comment]
If you can enable debug logs and sdk-trace from config file and share your config file and command I can check if we can optimize something from there. For the logs maybe you can try to dig yourself. Search for REQUEST or RESPONSE keywords and that will show your REST calls along with their response code and time taken by server to respond. If the response are slow or you see some 5xx return codes, then we are hitting throttling. If you can search few logs and share them here it might be helpful.
Only way to share entire log file I see is to raise an ICM and assign it to me with your log files attached.

**Comment by svelama** [comment]
I can see an option`(mountOptions in the Storage Class)` to override the default log level, 

```sh
--log-level=LOG_WARNING  # LOG_WARNING, LOG_INFO, LOG_DEBUG
```

However, I couldn't find anything specific to `sdk-trace`, the [docs says](https://github.com/Azure/azure-storage-fuse/wiki/blobfuse2-logging#sdk-logging) - `SDK logging can be enabled by specifying the config file parameter azstorage.sdk-trace: true`, but it's not clear how and where this config file actually located in the context of AKS Cluster?

**Comment by vibhansa-msft** [comment]
sdk-trace as of now can be enabled only through config file, for AKS this might not work. Let me take this up as an action item to allow this config through cli as well. For now you can just set LOG_DEBUG and share the log files. Any error coming from backend will still be emitted in logs but regular trace of rest calls will be skipped.

**Comment by svelama** [comment]
@vibhansa-msft - Just in case - I've raised an IcM on 14th March (Ref: 2403140050001815)

**Comment by vibhansa-msft** [comment]
Can you share the ICM number/link here?

**Comment by svelama** [comment]
I got a response from AKS PG team this morning, and they're suggesting to set `--attr-cache=true` flag to reduce kernel calls, this is again not clear. I do not see any flag that says `--attr-cache`, the only flag that comes closer `--use-attr-cache=true`

https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-provision?tabs=mount-nfs%2Csecret#storage-class-using-blobfuse

From AKS User point of view, I don't think we should be playing at node level to tweak these settings, this breaks the meaning of `managed` clusters.

Please go-ahead and close the issue, will continue with the support request TrackingID#2403140050001815

Thanks again for all the help, much appreciated.

**Comment by vibhansa-msft** [comment]
"--use-attr-cache=true" shall be the one. In case of AKS you need to provide these options to your PV only so this will go at node level.

**Comment by svelama** [comment]
Yes, `--use-attr-cache=true` was present in the storage class, when the logs were collected.

**Comment by vibhansa-msft** [comment]
Try setting below param as well
```
--attr-timeout=<TIMEOUT IN SECONDS>: Time the kernel can cache inode attributes.
--entry-timeout=<TIMEOUT IN SECONDS>: Time the kernel can cache directory listing.
--negative-timeout=<TIMEOUT IN SECONDS>: Time the kernel can cache non-existance of file or directory.
```

**Comment by vibhansa-msft** [comment]
Again, all these can give you some boost in performance but still it will not be comparable to local file system due to heavy network call we rely on to interact with storage container.

**Comment by vibhansa-msft** [comment]
If you are able to share a debug log then I can go over it to see what all operations your application is performing,

**Comment by svelama** [comment]
We're using the same `sc` sample from [MS website](https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-provision?tabs=mount-nfs%2Csecret#storage-class-using-blobfuse),

```yaml
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10  # prevent billing charges on mounting
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --log-level=LOG_DEBUG  
  - --cache-size-mb=1000 
```

again, the logs were collected with the above settings

**Comment by vibhansa-msft** [comment]
In general your file sizes are big or you have large number of small files ?

**Comment by vibhansa-msft** [comment]
Closing this as there is no update, feel free to reopen if the issue persists.
