### ISSUE TITLE
error: library too old when mounting adls container

### ISSUE THREAD

**Issue by dougkite** [Azure/azure-storage-fuse#1359]
### Which version of blobfuse was used?
2.2.1

### Which OS distribution and version are you using?
RHEL 8.6

### If relevant, please share your mount command.
> blobfuse2 mount /mnt/adls --config-file=/usr/share/blobfuse2/config.yaml

### What was the issue encountered?
fuse: warning: library too old, some operations may not not work
fuse: reading device: Invalid argument
Error: unable to start pipeline [failed to mount fuse]

### Have you found a mitigation/solution?
no

### Please share logs if available.

**installed versions:**
> yum list installed | grep fuse
blobfuse2.x86_64                 **2.2.1-1**                                     @packages-microsoft-com-prod                  
fuse-common.x86_64                **3.3.0-15.el8**                                @rhel-8-for-x86_64-baseos-eus-rhui-rpms       
fuse-libs.x86_64                  **2.9.7-15.el8**                                @rhel-8-for-x86_64-baseos-eus-rhui-rpms       
fuse3.x86_64                      **3.3.0-15.el8**                                @rhel-8-for-x86_64-baseos-eus-rhui-rpms       
fuse3-libs.x86_64                 **3.3.0-15.el8**                                @rhel-8-for-x86_64-baseos-eus-rhui-rpms       

(cannot find later rpm for fuse-libs)

**config.yaml:**
foreground: true
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /mnt/tempcache
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: adls
  account-name: <acctname>
  container: <contname>
  mode: msi
  sdk-trace: true

**Comment by vibhansa-msft** [comment]
Kindly check your package manager and upgrade the fuse library if possible. This warning and error is coming from underlying fuse driver itself.

**Comment by dougkite** [comment]
the latest in the package manager is 2.9.7-15.el8
I also tried installed 2.9.7-19.el8 from a CentOS repository.

Can you tell me which version supported? Thought 2.9.7 was ok.

also tried uninstalling fuse-libs and just having only fuse3-libs installed but that gives the same result.

Thanks

**Comment by vibhansa-msft** [comment]
On RHEL 8.6 you shall have Fuse 3.x version and not 2.9.7.
May be you can uninstall fuse and libfuse-devel and install fuse3 and libfuse3-devel instead and try again.
Also, in the config file you have a knob to include fuse-trace, enable this flag and enable foreground mounting as well. This will start dumping fuse related logs on the console and shall help us understand what issue fuse is facing here.

**Comment by dougkite** [comment]
It is working now. However it does still give the "library too old" message.

Upgraded to RHEL 8.9.
removed lib-fuse **2.9.7** with command rpm -e --nodeps fuse-libs
removed and reinstalled fuse3 and fuse3-libs (3.3.0-17.el8)

Thank you!

**Console messages with foreground and fuse-trace on:**
blobfuse2 mount /mnt/adls --config-file=/usr/share/blobfuse2/config.yaml
fuse: warning: library too old, some operations may not not work
FUSE library version: 3.3.0
nullpath_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 104, pid: 0
INIT: 7.34
flags=0x73fffffb
max_readahead=0x00020000
   INIT: 7.26
   flags=0x0041f039
   max_readahead=0x00400000
   max_write=0x00100000
   max_background=128
   congestion_threshold=96
   time_gran=1
   unique: 2, success, outsize: 80
unique: 4, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 8635
statfs /

**Comment by vibhansa-msft** [comment]
If things are working fine now and you do not see any upgrades available for your fuse3 driver then you can ignore the warning message for now and continue to use blobfuse. If you face any issue in any sort of operations than let me know.
