### ISSUE TITLE
File cache setting doesn't honor timeout-sec 

### ISSUE THREAD

**Issue by ytaous** [Azure/azure-storage-fuse#1369]
### Which version of blobfuse was used?
blobfuse2

### Which OS distribution and version are you using?
v 2.1.2
Operating System: Ubuntu 22.04.3 LTS 

### If relevant, please share your mount command.

#!/bin/bash

LOCAL_DIR_NAME=
MOUNT_PATH=
TMP_PATH=

mkdir -p $MOUNT_PATH
mkdir -p $TMP_PATH

fusermount -uq $MOUNT_PATH

blobfuse2 $MOUNT_PATH --config-file=./123.yaml --log-level=LOG_DEBUG -o ro,allow_root --tmp-path=$TMP_PATH

------------ 123.yaml

allow-other: true

# Logger configuration
logging:
  type: syslog
  level: log_debug

# Pipeline configuration. Choose components to be engaged. The order below is the priority order that needs to be followed.
components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120

file_cache:
  timeout-sec: 604800 # set for 7 day, ideally we want to disable evicition
  high-threshold: 95
  allow-non-empty-temp: true
  cleanup-on-start: false     # Default=true (determine if yields dirty writes)
  sync-to-flush: false
  refresh-sec: 86400 # 1 day, ideally want to disable newer weights' file
attr_cache:
  timeout-sec: 7200

# Azure storage configuration
azstorage:
# Required
    type: block
    account-name: 
    mode: msi
    resid: 
    container: 

### What was the issue encountered?
We 'd like to keep cached files remain un-expired or at least honor the  timeout-sec settings to keep the files for more than 7 days.
However, if no code is accessing the cache over a weekend, the file cache will be re-built again. 
Any idea why? are we missing any setting, or it's known issue to be fixed in future?
thx.

### Have you found a mitigation/solution?
No. Not so good mitigation - wait a few hours to rebuild cache.

**Comment by vibhansa-msft** [comment]
If objective is to just keep the files cached for 7 days, do not provide any refresh-sec option. Another reason for early eviction may be due to disk getting full. In disk exhaustion early eviction will kick in. Otherwise, files will remain as per the given timeout.

**Comment by ytaous** [comment]
Thanks, will try wo/ timeout-sec and see. Our disk size is plenty, should not be the reason.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Feel free to reopen if the issue persists.
