### ISSUE TITLE
Query : Use case for blobfuse2

### ISSUE THREAD

**Issue by rajsshah86** [Azure/azure-storage-fuse#1370]
### Which version of blobfuse was used?
blobfuse2

### Which OS distribution and version are you using?
RHEL 9 (VM) and ubuntu 22.04 (container) in Azure.

### If relevant, please share your mount command.
N/A

### What was the issue encountered?

This is more of a query to check is blobfuse is a good candidate for our use case . 

Case: We want to host linux repository on Azure Blob so that all the client Vms can simply access the storage account blob url and downloads the packages .
For this we want to run monthly an automation ( preferably via github action) that will use blobfuse to mount the BLOB. Then we will run reposync command with destination as blob mountpoint which will eventually download the packages and upload it to BLOB.

My question is from COST and PERFORMANCE prespective .
Every month when we run this automation 
- As soon as blob is mounted on the VM/runner , blobfuse will first download the entire blob in the cache . Correct ? 
- In local file system scenario when we run reposync command along with some flags it makes sure that it downloads only the newer file ( as it internally checks / compares all the files present on that local path) and skips the file that is already present . However we are not sure if on the blobfuse filesystem will add some extra cost because it will again try to upload the skipped files as well ??

Because the repo size will be around 800 GB we want to check if performance wise it will be ok and from cost perspective we want to avoid  double cost.

Would azcopy be a better candidate for this use case ?

**Comment by vibhansa-msft** [comment]
- When you mount nothing gets downloaded. There might be calls made by kernel to get a list of objects on root and calls to get their properties. No download of any blob unless you try to open that file.
- If the reposync command tries to validate the contents of a file by reading it then yes, all the files it tries to touch will get downloaded. If reposync just checks based on last modified time or something (which is highly unlikely) it will not download. 
- In terms of upload only files reposync tries to write will be charged (as both upload and download involves a REST call).

In general, any file you/application tries to open up for read/write will be downloaded to the host. If the file gets modified, then its marked dirty in blobfuse. When application tries to close the file, if its dirty it gets uploaded back to the storage. If the file was only read and not modified, then upload will not hit, and you will save some cost there.

**Comment by vibhansa-msft** [comment]
Closing this item here. If you have any further queries feel free to use this thread.

**Comment by rajsshah86** [comment]
@vibhansa-msft Hi vikas 
i am having issue in understanding why the packages are getting downloaded and uploaded again by blobfuse and the reposync utility.
To give you context 

I am using yum utility (reposync) command that basically downloads the packages from internet . 
`
reposync -p /repo/ --download-metadata --delete -a noarch -a x86_64
`
If the packages are already in the local destination folder then it skips those packages and only downloads the newer one.

In my case the destination is not local but **/repo**  which is basically the location where I have mounted the storage account container using blobfuse2-2.3.0

I can see that on my multiple runs , most of the time the reposync is thinking that the packages are not present on the container and hence downloading it again . This behaviour is not aways for the same set of files/packages . It differs every run.

For eg, in below snap you can see that from my previous run reposync found few packages in container and marked them as skipped , but it is again trying to download other packages eventhough they are already in the container from the previous runs.
<img width="725" alt="image" src="https://github.com/Azure/azure-storage-fuse/assets/38250316/e4a23218-27e1-4a91-843f-12674c6db619">

I tried with both block_cache and file_cache settings but i am unable to achieve the desired results. MY doubt is that I am some how not able to find the optimal settings that I need to put in blobfuse config file.

In your opinion what would be an ideal setting for this scenario . The only intention is that blobfuse mount container and reposync downloads package from internet and upload to this container . There are no other clients that will use this container.
