### ISSUE TITLE
file can not sync to storage account , use blobfuse1 mount storage blob in AKS

### ISSUE THREAD

**Issue by ZHASONG** [Azure/azure-storage-fuse#1383]
### Which version of blobfuse was used?
V1

AKS node OS version: 
ubuntu-22.04

mount is successful, and there is one file that cannot be synchronized to the storage account. Please check the screenshot
![image](https://github.com/Azure/azure-storage-fuse/assets/58546663/b904014c-2ba1-4abe-9b16-9580db55c97d)

the file mail-admin-2024-04-08.log can not sync to storage account , the other files can sync successful
![image](https://github.com/Azure/azure-storage-fuse/assets/58546663/6952edaa-aa3c-4b45-8b7f-66a7319503f2)

It is very strange that the permissions of other files cannot be changed, but this problematic file can change the permissions at will
and you can see the mail-admin-2024-04-08.log is in the mount directory.

please help to check, Under what circumstances can a file not be written to the storage directory, even though the file is already in the storage directory, but in fact, the file is not in the storage directory at that time

**Comment by vibhansa-msft** [comment]
Can you upgrade to Blobfuse2 and revalidate the behaviour.

**Comment by ZHASONG** [comment]
> Can you upgrade to Blobfuse2 and revalidate the behaviour.

Thanks for your feedback,  could you please provide how to  upgrade to Blobfuse2,  and could you please give some suggestions about why the file can not sync to the storage directory,

**Comment by vibhansa-msft** [comment]
"sudo apt install blobfuse2" that will install blobfuse2 and then you need to create a yaml config or set env variables and just change your mount command from "blobfuse <mnt path> ..." to "blobfuse2 mount <mnt path> ...". Kindly refer to our Readme in this repo and there are some sample config files as well on the root.

**Comment by ZHASONG** [comment]
> "sudo apt install blobfuse2" that will install blobfuse2 and then you need to create a yaml config or set env variables and just change your mount command from "blobfuse ..." to "blobfuse2 mount ...". Kindly refer to our Readme in this repo and there are some sample config files as well on the root.

Thanks for the information,  We found that under the directory mounted in the pod, users can directly create files and they can be synchronized to the storage blob, but when using code to automatically generate log files and place them in the directory mounted, the files may not necessarily be synchronized. Are there any conditions for file synchronization, such as permissions or files generated using other APIs? Is there a problem?

**Comment by vibhansa-msft** [comment]
There is no such restriction. If you are creating files on the pod where blobfuse is mounted, it shall work fine. If this is a shared directory and you create files through some other means it may not hit the kernel in pod and hence may get skipped.

**Comment by ZHASONG** [comment]
> There is no such restriction. If you are creating files on the pod where blobfuse is mounted, it shall work fine. If this is a shared directory and you create files through some other means it may not hit the kernel in pod and hence may get skipped.

Because the file cannot be synchronized to the storage account without any error reporting messages, I would like to ask whether there is a log that can be viewed for the specific reason. Thank you.

**Comment by vibhansa-msft** [comment]
AKS by default will use blobfuse2. @andyzhangx  to throw more light on this.

**Comment by andyzhangx** [comment]
> we found the config document in Microsoft Azure refer to the document : https://docs.azure.cn/en-us/aks/azure-csi-blob-storage-provision?tabs=mount-blobfuse%2Csecret#mount-volume Is blobfuse 1 or 2 used by default for this mount?

if it's aks supported version(1.26 or later version), the managed blob csi driver is already using blobfuse v2? @ZHASONG what is your aks cluster version? is your blob csi driver open source installed?

**Comment by ZHASONG** [comment]
> > we found the config document in Microsoft Azure refer to the document : https://docs.azure.cn/en-us/aks/azure-csi-blob-storage-provision?tabs=mount-blobfuse%2Csecret#mount-volume Is blobfuse 1 or 2 used by default for this mount?
> 
> if it's aks supported version(1.26 or later version), the managed blob csi driver is already using blobfuse v2? @ZHASONG what is your aks cluster version? is your blob csi driver open source installed?

Hi Andy, 

Current Kubernetes Version is 1.27.9 in AKS.  Blob CSIDriver Enabled True.  use official document to config : https://docs.azure.cn/en-us/aks/azure-blob-csi?tabs=NFS
https://docs.azure.cn/en-us/aks/azure-csi-blob-storage-provision?tabs=mount-nfs%2Csecret

**Comment by andyzhangx** [comment]
@ZHASONG then how do you know it's blobfuse v1? do you have the csi driver logs on the node, follow by: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by andyzhangx** [comment]
also you could ssh to the node, and check blobfuse2 logs under `/var/log/blobfuse2.log`

**Comment by ZHASONG** [comment]
> also you could ssh to the node, and check blobfuse2 logs under `/var/log/blobfuse2.log`

Hi  Andy , i have confirmed it is blobfuse2 .  I found an information from the document:
https://docs.azure.cn/en-us/storage/blobs/blobfuse2-what-is#file-caching-on-disk

the data is first persisted to cache on a local disk. The data is written to Blob Storage only after the file handle is closed. If an issue attempting to persist the data to Blob Storage occurs, an error message appears.  do you know how to check whether the file handle is closed

**Comment by vibhansa-msft** [comment]
File handle is something that exists in the application context and AKS or blobfuse has no way directly to understand that. Application needs to take care of handle closure. If wish to figure out application has closed it or not, best way is to check the application itself. Another way can be to check blobfuse logs and search for handle closure related logs (however this will exists only when debug logs are enabled). Another much easier way to check for all the handles currently open on the application front using proffs. Execute 'ls -l /proc/<pid>/fd', here pid shall be the pid of your application instance.

**Comment by vibhansa-msft** [comment]
Closing this assuming there are no further queries on this thread. Feel free to reopen or post your queries here.
