### ISSUE TITLE
unable to chnage directory or file permissions

### ISSUE THREAD

**Issue by vipinvijay7793** [Azure/azure-storage-fuse#1389]
### Which version of blobfuse was used?
blobfuse2 version 2.3.0~preview.1

### Which OS distribution and version are you using?
RHEL-9

### If relevant, please share your mount command.
sudo blobfuse2 mount /DATA/test/ --config-file=/root/blobfuse2config_test.yaml -o allow_other

### What was the issue encountered?
unable to chnage directory or file permissions tried chmod, chown and umask, there it is not working.

### Have you found a mitigation/solution?
no

### Please share logs if available.

no logs

**Comment by vibhansa-msft** [comment]
'chown' is not supported by blobfuse as there is no native filed for uid/gid in blobs.
'chmod' is supported and it modifies the permissions part of blob properties. However this will require certain access privillage. What authentication mode you are using here?

**Comment by vipinvijay7793** [comment]
using MSI auth.

**Comment by souravgupta-msft** [comment]
@vipinvijay7793, chmod operation is not permitted in `Storage Blob Data Contributor` role. You will have to assign your MSI `Storage Blob Data Owner` role.

**Comment by souravgupta-msft** [comment]
Closing this. Please try the above option. For more queries, you can post in this thread.
