### ISSUE TITLE
Disabling authentication is supported on a different endpoint within Azure BlobFuse?

### ISSUE THREAD

**Issue by Tulsishah** [Azure/azure-storage-fuse#1391]
Hi,

Is there any way to disable authentication on a different endpoint within Azure BlobFuse?

Thanks,
Tulsi Shah

**Comment by vibhansa-msft** [comment]
What you mean by disable authentication ? If you are using Azure Storage how do you plan to access the storage account / container without authentication.

**Comment by Tulsishah** [comment]
I meant public bucket which have read only access without any authentication or any test server which does not require authentication.

**Comment by vibhansa-msft** [comment]
Anonymous auth is not supported officially by Blobfuse2.

**Comment by vibhansa-msft** [comment]
This is not safe and you will not get any help from backend in case of data corruption or loss as it's not traceable as to who did the modifictions/deletion. Its advised that you use OAuth based authentication to access your storage accounts.

**Comment by vibhansa-msft** [comment]
Closing this as this is an unsupported feature.
