### ISSUE TITLE
unable to build in mac

### ISSUE THREAD

**Issue by quantrpeter** [Azure/azure-storage-fuse#1397]
hi, unable to build in mac, any hints?

/Users/peter/workspace/azure-storage-fuse>go version
go version go1.20.5 darwin/amd64

/Users/peter/workspace/azure-storage-fuse>go build -o blobfuse2

# github.com/Azure/azure-storage-fuse/v2/common
common/util.go:376:45: stat.Frsize undefined (type syscall.Statfs_t has no field or method Frsize)
common/util.go:379:46: stat.Frsize undefined (type syscall.Statfs_t has no field or method Frsize)
common/util.go:382:42: stat.Frsize undefined (type syscall.Statfs_t has no field or method Frsize)

thanks

**Comment by ashruti-msft** [comment]
As of now we do not support blobfuse on MacOS.
One possible way to do this is to use docker container. Refer [this](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Docker-Container) if you are interested in that.
