### ISSUE TITLE
unable to mount container with private link to a vm

### ISSUE THREAD

**Issue by vahsek300501** [Azure/azure-storage-fuse#1399]
### Which version of blobfuse was used?
blobfuse2-2.2.1

### Which OS distribution and version are you using?
Ubuntu 20.04

### If relevant, please share your mount command.
blobfuse2 mount /mnt/mountpoint/ --config-file config.yaml foreground &

### What was the issue encountered?
I am getting authentication issue Error: failed to initialize new pipeline [failed to authenticate credentials for azstorage]. I have the following config file

![image](https://github.com/Azure/azure-storage-fuse/assets/58917332/ae2bd9ab-1576-4f27-ac5a-2547f61baf94)

to generate the sas token I went to container and then generated the sas token by right clicking the container. The storage account is in a vnet attached using private link

### Have you found a mitigation/solution?
NO

**Comment by ashruti-msft** [comment]
When generating the SAS token did you give it "list" permission? Check the permissions given and also the expiry date.

**Comment by vahsek300501** [comment]
Yes I gave all the permissions when generating the SAS token. Along with this the following was the error

![image](https://github.com/Azure/azure-storage-fuse/assets/58917332/cce0708c-be4d-45aa-81d2-d41d6ab77238)

**Comment by ashruti-msft** [comment]
Does your DNS have correct entry to resolve public endpoint to private endpoint? 
Also, you should use the foreground flag `--foreground`

**Comment by vahsek300501** [comment]
Yes I have an entry in the DNS. 
Sure I will try with the flag

**Comment by vahsek300501** [comment]
Hi the issue got resolve.
Thanks

**Comment by ashruti-msft** [comment]
In your config change the endpoint to your private endpoint and try again. Also, ensure that you are able to reach your storage account using other tools like curl etc. to confirm its reachability. If you are using SAS you can just give a blob's SASurl to check its accessibility.

**Comment by vibhansa-msft** [comment]
What were we missing here? Kindly share to help other customers facing similar issues.
