### ISSUE TITLE
RHEL 9 support still wip or done ?

### ISSUE THREAD

**Issue by mbagiella** [Azure/azure-storage-fuse#1401]
Is the blobfuse 2 compatible with RHEL 9 ?
The document is saying RHEL 9 WIP since 2022. Is it now compatible?

**Comment by souravgupta-msft** [comment]
Hi @mbagiella. Thanks for reaching out. We do release blobfuse2 in RHEL 9.0 for both AMD and ARM architectures. You can refer [this](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Installation) for installing using the yum package manager.

**Comment by souravgupta-msft** [comment]
@mbagiella, can you share the document which says that it is WIP for RHEL 9.

**Comment by mbagiella** [comment]
The following platforms are supported for Blobfuse2 as of 10/12/2022

Blobfuse2 is supported only on x86_64 architecture.
ARM64 support is work-in-progress.
RHEL9 x86_64 is also WIP.

Source: https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Supported-Platforms

**Comment by souravgupta-msft** [comment]
Thanks for pointing it. We will update this doc.

**Comment by mbagiella** [comment]
Hi Sourav, Thanks for the update.
When the package will be deployed in an officially ?
I mean in Microsoft package ?
My company is reticent to use the package because they do not trust Github :(

**Comment by souravgupta-msft** [comment]
Blobfuse is already published to the Microsoft packages. You can follow the instructions [here](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Installation#install-from-aptyum-package-repositories).
