### ISSUE TITLE
Azure blob fuse via a proxy

### ISSUE THREAD

**Issue by thekoolestkat** [Azure/azure-storage-fuse#1402]

**Comment by souravgupta-msft** [comment]
Hi @thekoolestkat. Thanks for reaching out. Can you share your config file and mount command?
You can mention the proxy in your config file in either [`http-proxy or https-proxy`](https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml#L160-L161) under azstorage section.

**Comment by thekoolestkat** [comment]
Hi
Thanks for the prompt reply the mount command i used was "blobfuse2 mount ./blobtestrhel --config-file=./fuse-config.yaml" i also tried "blobfuse2 mount ./blobtestrhel --config-file=./fuse-config.yaml --disable-version-check=true" the proxy settings are on the linux host not held in the config file.

Config File:

logging:

  type: syslog

  level: log_debug

 

components:

  - libfuse

  - file_cache

  - attr_cache

  - azstorage

 

libfuse:

  attribute-expiration-sec: 120

  entry-expiration-sec: 120

  negative-entry-expiration-sec: 240

 

file_cache:

  path: /mnt/ramdisk/blobtestrhel

  timeout-sec: 120

  max-size-mb: 4096

 

attr_cache:

  timeout-sec: 7200

 

azstorage:

  type: block

  account-name: blobtestrhel

  sas: <Removed for Security>

  endpoint: https://blobtestrhel.blob.core.windows.net/

  mode: sas

  container: data

**Comment by souravgupta-msft** [comment]
Can you specify the proxy in environment variable `http_proxy` or `https_proxy` and retry mounting.

**Comment by thekoolestkat** [comment]
Hi Please see below:
[xxxx-xxx@dvxxxxx002 ~]$ echo $http_proxy

http://xxx.xx.xx.69:8080/

[xxxx-xxx@dvxxxxx002 ~]$ echo $https_proxy

http://xxx.xx.xx.69:8080/

[xxxx-xxx@dvxxxxx002 ~]$

**Comment by souravgupta-msft** [comment]
@thekoolestkat, can you retry mounting after setting either of the environment variable. Please share the debug logs if the mount is failing.

**Comment by thekoolestkat** [comment]
Hi thanks for the reply 
I have had the environment variables set to the proxy.
Can you confirm what log files are you after ?/var/log/blobfuse2.log
Thanks,

**Comment by souravgupta-msft** [comment]
Yes, please share the logs in /var/log/blobfuse2.log

**Comment by thekoolestkat** [comment]
Hi please find attached the log file 
[blobfuse2.log](https://github.com/Azure/azure-storage-fuse/files/15343441/blobfuse2.log)

**Comment by thekoolestkat** [comment]
Hi 
Thanks for getting back to me so I tried few things below:
Curl Prior to upgrade with No Porxy server
![CURL prior to upgradeWithProxyServer](https://github.com/Azure/azure-storage-fuse/assets/16217300/194e2450-d263-4277-b467-ede35d6ec9cd)

Curl prior to upgrade with a proxy server configured
![CurlPriorToUpgrade](https://github.com/Azure/azure-storage-fuse/assets/16217300/6221d086-7ec9-4379-bf22-9c7bcf5a7ed3)

Mount Prior to upgrade no proxy server configured
![Mount prior to upgrade No Proxy Servers configured](https://github.com/Azure/azure-storage-fuse/assets/16217300/18da6c68-453c-49ad-8431-67b213039cab)

Mount Prior to upgrade with a proxy server configured
![Mount prior to upgrade with Proxy servers](https://github.com/Azure/azure-storage-fuse/assets/16217300/4048f70f-ec74-491d-a6a5-7f7fb63a35c3)

Upgraded to 2.3.0 mount with proxy still fails with Mount
![Upgraded to 2 3 0 – Mount still failed](https://github.com/Azure/azure-storage-fuse/assets/16217300/678a414c-1f29-498e-8a5b-e9e2a7bce0f4)


Blobfuse2.log file attached




[blobfuse2-22-5-24.log](https://github.com/Azure/azure-storage-fuse/files/15411525/blobfuse2-22-5-24.log)

**Comment by souravgupta-msft** [comment]
@thekoolestkat, sorry for replying late. I was able to setup proxy and replicate this error. It is a bug in the code, and we will fix this in our next release. For now, as temporary mitigation, you can just set `https_proxy` as `xxx.xx.xx.42` (without protocol).

**Comment by stealth1188** [comment]
I seeing the same issue :(

proxyconnect tcp: dial tcp: lookup http://172.20.8.11: no such host

Our proxy requires to append a port as well (eg, 172.20.8.11:3128) and we've tried both dns name and ip separately under https_proxy and http_proxy for env.

blobfuse2 --version
blobfuse2 version 2.3.0
