### ISSUE TITLE
Entra ID Authentication

### ISSUE THREAD

**Issue by drjinying** [Azure/azure-storage-fuse#1411]
Recent security guidelines suggest to disable Key/SAS authentication, and use Microsoft Entra ID instead.
Is there a way to blobfuse with Entra ID authentication? Or what's the best alternative without using key/sas?
Thank you!

**Comment by ashruti-msft** [comment]
You can use Managed Identity(MSI) or Service Principal(SPN) for Entra ID authentication. Thanks!
