### ISSUE TITLE
Implement concurrency management

### ISSUE THREAD

**Issue by lubo** [Azure/azure-storage-fuse#1412]
[Managing Concurrency in Blob storage](https://learn.microsoft.com/en-us/azure/storage/blobs/concurrency-manage) describes concurrency management mechanisms supported by Azure Blob Storage. It'd be really useful if we could take advantage of them while using this app.

**Comment by vibhansa-msft** [comment]
Blobfuse is a file-system driver and works with last writer wins mindset. If you wish to update data as and when it's updated in storage container you can use "-o direct_io" option, however this means you are making extra calls to storage, and it will come with the cost. To save cost on user front blobfuse uses a local cache both for contents and metadata and hence it does not support concurrency the way you are thinking unless its configured to take a hit on cost and provide consistency.
