### ISSUE TITLE
Unable to build the blobfuse2 from the source code.

### ISSUE THREAD

**Issue by rajsshah86** [Azure/azure-storage-fuse#1413]
### Which version of blobfuse was used?
N/A trying to build the blobfuse2 from main branch

### Which OS distribution and version are you using?
rhel 8.8

### If relevant, please share your mount command.
N/A

### What was the issue encountered?
Trying to build the blobfuse from main branch because I want to use the azcli auth feature. However while building getting error.

I already have below package installed

fuse-common.x86_64                            3.3.0-16.el8                             
fuse-libs.x86_64                              2.9.7-16.el8                                           
fuse-overlayfs.x86_64                         1.11-1.module+el8.8.0+21336+3fe03132     
fuse3.x86_64                                  3.3.0-17.el8                             
fuse3-devel.x86_64                            3.3.0-17.el8                              
fuse3-libs.x86_64                             3.3.0-17.el8                             

```
git clone https://github.com/Azure/azure-storage-fuse/
cd ./azure-storage-fuse
git checkout main
go get
go build -tags=fuse3

```

### Have you found a mitigation/solution?
no

### Please share logs if available.
```
# github.com/Azure/azure-storage-fuse/v2/component/libfuse
component/libfuse/libfuse.go:164:12: lf.initFuse undefined (type *Libfuse has no field or method initFuse)
component/libfuse/libfuse.go:176:9: lf.destroyFuse undefined (type *Libfuse has no field or method destroyFuse)
```

**Comment by vibhansa-msft** [comment]
You have missing depedencies and hence build is failing. Kindly install those using
```
sudo yum groupinstall "Development Tools" -y
sudo yum install git fuse fuse3-libs fuse3-devel fuse3 python36 -y --nobest --allowerasing
```
