### ISSUE TITLE
blobs mounted in linux become duplicate files

### ISSUE THREAD

**Issue by DavidChenLiang** [Azure/azure-storage-fuse#1422]
### Which version of blobfuse was used?
blobfuse1 were used.
blobfuse2 also installed but not mount successfully:

rpm -qa|grep blobfuse
blobfuse2-2.3.0-1.x86_64
blobfuse-1.4.5-1.el7.x86_64

### Which OS distribution and version are you using?
cat /etc/system-release
CentOS Linux release 7.9.2009 (Core)

 uname  -a
Linux h3clearning-transforms01 3.10.0-1160.118.1.el7.x86_64 #1 SMP Wed Apr 24 16:01:50 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### If relevant, please share your mount command.
blobfuse /data/nfs --tmp-path=/home/ramdisk --config-file=/etc/azure-storage-fuse1.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o nonempty

### What was the issue encountered?
My customer use blobfuse1 to mount a container with Azure Blob Service to read/write blobs in a CentOS box,  some other service like AKS also mounts the container as it pv to read/write files in the blob container as well, it is working fine until after upgrade AKS lately (could be coincidence), the CentOS box cannot read the "folder" which created by AKS, if AKS side create a folder like "abc", from the CentOS end, it will see two files, one named "abc", another one named "abc "(with a space appended).

screen shot like below:
![image](https://github.com/Azure/azure-storage-fuse/assets/5467103/a041440b-2174-4aa7-adc4-255573c6d536)

### Have you found a mitigation/solution?
Customers have to create "folders" manually from CentOS end.

**Comment by souravgupta-msft** [comment]
Hi @DavidChenLiang. Please update to use blobfuse v2. If you are seeing errors while mounting, kindly share the mount command, config file, debug logs and console output (which contains the error).
Also, are you using HNS enabled storage account?

**Comment by souravgupta-msft** [comment]
The issue resolved after updating to blobfuse v2.
