### ISSUE TITLE
Security: Support `az login` authentication

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-storage-fuse#1423]
blobfuse only supports managed identity as keyless authentication method. During development, it is common that the account key or SAS token methods are used. Developers tend to use those methods because there is either no control over the managed identity of VMs, or because blobfuse is used locally outside Azure, for example in WSL.

I propose that Azure CLI login is added as authentication method.

This is quickly becoming critical as key-based authentication is being disabled on storage accounts across organisations to improve their security posture.

**Comment by rajsshah86** [comment]
@letmaik : New release blobfuse2-2.3.0 supports this . I have been using it now from last week.

**Comment by souravgupta-msft** [comment]
@rajsshah86, thanks for pointing it out and confirming that it is working for your scenario.

@letmaik, you can use the login mode as `azcli` in your [config file](https://github.com/Azure/azure-storage-fuse/blob/main/testdata/config/azure_cli.yaml) under azstorage section.
