### ISSUE TITLE
Renew user delegation SAS

### ISSUE THREAD

**Issue by hieuhoang** [Azure/azure-storage-fuse#1427]
### Which version of blobfuse was used? 
V1 (1.4.5)

### Which OS distribution and version are you using? 
Ubuntu 22.04

### What was the issue encountered?
A delegation SAS token has a max time limit of 7 days. If they are used, we need to unmount and remount the blob, which causes issues if there are running jobs that is using the mount. Is there a way to update the SAS token that the blobfuse driver uses without having to unmount & remount?

**Comment by vibhansa-msft** [comment]
You are using a very old version of Blobfuse. Kindly upgrade to Blobfuse 2.3.0. In Blobfuse2 we have a feature where you can just update the SAS token in configuration file and without remount, running instance of blobfuse will start using the new token.

**Comment by hieuhoang** [comment]
Oh, that sounds great. This is probably the reason to move to blobfuse v2. 

How do we enable this feature, or is it always on? So the driver will re-read the config file every time it does a read or write, or do it re-read the config file periodically? If periodically, what is the period?

**Comment by vibhansa-msft** [comment]
This is always on just configure blobfuse2 to use SAS through a config file and whenever you regenerate you SAS just update the config file and new SAS will take effect. Config files are read on update so moment you save the config file Blobfuse will get a notification to re-read the config.
