### ISSUE TITLE
Feedback Request: Stable release approaching. Give us feedback!

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-fuse#143]
Hello folks,

We are working towards the stable version of blobfuse at the moment. Please let us know if you encounter ANY stability issue even if you do not have logs, information about what you encountered. Just let us know :)

The list of issues we are targeting for the blobfuse 1.0 release is here: https://github.com/Azure/azure-storage-fuse/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22blobfuse+1.0%22

**Comment by devmanhinton** [comment]
This is awesome @seguler !!! 

Would really love a fix for https://github.com/Azure/azure-storage-fuse/issues/90 or a work around!

If that is handled then we will 100% adopt in house as it solves an internal pain point!

**Comment by seguler** [comment]
@devmanhinton - hi there! What is the intend here ? Is it truly read-only mount ? 

This is actually supported in FUSE. You just need to use -o ro option.

Here is a quick test:
```
$ touch hereisafile
touch: cannot touch 'hereisafile': Read-only file system
```

**Comment by devmanhinton** [comment]
Did not realize that! Thank you! That is perfect.

README docs for that threw me off a bit. 

Again, this is SWEET 🙏 👍 💃

**Comment by SupriyoBiswas** [comment]
@seguler - Hi, we just started using blobfuse for a small dataset. Our plan is to use this feature for other datasets. We are using version 0.4. When are you planning to release version 1.0? Do we need to reinstall again?

A few observations while using v 0.4
1. does not preserve original file permission
2. does not preserve original time stamp
3. Created a new subdirectory under the mounted directory on on-prem RHEL 7.3 server. That directory appears as a file on the container. Later when I placed once file under the sub subdirectory, the file appears under the new folder on the container. The old incorrect file was still there. Note: I did not observe the same when used the cloud RHEL 7.3 server.

Can a container be mounted to multiple directories and can display only those files which are loaded into the container from that directory with 'ls -l' command?

**Comment by seguler** [comment]
Yes - you will need to install manually in order to upgrade. We have just released 1.0-RC release on Ubuntu, but haven't released one for RHEL yet (a minor issue is blocking us).. We plan to release the 1.0 in a few weeks.

Regarding your observations:
1. We do not intend to do lot of magic on top of blob storage. Blob storage does not support permissions, and custom timestamps
2. See above.
3. Are you seeing the file on blobfuse or on the Storage Explorer ? Our design is that we create an empty blob with the directory name. This empty blob will appear as a directory when looking from Blobfuse - but will appear as a file/blob if you look from Storage Explorer. If you have saw the directory as a file on blobfuse - then this is a bug we haven't seen before

**Comment by SupriyoBiswas** [comment]
Hello,
Thanks for the update on RHEL release.

1. By custom timestamp, I guess you mean the original time stamp that the
file had on the on-prem server before coping (cp -p) to the blogfuse mount
directory. If original time stamp  is not supported, then it will hard to
use this virtual file system for data backup purpose.

3. Adding screenshot from the Linux RHL server where virtual file system
was created backed by Azure blob. It has a sub directory 'suubdir3' and
subdir3 has a file 'xxx'. On Azure Portal I am seeing subdir3 as file as
well as a directory under the container.

**Comment by seguler** [comment]
Ok - blob storage does not support overwriting last modified time. The only time we can report is the actually last modified time of a blob. Hence we cannot preserve the last modified time you have on prem.

Re. directory behavior - yes - a directory you create on blobfuse will correspond to an empty blob with metadata "hdi_isfolder". This is the behavior that matches wasb endpoint (HDFS) on Blob storage.

**Comment by SupriyoBiswas** [comment]
Thanks.

One question - Could you please tell me the location and file name of the
log file for blobfuse?

**Comment by seguler** [comment]
Logs are located in /var/log/syslog. You can change the default logging level when mounting. See: https://github.com/Azure/azure-storage-fuse/wiki/5.-Logging

**Comment by icebrian** [comment]
Just wanted to give my feedback. I've been testing blobfuse with basically no issues at all. It seems to be working great! Congrats to devs for idea and work! Definately much appreciated!

**Comment by e271828-** [comment]
https://github.com/Azure/azure-storage-fuse/issues/162 might be a good one to patch before declaring it stable. This limitation can be an expensive discovery if you happen to be syncing 10+ TB buckets.

**Comment by SupriyoBiswas** [comment]
Sercan,
This regarding  '--tmp-path' for blobfuse command.

Does it always need to be '/mnt/resource/blobfusetmp' for RHEL?

Can not be any location and name (e.g. /any/location/myTmp)?

How much free space is needed under above allocation? Does the free space
amount impact data upload or download speed from / to on-pre server?

**Comment by seguler** [comment]
It can be any location on the file system. We recommended /mnt/resource/blobfusetmp on Azure as this location on RHEL is the local SSD attached to the Host. It is the most performant disk. Instead you can use any other disk, including a ramdisk.

**Comment by mikejwhitty** [comment]
hi @seguler, some queries related to @SupriyoBiswas's question,

should each blobfuse mount have it's own temp directory, or can they share?
are multiple blobfuse mounts on the same machine supported?
if the directory declared in --tmp-path doesn't exist, will blobfuse mount create it? (eg, from fstab) or should the mount shell script take care of that first?

**Comment by seguler** [comment]
Yes each blobfuse will have to use its own temp directory. They cannot share. This is documented in the README file.

Multiple blobfuse mounts are okay.

You will need to create the directory defined in tmp-path. Hope this helps!

**Comment by seguler** [comment]
Closing this issue as we just released the stable package! Yayy!
