### ISSUE TITLE
Connection drops after a few commands

### ISSUE THREAD

**Issue by JamesGlare** [Azure/azure-storage-fuse#1465]
### Which version of blobfuse was used?
blobfuse2 version 2.3.0

### Which OS distribution and version are you using?
Ubuntu 20.04.6 LTS

### If relevant, please share your mount command.
blobfuse2 mount <folder> --config-file=config.yaml

### What was the issue encountered?
After a few commands inside the mounted folder, say ls and cd,  the connection seems to drop and ls outputs
ls: cannot open directory '.': Transport endpoint is not connected

### Have you found a mitigation/solution?
No. It looks like it has to do with some timeout, but I cannot figure out which one. Blobfuse2 works without issue for a blobstorage that is physically closer. This one is mounted across the Atlantic (the storage account is in eastus and I am in UK south).

### Please share logs if available.
[I redacted some names]
Here's the output of tail /var/log/blobfuse2.log

Jul 22 11:00:38 myvm blobfuse2[3748285]: [/home/user/mount_folder] LOG_CRIT [mount.go (407)]: Starting Blobfuse2 Mount : 2.3.0 on [Ubuntu 20.04.6 LTS]
Jul 22 11:00:38 myvm blobfuse2[3748285]: [/home/user/mount_folder] LOG_CRIT [mount.go (409)]: Logging level set to : LOG_WARNING
Jul 22 11:00:38 myvm blobfuse2[3748285]: [/home/user/mount_folder] LOG_WARNING [config.go (367)]: ParseAndValidateConfig : account endpoint not provided, assuming the default .core.windows.net style endpoint
Jul 22 11:00:40 myvm blobfuse2[3748329]: [/home/user/mount_folder] LOG_CRIT [mount.go (407)]: Starting Blobfuse2 Mount : 2.3.0 on [Ubuntu 20.04.6 LTS]
Jul 22 11:00:40 myvm blobfuse2[3748329]: [/home/user/mount_folder] LOG_CRIT [mount.go (409)]: Logging level set to : LOG_WARNING
Jul 22 11:00:40 myvm blobfuse2[3748329]: [/home/user/mount_folder] LOG_WARNING [config.go (367)]: ParseAndValidateConfig : account endpoint not provided, assuming the default .core.windows.net style endpoint
Jul 22 11:01:04 myvm blobfuse2[3748329]: [/home/user/mount_folder] LOG_ERR [datalake.go (485)]: Datalake::List : Failed to get file permissions for folder_in_mounted_folder

After this, the connection drops or has dropped already.

**Comment by JamesGlare** [comment]
azstorage:
  type: adls
  account-name: <account_name>
  container: <container>
  mode: azcli

file_cache:
  # Required
  path: /tmp/mycache

**Comment by souravgupta-msft** [comment]
Hi @JamesGlare, thanks for reaching out.
`ls: cannot open directory '.': Transport endpoint is not connected`
The above error indicates that the binary has crashed. Can you mount blobfuse2 in foreground mode. It can be done by adding `--foreground` flag in the mount command. This will block the console where you will run the mount command. Please share the console logs if the binary crashes.
Also, please enable debug level logs in your config and the share the blobfuse2 logs as well.

**Comment by JamesGlare** [comment]
How can I set logging to debug level? I could not find that setting [here ](https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml)- probably wrong page.

Here's the output from command line when I mount in foreground mode:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa42b43]

goroutine 17 [running, locked to thread]:
github.com/Azure/azure-storage-fuse/v2/component/azstorage.(*Datalake).GetAttr(0xc000026808, {0xc0002f1861, 0x9})
        /mnt/vss/_work/1/s/azure-storage-fuse/component/azstorage/datalake.go:381 +0x463
github.com/Azure/azure-storage-fuse/v2/component/azstorage.(*AzStorage).GetAttr(0xb561e0?, {{0xc0002f1861?, 0x12203a0?}, 0x9?})
        /mnt/vss/_work/1/s/azure-storage-fuse/component/azstorage/azstorage.go:524 +0x22
github.com/Azure/azure-storage-fuse/v2/component/attr_cache.(*AttrCache).GetAttr(0xc0003ee550, {{0xc0002f1861?, 0xd87360?}, 0x90?})
        /mnt/vss/_work/1/s/azure-storage-fuse/component/attr_cache/attr_cache.go:493 +0x46c
github.com/Azure/azure-storage-fuse/v2/component/file_cache.(*FileCache).isDownloadRequired(0xc0003404e0, {0xc000313290, 0x2a}, {0xc0002f1861, 0x9}, 0xc0001e18f0)
        /mnt/vss/_work/1/s/azure-storage-fuse/component/file_cache/file_cache.go:827 +0x768
github.com/Azure/azure-storage-fuse/v2/component/file_cache.(*FileCache).OpenFile(0xc0003404e0, {{0xc0002f1861?, 0xd846b8?}, 0xc000289150?, 0xd81f50?})
        /mnt/vss/_work/1/s/azure-storage-fuse/component/file_cache/file_cache.go:867 +0x2b1
github.com/Azure/azure-storage-fuse/v2/component/libfuse.libfuse_open(0x0?, 0x7f1ca37fdd30)
        /mnt/vss/_work/1/s/azure-storage-fuse/component/libfuse/libfuse_handler.go:702 +0x3e3
```

**Comment by souravgupta-msft** [comment]
```
azstorage:
type: adls
```
Is your storage account HNS enabled?

**Comment by JamesGlare** [comment]
ah..  not it is not :/

**Comment by souravgupta-msft** [comment]
You can set the `type: block` in the config and retry.

**Comment by vibhansa-msft** [comment]
Closing this as there are no updates. Feel free to reopen if you have any further queries on this.
