### ISSUE TITLE
Blobfuse2 is not interpreting the no_proxy environment variable

### ISSUE THREAD

**Issue by pier62350** [Azure/azure-storage-fuse#1466]
### Which version of blobfuse was used?

blobfuse2-2.3.0-1.x86_64
 
### Which OS distribution and version are you using?

Red Hat Enterprise Linux release 9.4 (Plow) in Azure Virtual machine

### If relevant, please share your mount command.

`blobfuse2 /mount/blobname/blobcontainer --tmp-path="/mnt/resource/blobfusetmp/StorageAccount" --config-file="/tmp/fuse_connection_blobname_blobcontainer.yaml" -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG`

> /tmp/fuse_connection_blobname_blobcontainer.yaml content: 
> azstorage:
>   account-name: blobname
>   container: blobcontainer 
>   mode: key
>   account-key:XXXXXXXXXXXXXXXXXXXXXXX

### What was the issue encountered?

Mounting is not working as blobfuse2 is not interpreting "no_proxy" environment variable. In our environment access to the storage account should be done directly using private endpoint, and proxy has no access to the storage account. 

Port 443 is opened between the VM and the storage account, DNS resolution is OK from the VM

### Have you found a mitigation/solution?
We are able to mount the storage account when removing the proxy configuration using the following code: 

`unset no_proxy https_proxy HTTPS_PROXY HTTP_PROXY http_proxy`
when putting again the `https_proxy ` and `no_proxy` configuration mounting is not working

### Please share logs if available.

> AzStorage::configureAndTest : Failed to validate credentials [Get "https://blobname.blob.core.windows.net/blobcontainer?comp=list&delimiter=%2F&maxresults=2&prefix=&restype=container": proxyconnect tcp: dial tcp: lookup http://proxy.browsing.rec.azu.local no such host]
> 2024-06-18T10:17:15.918828+02:00 vm-backup-rec blobfuse2[2003463]: [/mount/blobname/blobcontainer] LOG_ERR [azstorage.go (101)]: AzStorage::Configure : Failed to validate storage account [failed to authenticate credentials for azstorage]
> 2024-06-18T10:17:15.918844+02:00 vm-backup-rec blobfuse2[2003463]: [/mount/blobname/blobcontainer] LOG_ERR [pipeline.go (69)]: Pipeline: error creating pipeline component azstorage [failed to authenticate credentials for azstorage]
> 2024-06-18T10:17:15.918864+02:00 vm-backup-rec blobfuse2[2003463]: [/mount/blobname/blobcontainer] LOG_ERR [mount.go (413)]: mount : failed to initialize new pipeline [failed to authenticate credentials for azstorage]

**Comment by souravgupta-msft** [comment]
Hi @pier62350, thanks for reaching out. In Blobfuse, we do not support the `no_proxy` environment variable. The default mode is without proxy. If you want to specify proxy, you can do so using the `https_proxy` or `http_proxy` environment variables. In your case, you can unset these environment variables and mount blobfuse2.

**Comment by vibhansa-msft** [comment]
Feature has been added to main line, next release will have this support.
