### ISSUE TITLE
Confirmation of Blobfuse2 support on RHEL 8.x

### ISSUE THREAD

**Issue by biggles007** [Azure/azure-storage-fuse#1468]
### Which version of blobfuse was used?

Latest

### Which OS distribution and version are you using?

RHEL 8

### If relevant, please share your mount command.

n/a

### What was the issue encountered?

The documentation states that version 8.2 is the latest supported version of RHEL 8, are the later versions of version 8 supported? If later versions (e.g. the latest RHEL 8 version on Azure) are supported, can that be clarified and the documentation updated.

### Have you found a mitigation/solution?

n/a

### Please share logs if available.

n/a

**Comment by biggles007** [comment]
To add a little more detail, my client can only run RHEL 8 for a specific service, as the third party software vendor don't currently support their solution on RHEL 9.

**Comment by ashruti-msft** [comment]
Yes, blobfuse2 supports other versions RHEL 8.x . Can you please point me to the document you are referring to here we will update it.

**Comment by biggles007** [comment]
Sorry, I should have included the link. It's in the Wiki, somewhere else (I think, but can't remember where) states to look at the latest releases in GitHub for supported releases. Wondering if that was maybe a Microsoft page? But the main one is the link below.

https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Supported-Platforms

**Comment by ashruti-msft** [comment]
Yes, so we officially dont support all versions but you can try to yum install blobfuse using the installation guide and it should work on your particular version. In case it doesn't work you can install this rpm [blobfuse2-2.3.0-RHEL-8.2.x86_64.rpm](https://github.com/Azure/azure-storage-fuse/releases/download/blobfuse2-2.3.0/blobfuse2-2.3.0-RHEL-8.2.x86_64.rpm) and use blobfuse on your system.
