### ISSUE TITLE
cannot mount when using proxy with authentification

### ISSUE THREAD

**Issue by k4ndr3** [Azure/azure-storage-fuse#1474]
### Which version of blobfuse was used?
- v2.3.0

### Which OS distribution and version are you using?
- Ubuntu WSL instance

### What was the issue encountered?
- unable to mount if using proxy / working fine without proxy

### Have you found a mitigation/solution?
- no

### Please share logs if available.
- error Get "https://xxxxx.net/xxxxxxx": proxyconnect tcp: dial tcp: lookup user:password@proxy.net: no such host

proxy is set to as environment variable $https_proxy="user:password@proxy.net:port"
it seems it cannot resolve the proxy with authentification, is this not possible at the moment and is there a workaround?

**Comment by vibhansa-msft** [comment]
We have modified the code to read details from environment variable and support no_proxy as well. Next release will have the feature.
