### ISSUE TITLE
Blobfuse2 Health Monitor - Latest log file name

### ISSUE THREAD

**Issue by luisfeliz79** [Azure/azure-storage-fuse#1478]
### Which version of blobfuse was used?
2.3.0

### Which OS distribution and version are you using?
Red Hat 8.10

### What was the issue encountered?

The health monitor log filename is monitor_<pid>.json(Zeroth index) is latest and monitor_<pid>_9.json is the oldest output file.
The issue is that is not easy to monitor this file using Azure monitor agent because the file name always changes.  Further, even if all json files in the directory were targeted, there is no easy way to select reading only the latest file, meaning that Azure monitor agent ingests duplicate data, as it reads all the other 9 monitor_<pid>_<index>.json files.

### Have you found a mitigation/solution?

The ask is for the latest log file name to have a standard name, such as monitor.json or add a common suffix, such as _0.json or _latest.json.   This would allow for a data collection rule in Azure monitor agent where only files with that name or suffix 
 targeted for ingestion.

**Comment by vibhansa-msft** [comment]
Does the latest log file not named "monitor.json" and instead shows "monitor_0.json" ?
If so, it's a miss from our end and we will try to fix this (on low priority though).

**Comment by vibhansa-msft** [comment]
Is there any particular reason you are using Health Monitor in your setup?

**Comment by luisfeliz79** [comment]
Hi @vibhansa-msft, we are using it to monitor performance and file cache transactions.   The customer is new to BlobFuse (switching over from SMB) and they want to monitor its performance, see which files made it to the cache, and impact on system resources.   They are also monitoring other related files to help with troubleshooting during issues.

In my Lab testing, the blobfuse2 health monitor files are being named like this:
(see screenshot)

monitor_<pid>.json   (latest)
monitor_<pid>_2.json  (older)

The challenge is that PID is dynamic (The PID changes across server/process restarts), and so we are not able to specify which file monitor using monitoring software, such as Azure Monitor Agent.

Some alternatives I thought of are:

- don't include the PID, example: monitor.json
- keep the PID, but add something unique to the most recent file, example:   monitor_pid_latest.json  or monitor_pid_0.json

Thank you!

![blobfusemon](https://github.com/user-attachments/assets/79a17643-36fa-4301-8607-da501b42cb1a)

**Comment by vibhansa-msft** [comment]
As per design, Health Monitor can monitor multiple instances of blobfuse running on the same system. For that reason, adding pid of the blobfuse2 instance to the log file name was a logical choice. For now, we do not have any plan to modify this behavior. If you feel this is blocking your flow, you can fork the repo and create your own version of health monitor. 
If you are using it to monitor which files have made to the container, from application side whatever file handle you close will start to sync with storage container immediately. Any failure of any sort can be found in blobfuse2 log files itself  (you can search for LOG_ERR keyword).

**Comment by vibhansa-msft** [comment]
Closing this as we will not be entertaining this request for now. We have added an item to our backlog for low priority to improvise this. For now, if you are blocked due to this you can fork and update the code and build a local binary.

**Comment by luisfeliz79** [comment]
Hi @vibhansa-msft , I can understand needing to keep the PID.   Would you entertain just adding the suffix _latest  or _0 to the first file ?    that could be a low effort but really beneficial change for many monitoring scenarios.  Thanks
