### ISSUE TITLE
Blobfuse2 Health monitor does not load when mounting blobfuse2 using fstab entry

### ISSUE THREAD

**Issue by luisfeliz79** [Azure/azure-storage-fuse#1479]
### Which version of blobfuse was used?
2.3.0

### Which OS distribution and version are you using?
Red Hat 8.10

### If relevant, please share your mount command.
- FSTAB entry:
  blobfuse2 /blobfuse-storage fuse3 defaults,_netdev,--config-file=/home/luisadmin/oracle/blobfuse.yaml

- Non-FSTAB command:
  sudo blobfuse2 mount /blobfuse-storage --config-file=/home/luisadmin/oracle/blobfuse.yaml

### What was the issue encountered?
The blobfuse2 config file contains the needed entries for enabling the health monitor.

- When mounting blobfuse2 using an fstab entry, health monitor is not loaded and no log files are produced.  Additionally, using command "ps -aux" does not show that bfusemon is running.

- However, if I mount blobfuse2 via command line, then the health monitor loads (ps -aux shows  bfusemon is running), and the log files are created.

### Please share logs if available.
Jul 27 00:50:31 blobefuseoracle blobfuse2[2292]: [/blobfuse-storage] LOG_ERR [health-monitor.go (113)]: health-monitor : failed to start health monitor [exec: "bfusemon": executable file not found in $PATH]
Jul 27 00:50:31 blobefuseoracle blobfuse2[2292]: [/blobfuse-storage] LOG_ERR [mount.go (578)]: Mount::startMonitor : [failed to start health monitor [exec: "bfusemon": executable file not found in $PATH]]

**Comment by vibhansa-msft** [comment]
Sorry for replying late on this. As per the logs shared, when Blobfuse2 is run from /etc/fstab the system is not exporting the PATH correctly. As you can see it reports "bfusemon" is not found. We have seen similar issues in past and most customers had to run a script from /etc/fstab and then from the script export correct PATH, run Blobfuse2.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Try running a script from /etc/fstab and export the path correctly from there before calling blobfuse mount.
