### ISSUE TITLE
Should backup cache go down to 0 GB after moving the backup to storage blobs

### ISSUE THREAD

**Issue by SangharshMyCD** [Azure/azure-storage-fuse#1494]
### Which version of blobfuse was used?
Blobfuse2

### Which OS distribution and version are you using?
Oracle Linux Server 8.6

### What was the issue encountered?
I have Oracle Linux VM on Azure that should take backup and push to Azure Storage account. This VM has 512GiB disk attached. I create LV with 100%FREE. I am using Blobfuse2 along with fuse3. There two directories /backup-cache and /backup. The problem is that /backup is getting full. I can see the backups are done in the blob storage and my expectation was /backup will get to 0 GiB after the backup is pushed. But it's not happening. I am using /etc/blobfuse2/streamingConfig.yaml.

### Have you found a mitigation/solution?
Not yet. We had to unmount /backup-cache and /backup. Clean it up and do the full backup.

### Please share logs if available.
stramingConfig.yaml

allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240
  direct-io: true

stream:
  block-size-mb: 0
  max-buffers: 0
  buffer-size-mb: 0
  file-caching: false

file_cache:
  allow-non-empty-temp: true
  path: /backup-cache/blobfuseCache
  timeout-sec: 18000
  max-size-mb: 100000

attr_cache:
  timeout-sec: 7200
  max-files: 5000000
  no-cache-on-list: true

azstorage:
  type: block
  account-name: <hidden>
  account-key: <hidden>
  endpoint: <hidden>
  mode: key
  container: backups
  max-retries: 5
  max-retry-timeout-sec: 900
  tier: none
  max-concurrency: 32

health_monitor:
  enable-monitoring: true
  stats-poll-interval-sec: 30
  process-monitor-interval-sec: 30
  output-path: /var/log

**Comment by ashruti-msft** [comment]
Hello, first of all you should not be using both stream and file_cache in your config file, I would suggest to use file_cache instead. Also, what is the /backup folder is it the mount directory for blobfuse2?

**Comment by SangharshMyCD** [comment]
Hi,
thank you for the response. Could you please clarify why both cannot be used? Is there a problem? 
/backup is mount directory for blobfuse2. 
![image](https://github.com/user-attachments/assets/1cf04e4e-6834-41b6-9cf6-e59a32ca6dd8)

**Comment by ashruti-msft** [comment]
Yes we only use one of the two components for transferring data , also stream is going to be deprecated in the future so its recommended to use file-cache instead.
Also, from your output of df I see that 1% is the use% and so what do you mean by backup is getting full? The same goes for the backup_cache directory. P.S: the mount directory does not occupy space on your local disk , its a virtual filesystem interface and shows the contents of your azure storage. Only when you go to read a file will we download it using file _cache.

**Comment by SangharshMyCD** [comment]
Thank you for the clarification. This means I have to remove following block from the streamConfig.yaml
stream:
block-size-mb: 0
max-buffers: 0
buffer-size-mb: 0
file-caching: false


The screenshot is after we unmount and cleaned that's why it shows 1%.  The below screenshot is when it was full, and we had to manually clean it up:

![image](https://github.com/user-attachments/assets/e403b58c-7eb8-4e21-b8ce-aafbe4daf331)

**Comment by SangharshMyCD** [comment]
Anything else I need to know apart from removing the stream block from the streamConfig.yaml?

**Comment by ashruti-msft** [comment]
> Anything else I need to know apart from removing the stream block from the streamConfig.yaml?

Yes you will need to remove stream from components list in your config file.

**Comment by ashruti-msft** [comment]
Try running your tasks with the new configuration and let me know. Also, how many file handles are open when you check df -h of your mount?

**Comment by SangharshMyCD** [comment]
@ashruti-msft - here it is 
[root@vm-tmcnt-db-pr-01 ~]# df -h
Filesystem                               Size  Used Avail Use% Mounted on
devtmpfs                                  32G     0   32G   0% /dev
tmpfs                                     32G     0   32G   0% /dev/shm
tmpfs                                     32G  3.1G   29G  10% /run
tmpfs                                     32G     0   32G   0% /sys/fs/cgroup
/dev/mapper/rootvg-rootlv                 19G   12G  7.3G  62% /
/dev/mapper/rootvg-crashlv                10G  104M  9.9G   2% /var/crash
/dev/nvme0n1p1                           794M  323M  471M  41% /boot
/dev/nvme0n1p15                          495M  5.1M  490M   2% /boot/efi
/dev/mapper/backupcachevg-backupcachelv  503G   40K  478G   1% /backup_cache
/dev/mapper/u01vg-u01lv                   49G   18G   30G  37% /u01
/dev/mapper/swapvg-swaplv                 16G   16G     0 100% /mnt/swap
/dev/mapper/datavg-oraredologlv           49G  2.1G   45G   5% /db_rlog01
/dev/mapper/oralogvg-oramirloglv          49G  1.8G   45G   4% /db_mlog01
/dev/mapper/oralogvg-oraarchloglv        196G  4.5G  182G   3% /db_arch01
/dev/mapper/datavg-oracledatalv          885G  317G  524G  38% /db_data01
tmpfs                                    6.3G     0  6.3G   0% /run/user/54321
tmpfs                                    6.3G     0  6.3G   0% /run/user/1000
blobfuse2                                 98G   12K   98G   1% /backup

**Comment by ashruti-msft** [comment]
Ok so is blobfuse not taking up entire space now?

**Comment by SangharshMyCD** [comment]
No. For now we have removed stream block and monitoring the situation.

**Comment by SangharshMyCD** [comment]
As we have not been experienced the issue after removing the stream block. I am marking the issue resolved. Thanks for your help @ashruti-msft :)
