### ISSUE TITLE
Is it possible to mount NFS share under nested directory within blubfuse2 mount?

### ISSUE THREAD

**Issue by kamilzzz** [Azure/azure-storage-fuse#1500]
Unsupported scenarios section in blobfuse2 wiki limitation page says:
> Blobfuse2 does not support co-existence with NFS on same mount path. Behavior in this case is undefined.

What about scenario where I would like to mount NFS share to some directory under blobfuse2 mount?

For example:
`/data/blobfuse2` - blobfuse mount
`/data/blobfuse2/tmp` - NFS share mount

Is this scenario supported or behavior is undefined and this is discouraged?

**Comment by vibhansa-msft** [comment]
It is not advised to do this kind of intermixing as kernel can forward calls to only one filesystem at a time.
What is the objective here? If a container is mounted via blobfuse you are already connecting your storage account then why you want to mount a sub directory inside it using NFS.

**Comment by kamilzzz** [comment]
> It is not advised to do this kind of intermixing as kernel can forward calls to only one filesystem at a time.

Well, forwarding to only one filesystem at a time would be expected in my case. I would like all calls to `/data/blobfuse2/tmp` to be forwarded to NFS share.

> What is the objective here?

We're migrating COTS app and trying to get rid of local filesystem dependency. It looks like blobfuse2 could be good solution to our needs however application is using one directory under that mount path as its internal cache (ideally should be persisted between restarts though) where it issues a lot of writes (in some cases tens/or even hundreds per second) which adds up to huge amount of PutBlob/ListBlobs calls on the Storage Account.

**Comment by vibhansa-msft** [comment]
If you are using file-cache model for Blobfuse2 then these calls can be reduced as file will be uploaded to backend storage only when application closes the handle of the file. If application is executing open - read/write - close workflow then even having NFS may not help as that would also result into similar APIs to sync the data with storage. If file-cache timeout is set to higher value then next time application opens the same file there will be no network calls and file will be served from local disk cache only.

**Comment by kamilzzz** [comment]
> If application is executing open - read/write - close workflow then even having NFS may not help as that would also result into similar APIs to sync the data with storage.

Yes, it is executing write-close as it generates a bunch of small files per specific operation and stores them in the cache.
I agree it would result in similar API calls with NFS but my observation is NFS would typically result in lower latency compared to blobfuse and often operations on NFS shares are free (for example, for Azure Files NFS shares with Premium tier).

> If file-cache timeout is set to higher value then next time application opens the same file there will be no network calls and file will be served from local disk cache only.

In this specific scenario issue only about writes.

**Comment by vibhansa-msft** [comment]
If you incur less cost or get better performance with NFS,  you can just mount that folder/container with NFS itself and not involve blobfuse at all. Do you have any issue with that approach?

**Comment by kamilzzz** [comment]
Yes, with storing all the data on NFS there are some challenges regarding RPO/RTO for recovery and with cross-region replication as for example NFS Azure Files shares do not feature built in cross-region replication at all.

I see blobfuse supports symlinks, do you think it could be a viable solution to symlink that folder to NFS mounted under completely different mount point?

**Comment by vibhansa-msft** [comment]
As in you mount blobfuse and one of the folder inside that mount path is a symlink to some other drive (mounted using standard file system like ext3 or something). In theory this shall work, you can try that out.

**Comment by vibhansa-msft** [comment]
Closing this as there is open action item on blobfuse for this. Mounting using symlink you need to validate on your end.
