### ISSUE TITLE
debian 12 support

### ISSUE THREAD

**Issue by mike-england** [Azure/azure-storage-fuse#1510]
### Which version of blobfuse was used?
blobfuse2

### Which OS distribution and version are you using?
Debian 12

### What was the issue encountered?
I'm trying to install blobfuse2 into Debian Bookworm (version 12).  I've found that it isn't in the supported distribution list (https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Supported-Platforms).  Is this in plan or possible to add to a roadmap?

I'm looking to use this from a docker container and many of those seem to use Debian as a base.

### Have you found a mitigation/solution?
Use debian 11

**Comment by souravgupta-msft** [comment]
Hi @mike-england. Thanks for reaching out. You can download the required binary from the [Debian 11 repo](https://packages.microsoft.com/debian/11/prod/pool/main/b/blobfuse2/) and install it in Debian 12.
I will discuss with my team about releasing in Debian 12.

**Comment by mike-england** [comment]
Fantastic, thanks.  If anyone else has the same problem, I've simply hard coded the VERSION_ID (and left the original "auto-detect" in for reference).  This seems to work fine
```
RUN ID=$( grep "^ID=" /etc/os-release | cut -d '=' -f 2 | tr -d '"') && \
    VERSION_ID=$(grep "^VERSION_ID=" /etc/os-release | cut -d '=' -f 2 | tr -d '"') && \
    VERSION_ID=11 && \
    URL="https://packages.microsoft.com/config/${ID}/${VERSION_ID}/packages-microsoft-prod.deb" && \
    curl $URL -o /tmp/packages-microsoft-prod.deb && \
    dpkg -i /tmp/packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y libfuse3-dev fuse3 blobfuse2 && \
    rm /tmp/packages-microsoft-prod.deb
```

**Comment by vibhansa-msft** [comment]
@mike-england  Thanks for sharing the steps, hope this helps many customers who are trying to achieve something similar.
