### ISSUE TITLE
blobfuse and storing PNG files as blobs - support "Content-Type" property

### ISSUE THREAD

**Issue by irinilu** [Azure/azure-storage-fuse#152]
Hello Team
I am using blobfuse and storing PNG files as blobs. The content type is   'contentType': 'application/octet-stream' and not 'contentType': 'image/png'
As needed in order for the browser to display the PNG blob directly. Is there a way to correct this?

Thank you for the help

**Comment by seguler** [comment]
This is currently not supported, but I think we should. Marking this as an enhancement.

**Comment by fmt** [comment]
Both CLI and AZCopy support guessing the content-type based on the extension, this would be a very welcomed enhancement

**Comment by cyptus** [comment]
@vibhansa-msft could you have a look into this? blob storages with static websites do really need this

**Comment by vibhansa-msft** [comment]
We have this feature request in our backlog will evaluate and update.

**Comment by elabbarw** [comment]
I have been having this issue with CSS files as well. Have to go into Storage Explorer to change the MIME type every time the file is uploaded.

**Comment by cyptus** [comment]
we do currently run a script to guess the type by extension for this, but this requires additional http requests after upload which results in poor performance.

**Comment by AmpliNet** [comment]
Hello, i need implement more extensions lib for ,map, .js and correct problem with regular names in txt extensions, see this problem when publish site by gatsyb.

![image](https://user-images.githubusercontent.com/51324273/115403904-35e7a400-a1c3-11eb-86f7-0589ad586e09.png)

all applications/octetstream have problem to open in static site azure blobs.

How i edit e recomplile new dictioray for solve this questions ?

Tanks Igor.

**Comment by vibhansa-msft** [comment]
You can pull the latest code and see the table of file extension to content-type mapping in cpplite/src/blob/blob_client.cpp file.

**Comment by NaraVen** [comment]
The latest blobfuse 1.3.7 is setting this correctly, so I am closing this one.
