### ISSUE TITLE
MSI resid authentication 500 error: DefaultIdentity is null

### ISSUE THREAD

**Issue by Mmdixon** [Azure/azure-storage-fuse#1526]
### Which version of blobfuse was used?
`blobfuse2 version 2.3.2`

### Which OS distribution and version are you using?
`Ubuntu 18.04.5 LTS`

### What was the issue encountered?
`Error: failed to initialize new pipeline [failed to authenticate credentials for azstorage]`

### Have you found a mitigation/solution?
Use `appid` instead of `resid`

### Please share logs if available.
```
Wed Sep 25 00:14:28 UTC 2024 : blobfuse2[72905] : [/blob2/cache] LOG_DEBUG [utils.go (156)]: SDK(Authentication) : WARNING: Azure ML doesn't support specifying a managed identity by resource ID
```
```
GET http://127.0.0.1:9138/metadata/managedidentity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 500 Internal Server Error
--------------------------------------------------------------------------------
{
  "error": {
    "code": "Internal Server Error",
    "message": "DefaultIdentity is null",
    "innerError": null,
    "details": null
  }
}
--------------------------------------------------------------------------------
To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#managed-id]
```
I noticed the log warning that AML doesn't support managed identity by resource ID, but by app ID it is working. Was wondering when `resid` would be supported or is the `DefaultIdentity is null` error about `resid` can only be used with a certain env setup?

**Comment by vibhansa-msft** [comment]
Default mode for MSI based authentication for Blobfuse is using appid only, so if appid is working for you stick to that.

**Comment by vibhansa-msft** [comment]
ML workspace with resid is not supported by the authentication library itself. Closing this here as there is nothing, we can do to support this from Blobfuse end. From the warning it appears even the ML workspace does not support this as of now. You need to reach out to Azure ML workspace support for this.

**Comment by vibhansa-msft** [comment]
Here is a link to code where identity library throws this error back:

https://github.com/Azure/azure-sdk-for-go/blob/e75eee983c413f49e599ac1b14eb0b31b89ffccf/sdk/azidentity/managed_identity_client.go#L387C1-L409C2
