### ISSUE TITLE
blobfusev2 RHEL7.9

### ISSUE THREAD

**Issue by paradoxicalNL** [Azure/azure-storage-fuse#1528]
Hi, I want to use blobfusev2, but I am seeing 1 possible issue, my platform is not supported:

https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Supported-Platforms
RHEL7.9 is not lised.
Other RHEL 7 versions are supported, RHEL7.9 is the final RHEL7 minor release. I'm guessing this page is not up-to-date or it is really not suported? Thanks

**Comment by vibhansa-msft** [comment]
We will take a work item to correct our documentation around this. Thanks for bringing this to our notice.
