### ISSUE TITLE
Service SAS doesn't work

### ISSUE THREAD

**Issue by asorrin-msft** [Azure/azure-storage-fuse#153]
Currently, only Account SAS tokens work with SAS support.  We should support service SAS tokens as well, as long as they're at the container-level.  Once this is done, we also need to document the min requirements for SAS tokens to work with blobfuse.

**Comment by Tatsinnit** [comment]
👍 to this, thanks.

If I may add something to this:
- Error message which gets returned is also little misleading so might as well make it more informative.

**Comment by seguler** [comment]
Fixed!

**Comment by hasterhorb** [comment]
Hi, im trying to mount a blob storage with a single container service SAS **associated with a policy**, but it does not work.

Is it supposed to work?
