### ISSUE TITLE
Unable to mount the Directory under docker container with blobfuse2 using the Docker Desktop and Ubuntu Ubuntu 22.04.5 LTS image

### ISSUE THREAD

**Issue by rahulshrivastava-eaton** [Azure/azure-storage-fuse#1534]
Error : 
Unable to start blobfuse. Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key/sas token/OAuth access token and container name. errno=60
Unable to start blobfuse due to authentication or connectivity issues. Please check the readme for valid auth setups.

**installation steps 👍** 

```shell
sudo wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb --no-check-certificate
sudo dpkg -i packages-microsoft-prod.deb

sudo cat <<EOF > /etc/apt/apt.conf.d/proxy.conf
Acquire::https::Verify-Peer "false";
Acquire::https::Verify-Host "false";
EOF

sudo apt-get update
sudo apt-get -y --no-install-recommends install blobfuse
sudo apt-get install libfuse2
```
 
blobfuse.cfg file details 
```shell
accountName *****************
accountKey Q*****************
containerName ***********************
``` 

Running blob fuse with below command , all paths cross checked and looks working : 
```shell
sudo blobfuse /home/rahuls/cov_idir --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/rahuls/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --file-cache-timeout-in-seconds=0
```

**Comment by vibhansa-msft** [comment]
You are using an older version of Blobfuse, Kindly migrate to Blobfuse2 latest version and validate. Feel free to reopen if the issue persists.
