### ISSUE TITLE
fusermount3: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf

### ISSUE THREAD

**Issue by rahulshrivastava-eaton** [Azure/azure-storage-fuse#1538]
I did not find the any documentation that how to set in user_allow_other in configuration file , can you please explain or provide any link where to add this flag in the file 
i am referring this config file https://github.com/Azure/azure-storage-fuse/blob/main/sampleBlockCacheConfig.yaml

**Comment by ashruti-msft** [comment]
To use allow_other in your config file you will have to edit your file /etc/fuse.conf first.
`sudo vim /etc/fuse.conf`
Uncomment the line `user_allow_other` and save the file. Now you should be able to use allow_other 

After this you can add allow_other to your config file :
`allow-other: true|false <allow other users to access the mounted directory - used for FUSE and File Cache>`
[Refer [AdvancedConfig](https://github.com/Azure/azure-storage-fuse/blob/main/setup/advancedConfig.yaml)]
or add the `-o allow_other` flag to your mount command

**Comment by rahulshrivastava-eaton** [comment]
ok thanks for the update you can close this

**Comment by recolic** [comment]
this is a stupid **bug**. The same script has been working for years, but fuse dev chose to break everyone's script to make themselves feel better.

If something should work but didn't, it's a bug. We should ask upstream to fix this bug. azure-storage-fuse is not the only victim.

**Comment by bhansalivikas** [comment]
fuse.conf is not something that blobfuse owns. It's a standard config file that comes packaged with libfuse and by default it does not allow you to mount with "allow_other" flag. Any customer willing to use allow_other has to go and enable it in fuse.conf manually. I do not see any breakage from blobfuse end here. If you upgrade or install new libfuse on your system it will ask whether you want to retain the old fuse.conf file or overwrite it.
Let me know if you need any help from blobfuse side here.

**Comment by bhansalivikas** [comment]
Also, not allowing allow_other by default has been the default setting in fuse.conf for many years, so I don't have any reason to believe it's a breaking change from their side.

**Comment by beedell-roke** [comment]
> I don't have any reason to believe it's a breaking change from their side.

@vibhansa-msft, the undermentioned would appear to indicate otherwise:

1. [`rpm-software-management/dnf5/issues/2471#issuecomment-3475940489`](https://github.com/rpm-software-management/dnf5/issues/2471#issuecomment-3475940489)

1. [`Inokinoki/QEFIEntryManager/issues/38#issuecomment-3886522110`](https://github.com/Inokinoki/QEFIEntryManager/issues/38#issuecomment-3886522110)
