### ISSUE TITLE
file cache directory is not empty

### ISSUE THREAD

**Issue by meono** [Azure/azure-storage-fuse#1539]
### Which version of blobfuse was used?
2.3.2

### Which OS distribution and version are you using?
Ubuntu 20.04.6 LTS

### If relevant, please share your mount command.
* through fstab
`/usr/bin/blobfuse2	/home/user/blobname	fuse3	defaults,_netdev,--config-file=/home/user/blobfuse2_config_blobname.yaml	0	0`

### What was the issue encountered?
I have been encountering issues with the file cache path:
`FileCache: config error /mnt/blobfuse2tmpblobname directory is not empty`
I assumed the /mnt folder would be for the temp disk and would be clear at every start up. However, the file cache path above persists. I noticed that the mount of temp disk (sdc1) fails:

```sdb       8:16   0   64G  0 disk 
├─sdb1    8:17   0 63.9G  0 part /
├─sdb14   8:30   0    4M  0 part 
└─sdb15   8:31   0  106M  0 part /boot/efi
sdc       8:32   0  2.4T  0 disk 
└─sdc1    8:33   0  2.4T  0 part 
```

I'm not sure if this is because the blobfuse2 gets processed faster than mounting the temp disk and the /mnt is no longer empty. Otherwise, I was able to mount the temp disk to a different path.

I'd appreciate if you have a suggestion for handling this and using temp disk as cache.

### Have you found a mitigation/solution?

Delete contents of /mnt and restart VM. I also noticed `cleanup-on-start` flag on [wiki](https://github.com/Azure/azure-storage-fuse/blob/42b3b19b42dbe36e5b37e7b4d81115c6a319b277/TSG.md?plain=1#L230). However, both of these still end up using VM disk and not temp disk for file cache.

### Please share logs if available.

**Comment by ashruti-msft** [comment]
Just to confirm I understand correctly you are directing the tempcache path to a disk attached to your vm but you do not see blobfuse using that disk but instead using the vm disk? 
We have an open PR to fix this issue already and hope to roll this fix out soon.
Regarding the flag you discovered `cleanup-on-start`, this will help you to mount blobfuse2 without having to handle clearing out the cache manually and hence you should not encounter directory not empty error.

**Comment by meono** [comment]
I have these two lines (among others) on `/etc/fstab`:

```
/dev/disk/cloud/azure_resource-part1	/mnt	auto	defaults,nofail,x-systemd.requires=cloud-init.service,_netdev,comment=cloudconfig	0	2
/usr/bin/blobfuse2	/home/user/blobname	fuse3	defaults,_netdev,--config-file=/home/user/blobfuse2_config_blobname.yaml	0	0
```

I expect the first line to mount the temp disk for an azure VM to `/mnt` and the second line to use a path under `/mnt` as tempcache for blobfuse2. As far as i can tell, the blobfuse2 path under `/mnt` gets established before the temp disk can be mounted. From there on, the temp cache gets stored on vm disk and doesn't get flushed with VM restart. 

We will continue to use the `cleanup-on-start` for now but it would actually help to not use the limited VM disk space.

I hope this makes it clearer and please let me know if there are logs i can provide to help.

**Comment by vibhansa-msft** [comment]
If /mnt is not yet mounted and blobfuse starts before that, it's not a blobfuse issue technically. Blobfuse will check the configured path and use it irrespective of who and how its mounted. If you wish to have a control over the mount and /mnt then better to write a script that mounts both in a proper order and use that script in fstab instead of mount command. There is no knob in blobfuse to wait for the tempcache to stablise.
