### ISSUE TITLE
files are not executable when using ADLS

### ISSUE THREAD

**Issue by hieuhoang** [Azure/azure-storage-fuse#1544]
We manually upgraded our blob container to Data Lake Gen2 to take advantage of hierarchical namespace.

The new blob has to be mounted with 
>azstorage:
>>type: adls

instead of
>azstorage:
>>type: block

The Unix file attribute in the ADLS mounts are not executable, whereas they are when mounting as block type: For example
#ls -l /mnt/ADLS-mount/loadnpz.py
**-rw-r-----** 1 hihoan hihoan 286 Oct 14 10:33 loadnpz.py

#ls -l /mnt/block-mount/loadnpz.py
**-rwxrwxrwx** 1 hihoan hihoan 286 Nov 29  2020 loadnpz.py

Is there a way to make the default ADLS files executable?

**Comment by vibhansa-msft** [comment]
If you are using HNS account then you need to set the permissions for file via portal. If you are using FNS (non-HNS) account then you can set the default permissions via blobfuse config.

**Comment by hieuhoang** [comment]
I'm using HNS. How do I set the permission via the portal? Do I need to set the permission for each file, or for all files?

**Comment by vibhansa-msft** [comment]
If the files are already there then you need to set for all existing files. If you set it to a folder then all new children will inherit the same. 
On portal navigate to the file you wish to change and then right click on it and choose "Manage ACL"
![Image](https://github.com/user-attachments/assets/1c4aff73-d6cb-4f1e-9890-fde74a1293de)

**Comment by vibhansa-msft** [comment]
> If the files are already there then you need to set for all existing files. If you set it to a folder then all new children will inherit the same. On portal navigate to the file you wish to change and then right click on it and choose "Manage ACL" ![Image](https://private-user-images.githubusercontent.com/64532198/377327665-1c4aff73-d6cb-4f1e-9890-fde74a1293de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDQyNjMsIm5iZiI6MTcyOTE0Mzk2MywicGF0aCI6Ii82NDUzMjE5OC8zNzczMjc2NjUtMWM0YWZmNzMtZDZjYi00ZjFlLTk4OTAtZmRlNzRhMTI5M2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA1NDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NDI1YTUxOGJiNDQ2OThjMDJkN2NlNTA1ZjQyMzFkMjljN2I5ZTVmZWIzODU5ZGI2NDJlM2YyOGFhZTZhZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IdTTokkzKW9iLwGNhhSe6Y4dRcj6d-iq4RAvl3nxIzQ)

Here you can set the "execute" permission.

**Comment by hieuhoang** [comment]
ah thanks. Is there plans to be able to do this from the Linux command line, eg. chmod +x [file]? 

It's any existing filesystem with thousands of files. We also have to be able to set ACL for new files without going to the portal

**Comment by vibhansa-msft** [comment]
After mounting using blobfuse you can use "chmod" command as well for HNS account. Not sure your current permissions will allow that or not hence suggested to go over portal but you can try blobfuse mount path first with standard chmod command.

**Comment by vibhansa-msft** [comment]
Try having "Storage blob data contributor" role.

**Comment by hieuhoang** [comment]
Ah thanks. 'Storage Blob Data Owner' role is required,  "Storage blob data contributor" is insufficient

**Comment by hieuhoang** [comment]
When editing an executable script with VS.code the executable permission resets every time the file is saved. (Using emacs doesn't do this)

Is there a way to preserve the file permission?

**Comment by vibhansa-msft** [comment]
Does it mean, even if you have "X" permission, if you edit the file and save it the permission is lost ?

**Comment by hieuhoang** [comment]
Yep

**Comment by hieuhoang** [comment]
fyi, the permission reset occurs with VS.code, vi, nano editors on Ubuntu 20.04 and 22.04,  bare metal and WSL.
It does not occur with emacs

The blobfuse2 driver is 
   blobfuse2/focal,now 2.3.2 amd64 [installed]

**Comment by hieuhoang** [comment]
If file permission can't be preserved when the file is edited, is there some way to have executable permission as default? It's a pain to have to do chmod +x every time a script is edited.

**Comment by vibhansa-msft** [comment]
As of now there is no way to set a default permissions kind of a thing, only workaround is to set the 'x' permission again after editing from your application/console. We are working on this item, and we are able to reproduce this locally.

**Comment by hieuhoang** [comment]
ah thanks. Good to know. I can wait for your fix

**Comment by vibhansa-msft** [comment]
This has been fixed in our latest version released yesterday (2.4.0). If you wish your preserve your acls/permissions during mount use a cli parameter "--preserve-acl".
