### ISSUE TITLE
what should be the value for BLOBFUSE_PLUGIN_PATH

### ISSUE THREAD

**Issue by bharath-krishna** [Azure/azure-storage-fuse#1561]
Hi

I am trying to use blobfuse2 and getting this error

`Sun Nov 10 23:26:27 UTC 2024 : blobfuse2[7537] : [] LOG_INFO [custom.go (54)]: No plugins to load, BLOBFUSE_PLUGIN_PATH is empty
Error: Sun Nov 10 23:26:28 UTC 2024 : blobfuse2[7549] : [] LOG_INFO [custom.go (54)]: No plugins to load, BLOBFUSE_PLUGIN_PATH is empty`

Could someone please help me what is the value I should set for `BLOBFUSE_PLUGIN_PATH`

I am using Linux machine inside kubernetes.

`uname -a
Linux job-dff67da509c1fa43-ndmrr 5.15.0-1073-azure #82-Ubuntu SMP Mon Sep 2 11:36:34 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by souravgupta-msft** [comment]
Hi @bharath-krishna. Thanks for reaching out. What version of blobfuse2 are you using because `BLOBFUSE_PLUGIN_PATH` is an unreleased feature. Please use the version [v2.3.2](https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.3.2).
