### ISSUE TITLE
Compile on Debian 9

### ISSUE THREAD

**Issue by difrancosimone** [Azure/azure-storage-fuse#158]
Hello!

i got an error compiling on Debian 9 64bit, on retry.h file.
The error is: 
retry.h:72:65: error: ‘pow’ was not declared in this scope
                     double delay = (pow(1.2, context.numbers()-1)-1);

i solved adding the

    #include <math.h>

line to the retry.h file at line 11.

I hope this might help.

**Comment by seguler** [comment]
I have also just encountered this issue on Ubuntu 17.10 as well

**Comment by seguler** [comment]
Thanks resolved!
