### ISSUE TITLE
Missing file system information

### ISSUE THREAD

**Issue by NillsF** [Azure/azure-storage-fuse#16]
Hi,

I've been trying out the blobFUSE adapter on multiple VMs, with multiple installations. One thing I keep running into (not always, but often) is that once I mount the blob container, my FS info dissappear. With that I mean that the mountpoint loses its access permissions (they appear as question marks) and ownership (also changes to question marks). I cannot access the mount point myself, but with sudo I can.

Some output:

**Mount point before mounting using FUSE**
```nilfranadmin@sshjumpabivnet:~$ sudo mkdir -p /datamnt/blobs
nilfranadmin@sshjumpabivnet:~$ ls /datamnt/ -la
total 12
drwxr-xr-x  3 root root 4096 Nov 17 16:07 .
drwxr-xr-x 24 root root 4096 Nov 17 16:07 ..
drwxr-xr-x  2 root root 4096 Nov 17 16:07 blobs
```

**Mount point after mounting using FUSE**
```
nilfranadmin@sshjumpabivnet:~$ sudo blobfuse /datamnt/blobs/ --tmp-path=/mnt/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=connection.cfg
nilfranadmin@sshjumpabivnet:~$ ll /datamnt/
ls: cannot access '/datamnt/blobs': Permission denied
total 8
drwxr-xr-x  3 root root 4096 Nov 17 16:07 ./
drwxr-xr-x 24 root root 4096 Nov 17 16:07 ../
d?????????  ? ?    ?       ?            ? blobs/
nilfranadmin@sshjumpabivnet:~$ ls /datamnt/blobs
ls: cannot access '/datamnt/blobs': Permission denied
nilfranadmin@sshjumpabivnet:~$ sudo ls /datamnt/blobs
postdeploy.sh  post.sh  txt.txt
nilfranadmin@sshjumpabivnet:~$ sudo ls /datamnt
blobs
nilfranadmin@sshjumpabivnet:~$ sudo ls /datamnt -la
total 8
drwxr-xr-x  3 root root 4096 Nov 17 16:07 .
drwxr-xr-x 24 root root 4096 Nov 17 16:07 ..
drwxrwx---  2 root root 4096 Jan  1  1970 blobs

```
Also note that the date on the folder changes.

**Comment by seguler** [comment]
FUSE mounts the filesystem in user space, and only the user who mounts fuse can access the filesystem. In your case you run it via sudo, and only root can access the mountpoint.

If you intend to mount with root, and give access to all users, then use '-o allow_other option'.

If you intend to mount and access the filesystem with a non sudo user, then make sure that your user is part of the group 'fuse'. ```sudo addgroup <user> fuse```

**Comment by NillsF** [comment]
Ok, thx @seguler . The -o allow_other solved it for me, also for non sudo users.
