### ISSUE TITLE
[Request] Ability to mount as a specific user

### ISSUE THREAD

**Issue by icebrian** [Azure/azure-storage-fuse#160]
I understand chown & chmod are not supported, but may-be having the ability to mount a blob as a specific user will avoid issues other application might have with running certain dirs with 777 permission.

So the request in this case is the ability to mount the blod under a specific UID & GID, maintaining the permssions as 770. 

Ideally if also possible to mount with a speific default permssions, would also be usefull.

**Comment by seguler** [comment]
Can you not do this already ? Mount blobfuse under the user x, and you will get only user x being able to access the data with 770 permissions. 777 permissions only given if you mount with -o allow_other mode...

**Comment by icebrian** [comment]
Well I have been trying with a system user, namely "daemon" in ubuntu with "sudo -u daemon /usr/bin/blobfuse" but i've have many issues. First with lack of permssions under /mnt then the mount point becomes completely unusable with questions marks appearing on UID/GID,perms etc when doing a directory listing. CD'ing into mount point does not work. What I was suggesting is actually pass a cmd line parameters for "uid" & "gid" for the mount point to be mounted under.

**Comment by seguler** [comment]
This is not possible. The user mounting blobfuse MUST have read/write access to the cache directory. Either modify /mnt folder permissions ( I know it gets reset after reboot), or choose a different cache directory.. Perhaps a ramdisk for performance.
