### ISSUE TITLE
[Request] Ability to SetBlobTier between Hot/Cold

### ISSUE THREAD

**Issue by icebrian** [Azure/azure-storage-fuse#163]
I beleive it would be very interesting to be able to set the blob tier with may-be a specific command line to hot, cool or archive.

**Comment by seguler** [comment]
What about implementing this with an extended attribute ?

such as:
```xattr tier archive /blob/myfile```

**Comment by ivanignatiev** [comment]
Is there any update on it?

**Comment by francisco-noguera** [comment]
There is any update on this?

**Comment by NaraVen** [comment]
We haven't planned for this yet. As a virtual file driver, this may not necessarily fall under blobfuse.

**Comment by vibhansa-msft** [comment]
We will not be taking up this feature in blobfuse. However, we have recently previewed next generation of blobfuse and user can set default tier to be used to all uploaded files in blobfuse2.
