### ISSUE TITLE
No Build folder in azure-storage-fuse / mount.sh failing

### ISSUE THREAD

**Issue by sumitsar** [Azure/azure-storage-fuse#164]
I have downloaded\cloned azure-storage-fuse in the past and things used to work fine. I was able to mount Azure Blobs on Linux VMs pretty easily. However, since yesterday things seems to have broken. 

Yesterday, I cloned azure-storage-fuse using https://github.com/Azure/azure-storage-fuse.git and it downloaded the contents but with no 'build' folder. mount.sh looks for build folder as per the code.. 
```
....
cd $BLOBFS_DIR/build
./blobfuse $1 ....
```

However, there is no 'build' folder downloaded when I cloned it. Due to this the mount command is failing. 

Is there something I'm missing?

**Comment by seguler** [comment]
build folder gets created when you build the binaries. You do this by running the provided build script

```./build.sh```

**Comment by seguler** [comment]
Closing the issue - I assume it is fixed
