### ISSUE TITLE
Unable to mount Blob storage on VM

### ISSUE THREAD

**Issue by pavanchelvaraj** [Azure/azure-storage-fuse#165]
I have created a blob storage however I am unable to mount it on my linux vm. 

I have used the below documentation
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux

I get errors 
blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp --config-file=/root/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
length of base64 string is not an even multiple of 4
Creating blob client failed: errno = 1600

**Comment by asorrin-msft** [comment]
It looks like blobfuse is unable to convert the account key in /root/fuse_connection.cfg from a base 64 string into a byte array.  Could you check your connection file, and make sure that the account key is correct?  It should be something like this, just these three lines:

```
accountName myaccount
accountKey 2AE+/ajshdfLKAJSHUDIjksdfhkwejAUSIHD/asdhfoiasiaAISOIJDOJFLSD/askdfewiAASJDNFL+askdlfj==
containerName fusetest

```

The account key here is fake, but it should be the correct number of characters.  No whitespace or anything after the "==" in the account key, just a newline (\n).

**Comment by seguler** [comment]
Closing as no response
