### ISSUE TITLE
Compatibility with standard mount: allow account/container url as source device

### ISSUE THREAD

**Issue by jbgi** [Azure/azure-storage-fuse#168]
I'd like to use systemd to manage the blob container mount.
For this systemd requires to pass source device and mount point to `mount`, as such:
```
mount "https://<account>.blob.core.windows.net/[container]" /mnt/blofuse -t blobfuse -o --tmp-path=/mnt/blofusetmp,--config-file=/run/keys/blobfuse-credentials
```
(mount.blobuse is an alias to blobfuse)
Currently this does not work because blofuse accept only one "non-option" argument, the mount point.

**Comment by seguler** [comment]
I may not understand the mountd details here, but why is this any different than persisting the mountpoint in /etc/fstab ? We have a procedure for this here: https://github.com/Azure/azure-storage-fuse/wiki/2.-Configuring-and-Running#persisting

**Comment by jbgi** [comment]
overlooked that paragraph, sorry. Although it would be nice to be able to avoid creating a custom script for each particular mount. I will see what I can do with `mount.sh`.

**Comment by seguler** [comment]
cool! feel free to open a new issue for any further questions
