### ISSUE TITLE
Allow sas token for single container

### ISSUE THREAD

**Issue by jbgi** [Azure/azure-storage-fuse#169]
Currently blobfuse fails to mount if the SAS token was created for a single container, eg. via
`New-AzureStorageContainerSASToken -Name "Test" -Permission rwdl`
Error is 
` Unknown failure in container_exists.  No exception, but the container property object is invalid.  errno = 0.`
(with logs of #166)

**Comment by seguler** [comment]
Yes this is being tracked in #153 - it is a bug.
