### ISSUE TITLE
directory name different on rhel/6/prod/repodata/

### ISSUE THREAD

**Issue by ashitabh** [Azure/azure-storage-fuse#170]
While running "sudo yum install blobfuse --skip-broken", I am getting the following error on Redhat 6

https://packages.microsoft.com/rhel/6/prod/repodata/db46852dd9ac6c821a80c64eaf6ef04e71df10255ee0d792f36685bdac8db17f-fileli.sqlite.bz2: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"

When I checked the repo online the folders are different from what rpm is trying to install
https://packages.microsoft.com/rhel/6/prod/repodata/
and there is no file starting with name "db465......"

**Comment by seguler** [comment]
I am not sure about this, but looks like an issue with the repository... Why did you need to run with --skip-broken ?

**Comment by ashitabh** [comment]
without skip-broken , the error is as shown below
Error: Package: blobfuse-0.4-1.x86_64 (packages-microsoft-com-prod)
           Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
Error: Package: blobfuse-0.4-1.x86_64 (packages-microsoft-com-prod)
           Requires: libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
Error: Package: blobfuse-0.4-1.x86_64 (packages-microsoft-com-prod)
           Requires: libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
Error: Package: blobfuse-0.4-1.x86_64 (packages-microsoft-com-prod)
           Requires: libgnutls.so.28(GNUTLS_1_4)(64bit)
Error: Package: blobfuse-0.4-1.x86_64 (packages-microsoft-com-prod)
           Requires: libgnutls.so.28()(64bit)
Error: Package: blobfuse-0.4-1.x86_64 (packages-microsoft-com-prod)
           Requires: libgnutls.so.28(GNUTLS_2_10)(64bit)
Error: Package: blobfuse-0.4-1.x86_64 (packages-microsoft-com-prod)
           Requires: libc.so.6(GLIBC_2.14)(64bit)
 You could try using --skip-broken to work around the problem

**Comment by ashitabh** [comment]
i tried same steps on another VM ( same configuration ) , and it installed without issue .
It seems my current VM is having some issue not related to this tool
