### ISSUE TITLE
ARM32/64 support

### ISSUE THREAD

**Issue by rcarmo** [Azure/azure-storage-fuse#173]
It would be nice to have these pre-packaged for `armhf`(or similar) and `aarch64`.

**Comment by seguler** [comment]
What is the use case for that ? Is it Raspberry Pi ?

**Comment by seguler** [comment]
Ok - I don't think we'll be able to support this. We do not have access to any 32 bit devices on Azure (or do we ?). Could you instead build from source ? I'd be happy to help with that.

**Comment by seguler** [comment]
I've just updated the docs - we'll probably never going to ship binaries for any other platforms than x86. Closing this, but feel free to continue posting if you have any issues with building from source. Building from source should be possible on ARM platforms.

**Comment by noizo** [comment]
Since most cloud providers now have free tiers with impressive ARM machines, blobfuse for arm architecture is really needed. Glad You're working on next gen blobfuse. Any ttl? Or a preview maybe @vibhansa-msft  ❓

**Comment by andyzhangx** [comment]
shall we reopen this issue?

**Comment by vibhansa-msft** [comment]
new generation is still under development so will update once its in preview mode. Plan is to have next gen as a seperate repo as of now so no need to reopen this one here, we will add a backlog item to our next gen for this one.

**Comment by souravgupta-msft** [comment]
@andyzhangx, yes ARM is supported. We release ARM64 binaries in Ubuntu (22.04 and 24.04), RHEL 9.0 and Mariner (2.0 and 3.0).

**Comment by mweibel** [comment]
@souravgupta-msft would it be possible to release those binaries also to the apt/yum package repositories? Currently [Blobfuse2 installation](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Installation) documents only x86 are available and indeed when looking into the package list it's only in the amd64 list.

**Comment by souravgupta-msft** [comment]
Hi @mweibel. We do release Blobfuse2 arm64 binaries in apt/yum package managers for few distros. You can get the list from [here](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Supported-Platforms).
