### ISSUE TITLE
404 for https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb

### ISSUE THREAD

**Issue by AlexanderYukhanov** [Azure/azure-storage-fuse#174]
FYI, the server returns 404 for https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb

**Comment by seguler** [comment]
@szarkos could you help us with this issue ? Batch AI production service depends on this debian package.

**Comment by seguler** [comment]
This looks like it is resolved. @AlexanderYukhanov  can we close it ?

**Comment by seguler** [comment]
Resolved.
