### ISSUE TITLE
apt-get install blobfuse doesn't work anymore

### ISSUE THREAD

**Issue by NillsF** [Azure/azure-storage-fuse#18]
Hello,

I might be a temporary issue, but I am not able to install blobfuse via apt-get anymore.

I followed the instructions, and downloaded/loaded the microsoft packages information.

```
wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update -q

sudo apt-get install blobfuse -q -y
```

This results in inability to locate the package.

``` sudo apt-get install blobfuse
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package blobfuse
```

**Comment by seguler** [comment]
Can you post the output of the following commands here ? Is anything failing ? Can you try update without -q option ?

It works on my machine too.. I suspect one of these commands to configure the repo is failing. 

wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
 sudo dpkg -i packages-microsoft-prod.deb
 sudo apt-get update

**Comment by NillsF** [comment]
Hi,

I tried again (on a plain ubuntu 16.04 and on a data science VM ubuntu 16.04). It works on the plain ubuntu 16.04, but fails on the data science VM ubuntu 16.04. It used to work until yesterday.

Output of apt-get update/install without the quiet parameter.

```
nilfranadmin@testaptagain:~$ wget https://packages.microsoft.com/config/ubuntu/1                                                                                                                                                             6.04/packages-microsoft-prod.deb
--2017-11-22 15:03:22--  https://packages.microsoft.com/config/ubuntu/16.04/pack                                                                                                                                                             ages-microsoft-prod.deb
Resolving packages.microsoft.com... 13.80.10.205
Connecting to packages.microsoft.com|13.80.10.205|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2260 (2.2K) [application/octet-stream]
Saving to: ‘packages-microsoft-prod.deb.1’

packages-microsoft- 100%[===================>]   2.21K  --.-KB/s    in 0s

2017-11-22 15:03:22 (479 MB/s) - ‘packages-microsoft-prod.deb.1’ saved [2260/226                                                                                                                                                             0]

nilfranadmin@testaptagain:~$ sudo dpkg -i packages-microsoft-prod.deb

(Reading database ... 307162 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-1) over (1.0-1) ...
Setting up packages-microsoft-prod (1.0-1) ...
nilfranadmin@testaptagain:~$ sudo apt-get update
Get:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Ign:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Get:2 file:/var/nvidia-diag-driver-local-repo-384.66  InRelease
Ign:2 file:/var/nvidia-diag-driver-local-repo-384.66  InRelease
Get:3 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Get:4 file:/var/nvidia-diag-driver-local-repo-384.66  Release [574 B]
Hit:5 http://azure.archive.ubuntu.com/ubuntu xenial InRelease
Get:3 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Hit:6 http://azure.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:7 http://azure.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:8 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:9 http://packages.microsoft.com/repos/vscode stable InRelease
Hit:10 http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial InRelease
Get:4 file:/var/nvidia-diag-driver-local-repo-384.66  Release [574 B]
Hit:11 http://ppa.launchpad.net/x2go/stable/ubuntu xenial InRelease
Hit:12 https://packages.microsoft.com/repos/azure-cli wheezy InRelease
Ign:13 https://dl.bintray.com/sbt/debian  InRelease
Hit:15 https://dl.bintray.com/sbt/debian  Release
Reading package lists... Done
nilfranadmin@testaptagain:~$
nilfranadmin@testaptagain:~$ sudo apt-get install blobfuse -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package blobfuse
nilfranadmin@testaptagain:~$
nilfranadmin@testaptagain:~$

```

**Comment by seguler** [comment]
It seems you had added the wheezy repo for Azure CLI; where we don't have blobfuse available. Let me fix that..

**Comment by seguler** [comment]
Yeah sorry - I was wrong. It seems this is an Azure CLI only repo.. And somehow you are not able to install the repo https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod/ in your repo list....  It doesn't seem to appear in this list:

nilfranadmin@testaptagain:~$ sudo apt-get update
Get:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Ign:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Get:2 file:/var/nvidia-diag-driver-local-repo-384.66  InRelease
Ign:2 file:/var/nvidia-diag-driver-local-repo-384.66  InRelease
Get:3 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Get:4 file:/var/nvidia-diag-driver-local-repo-384.66  Release [574 B]
Hit:5 http://azure.archive.ubuntu.com/ubuntu xenial InRelease
Get:3 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Hit:6 http://azure.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:7 http://azure.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:8 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:9 http://packages.microsoft.com/repos/vscode stable InRelease
Hit:10 http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial InRelease
Get:4 file:/var/nvidia-diag-driver-local-repo-384.66  Release [574 B]
Hit:11 http://ppa.launchpad.net/x2go/stable/ubuntu xenial InRelease
Hit:12 https://packages.microsoft.com/repos/azure-cli wheezy InRelease
Ign:13 https://dl.bintray.com/sbt/debian  InRelease
Hit:15 https://dl.bintray.com/sbt/debian  Release
Reading package lists... Done

Any ideas why ?

**Comment by NillsF** [comment]
I have no idea why. It's linked to the data science it seems. Maybe @gopitk can help here?

**Comment by AlexanderYukhanov** [comment]
Deployment on Batch AI DSVM is broken as well.

**Comment by gopitk** [comment]
We just published a new version of Ubuntu DSVM image (went live a few hours ago) with the Fuse driver prebuilt and installed. Not sure why this issue was there in the previous version. Are you able try on the just released version of Ubuntu DSVM instance?

**Comment by AlexanderYukhanov** [comment]
trying

**Comment by AlexanderYukhanov** [comment]
2017/11/25 04:45:23 Executing 'sudo apt-get install blobfuse'
E: Unable to locate package blobfuse

**Comment by AlexanderYukhanov** [comment]
That's interesting i can install blobfuse on new DSVM by running 'sudo apt install blobfuse'.
But if i do
wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt install blobfuse
I am getting:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package blobfuse

Is https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb broken?

**Comment by seguler** [comment]
Can you try the following manual configuration instead ?

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-get update

**Comment by AlexanderYukhanov** [comment]
trying

**Comment by AlexanderYukhanov** [comment]
the manual configuration works

**Comment by AlexanderYukhanov** [comment]
So, there is /etc/apt/sources.list.d/microsoft-prod.list in fresh DSVM installation containing "deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main".
 sudo dpkg -i packages-microsoft-prod.deb deletes this file and doesn't add the required source anywhere.

**Comment by szarkos** [comment]
We have a new package available for Ubuntu 16.04 here: https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/p/packages-microsoft-prod/packages-microsoft-prod_1.0-3-xenial.deb

Can you please use this one and let me know if it works for you?

Thanks!

**Comment by AlexanderYukhanov** [comment]
Checked it yesterday on Ubuntu LTS and DSVM. Was working for me.

**Comment by seguler** [comment]
Thanks @szarkos ! @NillsF, resolved for you too ?

**Comment by AlexanderYukhanov** [comment]
It's not resolved yet, the last step is required - link packages-microsoft-prod.deb to packages-microsoft-prod_1.0-3-xenial.deb.

**Comment by szarkos** [comment]
The symlinks have been updated.  Please confirm that this is all fixed now.

**Comment by AlexanderYukhanov** [comment]
Works

Thanks,
Alex
________________________________

**Comment by seguler** [comment]
Great - thanks all - closing the issue
