### ISSUE TITLE
Package blobfuse-1.0.1-RC-preview-rhel74.rpm is not signed

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/azure-storage-fuse#180]
Hiya guys,

Mainly reporting this for tracking. Scenario is as follows: I use it in shell script and put `set e` on top then I will get this as an error reported to me when the `Package blobfuse-1.0.1-RC-preview-rhel74.rpm is not signed` this happens.

I have a work around for this by simply not putting `set e`, but mainly bringing down to your attention.

![image](https://user-images.githubusercontent.com/6233295/39792606-874669e6-5395-11e8-8dfd-5f7b13bc6f31.png)

**Comment by seguler** [comment]
Interesting - we got these packages signed... I wonder if they weren't signed.. In any case, I will release blobfuse 1.0.2 GA package this week.. Hopefully that won't have the same issue

**Comment by RyanLYZ** [comment]
I encountered the same issue.. My workaround is to specify the --nogpgcheck option to yum command

**Comment by seguler** [comment]
We have released the stable blobfuse package version 1.0.2.  Please re-open this issue if you encounter it again. Thanks !

**Comment by seguler** [comment]
I've tested this just now and I got blobfuse 1.0.2 installed. My RedHat VM is also a fresh one.. Not sure what's going on.. Are you still encountering this issue ? If so, I will open this issue for tracking purposes

**Comment by Tatsinnit** [comment]
💡 📓 ==> This seems like intermittent, unless I exactly boil down to what it is, (probably related not related i.e. might be to do with the setting) I am easy with whatever you want even though its closed, I am happy to track this personally, otherwise feel free to open it for tracking purpose. (aka I am easy either ways)
