### ISSUE TITLE
Not supports other regions

### ISSUE THREAD

**Issue by RyanLYZ** [Azure/azure-storage-fuse#181]
Hi, we're using China Azure and I found the service end point is hard coded in: 
azure-storage-cpp-lite/include/constants.dat

DAT(default_endpoint_suffix, ".core.windows.net")

[https://github.com/Azure/azure-storage-fuse/search?utf8=%E2%9C%93&q=windows.net&type=](url)

The current workaround is to clone the source -> change the setting -> build my local copy.

Hopefully this can be resolved if it is confirmed an issue.

**Comment by seguler** [comment]
We do support this. Just add blobEndpoint into connection.cfg as a new line:

e.g.
```
accountName myaccount
accountKey something==
blobEndpoint myaccount.blob.core.windows.net
```

**Comment by seguler** [comment]
I will keep this open as our documentation does not detail this.

**Comment by RyanLYZ** [comment]
Thanks for the prompt reply. Will stay tuned for the documentation update.

**Comment by seguler** [comment]
Take a look here: https://github.com/Azure/azure-storage-fuse/blob/dev/connection.cfg

I have added the variable into the template connection.cfg. Closing the issue. Let me know if you encounter issues.

**Comment by andyzhangx** [comment]
Hi @seguler I am trying to enable blobfuse flexvol on azure china, while in blobfuse flexvol, it does not use `connection.cfg`, instead, it's using env var, so would you add an env like BLOB_ENDPOINT?
