### ISSUE TITLE
Accented character support

### ISSUE THREAD

**Issue by rcarmo** [Azure/azure-storage-fuse#182]
I have a blocking issue with this, which is that it has trouble with filenames with accented characters in most encodings (UTF-8 and CP-1252 converted to UTF-8 via Samba or SFTP)

It would be nice if those filenames could be supported somehow, since right now they are mangled beyond recovery (or file creation errors out)

**Comment by seguler** [comment]
Sorry about this - it seems we missed responding to this. Can you send a simple repro for this issue ?

**Comment by rcarmo** [comment]
This was on a RHEL system at a customers', but I haven't been able to repro on Ubuntu or had the chance to try on RHEL again.

**Comment by seguler** [comment]
Ok let us know when you can repro - we'll reopen this then
