### ISSUE TITLE
Modification date check

### ISSUE THREAD

**Issue by dadebarr** [Azure/azure-storage-fuse#185]
Is it possible to add an option to compare a file's modification timestamp to the file's cache timestamp, so that blobfuse knows to fetch the file contents from the blob instead of the cache.  This check should be relatively quick, and it would help avoid confusing users (when older file contents get processed instead of the updated file contents).  Thanks for your consideration!

**Comment by seguler** [comment]
That makes sense to me! @AlexanderYukhanov @asorrin-msft did we other thoughts on this ? I recall we were going to make use of eTags for this ?

**Comment by AlexanderYukhanov** [comment]
I think etags will give slightly simpler solution if we will cache them in memory. modification time is always difficult to reason about when considering local/remote modification scenarios.

**Comment by syagev** [comment]
Is this being considered? It's the basic method of operation for any file synchronization client (such as OneDrive) so I was really surprised this isn't the current behavior. 

I guess you can even use the MD5 signature for read-only workloads, but anything is better than just blindly deleting from cache and redownloading on a timeout

**Comment by NaraVen** [comment]
This issue is now fixed in our latest release 1.3.4. Closing this one.
