### ISSUE TITLE
Unable to manipulate dir

### ISSUE THREAD

**Issue by andrelscarvalho** [Azure/azure-storage-fuse#186]
hello,

After install blobfuse, I'm able to mount a blob container and able to work with files.
But when trying to create a dir receive this error: cannot create directory ‘dir_name’: Input/output error
The command used to mount was: blobfuse /blobtst --tmp-path=/mnt/resource/blobfusetmp  --config-file=/etc/fuse/connection.cfg -o allow_other

Am I doing something wrong?

Thanks,
André

**Comment by seguler** [comment]
All looks good in the command. Can you share the logs with us after remounting it with DEBUG logs on ? See: https://github.com/Azure/azure-storage-fuse/wiki/5.-Logging

Also could you test this with the user you have mounted blobfuse ? So use the same user for creating a directory.

**Comment by andrelscarvalho** [comment]
Forgot to mention, this is a RedHat 7.3
Mounted again with this command:  blobfuse /blobtst --tmp-path=/mnt/resource/blobfusetmp --config-file=/etc/fuse/connection.cfg -o --log-level=LOG_DEBUG

Tried to create a dir and got this:

Jun 07 09:23:34 server1 blobfuse[2440]: Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 349:
Jun 07 09:23:35 server1 blobfuse[2440]: Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 349:
Jun 07 09:23:37 server1 blobfuse[2440]: Function azs_readdir, in file /home/seguler/azure-storage-fuse/blobfuse/directoryapis.cpp, line
Jun 07 09:23:37 server1 blobfuse[2440]: Function azs_readdir, in file /home/seguler/azure-storage-fuse/blobfuse/directoryapis.cpp, line
Jun 07 09:23:37 server1 blobfuse[2440]: Function list_all_blobs_hierarchical, in file /home/seguler/azure-storage-fuse/blobfuse/utilitie
Jun 07 09:23:42 server1 blobfuse[2440]: Function list_all_blobs_hierarchical, in file /home/seguler/azure-storage-fuse/blobfuse/utilitie
Jun 07 09:23:42 server1 blobfuse[2440]: Function azs_readdir, in file /home/seguler/azure-storage-fuse/blobfuse/directoryapis.cpp, line
Jun 07 09:23:51 server1 blobfuse[2440]: Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 349:
Jun 07 09:23:51 server1 blobfuse[2440]: Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 349:
Jun 07 09:23:51 server1 blobfuse[2440]: Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 391:
Jun 07 09:23:51 server1 blobfuse[2440]: Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 449:
Jun 07 09:23:51 server1 blobfuse[2440]: Function azs_mkdir, in file /home/seguler/azure-storage-fuse/blobfuse/directoryapis.cpp, line 6:
Jun 07 09:23:51 server1 blobfuse[2440]: Failed to upload zero-length directory marker for path /tst to blob tst.  errno = 400.
Jun 07 09:23:51 server1 blobfuse[2440]: Failed to map storage error code 400 to a proper errno.  Returning EIO = 5 instead.

**Comment by seguler** [comment]
I can't make sense of what the problem here is.. Could it be you are using a premium storage account ? Can you upload any files ? Are you using SAS token or the key to authenticate ?

**Comment by andrelscarvalho** [comment]
Yes, I am using premium storage account.
Yes, I can upload any files (those ones I've tried, at least).
I'm using key to authenticate.

**Comment by andrelscarvalho** [comment]
I just realized that although I can copy files to blob they "disappear" after some time (few minutes)...

**Comment by seguler** [comment]
Sorry I did not clarify in my previous message - blobfuse does not support premium accounts. Or said differently, premium accounts do not support block blobs, whereas blobfuse uses block blobs... This is not mentioned anywhere in our documentation... I will get the docs updated. Sorry for all this trouble.

**Comment by andrelscarvalho** [comment]
I got it. No problem at all. Thank you for the information.

**Comment by NaraVen** [comment]
Blobfuse supports Premium accounts of BlockBlobStorage. It does not support Premium accounts of type Storage V1 or V2 or FileStorage. Blobfuse only supports block blobs and only Premium accounts of kind BlockBlobStorage allows block blobs.
