### ISSUE TITLE
Metatada markers interfere with Static Websites and other tools

### ISSUE THREAD

**Issue by rcarmo** [Azure/azure-storage-fuse#191]
I'm testing the [Static Websites preview](https://youtu.be/LFFCokEONvo?t=13m41s), and if I create a folder inside the  `$web` container using `blobfuse` and try to access it from a browser I get a zero-byte download instead of that folder's `index.html`.

I've set up a test case like so:

```
- $web
    +- index.html
    +- subfolder (created with Storage Explorer)
    |   +- index.html
    +- fusefolder (created with blobfuse)
        +- index.html
```

If I access `http://foobar` and `http://foobar/subfolder` I get the correct result, but if I try to access `http://foobar/fusefolder` I get a zero-byte download.

I've verified this result using `curl` (hostname redacted to `foobar`):

### subfolder

```
$ curl -v http://foobar/subfolder
*   Trying 13.71.200.245...
* TCP_NODELAY set
* Connected to foobar (13.71.200.245) port 80 (#0)
> GET /subfolder HTTP/1.1
> Host: foobar
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 21
< Content-Type: text/html
< Last-Modified: Mon, 11 Jun 2018 18:01:05 GMT
< Accept-Ranges: bytes
< ETag: "0x8D5CFC54D44E814"
< Vary: Origin
< Server: Windows-Azure-Web/1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: 01a96d79-a01e-0025-10b0-05fcb3000000
< x-ms-version: 2018-03-28
< Date: Sat, 16 Jun 2018 20:25:21 GMT
< 
<H1>Hello World</H1>
* Connection #0 to host foobar left intact
```

### fusefolder

```
$ curl -v http://foobar/fusefolder
*   Trying 13.71.200.245...
* TCP_NODELAY set
* Connected to foobar (13.71.200.245) port 80 (#0)
> GET /fusefolder HTTP/1.1
> Host: foobar
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type: application/octet-stream
< Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
< Last-Modified: Sat, 16 Jun 2018 20:10:30 GMT
< Accept-Ranges: bytes
< ETag: "0x8D5D3C535942C17"
< Vary: Origin
< Server: Windows-Azure-Web/1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: 9cdc7a81-701e-002c-62af-05e63d000000
< x-ms-version: 2018-03-28
< Date: Sat, 16 Jun 2018 20:21:59 GMT
< 
* Connection #0 to host foobar left intact
```

The `Content-MD5` header matches the blob info for the metadata marker:

<img width="543" alt="screen shot 2018-06-16 at 21 26 54" src="https://user-images.githubusercontent.com/392683/41502178-11bc0386-71ac-11e8-8895-217f249eac45.png">

This might ordinarily be construed as a bug on Static Websites, but:

* There _is_, to all intents and purposes, a zero-byte file that matches the folder, and server behaviour when two items match the same URI is... undefined, at best (because it puts into question the entire definition of URI in the first place)
* I've had issues with other tools that access Azure Storage directly and appear to "trip over" these metadata markers because they match folder names (and that would not happen in a standard filesystem abstraction, which is what they take for granted)

An example of other tools affected by this issue is [Cyberduck/Mountain Duck](http://mountainduck.io), which cannot see any folders created with `blobfuse`:

<img width="526" alt="screen shot 2018-06-16 at 21 53 27" src="https://user-images.githubusercontent.com/392683/41502364-0ebb8964-71b0-11e8-900e-396cfc6de190.png">

I've tested removing the `fusefolder` marker, and in [Mountain Duck](http://mountainduck.io) it actually removes the _folder_ from the storage account and leaves the metadata marker (which is likely a result of the folder being listed first in API results, but an unexpectedly destructive behaviour).

I have also tested [Expandrive](https://www.expandrive.com) with similar results - it listed `fusefolder`as a zero-byte file and did not display the folder, and it crashed when I attempted to remove the marker.

Since `blobfuse` is quite likely to be used in site publishing pipelines or in conjunction with other tools like the above, I think it is best this is fixed, ideally by removing the metadata markers altogether.

**Comment by mirobers** [comment]
Thanks for reporting this! It's an unintended consequence for sure. We'll consider what the best fix is. Thanks also for your analysis, this is very helpful.

**Comment by rcarmo** [comment]
No problem. I took a look at the code and my initial reaction was that changing the markers to be _inside_ the folder (i.e., `folder/.blobfuse`) might work and render them harmless to most tools, but I’m not sure they’re needed at all (and the tools I mentioned deliver equivalent functionality without any extra markers...)

**Comment by mirobers** [comment]
Without a marker of some kind, directory creation will not be persistent until a file is written into the directory. And when all files are removed, the directory would vanish. So a marker is necessary to maintain basic filesystem behavior.

**Comment by rcarmo** [comment]
Most of the other tools I use sustain the illusion of an empty directory on the client side. Either way, I suggest moving the marker inside the directory as a .dotfile so that it does not clash with the actual directory.

**Comment by seguler** [comment]
I like your idea (in fact that is what we used to have) but now this directory marker scheme is crucial for us as an upcoming service feature depends on this functionality. Stay tuned..

**Comment by rcarmo** [comment]
As long as I can get both static web sites and third party tools to work (I have a couple of partners who use similar tooling)...

**Comment by rcarmo** [comment]
Any update on this? I've come across this a few times myself on customers, and my colleagues (and customers) now reach out to me because they Google for this functionality and find this issue...

**Comment by NaraVen** [comment]
Blobfuse is a virtual file driver. so the expectation is that the user types in the full url. http://foobar/fusefolder/index.html or you have a Url router.
From a blobfuse perspective it is not possible to interpret if the user is just asking to download a blob or trying to reach a webpage. So it is a better design for you to have a routeconfig that will translate http://foobar/fusefolder to http://foobar/fusefolder/index.html. 
Even if we eliminate the zero-byte markers for fodler, this issue will persist for you if there is a blob with the name. The solution lies in your config Url request mapping , therefore I am closing this issue.

**Comment by rcarmo** [comment]
Hello,

I’m sorry, but I disagree. We have competitive offerings from other providers that deliver on this functionality without any other services and any of the hassles, and as such we are now willfully placing ourselves at a disadvantage.

**Comment by vibhansa-msft** [comment]
Can you try the same test case with a ADLS based storage account with HNS (Hierarchical Name Space) enable. There 'directories' are treated just like a standard file-system directory and your case shall work fine.

**Comment by rcarmo** [comment]
As far as I understand that is not supported for Azure static web sites (or at least was not supported when ADLS2 storage went GA). I may be wrong on this, but there are other points to be made.

It also places us at a disadvantage price-wise (a quick check on the pricing pages shows higher transaction costs) and, again, is “fixing” this by using a different service - I am still adamant about this needing to be fixed in the client.

**Comment by NaraVen** [comment]
We have to keep it for empty folders. We can remove it for non-empty folders. Based on your requirement of rendering the index.html within the directory instead of the empty blob directory marker, leaving it on for empty folders will still work.  This will be a enhancement in future releases.

**Comment by vibhansa-msft** [comment]
For folder we do create an empty marker file and that's a way to identify existence of a folder in block blob account.  For ADLS Gen2 account no such special handling is there. As far as index.html is concerned, blobfuse acts a file-system driver and not a web server so if user asks for "/a/" it will try to download the folder marker only and not the index.html file within in. Closing this issue as this will not be supported.

**Comment by rcarmo** [comment]
Just for the record then, this means that customers will be unable to maintain Azure Static Web Sites via this solution.

**Comment by vibhansa-msft** [comment]
Blobfuse is a file-system driver and in any regular file-system if you wish to read index.html you need to provide fully qualified path for that file, giving the folder name will not work.

**Comment by rcarmo** [comment]
I don’t think you actually understood the issue here.

**Comment by rcarmo** [comment]
The issue was that accessing the path via HTTP was broken due to the directory markers inserted by blob fuse. 

Literally my second sentence: 

> if I create a folder inside the  $web container using blobfuse and try to access it from a browser I get a zero-byte download instead of that folder's index.html.

From Mar 26 2020 the discussion shifted towards the need to retain the empty folder marker, and it still prevents this kind of access from working.

**Comment by vibhansa-msft** [comment]
As you might be aware that block blob accounts in azure storage do not have a concept of folder (they exist virtually). On the other hand, blobfuse is a file-system driver and has to follow regular FS norms, which allows user to create a directory (and possibly and empty one). To support the concept of a folder (when user executes mkdir) blobfuse internally creates a file in storage container which is a special marker file (0 byte in size and containing meta info that it represents a folder). 
However, on Gen2 account this may not be true as they support concept of a folder at storage level itself.
As you can see to have FS compatibility, we need these special marker files and as of now there is no way around this.

**Comment by rcarmo** [comment]
To your point, the initial intent of this ticket was to try to raise the bar for our own, first-party tools. 

I understand the approach used but do not accept the compromise and limitations of it nor the statement that there is no workaround, since third-party tools (like Expandrive and Mountain Duck) do allow managing content in Azure blob storage (the standard kind).

**Comment by vibhansa-msft** [comment]
By "no workaround" I mean using blobfuse there is no workaround, as this has been day-1 design in here and many customers are already using this semantics of an market file. I do agree there are tools that work with directories in other ways, however I am not sure if any of those allow you to create an empty directory in container. Can you confirm that, if you are already aware of those tools?
