### ISSUE TITLE
Is performance of blob container mounted using blobfuse comparable to mounted Azure file-share?

### ISSUE THREAD

**Issue by jefjos** [Azure/azure-storage-fuse#192]
I was doing a performance analysis between Azure blob storage and Azure Files. I mounted both of them to a Linux VM. Ran a script to load the same set of files from both types of storage. While loading from Azure files took 27 secs, loading from Azure Blob storage took 5 minutes. The speed as Azure documentation for bpth is upto 60 MiB/s. I am using a cache folder with blobfuse.

**Comment by jefjos** [comment]
I believe we can use the caching feature for this.

**Comment by seguler** [comment]
Hi @jefjos 

Could you tell us more about the test ? Blobfuse aggresively caches data during an open call.. Hence if you are just opening files without reading them, blobfuse will trigger a full download from Blob storage, hence it will be slower than Azure Files... It is currently only optimized for workloads that read the entire data once opened.

**Comment by jefjos** [comment]
Thank you for the answer. It is quite insightful. I'm doing a performance analysis between reading from mounted Azure files and mounted Azure blob container. I have the same set of files on both types of storages. Reading these 500 files through an R script. Azure files - 27s. Blob-5 min.

**Comment by seguler** [comment]
That is unexpected - where is your cache directory located ? Is it on a Azure disk backed by standard storage ? Or is it the ephemeral drive mounted on /mnt drive ? What is the VM size ? You'll most likely have some bottleneck somewhere else than blobfuse.
