### ISSUE TITLE
blobfuse command hangs and provides no output

### ISSUE THREAD

**Issue by JonShelley** [Azure/azure-storage-fuse#194]
I am trying to use blobfuse 1.0.2 on Centos 7.4. I installed it using the install instructions for RHEL7. 

I have set the environment variables
export AZURE_STORAGE_ACCOUNT="https://someaccount.blob.core.windows.net/"
export AZURE_STORAGE_ACCESS_KEY=dN6JHzjE7yarJd3b7MimF4Vsb811I/31qIixBnPB387mThTGazM7K0uhR07H8DFOkC5As7MGh8fP6eU5EbNRRg== (Not actual key)

and as root I run

[root@mymachine resource]# blobfuse --version
blobfuse 1.0.2
[root@mymachine resource]# blobfuse /usr/local/blob --container-name=fuse --tmp-path=/mnt/resource/blobfusetmp

Any ideas how I can determine why it is hung? I have look /var/log/messages and I don't see anything in there.  I have also done an strace but don't see anything obvious

[root@mymachine user]# strace -f -ttt -p 56897
strace: Process 56897 attached
1530220916.047515 restart_syscall(<... resuming interrupted nanosleep ...>) = 0
1530220940.198134 clock_gettime(CLOCK_MONOTONIC, {867928, 313282614}) = 0
1530220940.198319 clock_gettime(CLOCK_MONOTONIC, {867928, 313461812}) = 0
1530220940.198410 clock_gettime(CLOCK_MONOTONIC, {867928, 313554711}) = 0
1530220940.198534 clock_gettime(CLOCK_MONOTONIC, {867928, 313673610}) = 0
1530220940.198614 clock_gettime(CLOCK_MONOTONIC, {867928, 313758409}) = 0
1530220940.198729 clock_gettime(CLOCK_MONOTONIC, {867928, 313867608}) = 0
1530220940.198811 clock_gettime(CLOCK_MONOTONIC, {867928, 313951507}) = 0
1530220940.198921 clock_gettime(CLOCK_MONOTONIC, {867928, 314063905}) = 0
1530220940.199022 clock_gettime(CLOCK_MONOTONIC, {867928, 314156404}) = 0
1530220940.199133 clock_gettime(CLOCK_MONOTONIC, {867928, 314285503}) = 0
1530220940.199227 clock_gettime(CLOCK_MONOTONIC, {867928, 314365302}) = 0
1530220940.199347 clone(strace: Process 56987 attached
child_stack=0x7fb77bce4e30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb77bce59d0, tls=0x7fb77bce5700, child_tidptr=0x7fb77bce59d0) = 56987
[pid 56987] 1530220940.199595 set_robust_list(0x7fb77bce59e0, 24 <unfinished ...>
[pid 56897] 1530220940.199621 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.199646 <... set_robust_list resumed> ) = 0
[pid 56897] 1530220940.199662 <... clock_gettime resumed> {867928, 314761398}) = 0
[pid 56987] 1530220940.199693 stat("/etc/resolv.conf",  <unfinished ...>
[pid 56897] 1530220940.199736 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.199758 <... stat resumed> {st_mode=S_IFREG|0644, st_size=114, ...}) = 0
[pid 56897] 1530220940.199795 <... clock_gettime resumed> {867928, 314870397}) = 0
[pid 56987] 1530220940.199819 open("/etc/hosts", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid 56897] 1530220940.199854 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.199880 <... open resumed> ) = 5
[pid 56987] 1530220940.199964 fstat(5,  <unfinished ...>
[pid 56897] 1530220940.199979 <... clock_gettime resumed> {867928, 314987595}) = 0
[pid 56987] 1530220940.200005 <... fstat resumed> {st_mode=S_IFREG|0644, st_size=306, ...}) = 0
[pid 56897] 1530220940.200025 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.200051 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0 <unfinished ...>
[pid 56897] 1530220940.200077 <... clock_gettime resumed> {867928, 315164693}) = 0
[pid 56987] 1530220940.200119 <... mmap resumed> ) = 0x7fb7829dc000
[pid 56897] 1530220940.200135 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.200158 read(5,  <unfinished ...>
[pid 56897] 1530220940.200178 <... clock_gettime resumed> {867928, 315273792}) = 0
[pid 56987] 1530220940.200207 <... read resumed> "127.0.0.1   localhost localhost."..., 4096) = 306
[pid 56897] 1530220940.200222 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.200250 read(5,  <unfinished ...>
[pid 56897] 1530220940.200268 <... clock_gettime resumed> {867928, 315356491}) = 0
[pid 56987] 1530220940.200292 <... read resumed> "", 4096) = 0
[pid 56897] 1530220940.200308 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.200331 close(5 <unfinished ...>
[pid 56897] 1530220940.200348 <... clock_gettime resumed> {867928, 315446490}) = 0
[pid 56987] 1530220940.200370 <... close resumed> ) = 0
[pid 56987] 1530220940.200420 munmap(0x7fb7829dc000, 4096 <unfinished ...>
[pid 56897] 1530220940.200439 clock_gettime(CLOCK_MONOTONIC, {867928, 315572389}) = 0
[pid 56987] 1530220940.200502 <... munmap resumed> ) = 0
[pid 56897] 1530220940.200533 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.200552 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP <unfinished ...>
[pid 56897] 1530220940.200582 <... clock_gettime resumed> {867928, 315665988}) = 0
[pid 56897] 1530220940.200615 clock_gettime(CLOCK_MONOTONIC, {867928, 315757987}) = 0
[pid 56897] 1530220940.200706 clock_gettime(CLOCK_MONOTONIC, {867928, 315832286}) = 0
[pid 56987] 1530220940.200782 <... socket resumed> ) = 5
[pid 56897] 1530220940.200807 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.200825 connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("168.63.130.16")}, 16 <unfinished ...>
[pid 56897] 1530220940.200874 <... clock_gettime resumed> {867928, 315939785}) = 0
[pid 56987] 1530220940.200953 <... connect resumed> ) = 0
[pid 56897] 1530220940.200968 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.201010 gettimeofday( <unfinished ...>
[pid 56897] 1530220940.201020 <... clock_gettime resumed> {867928, 316101883}) = 0
[pid 56987] 1530220940.201090 <... gettimeofday resumed> {1530220940, 201058}, NULL) = 0
[pid 56897] 1530220940.201122 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.201141 poll([{fd=5, events=POLLOUT}], 1, 0 <unfinished ...>
[pid 56897] 1530220940.201173 <... clock_gettime resumed> {867928, 316254781}) = 0
[pid 56987] 1530220940.201191 <... poll resumed> ) = 1 ([{fd=5, revents=POLLOUT}])
[pid 56897] 1530220940.201220 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.201238 sendmmsg(5,  <unfinished ...>
[pid 56897] 1530220940.201264 <... clock_gettime resumed> {867928, 316351880}) = 0
[pid 56987] 1530220940.201312 <... sendmmsg resumed> {{{msg_name(0)=NULL, msg_iov(1)=[{"\177\356\1\0\0\1\0\0\0\0\0\0\5https\32uchkgqla22puh"..., 75}], msg_controllen=0, msg_flags=MSG_EOR|MSG_FIN|MSG_SYN|MSG_CONFIRM|MSG_ERRQUEUE|MSG_BATCH|MSG_FASTOPEN|MSG_CMSG_CLOEXEC|0x1bca0000}, 75}, {{msg_name(0)=NULL, msg_iov(1)=[{"/\3\1\0\0\1\0\0\0\0\0\0\5https\32uchkgqla22puh"..., 75}], msg_controllen=0, msg_flags=MSG_OOB|MSG_PEEK}, 75}}, 2, MSG_NOSIGNAL) = 2
[pid 56897] 1530220940.201349 poll(NULL, 0, 4 <unfinished ...>
[pid 56987] 1530220940.201378 poll([{fd=5, events=POLLIN}], 1, 5000) = 1 ([{fd=5, revents=POLLIN}])
[pid 56987] 1530220940.202698 ioctl(5, FIONREAD, [154]) = 0
[pid 56987] 1530220940.202809 recvfrom(5, "\177\356\205\203\0\1\0\0\0\1\0\0\5https\32uchkgqla22puh"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("168.63.130.16")}, [16]) = 154
[pid 56987] 1530220940.202927 gettimeofday({1530220940, 202949}, NULL) = 0
[pid 56987] 1530220940.203006 poll([{fd=5, events=POLLIN}], 1, 4998) = 1 ([{fd=5, revents=POLLIN}])
[pid 56987] 1530220940.203076 ioctl(5, FIONREAD, [154]) = 0
[pid 56987] 1530220940.203157 recvfrom(5, "/\3\205\203\0\1\0\0\0\1\0\0\5https\32uchkgqla22puh"..., 65536, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("168.63.130.16")}, [16]) = 154
[pid 56987] 1530220940.203239 close(5)  = 0
[pid 56987] 1530220940.203333 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 5
[pid 56987] 1530220940.203436 connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("168.63.130.16")}, 16) = 0
[pid 56987] 1530220940.203521 gettimeofday({1530220940, 203547}, NULL) = 0
[pid 56987] 1530220940.203610 poll([{fd=5, events=POLLOUT}], 1, 0) = 1 ([{fd=5, revents=POLLOUT}])
[pid 56987] 1530220940.203675 sendmmsg(5, {{{msg_name(0)=NULL, msg_iov(1)=[{"{t\1\0\0\1\0\0\0\0\0\0\5https\0\0\1\0\1", 23}], msg_controllen=0, msg_flags=MSG_EOR|MSG_FIN|MSG_SYN|MSG_CONFIRM|MSG_ERRQUEUE|MSG_BATCH|MSG_FASTOPEN|MSG_CMSG_CLOEXEC|0x1bca0000}, 23}, {{msg_name(0)=NULL, msg_iov(1)=[{"\261{\1\0\0\1\0\0\0\0\0\0\5https\0\0\34\0\1", 23}], msg_controllen=0, msg_flags=MSG_OOB|MSG_PEEK}, 23}}, 2, MSG_NOSIGNAL) = 2
[pid 56987] 1530220940.203803 poll([{fd=5, events=POLLIN}], 1, 5000) = 1 ([{fd=5, revents=POLLIN}])
[pid 56987] 1530220940.204530 ioctl(5, FIONREAD, [98]) = 0
[pid 56987] 1530220940.204678 recvfrom(5, "\261{\201\203\0\1\0\0\0\1\0\0\5https\0\0\34\0\1\0\0\6\0\1\0\0\0\24"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("168.63.130.16")}, [16]) = 98
[pid 56987] 1530220940.204861 gettimeofday({1530220940, 204952}, NULL) = 0
[pid 56987] 1530220940.205068 poll([{fd=5, events=POLLIN}], 1, 4998) = 1 ([{fd=5, revents=POLLIN}])
[pid 56987] 1530220940.205232 ioctl(5, FIONREAD, [98]) = 0
[pid 56987] 1530220940.205432 recvfrom(5,  <unfinished ...>
[pid 56897] 1530220940.205517 <... poll resumed> ) = 0 (Timeout)
[pid 56987] 1530220940.205535 <... recvfrom resumed> "{t\201\203\0\1\0\0\0\1\0\0\5https\0\0\1\0\1\0\0\6\0\1\0\0\0\24"..., 65536, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("168.63.130.16")}, [16]) = 98
[pid 56897] 1530220940.205579 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.205598 close(5 <unfinished ...>
[pid 56897] 1530220940.205625 <... clock_gettime resumed> {867928, 320712932}) = 0
[pid 56987] 1530220940.205644 <... close resumed> ) = 0
[pid 56897] 1530220940.205669 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.205708 uname( <unfinished ...>
[pid 56897] 1530220940.205726 <... clock_gettime resumed> {867928, 320801431}) = 0
[pid 56987] 1530220940.205769 <... uname resumed> {sysname="Linux", nodename="mymachine", ...}) = 0
[pid 56897] 1530220940.205786 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.205814 madvise(0x7fb77b4e5000, 8368128, MADV_DONTNEED <unfinished ...>
[pid 56897] 1530220940.205854 <... clock_gettime resumed> {867928, 320920630}) = 0
[pid 56987] 1530220940.205869 <... madvise resumed> ) = 0
[pid 56897] 1530220940.205884 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 56987] 1530220940.205946 exit(0)   = ?
[pid 56897] 1530220940.206013 <... clock_gettime resumed> {867928, 321087328}) = 0
[pid 56987] 1530220940.206069 +++ exited with 0 +++
1530220940.206078 clock_gettime(CLOCK_MONOTONIC, {867928, 321214226}) = 0
1530220940.206150 clock_gettime(CLOCK_MONOTONIC, {867928, 321286326}) = 0
1530220940.206236 clock_gettime(CLOCK_MONOTONIC, {867928, 321376725}) = 0
1530220940.206294 clock_gettime(CLOCK_MONOTONIC, {867928, 321437824}) = 0
1530220940.206376 poll(NULL, 0, 8)      = 0 (Timeout)
1530220940.214534 clock_gettime(CLOCK_MONOTONIC, {867928, 329680733}) = 0
1530220940.214739 rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
1530220940.214836 rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
1530220940.214927 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
1530220940.215011 nanosleep({39, 0},

**Comment by zezha-msft** [comment]
Hi @JonShelley, thanks for reaching out!

I've logged this issue for investigation.

**Comment by seguler** [comment]
export AZURE_STORAGE_ACCOUNT="https://someaccount.blob.core.windows.net/"
needs to be the account name. In this case; "someaccount", it is not the full uri to the blob endpoint.

The reason blobfuse looks like it is hanging is because of the retries. It retries to connect like 100 times with backoffs… This is very aggressive because in the event of a failure/throttling from the service, we didn't want to fail to persist the data... But the downside is this use case - makes it hard to troubleshoot.

**Comment by JonShelley** [comment]
The storage account name was the actual account name. I changed it in the
issue because I didn’t want to share it.

Is there a way we can add a verbose option so that we can see why it is
taking so long.

Jon

**Comment by JonShelley** [comment]
It looks like I was using the URL for the storage (https://<Storage Account Name>.blob.core.windows.net) instead of just the storage account name. Once I did this it works as expected.
