### ISSUE TITLE
Sovereign Cloud documentation in the wiki

### ISSUE THREAD

**Issue by daweins** [Azure/azure-storage-fuse#199]
Can you please append the following documentation to page 2 of the wiki to reflect https://github.com/daweins/azure-storage-fuse/wiki/2.-Configuring-and-Running to clarify the blobEndpoint parameter for Sovereign Cloud usage once the pull request addings connectionGov.cfg has been merged?

Thank you,
-Dave-

---
## Sovereign Clouds
Blobfuse now supports Sovereign Clouds such as USGovernment (Fairfax), Azure China (Mooncake) and Azure Germany (Black Forest) via a new configuration option: "blobEndpoint". To access a sovereign cloud, you must supply the blobEndpoint parameter with the full blob endpoint for your storage account.   
Ex:

|Environment|blobEndpoint|
|-----------|------------|
|Azure USGovernment|&lt;youraccountname&gt;.blob.core.usgovcloudapi.net
|Azure China|&lt;youraccountname&gt;.blob.core.chinacloudapi.cn
|Azure Germany|&lt;youraccountname&gt;.blob.core.cloudapi.de

An example USGovernment configuration file is at: 
https://github.com/Azure/azure-storage-fuse/blob/master/connectionUSGov.cfg

**Comment by seguler** [comment]
Done - thanks!

**Comment by andyzhangx** [comment]
is the `blobEndpoint` can only be set inside a config file? How can I set this value via env var? We don't want to store secret in a config file, set it as env var would be safer, thanks. @seguler

**Comment by a139786** [comment]
You may want to man ps before you make that assumption about what’s safest. At least with a config file you can get the permissions right unless unless you can’t trust root. But if you can’t trust root, you’re hosed anyway.

HTH,
Barry

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andyzhangx** [comment]
anyway, can we add an identical `AZURE_BLOB_ENDPOINT` env?

**Comment by amnguye** [comment]
Hi Andy, Could you make a new issue/feature request for this and we will address it when we can. Thanks!
