### ISSUE TITLE
fuse: device not found

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-storage-fuse#20]
Hello

I try to use fuse inside of a docker container. However, when I install it / build it from source, it says

```
# ./mount.sh /var/blobfuse/storage
fuse: device not found, try 'modprobe fuse' first
```

To reproduce,  I'll share a Dockerfile.  I'm adding connection.cfg which is my private blob account information. Also, `mount.sh` is edit the place of blobfuse binary as `/azure-storage-fuse/blobfuse/build/blobfuse`.

Any ideas?

_Dockerfile_ 

```
FROM ubuntu:16.04
RUN apt-get update && apt upgrade -y 
RUN apt-get install wget -y
RUN wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get install apt-transport-https -y
RUN apt-get update
RUN apt-get install git -y
RUN git clone https://github.com/Azure/azure-storage-fuse/
RUN apt-get install pkg-config libfuse-dev cmake libcurl4-gnutls-dev libgnutls28-dev -y
RUN cd azure-storage-fuse && ./build.sh


RUN mkdir -p /mnt/blobfusetmp
RUN mkdir -p /var/blobfuse/build
RUN chmod 777 /var/blobfuse
WORKDIR /var/blobfuse

ADD connection.cfg .
ADD mount.sh .
RUN chmod +x mount.sh
# RUN ./mount.sh /var/blobfuse
```

**Comment by AlexanderYukhanov** [comment]
Hi,
The simplest solution is to mount the blob filesystem on the host and make it available in docker via "-v" option. e.g.
docker run  -v /var/blobfuse:/var/blobfuse ubuntu ...

Another option is to add access to /dev/fuse to the image for example as suggested here: https://github.com/moby/moby/issues/514

**Comment by TsuyoshiUshio** [comment]
I see, Thanks! :)

**Comment by andersjohansenange** [comment]
See https://github.com/docker/for-linux/issues/321 for an open issue that addresses this. No concrete suggestions for a solution though ;)

**Comment by dashesy** [comment]
@AlexanderYukhanov  mounting in the host and then `docker run -v /var/blobfuse:/var/blobfuse ubuntu` does not work. docker tries to mkdir the source path and then errors out because it exists.
