### ISSUE TITLE
connection.cfg file encryption

### ISSUE THREAD

**Issue by ghost** [Azure/azure-storage-fuse#200]
In connection.cfg file we mentioned account key and that is in plain text. Is there any way to encrypt this account key to keep secure.

![image](https://user-images.githubusercontent.com/22212578/42763670-65d84636-8931-11e8-9b41-a012632a5715.png)

**Comment by seguler** [comment]
Nope - doesn't support encryption. If you are looking to secure things, the best practice is to put these into environment variables and mount blobfuse using env variables. Only your user will be able to access these variables.

**Comment by vijayraje23** [comment]
@seguler Thanks for quick response. I found one workaround and it worked as per need. Please review it and let me know if this is the correct way to do it.

#**Create mount.sh file to encrypt and decrypt account key.**
cd /etc/vsftpd

#**generate a 2048-bit RSA key and store it in rsakey.txt.**
openssl genrsa -out .rsakey.txt 2048

**#generate encrypted account key using the RSA key and store it in accountkey.txt.**
echo "insert the actual key taken from azure portal" | openssl rsautl -inkey .rsakey.txt -encrypt >.accountkey.txt

**vi /etc/vsftpd/mount.sh**
#!/bin/bash
file=$(openssl rsautl -inkey .rsakey.txt -decrypt <.accountkey.txt)
echo "accountName blobftp" >/etc/vsftpd/.connection.cfg
echo "accountKey $file" >>/etc/vsftpd/.connection.cfg
echo "containerName blobfuseftp" >>/etc/vsftpd/.connection.cfg

blobfuse /blobftp/ftp/localuser --tmp-path=/mnt/blobfusetmp --config-file=/etc/vsftpd/.connection.cfg  -o allow_other -o nonempty
sleep 2
echo "#Decrypting AccountKey in .connection.cfg file"
echo "accountName blobftp" >/etc/vsftpd/.connection.cfg
echo "accountKey encrypted" >>/etc/vsftpd/.connection.cfg
echo "containerName blobfuseftp" >>/etc/vsftpd/.connection.cfg

**set this mount.sh script file to run after reboot. so now my .connection.cfg file looks like encrypted.**
![image](https://user-images.githubusercontent.com/22212578/42796793-1caaaa70-895a-11e8-815f-ee36c30d664d.png)



Thanks again !!!!

**Comment by seguler** [comment]
I am not sure what the aim here is. If some intruder has access to your machine/your user, they can decrypt this key just like you are doing. Right ?

So why is this different than simply leaving the key plain text, and putting a restricted ACL on the file so that only your user can read it.

**Comment by vijayraje23** [comment]
Hi Seguler,
The aim is keep account key encrypted for security.  Yes you are right if some intruder got access, they can decrypt this key. - is there any way to keep account key secure ?

We already put ACL restriction on this file.

**Comment by vijayraje23** [comment]
Thanks Seguler, But I was looking for encryption of account key to keep it secure. Thanks for your time.

**Comment by azvihar** [comment]
+1 for key/SAS token encryption support in connection.cfg. For blob fuse use in prod, i would prefer to save encrypted token in some file  rather than exporting env variable  with every reboot.

**Comment by seguler** [comment]
We would appreciate a PR for this feature!

**Comment by seguler** [comment]
For encryption, you still need to provide an encryption key and decryption key for blobfuse to read from the file. It is not any different than exporting the account key in environment variable, because if we encrypted than we'd need the decryption key in the environment variable...

Would it be easier if we simply supported Active Directory Authentication so that blobfuse uses MSI (Managed Service Identity) to authenticate with Storage ?

**Comment by adrian-ionescu** [comment]
@seguler, about the SAS token approach, do you have any plans to support live SAS token rotation (so that the blobfuse process doesn't need to be restarted)?

**Comment by NaraVen** [comment]
We will add the feature to check the config file and reestablish auth in our future releases. No ETA as of now.

**Comment by vibhansa-msft** [comment]
@adrian-ionescu : live SAS rotation has been added to version 1.3.5. When you wish to change the SAS token you can update the value in config file and do "kill -SIGUSR1 <pidof blobfuse>".

**Comment by vibhansa-msft** [comment]
We have posted preview release of blobfuse2 (next generation blobfuse) on github. it does have commands to encrypt a config file and mount a container using that encrypted file. It support passphrase based encryption so while mounting using encrypted file user need to pass on the passphrase or it can also be configured using an env variable.
