### ISSUE TITLE
Blobfuse does not output any logs

### ISSUE THREAD

**Issue by GrimSmiler** [Azure/azure-storage-fuse#202]
Hi!

After executing a command

```
blobfuse /home/ilya/ilya-test \
--tmp-path=/mnt/ramdisk/blobfusetmp \
-o attr_timeout=240 \
-o entry_timeout=240 \
-o negative_timeout=120 \
--container-name=ilyatest2 \
--log-level=LOG_DEBUG \
--file-cache-timeout-in-seconds=120
```

The login and password are stored in env vars: `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_ACCESS_KEY`

console goes silent and no console output is shown.
I checked `syslog` with `grep blob /var/log/syslog` and it is empty.

Where can i see the logs? i do not understand if the tool actually works or not.

OS = Ubuntu 18.04

Thanks in advance!

**Comment by seguler** [comment]
Blobfuse mount runs in deamon mode. Run ```echo $?``` to confirm that it is 0.

As for logs it should have printed something in /var/log/syslog. Let me try on 18.04 and confirm

**Comment by GrimSmiler** [comment]
While running the blobfuse it doesn't release the console:
![image](https://user-images.githubusercontent.com/5007741/43385809-0b10a85e-93e2-11e8-86a7-59d1e60a93b2.png)

running `echo $?` in another console returns `1`, so I assume something happened, although i have no idea how to debug this.

As for logs `grep blob /var/log/syslog` does not return anything.

**Comment by GrimSmiler** [comment]
Found the problem, i used my credentials for accountName, where i should have used storage account name and respective key and not my password

**Comment by HossamAmer12** [comment]
I am having the same issue:
When I run blobfuse I get this
$Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Unmounting blobfuse.
Unmounted blobfuse successfully

I am doing export for AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_ACCESS_KEY

and that's my command:

```
blobfuse ./blobs/blob-deeplm2/ --tmp-path=/mnt/cache-mtcairogroup2 -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 \
    --container-name=longsheng --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120
```


And no logs in the `/var/log/syslog`

Any ideas here, please?
