### ISSUE TITLE
Mount Fail - errno=No such file or directory

### ISSUE THREAD

**Issue by TShau** [Azure/azure-storage-fuse#203]
### What problem was encountered?

The mount to one of the blobs fails and the logs only show:
hpc-gitlab rsyslogd-3000: omazuremds error at connect(). errno=No such file or directory

### If relevant, please share your mount command.

blobfuse /mnt/Blob_backup/ --tmp-path=/mnt/resource/blobfusetmp  --config-file=/root/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG

**Comment by seguler** [comment]
Did the directory /mnt/Blob_backup exist ? The mount directory needs to be created before you try to mount.
