### ISSUE TITLE
Folders are created as files as well

### ISSUE THREAD

**Issue by mattsteele8** [Azure/azure-storage-fuse#204]
### If relevant, please share your mount command.

blobfuse ~/blobfuse --tmp-path=/mnt/resource/blobfusetemp  --config-file=/etc/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

**Comment by seguler** [comment]
Yes - I do agree it is annoying unfortunately. We had to implement it this way to align with other tools such as wasb hadoop driver, which is using this methodology as well as the new Azure Data Lake Storage Gen2 service. We wanted that you can upload data with blobfuse, read with wasb hadoop driver or ADLS Gen2 service. We believe this method will be wide spread among all tools in the future.

**Comment by mattsteele8** [comment]
thank you for the response. at least i know it isn't an issue
