### ISSUE TITLE
d_type not reporting for the mount root

### ISSUE THREAD

**Issue by sivagms** [Azure/azure-storage-fuse#207]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Ubuntu 14.04

### What problem was encountered?
Unable to use the blobfuse mount with Docker overlay2 driver
Error: "filesystem is formatted without d_type support, which leads to incorrect behavior. Backing filesystems without d_type support are not supported."

### Have you found a mitigation/solution?
No

### If relevant, please share your mount command.
standard blogfuse command

**Comment by seguler** [comment]
This may be a bug. It works fine in other fuse libraries.

**Comment by seguler** [comment]
This is now fixed in 1.0.3 release.
