### ISSUE TITLE
Access Tier Archive files are always present/listable

### ISSUE THREAD

**Issue by icebrian** [Azure/azure-storage-fuse#208]
This is not necessarily an issue but more of a discussion to understand what would make more sense. I have been testing Access Tiers in storage accounts, specifically using the new Datalifecycle Management feature. All is fine, but I have noticed that files that are under the Archive Access Tier are always present when listing (ls).

These files, even thou present are obviously not usable. If we try to do a change on the file we get an "Input/output error".

This again is expected, but my question or concern is whether or not files that are under Archive Tier, should actually show if in the directories?

Initially I had thought that anything under Archive tier would not show up, but am not sure if this is or not the best approach or even feasible.

Thanks,

**Comment by seguler** [comment]
Checkout your issue at #163 :) We planned to support archive tiers.
