### ISSUE TITLE
Not able to access blob with non-root user

### ISSUE THREAD

**Issue by devchop** [Azure/azure-storage-fuse#21]
Not able to mount/access blob with non-root user. 
Only able to mount blob with root user.

**Comment by seguler** [comment]
What is the error you're seeing with non-root users ?
Did you add your user to the fuse group ?
sudo addgroup <user> fuse

If this doesn't work, check that your user have permissions to execute fusermount... (ls -lart /usr/bin/fusermount)

**Comment by tsrik007** [comment]
Hi 
Is there any working solution for this issue ?

**Comment by seguler** [comment]
What's the exact error you're encountering ?

**Comment by seguler** [comment]
Closing this as the thread died

**Comment by GritBear** [comment]
Can we reopen it? What is the solution here?

**Comment by GritBear** [comment]
The error is simple, if I don't do sudo -i first, then all the file I blobfused shows permission denied when accessing them, even if their owner is the current local user.

**Comment by seguler** [comment]
use `-o allow_other` flag when mounting blobfuse. Or have you tried this already ?

**Comment by seguler** [comment]
This is documented here: https://github.com/Azure/azure-storage-fuse/wiki/2.-Configuring-and-Running#allow-other-users-or-root-access-to-the-mount

**Comment by kwikwag** [comment]
There is a problem that the [Azure storage guide for setting up blobfuse](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux) uses `sudo` to mount - though the setup was done for the current user. I posted an issue on those docs as well.
