### ISSUE TITLE
NFS unsupported by azure-storage-fuse

### ISSUE THREAD

**Issue by anhowe** [Azure/azure-storage-fuse#213]
### The Problem

Exporting a blobfuse folder as an NFS export does not fully work.  Files written from an NFS client can be seen for a short while by all NFS clients and also show up in the blobfuse temporary cache.  However, they are never uploaded to the storage account.  The blobfuse GC process eventually removes them.

A dump of the blobfuse debug logs shows that the ```azs_flush``` callback is never called from NFS, and since blobfuse only uploads the blob in the ```azs_flush```, this explains why the blob is never uploaded.  This is confirmed on the SSHFS Fuse driver mailing list (https://sourceforge.net/p/fuse/mailman/message/8901469/).  SSHFS calls ```flush``` from ```release```, and then uploads the file at the end of the ```release``` call: https://github.com/libfuse/sshfs/blob/master/sshfs.c#L2664-L2676.

### The Repro

1. Setup Blob Fuse on Ubuntu 18.04
2. Export the share using the "/etc/exports" and don't forget to add ```fsid=NNN``` where ```NNN``` can be any number (example: ```echo -e "\n${FUSE_BASE}   *(rw,fsid=1,sync,no_root_squash)" >> /etc/exports```) and restart nfs server.
3. mount using some NFS clients, and write some files.  The files will be seen by all NFS clients and the blobfuse cache, but never uploaded.  The blobfuse GC will kick in and eventually remove the files.

### Solution

A potential solution is following what was done by SSHFS and either call ```azs_flush``` from```azs_release```, or upload the blob in the release.

### Which version of the blobfuse was used?
Ubuntu 18.04 (https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb)

**Comment by seguler** [comment]
I have reproduced it. First of all, one needs to export with no_root_squash and no_all_squash to get bypass the NFS cache and hit blobfuse. When hitting blobfuse, it seems flush is not being called.

A similar issue was discussed here: https://sourceforge.net/p/fuse/mailman/message/8901482/

**Comment by anhowe** [comment]
Here is a template that implements an NFS server with a blob fuse driver: https://github.com/anhowe/scratch/tree/master/fuse-nas.

**Comment by vibhansa-msft** [comment]
We have recently previewed next generation of blobfuse and the flow of calling 'close' without calling 'flush' has been taken care of. If close is called without flush, blobfuse2 will upload the file to container, if it had any local changes.
