### ISSUE TITLE
blobfuse can establish connection to storage container

### ISSUE THREAD

**Issue by carlosporter** [Azure/azure-storage-fuse#216]
### Which version of the blobfuse was used?
blobfuse.x86_64 0:1.0.2-1
fuse-2.8.3-5.el6.x86_64

### Which OS (please include version) are you using?
Red Hat 6.9
kernel-2.6.32-696.28.1.el6.x86_64

### What problem was encountered?
I can mount the storage container locally without errors, however when I to access it's contents I get the following error:

df /netshares/testingblob1
df: `/netshares/testingblob1': Transport endpoint is not connected

A similar problem occurs when I try to copy data there:

cp -av /var/lib/rpm  /netshare/testingblob1
cp: cannot stat `/netshares/testingblob1/rpm': Software caused connection abort

### Have you found a mitigation/solution?
The process seems to work as expected when using and storage account and server in the same resource group and there is no outbound traffic filtering on the security group associated to the virtual machine

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
There is no syslog file on Red Hat 6.9, I already tried to enable logs using the option --log-level=LOG_DEBUG

### If relevant, please share your mount command.

blobfuse /netshares/testingblob1 --tmp-path=/mnt/resource/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/etc/blobfuse/connection_testingblob1.cfg

**Comment by seguler** [comment]
I am not sure what but you must have had some issues in your connection_testingblob1.cfg file. Blobfuse looks like it mounts, but it actually does not mount it successfully... Are you using a SAS token or SharedKey ?

**Comment by carlosporter** [comment]
Currently I'm using a sharedkey, the connection file is created using bash commands like the ones below...

```
STORAGE_ACCOUNT="mystorage"

RESOURCE_GROUP="somegroup"

# I save my storage account keys into a json file
az storage account keys list --account-name $STORAGE_ACCOUNT --resource-group $RESOURCE_GROUP | tee ${STORAGE_ACCOUNT}.keys.json

# Then I retrieve the 1st key
STORAGE_KEY1="$( jq .[0].value -r ${STORAGE_ACCOUNT}.keys.json )"

# Create an storage container
STORAGE_CONTAINER="blobshare$( date +%s ) "
az storage container create --account-name $STORAGE_ACCOUNT --name $STORAGE_CONTAINER

# and setup a custom name for the mount point/configfile
MOUNT_NAME="testingblob1"

# finally I create the config file...
echo -e "accountName ${STORAGE_ACCOUNT}\naccountKey ${STORAGE_KEY1}\ncontainerName ${STORAGE_CONTAINER}" | tee connection_${MOUNT_NAME}.cfg

Also, I'm currently filtering the traffic comming out of my virtual machine in Azure through the security group rules... is there any particular ports I need to open for outgoing connections for blobfuse to work properly?
```

**Comment by seguler** [comment]
It uses HTTP and HTTPS. By default it is HTTPS, so it is port 443

**Comment by carlosporter** [comment]
Ok, that checks out... I can see on the tcpdump output connections to and azure server "blob.XXXXXXXXXX.store.core.windows.net" to port 443, also port 80 and 443 were already open as they neded them to get the red hat updates.

What about the blobfuse log messages? My server is logging into /var/log/messages, but the documenation indicates that blobfuse logs into /var/log/syslog it this hardwired into blobfuse or it's supposed to talk to rsyslogd ?

I asked because I have tried the command below and I haven't found any debug messages on the server logs...

```
blobfuse /netshares/testingblob1 --tmp-path=/mnt/resource/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/etc/blobfuse/connection_testingblob1.cfg --log-level=LOG_DEBUG
```

**Comment by seguler** [comment]
Sorry for the late response on this. Do you still need assistance ? Hopefully by now the issue was resolved ?

Yes messages logs are fine. You should be able to see blobfuse logs there. Try this: `grep blobfuse /var/log/messages/` What do you see in there ? Perhaps we can see the error.

Have you also tried to mount blobfuse by handcrafting a config file ? I am suspecting that the echo `echo -e "accountName ${STORAGE_ACCOUNT}\naccountKey ${STORAGE_KEY1}\ncontainerName ${STORAGE_CONTAINER}" | tee connection_${MOUNT_NAME}.cfg` is the problem. For instance, does this put the account key in quotes ? There should be no quotes around the accountkey.

**Comment by xiangwums** [comment]
I am troubleshooting a similar issue. If you still have the issue, please enable the debug on RedHat 6.9 and reproduce the problem again, and paste the logs

vi /etc/rsyslog.conf

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.debug;mail.none;authpriv.none;cron.none                /var/log/messages


grep blobfuse /var/log/messages
