### ISSUE TITLE
Blobfuse with RHEL compatability

### ISSUE THREAD

**Issue by sivaemn** [Azure/azure-storage-fuse#219]
### Which version of the blobfuse was used?

Blobfuse 0.4.0
### Which OS (please include version) are you using?

RHEL 7.3 
### What problem was encountered?
Unable to perform SCP and truncate

### Have you found a mitigation/solution?
we are planning to upgrade to blobfuse 1.0.2 and would like to understand whether it can work with RHEL7.3

**Comment by seguler** [comment]
Yes Blobfuse supports RHEL 7.3. Please do upgrade. You are using a preview version (0.4) with bugs and issues.

**Comment by seguler** [comment]
@sivaemn sorry for my late response for this.
