### ISSUE TITLE
Question for connection.cfg for China Azure blob

### ISSUE THREAD

**Issue by nonokangwei** [Azure/azure-storage-fuse#22]
Does this support country sepcified azure, like China Azure?

**Comment by seguler** [comment]
Not at this moment. @JasonYang-MSFT @vinjiang can we implement the support for China and Gov clouds ?

**Comment by JasonYang-MSFT** [comment]
Only need to change suffix for different clouds at https://github.com/Azure/azure-storage-fuse/blob/master/azure-storage-cpp-lite/include/constants.dat#L7

And change the api-version number to match different clouds:https://github.com/Azure/azure-storage-fuse/blob/master/azure-storage-cpp-lite/include/constants.dat#L93

**Comment by arsenvlad** [comment]
In addition to China and Gov, would be great to make it extensible to support additional sovereign clouds like Azure Germany. Each separate cloud has it's own set of endpoints suffixes: 

- Azure US Government Developer Guide describing the AzureUSGovernment endpoints - https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-developer-guide 
- Azure Germany Developer Guide describing the AzureGermanCloud endpoints - https://docs.microsoft.com/en-us/azure/germany/germany-developer-guide
- Azure China 21Vianet Developer Guide describing the AzureChinaCloud endpoints - https://docs.microsoft.com/en-us/azure/china/china-get-started-developer-guide

Azure CLI 2.x uses constants for each "cloud" (e.g. az cloud list -o json) - https://github.com/Azure/azure-cli/blob/06cd9c2160c2f792a3af76f71fb55368c92cf0d6/src/azure-cli-core/azure/cli/core/cloud.py#L201

Azure PowerShell uses constants for each "environment" (e.g. Get-AzureRmEnvironment) - https://github.com/Azure/azure-powershell/blob/0e40f91f5eb32e6f5670d3bd7e08d8db37a6a5be/src/Common/Commands.Common.Authentication.Abstractions/AzureEnvironmentConstants.cs#L36 

Just for reference, Azure Python SDK provides multi-cloud support in https://github.com/Azure/azure-sdk-for-python/blob/master/doc/multicloud.rst defiled in here https://github.com/Azure/msrestazure-for-python/blob/b55563d1f88e0d34ed70288afc1c5f6729160703/msrestazure/azure_cloud.py#L181

**Comment by seguler** [comment]
I think I don't like the fact that this is defined in constants. Because one day this will be a very custom URL, and constants will not work. In my opinion, the user should be able to provide a url in connection.cfg like (https://mydomain.com/)

Any takers for this enhancement ? Would be great to get a PR on this :)

**Comment by seguler** [comment]
Sent a PR to add support for this. Could one of you test it ? I wasn't able to test it as I don't access to any of these clouds.

**Comment by seguler** [comment]
This is now merged into the dev branch. Let us know if you encounter any issues

**Comment by seguler** [comment]
Fixed in blobfuse 0.3
