### ISSUE TITLE
Linux - blobfuse mount just hang

### ISSUE THREAD

**Issue by kpmguser** [Azure/azure-storage-fuse#221]
### Which version of the blobfuse was used?
blobfuse 1.0.2

### Which OS (please include version) are you using?
Red Hat Enterprise Linux Server release 7.5 (Maipo)

### What problem was encountered?
blobfuse mount doesn't respond (hang)

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Sep 13 11:54:30 localhost blobfuse[94625]: list_blobs_hierarchical failed for the 1 time with errno = -853810000. 
Sep 13 12:14:39 localhost blobfuse[94625]: list_blobs_hierarchical failed for the 2 time with errno = -853810000. 
Sep 13 12:35:11 localhost blobfuse[94625]: list_blobs_hierarchical failed for the 3 time with errno = -1073532192. 
Sep 13 12:55:03 localhost blobfuse[94625]: list_blobs_hierarchical failed for the 4 time with errno = -1073532192. 
Sep 13 13:15:12 localhost blobfuse[94625]: list_blobs_hierarchical failed for the 5 time with errno = -1073532192. 
Sep 13 13:35:02 localhost blobfuse[94625]: list_blobs_hierarchical failed for the 6 time with errno = -1073532192. 
Sep 13 13:55:40 localhost blobfuse[94625]: list_blobs_hierarchical failed for the 7 time with errno = -1073532192. 
Sep 13 14:15:31 localhost blobfuse[94625]: list_blobs_hierarchical failed for the 8 time with errno = -1073532192. 

### If relevant, please share your mount command.
blobfuse /remote --tmp-path=/mnt/resource/blobfusetmp --config-file=/root/fuse_connection.cfg --use-https=true -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG

**Comment by seguler** [comment]
Hello there - 

Sorry for our late response. Unfortunately blobfuse has extensive retry mechanism so that you never lose data in the event of network problems. It automatically retry 25 times, that should take about 25 minutes... This is a problem we need to solve. @asorrin-msft 

It seems you have a problem in the fuse_connection.cfg file. Have you provided correct account name and key ? Are you following the following format ?
```
accountName myaccount
accountKey myKey==
containerName containername
```

**Comment by kpmguser** [comment]
Hello,

Sorry, but I cannot share the key and account due to security reasons, but I’ve double check key and account – it’s correct.

Just to mention – mount command works 2-3 weeks ago with same config file. We just unmounted and mounted it again but with different temp folder and its stucks..



Kind Regards,



Atanas Georgiev

Cloud Central Linux Managed Service
Senior Linux Support Engineer

KPMG IT Service OOD
Business Park Sofia
Building 4, Floor 4
Sofia 1766
Bulgaria

T +49 30 2068-1876

atanasgeorgiev@kpmg.com<mailto:atanasgeorgiev@kpmg.com>
GO-DL ITS Global Linux Support<mailto:go-dlitsgloballinuxs@kpmg.com>
GO-FM ITS Global Linux Support<mailto:go-fmitsgloballinuxs@kpmg.com>

www.kpmg.de<https://home.kpmg.com/de/de/home.html>
www.kpmg.com/socialmedia<https://home.kpmg.com/de/de/home/ueber-kpmg/social-media---kpmg.html>

**Comment by petit-lu** [comment]
Hello @seguler 

I've same error 
`
blobfuse[105044]: list_blobs_hierarchical failed for the 1 time with errno = 400.
blobfuse[105044]: list_blobs_hierarchical failed for the 1 time with errno = 400.
blobfuse[105044]: list_blobs_hierarchical failed for the 1 time with errno = 400.
`

Have you an idea ?

**Comment by seguler** [comment]
There is some communication problem with Storage, it seems @petit-lu 

Have you used SAS token ? If so, change to Account Key just to see if SAS token has an issue.
Is there a VNET firewall enabled ? If so make sure you have connectivity to Storage by downloading a simple file from Storage perhaps using AzCopy.
Is the account name you pass correct ? Verify that you get dns resolution by issuing `nslookup accountName.blob.core.windows.net`

**Comment by a139786** [comment]
One thing that may be an issue (I had similar) - is if you develop a problem with name resolution. It appears that shitstemd name resolution doesn't take it kindly if your primary nameserver develops issues. Access to my fusemounted directory under these circumstances hung forever. @seguler I'm guessing there are no timeout errors/exceptions raised - no ETIMEDOUT?

**Comment by kailashmsft** [comment]
@seguler we have same issue with one of our customer, 
he is using RHEL 7.5, when he is trying to mount blobfuse, but the command hangs.
we are able to resolve the storage account, we are able to telnet to the storage account on port 443, The tcpdump traces looks good. 
When we checked the cat /proc/mounts command  and we could see that the blobfuse is mounted.
Does it got anything to do with the AD authentication with the storage account access.

**Comment by chaim1221** [comment]
25 minutes, seriously? Is there a way to limit this?

**Comment by NaraVen** [comment]
@kpmguser Could you please add authType Key in the config file?

**Comment by NaraVen** [comment]
closing this one as the latest version 1.3.4 displays an appropriate error message "Storage connection failed, please check config values"
