### ISSUE TITLE
Wrong syslog message

### ISSUE THREAD

**Issue by valentinomiazzo-tba** [Azure/azure-storage-fuse#223]
https://github.com/Azure/azure-storage-fuse/blob/43e82df5d85a4c082dc67af8131bcf05f4d9270a/blobfuse/blobfuse.cpp#L84

syslog gets "Unable to start blobfuse.  No config file was specified and AZURE_STORAGE_ACCESS_KEY environment variable is empty.", which is wrong, while stderr gets "No config file was specified and AZURE_STORAGE_ACCOUNT environment variable is empty.\n".

**Comment by seguler** [comment]
Thanks! Definitely a bug!

**Comment by NaraVen** [comment]
fixed
