### ISSUE TITLE
Package not available in debian 9

### ISSUE THREAD

**Issue by smith000-000** [Azure/azure-storage-fuse#224]
I installed the debian 9 package repo from https://packages.microsoft.com/config/debian/9/prod.list

Here's my distro info:

Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch

Tried to install:

apt-get install blobfuse fuse
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package blobfuse

Here's the relevant line from apt-get update to confirm I'm hitting the repo:
Hit:21 https://packages.microsoft.com/debian/9/prod stretch InRelease

**Comment by smith000-000** [comment]
Is this possibly a similar issue to #18?

https://github.com/Azure/azure-storage-fuse/issues/18

**Comment by seguler** [comment]
I don't think we have binaries for Debian 9. You will need to build from source cloning this repository. Instructions here: https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation#option-2---build-from-source

Dependent package names might be slightly different, but we should be able to figure them out. If you do, please share here so I can update the docs
