### ISSUE TITLE
ANNOUNCEMENT: Use Premium Block Blob storage for improved performance

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-fuse#227]
Hello everyone!

Azure Storage team has announced the new SSD backed Block Blob storage accounts recently, which improves the performance (latency and throughput) significantly compared to the standard Block Blob (GPV2) accounts. Based on my tests, things go 2X faster in blobfuse with Premium Storage. If you would like to give it a try, check out [the announcement on the Public Preview of Premium Block Blobs](https://azure.microsoft.com/en-us/blog/introducing-azure-premium-blob-storage-limited-public-preview/).

Note that you have to register for the preview, and use the private drop of PowerShell highlighted in the announcement. Currently there is no Azure Portal support for it. Premium tier you see in Azure Portal only supports Premium Disks at this moment.

Have fun!

**Comment by anhvoms** [comment]
This is currently only available in very limited number of regions. Do you know when will they be available in more regions such as East US, South Central, West US 2?
