### ISSUE TITLE
File delete issue - soft delete

### ISSUE THREAD

**Issue by vijayraje23** [Azure/azure-storage-fuse#228]
### Which version of the blobfuse was used?
blobfuse-1.0.2-1

### Which OS (please include version) are you using?
CentOS Linux release 7.5.1804 (Core)

### What problem was encountered?
We have Two FTP servers in load balancer and on both servers we have
same blob storage mounted; same users are created on both severs; Servers have same configuration;
We have enabled soft delete feature on blob storage and retention is 14 days.

If we delete any folder which contain large numbers of files from one of the server. It got deleted/hidden immediately but from second server we can see that folder and files for some time. so my concern is it should reflect immediately on second server as well. is this because of soft delete feature or it taking some time to mark these folder/files as deleted. 
Between this period user can still see these files/folder if he reconnect to another server.

How we can speedup this operation ?

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

### If relevant, please share your mount command.
blobfuse /ftp/localuser --tmp-path=/mnt/blobfusetmp --config-file=/etc/vsftpd/connection.cfg -o allow_other -o nonempty

**Comment by seguler** [comment]
So, first of all, directory deletion is not atomic. You should not be able to remove a directory instantaneously. Maybe FTP is doing some magic caching and hiding the directory although it hasn't been completely deleted ?

Can you take the FTP server out of the picture and test this using bash ? E.g. delete the directory with `rm -r` and once it completes, do an `ls` on the other server.

If this is checking out, then I would also confirm that you haven't used any of the cache settings. Listing operation will be cached if you used the following settings when mounting blobfuse: `attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120`. These are the settings we have in `mount.sh` file if you have used that by any chance on the second server. You can verify your blobfuse mount command with `ps -ef | grep blobfuse`
