### ISSUE TITLE
Maximum number of mount?

### ISSUE THREAD

**Issue by gianlucb** [Azure/azure-storage-fuse#232]
Hi,

which is the maximum number of mount that is supported? Or at least tested on?
We would like to use it, for more than 100 mount points

**Comment by seguler** [comment]
We only test a single mount point per VM, but this doesn't mean there is a limitation. I believe it should work with however many you want as long as you use a DIFFERENT tmp location (cache location). Just know that blobfuse and FUSE uses CPU cycles to do lot of the operations (more than a local filesystem does), hence having 100 mountpoints on a 2-core machine could be slow.
