### ISSUE TITLE
Blob file name leading character is stripped for every `//` in `--tmp-path`

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-storage-fuse#233]
### Which version of the blobfuse was used?

Centos 7 package `blobfuse-1.0.2-1.x86_64`

### Which OS (please include version) are you using?

Centos 7

### What problem was encountered?

Step 1: do something like this:

```
declare -r CACHE_DIR="/tmp/blobcache//x//y//z"

blobfuse "${MOUNT_DIR}" \
  --container-name="${AZURE_STORAGE_CONTAINER}" \
  --tmp-path="${CACHE_DIR}" \
  ${BLOBFUSE_OPTIONS}
```

Step 2: observe weirdness:

```
cd ${MOUNT_DIR}
echo foo > 1234.txt
ls -l
```

The result is:

```
-rwxrwx---. 1 root root 4 Oct 24 11:20 4.txt
```

Note that `4.txt` is the actual blob name created. I can see it exactly like this in storage explorer and other places.

I found that the file name is stripped of a leading character for every `//` you have in `--tmp-path` paramteter.

Note that **reading** files  is not affected as far as I can tell.  But create/touch operations are. Maybe something else breaks too.

It is a common issue to have these empty paths, in fact, that's how I found this. My config was like this:

```
declare -r MOUNT_DIR="${HOME}/blobmount"
declare -r CACHE_DIR="/tmp/blobcache/${MOUNT_DIR}"   # <-- doh!
```

### Have you found a mitigation/solution?

Not really, except **being VERY VERY CAREFUL** :) 

It would be nice if blobfused normalised paths, which would remove empty `//`?  Or at least fail.  The current silent behaviour is rather dangerous.

**Comment by seguler** [comment]
Good find! This is a bug, and needs fixing.

**Comment by flybd5** [comment]
This bug has been flopping around for 10 months. We just ran into it at a critical point in our project and it makes this product unusable. is there a fix??? I mean, changing filenames when copying files is a pretty serious issue, would you not agree???

**Comment by flybd5** [comment]
Add to this Ubuntu 14, 16 and 18. This is a P1 BUG. 10 months and still there is unforgivable, makes the statement that this product is "stable" a total lie.

**Comment by flybd5** [comment]
It also fails on a simple cp command. I think it's because the source is a symbolic link.

**Comment by flybd5** [comment]
If I use "cp -L" instead, two files are created in the destination, one with the munged filename, one with the right filename. This is on Ubuntu 14.04.

**Comment by flybd5** [comment]
The silence is deafening.

**Comment by flybd5** [comment]
[syslog.blobfuse.events.txt](https://github.com/Azure/azure-storage-fuse/files/3560571/syslog.blobfuse.events.txt)

These are the blobfuse events from my syslog file. The filenames are clearly being truncated. For example, database.sql turns into base.sql and search-index.tgz turns into -index.tgz. There seems to be no rhyme or reason to how the truncations are taking place. @amnguye any idea what might be happening here?

**Comment by flybd5** [comment]
Well, since there has been not a peep from the team to this P1 bug in more than 10 months, my customer has decided to sh*tcan blobfuse as an unusable product. I'm done wasting my time here, moving on.

**Comment by kahing** [comment]
I can't speak for your use case of blobfuse and I work on another project that does something similar, but maybe you can do this as a workaround:

```
declare -r CACHE_DIR=$(realpath -m "/tmp/blobcache/${MOUNT_DIR})"
```

**Comment by amnguye** [comment]
Hi Juan @flybd5 ,

Thanks for reaching out to us and bringing this to our attention.

The truncating of filenames/blobs names even when the "--tmp-path" does not have "//" in the name is a concerning issue. This is unrelated to the original issue of this post.

Also the issue with cp truncating the filenames is also a concerning issue however should also be unaffected by tmp-path formatting. This is also unrelated to the current issue. Also when it is dereferenced (-L) should also not be creating two separate blobs. This seems like a separate issue since its affecting cp and symlink paths.

I took a look into the syslog you've provided. Thank you for providing that. The amount of truncated characters is different for each file name to blob name, which is a very strange issue.

We will create separate issues with your logs and details and get to them as soon as we can.

Thank you @kahing for your input and suggestion of the workaround :)

**Comment by nerddtvg** [comment]
I've subscribed to this as well. It's impacting us, although this is typically a typo and easily worked around, it is annoying.

**Comment by flybd5** [comment]
My contract with the client to whom this happened and who dumped blobfuse
has ended and I have no interest in the resolution of this so I am
unsubscribing.
