### ISSUE TITLE
`mv file#with#hash to_another_file` does not work

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-storage-fuse#235]
### Which version of the blobfuse was used?

`blobfuse 1.0.2`, Centos 7.

### What problem was encountered?

Cannot rename/move files containing `#` hash character.

To repro:

```
# The file 'foo#bar.txt' is created with correct content in blob storage
echo foo > 'foo#bar.txt'

# Try to rename the file.
# The exit code of this is 0, indicating success.
mv 'foo#bar.txt' 'bar.txt'
echo $?

```

After this op, `foo#bar.txt` is still in blob storage.

No file `bar.txt` is created.

Sometimes issuing ls lists **both** files, but only one of them would be in actual blob storage. The extra file would be found in cache directory. But cannot repro this reliably.

Error message from blobfuse found in logs:

```
Oct 31 15:51:16 [redacted] blobfuse[12353]: Attempt to call start_copy from foo#bar.txt to bar.txt failed.  errno = 404
```

Looks like blobfuse does not URL-encode '#' character properly when talking to blob REST API.

### Have you found a mitigation/solution?

Not really a workaround because does not work for us as we exec `mv` from programs etc, but for those desperate: copy/delete works.

```
cp 'foo#bar.txt' 'bar.txt'
rm 'foo#bar.txt'
```

### NOTES:

- `cp` is not affected. 
- `rm` is not affected either.

Most annoying parts are in addition to the fact it isn't working are :)) 

- zero exit code when there is clearly a failure
- messages printed to logs of sort (well we use systemd), nothing prinited to stderr to inform user

**Comment by mysil2** [comment]
I tried to store the persistence for a MariaDB docker instance on a blobfuse mount and it seems like I'm also encountering this bug. Here is the error:

`blobfuse[3063]: Attempt to call start_copy from mariadb/mariadb/data/bitnami_magento/#sql-1_f.frm to mariadb/mariadb/data/bitnami_magento/store_group.frm failed.  errno = 404#012.`

**Comment by vibhansa-msft** [comment]
@ppanyukov Can you try the latest version. I see both 'cp' and 'rm' commands are working with file names having '#' in the name. There were some file name encoding issue earlier which was fixed in version 1.3.1.

**Comment by vibhansa-msft** [comment]
Fix has been integrated. You can either try the latest source code or use 1.3.5 release when its available.

**Comment by destopa** [comment]
Hi, the same problem is now reproduced on a Centos 8 having blobfuse 1.3.6. Is there any solution for this ?

**Comment by vibhansa-msft** [comment]
@destopa : I tried on my CentOS8 VM with block blob account and rename works fine for me. I can see 'foo#bar.txt' getting renamed correctly. Can you double check the version you are using on CentOS8.

**Comment by vibhansa-msft** [comment]
Can you confirm issue still persists or not.

**Comment by vibhansa-msft** [comment]
Closing as there is no update on this. Feel free to reach out to us in case issue persists.
