### ISSUE TITLE
Sequential read-only access without local cache?

### ISSUE THREAD

**Issue by rcarmo** [Azure/azure-storage-fuse#237]
I'm experimenting with the [NYCTaxi dataset](http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml) which I uploaded to a storage account and mounted on a Linux DSVM, and I'm coming to the conclusion that it would be great to have "read only" mount option that would not use the local cache at all, because I just ran out of space twice during a few tests.

Maybe it would be possible to only actually download the remote blob if it was opened in write/append mode and skip the local cache altogether, like some other FUSE adapters do?

**Comment by seguler** [comment]
We are not planning to address this via changing our design. Instead we are thinking of purging the cached files automatically as the disk fills up... Stay tuned.

On the other hand, what have you done that filled up the disk that quickly ? How much disk space are we talking about ? If you reduce the file cache timeout parameter and set to few seconds, it is very unlikely to run out of space as long as you have a few dozens of GBs space on your disks. Remember blobfuse automatically purges the cached files as they timeout.

**Comment by xiangwu-ms** [comment]
There is a scenario for sequential write-only access for backup jobs. The backup file is normally > 10G, and it's just waste of space to use cache. And because it's a single big file, there is no way to purge the cache during the file is transferring to the blob storage from cache?

**Comment by seguler** [comment]
That is right, because we have no way of whether you will write sequentially or randomly. It is a recipe for data lost.. We can't improve this without sacrificing throughput... as in the throughput would drop to 5-10MB/s range..

**Comment by rcarmo** [comment]
Besides my massive read tests the other day with the NYC dataset, I would love to be able to use this to mount read-only file systems in Container Instances and bypass the cache altogether...

**Comment by seguler** [comment]
Is the intend not to fill the disk space with cache ? If so, we can consider automatically purging files from cache as the disk fills up. However as I've mentioned before we do not intend to do range reads. There are issues with data integrity and performance with that approach.

**Comment by rcarmo** [comment]
No, the intent is to have no cache at all (at least on disk) for read-only filesystems. I have been experimenting with competing FUSE drivers, and find the functionality very useful.

**Comment by seguler** [comment]
What is the reason of no-cache behavior ask ? Why not use Azure Files with SMB then ? 

You said the reason you did not want the cache was the disk space issue. Hence my suggestion on avoiding the disk space issue via automatic purging

**Comment by seguler** [comment]
I am closing this issue as we do not plan to address this in a way we do sequential read-only access.
