### ISSUE TITLE
Provide URI for blobfuse to address resources

### ISSUE THREAD

**Issue by stephenllai** [Azure/azure-storage-fuse#238]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Ubuntu 16.04.5 LTS

### What problem was encountered?
Can only configure blobfuse with account name and container name
Believe that, blobfuse will construct the URI for accessing resources using the following pattern
https://<account-name>.blob.core.windows.net/<container-name>
However, this URI is not applicable for resources stored in a storage emulator, which have the URI for accessing resources using the following pattern
http://127.0.0.1:10000/<account-name>/<container-name>
Cannot find a way for providing the URI to blobfuse for addressing resources.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Nil

### If relevant, please share your mount command.
`blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/stephen/fuse_connection.cfg --use-https=false -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120`

**Comment by seguler** [comment]
It is a good feature request, but given the higher priority backlog items I do not see this being implemented in the short term.

**Comment by seguler** [comment]
and also duplicate with #240 
Thanks!
