### ISSUE TITLE
Can this be used with Azure Container Instances ?

### ISSUE THREAD

**Issue by writeameer** [Azure/azure-storage-fuse#239]
### Which version of the blobfuse was used?

blobfuse v1.0.2

### Which OS (please include version) are you using?

Redhat 7

### What problem was encountered?

I'm trying to use this in a Container Instance hosted on ACI. The application asks for a container name - I think it assumes it's running on a Linux docker host. Can I use this with ACI to mount blob storage as a volume ?

### Have you found a mitigation/solution?

No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

Can't get it started.

**Comment by seguler** [comment]
I have tested it before using a docker container but the container needs to be started with –privileged mode. Not sure if this is something that can work in ACI.

**Comment by writeameer** [comment]
Hi there @seguler ,

Thanks so much for the update. Yes - appears we can't have privileged containers in ACI.  I'll close this ticket given it can't be done.

thanks,
Ameer Deen.
