### ISSUE TITLE
Storage emulators are not supported

### ISSUE THREAD

**Issue by Sushobhan123** [Azure/azure-storage-fuse#240]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Ubuntu 16.04

### What problem was encountered?
I have Azurite running in a docker container in a server. I have an azure container created inside it, named 'test'. I have been trying to mount this container 'test' using blobfuse on my machine with no success. 

I have followed [1. Installation - Azure/azure-storage-fuse](https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation) for installing blobfuse, using apt, including the dependencies.

##### Creation of ramdisk for the temporary path:
    sudo mkdir /mnt/ramdisk
    sudo mount -t tmpfs -o size=16g tmpfs /mnt/ramdisk
    sudo mkdir /mnt/ramdisk/blobfusetmp
    sudo chown <username> /mnt/ramdisk/blobfusetmp

##### Creating mountpoint:
    mkdir ~/blob

##### Connection.cfg (located in my home directory):
    accountName devstoreaccount1
    accountKey Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    containerName test
    blobEndpoint http://192.168.1.11:10000/devstoreaccount1

##### About the credentials used in the configuration file:
These are the provided credentials in Azurite. I have used Azure-cli (az) to connect to the Azurite using the same credentials and blobEndPoint.

    az storage blob list -c 'test' -o table --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://192.168.1.11:10000/devstoreaccount1;'
which gives the following output:

    Name    Blob Type    Blob Tier    Length    Content Type    Last Modified              Snapshot
    ------  -----------  -----------  --------  --------------  -------------------------  ----------
    a.txt   BlockBlob                 3486      text/plain      2018-11-15T12:02:09+00:00
    b.txt   BlockBlob                 3865      text/plain      2018-11-15T12:03:04+00:00

##### Command used to mount:
    blobfuse ~/blob --tmp-path=/mnt/ramdisk/blobfusetmp --config-file=/home/<username>/Connection.cfg --use-https=false -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG

When I run the command, the prompt comes down to the next line and waits for 5-10 mins before releasing it. It does not log any output to the prompt, but logs the following to syslog:

    <15>1 2018-11-16T16:06:59.218105+05:30 sk30 blobfuse 73260 - -  Function ensure_files_directory_exists_in_cache, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 202: Making cache directory /mnt.
    <15>1 2018-11-16T16:06:59.218652+05:30 sk30 blobfuse 73260 - -  Function ensure_files_directory_exists_in_cache, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 202: Making cache directory /mnt/ramdisk.
    <15>1 2018-11-16T16:06:59.219213+05:30 sk30 blobfuse 73260 - -  Function ensure_files_directory_exists_in_cache, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 202: Making cache directory /mnt/ramdisk/blobfusetmp.
    <15>1 2018-11-16T16:06:59.254350+05:30 sk30 blobfuse 73260 - -  Function ensure_files_directory_exists_in_cache, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 202: Making cache directory /mnt/ramdisk/blobfusetmp/root.

Running `df -h` shows a blobfuse mount at the specified mountpoint as:

    Filesystem                                      Size  Used Avail Use% Mounted on
    tmpfs                                            16G     0   16G   0% /mnt/ramdisk
    blobfuse                                         16G     0   16G   0% /home/<username>/blob

Now if I run `ls ~/blob`, I expect to see the two blobs 'a.txt' and 'b.txt'. Their presence in the container is verified by the output of the `az` command.
But `ls ~/blob` again holds the prompt for 5-10 mins and returns with no output. This command logs the following to syslog:

    <15>1 2018-11-16T16:15:31.223118+05:30 sk30 blobfuse 95928 - -  Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 349: azs_getattr called with path = /
    <15>1 2018-11-16T16:15:31.223621+05:30 sk30 blobfuse 95928 - -  Function azs_readdir, in file /home/seguler/azure-storage-fuse/blobfuse/directoryapis.cpp, line 44: azs_readdir called with path = /
    <15>1 2018-11-16T16:15:31.223856+05:30 sk30 blobfuse 95928 - -  Function azs_readdir, in file /home/seguler/azure-storage-fuse/blobfuse/directoryapis.cpp, line 59: Reading contents of local cache directory /mnt/ramdisk/blobfusetmp/root/.
    <15>1 2018-11-16T16:15:31.224084+05:30 sk30 blobfuse 95928 - -  Function list_all_blobs_hierarchical, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 236: About to call list_blobs_hierarchial.  Container = test, delimiter = /, continuation = , prefix =
    <15>1 2018-11-16T16:22:44.803021+05:30 sk30 blobfuse 95928 - -  Function list_all_blobs_hierarchical, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 244: Successful call to list_blobs_hierarchical.  results count = 0, next_marker = .
    <15>1 2018-11-16T16:22:44.803407+05:30 sk30 blobfuse 95928 - -  Function azs_readdir, in file /home/seguler/azure-storage-fuse/blobfuse/directoryapis.cpp, line 114: Reading blobs of directory  on the service.  Total blobs found = 0.

When I listed the blobs in the container using `az`, the Azurite container logged the following:

    GET /devstoreaccount1/test?restype=container&comp=list 200 2.935 ms - 1210

But with everything that I tried using blobfuse, Azurite did not log anything. I am guessing the blobfuse never established any connection with Azurite. Maybe something to do with the `blobEndPoint`?

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
All relevant logs in the syslog have been provided above.

### If relevant, please share your mount command.

    blobfuse ~/blob --tmp-path=/mnt/ramdisk/blobfusetmp --config-file=/home/<username>/Connection.cfg --use-https=false -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG

**Comment by seguler** [comment]
We do not support Storage Emulators... and don't plan to given higher priority improvements we have in our backlog

**Comment by Sushobhan123** [comment]
[This comment](https://github.com/Azure/azure-storage-fuse/issues/218#issuecomment-424181464) of yours, where you are suggesting to use Azurite, led me to believe that it is supported.

**Comment by seguler** [comment]
Sorry about that - I was confused... Custom IP:port addresses are supported, however the storage account at the end of the url that is needed for emulators are not supported in blobfuse.

**Comment by Sushobhan123** [comment]
Sorry, the above was a reply to your first comment.

And as for, 'the storage account at the end of the url that is needed for emulators', we can access a blob in Azurite using 
`curl http://custom-ip:10000/devstoreaccount1/my-blob-container/my-file.my-extension`
which is similar to 
`curl http://my-account.blob.core.windows.net/my-blob-container/my-file.my-extension`
where `custom-ip:10000/devstoreaccount1` replaces `my-account.blob.core.windows.net`. 

Can you elaborate on how this creates a problem?

**Comment by damienpontifex** [comment]
@seguler the use of storage emulator with the azure-storage-cpp-lite library would be useful. I'm currently trying to write tests for an azure blob storage implementation for tensorflow/io repo.
Let me know if I can help out in making this happen, at least in the storage lib anyway.

**Comment by NaraVen** [comment]
I successfully mounted with a storage emulator. The emulator was running already. Is this still an issue?

**Comment by Jamie-round455** [comment]
I've recently had the same problem as @Sushobhan123 trying to get this working with a local Azurite docker container. 
For anyone else experiencing a problem, we found wte blobEndoint, when used in the config or environment variable expects the following pattern _{accountName}.blob.{anytext}.{anytext}_

The first two url segments were key to getting blobfuse to use the endpoint as expected and to see traffic hitting the Azurite container.

**Comment by GuillaumeDesforges** [comment]
Had the same problem, would be excellent to write proper tests.

**Comment by bluebrown** [comment]
> I've recently had the same problem as @Sushobhan123 trying to get this working with a local Azurite docker container. For anyone else experiencing a problem, we found the blobEndoint expects the following pattern _{accountName}.blob.{anytext}.{anytext}_
> 
> The first two url segments were key to getting blobfuse to use the endpoint as expected and to see traffic hitting the Azurite container.

can you explain this more please? 

afaik, this is the default pattern and I would expect blob-fuse to try to connect this way. So did you configure this in azurite? I am not aware of any setting in this regard. Would be nice to get some more info.

**Comment by gapra-msft** [comment]
Hi all, 

We are working on next generation of blobfuse called "blobfuse2" (in preview mode as of now) **that [supports ](https://github.com/Azure/azure-storage-fuse/pull/865) Azurite style endpoints.** If you wish you give it a try, you can get the binary from this link : https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2 or install it from the Microsoft repos (package name is blobfuse2)
Blobfuse2 has a different cli and config model so you can refer to our readme @ https://github.com/Azure/azure-storage-fuse/tree/main#readme
