### ISSUE TITLE
<no name> folder in blob storage account if temp and mount path has ~/

### ISSUE THREAD

**Issue by xiangwu-ms** [Azure/azure-storage-fuse#241]
There is another similar bug for the temp mount path, which seems to similar of directory handling in the code.

### Which version of the blobfuse was used?
Installed Packages
Name        : blobfuse
Arch        : x86_64
Version     : 1.0.2
Release     : 1
Size        : 1.1 M
Repo        : installed
From repo   : packages-microsoft-com-prod
Summary     : blobfuse 1.0.2 for Azure Storage - MIT License
License     : MIT
Description : DESCRIPTION
            : ===========
            :
            : This is an installer created using CPack (http://www.cmake.org). No additional installation instructions provided.

### Which OS (please include version) are you using?
Linux localhost.localdomain 2.6.32-696.el6.x86_64 #1 SMP Tue Feb 21 00:53:17 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

### What problem was encountered?
<no name> folder created. 

### Have you found a mitigation/solution?
Don't use ~/

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Took the network trace and can see the error.

### If relevant, please share your mount command.
sudo mkdir ~/blobfusetmp
sudo mkdir ~/blobfusemount

export AZURE_STORAGE_ACCOUNT=xwtest
export AZURE_STORAGE_ACCESS_KEY=<removed>

>` blobfuse  ~/blobfusemount --container-name=test --tmp-path=~/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 --use-https=false`

==Create the file===
echo "test" >   ~/blobfusemount/test2

==Network trace ==
== Before file creation, looks good for checking the file==
cÔV]ùlE:Qk@@ANÀ¨y4¿°$ÔPLâ3£Ed¸
s¨1
c"Kr»HEAD /test/test2 HTTP/1.1
Host: xwtest.blob.core.windows.net
Accept: */*
User-Agent: Azure-Storage-Fuse/1.0.2
x-ms-date: Sat, 17 Nov 2018 05:15:24 GMT
x-ms-version: 2017-04-17
Authorization: SharedKey xwtest:VWF1Hz9NnwS0DEzBBP1qp3UOlHnpd+4Z3d5ZtCUSs2M=

== When creating the file, the extra / was added. Looks like blob storage doesn't ignore the additional / and create /<no name>/test2

cÔV]ùlE{Ü:@@¶=À¨y4¿°$ÔP;¸aÉ.q#s¨r
d¡A
PUT /test//test2 HTTP/1.1
Host: xwtest.blob.core.windows.net
Accept: */*
Content-Length: 0
x-ms-blob-type: BlockBlob
User-Agent: Azure-Storage-Fuse/1.0.2
x-ms-date: Sat, 17 Nov 2018 05:15:24 GMT
x-ms-version: 2017-04-17
Authorization: SharedKey xwtest:d1ycN5vmviHQbg5nYG6f6fcSSX7pZHLhAp4Qp54u1kc=
Content-Length: 0

Remount and nothing shows in the mounted folder
==================================
umount -l ~/blobfusemount
`blobfuse~/blobfusemount --container-name=test --tmp-path=~/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 `--use-https=false`

**Comment by xiangwu-ms** [comment]
ov 16 21:28:16 localhost blobfuse[4287]: Function azs_release, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/fileapis.cpp, line 361: azs_release called with path = /test2, fi->flags = 32769
Nov 16 21:28:16 localhost blobfuse[4287]: Function azs_release, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/fileapis.cpp, line 380: Adding file to the GC from azs_release.  File = ~/blobfusetmp/root/test2#012.
Nov 16 21:30:17 localhost blobfuse[4287]: Function run_gc_cache, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 72: File /test2 being considered for deletion by file cache GC.
Nov 16 21:30:17 localhost blobfuse[4287]: Function run_gc_cache, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 109: GC cleanup of cached file ~/blobfusetmp/root/test2.
Nov 16 21:32:10 localhost blobfuse[4287]: Function azs_destroy, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 481: azs_destroy called.
Nov 16 21:32:11 localhost blobfuse[4304]: Function ensure_files_directory_exists_in_cache, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 202: Making cache directory ~.
Nov 16 21:32:11 localhost blobfuse[4205]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 349: azs_getattr called with path = /~
Nov 16 21:32:11 localhost blobfuse[4205]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 391: Object ~/blobfusetmp/root/~ is not in the local cache during get_attr.
Nov 16 21:32:11 localhost blobfuse[4205]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 403: Blob /~, representing a directory, found during get_attr.
Nov 16 21:32:11 localhost blobfuse[4304]: Function ensure_files_directory_exists_in_cache, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 202: Making cache directory ~/blobfusetmp.
Nov 16 21:32:11 localhost blobfuse[4205]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 349: azs_getattr called with path = /~/blobfusetmp
Nov 16 21:32:11 localhost blobfuse[4205]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 391: Object ~/blobfusetmp/root/~/blobfusetmp is not in the local cache during get_attr.
Nov 16 21:32:12 localhost blobfuse[4205]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 403: Blob /~/blobfusetmp, representing a directory, found during get_attr.
Nov 16 21:32:12 localhost blobfuse[4304]: Function ensure_files_directory_exists_in_cache, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 202: Making cache directory ~/blobfusetmp/root.
Nov 16 21:32:12 localhost blobfuse[4205]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 349: azs_getattr called with path = /~/blobfusetmp/root
Nov 16 21:32:12 localhost blobfuse[4205]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 391: Object ~/blobfusetmp/root/~/blobfusetmp/root is not in the local cache during get_attr.
Nov 16 21:32:12 localhost blobfuse[4205]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 403: Blob /~/blobfusetmp/root, representing a directory, found during get_attr.
Nov 16 21:32:21 localhost blobfuse[4205]: Function azs_readdir, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/directoryapis.cpp, line 44: azs_readdir called with path = /
Nov 16 21:32:21 localhost blobfuse[4205]: Function azs_readdir, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/directoryapis.cpp, line 101: Directory ~/blobfusetmp/root/ not found in file cache during readdir operation for /.
Nov 16 21:32:21 localhost blobfuse[4205]: Function list_all_blobs_hierarchical, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 236: About to call list_blobs_hierarchial.  Container = test, delimiter = /, continuation = , prefix =
Nov 16 21:32:21 localhost blobfuse[4205]: Function list_all_blobs_hierarchical, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 244: Successful call to list_blobs_hierarchical.  results count = 3, next_marker = .
Nov 16 21:32:21 localhost blobfuse[4205]: Function azs_readdir, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/directoryapis.cpp, line 114: Reading blobs of directory  on the service.  Total blobs found = 3.
Nov 16 21:32:21 localhost blobfuse[4205]: Function azs_readdir, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/directoryapis.cpp, line 165: Blob directory ~ found in directory  on the service during readdir operation.  Adding to readdir list; fillerResult = 0.
Nov 16 21:32:21 localhost blobfuse[4205]: Function azs_readdir, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/directoryapis.cpp, line 174: Skipping adding blob ~ to readdir results because it was already added from the local cache.
Nov 16 21:32:27 localhost blobfuse[4306]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 349: azs_getattr called with path = /test2
Nov 16 21:32:27 localhost blobfuse[4306]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 391: Object ~/blobfusetmp/root/test2 is not in the local cache during get_attr.
Nov 16 21:32:29 localhost blobfuse[4306]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 449: Entity /test2 does not exist.  Returning ENOENT (2) from get_attr.
Nov 16 21:32:29 localhost blobfuse[4306]: Function azs_create, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/fileapis.cpp, line 201: azs_create called with path = /test2, mode = 33188, fi->flags = 8241
Nov 16 21:32:29 localhost blobfuse[4306]: Function ensure_files_directory_exists_in_cache, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 202: Making cache directory ~.
Nov 16 21:32:29 localhost blobfuse[4306]: Function ensure_files_directory_exists_in_cache, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 202: Making cache directory ~/blobfusetmp.
Nov 16 21:32:29 localhost blobfuse[4306]: Function ensure_files_directory_exists_in_cache, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 202: Making cache directory ~/blobfusetmp/root.
Nov 16 21:32:29 localhost blobfuse[4306]: Successfully created file /test2 in file cache.
Nov 16 21:32:29 localhost blobfuse[4306]: Function azs_create, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/fileapis.cpp, line 231: Returning success from azs_create with file /test2.
Nov 16 21:32:29 localhost blobfuse[4306]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 349: azs_getattr called with path = /test2
Nov 16 21:32:29 localhost blobfuse[4306]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 374: Accessing mntPath = ~/blobfusetmp/root/test2 for get_attr succeeded; object is in the local cache.
Nov 16 21:32:29 localhost blobfuse[4306]: Function azs_getattr, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/utilities.cpp, line 385: lstat on file ~/blobfusetmp/root/test2 in local cache succeeded.
Nov 16 21:32:29 localhost blobfuse[4306]: Function azs_flush, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/fileapis.cpp, line 265: azs_flush called with path = /test2, fi->flags = 0, (((struct fhwrapper *)fi->fh)->fh) = 9.
Nov 16 21:32:29 localhost blobfuse[4306]: Function azs_flush, in file /home/seguler/azure-storage-fuse-1.0.2/blobfuse/fileapis.cpp, line 283: Successfully looked up mntPath.  Input path = /test2, path_link_buffer = /proc/self/fd/9, path_buffer = /~/blobfusetmp/root/test2
Nov 16 21:32:29 localhost blobfuse[4306]: Successfully uploaded file /test2 to blob /test2.

**Comment by xiangwu-ms** [comment]
[root@localhost ~]# ./azcopy_linux_amd64_10.0.4/azcopy list "https://xwtest.blob.core.windows.net/test?SAS"
/test1
/test2

So file names with "/", however there is a different bug in portal that show <no name> folder.

**Comment by seguler** [comment]
Yep it is a bug. If you mount with the home shortcut (~/) blobfuse does not work correctly.

**Comment by atomek1000** [comment]
I don't use ~/ and still get this bug which creates blank folders, look at my issue #242

**Comment by azvihar** [comment]
mkdir "/path/to/mount/folder1\/\test2" will create <noname> in folder1

**Comment by azvihar** [comment]
mkdir "/path/to/mount/folder1\/\test2" will create noname in folder1

**Comment by azvihar** [comment]
mkdir "/path/to/mount/folder1\\/\test2" will create noname in folder1.

**Comment by vibhansa-msft** [comment]
This has been fixed, kindly try out the latest version and update issue is still seen or not.

**Comment by asantos00** [comment]
While using the azure-sdk client for Node.js we managed to somehow create a folder that says <no name>. That's a folder we can't interact at all via UI (no rename, no delete, nothing), but somehow it seems that we can still upload files there (via SDK).

While trying to debug, and inspect the request coming on Azure portal, it says (on your server XML response) that the folder is named "/" on your response.

![image](https://user-images.githubusercontent.com/2593480/168326088-554f98e6-3d6e-497c-a765-72f5e7db771d.png)

Do you know what can we do to fix this? And also, since we're running in production and there's already files in the "< no name >" folder, how should we proceed to fix it?

Thanks!

**Comment by vibhansa-msft** [comment]
Sorry din't get your problem statement. What I understand is you have a folder "/" on your root and you want to interact with files within it? For such folder blob names shall be starting with "/" so if you can fabricate a REST request with correct file name, including first "/" it shall work fine. However, it's not advisable to use such folder name, so better to get the files out of it and move to another folder.
