### ISSUE TITLE
Blobfuse unmounts randomly

### ISSUE THREAD

**Issue by atomek1000** [Azure/azure-storage-fuse#242]
### Which version of the blobfuse was used?
1.02

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
blobfuse gets unmounted randomly - during transfer
I'm running it on smallest azure vm B1s with 1GB ram and 50GB hdd disk mounted, blobfuse is running on this disk both temp and fused directory.
I managed to copy 10gb file once (so i guess ram is not an issue). But other times it fails on 2gb file.
I can't get it to be reliable. Why i want to get it to be reliable? I want to have sftp server which is connected directly to blob so when somebody uploads it automatically is transferred to blob. Thats why i have allow others flag enabled.
When trying to access i get error: Transport endpoint is not connected

### Have you found a mitigation/solution?
Not really, i tried almost everything and multiple times.
Ran it on ramdisk, currently on bigger mounted drive.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
From what i see blobfuse was outofmemory
https://pastebin.com/esgDu0Dn

### If relevant, please share your mount command.
blobfuse sftp1 --tmp-path=blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=fuse_connection.cfg --file-cache-timeout-in-seconds=100 -o allow_other

**Comment by atomek1000** [comment]
Another issue i have is that it ignores files in nested in folders. it only syncs files from root directory.
But funny thing is it creates folder on blob but its empty - and deletes files in the folder after cache-timeout period.
Is it designed to pick up files from nested folders or only root?

**Comment by seguler** [comment]
Yes - nested folders work too. I can only guess the issue is related to the server being with few GBs of memory, or the cache space is running out of space. Just a note - blobfuse needs to store the entire file contents on the disk while the file is open. If you don't have space, things will stop working.

**Comment by atomek1000** [comment]
Hey, disconnecting didn't happen yet after scaling up vm a bit so that's good.
But nested folders never worked  - could you tell me what should i check to make sure it picks up files in nested folders as well? (it creates directories on blob but doesn't put any files in it, files still disappear on VM after cache timeout period so they are lost forever).
SAS token has all permissions so that can be the issue
Directory to which i mount blobfuse is on mounted drive and user which mounts it was 'chowned' to this directory. I also tried sudo blobfuse and same results. It's like a one way road -> blob, existing files from blob do not appear in the mounted path.

Any ideas?

**Comment by atomek1000** [comment]
Based on referenced issue i tried providing whole path not local path and now it works correctly...
Please update documentation to say that you need to specify whole path...
Also, on Standard B2s (2 vcpus, 4 GB memory) it doesnt unmount itself now.
Please close issue 👍

**Comment by seguler** [comment]
Thank you ! I've updated the docs mentioning only absolute paths work.
