### ISSUE TITLE
Azure data lake equivalent

### ISSUE THREAD

**Issue by sophia-wright-blue** [Azure/azure-storage-fuse#243]
is there a blobfuse like software to directly read/write data from an azure VM to azure data lake storage (instead of blob storage)?

thanks,

**Comment by seguler** [comment]
Not at this moment. Soon ADLS Gen2 will be compatible with Blob storage, hence there won't be need to have a blobfuse for it. Blobfuse will read the data from an ADLS enabled Storage account.

**Comment by sophia-wright-blue** [comment]
thanks for that information @seguler , i look forward to using ADLS Gen 2 that is compatible with Blob storage,
