### ISSUE TITLE
Add instructions on how to mount the driver in a container (requires --cap-add SYS_ADMIN --device /dev/fuse)

### ISSUE THREAD

**Issue by andersjohansenange** [Azure/azure-storage-fuse#244]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Ubuntu 18.04.1 LTS (Bionic Beaver)

### What problem was encountered?
Can't mount the FUSE system in a container without giving it additional privileges via --cap-add SYS_ADMIN --device /dev/fuse

### Have you found a mitigation/solution?
Yes, but suggest that docs and Wiki troubleshooting specifically mentions this.

### If relevant, please share your mount command.
N/A

**Comment by seguler** [comment]
Thanks @andersjohansenange - I was usually trying `--priviliged` mode to mount blobfuse. What is the difference between priviliged mode and the flags you provided ? Once I learn more about this, I can update wiki.

**Comment by andersjohansenange** [comment]
Sure, the --priviliged flag gives the container all system capabilities. The --cap-add allows you to only add the one(s) that are needed. So it's best practice to only use the minimum required, in this case SYS_ADMIN. It's not a huge improvement, as SYS_ADMIN is extremely broad, but FUSE does need privs to mount and to add kernel extensions, so I suppose it's to be expected.

A recent change to the way security is handled in Docker actually makes it so that another change is required: deactivate apparmor.

Here's my full command line to run my own FUSE container:

`docker run --security-opt apparmor:unconfined --device /dev/fuse --cap-add SYS_ADMIN -d --name protosubterraneous-ctr protosubterraneous &
`

... where `--name protosubterraneous-ctr protosubterraneous` is specific to my container, and everythign else is required for FUSE to work in the container - at least for Alpine linux based containers.

More here:
cap-add vs. priviliged
https://serverfault.com/questions/824809/chrome-under-docker-cap-sys-admin-vs-privileged

Why SYS_ADMIN is required
https://rhelblog.redhat.com/2016/11/30/container-tidbits-adding-capabilities-to-a-container/

**Comment by chaim1221** [comment]
Hey can you provide a link to your Dockerfile? I am trying to make an azure-storage-fuse container and I think running into a related problem but your command does not work for me on Mojave:

```
celiyah at ce-mbp-dev Tue Apr 30 10:39:13 ~/Code/machete/backups/docker/azure-storage-fuse 
azure-storage-fuse:$ docker run ndlonmachete/azure-storage-fuse:0.0.1 --device /dev/fuse --cap-add SYS_ADMIN -dit --name azure_fuse /bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"--device\": executable file not found in $PATH": unknown.
ERRO[0001] error waiting for container: context canceled 
celiyah at ce-mbp-dev Tue Apr 30 10:39:24 ~/Code/machete/backups/docker/azure-storage-fuse 
azure-storage-fuse:$ docker run --security-opt ndlonmachete/azure-storage-fuse:0.0.1 --device /dev/fuse --cap-add SYS_ADMIN -dit --name azure_fuse /bin/bash
docker: invalid reference format.
See 'docker run --help'.
```

**Comment by NaraVen** [comment]
done
