### ISSUE TITLE
DataLake Gen2: errno = 1600.

### ISSUE THREAD

**Issue by thelazydogsback** [Azure/azure-storage-fuse#245]
I'm getting a:
    `Creating blob client failed: errno = 1600.`
when I try and mount to an HNS-enabled DataLake Gen2 target.
The accountName, accountKey and containerName are copied from the portal and appear to work fine in other contexts. 
I also tried using the blobEndpoint parameter.
LOG_DEBUG doesn't seem to add anything else to stderr or any log file I can find.

thanks

Linux ubuntu4 4.15.0-1035-azure #36-Ubuntu
blobfuse 18.04

**Comment by seguler** [comment]
Data Lake Gen2 accounts do not yet support Blob REST APIs, hence blobfuse does not work with ADLS Gen2. When ADLS Gen2 supports Blob REST APIs ( which should be coming soon) you will be able to use blobfuse.
