### ISSUE TITLE
blobfuse command hangs when trying to mount on RHEL 7.5 vm

### ISSUE THREAD

**Issue by kailashmsft** [Azure/azure-storage-fuse#248]
### Which version of the blobfuse was used?

blobfuse 1-0.2 
### Which OS (please include version) are you using?
Rhel 7.5
### What problem was encountered?
The cx is trying to mount the blobfuse but the command seems to be hanging.
But when we check the "cat /proc/mounts " in another session we could see that it shows as mounted. The outputs are attached for the same.
we have checked the "fuse" module is loaded, the blobfuse package is installed, but still we are not able to trace to why this is not mounting.
we have checked the storage account is resolvable from the vm, it is also connecting to the port 443. 

### Have you found a mitigation/solution?
No solution found yet,
we have asked to create a new vm and mount and it works
only for the existing vm's they mount is not working.
we have compared both the vm's and we didnt find any major difference between them.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
we could only timeout errors.
attached the snippet of the message file, and strace output

### If relevant, please share your mount command.

Please let us know if you need any more details

**Comment by seguler** [comment]
We have a known bug where a DNS lookup failure can freeze blobfuse. Can you try adding the DNS resolution for your account to /etc/hosts and retry ?

**Comment by kailashmsft** [comment]
The customer used --use-https=true option while mounting blobfuse and it resolved the issue
