### ISSUE TITLE
Segfault blobfuse

### ISSUE THREAD

**Issue by ludlbn** [Azure/azure-storage-fuse#249]
### Which version of the blobfuse was used?
We using 1.0.2

### Which OS (please include version) are you using?
CentOS 7.5

### What problem was encountered?
We got segfault about Fuse and we lost connection on blob storage.

### Have you found a mitigation/solution?
no, we need to rexecute mount script

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

blobfuse[1657]: list_blobs_hierarchical failed for the 1 time with errno = 400.
blobfuse[1657]: list_blobs_hierarchical failed for the 1 time with errno = 400.
blobfuse[1657]: list_blobs_hierarchical failed for the 2 time with errno = 400.
blobfuse[1657]: list_blobs_hierarchical failed for the 1 time with errno = 400.
blobfuse[1657]: list_blobs_hierarchical failed for the 2 time with errno = 400.
blobfuse[1657]: list_blobs_hierarchical failed for the 3 time with errno = 400.
blobfuse[63357]: list_blobs_hierarchical failed for the 2 time with errno = 400.
kernel: [357955.276606] blobfuse[70272]: segfault at 30 ip 0000000000452d64 sp 00007fc581bb8dd0 error 4 in blobfuse[400000+c8000]
blobfuse[63357]: list_blobs_hierarchical failed for the 1 time with errno = 400.

### If relevant, please share your mount command.
`/bin/blobfuse $1 --tmp-path=/blobfusetmp -o allow_root -o nonempty -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/fuse_connection.config --log-level=LOG_INFO
`

**Comment by ludlbn** [comment]
Hello,

I'm staying available, if you need more information.
We got new occur about this issue :

`kernel: [588156.104288] blobfuse[1894]: segfault at 30 ip 0000000000452d64 sp 00007f391f7fcdd0 error 4 in blobfuse[400000+c8000]`

Regards.

**Comment by seguler** [comment]
Were you able to successfully list any blobs using ls command at all ? From the looks blobfuse is unable to reach out to Blob storage. Where is this VM running ? Is it in the same region as your storage account ?

**Comment by ludlbn** [comment]
Hello,

ls command works fine.
Vm is running in West Europe and it's same region as storage account.
Storage Account is accessible and running during incident.

We using blob mount on 7 servers.
For example this morning we got an occur issue on specific server of this group :
`[923652.534158] blobfuse[118409]: segfault at 30 ip 0000000000452d64 sp 00007ff37ba87dd0 error 4 in blobfuse[400000+c8000]`

Thanks for your help.

**Comment by seguler** [comment]
Could you please create a support ticket and escalate this issue ? We should get more details, logs and core dump to look into this.

**Comment by ludlbn** [comment]
Hi @seguler , 

I opened a support ticket on Azure Support, and they asked me to open an issue here on blobfuse repo. Because, they aren't issue on Filestorage account.
What type of log you need to investigate on issue ?

**Comment by seguler** [comment]
Could you send us an e-mail at ascl@microsoft.com on this issue with some more details ? Let's continue from there.

**Comment by seguler** [comment]
@ludlbn please send us an e-mail on this.

**Comment by ludlbn** [comment]
Thanks. It sent.

**Comment by ustcnene** [comment]
I meet errno 400 issue too, do you have some explanation?

**Comment by admiraldata** [comment]
We see the exact same error message? what was the ultimate RCA for this?

**Comment by NaraVen** [comment]
> We see the exact same error message? what was the ultimate RCA for this?

Which version of Blobfuse are you using?

**Comment by vibhansa-msft** [comment]
In latest version this has been addressed.
