### ISSUE TITLE
Seems to hang on RHEL and files dont move from cache to blob storage

### ISSUE THREAD

**Issue by richardharrison2** [Azure/azure-storage-fuse#25]
Hi,
I tried this out on RHEL and blogged about the result here http://dbaharrison.blogspot.de/2017/12/fusing-blobs-in-azure.html it seems that the process is very slow and even when it says its complete doesnt actually write files to the blob storage but only the cache area.

I think i set everything up right but it's not working as i expected - did i miss to do something here?

Cheers,
Rich

**Comment by seguler** [comment]
What is your Redhat version ?
Normally if you get success to cp; it means that you successfully persisted the data to blob storage. But maybe there is an issue somehwhere in the config or a bug in the code

**Comment by seguler** [comment]
Also - with which user did you mount blobfuse ? The owner of the /mnt/resource/blobfusetmp should be the same user as the one that launches blobfuse. I suspect this is the issue.

**Comment by seguler** [comment]
This issue may be related to the issue #37.

**Comment by seguler** [comment]
Closing this as we addressed the HTTPS issue #37
