### ISSUE TITLE
blobfuse不支持命令行传入blobEndpoint 

### ISSUE THREAD

**Issue by xiaocaisgit** [Azure/azure-storage-fuse#251]
### Which version of the blobfuse was used?

blobfuse 1.0.2

### Which OS (please include version) are you using?

centos 7
### What problem was encountered?
在自建的kubernetes 集群中使用azure提供的daemonset驱动。并使用官方提供的nginx镜像来测试。发现pod无法启动。日志中提示403.   结合之前虚拟机上单独挂载blobfuse 的情况。 我发现是因为中国用户在使用blobfuse 的时候需要在connection.cfg指定blobEndpoint 。因此，我修改了官方的镜像中挂载的参数如下：
CFG="/etc/kubernetes/volumeplugins/azure~blobfuse/connection.cfg"
	${BLOBFUSE} ${MNTPATH} --container-name=${CONTAINER} --config-file=${CFG} --tmp-path=${TMP_PATH} -o allow_other ${read_only_param} ${MOUNT_OPTIONS}

connection如下：
accountName <testit>
accountKey <mykey>
blobEndpoint testit.blob.core.chinacloudapi.cn
但是当我创建容器的时候。 他提示我需要传入container-name。。。这导致我kubernetes中配置的 containner-name无效，而且整个集群只能使用一个container。
不知道blobfuse  是否支持读取环境变量或者传入参数的方式读取blobEndpoint ？

### Have you found a mitigation/solution?

see below

**Comment by seguler** [comment]
Sorry at this point we only provide support in English.

**Comment by andyzhangx** [comment]
in latest blobfuse 1.2.1, it's already supported
