### ISSUE TITLE
Mounted Azure Blob Storage on Azure Linux VM using fuse gets unmouted automatically after 2 or 3 days

### ISSUE THREAD

**Issue by fasigpt** [Azure/azure-storage-fuse#252]
### Which version of the blobfuse was used?
blobfuse 1.0.2 https://github.com/Azure/azure-storage-fuse/releases/tag/v1.0.2 

### Which OS (please include version) are you using?
Linux  2.6.32-642.4.2.el6.x86_64 
CentOS 6.8

### What problem was encountered?
Mounted Azure Blob Storage on Azure Linux VM using **fuse** gets unmounted automatically after 2 or 3 days. So we need to re mount again if this happens

### Have you found a mitigation/solution?
No, except need to re mount everytime

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

grep blob /var/log/secure
Mar 4 21:42:05 xxx-jump01 sudo: XXXXXuser : TTY=pts/3 ; PWD=/xxxxnssmx ; USER=root ; COMMAND=/usr/bin/blobfuse /xxxxnssmx/client --tmp-path=/mnt/resource/blobfusetmp --config-file=/path/to/client.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o uid=501 -o gid=501
[root@xxx-jump01 client]# grep blob /var/log/messages
Mar 4 07:49:42 xxx-jump01 blobfuse[105670]: Directory /server package does not exist; failing directory delete operation.
Mar 4 20:56:40 xxx-jump01 blobfuse[105670]: Directory /server package does not exist; failing directory delete operation.
Mar 4 20:56:40 xxx-jump01 blobfuse[105670]: Directory /ipa does not exist; failing directory delete operation.
Mar 4 22:41:28 xxx-jump01 blobfuse[95389]: Unable to start blobfuse, no config file provided and --container-name is not set.
If relevant, please share your mount command.
#!/bin/bash
blobfuse /xxxxnssmx/ledao --tmp-path=/mnt/resource/blobfusetmp --config-file=/path/to/ledao.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o uid=501 -o gid=501
blobfuse /xxxxnssmx/qa-patch --tmp-path=/mnt/resource/blobfusetmp --config-file=/path/to/qa-patch.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o uid=501 -o gid=501
blobfuse /xxxxnssmx/client --tmp-path=/mnt/resource/blobfusetmp --config-file=/path/to/client.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o uid=501 -o gid=501

**Comment by towishy** [comment]
also  When blobfuse Issue occured , Azure Blob Storage Avail. is normal state.
is there any issue?

**Comment by fasigpt** [comment]
The storage availability had no issues during that time frame.

**Comment by seguler** [comment]
Hey folks - what is the memory usage of blobfuse after a day ? How many files have you been ingesting/egressing per day ? I suspect a 1 core, 3.5GB machine is not enough to sustain blobfuse. Also there is a slight memory usage growth problem in blobfuse that is explained here: https://github.com/Azure/azure-storage-fuse/issues/246 that may be related if you are working on millions of blobs.

**Comment by seguler** [comment]
is this still an issue ? @fasigpt @towishy
