### ISSUE TITLE
run "ls", "find" in blobfuse directory found Input/Output Error

### ISSUE THREAD

**Issue by yakonaru** [Azure/azure-storage-fuse#253]
### Which version of the blobfuse was used?

version : 1.0.2

### Which OS (please include version) are you using?
Ubuntu 16.04.5 LTS (Xenial Xerus)
Kernel : 4.15.0-1021-azure

### What problem was encountered?
Found Input/Output Error when we run  ls , find command to list file in blobfuse directory sometime.

In the capture
We try to count the file in blobfuse directory with filter BI files.
Sometime there were returned correct number of file (more than 10000 files in blobfuse) .
Sometime there were returned 0 for number of files with Input/Output Error while all files were existing.
Could you please help to see the capture below? Please find how to correct list file anytime .

![1](https://user-images.githubusercontent.com/48551829/54656217-5f6f0680-4af7-11e9-9698-41f03207465b.png)

### Have you found a mitigation/solution?
-

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
-

### If relevant, please share your mount command.
blobfuse 'mount filesystem directory' --tmp-path=/mnt/azureblobtmp --config-file=/mnt/'configfile' -o ro -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Comment by yakonaru** [comment]
By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

syslog :

Mar 14   04:14:41 <hostname> blobfuse[7363]: list_blobs_hierarchical failed for   the 1 time with errno = 12.
--
Mar 14 04:14:42   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 2   time with errno = 12.
Mar 14 04:14:42   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 3   time with errno = 12.
Mar 14 04:14:43   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 4   time with errno = 12.
Mar 14 04:14:44   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 5   time with errno = 12.
Mar 14 04:14:44   <hostname> azsecmond[1440]: 2019/03/14 04:14:44 Connected to mdsd
Mar 14 04:14:44   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 6   time with errno = 12.
Mar 14 04:14:45   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 7   time with errno = 12.
Mar 14 04:14:45   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 8   time with errno = 12.
Mar 14 04:14:46   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 9   time with errno = 12.
Mar 14 04:14:47   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 10   time with errno = 12.
Mar 14 04:14:47   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 11   time with errno = 12.
Mar 14 04:14:48   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 12   time with errno = 12.
Mar 14 04:14:48   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 13   time with errno = 12.
Mar 14 04:14:49   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 14   time with errno = 12.
Mar 14 04:14:50   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 15   time with errno = 12.
Mar 14 04:14:50   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 16   time with errno = 12.
Mar 14 04:14:51   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 17   time with errno = 12.
Mar 14 04:14:52   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 18   time with errno = 12.
Mar 14 04:14:52   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 19   time with errno = 12.
Mar 14 04:14:53   <hostname> blobfuse[7363]: list_blobs_hierarchical failed for the 20   time with errno = 12.
Mar 14 04:14:53   <hostname> blobfuse[7363]: Failed to list blobs under directory   /mnt/azureblobtmp/<mountpath> on the service during readdir   operation.  errno = 12.

**Comment by seguler** [comment]
Thanks for raising this. We have an upcoming release which I think is going to fix this. Please stay tuned.

**Comment by seguler** [comment]
@yakonaru - could you test a fix we have for this ? The fix is located here: https://github.com/asorrin-msft/azure-storage-fuse-1/commit/c535ae0c89d07b2329167b55f22b346ff427c795

Simply remove line 169: https://github.com/Azure/azure-storage-fuse/blob/master/blobfuse/directoryapis.cpp#L169 and then rebuild from source following instructions [here](https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation#option-2---build-from-source). Does this solve your problem ?

**Comment by yakonaru** [comment]
@seguler 
Do you have any idea to simulate and describe the cause  of this case? Now, I found only this case on production. I cannot test while operation is running.

**Comment by seguler** [comment]
Under heavy load we sometimes find that the internal structures we use for holding list of files can get memory errors when trying to grow. Turns out we grow the list of files unintentionally too much at times, and we have a fix for it but have not been released yet.

Meanwhile what kind of load do you have in your production ? How many directories/files do you try to list and how often ? Perhaps this could help us pinpoint the problem easier.

**Comment by yakonaru** [comment]
@seguler 
Currently we mount for 6 blobfuse. This error blobfuse filesystem are around 50000 files. 
We always find 2 directories are error. each directories ,which were error, are 10000 files (summary size : 400 GB)
The errors always occurred every 1 minutes. Sometime is 1 , 2 , 3 minutes.

Is it possible to reduce heavy load if we seperate Blobfuse directory instead?
For example
Blobfuse  :  /mnt/blobfuse1  > which there are /mnt/blobfuse1/a  and /mnt/blobfuse1/b
seperate to
Blobfuse1  : /mnt/blobfuse1/a
Blobfuse2 :  /mnt/blobfuse1/b

What do you think ?

**Comment by radupaul** [comment]
I still have the same issue, "ls" command in local directory mounted by blobfuse returns:
----------------------
>ls *AAPL*txt
> ls: cannot access '*AAPL*txt': No such file or directory
-------------------------------
--- ! The files are present in the Azure blob

--- in /var/log/syslog
Mar 28 17:57:24 eoldatascivmlx01 blobfuse[26286]: Failed to list blobs under directory /mnt/blobfusetmp/root/7/ on the service during readdir operation.  errno = 12.
Mar 28 17:57:24 eoldatascivmlx01 blobfuse[26286]: Failed to map storage error code 12 to a proper errno.  Returning EIO = 5 instead.

---------------- Sysinfo
blobfuse version: 1.0.2
ubuntu xenial 16.04

--- NOTE: I applied the @yakonaru hack "Simply remove line 169: https://github.com/Azure/azure-storage-fuse/blob/master/blobfuse/directoryapis.cpp#L169" w/o success.
thank you  Radu

**Comment by seguler** [comment]
I apologize. It turns out it is not a 1-line issue. We have a fix in this PR: https://github.com/Azure/azure-storage-fuse/pull/262

Could you test this one for us before we release as a hotfix ?

**Comment by seguler** [comment]
Here is a procedure to try the PR:
git clone https://github.com/azure/azure-storage-fuse
cd azure-storage-fuse
git fetch origin pull/262/head:1.0.3
git checkout 1.0.3
./build.sh
./mount.sh /mymountdir

**Comment by seguler** [comment]
Update: we released the fix yesterday. Binaries will be available in just a few days.

**Comment by radupaul** [comment]
Hi Seguler - that was fast awesome 👍  ... I'm trying it first the "git" right now !

**Comment by radupaul** [comment]
> I apologize. It turns out it is not a 1-line issue. We have a fix in this PR: #262
> 
> Could you test this one for us before we release as a hotfix ?
- apologies I got the alert but looked it up late ... anyway trying now thanks!

**Comment by radupaul** [comment]
I think I can do only from "git fetch origin pull/262/head:1.0.3 ..." on  ... I already I gitted the azure-storage-fues"

**Comment by seguler** [comment]
Sorry ignore my earlier ask to fetch. Because we already released the fix to master, you can simply clone the repository, checkout 'master' (git checkout master), and then build.

**Comment by radupaul** [comment]
ok perfect I'll redo thanks

**Comment by radupaul** [comment]
not sure how to stop the blobfuse process (fusermount -u  /mountpoint still keeps it going)  just kill it (pkill etc ) ? thanks !

**Comment by seguler** [comment]
Just kill it and unmount forcefully - `sudo umount -l /mountpoint`

**Comment by radupaul** [comment]
awesome ! works - also faster :-)

**Comment by seguler** [comment]
Thanks for confirming! I'll close this as it is fixed in 1.0.3.

**Comment by yakonaru** [comment]
@seguler 
Thanks for providing solution.
Do you have any methods to roll back to the old version?
We would like to prepare this method in case there is further issue on new version.
Our business operation cannot wait to do a further fix if there is new issue for new version.


Thank you,

**Comment by seguler** [comment]
Simply reinstall blobfuse from the Linux repository. The version in there is still 1.0.2.

**Comment by danielvdende** [comment]
I am seeing this error with blobfuse when using it with ADLS gen2. Using version 1.3.1
