### ISSUE TITLE
blobfuse: error while loading shared libraries: libgnutls.so.26

### ISSUE THREAD

**Issue by Bougiefever** [Azure/azure-storage-fuse#254]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
16.04

### What problem was encountered?
When issuing the following command: blobfuse /mnt/blobfusetmp/myfilescontainer --tmp-path=/mnt/ramdisk/blobfusetmp --config-file=/home/anbougieadmin/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

I encountered the error:
blobfuse: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
I don't know how to find that out

### If relevant, please share your mount command.
blobfuse /mnt/blobfusetmp/myfilescontainer --tmp-path=/mnt/ramdisk/blobfusetmp --config-file=/home/anbougieadmin/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

**Comment by Bougiefever** [comment]
I was able to resolve this by deleting my VM and starting over with a new one.

**Comment by seguler** [comment]
Sorry about that. For some reason blobfuse could not find libgnutls dependency. The following command would re-install it if you encounter it again:

`sudo apt-get install libcurl4-gnutls-dev libgnutls28-dev`

**Comment by HeffRaleigh** [comment]
Hello!

`sudo apt-get install libcurl4-gnutls-dev libgnutls28-dev` didn't fix this error in my environment.  Any other suggestions?

Here's the command I'm running:
`sudo blobfuse ~/azureblobcars --tmp-path=/mnt/resource/blobfusetmp  --config-file=/root/fuse_connection.cfg -o allow_other attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120`

**Comment by camachorm** [comment]
**I just installed the following version of Blobfuse**
Package: blobfuse
Version: **1.1.1**
Priority: optional
Section: devel
Maintainer: Microsoft - Azure Storage
Installed-Size: 16.0 MB
Download-Size: 4,385 kB
APT-Manual-Installed: yes
APT-Sources: https://packages.microsoft.com/ubuntu/14.04/prod trusty/main amd64 Packages
Description: blobfuse 1.1.1 - FUSE adapter for Azure Blob Storage

**And also installed**
Package: libgnutls30
Version: 3.5.8-5+deb9u4
Priority: standard
Section: libs
Source: gnutls28
Maintainer: Debian GnuTLS Maintainers <pkg-gnutls-maint@lists.alioth.debian.org>
Installed-Size: 2,487 kB
Depends: libc6 (>= 2.22), libgmp10 (>= 2:6), libhogweed4, libidn11 (>= 1.13), libnettle6, libp11-kit0 (>= 0.23.1), libtasn1-6 (>= 4.9), zlib1g (>= 1:1.1.4)
Suggests: gnutls-bin
Homepage: http://www.gnutls.org/
Tag: role::shared-lib
Download-Size: 896 kB
APT-Manual-Installed: yes
APT-Sources: http://mirror.bytemark.co.uk/debian stretch/main amd64 Packages
Description: GNU TLS library - main runtime library
 GnuTLS is a portable library which implements the Transport Layer
 Security (TLS 1.0, 1.1, 1.2) and Secure Sockets Layer (SSL) 3.0 and Datagram
 Transport Layer Security (DTLS 1.0, 1.2) protocols.
 .
 GnuTLS features support for:
  - TLS extensions: server name indication, max record size, opaque PRF
    input, etc.
  - authentication using the SRP protocol.
  - authentication using both X.509 certificates and OpenPGP keys.
  - TLS Pre-Shared-Keys (PSK) extension.
  - Inner Application (TLS/IA) extension.
  - X.509 and OpenPGP certificate handling.
  - X.509 Proxy Certificates (RFC 3820).
  - all the strong encryption algorithms (including SHA-256/384/512 and
    Camellia (RFC 4132)).
 .
 This package contains the main runtime library.


**inspite of this, I still get** 
$ blobfuse
blobfuse: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory

is there any other workaraound for this?

**Comment by AleksCallebat** [comment]
I am getting the same error

blobfuse: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory

I installed libgnutls28-dev with no success, and cannot find libgnutls26

**Comment by yungshinlintw** [comment]
I am hitting the same issue:

base) :~$ sudo apt-get install libcurl4-gnutls-dev libgnutls28-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcurl4-gnutls-dev is already the newest version (7.68.0-1ubuntu2).
libgnutls28-dev is already the newest version (3.6.13-2ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.

(base) :~$ sudo blobfuse ~/invoice --tmp-path=/mnt/resource/blobfusetmp  --config-file=/path/to/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
blobfuse: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory

**Comment by NaraVen** [comment]
Ubuntu 20.04 is not supported at this time. We have not yet prioritized Ubuntu 20.04.

**Comment by donglinz** [comment]
@NaraVen  I am hitting exactly the same issue on Ubuntu 18.04

**Comment by NaraVen** [comment]
@donglinz which version of blobfuse are you using?

**Comment by SnoWolfT** [comment]
> @NaraVen I am hitting exactly the same issue on Ubuntu 18.04

I encounter the same issue in 16.04 and fix that by replacing the "**### wget**" link under "Configure the Microsoft package repository". 

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux
Another example on an Ubuntu 14.04 distribution:

Bash

Copy
wget https://packages.microsoft.com/config/ubuntu**### /14.04/**packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
Similarly, change the URL to .../ubuntu/16.04/... or **### .../ubuntu/18.04/...** to reference another Ubuntu version.


Before:
wget https://packages.microsoft.com/config/ubuntu**### /14.04/**packages-microsoft-prod.deb
After:
wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
