### ISSUE TITLE
Blobfuse is correctly mounted but cannot list or access files under mount point due to a DNS issue

### ISSUE THREAD

**Issue by EstebanLopezF** [Azure/azure-storage-fuse#256]
### Which version of the blobfuse was used?
blobfuse-1.0.2-1.x86_64

### Which OS (please include version) are you using?
Red Hat Enterprise Linux Server release 7.6 (Maipo)

### What problem was encountered?
The blobfuse is correctly mounted however if the customer tries to list the files under that container the process became unresponsive and never returns the output.

We executed the ls command with strace (which is to verbose/debug commands) under the directory where the blobfuse was mounted and it recognize one of the files but it never list them or finish the lstat statement:

openat(AT_FDCWD, "/mnt/azure_blob_nhinpxplatencbackup", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
getdents(3, /* 51 entries */, 32768)    = 3192
lstat("/mnt/azure_blob_nhinpxplatencbackup/ARS_D_1275_lstq5fqi_1_1.bkp.gpg",

### Have you found a mitigation/solution?
not yet.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
With debug_log option:

found in directory  on the service during readdir operation.  Adding to readdir list; fillerResult = 0.
Mar 14 21:12:21 zp-csdb-01.nhsrx.com blobfuse[79313]: Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 349: azs_getattr called with path = /CSProdMigration2_CHC533180023_CopyLog_49ef085953094d109872993792537e82.xml
Mar 14 21:12:21 zp-csdb-01.nhsrx.com blobfuse[79313]: Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 391: Object /mnt/resource/blobfusetmp/root/CSProdMigration2_CHC533180023_CopyLog_49ef085953094d109872993792537e82.xml is not in the local cache during get_attr.
Mar 14 21:12:55 zp-csdb-01.nhsrx.com blobfuse[79313]: Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 349: azs_getattr called with path = /
Mar 14 21:12:55 zp-csdb-01.nhsrx.com blobfuse[79313]: Function azs_statfs, in file /home/seguler/azure-storage-fuse/blobfuse/directoryapis.cpp, line 247: azs_statfs called with path = /.
Mar 14 21:12:55 zp-csdb-01.nhsrx.com blobfuse[79313]: Function azs_getattr, in file /home/seguler/azure-storage-fuse/blobfuse/utilities.cpp, line 349: azs_getattr called with path = /

### If relevant, please share your mount command.

sudo blobfuse /mnt/azure_blob_nhinpxplatencbackup  --tmp-path=/mnt/resource/blobfusetmp  --config-file=/path/to/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

Also with option: '--use-https=true' and '--log-level=LOG_DEBUG'

**Comment by seguler** [comment]
Blobfuse exports the filesystem in the userspace, available only to the user mounting it. Here you are mounting as root, but are you trying to access the data through root as well ? Try dropping sudo, and mount it from the current user.

**Comment by EstebanLopezF** [comment]
Hello Seguler, Thanks for your help.
We mounted it with user-level without root or sudo but unfortunately the behavior/issue is the same.
Also, we tried with a different blob that only contains a couple of files but the issue persisted.
The fuse rpm package is installed, is there any other dependency or configuration that may affect a blobfuse connection?

**Comment by mooninite** [comment]
The issue ended up being with the DNS configuration on the VM. The DNS server configured caused blobfuse to not work correctly. Changing to a different DNS server allowed the "ls" command or any other command to work. The DNS server was also causing the long mount delay. I'm not sure if you want to try and fix an error you can't reproduce @seguler, but we know how to workaround it. This is the only software that we have seen have an issue with our DNS server.

**Comment by seguler** [comment]
This is a possible bug - multiple users have reported that some DNS settings (Ipv6) may result in issues in blobfuse.

**Comment by vibhansa-msft** [comment]
Blobfuse will not work if DNS config is not valid. It will not be able to connect to the storage in such case.

**Comment by samueljamkhandi07** [comment]
I had similar issue and DNS was the cause.
