### ISSUE TITLE
mkdir: cannot create directory ‘directoryname' : Input/output error when using Premium (Page) Blob accounts

### ISSUE THREAD

**Issue by mihammer** [Azure/azure-storage-fuse#263]
### Which version of the blobfuse was used?
Current

### Which OS (please include version) are you using?
Redhat 7.6

### What problem was encountered?
I'm an azure SE at Microsoft. I was helping a customer with an issue. After mounting the blob, he was getting the following when attempting to create a directory: 

 mkdir: cannot create directory ‘directoryname' : Input/output error

### Have you found a mitigation/solution?
Yes - Turns out this was due to the storage account being on premium storage, thus a PAGE BLOB.  Looking closer to the documentation, I found it must be a block blob. 

Can you by any means not allow blobfuse to even mount a page blob so we can avoid this? 
Maybe in a troubleshooting section, name the above error and let users know this is due to mounting a page blob. 

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
n/a

### If relevant, please share your mount command.
n/a

Thanks Guys

**Comment by seguler** [comment]
Thanks @mihammer - I've updated the troubleshooting guide and also put bug label so we can address this in blobfuse - detecting whenever this issue happens before mounting.

**Comment by NaraVen** [comment]
We do not support page blobs in Blobfuse. So closing this one.
