### ISSUE TITLE
Empty directories have modification time at epoch

### ISSUE THREAD

**Issue by anisoptera** [Azure/azure-storage-fuse#264]
### Which version of the blobfuse was used?
Latest master

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
Empty directories have a modification time at the epoch.

This is an issue when trying to zip up files on the blobfuse mount if there's an empty directory - ZIP doesn't support dates before 1980, and epoch is 1970. 

I note that issue #95 was opened for this on files, and directories were punted in that issue, but no follow-up issue was created for directories.

### Have you found a mitigation/solution?
Touching a file in the empty directory (i.e. making it not empty anymore) "solves" the problem, but isn't a real workaround.

**Comment by amnguye** [comment]
Thanks for bringing this issue to our attention. I've been able to reproduce the issue and we will address the issue when we can. I will update this thread if I have any other questions or news of this bug.

**Comment by vibhansa-msft** [comment]
Last modified time issues have been fixed in version 1.3.1
