### ISSUE TITLE
Blobfuse leaves unreadable mount/container directory

### ISSUE THREAD

**Issue by jolguk** [Azure/azure-storage-fuse#266]
### Which version of the blobfuse was used?

blobfuse 1.0.2
### Which OS (please include version) are you using?
Ubuntu 16.04 and 18.04

### What problem was encountered?
The storage appears to mount - it doesn't generate an error, but you are subsequently unable to cd into the container directory and it seems unreadable to the o/s. 
### Have you found a mitigation/solution?

no
### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

No
### If relevant, please share your mount command.
jolguk@jolgukubuntu:~$ sudo mkdir /mnt/ramdisk
jolguk@jolgukubuntu:~$ sudo mount -t tmpfs -o size=16g tmpfs /mnt/ramdisk
jolguk@jolgukubuntu:~$ sudo mkdir /mnt/ramdisk/blobfusetmp
jolguk@jolgukubuntu:~$ sudo chown jolguk /mnt/ramdisk/blobfusetmp
jolguk@jolgukubuntu:~$ vi fuse_connection.cfg
jolguk@jolgukubuntu:~$ vi fuse_connection.cfg
jolguk@jolgukubuntu:~$ chmod 600 fuse_connection.cfg
jolguk@jolgukubuntu:~$ pwd
/home/jolguk
jolguk@jolgukubuntu:~$ mkdir jolguk
jolguk@jolgukubuntu:~$ sudo blobfuse mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/jolguk/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
fuse: bad mount point `mycontainer': No such file or directory
jolguk@jolgukubuntu:~$ sudo blobfuse /home/jolguk/jolguk --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/jolguk/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
jolguk@jolgukubuntu:~$ df -k
Filesystem     1K-blocks    Used Available Use% Mounted on
udev             4075004       0   4075004   0% /dev
tmpfs             816924   25196    791728   4% /run
/dev/sda1       30428648 1168808  29243456   4% /
tmpfs            4084612       0   4084612   0% /dev/shm
tmpfs               5120       0      5120   0% /run/lock
tmpfs            4084612       0   4084612   0% /sys/fs/cgroup
/dev/sdb1       16381800   45056  15481556   1% /mnt
tmpfs             816924       0    816924   0% /run/user/1000
tmpfs           16777216       0  16777216   0% /mnt/ramdisk
jolguk@jolgukubuntu:~$ cd jolguk
-bash: cd: jolguk: Permission denied
jolguk@jolgukubuntu:~$ ls -lrt
ls: cannot access 'jolguk': Permission denied
total 8
d????????? ? ?      ?         ?            ? jolguk
-rw-rw-r-- 1 jolguk jolguk 2452 Nov 27  2017 packages-microsoft-prod.deb
-rw------- 1 jolguk jolguk  149 Apr  9 08:28 fuse_connection.cfg

**Comment by seguler** [comment]
Because you are mounting as root. As the documents say, blobfuse exposes the mountpoint to the current user who mounts blobfuse. In your case that is root. See this section: https://github.com/Azure/azure-storage-fuse/wiki/2.-Configuring-and-Running#allow-other-users-or-root-access-to-the-mount

**Comment by WilliamZhaoz** [comment]
Hi @seguler 
I hit the same problem, with adding -o allow_other.
The storage appears to mount - it doesn't generate an error, but some dirs can not accessed
when I run `ls myblob`, I get:
ls: cannot access 'speech-dataset/960hrs_50reverb': No such file or directory
and the rest dirs are accessed.

**Comment by NaraVen** [comment]
Which distro of linux and which version of blobfuse are you using?

**Comment by mhatreabhay** [comment]
> Hi @seguler
> I hit the same problem, with adding -o allow_other.
> The storage appears to mount - it doesn't generate an error, but some dirs can not accessed
> when I run `ls myblob`, I get:
> ls: cannot access 'speech-dataset/960hrs_50reverb': No such file or directory
> and the rest dirs are accessed.

Seeing same issue. on ubunut 18.04 blobfuse 1.2.3

**Comment by NaraVen** [comment]
Could you please attach the syslog entries about 200 lines around the time period this happened?

**Comment by NaraVen** [comment]
We repro'd the issue and fixed it. Please upgrade to version 1.2.4 and all the dirs should be accessible.
