### ISSUE TITLE
what if two blobfuse mounts have same `tmp-path` path

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#267]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Ubuntu

### What problem was encountered?
The first alpha version of [blobfuse CSI driver on Kubernetes](https://github.com/csi-driver/blobfuse-csi-driver) is almost complete. I have one question:
I set `tmp-path` value of blobfuse to `/mnt/blobfuse` in the driver, that means two blobfuse mounts have same `tmp-path` value, will there be race condition?

@seguler

**Comment by seguler** [comment]
Blobfuse takes a lock on the files and keep the lock in a mutex within the process. Another blobfuse process would bypass this lock and cause data corruption. Each blobfuse process should have a separate tmp cache.

**Comment by andyzhangx** [comment]
@seguler  thanks, I created a PR to fix this issue.
