### ISSUE TITLE
Publish package sources

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-storage-fuse#270]
.deb and .rpm files are offered at packages.microsoft.com but the packaging scripts (e.g. RPM SPEC) are not found in the repository, and no src.rpm files are offered in the repos.

**Comment by NaraVen** [comment]
https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux is the link to where the packages are uploaded. Also if you run the generaterpm.sh script in the blobfuse directory it will generate the RPM for you. The SPEC is included.
We will also be publishing signed versions to packages.microsoft.com soon.
Closing this issue.

**Comment by stewartadam** [comment]
A few point of feedback (happy to break those out as different issues):
1. Spec file should be included in the repo, not as an inline heredoc
2. The script should not make assumptions about where users build RPMs, `~/rpmbuild` is the default but not always the case (and is configured by rpmmacros)
3. The script appears to build a custom tarball from the repo, it should use a tarball as released from GitHub, e.g. `https://github.com/Azure/azure-storage-fuse/archive/blobfuse-%{VERSION}-Linux.zip`
4. most importantly, this script **should absolutely not** silently overwrite a user's `~/rpmbuild/.rpmmacros` file
