### ISSUE TITLE
feature request: mount all containers

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-storage-fuse#271]
A nice feature would be to make the --container-name flag truly optional and simply expose containers as top-level directories in the mounted filesystem instead, permitting access to any container. This would of course require an account key.

**Comment by vibhansa-msft** [comment]
This feature will not be added to blobfuse. We are working no next generation of blobfuse and preview release is already posted on github. Blobfuse2 has a command "mount all" which takes the storage account and mounts all the containers into different local directories. It also has feature of allow-list and deny-list where you can only mount certain containers from the list or skip mounting certain containers from your storage account,
