### ISSUE TITLE
NSG (firwall) settings

### ISSUE THREAD

**Issue by GoldenMouse** [Azure/azure-storage-fuse#273]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
CentOS 7.6

### What problem was encountered?
Currently we block internet out using Azure NSG for our VM. 
Rule is Source Any, Destination Internet for Outbount Rules.  

What endpoints/ports should I be opening if I want to allow BlobFuse but still disallow Internet Out?

**Comment by amishra-dev** [comment]
@GoldenMouse You would have to open up port 80 (HTTP). I would recommend checking the setting for CentOS to see if you can just open it up for your blob url.

**Comment by GoldenMouse** [comment]
@amishra-dev Oh of course the Storage URL endpoint. It's too bad Azure Network Gateway only allow filtering by IP and not DNS. So I can't simply allow 443 to myblobstorage.blob.core.windows.net .  We don't use iptables or any kind of VM base firewall.

**Comment by amishra-dev** [comment]
You're welcome. Glad your issue was resolved.
