### ISSUE TITLE
Debian support for Blobfuse?

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/azure-storage-fuse#275]
### Which version of the blobfuse was used?
* Latest

### Which OS (please include version) are you using?
* Debian

### What problem was encountered?
* Question is fairly quick, I remember there was debian support for blobfuse is it no longer the case. Please also refer to the chatter here: https://github.com/MicrosoftDocs/azure-docs/issues/28906 
* Any directions or plan to add them back again?

### Have you found a mitigation/solution?
* Mainly a question to make sure that blobfuse donot support debian anymore?

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
* N/A

### If relevant, please share your mount command.
* N/A

**Comment by amnguye** [comment]
Hi Tatsinnit,

Support for Debian is currently not on the roadmap for blobfuse. We are open to feedback and looking into it if the interest in this becomes larger.

Amanda

**Comment by chaim1221** [comment]
You support Ubuntu but not Debian? Isn't that a little bit like supporting Windows but not MS-DOS? Makes no sense.

**Comment by amnguye** [comment]
We are currently looking into supporting blobfuse on Debian

**Comment by chaim1221** [comment]
Great! FYI for the time being, it works to run an Ubuntu container on Debian (or, I'd imagine, any OS running Docker) as described in #250 :)

**Comment by amnguye** [comment]
We've made a release on Debian, if there's any issues with this build please make a new issue, as this issue was in regards to asking for support.

**Comment by tepebox** [comment]
Any progress on this? Looking to transfer data from a RasPi to Azure... Blobfuse would be great...

**Comment by chaim1221** [comment]
> Any progress on this? Looking to transfer data from a RasPi to Azure... Blobfuse would be great...

scroll up...just a bit further...

**Comment by tepebox** [comment]
Hi,

yes... saw that too late... However it's still not available to Rasipian/Raspberry OS...

Thanks,


Thomas
________________________________

**Comment by amnguye** [comment]
Hi, Could you make a new issue regarding support for Rasipian/Rasberry OS? This issue is regarding supporting Debian.

You are also free to make your own build for this OS and if you have trouble making the release please let us know and we will try to support you.
