### ISSUE TITLE
ls /mount/backups fails, no logs

### ISSUE THREAD

**Issue by chaim1221** [Azure/azure-storage-fuse#277]
### Which version of the blobfuse was used?
blobfuse 1.0.3

### Which OS (please include version) are you using?
Docker version 18.09.5, build e8ff056dbc
ubuntu:18.04 (see #250 for my setup)

### What problem was encountered?
`blobfuse /mount/backups/ --tmp-path=/mnt/blobfusetmp/ -o allow_root -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 --container-name=$AZURE_CONTAINER_NAME` hangs forever, then exits with status 0 leaving no logs

`ls /mount/backups` has same behaviour

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No, it doesn't even exist (`/var/log/syslog`)

### If relevant, please share your mount command.
see above

**Comment by amnguye** [comment]
Looks like most Docker Containers don't run systemd or journald which means that rsyslog is not listening and that you would have to install rsyslog in order for this to be enabled. Which means most likely you will have to look in another folder for your syslogs
https://unix.stackexchange.com/questions/395841/docker-debian-jessie-cant-find-var-log-syslog

As for your issue of unable to call
> ls /mount/backups
I'm wondering if it has a communication issue with storage. Do you get a DNS resolution when using 
>nslookup accountName.blob.core.windows.net
There might be an issue with the account and container you are trying to mount. If you have anything invalid in your configuration file, this might be why it hangs forever. Also trying between a SAS token or account key might help as well. I'm trying to name all the possible reasons why it's hanging and not mounting.

**Comment by chaim1221** [comment]
It turned out to be a networking issue. I was routing traffic out on the intranet. 🤦‍♂ 

Thank you!
