### ISSUE TITLE
Support for Azure Data Lake storage gen2

### ISSUE THREAD

**Issue by sondberg** [Azure/azure-storage-fuse#278]
### Which version of the blobfuse was used?
1.0.3

### Which OS (please include version) are you using?
Ubuntu 18.04.2 LTS

### What problem was encountered?
Unable to mount blob gen2 

### Have you found a mitigation/solution?
No workarounds if we need to mount locally.

### If relevant, please share your mount command.
sudo blobfuse ~/mnt_dir --tmp-path=/mnt/resource/blobfusetmp --config-file=/path_to_cfg/fuse_connection.cfg -o attr_time=240 -o entry_timeout=240 -o negative_timeout=120

The content of fuse_connection.cfg is:

accountName <storage_account>
accountKey <secret>
containerName <container>

**Comment by amnguye** [comment]
Hi Sondberg,

Your fuse_connection.cfg file is missing two things. You should provide a accountKey and containerName. I'm assuming you left it blank since you provided that you did provide the .cfg file a <storage_account> but not a <account_key> and <container_name>

**Comment by sondberg** [comment]
@amnguye - yes thanks for noting this - but I only left them blank here while I for sure filled them out on my test installation.

**Comment by mengxr** [comment]
@amnguye Does blobfuse support ADLSv2 already? I saw BLOB API is disabled in ADLSv2 here: https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-known-issues#blob-storage-apis. Just want to confirm.

**Comment by amnguye** [comment]
@sondberg  @mengxr 
Currently blobfuse does not support ADLS

**Comment by vibhansa-msft** [comment]
Version 1.3.1 supports ADLS gen-2 account. Kindly refer README on how to configure blobfuse for the same.
