### ISSUE TITLE
fuse: device not found on WSL

### ISSUE THREAD

**Issue by petarvucetin** [Azure/azure-storage-fuse#282]
### Which version of the blobfuse was used?
Get:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 blobfuse amd64 1.0.3 [5068 kB]
Fetched 5068 kB in 1s (10.1 MB/s)
Selecting previously unselected package blobfuse.
(Reading database ... 106757 files and directories currently installed.)
Preparing to unpack .../blobfuse_1.0.3_amd64.deb ...
Unpacking blobfuse (1.0.3) ...
Setting up blobfuse (1.0.3) ...

### Which OS (please include version) are you using?
Windows 10 WSL

### What problem was encountered?
fuse: device not found, try 'modprobe fuse' first

  $ modprobe fuse
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17763-Microsoft/modules.dep.bin'
modprobe: FATAL: Module fuse not found in directory /lib/modules/4.4.0-17763-Microsoft

### Have you found a mitigation/solution?
No

### If relevant, please share your mount command.
sudo blobfuse ~/event-hub-asa-input-files --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/petar/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

**Comment by amnguye** [comment]
Currently blobfuse does not support Windows 10 WSL.

What version of WSL do you have?

**Comment by amnguye** [comment]
Hi, did you still need help on this issue?

**Comment by bissont** [comment]
I'd like to see blobfuse support Windows 10 WSL

**Comment by amnguye** [comment]
FUSE is not supported on Windows WSL, therefore blobfuse cannot be supported on WSL due to that dependency.

**Comment by bissont** [comment]
I see. Thanks.

**Comment by bissont** [comment]
Hi, I just wanted to follow up and say that BlobFuse does with with WSL -- you just have to use "WSL 2".
