### ISSUE TITLE
Cannot turn https off by using --use-https=false

### ISSUE THREAD

**Issue by ashapte** [Azure/azure-storage-fuse#283]
### Which version of the blobfuse was used?
blobfuse 1.0.2

### Which OS (please include version) are you using?
RHEL 7.6

### What problem was encountered?
While mounting a container with the option --use-https=false, always gives error:
_Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 400_

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Nothing relevant was found other than the same error on the console.

### If relevant, please share your mount command.

blobfuse "mount point name" --container-name="container name" --tmp-path="cache folder" --log-level=LOG_DEBUG --use-https=false

**Comment by a139786** [comment]
Apologies if this occurs as a silly question - have you checked that your containers actually are available over http (either in the portal or with storage explorer)?

Thanks and Regards,
Barry Anderson
(Security) Solution Architect, (Enterprise Splunk|Security Uplift Program)
m: +61 412 051 878
t : +61 3 8633 7217
e : barry.anderson@agl.com.au

________________________________

**Comment by ashapte** [comment]
@Barry: I am not sure how to check that, is there a specific way to do that? I had assumed that if https url works, so should http, is that different in case of Azure? ... Thanks

**Comment by a139786** [comment]
Your administrator (or the storage owner) may have configured it to only allow https access - it could even be the default now, I don’t remember. You can check in the portal or use storage explorer to test.

Thanks and Regards,
Barry Anderson
(Security) Solution Architect, (Enterprise Splunk|Security Uplift Program)
m: +61 412 051 878
t : +61 3 8633 7217
e : barry.anderson@agl.com.au

________________________________

**Comment by amnguye** [comment]
If you access your storage account and check if you selected allowing HTTP and HTTPS for your allowed protocols. Then you've allowed the account to be accessed by HTTP.

**Comment by amnguye** [comment]
Hi @ashapte were you able to find a solution to your problem?

**Comment by xiangwu-ms** [comment]
One of the possibilities is to go to storage account to check the configuration, secure transfer required enabled or not.

**Comment by ashapte** [comment]
Sorry for the delayed response ... Thanks for the help @amnguye ... I did exactly what @xiangwu-ms mentioned and it worked fine. 

It would really help if this documented somewhere.
