### ISSUE TITLE
Not able to build blobfuse

### ISSUE THREAD

**Issue by amitwac** [Azure/azure-storage-fuse#287]
### Which version of the blobfuse was used?
blobfuse master branch source code

### Which OS (please include version) are you using?
RHEL 7.3

### What problem was encountered?
I am trying to build blobfuse from source code of master branch. When I try to run build.sh script, it gives below error :

# ./build.sh
mkdir: cannot create directory ‘build’: File exists
./build.sh: line 16: cmake3: command not found
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
 Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
 /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
 /usr/local/share/cmake-3.15/Modules/FindCURL.cmake:143 (find_package_handle_standard_args)
 CMakeLists.txt:124 (find_package)

-- Configuring incomplete, errors occurred!
See also "/azure-storage-fuse/build/CMakeFiles/CMakeOutput.log".
See also "/azure-storage-fuse/build/CMakeFiles/CMakeError.log".
cmake failed.  Please ensure that cmake version 3.5 or greater is installed and available.

I also checked the CMakeError.log file, snippet of which is below :

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /azure-storage-fuse/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_a13fc/fast && /usr/bin/gmake -f CMakeFiles/cmTC_a13fc.dir/build.make CMakeFiles/cmTC_a13fc.dir/build
gmake[1]: Entering directory `/azure-storage-fuse/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a13fc.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_a13fc.dir/src.c.o   -c /azure-storage-fuse/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_a13fc
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a13fc.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    -rdynamic CMakeFiles/cmTC_a13fc.dir/src.c.o  -o cmTC_a13fc
CMakeFiles/cmTC_a13fc.dir/src.c.o: In function `main':
src.c:(.text+0x2d): undefined reference to `pthread_create'
src.c:(.text+0x39): undefined reference to `pthread_detach'
src.c:(.text+0x4a): undefined reference to `pthread_join'
src.c:(.text+0x5e): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_a13fc] Error 1
gmake[1]: Leaving directory `/azure-storage-fuse/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_a13fc/fast] Error 2
#

my PATH is :  
/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/lib64/

# locate libpthread.so
/usr/lib/x86_64-redhat-linux6E/lib64/libpthread.so
/usr/lib64/libpthread.so
/usr/lib64/libpthread.so.0
#

### Have you found a mitigation/solution?
No

**Comment by amnguye** [comment]
Looks like you havent installed all the dependencies

Required dependencies to compile Blobfuse are: fuse-dev, libcurl-dev, gnutls-dev, libgcrypt-dev, uuid-dev.

sudo yum install git cmake fuse-devel libcurl-devel gcc gcc-c++ gnutls-devel libgcrypt-devel libuuid-devel fuse -y

https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation

**Comment by xiangwu-ms** [comment]
Your cmake 3 is not installed.

**Comment by NaraVen** [comment]
I verified this works now. We also have rpms uploaded to https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux. So, closing this for now.
