### ISSUE TITLE
Issues accessing files in blob

### ISSUE THREAD

**Issue by mcooper** [Azure/azure-storage-fuse#288]
### Which version of the blobfuse was used?
blobfuse 1.0.3

### Which OS (please include version) are you using?
Ubuntu 18.04.2 LTS

### What problem was encountered?
I have mounted a blob, but am unable to read files withig the blob.  I have made sure my mountpoint at `~/mountpoint` and the temporary file at `/mnt/blobfusetemp` have my local user as the owner.  I can create folders in `~/mountpoint` using `mkdir`, but I cannot write or read the files in the folders, either as a local user or as a superuser with `sudo`.

    echo "test" > test.txt
    -bash: test.txt: Permission denied

    sudo echo "test" > test.txt
    -bash: test.txt: Permission denied

When I copy a file into the blob container using Azure Storage Explorer and try to view it:

    cat myfile.csv
    cat: myfile.csv: No such file or directory

    sudo cat myfile.csv
    cat: myfile.csv: No such file or directory

even though the file is definitely there:

    ls -l
    total 0
    -rwxrwxrwx 1 mattcoop mattcoop  338 Jul 12 10:24 myfile.csv

### Have you found a mitigation/solution?
No.  I tried adding `-o allow_other`, but it still doesnt work.

### If relevant, please share your mount command.
`blobfuse ~/mountpoint --tmp-path=/mnt/blobfusetemp --config-file=.fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other`

**Comment by a139786** [comment]
Matt,
Not in front of anything at the moment so can’t check this but just in case it helps you, I don’t suppose it’s your permissions to the tmp-path?

Thanks and Regards,
Barry Anderson
(Security) Solution Architect, (Enterprise Splunk|Security Uplift Program)
m: +61 412 051 878
t : +61 3 8633 7217
e : barry.anderson@agl.com.au

________________________________

**Comment by mcooper** [comment]
Hi Barry, thanks for the quick feedback.  I definitely made sure to perform `chown mattcoop /mnt/blobfusetemp`

**Comment by a139786** [comment]
Just one thing in my mount command I also use -o uid=1002 -o gid=1002 which in my case are the uid and gid for splunk but in your case should be replaced by those for mattcoop. Hope that helps!

Thanks and Regards,

Barry Anderson

Solution Architect, Security Uplift Program

m: +61 412 051 878
t  : +61 3 8633 7217
e : barry.anderson@agl.com.au<mailto:barry.anderson@agl.com.au>

[cid:11E14031-FE1A-4090-9EBF-AF95138F6AD4]

Have a Cybersecurity Question?
CybersecurityQuestion@agl.com.au<mailto:CybersecurityQuestion@agl.com.au>

[Cybersecurity_v1_0_Cyan]

At AGL we work flexibly – so while it suits
me to email now, please feel free to respond
at a time that suits your working hours.

**Comment by mcooper** [comment]
That didnt work either

**Comment by a139786** [comment]
Guess we’ll have to wait for someone more clueful than I to chime in. Just to double-check: the creds you are using in your connection.cfg definitely have read/write access on the blobs, correct (because you can have list without having read/write)? Sorry I couldn’t help you.

Thanks and Regards,

Barry Anderson

Solution Architect, Security Uplift Program

m: +61 412 051 878
t  : +61 3 8633 7217
e : barry.anderson@agl.com.au<mailto:barry.anderson@agl.com.au>

[cid:11E14031-FE1A-4090-9EBF-AF95138F6AD4]

Have a Cybersecurity Question?
CybersecurityQuestion@agl.com.au<mailto:CybersecurityQuestion@agl.com.au>

[Cybersecurity_v1_0_Cyan]

At AGL we work flexibly – so while it suits
me to email now, please feel free to respond
at a time that suits your working hours.

**Comment by amnguye** [comment]
Could you provide the details of both folders (~/mountpoint) and (/mnt/blobfusetmp) (e.g. ls -l) ?

Could you also add "--log-level=LOG_DEBUG" to your mount command and see if there's anything produced in the syslog (/var/log/syslog) by blobfuse when attempting to access these files within your mounted container?

I am failing to reproduce your issue.

**Comment by mcooper** [comment]
I re-sized the vm and when I did `/mnt/blobfusetmp` got deleted.  After re-creating it and re-mounting, the issue went away, so I'm guessing it was a problem with the permissions on that folder.

Thanks for the help.
