### ISSUE TITLE
File copied to blobfuse inherit execute permission

### ISSUE THREAD

**Issue by xerothermic** [Azure/azure-storage-fuse#289]
### Which version of the blobfuse was used?
blobfuse 1.0.3

### Which OS (please include version) are you using?
Ubuntu 18.04.2 LTS

### What problem was encountered?
Files copied into blobfuse destination should not automatically inherit execute permissions.

I can read/write files to the mounted directory, and the files are transmitted to the Azure cloud.
However, all the files which had no execute permission once copied into these directory inherit execute permission.
-rwxrwx---  1 user user 4827 Jul 14 06:10 Rplots.pdf

I'm executing these commands (both mounting and file ops) as non-root user.

### Have you found a mitigation/solution?
No

### If relevant, please share your mount command.
blobfuse --container-name=stats --tmp-path=/mnt/ cloud/

**Comment by amnguye** [comment]
It seems that the files are inheriting the permissions of the parent directory that it's being moved to. This does seem like a bug, but at the same time these might be necessary permissions in order for blobfuse to perform the operations it needs to do.  I will label this as a bug and needing investigation for now.

Is there a reason giving execute permissions on the files moved to your mounted container directory would be a problem for you?

**Comment by vibhansa-msft** [comment]
Can you share your complete mount command. Are you using '-o allow_other' option during mount.

**Comment by vibhansa-msft** [comment]
Kindly revert back if you have any further query.
