### ISSUE TITLE
cache forever

### ISSUE THREAD

**Issue by cometta** [Azure/azure-storage-fuse#290]
if i set `--file-cache-timeout-in-seconds=-1`, will it cache forever ?

**Comment by amnguye** [comment]
No. Blobfuse has to eventually clear the cache in order for efficiency and due to the nature of a cache, it is only temporary as well.

**Comment by amnguye** [comment]
Does this clear up your question or does more clarity need to be addressed on this question?

**Comment by cometta** [comment]
clarified. Thank you
