### ISSUE TITLE
apt-get Ubuntu 18.10 blobfuse not found

### ISSUE THREAD

**Issue by tgkprog** [Azure/azure-storage-fuse#294]
### Which version of the blobfuse was used?
trying to install latest

### Which OS (please include version) are you using?
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

### What problem was encountered?

last step from https://docs.microsoft.com/en-us/windows-server/administration/Linux-Package-Repository-for-Microsoft-Software does not work

$    sudo apt-get install blobfuse
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package blobfuse

All Commands
  curl https://packages.microsoft.com/config/ubuntu/18.10/prod.list > ./microsoft-prod.list
   sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
   curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
   sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
   sudo apt-get update
   sudo apt-get install blobfuse

Commands output

$ curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0   1471      0 --:--:-- --:--:-- --:--:--  1471

$    sudo apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://deb.nodesource.com/node_10.x cosmic InRelease                                                                                          
Hit:3 http://in.archive.ubuntu.com/ubuntu cosmic InRelease                                                                                           
Hit:4 http://packages.microsoft.com/repos/vscode stable InRelease                                                                                    
Ign:5 http://repos.azulsystems.com/ubuntu stable InRelease                                                                                           
Get:6 http://in.archive.ubuntu.com/ubuntu cosmic-updates InRelease [88.7 kB]                                                                         
Hit:7 http://repos.azulsystems.com/ubuntu stable Release                                                                                             
Hit:8 http://dl.google.com/linux/chrome/deb stable Release                                                                                           
Hit:9 https://packages.microsoft.com/ubuntu/18.10/prod cosmic InRelease                                                                              
Get:10 http://in.archive.ubuntu.com/ubuntu cosmic-backports InRelease [74.6 kB]                                                                     
Hit:11 http://ppa.launchpad.net/linuxuprising/java/ubuntu cosmic InRelease                                
Hit:12 http://security.ubuntu.com/ubuntu cosmic-security InRelease                                        
Fetched 163 kB in 2s (82.7 kB/s)                   
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://packages.microsoft.com/ubuntu/18.10/prod cosmic InRelease' doesn't support architecture 'i386'

$    sudo apt-get install blobfuse
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package blobfuse
 
 Also tried

  sudo apt-get clean
  sudo apt-get update

then

   sudo apt-get install blobfuse

No cigar.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

NA

**Comment by Tatsinnit** [comment]
This is consistent with with `bionic` as well:

![image](https://user-images.githubusercontent.com/6233295/62014437-19d4ef80-b1f5-11e9-84f5-c3128ad3bb64.png)

**Comment by Tatsinnit** [comment]
**Solution** hey @tgkprog  - here is the solution:

* I think you need to configure your `apt` repository for Microsoft product.
* Mentioned here: https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation 

* So, you can change the version of Ubuntu you are using accordingly I tried this in **Bionic** 

```
wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
```
**Working**

![image](https://user-images.githubusercontent.com/6233295/62017638-8955d980-b20b-11e9-93dd-152fe6d5ddab.png)

**Comment by Tatsinnit** [comment]
**Solution 2** works as well: follow the steps mentioned here: 

Seems like this is working as well atleast for `bionic` 
* I will lets blobfuse folks to comment on the specific `i386` arch based issue here which I can see in your update.



![image](https://user-images.githubusercontent.com/6233295/62018451-e0a97900-b20e-11e9-9213-2de910e4c696.png)

**Comment by amnguye** [comment]
Thanks for your help on this issue Tatsinnit. 

In regards to the i386 architecture, I will pretty much reiterate what Sercan said in #121 issue. We are not looking to release binaries for non-x86 platforms. But we will do as much as we can to help you when building blobfuse on non-x86 platforms.

@tgkprog Does Tatsinnit's input help with this issue? Or do you need more help or clarity?

**Comment by Tatsinnit** [comment]
:bulb: @amnguye - I think we should **close** this unless user specify and give us more information, this is definitely associated the issue I have mentioned above and relates to arch which bfuse dont support. Thanks!

**Comment by tgkprog** [comment]
Thank you, not using azure at the moment. But I think should update the docs. For ubuntu 20.04 too, current LTS.
