### ISSUE TITLE
Input/Output error when reading or writing data

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-storage-fuse#296]
### Which version of the blobfuse was used?
1.0.3

### Which OS (please include version) are you using?
n/a

### What problem was encountered?
random input/output error message from python script calling blobfuse.

This occurs on an Azure Machine Learning service.

![image](https://user-images.githubusercontent.com/48961492/62235292-7cf38d00-b381-11e9-9ca5-9f89b6178b1c.png)

### Have you found a mitigation/solution?
no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
n/a

### If relevant, please share your mount command.
n/a

**Comment by rishabpoh** [comment]
This issue has been fixed in the latest version of Blobfuse.
