### ISSUE TITLE
Is there a similar azure storage driver for windows?

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#30]
Not related to this repo issue. 
Just curious, Is there a similar azure storage plugin for windows?
I am now enabling this plugin for kubernetes on linux, would like to know if there is a similar windows driver. Thanks.

**Comment by seguler** [comment]
At this moment - we do not have a windows adapter, but we are looking for ways to enable this on Windows in the future.

**Comment by andyzhangx** [comment]
thanks for the check, just let me know if you have in the future, I would also like to enable such driver for k8s on windows.

**Comment by seguler** [comment]
Closing this as this isn't something we can resolve in this repository,
