### ISSUE TITLE
Possible CA problem in blobfuse

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#303]
### Which version of the blobfuse was used?
blobfuse.x86_64 1.0.2-1

### Which OS (please include version) are you using?
Server OS:  Red Hat Enterprise Linux Server release 7.6 (Maipo)

### What problem was encountered?
Sorry to post this here, but from my work computer I can not reach any .io domain.

Server OS:  Red Hat Enterprise Linux Server release 7.6 (Maipo)
blobfuse version:  blobfuse.x86_64 1.0.2-1

In our configuration we are not connecting directly from our server to the Azure storage.  We are going through a proxy/load balancer that intercepts the traffic and then forwards it to Azure.  When we try to connect we get the following entries for blobfuse in /var/log/messages:

  Aug 12 15:02:55 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 1 time with errno = -1352207232.
  Aug 12 15:10:06 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 2 time with errno = 1932808281.
  Aug 12 15:17:39 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 3 time with errno = 1932808281.
  Aug 12 15:24:33 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 4 time with errno = 1932808281.
  Aug 12 15:31:44 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 5 time with errno = 1932808281.
  Aug 12 15:38:36 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 6 time with errno = 1932808281.
  Aug 12 15:46:16 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 7 time with errno = 1932808281.
  Aug 12 15:53:09 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 8 time with errno = 1932808281.
  Aug 12 15:59:49 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 9 time with errno = 1932808281.
  Aug 12 16:06:40 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 10 time with errno = 1932808281.
  Aug 12 16:14:04 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 11 time with errno = 1932808281.
  Aug 12 16:20:49 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 12 time with errno = 64.
  Aug 12 16:27:25 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 13 time with errno = 64.
  Aug 12 16:34:15 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 14 time with errno = 64.
  Aug 12 16:40:59 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 15 time with errno = 64.
  Aug 12 16:47:38 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 16 time with errno = 64.
  Aug 12 16:54:05 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 17 time with errno = 64.
  Aug 12 17:01:14 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 18 time with errno = 64.
  Aug 12 17:07:57 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 19 time with errno = 64.
  Aug 12 17:15:41 radfw6 blobfuse[60122]: list_blobs_hierarchical failed for the 20 time with errno = 64.
  Aug 12 17:15:41 radfw6 blobfuse[60122]: Failed to list blobs under directory /mnt/ramdisk/root/ on the service 
  during readdir operation.  errno = 64.

When we do a network capture we see the following error:
  10 0.222327  ww.xx.60.101  yy.zz.95.130    TLSv1.2   75  Alert (Level:  Fatal, Description: Unknown CA)

After that line we see a connection reset.

I tried to look up the errors from the syslog, but did not have much luck.  The error in the network traffic seemed to indicate that it did not like the certificate authority that signed the certificate on the proxy.  Since blobfuse is written in Python, and Python uses OpenSSL I added the CA information to the OpenSSL certs directory and I can now verify the proxy certificates with OpenSSL but I still can't get blobfuse to connect.  So my questions are:
  Is this just a problem with the Certificate Authority that signed the certificate?
  Where does blobfuse store certificate information?
  How do I add additional Certificate Authorities to blobfuse? 

Any help would be greatly appreciated.

### If relevant, please share your mount command.

this issue is posted by @Jim243

**Comment by amnguye** [comment]
Hi @jim243,

Just for clarification, blobfuse is not written in python.

Also by the looks of it I would double check if your connection information you've provided is correct. 

A bad storage account would cause an error like this with this many failures. If this blobfuse tries to connect for about 20 minutes, this is a symptom of a bad storage account entered or other connection information provided is not valid.

There might be a problem with the CA that signed the certificate. Also blobfuse does not store the certificate information or have an ability to add additional certificate authorities to blobfuse.

**Comment by NaraVen** [comment]
@andyzhangx , this is a Curl error when Curl is trying to verify and Http request. In this case the peer certificate is missing. blobfuse Curl needs to  tunnel through the proxy so that it can do TLS all the way, without any middle man, in this case to your remote server. To establish trust it will verify the Cert chain.

There  are 2 ways to fix this
1) you can install the certificate bundle from http://curl.haxx.se/ca/cacert.pem  so that blobfuse can verify the peer locally
OR
2) We can fix it by turning off Peer certificate verification in  blobfuse so that Curl does not attempt to. 

I think Option 2) is a security loophole so would you be able to try out option 1) and update this thread.
If this is no longer an issue could you please close this issue?

**Comment by andyzhangx** [comment]
thanks for explanation.
