### ISSUE TITLE
Unable to build on CentOS 7

### ISSUE THREAD

**Issue by arvindshmicrosoft** [Azure/azure-storage-fuse#305]
### Which version of the blobfuse was used?
Attempting to build from source

### Which OS (please include version) are you using?
CentOS 7.5

### What problem was encountered?
Following the Wiki, installed pre-requisites for building, but ./build.sh fails:

bash: go: command not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/someuser/azure-storage-fuse/build
[  2%] Building CXX object CMakeFiles/blobfuse.dir/blobfuse/fileapis.cpp.o
In file included from /home/someuser/azure-storage-fuse/blobfuse/blobfuse.h:32:0,
                 from /home/someuser/azure-storage-fuse/blobfuse/fileapis.cpp:1:
/home/someuser/azure-storage-fuse/azure-storage-cpp-lite/include/blob/blob_client.h:7:24: fatal error: shared_mutex: No such file or directory
 #include <shared_mutex>
                        ^
compilation terminated.
make[2]: *** [CMakeFiles/blobfuse.dir/blobfuse/fileapis.cpp.o] Error 1
make[1]: *** [CMakeFiles/blobfuse.dir/all] Error 2
make: *** [all] Error 2

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Not applicable

### If relevant, please share your mount command.
Not applicable

**Comment by joy4eg** [comment]
Try to upgrade GCC to version 6.1+
