### ISSUE TITLE
Question on max_read, max_write?

### ISSUE THREAD

**Issue by cometta** [Azure/azure-storage-fuse#306]
I can't find wiki explaining about max_read, max_write.  After I mounted a directory of Azure on my local memory/disk, I put a 1gb of file on the directory from time to time. These files will automatically upload to Azure. Can blobfuse auto clear local cache so that my local cache size will not increase if I put too many new files ?  Let say I have limited memory and disk space on local machine compared to total files in Azure blob. Alternative how to clear local cache  ?

**Comment by amnguye** [comment]
I would update to the newest version of blobfuse and see if this alleviates your problem of overfilling the cache.
