### ISSUE TITLE
Couldn't mount blob storage on an Azure VM.

### ISSUE THREAD

**Issue by fcbmg** [Azure/azure-storage-fuse#308]
### Which OS (please include version) are you using?

Ubuntu 18.04
### What problem was encountered?
Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 28.

The storage is a blob-storage account, the container exists and contains files and can be accessed with an access key via e.g. powershell, azure storage explorer, azcopy.
### Have you found a mitigation/solution?

No

**Comment by amnguye** [comment]
Hi, what version of blobfuse are you using?

What format is your storage account in? It should just be the storage account name not the url. When sharing the connection configurations, please provide the same format of what your information is but not the actual config information. Fake information is fine.

**Comment by fcbmg** [comment]
Hi, 

The blobfuse version is : blobfuse 1.0.3

Blobfuse config's file informations:
accountName myazurestorage
accountKey storage access key
containerName mycontainer
Thanks

**Comment by amnguye** [comment]
Sorry for the very late reply. I was wondering why there was spaces in your storage access key but not the storage account name or container name.

We might have to take this email in order to further investigate the issue.

**Comment by Tatsinnit** [comment]
:bulb: Adding my 2 cents, but usually `errno=28` : for mounts roughly translate to `devise is low in memory` **or** `No space left in device` , **note** surely core Blobfuse folks can correct me, or probably add more information around any quadrant for `errno` mapping.

**Comment by rishabpoh** [comment]
This issue seems to be in your config file. Feel free to re-open if not.
