### ISSUE TITLE
Issue building blob fuse on VM with SLES 12 SP3 for SAP Application

### ISSUE THREAD

**Issue by rukawata** [Azure/azure-storage-fuse#311]
### Which OS (please include version) are you using?
SLES 12 SP3

### What problem was encountered?
./build.sh failed

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_cda93.dir/build.make:97: recipe for target 'cmTC_cda93' failed
gmake[1]: *** [cmTC_cda93] Error 1
gmake[1]: Leaving directory '/hana/shared/azure-storage-fuse/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_cda93/fast' failed
gmake: *** [cmTC_cda93/fast] Error 2

### If relevant, please share your mount command.

Here are the steps I took:

zypper install git
git clone   https://github.com/Azure/azure-storage-fuse/
zypper install git cmake fuse-devel   libcurl-devel gcc gcc-c++ gnutls-devel libgcrypt-devel fuse libuuid-devel
./build.sh

Versions installed:
cmake version 3.5.2
gcc (SUSE Linux) 4.8.5

Output of ldconfig -p | grep pthread:
        libpthread.so.0 (libc6,x86-64, OS ABI: Linux 3.0.0) => /lib64/libpthread.so.0
        liblttng-ust-pthread-wrapper.so.0 (libc6,x86-64) => /usr/lib64/liblttng-ust-pthread-wrapper.so.0
        libgpgme-pthread.so.11 (libc6,x86-64) => /usr/lib64/libgpgme-pthread.so.11
        libevent_pthreads-2.0.so.5 (libc6,x86-64) => /usr/lib64/libevent_pthreads-2.0.so.5
        libOpenIPMIpthread.so.0 (libc6,x86-64) => /usr/lib64/libOpenIPMIpthread.so.0

**Comment by amnguye** [comment]
Closed. We made the the package offline.
