### ISSUE TITLE
Filenames truncated while copying

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-storage-fuse#313]
### Which version of the blobfuse was used?
n/a

### Which OS (please include version) are you using?
Ubuntu 14.04/16/18

### What problem was encountered?
Filenames being truncated upon being copied. There's no consistency of how many letters are taken off. This may have something to do with the file being a symbolic link.

In the log file, it shows the original file was named "database.sql" and is being renamed "base.sql" when moved into the mounted directory.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
[syslog.blobfuse.events.txt](https://github.com/Azure/azure-storage-fuse/files/3561446/syslog.blobfuse.events.txt)

### If relevant, please share your mount command.
n/a

Issue originally posted in #233 by @flybd5

**Comment by vibhansa-msft** [comment]
symlink copy issues have been fixed in version 1.3.1

**Comment by flybd5** [comment]
And it only took a year. Amazing.
