### ISSUE TITLE
cp command with -l flag causes more than one blob to be created

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-storage-fuse#314]
### Which version of the blobfuse was used?
n/a

### Which OS (please include version) are you using?
Ubuntu 14.04/16/18

### What problem was encountered?
Upon copying a file with a symlink, the filename gets altered and drops character (see issue #313).
Upon using the cp command with the -L flag, which is supposed to dereference and follow symbolic links to the source, the file copied into the mounted filesystem instead creates two blobs.

### Have you found a mitigation/solution?
no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
no

### If relevant, please share your mount command.
n/a

Original issue reported in #233 by @flybd5

**Comment by vibhansa-msft** [comment]
symlink support has been added in version 1.3.1

**Comment by flybd5** [comment]
A year later. wow.
