### ISSUE TITLE
Blobfuse does not mount fast enough

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-storage-fuse#315]
### Which version of the blobfuse was used?
n/a

### Which OS (please include version) are you using?
n/a

### What problem was encountered?
blobfuse does not mount containers fast enough. In comparison to a Azure File Share, it took 1 hour and 40 minutes to be mounted twice, while in comparison to mounting a Azure File Share it took less than a minute

### Have you found a mitigation/solution?
no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
n/a
----
>>>   2019/08/28 **17:39:40** Successfully mounted a/an Blobfuse File System at /mnt/batch/tasks/shared/LS_root/jobs/ai-test-batch-compute/azureml/33a3baf2-601a-4a8f-aa90-cd67706833d6/mounts/workspaceblobstore
>>>   2019/08/28 **19:19:05** Waiting for blobfs to be mounted at /mnt/batch/tasks/shared/LS_root/jobs/ai-test-batch-compute/azureml/33a3baf2-601a-4a8f-aa90-cd67706833d6/mounts/workspaceblobstore

### If relevant, please share your mount command.
n/a

**Comment by Tatsinnit** [comment]
:bulb: Thanks for this incident in the log. 

* If possible can you please share the `dataset` which makes this issue visible? I test with not so heavy work load so I don't notice it but few folks have mentioned recently few folks (yet to confirm) that they can see the performance hit. (I will keep you posted) personally with one mount with blob with just few files I don't see much of performance.

**Comment by NaraVen** [comment]
I tried a 5 petabyte storage container but cannot repro this is version 1,3,4. Closing it therefore.
