### ISSUE TITLE
Add support for reading SAS token from Azure KeyVault

### ISSUE THREAD

**Issue by lenisha** [Azure/azure-storage-fuse#316]
Add ability to read SAS token from Azure KeyVault, or use MSI identity to access Storage account

**Comment by adreed-msft** [comment]
MSI is currently in CR, alongside service principal auth.

Should you want to make use of SAS tokens in this way in the meantime, you can configure blobfuse via environment variables, and obtain your SAS token via an external method:

(from blobfuse/blobfuse.cpp:76)
```cplusplus
    char* env_account = getenv("AZURE_STORAGE_ACCOUNT");
    char* env_account_key = getenv("AZURE_STORAGE_ACCESS_KEY");
    char* env_sas_token = getenv("AZURE_STORAGE_SAS_TOKEN");
    char* env_blob_endpoint = getenv("AZURE_STORAGE_BLOB_ENDPOINT");
```

However, do note that you can't use a config in combination with these at the moment.

**Comment by rishabpoh** [comment]
Blobfuse now features support for managed identity.
