### ISSUE TITLE
Error building blobfuse on SuSE 15

### ISSUE THREAD

**Issue by hongsee1** [Azure/azure-storage-fuse#319]
### Which version of the blobfuse was used?
1.66.0

### Which OS (please include version) are you using?
SUSE Linux Enterprise Server 15

### What problem was encountered?
build.sh issues
./build.sh
./build.sh: line 16: cmake3: command not found
-- The C compiler identification is GNU 7.4.1
-- The CXX compiler identification is GNU 7.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CURL: /usr/lib64/libcurl.so (found version "7.60.0")
-- Found GnuTLS: /usr/lib64/libgnutls.so (found version "3.6.7")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Boost version: 1.66.0
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1938 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.66.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_filesystem
          boost_system

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:130 (find_package)

CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1938 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.66.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_thread

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:131 (find_package)

-- Checking for one of the modules 'uuid'
bash: go: command not found
-- Configuring incomplete, errors occurred!
See also "/home/hong/azure-storage-fuse/build/CMakeFiles/CMakeOutput.log".
See also "/home/hong/azure-storage-fuse/build/CMakeFiles/CMakeError.log".
cmake failed.  Please ensure that cmake version 3.5 or greater is installed and available.

### Have you found a mitigation/solution?
No

**Comment by hongsee1** [comment]
Anyone can advise on how to install the Boost libraries?

Thank you.

**Comment by amnguye** [comment]
Hi @Hongsee1,

I would recommend downloading Boost from the source and building it from there and altering the CMakeList.txt file so that it can find the libraries properly.

If you need a build for SUSE, I would wait a business day or two because we are in the process of signing those right now.

**Comment by hongsee1** [comment]
Hi amnguye,

Thank you for your reply.

**Comment by phwecker** [comment]
hi there, 

are we sure the "build from source" instructions are accurate ? i tried both SLES (15) and RHEL (7) and in both cases i got stuck at this exact issue (complaining about the missing libraries). 

Despite explicitly installing them (on SLES, where they do not seem to get installed by the zypper instructions provided) and setting the suggested BOOST_* variables in CMakeList.txt, i was not able to overcome the issue. i did try then on RHEL (quickly) but ran into the same issue. 

Any suggestions would be very much appreciated. 

Thanks.

**Comment by richardharrison2** [comment]
Hi,
I hit the exact same issue and couldn't find any fix when searching - however i found a fix myself in the end.

In the file CMakeLists.txt

There are 2 lines of the format

set(Boost_USE_STATIC_LIBS ON)

simply change them to

set(Boost_USE_STATIC_LIBS OFF)

Then it will work - this is then switching to dynamic libraries which it then seems quite happy to accept (OFF seems to be the boost default - not sure why this code is explicitly having it set to ON?)

Maybe it's for some other linux variant?

Cheers,
Rich

**Comment by AlastairMorrison** [comment]
Hi @phwecker, @hongsee1 

In addtion to @richardharrison2 changes for the CMakeLists.txt run 

zypper install libboost*devel to install the additional libraries for SLES 15.

The build then works.

Cheers
Al

**Comment by karlochacon** [comment]
where do you find the build.sh and  CMakeLists.txt files? 

sorry I am not that familiar with suse and "Run the build script located in the root folder of the repository. This will build the Azure Storage C++ Light library along with Blobfuse."

I am not sure where root folder of the repository is located 
thanks

**Comment by amnguye** [comment]
Hi,

Please follow Option 2 - Building from source. I'm assuming that's what you're attempting to do.

"root folder of the repository", I'm assuming you didn't clone the repository yet. Clone it and it will be in the folder you cloned the repository to

Please follow the documentation and wiki and reply when you have problems.

**Comment by NaraVen** [comment]
The latest build.sh will build on RHEL. Please download it. If you have questions on what binaries to yum install, please reopen, closing it for now.
