### ISSUE TITLE
Unable to see the blobfuse mountpoint when connected through winscp tool.

### ISSUE THREAD

**Issue by dibaskar** [Azure/azure-storage-fuse#321]
### Which version of the blobfuse was used?

blobfuse-1.0.2-1.x86_64

### Which OS (please include version) are you using?
Red Hat Enterprise Linux Server release 7.4 (Maipo)  

### What problem was encountered?

Its not a problem, Its actually a query. I can successfully mount the blobfuse filesystem as below. I can navigate to /home/dibaskar/mycontainer to my linux VM through SSH.

blobfuse        3.9G  2.1G  1.7G  56% /home/dibaskar/mycontainer

But when i use winscp to connect to VM, I cannot see /home/dibaskar/mycontainer where my blobfuse is mounted.

I tried with SFTP protocol and its not listing. If this is expected could you please provide the reason.

This is our customer's query and i need to update them with the reason as i dont see anywhere in article this is mentioned.

### Have you found a mitigation/solution?
No

**Comment by amnguye** [comment]
Hi Dibaskar,

I'm also confused to why you can't see the mounted directory. Most likely it could be that the directory is mounted by the root user and when winscp or any other tool connects to the VM/remote computer, it probably isn't the root user and therefore cannot view the mounted directory.

So the mounted directory should be owned by the same user, or owned by a user group that has a lower elevated privilege. That way the winscp tool has access to viewing these folders.

**Comment by NaraVen** [comment]
I cannot repro this. I tried Ubuntu 16.04 and 18.04  and I see the mount directory. so I am closing this. Please feel free to reopen if the issue still persists
