### ISSUE TITLE
page blob support

### ISSUE THREAD

**Issue by huaraz** [Azure/azure-storage-fuse#323]
### Which version of the blobfuse was used?
blobfuse-1.0.2-1.x86_64

### Which OS (please include version) are you using?
Redhat 7.1

### What problem was encountered?
write page blob

### Have you found a mitigation/solution?
No

### If relevant, please share your mount command.
MOUNTPOINT=/media/azureblobs/vhds
CONFIGFILE=/root/fuse_connection.cfg
TMPDIR=/mnt/resource/blobfusetmp
mkdir $MOUNTPOINT -p
mkdir $TMPDIR -p
chown root $TMPDIR
blobfuse $MOUNTPOINT --tmp-path=$TMPDIR --config-file=$CONFIGFILE -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

Is there an option to create a page blob instead of a block blob ?

**Comment by amnguye** [comment]
Hi,

There is not an option to create page blobs instead of block blobs. Blobfuse only supports the creation of block blobs.

**Comment by andyzhangx** [comment]
@amnguye is page blob supported now? thanks.

**Comment by NaraVen** [comment]
No page support yet.

**Comment by NaraVen** [comment]
we don't have any plan to support page blob.

**Comment by eaydogan** [comment]
Hello @NaraVen @andyzhangx 
 Is there any changes on this  (page blob support) ?

**Comment by vibhansa-msft** [comment]
As of now we do not have any plans to support this. We are working on the next generation of blobfuse and may be in future we will look at this again to add it there.
