### ISSUE TITLE
Mount blobfuse on host volume via container 

### ISSUE THREAD

**Issue by AnassKartit** [Azure/azure-storage-fuse#324]
### Which version of the blobfuse was used?
1.0.3

### Which OS (please include version) are you using?
Mac OSx Mojave / Container on ubuntu 18.04

### What problem was encountered?
blobfuse /OSX/containerblob --container-name=mycontainer --tmp-path=/mnt/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG

### Have you found a mitigation/solution?
Nothing

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Files are showing successfully on container but not on host osx folder mounted 
using docker run -it -v ~/OSX:/OSX--priviliged ubuntu:18.04 sh

**Comment by amnguye** [comment]
Hi,

Blobfuse does not support Mac OSx.
