### ISSUE TITLE
Blobfuse shall not the copy on symlink

### ISSUE THREAD

**Issue by wangdfgithub** [Azure/azure-storage-fuse#328]
### Which OS (please include version) are you using?

Ubuntu 16.04
### What problem was encountered?
When copy a folder which contains symlinks, the copy will fail with below exception
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    shutil.copy2('foo.txt', 'bar.txt')
  File "/usr/lib/python3.5/shutil.py", line 252, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 219, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/usr/lib/python3.5/shutil.py", line 151, in _copyxattr
    names = os.listxattr(src, follow_symlinks=follow_symlinks)
OSError: [Errno 38] Function not implemented: 'foo.txt'

### Have you found a mitigation/solution?

NA
### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

NA
### If relevant, please share your mount command.

NA

**Comment by vibhansa-msft** [comment]
symlink support has been added in version 1.3.1
