### ISSUE TITLE
blobfuse will hang after running for 65 hours

### ISSUE THREAD

**Issue by wangdfgithub** [Azure/azure-storage-fuse#329]
### Which version of the blobfuse was used?
ver 1.0.3

### Which OS (please include version) are you using?
Ubuntu

### What problem was encountered?
Blobfuse will hang after running for 65 hours

### Have you found a mitigation/solution?
N/A

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Oct 22 04:22:33 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: Failed to list blobs under directory /mnt/batch/tasks/shared/LS_root/jobs/repro/azureml/azureml-presumm_1571482468_3daa9f21/caches/workspaceblobstore/root/azureml/Azureml-Presumm_1571482468_3daa9f21/azureml_compute_logs/tvmps_6cf1e0087f571b241eba9fa1da772b76c379cf059bb550debf3cea6eda5cdf10_d/ on the service during readdir operation.  errno = 400.
Oct 22 04:23:04 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 1 time with errno = 400.
Oct 22 04:23:33 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 2 time with errno = 400.
Oct 22 04:24:03 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 3 time with errno = 400.
Oct 22 04:24:03 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 4 time with errno = 400.
Oct 22 04:24:03 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 5 time with errno = 400.
Oct 22 04:24:03 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 6 time with errno = 400.
Oct 22 04:24:33 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 7 time with errno = 400.
Oct 22 04:25:03 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 8 time with errno = 400.
Oct 22 04:25:32 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 9 time with errno = 400.
Oct 22 04:26:02 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 10 time with errno = 400.
Oct 22 04:26:32 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 11 time with errno = 400.
Oct 22 04:26:32 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 12 time with errno = 400.
Oct 22 04:26:32 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 13 time with errno = 400.
Oct 22 04:26:33 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 14 time with errno = 400.
Oct 22 04:26:33 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 15 time with errno = 400.
Oct 22 04:26:33 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 16 time with errno = 400.
Oct 22 04:26:33 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 17 time with errno = 400.
Oct 22 04:26:33 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 18 time with errno = 400.
Oct 22 04:27:03 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 19 time with errno = 400.
Oct 22 04:27:33 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: list_blobs_hierarchical failed for the 20 time with errno = 400.
Oct 22 04:27:33 8650f1073aac48a2a59082a0da963ffc000001 blobfuse[4647]: Failed to list blobs under directory

**Comment by datashinobi** [comment]
any toughts on this issue, this is a blocking issue

**Comment by NaraVen** [comment]
@datashinobi, @wangdfgithub,   Could you please upgrade to the latest version 1.3.3? It is hard to debug older versions due to the Linux upgrades after.

**Comment by NaraVen** [comment]
I tested running for 144 hours in Ubuntu 18.04, Oracle Linux 8.1 and RHEL8.1. I could not repro this. So, I am closing this issue.
