### ISSUE TITLE
Blobfuse --version wrong output

### ISSUE THREAD

**Issue by romulo-dbts** [Azure/azure-storage-fuse#332]
### Which version of the blobfuse was used?
1.1.1

### Which OS (please include version) are you using?
Debian 9

### What problem was encountered?
Installing version 1.1.1 from `.deb` package but --version command is displaying 1.0.3

### Have you found a mitigation/solution?
No

I have supposedly installed version 1.1.1 from deb package (https://github.com/Azure/azure-storage-fuse/releases/download/v1.1.1/blobfuse-1.1.1-stretch.deb) and it seems to be installing version 1.1.1, however when I run `blobfuse --version` it is being shown `blobfuse 1.0.3`. So, because of this I am a bit confused if I am really running version 1.1.1 or not. Please find the output below
```
root@56068c3a63b8:/var/www/html# dpkg -i blobfuse-1.1.1-stretch.deb 
(Reading database ... 34248 files and directories currently installed.)
Preparing to unpack blobfuse-1.1.1-stretch.deb ...
Unpacking blobfuse (1.1.1) over (1.1.1) ...
Setting up blobfuse (1.1.1) ...
root@56068c3a63b8:/var/www/html# blo
blobfuse  blockdev  
root@56068c3a63b8:/var/www/html# blobfuse --version
blobfuse 1.0.3
```

**Comment by amnguye** [comment]
Hi Romulo,

Sorry for the confusion. We are aware of the bug of it printing out the wrong version. The version you have is v1.1.1. It is a bug it's printing out the previous version.

**Comment by johanburati** [comment]
Same with RHEL/Centos, installed latest release [blobfuse-1.1.1.el7.x86_64.rpm](blobfuse-1.1.1.el7.x86_64.rpm) but still retruns the version as *1.0.3*.

When will you release a version with the fix ?
