### ISSUE TITLE
Low/High Threshold values for Caching feature

### ISSUE THREAD

**Issue by shraboin** [Azure/azure-storage-fuse#333]
### Which version of the blobfuse was used?

1.1.1
### Which OS (please include version) are you using?
REHL 7.7

### What problem was encountered?

n/a
### Have you found a mitigation/solution?
n/a

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
no

For the caching feature:
--use-attr-cache=true|false : Enables attributes of a blob being cached. False by default.
Improvements:

Cache will clear itself once reaching a high threshold and will reduce the cache to below the low threshold. Timeout cache still exists, so if the timeout is met and the threshold is not met, the cache will still clear itself

What are the low/high Threshold values? Is it possible for us to set and if so how do we do that.

**Comment by amnguye** [comment]
Hi,

I will assume when you say cache, you mean the attribute cache because you mentioned attribute cache option. Right now there is no high or low threshold set for attribute cache,
