### ISSUE TITLE
BlobFuse with incorrect permissions: ??? + switching ownership

### ISSUE THREAD

**Issue by evandropomatti** [Azure/azure-storage-fuse#334]
### Which version of the blobfuse was used?

```
bottledetector@bottledetector-vm-dev:~/mnt/cervejeiras/homolog$ blobfuse --version
blobfuse 1.0.3
```

### Which OS (please include version) are you using?

```
bottledetector@bottledetector-vm-dev:~/mnt/cervejeiras/homolog$ lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:    18.04
Codename:    bionic
```

### What problem was encountered?

We write files to our Storage from an IoT Hub route. Our device uploads files to the IoT Hub, which transparently create the directory with the corresponding device ID the first time it connects (in our case the GUID named folder). The device then triggers our application to process the image via Service Bus.

The problem is that when we read the file from the storage, mounted in our VM, it appears with unknown `???` permissions.

![image](https://user-images.githubusercontent.com/6530769/69821003-36078e00-11e1-11ea-9c10-46380fcbf7b8.png)

It always happens after the I/O process is "idle" for very short time, just a couple of minutes max. (We also observed it to happen in burst of files but we didn't manage to reproduce it again).

As we can see in the image above, the ownership of the files also is changing our user `bottledetector` and `root` between the "???" permissions and that exchange seems to be random for us.

### Have you found a mitigation/solution?

No.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

There's nothing relevant in syslog.

### If relevant, please share your mount command.

```
sudo blobfuse /home/bottledetector/mnt/cervejeiras --tmp-path=/mnt/cervblobfusetmp --config-file=/home/bottledetector/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other
```

**Comment by mawippel** [comment]
I'm having the same issue.

**Comment by amnguye** [comment]
Hi,

Thanks for bringing this issue up. Before mounting the filesystem, what user has ownership to the directory? You can also change the ownership of the directory by using the 'chown' command.

I can see this relating to blobfuse's need to cache the attributes and it was not able to get that files attributes. So you are unable to open that specific file/blob with the ??? attributes as well? Does the ??? attributes also persist when you run ls again?

The only mitagation I can think of is unmounting and remounting to see if that helps.

**Comment by evandropomatti** [comment]
We found the cause for the issue. There were 2 distinct problems:

1. We were using async operations to send the blob and the MQTT message, so there was no guarantee that the blob would be available when the message was processed.

2. On top of that, we were sending the blob AFTER the MQTT message, this was also wrong as the the blob should be sent first.
