### ISSUE TITLE
[bug] [investigation] Blobfuse sees 400 instead of 503, and should retry at 503 (mount failed)

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-storage-fuse#340]
### Which version of the blobfuse was used?
1.1.1

### Which OS (please include version) are you using?
various distros

### What problem was encountered?
When a mount is attempted, but when a storage account is being throttled, a 400 is seen by blobfuse. When blobfuse sees a 400, it will not attempt to retry because this is not a retriable http code if blobfuse sent a bad request. This is expected behavior when blobfuse gets back a 400.

However when an account is throttled and you try to send a request, it gives back a 503 actually. Which means blobfuse should have the okay to keep retrying the mount. Blobfuse should be able to handle 503s.

### Have you found a mitigation/solution?
No. As of now the storage account bandwidth would need to be increased. Yes blobfuse can't stop an account from being throttled but it should be able to handle a 503.

**Comment by NaraVen** [comment]
400 is not thrown any more. It is mapped to EFAULT.
