### ISSUE TITLE
cannot update the Mocrosoft package repository for Blobfuse with error "Hash sum mismatch"

### ISSUE THREAD

**Issue by Shanon666** [Azure/azure-storage-fuse#341]
### Which version of the blobfuse was used? 
V1.1.1 

### Which OS (please include version) are you using? 
Windows

### What problem was encountered? 
refer to the Microsoft Azure offical url 'https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux' to install blobfuse, got the error when configure the Microsoft package repository with command 'sudo dpkg -i packages-microsoft-prod.deb'. it shows error "Hash sum mismatch"

Error Message

root@Blobfuseubt16:/home/hana# wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
--2019-12-13 05:42:34--  https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.75.127.55
Connecting to packages.microsoft.com (packages.microsoft.com)|13.75.127.55|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2452 (2.4K) [application/octet-stream]
Saving to: ‘packages-microsoft-prod.deb’

packages-microsoft-prod.deb                     100%[====================================================================================================>]   2.39K  --.-KB/s    in 0s      

2019-12-13 05:42:34 (450 MB/s) - ‘packages-microsoft-prod.deb’ saved [2452/2452]

root@Blobfuseubt16:/home/hana# sudo dpkg -i packages-microsoft-prod.deb
Selecting previously unselected package packages-microsoft-prod.
(Reading database ... 53892 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-3) ...
Setting up packages-microsoft-prod (1.0-3) ...
root@Blobfuseubt16:/home/hana# sudo apt-get update
Get:1 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease [3,959 B]
Get:2 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages [156 kB]                  
Err:2 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages                                             
  Hash Sum mismatch
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]                                                    
Get:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [797 kB]          
Get:5 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [466 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [192 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [5,728 B]        
Get:8 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [2,708 B]        
Hit:9 http://azure.archive.ubuntu.com/ubuntu xenial InRelease                                    
Get:10 http://azure.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                                                                                                           
Get:12 http://azure.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [7,532 kB]                                                                                                     
Get:13 http://azure.archive.ubuntu.com/ubuntu xenial/universe Translation-en [4,354 kB]                                                                                                     
Get:14 http://azure.archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]                                                                                                     
Get:15 http://azure.archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]                                                                                                     
Get:16 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1,082 kB]                                                                                                 
Get:17 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [771 kB]                                                                                               
Get:18 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [324 kB]                                                                                               
Get:19 http://azure.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.8 kB]                                                                                            
Get:20 http://azure.archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8,468 B]                                                                                            
Get:21 http://azure.archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [7,280 B]                                                                                                
Get:22 http://azure.archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [4,456 B]                                                                                                
Get:23 http://azure.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8,064 B]                                                                                            
Get:24 http://azure.archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [4,328 B]                                                                                            
Fetched 16.3 MB in 8s (1,861 kB/s)                                                                                                                                                          
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

### Have you found a mitigation/solution?
yes, can refer to the Chinese url ‘https://www.cnblogs.com/magictwt/p/8000075.html’ install the blobfuse manually.

PS: need to disable the "Secure transfer required" for the storage account

below is the command may help .

1. downlaod blobfuse
git clone https://github.com/digitaltwt/azure-storage-fuse 
2. Install dependencies
#Centos#
sudo yum -y install epel-release 
sudo yum install git cmake3 fuse-devel libcurl-devel gcc gcc-c++ gnutls-devel fuse -y 

##Redhat#
install git cmake fuse-devel libcurl-devel gcc gcc-c++ gnutls-devel fuse -y

##Ubuntu#
sudo apt-get install pkg-config libfuse-dev cmake libcurl4-gnutls-dev libgnutls28-dev -y 

3. install blobfuse from build

cd azure-storage-fuse/ 
./build.sh 

4. update the connection.cfg with the storage account name/Key/containername

vim connection.cfg

5. create a  temporaty path (on ephemeral  disk of Azure VM)，and change owner 

#Centos#

sudo mkdir /mnt/resource/blobfusetmp -p
sudo chown <youruser> /mnt/resource/blobfusetmp

##Ubuntu##

mkdir -p /mnt/blobfusetemp 

chown <user> /mnt/blobfusetemp  

6. mount to your own directoy 

./mount.sh </path>

**Comment by Shanon666** [comment]
update: Ubuntu 18.04 has similar error 

root@Ubuntu18:/home/hana# sudo dpkg -i packages-microsoft-prod.deb
Selecting previously unselected package packages-microsoft-prod.
(Reading database ... 74452 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu18.04.2) ...
Setting up packages-microsoft-prod (1.0-ubuntu18.04.2) ...
root@Ubuntu18:/home/hana# sudo apt-get update
Get:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [3959 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu bionic InRelease                                              
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                            
Get:4 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [156 kB]                                             
Err:4 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages                                                            
  File has unexpected size (84552 != 156065). Mirror sync in progress? [IP: 13.75.127.55 443]
  Hashes of expected file:
   - Filesize:156065 [weak]
   - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
   - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
   - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
   - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
Get:5 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                                                            
Get:6 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [8570 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]       
Get:8 http://azure.archive.ubuntu.com/ubuntu bionic/universe Translation-en [4941 kB]           
Get:9 http://azure.archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [151 kB]      
Get:10 http://azure.archive.ubuntu.com/ubuntu bionic/multiverse Translation-en [108 kB]     
Get:11 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [817 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [288 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [24.1 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [6620 B]
Get:15 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1033 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [319 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [9284 B]
Get:18 http://azure.archive.ubuntu.com/ubuntu bionic-updates/multiverse Translation-en [4508 B]
Get:19 http://azure.archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2512 B]
Get:20 http://azure.archive.ubuntu.com/ubuntu bionic-backports/main Translation-en [1644 B]
Get:21 http://azure.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4028 B]
Get:22 http://azure.archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [1856 B]
Get:23 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [593 kB]      
Get:24 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [194 kB]
Get:25 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [15.1 kB]
Get:26 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [4684 B]
Get:27 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [627 kB]
Get:28 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [210 kB]
Get:29 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [6120 B]
Get:30 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [2600 B]
Fetched 18.2 MB in 11s (1647 kB/s)                                                                                                                                                          
Reading package lists... Done
W: Conflicting distribution: https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease (expected bionic but got stable)
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (84552 != 156065). Mirror sync in progress? [IP: 13.75.127.55 443]
   Hashes of expected file:
    - Filesize:156065 [weak]
    - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
    - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
    - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
    - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by amnguye** [comment]
Hi,

This seems like an issue with the packages downloaded from the microsoft production packages and not blobfuse.

This seems like the right place to voice your issues about not being able to access the packages correctly
https://windowsserver.uservoice.com/forums/295047-general-feedback

However I just attempted to reproduce your issues and I can't seem to replicate them. Sorry I cannot be of more help. If there is a blobfuse issue feel free to make a seperate issue for that

**Comment by amnguye** [comment]
Hi,

Looks like the issue with the Linux repos has been resolved. Please attempt to install blobfuse again, and if the issue is reproduced then please let the appropriate people know.
