### ISSUE TITLE
Ubuntu 19.10: Unable to locate package blobfuse

### ISSUE THREAD

**Issue by scegg** [Azure/azure-storage-fuse#344]
### Which version of the blobfuse was used?
N/A

### Which OS (please include version) are you using?
Ubuntu 19.10 x64

### What problem was encountered?
Unable to locate package blobfuse

### Have you found a mitigation/solution?
NO.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

> apt update
Hit:1 http://azure.archive.ubuntu.com/ubuntu eoan InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu eoan-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu eoan-backports InRelease
Get:4 https://packages.microsoft.com/ubuntu/19.10/prod eoan InRelease [10.5 kB]
Get:5 https://packages.microsoft.com/ubuntu/19.10/prod eoan/main armhf Packages [554 B]
Get:6 https://packages.microsoft.com/ubuntu/19.10/prod eoan/main arm64 Packages [554 B]
Get:7 https://packages.microsoft.com/ubuntu/19.10/prod eoan/main amd64 Packages [4179 B]
Hit:8 http://security.ubuntu.com/ubuntu eoan-security InRelease
Fetched 15.7 kB in 1s (11.1 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.

> apt install blobfuse
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package blobfuse

### If relevant, please share your mount command.
N/A

**Comment by amnguye** [comment]
Hi,

Sorry, we have not yet added the package on for Ubuntu 19.04. We expect to make a new release in the coming weeks, so we will add blobfuse for Ubuntu 19.04 then. For now if you have any problems installing the binary please let us know.

**Comment by scegg** [comment]
Now trying to use bionic version on 19.10 but not work.

Mounting returns nothing but actually nothing is mounted.

**Comment by amnguye** [comment]
Sorry to hear that. I will spin up a vm and the problem is and why blobfuse isn't working.

Is there an error that blobfuse gives when you attempt to mount? Is there anything in the syslog that prints out relevant to blobfuse?

You can tell blobfuse is running by either running the top command and see blobfuse as a process, and if you run the "sudo df -h" command and see your mounted container by blobfuse.

On our side we will try to reproduce the issue by making a vanilla vm of ubuntu 19 and see what the problem is.

**Comment by scegg** [comment]
Problem gone when I test again. I guess maybe the problem is, in this time I create the storage account under public access, instead of private.

Currently, I didn't find any problem.
