### ISSUE TITLE
Install blobfuse last version

### ISSUE THREAD

**Issue by quatrecentun** [Azure/azure-storage-fuse#346]
### Which version of the blobfuse was used?
blobfuse 1.0.3

### Which OS (please include version) are you using?
CentOS Linux release 7.7.1908

### What problem was encountered?
I would like to install the last version of blobfuse (1.1.1) and when I install the paquet I downloaded before on git I see the installed version is 1.0.3 insted of 1.1.1 :

[root@xxxxxx]# rpm -ivh blobfuse-1.1.1.el7.x86_64.rpm                                                                         
attention : blobfuse-1.1.1.el7.x86_64.rpm: Entête V4 RSA/SHA256 Signature, clé ID be1229cf: NOKEY
Préparation...                       ################################# [100%]
Mise à jour / installation...
   1:blobfuse-1.1.1-1.el7             ################################# [100%]

[root@xxxxxxx]# blobfuse --version
blobfuse 1.0.3

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No logs

### If relevant, please share your mount command.
No mount command yet.

**Comment by amnguye** [comment]
Hi,

This is a duplicate of this issue #332 .

We actually already made the fix in the source code, but we are still looking to making a release soon with the fix. If you would like to see the fix immediately, you can pull the source code and build from there. However for now I can confirm you actually have version 1.1.1 of blobfuse.

**Comment by quatrecentun** [comment]
> Hi,
> 
> This is a duplicate of this issue #332 .
> 
> We actually already made the fix in the source code, but we are still looking to making a release soon with the fix. If you would like to see the fix immediately, you can pull the source code and build from there. However for now I can confirm you actually have version 1.1.1 of blobfuse.

Okay, thanks for your reply !
