### ISSUE TITLE
HTTP and HTTPS support

### ISSUE THREAD

**Issue by wolf-kuehnel** [Azure/azure-storage-fuse#35]
HTTPS is not the default protocol, apperently.  My initial testing resulted  in errors like

recvfrom(**4, "HTTP/1.1 400 The account being accessed does not support http**.\r\nTransfer-Encoding: chunked\r\nServer: Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: aaaaaaaa-0000-0000-6666-000000000000\r\nDate: Wed, 13 Dec 2017 19:56:58 GMT\r\n\r\n", 16384, 0, NULL, NULL) = 217
futex(0x183ad58, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 1600\n", 192Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 1600) = 192

(The above is output from "strace blobfuse --config....", request-Id was anonymized)

**Comment by seguler** [comment]
Yes - it is not. Let's make it the default in the next release. @asorrin-msft @AlexanderYukhanov would you agree ?

**Comment by AlexanderYukhanov** [comment]
agree, the default version should be https. only if user explicitly wants http we should use it

**Comment by wolf-kuehnel** [comment]
Yes, please make HTTPS the default protocol.  This would correspond to the default policy for the Blob storage, as far as I understand.

In addition, it would support the users if the HTTP/400 error, if there is a HTTP/HTTPS mismatch, gets forwarded to the user interface. Currently, the generated error message directs the user to some problems in the config file, which is misleading.

**Comment by seguler** [comment]
blobfuse 0.2 is now released and https is the default. Closing this. Thanks!
