### ISSUE TITLE
Blobfuse allows repeatedly mounting empty blob container to the same directory.

### ISSUE THREAD

**Issue by ebencarek** [Azure/azure-storage-fuse#352]
### Which version of the blobfuse was used?
1.1.1

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
Blobfuse allows repeatedly mounting an empty blob container to the same directory. If there is a file in the blob container, then this will not work and blobfuse will return an error when trying to mount again after the first time (expected behavior), but if the blob container is empty, the same mount command can be run repeatedly with no error, and multiple blobfuse processes will be started. In this case, running `fusermount -uz <mount_path>` will only remove the most recently started instance of blobfuse.

Steps to repro:
1. Create new empty blob container in storage account.
2. Mount container to directory on host machine.
3. Run the same mount command again.

Multiple blobfuse processes are now running.

### Have you found a mitigation/solution?
No, other than manually checking if something is mounted to that directory first.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
N/A

### If relevant, please share your mount command.
`blobfuse <mount_path> --config-file=blobconfig.cfg --tmp-path=/mnt/blobtmp -o allow_other`

**Comment by amnguye** [comment]
Hi,

Yes unfortunately the kernel does allow multiple mounts on a directory for more flexibility in what the user can do. More can be found in this Q&A.

https://unix.stackexchange.com/questions/251090/why-does-mount-happen-over-an-existing-directory

However you are correct, we should check if blobfuse currently is mounted as a filesystem on the directory in question to mount to.

Most likely the approach we will take is to check the mount point and see if anything is mounted at that point and if the filesystem that is mounted is blobfuse, then we refuse the mount.

Thanks for finding this bug. I will label this as a bug and add it to our backlog.
