### ISSUE TITLE
Blobfuse deletes contents of container after not unmounting the container

### ISSUE THREAD

**Issue by sdcnudde** [Azure/azure-storage-fuse#353]
### Which version of the blobfuse was used?
1.1.1

### Which OS (please include version) are you using?
Ubuntu 18.04.3 LTS (GNU/Linux 5.0.0-1028-azure x86_64)

### What problem was encountered?
We executed the following steps:
1. Creating and starting a VM and ssh-ing into it
2. Mount a Blob container through blobfuse in Jupyter Notebook
3. Close the Jupyter notebook and stop the python process without unmounting the container

This results in the contents of the container being deleted.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No syslog error logging.

This error message is given by VM:
```
Traceback (most recent call last):

  File "/home/admin/.local/share/virtualenvs/example-mg1unP_c/lib/python3.6/weakref.py", line 624, in _exitfunc
    f()
  File "/home/admin/.local/share/virtualenvs/example-mg1unP_c/lib/python3.6/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/admin/.local/share/virtualenvs/example-mg1unP_c/lib/python3.6/tempfile.py", line 799, in _cleanup
    _shutil.rmtree(name)
  File "/home/admin/.local/share/virtualenvs/example-mg1unP_c/lib/python3.6/shutil.py", line 490, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/admin/.local/share/virtualenvs/example-mg1unP_c/lib/python3.6/shutil.py", line 488, in rmtree
    os.rmdir(path)
OSError: [Errno 16] Device or resource busy: '/tmp/tmplj1oazu_'
```

### If relevant, please share your mount command.
`blobfuse storage-blob/container --config-file=[] --tmp-path=[] --file-cache-timeout-in-seconds=600 --use-https=True`

**Comment by amnguye** [comment]
Hi,

Sorry if I don't have all the information on how Juypter Notebook works. However this behavior does seem related to how Juypter Noteworks and how it makes calls to the kernel. 

Looking at the Juypter Notebook docs, it looks like when you "close a notebook" it shuts down the kernel. Shutting down the kernel might be making it remove the files from the container before it closes the notebook.

Could you tell me how you were able to mount blobfuse through juypter's notebook and how Juypter Notebooks works with blobfuse? Maybe we can get to the bottom of this and help blobfuse unmount correctly and then let Juypter's notebook close without the kernel automatically deleting all these files.

Also I found that we have Microsoft Azure Notebooks that uses Juypter's Notebook, if you are open to looking at that.

**Comment by NaraVen** [comment]
Could you please get our latest version 1.2.3 and confirm if you still have this issue. Please confirm or close this issue if 1.2.3 resolves the issue you are encountering.

**Comment by rishabpoh** [comment]
Please re-open this issue if it persists.
