### ISSUE TITLE
ClientId must be passed as a query parameter when talking to MSI_ENDPOINT

### ISSUE THREAD

**Issue by sweana** [Azure/azure-storage-fuse#356]
### Which version of the blobfuse was used?
v1.1.1

### Which OS (please include version) are you using?
ubuntu 18.04

### What problem was encountered?
Please pass clientid as a query parameter that indicates which user assigned identity to use for authentication.

**Comment by NaraVen** [comment]
1.2.1 has this param. So, upgrading to 1.,2.* is the solution.
