### ISSUE TITLE
Use the standard MSI_ENDPOINT instead of AZURE_STORAGE_MANAGED_IDENTITY_ENDPOINT

### ISSUE THREAD

**Issue by sweana** [Azure/azure-storage-fuse#357]
### Which version of the blobfuse was used?
v1.1.1

### Which OS (please include version) are you using?
ubuntu 18.04

### What problem was encountered?
Please use standard environment variable MSI_ENDPOINT to access the custom endpoint instead of AZURE_STORAGE_MANAGED_IDENTITY_ENDPOINT.

**Comment by NaraVen** [comment]
This is not an issue any more in 1.2.1. Can we close this?
