### ISSUE TITLE
changes to the contents of a file when performed from the blob storage in the Azure Portal doesn't change the file contents when accesses from the mount

### ISSUE THREAD

**Issue by amirgra** [Azure/azure-storage-fuse#358]
### Which version of the blobfuse was used?
1.0.3

### Which OS (please include version) are you using?
ubuntu 16.04

### What problem was encountered?
when updating file in the blob storage directly
the contents of the file in the blob storage match the contents of the file in the cache but doesn't match the contents of the file in the mount path

### Have you found a mitigation/solution?
unfortunately only unmount and mount again align all the files data (change is now shown in all locations).

**Comment by amnguye** [comment]
Hi,

Azure Portal is just another method of accessing your storage, it does not necessarily mean that's the direct way of accessing your data. Blobfuse is just another medium of accessing your data.

Unfortunately if you have blobfuse mounted, and you update the file in Azure Portal, blobfuse does not know automatically that you updated the blob through another means. In our documentation we stated in our limitations "Not optimized for updating an existing file. blobfuse downloads the entire file to local cache to be able to modify and update the file."
