### ISSUE TITLE
Return 403 Errors with the Correct Credential Type

### ISSUE THREAD

**Issue by liyiming-serif** [Azure/azure-storage-fuse#359]
### Which version of the blobfuse was used?
blobfuse 1.0.3

### Which OS (please include version) are you using?
Ubuntu 16.04

### What problem was encountered?
When a customer mounts with a SAS token and gets a 403 unauthorized (either because the SAS token is incorrect, expired, or storage account is behind vnet), blobfuse returns a fixed string asking the customer to check the account key.
![image](https://user-images.githubusercontent.com/10852438/73580487-8f3aaa80-443a-11ea-8969-51cf89de3fac.png)

Please change this error message to read `please double check the storage account name, *sas token* and container name. errno = 403` if the .cfg file is using SAS tokens instead of account keys.
![image](https://user-images.githubusercontent.com/10852438/73580539-c5782a00-443a-11ea-8f5d-3fe8e66e886a.png)

**Comment by adreed-msft** [comment]
I believe that this message is changed with the introduction of service principal auth and managed service identity, to be a bit more generic "supply valid auth credentials", or something along those lines.

**Comment by NaraVen** [comment]
could nto reproduce. So, this is fixed ?.
