### ISSUE TITLE
Is there a way to limit or disable parallel uploads/downloads?

### ISSUE THREAD

**Issue by OliverColeman** [Azure/azure-storage-fuse#360]
### Which version of the blobfuse was used?
1.1.1

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
Is it possible to limit the number of parallel uploads (and downloads)?

**Comment by amnguye** [comment]
Hi,

There currently is not a way to limit parallel uploads and downloads for blobfuse. Sorry for the inconvenience.
