### ISSUE TITLE
Documentation: Differences from POSIX does not mention lack of symlink support

### ISSUE THREAD

**Issue by krezreb** [Azure/azure-storage-fuse#361]
### Which version of the blobfuse was used?
latest

### Which OS (please include version) are you using?
ubuntu 19.10

### What problem was encountered?
It is well documented that blob storage does not support symlinks.  Your limitations documentation mentions chmod, chown,and hard links, but speaks nothing of symlinks.  Could you please make it clear that symlinks are not supported (maybe MS will implement it soon)?

**Comment by amnguye** [comment]
Hi,

I do agree with you, we should have documented that we don't fully support symlinks. However I think as you are aware we already have an issue open to hopefully fully support this case. We had a PR open for it, however it does not fully cover all the symlink conditions.

**Comment by krezreb** [comment]
Indeed I noticed the open issues and PR.  Since there's no guarantee of if/when symlinks will be added to the blob api, it would still be nice for newbies to realize that blobfuse doesn't support it either.  These caveats are mentioned in the original MS blobfuse release blog entry https://azure.microsoft.com/en-us/blog/linux-fuse-adapter-for-blob-storage/
