### ISSUE TITLE
[DOC] Recommend to update updatedb.conf to exclude FUSE and mounted directory(s)

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-storage-fuse#362]
If you mount one of our Azure storage accounts using blob fuse on a Linux environment
 
1-	Make sure you edit your /etc/updatedb.conf file (https://linux.die.net/man/5/updatedb.conf) as follows:
 
a)	Add the string “fuse” (without any suffix) to the “PRUNEFS” section (you can keep whatever was there before). After modifying it, it should look like the following:
•	PRUNEFS="NFS nfs nfs4 rpc_pipefs afs binfmt_misc proc smbfs autofs iso9660 ncpfs coda devpts ftpfs devfs devtmpfs fuse.mfs shfs sysfs cifs lustre tmpfs usbfs udf fuse.glusterfs fuse.sshfs curlftpfs ceph fuse.ceph fuse.rozofs ecryptfs fusesmb fuse"
 
b)	Add the path “/mnt” to the “PRUNEPATHS” section of the file (you can keep whatever was there before). After modifying it, it should look like the following:
•	PRUNEPATHS="/tmp /var/spool /media /var/lib/os-prober /var/lib/ceph /home/.ecryptfs /var/lib/schroot /mnt"

Without this, a process called mlocate (which typically runs daily in common Linux distributions – you can check your /etc/cron.daily file) enumerates the full storage account contents trying to index them, incurring unnecessary costs and impacting our transaction quotas.

**Comment by NaraVen** [comment]
https://github.com/Azure/azure-storage-fuse/wiki/3.-Troubleshoot-FAQ. Updated this link to add this as troubleshooting section.
