### ISSUE TITLE
Blobfuse on Ubuntu 19.04?

### ISSUE THREAD

**Issue by gazzaluty** [Azure/azure-storage-fuse#364]
### Which version of the blobfuse was used?
n/a

### Which OS (please include version) are you using?
Ubuntu 19.04

### What problem was encountered?
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package blobfuse

### Have you found a mitigation/solution?
No

I have run:

wget https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install blobfuse

**Comment by amnguye** [comment]
Hi,

We have not uploaded a package for Ubuntu 19. We plan to with the release of 1.2

Sorry for the delay.

**Comment by NaraVen** [comment]
Do you still need release 19.04? We have released version 1.2.3 for Ubuntu 16.04 and Ubuntu 18.04. Next, We plan to release to 20.04 directly after fixing the fuse mount issues in 20.04

**Comment by gazzaluty** [comment]
Hi, we still need the 19.04 release.

**Comment by NaraVen** [comment]
Since 19.04 is not an LTS release, we will only be publishing 20.04 now.

**Comment by gazzaluty** [comment]
Make sense. I'll upgrade
