### ISSUE TITLE
[BUG] [tests] test_multiple_threads_create_cache_directory_simultaneous

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-storage-fuse#367]
### Which version of the blobfuse was used?
1.2.1

### Which OS (please include version) are you using?
any

### What problem was encountered?
test in ThreadTests.test_multiple_threads_create_cache_directory_simultaneous, has a bug when a thread goes to delete the cached directory when it already has been deleted by another thread. Add check to check if the cached folder exists folder before trying to remove it.

**Comment by rishabpoh** [comment]
Fixed.
