### ISSUE TITLE
Download from file azure according to read offset

### ISSUE THREAD

**Issue by Binyang2014** [Azure/azure-storage-fuse#369]
According to https://github.com/Azure/azure-storage-fuse/blob/7c9f2e9f7414357d4b96e4b6070b7f70d3885ade/blobfuse/fileapis.cpp#L114-L116
blobfuse will download file when exec `open` operation. If the file is huge, and we only need read a piece of data from the file. It's wasting time to download it.

Can we change to only download data when we really need to read them? Seems blob API already support this: https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-the-range-header-for-blob-service-operations 

BTW, I use the blobfuse in `read-only` mode.

**Comment by amnguye** [comment]
Hi,

We don't have plans on how to support downloading a portion of a blob, how to expose that and implementing it. We download the entire blob to emulate a POSIX like environment. If you would like to only download part of the blob, I recommend using one of our storage SDKs.

https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage
There's more I have not listed, but here are some of them.

**Comment by Binyang2014** [comment]
Hi Amanda,
Thanks for reply, will try to use `Azure storage SDK`. But support download a portion of blob may be useful for some workload.  :-)
