### ISSUE TITLE
I want to use managed identity to authenticate to mount using blobfuse, Please help me. 

### ISSUE THREAD

**Issue by PradeepYadav1788** [Azure/azure-storage-fuse#371]

**Comment by PradeepYadav1788** [comment]
I dont want to put my storage key or SAS token, Just want to use managed identity, I have already configured from azure side , Please guide how can I use managed identity for blobfuse

**Comment by amnguye** [comment]
Please read our methods to set up authentication.
https://github.com/Azure/azure-storage-fuse#valid-authentication-setups
