### ISSUE TITLE
blobfuse mount random becomes inaccessible  with "Transport endpoint is not connected"

### ISSUE THREAD

**Issue by luna1230** [Azure/azure-storage-fuse#373]
### Which version of the blobfuse was used?
blobfuse 1.0.2

### Which OS (please include version) are you using?
CentOS 6.8

### What problem was encountered?
blobfuse mount random becomes inaccessible  with "Transport endpoint is not connected"

### Have you found a mitigation/solution?
mount again

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
 I using default setting and I don‘t see any blobfuse error in syslog 

### If relevant, please share your mount command.
blobfuse /var/log/temp --tmp-path=/mnt/abc/blobfusetmp --config-file=fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=120 -o allow_other-cache-timeout-in-seconds=60 -o negative_timeout=120 

temp-path location is 94G and VM is D3v2

**Comment by amnguye** [comment]
Hi,

Can you please set the a flag on your mount command "--log-level=LOG_DEBUG" and please send what gets displayed in the syslog. You might be running into issues of running out of space in your cache, so I suggest setting your cache time out to something lower to like 10 seconds or even 1 second. Also not opening many files/blobs at once. However its hard to diagnose the problem when I dont know what you're doing up to when the mount point gets disconnected.

**Comment by NaraVen** [comment]
We have fixed this in our latest source code. We have not yet released the package for CentOS but the source code is uptodate.

**Comment by leonardomiranda13** [comment]
I Solve this problem removing from /etc/mtab the blobfuse mount line, something like this:

blobfuse /source fuse rw,nosuid,nodev,allow_other,max_read=131072 0 0

After you remove this line, reboot your VM and try to mount again.

**Comment by NaraVen** [comment]
> ### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
> I using default setting and I don‘t see any blobfuse error in syslog
There are 2 ways to check the errors
1) 
In centOS syslog is probably not enabled . Make sure you modify your /etc/rsyslog.conf to include *.debug    /var/log/messages
also restart the rsyslog service.
service rsyslog restart         ### CentOS  6

then run blbofuse and check the logs
sudo tail -100 /var/log/messages

2) The other way to see the error would be 
sudo journalctl -fn0 &

If you can post the error here we can track down the problem

**Comment by saswatac** [comment]
I was facing this issue in my container. To troubleshhoot, i had to install syslog `apt-get install rsyslog -y`  and start it `service rsyslog restart` . After mounting the bucket again and running my workload, i got the following logs i syslog -

```
Aug 29 16:21:06 test-1-7778c76b6f-jvssb kernel: [ 5829.499483] audit: type=1325 audit(1598718066.768:1961): table=filter family=2 entries=241
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031178] blobfuse cpuset=48b0a4e0bca437fb449683713d5664ba33154129a0892f66c1bf5d7beba6136c mems_allowed=0
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031183] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS 090007  06/02/2017
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031191]  dump_stack+0x6d/0x92
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031198]  out_of_memory+0x11d/0x4c0
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031201]  mem_cgroup_out_of_memory+0xb9/0xd0
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031205]  ? mem_cgroup_css_reset+0xe0/0xe0
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031211]  mm_fault_error+0x8f/0x190
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031214]  __do_page_fault+0x480/0x4d0
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031219]  ? page_fault+0x2f/0x50
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031222] RSP: 002b:00007f9ec9bfb4b0 EFLAGS: 00010206
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031225] R13: 00007f9eae526fc0 R14: 0000000000000040 R15: 00007f9ec4000080
Aug 29 16:21:19 test-1-7778c76b6f-jvssb kernel: [ 5842.031230] memory: usage 262144kB, limit 262144kB, failcnt 9827
```

This seemed to indicate the container reaching its memory limit. Increasing the requests and limits on the container fixed the issue.

**Comment by NaraVen** [comment]
I recommend at 3GB memory for containers. Blobfuse consumes anywhere from 2GB to 8GB memory based on your file-cache-timeout-in-minutes and storage size. Also, please checkout the prebuilt blobfuse rpms at https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux. Please reopen this issue if you still have issues.
