### ISSUE TITLE
[Feature Request] Expose option to configure how much free space to keep on drive for caching

### ISSUE THREAD

**Issue by rongduan-zhu** [Azure/azure-storage-fuse#375]
### Which version of the blobfuse was used?
1.2.1

### Which OS (please include version) are you using?
Ubuntu 16.04

### What problem was encountered?
There are currently no options exposed for the user to specify how much free space should be kept available on the drive that is used for caching data.

We have a scenario where we are running on VMs that requires a minimum amount of space to be kept available on the drive where the cache directory is set for blobfuse otherwise the VM will become unusable. To add to the complexity, we use VMs of different sizes, some of them have smaller disks while others have much bigger disks. Using the timeout option is not ideal since we are just guessing based on the throughput of the blob service, and this can negatively impact performance since for our scenario, the files in blob don't actually change, and if we need to access existing files, they will need to be redownloaded and cached.

### Have you found a mitigation/solution?
None

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
N/A

### If relevant, please share your mount command.
N/A

**Comment by NaraVen** [comment]
The command line param is --cache-in-mb=< max_cacahe_in bytes>
Closing this issue since it is released in 1.3.1 and later.
