### ISSUE TITLE
Error when mounting blobfuse on Ubuntu 18.04

### ISSUE THREAD

**Issue by Oscar-BT** [Azure/azure-storage-fuse#376]
### Which version of the blobfuse was used?
1.2.1

### Which OS (please include version) are you using?
Ubuntu 18.04.3 LTS

### What problem was encountered?
Random error when mounting blobfuse at boot (the entry is not mounted at startup), but if after startup we execute command, the mount is correct.

### Have you found a mitigation/solution?
Mounting manually.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Mar 24 07:59:38 vmangularpro blobfuse[2172]: Tue Mar 24 07:59:38 2020 ==> REQUEST/RESPONSE
                                                     GET https://***.blob.core.windows.net/private?comp=list&delimiter=/&include=metada
                                                     User-Agent: [Azure-Storage-Fuse/1.2.1]
                                                     x-ms-date: [Tue, 24 Mar 2020 07:59:17 GMT]
                                                     x-ms-version: [2017-11-09]
                                                     Transfer-Encoding: []
                                                     --------------------------------------------------------------------------------
                                                     RESPONSE Status: 0
Mar 24 07:59:47 vmangularpro blobfuse[2172]: Tue Mar 24 07:59:47 2020 ==> REQUEST/RESPONSE
                                                     GET https://***.blob.core.windows.net/private?comp=list&delimiter=/&include=metada
                                                     User-Agent: [Azure-Storage-Fuse/1.2.1]
                                                     x-ms-date: [Tue, 24 Mar 2020 07:59:17 GMT]
                                                     x-ms-version: [2017-11-09]
                                                     Transfer-Encoding: []
                                                     Expect: []
                                                     User-Agent: [Azure-Storage-Fuse/1.2.1]
                                                     x-ms-date: [Tue, 24 Mar 2020 07:59:38 GMT]
                                                     x-ms-version: [2017-11-09]
                                                     Transfer-Encoding: []
                                                     --------------------------------------------------------------------------------
                                                     RESPONSE Status: 0
Mar 24 07:59:47 vmangularpro blobfuse[2172]: Tue Mar 24 07:59:47 2020 ==> REQUEST/RESPONSE
                                                     GET https://***.blob.core.windows.net/private?comp=list&delimiter=/&include=metada
                                                     User-Agent: [Azure-Storage-Fuse/1.2.1]
                                                     x-ms-date: [Tue, 24 Mar 2020 07:59:17 GMT]
                                                     x-ms-version: [2017-11-09]
                                                     Transfer-Encoding: []
                                                     Expect: []
                                                     User-Agent: [Azure-Storage-Fuse/1.2.1]
                                                     x-ms-date: [Tue, 24 Mar 2020 07:59:38 GMT]
                                                     x-ms-version: [2017-11-09]
                                                     Transfer-Encoding: []
                                                     Expect: []
                                                     User-Agent: [Azure-Storage-Fuse/1.2.1]
                                                     x-ms-date: [Tue, 24 Mar 2020 07:59:47 GMT]
                                                     x-ms-version: [2017-11-09]
                                                     Transfer-Encoding: []
                                                     --------------------------------------------------------------------------------
                                                     **RESPONSE Status: 400**
                                                     Content-Length: [353]
                                                     Content-Type: [application/xml]
                                                     Date: [Tue, 24 Mar 2020 07:59:47 GMT]
                                                     Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
                                                     **x-ms-error-code: [InvalidHeaderValue]**
                                                     x-ms-request-id: [efb59540-101e-0068-67b2-017106000000]
Mar 24 07:59:47 vmangularpro blobfuse[2172]: Unable to start blobfuse.  Failed to connect to the storage container. There might be something wrong abo
Mar 24 07:59:47 vmangularpro mount[1201]: Failed to connect to the storage container. There might be something wrong about the storage config, please
Mar 24 07:59:47 vmangularpro systemd[1]: var-www-html-private.mount: Failed with result 'exit-code'.
Mar 24 07:59:47 vmangularpro systemd[1]: Failed to mount /var/www/html/private.
Mar 24 07:59:47 vmangularpro systemd[1]: Dependency failed for Remote File Systems.
Mar 24 07:59:47 vmangularpro systemd[1]: remote-fs.target: Job remote-fs.target/start failed with result 'dependency'.

### If relevant, please share your mount command.
sudo -u www-data blobfuse /var/www/html/pre_web/backend/private --tmp-path=/mnt/blob_tmp/private --config-file=/var/www/scripts/fuse_connection_private.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --file-cache-timeout-in-seconds=0 -o allow_root -o nonempty

**Comment by amnguye** [comment]
Responded to the IcM which was submitted. We will close this issue when that IcM is closed. Please let me know if this problem is not relevant to the IcM I am referring to.

**Comment by NaraVen** [comment]
From the ICM, It was identified that multiple mounts to the same blob were happening to read/write blobs. Multiple mounts are possible only for readonly blobs.  Closing this ussue.
