### ISSUE TITLE
error while loading shared libraries: libgnutls.so.26

### ISSUE THREAD

**Issue by kj299** [Azure/azure-storage-fuse#378]
### Which version of the blobfuse was used?
$ dpkg-query -s blobfuse
Package: blobfuse
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 23369
Maintainer: Microsoft - Azure Storage
Architecture: amd64
Version: 1.2.1
Depends: fuse
Description: blobfuse 1.2.1 - FUSE adapter for Azure Blob Storage

### Which OS (please include version) are you using?
$ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 19 Tara
Release:        19
Codename:       tara

Linux hostname 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What problem was encountered?
blobfuse: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory

### Have you found a mitigation/solution?
no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
there was no relevant information within /var/log/syslog 

### If relevant, please share your mount command.
sudo blobfuse ~/mycontainer --tmp-path=/mnt/ramdisk/blobfusetmp --config-file=/home/username/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

**Comment by NaraVen** [comment]
LinuxMint is not a supported issue. In order to run Blobfuse in LinuxMint it is best to get the source code and compile it.

**Comment by kj299** [comment]
@NaraVen can you let me know which specific elements are not supported within LinuxMint? It will help me determine if there is something I can update to enable support. Thanks!

**Comment by NaraVen** [comment]
We have never tested it so I can't comment on specifics. Mot likely you can get it working with minor tweaks.

**Comment by kj299** [comment]
as directed

1. i had to download libfuse
2. build libfuse from source
3. reinstall all dependencies listed on this [azure-storage-fuse page ](https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation#build-from-source)
4. after following those instructions on how to rebuild the blobfuse
5. added `cd build/ ; sudo make install`
6. verified the appropriate PATH to the new blobfuse binary was in place
7. reran this command
`sudo blobfuse ~/mycontainer --tmp-path=/mnt/ramdisk/blobfusetmp --config-file=/home/username/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120`
8. checked on my azure portal and now see the file

thanks
