### ISSUE TITLE
blobfuse throws basic_string::_S_construct null not valid when trying to mount

### ISSUE THREAD

**Issue by mikejwhitty** [Azure/azure-storage-fuse#38]
I couldn't find a better place to ask this question, so please forgive if this isn't the right place. 

I have a clean centos 7.4 VM located in the same azure region (UK South) as my blob storage account. I've installed the `blobfuse` tool using `yum` with the package source listed on the wiki. I'm currently using root for everything.

I've created a temp directory in /mnt/resources and a config file in /root/conf/betaep1.cfg -- which it is able to read because if it can't it fails differently.

The content of my cfg file is (removing the key):

```
accountName onefilearc
accountKey [redacted]
containerName testfuse
```

The storage account is a blob-storage account, the container exists and contains files and can be accessed with the key via e.g. powershell, .net libraries. I thought perhaps the "account" name needed to be different and so tried the blob storage endpoint url and tried that.

And the blobfuse command I'm running is:

```
blobfuse /mnt/betaep1 --temp-path=/mnt/resource/betaep1 -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/root/conf/betaep1.cfg
```

which gives the output:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted
```

... any ideas?

**Comment by seguler** [comment]
Thanks for posting this here. I just tested your settings and got the same failure. The reason is that you have a typo: temp-path. You should instead use --tmp-path option

**Comment by seguler** [comment]
Let me know if anywhere in the documents we have a typo that shows this as --temp-path rather than --tmp-path

**Comment by mikejwhitty** [comment]
Well... aren't I an idiot. Sorry @seguler 

I now get the error:

```
Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 1600
```

which I'm going to hope is the same as the issue at https://github.com/Azure/azure-storage-fuse/issues/35 re: http/https and the workaround in #37 does seem to work.

but is it expected that the `blobfuse` command doesn't return?

**Comment by seguler** [comment]
Yes when you use -f option, blobfuse will not return and instead runs in debug mode. You can simply send this to background:

blobfuse /mnt/betaep1 --tmp-path=/mnt/resource/betaep1 -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/root/conf/betaep1.cfg **&> /tmp/blobfuse.log**
