### ISSUE TITLE
How to install release 1.2.x

### ISSUE THREAD

**Issue by norjen** [Azure/azure-storage-fuse#380]
### Which OS (please include version) are you using?
CentOS 7

### What problem was encountered?
When following the install guide: https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation on CentOS 7 in Azure, you get Blobfuse version: 1.0.2-1 

yum list installed | grep blobfuse
blobfuse.x86_64                      1.0.2-1                        @packages-microsoft-com-prod

Github releases (https://github.com/Azure/azure-storage-fuse/releases) provides access to 1.1.1

But I need to utilize Manged Identity (MSI) and needs releas 1.2.x but I can't find that anywhere.

Please advise

**Comment by NaraVen** [comment]
We have not pushed 1.2.1 toRHEL. Reason being we have not validated custom MSI endpoint in 1.2.1 on CentOS. The Azure managed VM  or VMSS endpoint works. If that is what you are looking for. You can download the source code and build it. Will that work?
