### ISSUE TITLE
Error Install Blobfuse on CentOS 8.

### ISSUE THREAD

**Issue by xiangwu-ms** [Azure/azure-storage-fuse#381]
### Which version of the blobfuse was used?
https://packages.microsoft.com/rhel/8/prod/
blobfuse-1.1.1.el7.x86_64.rpm      

### Which OS (please include version) are you using?
[root@localhost yum.repos.d]# uname -r
4.18.0-147.el8.x86_64

### What problem was encountered?
[root@localhost yum.repos.d]# sudo yum install blobfuse fuse
packages-microsoft-com-prod                                                                                                                   3.8 MB/s | 5.3 MB     00:01
Last metadata expiration check: 0:00:13 ago on Tue 07 Apr 2020 12:24:10 PM EDT.
Error:
 Problem: conflicting requests
  - nothing provides libboost_system-mt.so.1.53.0()(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libboost_thread-mt.so.1.53.0()(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libgnutls.so.28(GNUTLS_1_4)(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libgnutls.so.28()(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libboost_filesystem-mt.so.1.53.0()(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libgcrypt.so.11(GCRYPT_1.2)(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libgcrypt.so.11()(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libgnutls.so.28(GNUTLS_2_10)(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

### Have you found a mitigation/solution?
Seems have to build myself

**Comment by TNLion** [comment]
I am having the same issue. Do you have process to build your own package? Not sure what needs to be done.

Thanks

**Comment by NaraVen** [comment]
To build your own package you can clone the source code , yum install the binaries specified in the wiki and run the build.sh. It will create a blobfuse binary. If your org requires you to generate an rpm . Add one more step which is run the generate.rpm. It will create an apm and when you yum install the rpm. The blobfuse binary will be installed.

**Comment by MisiekBest** [comment]
> I am having the same issue. Do you have process to build your own package? Not sure what needs to be done.
> 
> Thanks

Yeap, same for me (CentOS 8, 4.18.0-193.6.3.el8_2.x86_64@AzureVM).
Here are the instructions on how to build it from scratch:

https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation#option-2---build-from-source

**Comment by marbed7** [comment]
Yeap, you can build the package and you can even install it properly on CentOS 8, but it doesn't mount the blob storage under a mount point. I can't find any error messages anywhere in the logs.

**Comment by TNLion** [comment]
Followed the instructions for the build. however when I run the mount script says it cant find "blobfuse: Cant find command. any ideas have I missed something? or is there still a bug.

**Comment by TNLion** [comment]
got the blobfuse part to work now however like someone else said it wont mount. run the mount option. It looks like its going to mount but then nothing. any ideas?

**Comment by NaraVen** [comment]
> Followed the instructions for the build. however when I run the mount script says it cant find "blobfuse: Cant find command. any ideas have I missed something? or is there still a bug.

a bug was introduced in the latest check in. I will update this thread  as soon as we finish the fix PR.

**Comment by arnofourie** [comment]
Any progress on the fix you mentioned @NaraVen? I've built and no errors are being thrown (RHEL8) but doesn't actually mount.  Also, it seems like the package that is in the Microsoft repo for RH8 is still the RH7 package (hence me having to build it).

**Comment by NaraVen** [comment]
@arnofourie , @TNLion, @xiangwu-ms, @marbed7 We have uploaded rpms for our latest release at https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux.  This should resolve the build issues you are facing.
