### ISSUE TITLE
Blobfuse failed to read data due to std::bad_alloc

### ISSUE THREAD

**Issue by Binyang2014** [Azure/azure-storage-fuse#382]
### Which version of the blobfuse was used?
blobfuse 1.2.1

### Which OS (please include version) are you using?
ubuntu 18.04 docker container

### What problem was encountered?
Failed to open file in Azure blob

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Apr  7 12:16:40 *** blobfuse[1146]: Unknown failure in download_blob_to_file.  ex.what() = std::bad_alloc, container = *** , blob = *** , destPath = /mnt/resource/blobfusetmp/blobserver/root/data/imagenet/train/*** .JPEG.
Apr  7 12:16:40 ** blobfuse[1146]: Failed to download blob into cache.  Blob name: data/imagenet/train/*** .JPEG, file name = /mnt/resource/blobfusetmp/blobserver/root/data/*** /imagenet/train/*** .JPEG, storage errno = 1600.

**Comment by NaraVen** [comment]
How big are the jpgs and how much is the cache in your machine?

**Comment by Binyang2014** [comment]
@Nara, thanks for reply,
The JPEG size is range form 10K-1M. I repeat many times and each time the `bad_alloc` exception raise by reading different jpeg.

I'm not sure the cache size you mean.  I use cmmand `blobfuse /tmp_azure_blob_test_root --tmp-path=/mnt/resource/blobfusetmp/azure_blob_test --config-file=/azure_blob_test.cfg -o attr_timeout=240` to mount the azure-blob.

I also has an image-net tar ball in the azureblob, the size is about 150GB. When I download it to local disk and use the extracted tar file. It works fine.

**Comment by NaraVen** [comment]
Could you please get the latest version 1.2.3 ? We have fixed a similar error in the 1.2.3 release.

**Comment by Binyang2014** [comment]
Thanks, will have a try

**Comment by NaraVen** [comment]
@Binyang2014 , We cannot repro this our latest release 1.3.4 even when we set file-cache-timeout-in-seconds= 1200. Blobfuse does consume about 3 GB memory but this issue does not happen.  I am closing this for now.  Feel free to reopen if the issue still persists.
