### ISSUE TITLE
`java.nio.file.NoSuchFileException` while reading a file which does exist.

### ISSUE THREAD

**Issue by 5hubh4m** [Azure/azure-storage-fuse#383]
### Which version of the blobfuse was used?
1.2.1

### Which OS (please include version) are you using?
Ubuntu 16.04

### What problem was encountered?
I'm encountering the exception `java.nio.file.NoSuchFileException: /mnt/checkpoint/1/tick/DONE` on trying to access a file which most definitely exists in the container. I can see the file on the Azure Portal but also the code is wrapped in a condition which checks whether the file exists, like so:

`if (Files.exists(tickFile)) Some(new String(Files.readAllBytes(tickFile)).toInt) else None`

This problem also occurs when running an ImageNet training script reading the images from a directory mounted using `blobfuse`. The training terminates with a `FileNotFound` exception but I can clearly see the file in the Azure Portal.

This only started occurring after I updated the `blobfuse` package so this might be a regression.

### Have you found a mitigation/solution?
No.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Cannot see the syslog as this job is running inside a Kubernetes container using [Azure/kubernetes-volume-drivers](https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/blobfuse).

### If relevant, please share your mount command.
The container is mounted using the [Azure/kubernetes-volume-drivers](https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/blobfuse) with basic configuration.

Does anyone have any ideas on why this might be happening or if there is something I'm missing with respect to some config that can help address this?

**Comment by NaraVen** [comment]
Are all the downloads failing or only selective file?
Does the file system get unmounted after this exception?

**Comment by NaraVen** [comment]
1.2.1 has MSI. If you do not need MSI I suggest you use 1.1.1. We are yet to look into this in 1.2.1 . However this was never reported in 1.1.1

**Comment by NaraVen** [comment]
This is fixed in Release 1.2.3
