### ISSUE TITLE
Mount fail with SPN authtype

### ISSUE THREAD

**Issue by zhangzexing789** [Azure/azure-storage-fuse#384]
### Which version of the blobfuse was used?
blobfuse 1.0.2

### Which OS (please include version) are you using?
RedHat 7

### What problem was encountered?
Occur below info:
Unable to start blobfuse. Exactly one of Account Key and SAS token must be specified in the config file, and the other line should be deleted.

### Have you found a mitigation/solution?
NO

### If relevant, please share your mount command.
sudo blobfuse /infa_dev/infa_shared/azure/test --tmp-path=/mnt/resource/blobfusetmp  --config-file=/infa_dev/infa_shared/HalleyCommon/blobfuse/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Comment by NaraVen** [comment]
Do you have the entries similar to below in your =/infa_dev/infa_shared/HalleyCommon/blobfuse/fuse_connection.cfg  config file?

accountName <abcaccount>
accountKey <jhjhkjbase64 key>
authType Key
containerName <abccontainer>

**Comment by zhangzexing789** [comment]
hi,
Using SPN Authentication also need accountKey?

**Comment by NaraVen** [comment]
Oh for SPN, you need SaSKey
Have you specified it?

**Comment by zhangzexing789** [comment]
But I don't understand why SPN authentication need SAS token?
I have assign role "Storage data contributor" to service principal which have enough permission to access storage account. And I think if have SAS token so SPN authentication is excess.

**Comment by amnguye** [comment]
SPN auth is not offered on v1.0.2, you have to upgrade to 1.2+ at least to get that support.

**Comment by NaraVen** [comment]
> But I don't understand why SPN authentication need SAS token?
> I have assign role "Storage data contributor" to service principal which have enough permission to access storage account. And I think if have SAS token so SPN authentication is excess.

SPN is service principal auth but you cannot use it for the earlier version. So, you need a storage key or SasKey instead.

**Comment by NaraVen** [comment]
version 1.0.2 needs a SaS or storage Key. So closing this issue
