### ISSUE TITLE
./build.sh failed on Suse 12 SP5

### ISSUE THREAD

**Issue by kevinzhang8888** [Azure/azure-storage-fuse#385]
### Which version of the blobfuse was used?
the latest download from github as fo 4/23/2020

### Which OS (please include version) are you using?
suse 12 SP5

### What problem was encountered?
-- Checking for one of the modules 'uuid'
bash: go: command not found
-- Configuring incomplete, errors occurred!
See also "/root/azure-storage-fuse/build/CMakeFiles/CMakeOutput.log".
See also "/root/azure-storage-fuse/build/CMakeFiles/CMakeError.log".
cmake failed.  Please ensure that cmake version 3.5 or greater is installed and available.

**Comment by NaraVen** [comment]
Uuid may need to be manually installed for OpenSuSe.
Try the Example below based on your version.
zypper addrepo https://download.opensuse.org/repositories/openSUSE:13.1/standard/openSUSE:13.1.repo
zypper refresh
zypper install uuid

**Comment by NaraVen** [comment]
Can I clsoe thsi, Did installing uuid fix the issue?

**Comment by kevinzhang8888** [comment]
demo@hn1-hdb0:~> sudo su - root
hn1-hdb0:~ # zypper addrepo
https://download.opensuse.org/repositories/openSUSE:13.1/standard/openSUSE:13.1.repo
File '/repositories/openSUSE:13.1/standard/openSUSE:13.1.repo' not found on
medium 'https://download.opensuse.org/'
Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
Problem encountered while trying to read the file at the specified URI:
ABORT request: Aborting requested by user

**Comment by kevinzhang8888** [comment]
in Suse 12 SP5: uuid changed to uuidd package
hn1-hdb0:~ # zypper install uuidd
Refreshing service 'Advanced_Systems_Management_Module_x86_64'.
Refreshing service 'Containers_Module_x86_64'.
Refreshing service 'HPC_Module_x86_64'.
Refreshing service 'Legacy_Module_x86_64'.
Refreshing service 'Public_Cloud_Module_x86_64'.
Refreshing service
'SUSE_Linux_Enterprise_Server_for_SAP_Applications_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Software_Development_Kit_x86_64'.
Refreshing service 'Toolchain_Module_x86_64'.
Refreshing service 'Web_and_Scripting_Module_x86_64'.
Loading repository data...
Reading installed packages...
'uuidd' is already installed.
No update candidate for 'uuidd-2.33.2-2.10.x86_64'. The highest available
version is already installed.
Resolving package dependencies...

**Comment by NaraVen** [comment]
Looks like this is the package for suse 12
zypper addrepo https://download.opensuse.org/repositories/devel:libraries:c_c++/SLE_12_SP5/devel:libraries:c_c++.repo
zypper refresh
zypper install uuid

**Comment by takhoshi** [comment]
hi, i am having the same issue. After running all zypper commands as mentioned above, i am still facing the following issue with CMake on SLES12 SP4. 

>>>>> 

VM-ANF-AZACSNAP:/root/azure-storage-fuse # ./build.sh
mkdir: cannot create directory ‘build’: File exists
./build.sh: line 16: cmake3: command not found
-- Boost version: 1.54.0
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1657 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_filesystem
          boost_system

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)


CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1657 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_thread

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:136 (find_package)


bash: go: command not found
-- Configuring incomplete, errors occurred!
See also "/root/azure-storage-fuse/CMakeFiles/CMakeOutput.log".
See also "/root/azure-storage-fuse/CMakeFiles/CMakeError.log".
cmake failed.  Please ensure that cmake version 3.5 or greater is installed and available.

**Comment by NaraVen** [comment]
Ok, so that error got resolved then, now you have gone further.
You can ignore the cmake3 : command not found. ( I have to remove it from the build.sh. It is an unnecessary warning)
For the boost not found. Looks like the path did not get set.
You should find where boost is installed and set the following
set(BOOST_LIBRARYDIR path/to/your/lib/folder)

**Comment by NaraVen** [comment]
since the build succeeded i am closing this.

**Comment by takhoshi** [comment]
hi NaraVen,

I found a number of files with a name with "libboost_*" at usr/lib64. So i run set BOOST_LIBRARYDIR /usr/lib64, but still am seeing the same error with cmake. Can you pls elaborate what I should do, if you already tested on SLES ? 
 
>>>

VM-ANF-AZACSNAP:/root/azure-storage-fuse # ./build.sh
mkdir: cannot create directory ‘build’: File exists
./build.sh: line 16: cmake3: command not found
-- Boost version: 1.54.0
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1657 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_filesystem
          boost_system

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)


CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1657 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_thread

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:136 (find_package)


bash: go: command not found
-- Configuring incomplete, errors occurred!
See also "/root/azure-storage-fuse/build/CMakeFiles/CMakeOutput.log".
See also "/root/azure-storage-fuse/build/CMakeFiles/CMakeError.log".
cmake failed.  Please ensure that cmake version 3.5 or greater is installed and available.
VM-ANF-AZACSNAP:/root/azure-storage-fuse #

**Comment by NaraVen** [comment]
I will check your boost install. You can do a zipper rm boost … and then a zipper install for the boost libraries to make sure it is a clean install
