### ISSUE TITLE
list may take some time and Ctrl+C will not stop it

### ISSUE THREAD

**Issue by dashesy** [Azure/azure-storage-fuse#390]
### Which version of the blobfuse was used?
1.2.1

### Which OS (please include version) are you using?

Ubuntu 16.04

### What problem was encountered?

Listing a directory with many many files, will take a long time, instead of starting to show the list while looking.
Also Ctrl+C signal is not working when doing ls.

### Have you found a mitigation/solution?

I kill the process, then unmount and mount again

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

I will capture that next time.

**Comment by NaraVen** [comment]
Blobfuse is non interactive once it is mounted. So, why should Ctrl-C work? I understand you are talking about some kind of list like ls -al in the mount directory or a sub-directory. If Ctrl-C does not work there Shouldn't it be a VM response issue?

**Comment by dashesy** [comment]
Yes it is `ls` that lists the files.
If there are many files list operation should not wait to get the full list but instead stream the content and stop if Ctrl+C signal is received.
Even if the entire list is being fetched the SIGINT signal should stop it.

**Comment by NaraVen** [comment]
Try ls -f instead of ls .Also, Ctrl-C works if you build our latest source code. It is also faster in our latest codebase. We will be releasing version 1.3.1 soon.

**Comment by dashesy** [comment]
Thanks. I had to check for "ls -f" 

```text
-f                         do not sort, enable -aU, disable -ls --color
```

It makes sense. Sorting may need to buffer everything and thus will try to load all the names.
