### ISSUE TITLE
Fetch account name and container name from SAS URI

### ISSUE THREAD

**Issue by soumyadebabrata** [Azure/azure-storage-fuse#391]
Please add support for SAS URI in .cfg file. That way user don't have to provide account name and container name separately, they can be just derived from the SAS URI.

**Comment by NaraVen** [comment]
We will add this to our feature request list.  Thank you!

**Comment by vibhansa-msft** [comment]
We will not be adding this feature to blobfuse, as we have stopped taking any more feature requests for it.
We are working on our next generation of blobfuse which is in preview mode as of now. You can find the binaries in our release section here.
