### ISSUE TITLE
Blobfuse Mount not working with FSTAB

### ISSUE THREAD

**Issue by TNLion** [Azure/azure-storage-fuse#392]
### Which version of the blobfuse was used?
blobfuse-1.0.2-1.x86_64 blobfuse-1.0.2-1.x86_64 

### Which OS (please include version) are you using?
Redhat 7

### What problem was encountered?
I have setup all the blob storage correctly and everything runs manually. I have done my version of this line in the FSTAB file:

/<path_to_blobfuse>/mount.sh /mnt/azuresa fuse _netdev

However when restarting the server it doesnt mount the volumes and you have run it manually

### Have you found a mitigation/solution?
No

### If relevant, please share your mount command.

blobfuse /mnt/azuresa --tmp-path=/mnt/aztemp --config-file=/mnt/aztemp/blobfuse.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --file-cache-timeout-in-seconds=0 -o allow_other

**Comment by NaraVen** [comment]
what's the line you have in fstab?
Do you have delay_connect, uid=10000, gid=000 as options to mount.sh. If not consider adding that so that it mounts after the boot sequence is done.

**Comment by TNLion** [comment]
Hi

The line I added to the FSTAB file is based on the document recommendation above?

/mnt/contenttemp/mount.sh /mnt/contentazuresa fuse _netdev

I dont have the entries you receommend in my mount.sh file so will add them and see if they work.

**Comment by NaraVen** [comment]
Since it is working. I am closing this one.

**Comment by JayDwivedi09** [comment]
Add the following line in /etc/fstab without run mount.sh

blobfuse /blob fuse defaults,_netdev,--tmp-path=/mnt/resource/blob,--config-file=/home/infomatica/blob.cfg,--log-level=LOG_DEBUG,allow_other 0 0
