### ISSUE TITLE
Multiple mount points?

### ISSUE THREAD

**Issue by maiorfi** [Azure/azure-storage-fuse#393]
Is it possible to run several blobfuse instances in order to have more than one mount point bound to different blob containers?

**Comment by NaraVen** [comment]
Yes, but for readonly no guarantee for writes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by maiorfi** [comment]
No guarantee even in the case of mount points pointing to distinct blob containers?

**Comment by NaraVen** [comment]
If every mountpoint is mounted to a different container then no issues. You can read and write. Single container with multiple mountpoints is only supported for reads.

**Comment by maiorfi** [comment]
Great, thanks.
