### ISSUE TITLE
blobfuse is not working on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by alexthemans** [Azure/azure-storage-fuse#395]
### Which version of the blobfuse was used?
blobfuse 1.2.2

### Which OS (please include version) are you using?
Ubuntu 20.04 LTS

### What problem was encountered?
The destination folder is not mounted as expected even the command said it had executed successfully.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
May  4 14:23:18 hkas-pubsys-prod-vm2 blobfuse[67328]: Mon May  4 14:23:18 2020 ==> REQUEST/RESPONSE#012#011GET https://hkaspubsysbackup.blob.core.windows.net/hkaspubsysdbbackup?comp=list&delimiter=/&include=metadata&maxresults=1&restype=container#012#011User-Agent: [Azure-Storage-Fuse/1.2.1]#012#011x-ms-date: [Mon, 04 May 2020 14:23:17 GMT]#012#011x-ms-version: [2017-11-09]#012#011Authorization: [REDACTED]#012#011Transfer-Encoding: []#012#011--------------------------------------------------------------------------------#012#011RESPONSE Status: 200#012#011Content-Type: [application/xml]#012#011Date: [Mon, 04 May 2020 14:23:17 GMT]#012#011Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]#012#011Transfer-Encoding: [chunked]#012#011x-ms-request-id: [db2688c7-701e-00d9-521f-222b71000000]#012#011x-ms-version: [2017-11-09]
May  4 14:23:18 hkas-pubsys-prod-vm2 blobfuse[67328]: Function ensure_files_directory_exists_in_cache, in file /home/ubuntu/azure-storage-fuse/blobfuse/utilities.cpp, line 244: Making cache directory /var.
May  4 14:23:18 hkas-pubsys-prod-vm2 blobfuse[67328]: Function ensure_files_directory_exists_in_cache, in file /home/ubuntu/azure-storage-fuse/blobfuse/utilities.cpp, line 244: Making cache directory /var/tmp2.
May  4 14:23:18 hkas-pubsys-prod-vm2 blobfuse[67328]: Function ensure_files_directory_exists_in_cache, in file /home/ubuntu/azure-storage-fuse/blobfuse/utilities.cpp, line 244: Making cache directory /var/tmp2/blobfuse.
May  4 14:23:18 hkas-pubsys-prod-vm2 blobfuse[67328]: Function ensure_files_directory_exists_in_cache, in file /home/ubuntu/azure-storage-fuse/blobfuse/utilities.cpp, line 244: Making cache directory /var/tmp2/blobfuse/hkaspubsysdbbackup.
May  4 14:23:18 hkas-pubsys-prod-vm2 blobfuse[67328]: Function ensure_files_directory_exists_in_cache, in file /home/ubuntu/azure-storage-fuse/blobfuse/utilities.cpp, line 244: Making cache directory /var/tmp2/blobfuse/hkaspubsysdbbackup/root.
May  4 14:23:18 hkas-pubsys-prod-vm2 blobfuse[67331]: Function azs_destroy, in file /home/ubuntu/azure-storage-fuse/blobfuse/utilities.cpp, line 523: azs_destroy called.
May  4 14:23:18 hkas-pubsys-prod-vm2 systemd[67114]: blob-hkaspubsysdbbackup.mount: Succeeded.
May  4 14:23:18 hkas-pubsys-prod-vm2 systemd[1]: blob-hkaspubsysdbbackup.mount: Succeeded.

### If relevant, please share your mount command.
 sudo /usr/bin/blobfuse /blob/hkaspubsysdbbackup --tmp-path=/var/tmp2/blobfuse/hkaspubsysdbbackup --config-file=/etc/blobfuse/hkaspubsysdbbackup.cfg  -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG

**Comment by rottoza** [comment]
I have the exact same issue with Ubuntu 20.04

**Comment by OliverColeman** [comment]
I'm seeing the same.

**Comment by OliverColeman** [comment]
This gets stranger still. I'm seeing the same behaviour running blobfuse in a docker container, which is based on ubuntu 18.04, but running on a ubuntu 20.04 host. There's no escape!

Running the same docker container on a ubuntu 19.10 host works no problem.

**Comment by NaraVen** [comment]
Could you please attach your entire syslog?

**Comment by OliverColeman** [comment]
[syslog.txt](https://github.com/Azure/azure-storage-fuse/files/4631344/syslog.txt)

**Comment by vibhansa-msft** [comment]
libfuse version on Ubuntu-20 is 2.9.9 while blobFuse is compatible with 2.9.7. Just add '-d' option to your blobfuse command and see what error it reports. If you get "fuse: reading device: Invalid argument" then you are hitting the incompatibility issue. You can check your libfuse version using 'fusermount -V'.

**Comment by OliverColeman** [comment]
That looks like it @vibhansa-msft. I could only find libfuse 2.9.7 in the ubuntu 18.04 repos. When trying to force this version with apt it wanted to uninstall a lot of core packages... Is blobfuse likely to be upgraded any time soon to be compatible with libfuse 2.9.9?

**Comment by vibhansa-msft** [comment]
Downgrading libfues to 2.9.7 did not go like an easy option on Ubuntu-20. That being said as of now we do not have a plan for the upgrade but defiantly we will go over the feasibility of this.

**Comment by OliverColeman** [comment]
Given that 20.04 is now the latest stable LTS release of probably the most popular linux distribution on the planet, any chance of making this a bit of a priority?

**Comment by OliverColeman** [comment]
Given that 20.04 is now the latest stable LTS release of probably the most popular linux distribution on the planet, any chance of making this a bit of a priority? 😛

**Comment by amnguye** [comment]
I think @vibhansa-msft has already said that there would be more investigation into the feasibility of this. So I think there is a priority being given to it considering all the other features/issues and asks of the project, and also considering how recent Ubuntu 20.04 LTS was released (April 23, 2020).

Thanks for your patience.

**Comment by OliverColeman** [comment]
More info: I downgraded to libfuse 2.9.7 but it didn't seem to make any difference:
```
oliver@hubert > blobfuse /workspace/data --use-https=true --tmp-path=/mnt/blobfusetmpdev --config-file=../config/axml_blobfuse_dev.cfg -d
FUSE library version: 2.9.7
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.31
flags=0x03fffffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000031
   max_readahead=0x00400000
   max_write=0x00400000
   max_background=128
   congestion_threshold=96
   unique: 2, success, outsize: 40
fuse: reading device: Invalid argument
```

**Comment by vibhansa-msft** [comment]
Just to give more details on this issue, the error is being thrown from libfuse library. When libfuse is trying to read the /dev/fuse device to communicate with kernel module its encountering some failure. As conveyed earlier this needs more investigation. Might be due to new kernel version on Ubuntu-20. Will keep you posted if we figure out some workaround or potential fix for this.

**Comment by gitanoqevaporelmundoentero** [comment]
I include error log in ubuntu 20.04 with libfuse 2.9.9:

`
blobfuse -d /home/kim-yong-il/azure/rawdata --container-name=rawdata --tmp-path=/mnt/blobfusetmp  
FUSE library version: 2.9.9
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.31
flags=0x03fffffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000031
   max_readahead=0x00400000
   max_write=0x00400000
   max_background=128
   congestion_threshold=96
   unique: 2, success, outsize: 40
fuse: reading device: Invalid argument
`

**Comment by horiacristescu** [comment]
Is there a workaround?

**Comment by NaraVen** [comment]
> I include error log in ubuntu 20.04 with libfuse 2.9.9:
> 
> ```
> blobfuse -d /home/kim-yong-il/azure/rawdata --container-name=rawdata --tmp-path=/mnt/blobfusetmp  
> FUSE library version: 2.9.9
> nullpath_ok: 0
> nopath: 0
> utime_omit_ok: 0
> unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
> INIT: 7.31
> flags=0x03fffffb
> max_readahead=0x00020000
>    INIT: 7.19
>    flags=0x00000031
>    max_readahead=0x00400000
>    max_write=0x00400000
>    max_background=128
>    congestion_threshold=96
>    unique: 2, success, outsize: 40
> fuse: reading device: Invalid argument
> ```
@gitanoqevaporelmundoentero  , could you please add --log-level=LOG_DEBUG to your commandline and resend the output. Thank you

**Comment by NaraVen** [comment]
> Is there a workaround?

No workarounds since we haven't done troubleshooting. Most likely since the Kernel has changed there is a mismatch between the device sector size and default blocksize and reading is failing causing mount to fail. We may need to tweak the code on top of upgrading the libraries in the build.

**Comment by gitanoqevaporelmundoentero** [comment]
> @gitanoqevaporelmundoentero , could you please add --log-level=LOG_DEBUG to your commandline and resend the output. Thank you


I include below the new log with the `--log-level=LOG_DEBUG` option. I think the command yields the same output... :S Please let me know if you need me to attach further log files.

`
blobfuse -d /home/kim-yong-il/azure/rawdata --container-name=rawdata --tmp-path=/mnt/blobfusetmp --log-level=LOG_DEBUG
FUSE library version: 2.9.9
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.31
flags=0x03fffffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000031
   max_readahead=0x00400000
   max_write=0x00400000
   max_background=128
   congestion_threshold=96
   unique: 2, success, outsize: 40
fuse: reading device: Invalid argument
`

**Comment by anki-code** [comment]
@NaraVen I've built blobfuse on Ubuntu 20.04 and got no result and no messages.

Here is the commands:
```bash
lsb_release -a # Ubuntu 20.04 LTS
sudo bash # We will test this from root to avoid access glitches
mkdir /tmp/blobfuse && cd /tmp/blobfuse
# Build (https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation)
sudo apt-get install pkg-config libfuse-dev cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev libboost-all-dev gcc g++ -y
git clone https://github.com/Azure/azure-storage-fuse/
cd azure-storage-fuse
./build.sh

# Create directories and configs (https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux)
# THIS COMMANDS WAS TESTED AND WORKING ON Ubuntu 18.04

MOUNT_HOME=$PWD/azure
AZURE_ACCOUNT_NAME=myaccountname
AZURE_ACCOUNT_KEY=somekeyaslkdalkdjlkasdalksdjlkasdjlkadjl==
AZURE_ACCOUNT_CONTAINER=mycontainer

MOUNT_DIR=$MOUNT_HOME/$AZURE_ACCOUNT_NAME/$AZURE_ACCOUNT_CONTAINER
BLOBFUSETMP=$MOUNT_HOME/$AZURE_ACCOUNT_NAME/$AZURE_ACCOUNT_CONTAINER-blobfusetmp
AZURE_ACCOUNT_CONFIG_FILE=$MOUNT_HOME/$AZURE_ACCOUNT_NAME-$AZURE_ACCOUNT_CONTAINER.cfg

mkdir -p $BLOBFUSETMP $MOUNT_DIR
echo -e "accountName $AZURE_ACCOUNT_NAME\naccountKey $AZURE_ACCOUNT_KEY\ncontainerName $AZURE_ACCOUNT_CONTAINER" > $AZURE_ACCOUNT_CONFIG_FILE
chmod 600 $AZURE_ACCOUNT_CONFIG_FILE

$PWD/azure-storage-fuse/build/blobfuse --version  # blobfuse 1.2.3

echo '[Mount]'
$PWD/azure-storage-fuse/build/blobfuse $MOUNT_DIR --tmp-path=$BLOBFUSETMP --config-file=$AZURE_ACCOUNT_CONFIG_FILE -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG
```
After this I've got nothing in the output.

**Comment by gitanoqevaporelmundoentero** [comment]
> @anki-code I've built blobfuse on Ubuntu 20.04 and got no result and no messages.


Be sure to add `-d` parameter, otherwise no log messages will be displayed. I also tried to build in Ubuntu 20.04 and got same problem (no folder was mount).

**Comment by anki-code** [comment]
@gitanoqevaporelmundoentero  Thanks! Error added above.

**Comment by scegg** [comment]
Same problem here with blobfuse 1.1.1 on ubuntu server 20.04.

Btw, where to get the binary of blobfuse 1.2.2? Thanks.

**Comment by vibhansa-msft** [comment]
Latest release has been posted on github few days back but blobfuse is not compatible with Ubuntu 20.04 as of now. We have a potential fix and its in testing phase as of now. Will update on this thread once released/committed to master.

**Comment by NaraVen** [comment]
The source code is updated for Blobfuse to work with Ubuntu 20.04. Please get the latest source code. We will be releasing the public package for 20.04 next week.

**Comment by anki-code** [comment]
It works! Thanks!

**Comment by softwarequalityforce** [comment]
Some upgrade about this?

**Comment by NaraVen** [comment]
appreciate your patience, we will be releasing 20.04 to the Linux package repository next week.

**Comment by softwarequalityforce** [comment]
Thanks, we will be attentive to the new release

**Comment by chrisyeh96** [comment]
@NaraVen : are there any updates on when the 20.04 blobfuse package will be released to the Linux package repository? It still doesn't seem to be available yet
