### ISSUE TITLE
blobfuse need report accurate  error message for failures.

### ISSUE THREAD

**Issue by c1301** [Azure/azure-storage-fuse#397]
### Which version of the blobfuse was used?

1.1.0
### Which OS (please include version) are you using?
Description:    Ubuntu 16.04.6 LTS

### What problem was encountered?
mount failed report error:
Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 400

It need report the real reason instead of error=400

Here is the list for the 400 error:
++++++++++++++++++++++++++++++++++++++++++++++++++++
BlockListTooLong    Bad Request (400)    The block list may not contain more than 50,000 blocks.
CopyAcrossAccountsNotSupported    Bad Request (400)    The copy source account and destination account must be the same.
InvalidBlobOrBlock    Bad Request (400)    The specified blob or block content is invalid.
InvalidBlobTier    Bad Request (400)    The specified blob tier is invalid.
InvalidBlockId    Bad Request (400)    The specified block ID is invalid. The block ID must be Base64-encoded.
InvalidBlockList    Bad Request (400)    The specified block list is invalid.
InvalidOperation    Bad Request (400)    Invalid operation against a blob snapshot.
InvalidVersionForPageBlobOperation    Bad Request (400)    All operations on page blobs require at least version 2009-09-19.
PreviousSnapshotCannotBeNewer    Bad Request (400)    The prevsnapshot query parameter value cannot be newer than snapshot query parameter value.
UnsupportedHeader    Bad Request (400)    One of the headers specified in the request is not supported.
+++++++++++++++++++++++++++++++
### Have you found a mitigation/solution?

NO
### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
the syslog also need to print the real reason for the failure.

**Comment by NaraVen** [comment]
We fixed this in the latest version
