### ISSUE TITLE
Add config option to mount to container subdirectory

### ISSUE THREAD

**Issue by michalzaptk** [Azure/azure-storage-fuse#400]
### Which version of the blobfuse was used?
v1.2.3

### Which OS (please include version) are you using?
OSX 10.15.2

### What problem was encountered?
In certain cases, it would be extremely helpful to be able to scope a mount to a subdirectory within a container, rather than just the entire container.

### Have you found a mitigation/solution?
I didn't know if this is something that's already been considered, or if there's a reason why this isn't an option

**Comment by vibhansa-msft** [comment]
We will not be adding this feature to blobfuse. We are working on next generation of blobfuse and preview release is already posted on github. Blobfuse2 supports mounting a subdirectory from a storage container.

**Comment by hauntsaninja** [comment]
@vibhansa-msft Awesome to hear! Are there any docs for blobfuse2 or expected (non-preview) release date?
