### ISSUE TITLE
Blob permanent mount is not workins

### ISSUE THREAD

**Issue by P9110963** [Azure/azure-storage-fuse#402]
### Which version of the blobfuse was used?
blobfuse 1.0.2

### Which OS (please include version) are you using?
Red Hat Enterprise Linux Server release 7.7 (Maipo)

### What problem was encountered?
Unable to mount blob container into Linux VM by adding below entry in /etc/fstab 

blobfuse /mnsfod-root --tmp-path=/mnt/resource/mnsfod-root --config-file=/root/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

### Have you found a mitigation/solution?
By running the same command manually, able to mount the container in the VM.

### If relevant, please share your mount command.

blobfuse /mnsfod-root --tmp-path=/mnt/resource/mnsfod-root --config-file=/root/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Comment by NaraVen** [comment]
encapsulate the blobfuse commandline above with a delay_connect option. 
I have a script with the commandline and I am calling the script with a delay_connect. It works for me.

**Comment by NaraVen** [comment]
Did this work? Can we close?

**Comment by P9110963** [comment]
No. I have added delay_connect as additional option to the mount entry which doesn't work. Could you share the script which is being used. 

updated Entry:
blobfuse /mnsfod-root --tmp-path=/mnt/resource/mnsfod-root --config-file=/root/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o delay_connect

**Comment by NaraVen** [comment]
blobfuse /home/nara/mntblobfuse fuse delay_connect,defaults,_netdev,--tmp-path=/home/nara/tmppath,--config-file=/home/nara/connection.cfg,--log-level=LOG_DEBUG,allow_other 0 0

this is in Ubuntu16.04 but should be the same for RHEL

**Comment by P9110963** [comment]
Thanks NaraVen. I figured out the issue while trying the options which u gave.  My system doesn't have fuse packages, it only had blobfuse and fuse-libs packages. After installing fuse 2.9.x I am able to successfully mount blob with the below options. 

blobfuse /mnsfod-root fuse defaults,_netdev,--tmp-path=/mnt/resource/mnsfod-root,--config-file=/root/fuse_connection.cfg,--log-level=LOG_DEBUG,allow_other 0 0
