### ISSUE TITLE
Error building blobfuse on RHEL8+

### ISSUE THREAD

**Issue by juyamash** [Azure/azure-storage-fuse#405]
### Which version of the blobfuse was used?
1.1.1

### Which OS (please include version) are you using?
RHEL8+

### What problem was encountered?
manually build will be failed as per as wiki steps.

### Have you found a mitigation/solution?
We should install 'make' package and disable Boost_USE_STATIC_LIBS on CMakeLists.txt. The complete procedure is below.
```
sudo yum install git make cmake fuse-devel libcurl-devel gcc gcc-c++ gnutls-devel libgcrypt-devel libuuid-devel boost-devel fuse -y
git clone https://github.com/Azure/azure-storage-fuse/
cd ./azure-storage-fuse/
sudo sed -i 's/set(Boost_USE_STATIC_LIBS ON)/set(Boost_USE_STATIC_LIBS OFF)/g' ./CMakeLists.txt
./build.sh
```

It seems that there are similar and related isssues.
https://github.com/Azure/azure-storage-fuse/issues/319
https://github.com/Azure/azure-storage-fuse/issues/196

**Comment by NaraVen** [comment]
This issue is fixed. Please download the source code and run build.sh
