### ISSUE TITLE
Unable to mount storage on Data Science Ubuntu 18.04 VM

### ISSUE THREAD

**Issue by SirRacha** [Azure/azure-storage-fuse#419]
### Which version of the blobfuse was used?
1.2.1

### Which OS (please include version) are you using?
Azure DSVM unbunto 18.04

### What problem was encountered?
I have tried everything but I cannot get the final command to mount my blobfuse on a DSVM.  I have even created a new and only get a similar error about it notfinding y config file.  I have created the file and saved it both in Root and Home. 

"Error: No config file found at ."

### Have you found a mitigation/solution?
No

### If relevant, please share your mount command.
sudo blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file= /root/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Comment by NaraVen** [comment]
Is there a config file in /root/ ? Also could you please download the 1.2.3 package for Ubuntu 18.04 and try it out.

**Comment by SirRacha** [comment]
yes there is a config file.  the solution was to blow away my VM (very unfortunate), start a new Ubuntu 18.04 and possibly an errant non-space needed here --tmp-path= /mnt/resource/blobfusetmp

**Comment by myidealab** [comment]
@SirRacha I'm having the same issue. I can list, read, and edit the file, but receive the message: `No config file found at ~/fuse_connection.cfg.`  I am trying to avoid creating a new DSVM, but I may need to.

Reference: [How to mount Blob storage as a file system with blobfuse](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux)

**Comment by vibhansa-msft** [comment]
@myidealab : can you try giving absolute path for config file in mount command.
