### ISSUE TITLE
Build error on base64.cpp: error: ‘runtime_error’ is not a member of ‘std’

### ISSUE THREAD

**Issue by UnoSD** [Azure/azure-storage-fuse#421]
### Which version of the blobfuse was used?

Latest git commit (c07e5028354924344c9d1de1b7e6a93aceb23d32)

### Which OS (please include version) are you using?

Arch Linux

gcc (GCC) 10.1.0

### What problem was encountered?

Compilation error when building from source:

`base64.cpp:100:32: error: ‘runtime_error’ is not a member of ‘std’`

### Have you found a mitigation/solution?

No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

N/A

### If relevant, please share your mount command.

N/A

**Comment by NaraVen** [comment]
This is an include error. exception.h is possibly different in Arch_linux. Can you upgrade to c++ 11?

**Comment by UnoSD** [comment]
Thanks for the reply.

Not sure if this is the right way of doing it, but I added `CXXFLAGS=-g -std=c++11 -Wall -pedantic` to the Makefile and exported the same CXXFLAGS variable and that did not help.

**Comment by UnoSD** [comment]
I "`sed`ed" around and removed runtime_error, leaving it to throw strings instead and fixed a couple of broken `catch` and I was able to compile it. That may work for now, but I would appreciate some guidance on how to fix it properly. I hope there is no control flow using exceptions in code.

**Comment by GuillaumeLeclerc** [comment]
Same issue here. @UnoSD is your patch available somewhere?

**Comment by GuillaumeLeclerc** [comment]
According to https://en.cppreference.com/w/cpp/error/runtime_error, the include should not be `exception.h` but `<stdexcept>` no ?

**Comment by GuillaumeLeclerc** [comment]
That's my diff. It works this way on my machine. I'm not sure how it could even compile with these include missing on other systems:

```
guillaume@glw /t/azure-storage-fuse (master)> git diff                                                                                                             (base) 
diff --git a/azure-storage-cpp-lite/src/base64.cpp b/azure-storage-cpp-lite/src/base64.cpp
index f5bb05b..507d065 100644
--- a/azure-storage-cpp-lite/src/base64.cpp
+++ b/azure-storage-cpp-lite/src/base64.cpp
@@ -1,5 +1,6 @@
 #include <array>
 #include <cstring>
+#include <stdexcept>
 
 #include "base64.h"
 
diff --git a/azure-storage-cpp-lite/src/storage_url.cpp b/azure-storage-cpp-lite/src/storage_url.cpp
index 5f64c02..f2b9a66 100644
--- a/azure-storage-cpp-lite/src/storage_url.cpp
+++ b/azure-storage-cpp-lite/src/storage_url.cpp
@@ -1,4 +1,5 @@
 #include <ctime>
+#include <stdexcept>
 
 #include "storage_url.h"
```

**Comment by UnoSD** [comment]
@GuillaumeLeclerc I do not have a patch, but if you want I can dig all the `sed` from my BASH history if that helps you getting it compiled.

**Comment by GuillaumeLeclerc** [comment]
I got it to work with the patch above, since it's just includes I think it
should preserve the original control flow in case exceptions happen

**Comment by vibhansa-msft** [comment]
Fix is available in version 1.3.3.

**Comment by RAOPT** [comment]
It might be caused by g++ version, and it could be solved by add "#include <stdexcept>" in my vm.

**Comment by RAOPT** [comment]
It might be caused by g++ version, and it could be solved by add `#include <stdexcept>` in my vm.

**Comment by naftalimurgor** [comment]
Hey @RAOPT 
Facing a similar issue: what version of g++ should work for this?
Thanks

**Comment by vibhansa-msft** [comment]
Are you getting this error with Blobfuse2 or legacy C++ code ?

**Comment by naftalimurgor** [comment]
Getting this error with legacy C++ code, not able to resolve it yet.

**Comment by vibhansa-msft** [comment]
You can migrate to blobfuse2 instead which is GoLang based. We are encouraging all our customers to migrate, as legacy c++ code will not be supported for long.
