### ISSUE TITLE
Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 403

### ISSUE THREAD

**Issue by siddhant777** [Azure/azure-storage-fuse#424]
### Which version of the blobfuse was used?
blobfuse 1.0.2

### Which OS (please include version) are you using?
Centos 7.5

### What problem was encountered?
Not able to access storage containers. No firewall restriction at storage level

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

### If relevant, please share your mount command.
sudo blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=/path/to/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Comment by NaraVen** [comment]
could you paste your config file. Please Hash out the storage key though.

**Comment by siddhant777** [comment]
accountName ppastorageacc
accountKey ###############################
containerName ppanextgenfs


Above are the contents of config file

**Comment by siddhant777** [comment]
The credentials are working perfectly fine when tried connecting by other means. Same credentials are not working when tried through mount command

**Comment by NaraVen** [comment]
1.0.2 is an old version. Could you please compile from the source code and upgrade to the latest version which is 1.2.3? We will be publishing to CentOS in a few days.

**Comment by siddhant777** [comment]
Reason behind this issue was network and access related. It is resolved now.
Marking it as closed
