### ISSUE TITLE
Is Blobfuse covered by Azure Support?

### ISSUE THREAD

**Issue by liambarnett** [Azure/azure-storage-fuse#425]
Apologies if this has already been answered -  I cannot find this documented anywhere and I've not been able to get a clear response from Azure Support via Twitter. 

If I deploy Blobfuse within my EA subscriptions, will I receive support from Azure Support for any related issues assuming Blobfuse is being used within the defined and documented limits?

Thanks in advance

**Comment by NaraVen** [comment]
There is a support team for Blobfuse but being an open source project, it does not fall under Azure support from Azure portal.
