### ISSUE TITLE
Release for Ubuntu 20.04?

### ISSUE THREAD

**Issue by scegg** [Azure/azure-storage-fuse#427]
### Which version of the blobfuse was used?
N/A

### Which OS (please include version) are you using?
Ubuntu Server 20.04 x64

### What problem was encountered?
Not published.

Is there any plan to publish a binary or push the package for Ubuntu 20.04?

**Comment by NaraVen** [comment]
Yes it will be published soon. Until then you can download the source code and build it yourself.

**Comment by scegg** [comment]
Any update?

**Comment by NaraVen** [comment]
In a week or 2.

**Comment by scegg** [comment]
Any update?

**Comment by chrisyeh96** [comment]
Any update? On June 7, 2020, @NaraVen said in #395 that the blobfuse package for 20.04 would be released as a public package "next week." It's been over 2 months and it's still "in a week or 2"? Some clarity is much needed here.

**Comment by NaraVen** [comment]
released!
