### ISSUE TITLE
Unable to mount after restart. Error:  temp directory '/mnt/resource/profiletmp' is not empty.

### ISSUE THREAD

**Issue by acollard** [Azure/azure-storage-fuse#432]
### Which version of the blobfuse was used?
blobfuse 1.2.3

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
The mount succeeds the first time. Upon setup it creates a folder called "root". Once the machine is restarted the mounting fails due to the existence of the "root" folder. I don't think blobfuse should create a situation where it blocks itself from re-mounting.

Here are the contents of the temp folder after restart:
/mnt/resource/profiletmp$ sudo ls -R
.:
root

./root:

### Have you found a mitigation/solution?
I haven't tried it yet, but I plan on just removing any folders/files in the temp folder on start up before blobfuse runs.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
blobfuse: Unable to start blobfuse. temp directory '/mnt/resource/profiletmp'is not empty.

### If relevant, please share your mount command.
blobfuse /path/to/mount/location --tmp-path=/mnt/resource/profiletmp --config-file=/var/fuse/profile_connection.cfg --file-cache-timeout-in-seconds=600 -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o nonempty -o allow_other

**Comment by vibhansa-msft** [comment]
Hi @acollard ,

With 1.2.3 we have added a check that the mount and cache (temp) directory shall be empty when blobfuse is mounted. As you have 'root' folder inside the temp path its failing. Just clear it out and it will work. We are also thinking of making these checks optional in future release. Till then you need to always clear these directories.

**Comment by acollard** [comment]
@vibhansa-msft I understand why it is blocking, my concern was that I don't think I am the one creating the "root" folder. I assumed blobfuse is creating it.

If my assumption is correct then should blobfuse be leaving this behind? Won't this add a hidden requirement in that everyone will need to clear their temp folder because blobfuse will always have leftover files/folders.

**Comment by vibhansa-msft** [comment]
As you suspect, 'root' folder is indeed created by blobfuse. Re-opening the issue to investigate why its left behind. And yes if that's the case right now it needs to be cleared manually.

**Comment by vibhansa-msft** [comment]
How do you unmount the container ? If unmounted gracefully it will clear the 'root' folder as well. Kindly collect syslogs during the unmount operatation.

**Comment by acollard** [comment]
I don't unmount the container. We keep it mounted until the VM is restarted.

Should we be unmounting on shutdown?

**Comment by kyauwong** [comment]
I arrived here searching for a solution to the same bug. It seems that the 'root' directory has the directory structure of the mounted file system (without the files). After removing the directory (I needed sudo and I disconnected from the internet just in case), everything is working fine (mounting and unmounting gracefully).
I hope this helps.

**Comment by vibhansa-msft** [comment]
@acollard - you can try un-mounting manually and verify that the directory structure including 'root' is getting cleared. If not there is a bug we need to fix. If this works then un-mounting gracefully can be considered before the shutdown. I have to investigate VM shutdown triggers blobfuse un-mount sequence or not. Also there are cases where user does not want to clear the directory structure so in upcoming releases we are planning to make this check optional.

**Comment by vibhansa-msft** [comment]
By default blobfuse will allow to mount with non-empty temp directories. However if user wishes to put a strict check for non-empty directory, provide '--empty-dir-check' command line option while mounting.

**Comment by vibhansa-msft** [comment]
Fixed in 1.3.1
