### ISSUE TITLE
Mount failed, an error occurred

### ISSUE THREAD

**Issue by screampig** [Azure/azure-storage-fuse#434]
### Which OS (please include version) are you using?
CentOS6.5

### What problem was encountered?
blobfuse: relocation error: blobfuse: symbol gnutls_hmac_fast, version GNUTLS_2_10 not defined in file libgnutls.so.26 with link time reference

### Have you found a mitigation/solution?
No

### If relevant, please share your mount command.
blobfuse /root/mycontainer --tmp-path=/mnt/resource/blobfusetmp --config-file=/lh_data/soft/fuse_connection.cfg

**Comment by vibhansa-msft** [comment]
This is due to a missing dependencies on the system. Kindly run below command and then try mount again.

sudo yum install git cmake fuse-devel libcurl-devel gcc gcc-c++ gnutls-devel libgcrypt-devel libuuid-devel fuse -y

**Comment by screampig** [comment]
> 这是由于缺少对系统的依赖关系。请运行以下命令，然后再次尝试安装。
> 
> sudo yum install git cmake fuse-devel libcurl-devel gcc gcc-c ++ gnutls-devel libgcrypt-devel libuuid-devel fuse -y

It worked, thank you very much
