### ISSUE TITLE
Single file size limit

### ISSUE THREAD

**Issue by blam810** [Azure/azure-storage-fuse#435]
### Which version of the blobfuse was used?
Latest on Ubuntu 18

### Which OS (please include version) are you using?
Ubuntu 18

### What problem was encountered?
What is the max single file limit if any?
I'm trying to copy a single 15TB file to Azure block blob using BlobFuse FS.
Will this work?

**Comment by blam810** [comment]
Hi Rishab,

Do you know if there is a file limit when using BlobFuse?
I have a 15TB single file which I would like to copy to Azure block blob but hitting brick wall after brick wall. Hopefully Blobfuse can be a solution for me.
If you have ever work with this size of file on Blobfuse please let me know.

Thanks for taking time to look into this.

**Comment by vibhansa-msft** [comment]
In blobfuse file size limits are governed by the amount of cache you have. If you have sufficient space in your cache directory (~15TB) then it shall be fine.

**Comment by blam810** [comment]
Hi Vikas,

Thanks for your response.
Since I only need to write to the file system, is there any way I can bypass the cache and not use one?

Thanks

**Comment by vibhansa-msft** [comment]
As of now there is now way around the caching part in blobfuse. I suggest you to try AzCopy tool, which allows you to copy data to and from your storage account (link provided below), instead of mounting the container.

https://github.com/Azure/azure-storage-azcopy

**Comment by blam810** [comment]
Hi Vikas,

I have already tried Azcopy and there is a block limit there and it cannot accept a single file larger than 4.5 TB which does not work for me. So you are saying if I can get a temp space that can hold 15TB Blobfuse should be able to copy the one 15TB file to a block blob on Azure?

**Comment by vibhansa-msft** [comment]
We have not tried a test-case with such a size but it shall work. However even if it uploads the file, how you are going to consume it as download will also have the same issues you are facing. Not sure about the use-case but splitting the file up is an option ?

**Comment by NaraVen** [comment]
Current:
https://azure.microsoft.com/en-gb/blog/general-availability-larger-block-blobs-in-azure-storage/
So 100MB max per block * 50,000 max allowed blocks = **4.77 TB** for a single block blob.
Future:
 For 15TB, you may want to try Jumbo blob which is a preview/upcoming feature that allows upto 197 TB in a single block blob.

**Comment by amnguye** [comment]
Currently cpplite does not support the 2019-12-12 version and blobfuse is dependent on cpplite.

If you're looking to try out the 2019-12-12 api version with the larger supported blobs, please look to using one of our SDKs which supports this.

e.g.
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet (supported in Azure.Storage.Blobs 12.5.0-preview.5)
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java (supported in azure-storage-blobs 12.8.0-beta.1)

**Comment by blam810** [comment]
> 
> 
> Current:
> https://azure.microsoft.com/en-gb/blog/general-availability-larger-block-blobs-in-azure-storage/
> So 100MB max per block * 50,000 max allowed blocks = **4.77 TB** for a single block blob.
> Future:
> For 15TB, you may want to try Jumbo blob which is a preview/upcoming feature that allows upto 197 TB in a single block blob.

Hi Nara,
Thanks for the update
Do you know how we can access the preview feature of jumbo blob?

Do you know if BlobFuse can support the single 15TB if I have the right cache size?

Thanks

**Comment by blam810** [comment]
> 
> 
> Currently cpplite does not support the 2019-12-12 version and blobfuse is dependent on cpplite.
> 
> If you're looking to try out the 2019-12-12 api version with the larger supported blobs, please look to using one of our SDKs which supports this.
> 
> e.g.
> https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet (supported in Azure.Storage.Blobs 12.5.0-preview.5)
> https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java (supported in azure-storage-blobs 12.8.0-beta.1)

Hi Amanda,

Thanks for the contribution.
I'm planning to use an Ubuntu box to complete this task. 
Sorry I'm not too familiar with cpplite etc as this is the first time I'm attempting to use Blobfuse to overcome the 15TB challenge the I have.
Is ccplite required on a linux box as well?

Thanks

**Comment by amnguye** [comment]
You can access the feature of jumbo blob when you call the service api version 2019-12-12.

Blobfuse cannot upload more a blob size of more than 4.75TB due to the service version blobfuse/cpplite currently depend on which is 2018-11-09. 
https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-block-blobs

I recommend you use one of our SDKs to do so. You can probably write up something quick in .NET, Java or Python to upload your blob and you can run (code or script) it in your ubuntu box in order to complete this task. Since this is a recently available feature, I recommend you install the latest version of the SDK (whichever you choose to use).
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet#upload-blobs-to-a-container
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java#upload-blobs-to-a-container
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python#upload-blobs-to-a-container

Also just for clarification, cpplite is also an SDK.

@rishabpoh Do you have any other recommendations of other tools that support jumbo blobs (aka the latest service version)?

**Comment by blam810** [comment]
> 
> 
> You can access the feature of jumbo blob when you call the service api version 2019-12-12.
> 
> Blobfuse cannot upload a blob that has the size of more than 4.75TB due to the service version blobfuse/cpplite currently depend on which is 2018-11-09.
> https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-block-blobs
> 
> I recommend you use one of our SDKs to do so. You can probably write up something quick in .NET, Java or Python to upload your blob and you can run (code or script) it in your ubuntu box in order to complete this task. Since this is a recently available feature, I recommend you install the latest version of the SDK (whichever you choose to use).
> https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet#upload-blobs-to-a-container
> https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java#upload-blobs-to-a-container
> https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python#upload-blobs-to-a-container
> 
> Also just for clarification, cpplite is also an SDK.
> 
> @rishabpoh Do you have any other recommendations of other tools that support jumbo blobs (aka the latest service version)?

Hi Amanda,

Thanks for the update.
Unfortunately I don't use python or Java or .Net that much. By any chance, Would you have a sample python script handy to share to test out the jumbo blob?

THanks
Brian

**Comment by NaraVen** [comment]
Hi Brian,
     This is our test script to test Jumbo blobs. https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/tests/test_largest_block_blob.py. It has examples for both upload and download and it specifies what API to use.

For reference use only the ones marked @pytest.mark.live_test_only, you can ignore the other test cases. There are helper methods for put and stream that you can copy and refer to the live_test and write your own upload, download and list., you can also copy the classes LargeStream, Payloaddroppingpolicy as is.
