### ISSUE TITLE
 Unable to start blobfuse.  Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 400

### ISSUE THREAD

**Issue by manalam1** [Azure/azure-storage-fuse#437]
### Which version of the blobfuse was used?
1.1.1-1
### Which OS (please include version) are you using?
7.7 (Maipo)
### What problem was encountered?
Unable to start and mount blobfuse
### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Jul 14 09:28:30 $HOSTNAME blobfuse[19843]: Unable to start blobfuse.  Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 400

The account credentials were verified successfully using storage explorer.

### If relevant, please share your mount command.
/bin/blobfuse /ora_blob_bkp --tmp-path=/mnt/resource/blobfusetmp  --config-file=/local/orabin/product/db_1/11.2.0.4/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --use-https=true -o uid=199 -o gid=342 -o allow_other --log-level=LOG_DEBUG

# more /local/orabin/product/db_1/11.2.0.4/fuse_connection.cfg
accountName databasename
accountKey ****==
containerName Container01

**Comment by vibhansa-msft** [comment]
When you are using accountKey for authorization you need to add 'authType Key' in config file. Kindly add the missing config and retry.

**Comment by manalam1** [comment]
Updated config file as follows:

accountName databasename
authType Key
accountKey ****==
containerName Container01

Same error:
Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 400

Syslog error:
Jul 14 12:08:07 $HOSTNAME  blobfuse[14071]: Unable to start blobfuse.  Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 400

**Comment by vibhansa-msft** [comment]
Can you try with 1.2.3 version. Also while making a config file make sure you have only one space between key and value. In older versions tab or multi-space were not supported and parsing of the config file will fail.

**Comment by manalam1** [comment]
Can I pull the 1.2.3 version from this URL https://packages.microsoft.com/config/rhel/7.4/packages-microsoft-prod.rpm or do I need to download the source and manually compile ?

**Comment by vibhansa-msft** [comment]
The link that you have pointed is not valid 1.2.3 release, kindly clone the code and build it. There is a 'build.sh' script in the workspace directory to build it.

**Comment by manalam1** [comment]
Is the RPM package for version 1.2.3 for Redhat 7 available for download ?

**Comment by SeshagiriSriram** [comment]
same here. I am on 1.2.4 and here's my config file (confidential data  hashed out) 
accountName     ######                                                                                                    
authType           ######                                                                                                                    
accountKey        ######  
containerName   ######                                                                                                                  ~

**Comment by vibhansa-msft** [comment]
@SeshagiriSriram kindly enable LOG_DEBUG for blobfuse and share the logs (logs will contain your account name and container name, you can mask them out before sharing)

**Comment by SeshagiriSriram** [comment]
**from log file**
_Jul 21 04:46:00 iotedge blobfuse[15168]: Setting logging level to : LOG_DEBUG
Jul 21 04:46:01 iotedge blobfuse[15168]: Tue Jul 21 04:46:01 2020 ==> REQUEST/RESPONSE#012#011GET https://localblobstorage.blob.core.windows.net/aivi?comp=list&delimiter=/&include=metadata&maxresults=1&restype=container#012#011User-Agent: [Azure-Storage-Fuse/1.2.4]#012#011x-ms-date: [Tue, 21 Jul 2020 04:46:00 GMT]#012#011x-ms-version: [2018-11-09]#012#011Authorization: [REDACTED]#012#011Transfer-Encoding: []#012#011--------------------------------------------------------------------------------#012#011RESPONSE Status: 403#012#011Content-Length: [220]#012#011Content-Type: [application/xml]#012#011Date: [Tue, 21 Jul 2020 04:46:01 GMT]#012#011Server: [Microsoft-HTTPAPI/2.0]#012#011x-ms-error-code: [AccountIsDisabled]#012#011x-ms-request-id: [da412d00-201e-0049-1a19-5f9283000000]
Jul 21 04:46:01 iotedge blobfuse[15168]: Result error message: The specified account is disabled.#012RequestId:da412d00-201e-0049-1a19-5f9283000000#012Time:2020-07-21T04:46:02.6238681Z
Jul 21 04:46:01 iotedge blobfuse[15168]: Unable to start blobfuse.  Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key/sas token/OAuth access token and container name. errno = 403_
**from docker ps -a**
_ad33bc0a7fcc        mcr.microsoft.com/azure-blob-storage:latest   "./docker-entrypoint…"    10 hours ago        Up 10 hours         0.0.0.0:11002->11002/tcp_

**Comment by SeshagiriSriram** [comment]
And from IoT Hub, 
![image](https://user-images.githubusercontent.com/3693855/88014457-9b2b3d80-cb3c-11ea-8518-cca1d982e328.png)
![image](https://user-images.githubusercontent.com/3693855/88014521-c0b84700-cb3c-11ea-9b64-c9b0af630845.png)

**Comment by vibhansa-msft** [comment]
As per below logs we are getting account disabled error from the server and hence unable to mount.

 [Microsoft-HTTPAPI/2.0]#12#011x-ms-error-code: [**AccountIsDisabled**]#12#
Jul 21 04:46:01 iotedge blobfuse[15168]: Result error message: **The specified account is disabled**.#012RequestId:da412d00-201e-0049-1a19-5f9283000000#012Time:2020-07-21T04:46:02.6238681Z

**Comment by SeshagiriSriram** [comment]
I am following instructions from here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-blob on an IoT edge device and I quote

_1. _Replace <your storage account name> with a name that you can remember. Account names should be 3 to 24 characters long, with lowercase letters and numbers. No spaces.
2. Replace <your storage account key> with a 64-byte base64 key. You can generate a key with tools like GeneratePlus. You'll use these credentials to access the blob storage from other modules.__

There is nothing that specifies that account has to be enabled. Are we missing something here?

**Comment by SeshagiriSriram** [comment]
Should the storage account be created on Hub also?

**Comment by vibhansa-msft** [comment]
From Azure portal login to you account and check your subscription status. If its not active you can follow below link
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/subscription-disabled

**Comment by SeshagiriSriram** [comment]
I have a valid, active subscription.I am owner of a resource group and can create resources under them.I can create storage accounts on the cloud, use the storage explorer and no issue. The issue only stems with access to local Blob Storage on an IoT edge device.

**Comment by NaraVen** [comment]
@SeshagiriSriram, is your blob url https://localblobstorage.blob.core.windows.net? 
Just want to confirm your account name is 'localblobstorage' and that you are using public cloud and sovereign cloud.

Also, could you please move the accountKey in the config file above the authType and try again after the above 2 points are confirmed. ( We had a bug in one of the versions where ordering mattered in the config file. We fixed it recently in 1.3.1-beta

**Comment by NaraVen** [comment]
@manalam1 ,Could you please share your storage xplorer connection string? 
It should be something like below
DefaultEndpointsProtocol=http;BlobEndpoint=http://<host device name>:11002/<your local account name>;AccountName=<your local account name>;AccountKey=<your local account key>;

Could you also add "blobEndPoint http://<host device name>:11002"  to the config file and move the authType Key below the accountName in the config file and try again.

**Comment by SeshagiriSriram** [comment]
> is your blob url https://localblobstorage.blob.core.windows.net from the edge device?

Yes

> Also confirm that you are using public cloud and not sovereign cloud.

not sure what this means. My IOT EDGE device is local and does not have a public IP  but I can piing to same. Does the Edge have to be on public cloud (with public IP)? If yes, I will try to hunt around for a machine I can use publicly. Any firewall settings that I need to be aware of?

> If` the above 2 points are verified then you likely need a "blobEndPoint http://:11002"

See above.

> Also, could you please move the accountKey in the config file above the authType and try again after the above 3 points are confirmed. ( We had a bug in one of the versions where ordering mattered in the config file). We fixed it recently in 1.3.1-beta

Ok. will try to get it later, today.

**Comment by NaraVen** [comment]
Let me clarify public cloud= (regular cloud or US cloud mainly, non government). I think that's what your case is
The issue appears to be in your config file.
you config file should look like this.
accountName <the account name you specified in the json file>
accountKey <the generated account key you specified in the json file>
blobEndpoint http://azureblobstorageoniotedge:11002
authType Key
containerName <target container name in your storage account>

**Comment by vibhansa-msft** [comment]
@SeshagiriSriram : Did steps shared earlier in this post help in resolving the issue ?

**Comment by manalam1** [comment]
I updated my config file to below, but it did not work.  

accountName databasename
AccountKey ****==
blobEndpoint http://rsgethosoracledatabase.blob.core.windows.net:11002
authType Key
containerName Container01

**Comment by NaraVen** [comment]
AccountKey should be accountKey.
The blob endpoint should be the "Iot Edge Custom module name" not the actual storage endpoint ,
also make sure the accountName is the  "the account name you specified in the json file" and not your actual storage account name
and the accountKey is the "the generated account key you specified in the json file" and not your actual storage key.

**Comment by SeshagiriSriram** [comment]
This can be closed The key was : The accountKey should be the generated Account key"

**Comment by vibhansa-msft** [comment]
Thanks for the confirmation.
