### ISSUE TITLE
--file-cache-timeout-in-seconds isn't honored when modifications are done by another process

### ISSUE THREAD

**Issue by francky-powerfactors** [Azure/azure-storage-fuse#442]
### Which version of the blobfuse was used?
1.2.3 but I'm not 100% sure

### Which OS (please include version) are you using?
Alpine Linux v3.12

### What problem was encountered?
I mounted a file system with the `--file-cache-timeout-in-seconds=10` option in a process that is being asked to read a file. I have another process on another machine that writes to that "same" file (same blob) that also has the mount option `--file-cache-timeout-in-seconds=10` set.

The writes to the blob get flushed every 10 seconds like they should but the reads are pretty random. I put the write time in the blob's content expecting my reads to show an updated write time every 10 seconds. But what I find is that some reads can show the same write time 1.5 (or more) minutes after the previous read.

### Have you found a mitigation/solution?
Not yet.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No.

### If relevant, please share your mount command.
I'm using blobfuse through Kubernetes, using the https://github.com/kubernetes-sigs/blobfuse-csi-driver project. So I'm not directly issuing the command myself.

But this looked like a blobfuse issue. This is why I'm reporting it here.

cc @andyzhangx

**Comment by NaraVen** [comment]
Did you verify if your changes were committed to blob:? How large are these files?

**Comment by francky-powerfactors** [comment]
Yes,

I can see the modified dates being updated in the blob storage UI. These are, at a maximum, 2KB files.

The 'writer' is writing every 10 seconds (as per the configuration file) but it looks like the reader, once it has a cached version of the file, isn't polling for changes every 10 seconds.

**Comment by vibhansa-msft** [comment]
This is fixed in version 1.3.2. You can take the latest code base and try out. Re-open if the issue persists.
