### ISSUE TITLE
Unable to mount via Systemd unit

### ISSUE THREAD

**Issue by tummop** [Azure/azure-storage-fuse#447]
### Which version of the blobfuse was used?

blobfuse-1.1.1-1.el7.x86_64

### Which OS (please include version) are you using?

CentOS Linux release 7.6.1810 (Core)

### What problem was encountered?

Mounting via shell script works fine. However, running it from a systemd unit file returns:

```
blobfuse.sh[26656]: Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 403
systemd[1]: blobfuse.service: control process exited, code=exited status=1
systemd[1]: Failed to start blobfuse.service.
```

The unit file:

```
[Unit]
Description=A virtual file system adapter for Azure Blob storage
After=network.target

[Service]
Type=forking
ExecStart=/usr/local/bin/blobfuse.sh
ExecStop=/usr/bin/fusermount -u ${BlobMountingPoint}

[Install]
WantedBy=multi-user.target
```

### Have you found a mitigation/solution?

No.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

No.

### If relevant, please share your mount command.

Content of `blobfuse.sh` shell script:

```
#!/bin/sh
BlobConfigFile=/root/fuse_connection.cfg
BlobMountingPoint=/mnt/blob
BlobTmp=/mnt/blobtmp
BlobUseHttps=true
BlobFileCacheTimeOutInSeconds=120
BlobLogLevel=LOG_DEBUG
BlobUseAttrCache=false
attr_timeout=240
entry_timeout=240
negative_timeout=120
/usr/bin/blobfuse ${BlobMountingPoint} --tmp-path=${BlobTmp} --config-file=${BlobConfigFile} --use-https=${BlobUseHttps} --file-cache-timeout-in-seconds=${BlobFileCacheTimeOutInSeconds} --log-level=${BlobLogLevel} --use-attr-cache=${BlobUseAttrCache} -o attr_timeout=${attr_timeout} -o entry_timeout=${entry_timeout} -o negative_timeout=${negative_timeout} -o allow_other
```

Content of `fuse_connection.cfg` config file:

```
accountName xxx
sasToken si=xxx&spr=https&sig=xxx=xxxx-xx-xx&sr=c
containerName xxx
```

**Comment by NaraVen** [comment]
Please refer to from https://github.com/Azure/azure-storage-fuse/tree/master/systemd/with-config-file . I verified it works on Ubuntu and RHEL 8.1 
you need to change the [Unit] to force after the Network starts and also change the [Service] Type to "simple" ( forking fails)
