### ISSUE TITLE
Unable to create files with & in the name.

### ISSUE THREAD

**Issue by rayzorben** [Azure/azure-storage-fuse#449]
### Which version of the blobfuse was used?
1.2.4

### Which OS (please include version) are you using?
Ubuntu 18.04 LTS

### What problem was encountered?
~~blobfuse does not support filenames over 100 characters. I have a file with 112 characters and when trying to create it throw a 'permission denied' error. Yet Azure Blob Storage seems to support well over that limit. This filename has 170 characters.~~

blobfuse does not support filenames with & in them (and maybe other characters). NTFS, EXT4 and Azure Blob Storage all seem to support this in the filename.

Error:
```bash
/sync/data/Books/Title$ echo foo>>'Higher Call_ An Incredible True Story of Combat and Chivalry
in the War-Torn Skies of World War II, A - Adam Makos & Larry Alexander.epub'
-bash: Higher Call_ An Incredible True Story of Combat and Chivalry in the War-Torn Skies of World War II, A - Adam Makos & Larry Alexander.epub: Permission denied
```

Works fine in /tmp so not a linux issue:
```bash
/tmp/data/Books/Title/Deeper$ echo foo>>'Higher Call_ An Incredible True Story of Combat and Chivalry in the War-Torn Skies of World War II, A - Adam Makos & Larry Alexander.epub'
```

I can create it fine in Azure Portal:

![image](https://user-images.githubusercontent.com/7737834/89661953-384ddc00-d888-11ea-829d-7438dba5be35.png)

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Not Relevant

### If relevant, please share your mount command.
Not Relevant but let me know and I can share.

**Comment by vibhansa-msft** [comment]
Can you remove '&' from the file name (Adam Makos & Larry Alexander.epub) and retry. It is not a file-name length issue.

**Comment by rayzorben** [comment]
Ah, my bad. I have a lot files named that way and it seems to be supported by both NTFS and ext4 and azure blob storage.

**Comment by vibhansa-msft** [comment]
Yes it is supported both by linux and Azure Storage. But blobfuse is not encoding the '&' in file name as of now hence the failure. Will fix it in next release.

**Comment by vibhansa-msft** [comment]
Bug fix checked-in, will be part of next release.
