### ISSUE TITLE
[FEATURE REQUEST] Add support to Azure Container Instances

### ISSUE THREAD

**Issue by rayzorben** [Azure/azure-storage-fuse#450]
I am sure the azure-storage-fuse project is separated to some degree from Azure Container Instances. 

Seeing these 2 combined would be very powerful for persistant storage in ACI.

**Comment by vibhansa-msft** [comment]
To mount a container that has blobfuse running inside one needs to add these three options to "docker run" command:
        --cap-add=SYS_ADMIN \
        --device=/dev/fuse \
        --security-opt apparmor:unconfined \

We are able to build and publish blobfuse2 image to azure container registry, but ACI does not support adding these capabilities to container on launch. This means you cannot add /dev/fuse to your container and have admin privileges to it. This blocks us from running blobfuse2 inside a ACI.
A container running on host will work fine once these options are added.
