### ISSUE TITLE
Blobfuse command hangs unless run as sudo (even when user is root)

### ISSUE THREAD

**Issue by sp4rry** [Azure/azure-storage-fuse#451]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
RHEL 6.8

### What problem was encountered?
I have sudo to root and running the command:
 blobfuse /archive-tempdocs --tmp-path=/mnt/resource/blobfusetmp/ --config-file=/etc/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

Eventually returns with:
Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 404

if i run the same (again as root) but prefix it with sudo it successfully mounts. 

a knock on affect seems to be that putting then mount.sh command in /etc/fstab the it doesn't mount on reboot.

the config file and tmp-path are owned by root

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

**Comment by NaraVen** [comment]
Could you please try the latest version, 1.3.2 of blobfuse? You have to build from the source code - git clone https://github.com/Azure/azure-storage-fuse. Then cd to azure-storage-fuse and run ./build.sh the blobfuse binary will be created in azure-storage-fuse
you can use the mount command with the path above and mount it.

**Comment by sp4rry** [comment]
Apologies Nara.  This went to my personal email which I don’t check that often.  Unfortunately we are running RHEL 6 still and the only version of cmake is 2.8 but the latest of azure-storage-fuse requires 3.6.

I find it strange that it works on an identical server just installing from the yum repo.

Regards
Steve

**Comment by vibhansa-msft** [comment]
If you are still facing issue with RHEL6, below are the steps to manually upgrade cmake to a version which blobfuse needs.
Kindly pull the latest code to get blobfuse version 1.3.6.
                
                sudo yum remove cmake -y
		wget https://cmake.org/files/v3.6/cmake-3.6.2.tar.gz
		tar -zxvf cmake-3.6.2.tar.gz
		cd cmake-3.6.2
		sudo ./bootstrap --prefix=/usr/local
		sudo make
		sudo make install
		vi ~/.bash_profile
			PATH=/usr/local/bin:$PATH:$HOME/bin
		cmake --version
			cmake version 3.6.2

**Comment by vibhansa-msft** [comment]
Closing as we did not receive any further inputs on this thread. Feel free to reopen if issue persists.
