### ISSUE TITLE
Unable to set Permissions

### ISSUE THREAD

**Issue by abamure** [Azure/azure-storage-fuse#453]
### Which version of the blobfuse was used?
1.1.1

### Which OS (please include version) are you using?
Oracle 7.8

### What problem was encountered?
1. I am unable to change ownership and set permissions as both chmod and chown is having no effect.

2. After persisting the blobfuse, the blobfusetmp directory created for --tmp-path gets deleted after system reboots (being ephemeral drive). Do I have to always recreate the dir?  

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

### If relevant, please share your mount command.
blobfuse "/var/orabackup/c001" --tmp-path=/mnt/blobfusetmp  --config-file=/path/to/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

****

**Comment by vibhansa-msft** [comment]
1. chmod and chown are not supported by blobfuse. Soon we will release version 1.3.1 where chmod will be supported for ADLS accounts. chown will still not work.

2. Blobfuse does not delete temp directory created by user. If it gets deleted by any other means then you need to create it again before you mount blobfuse again. One quick solution to this might be writing a small shell script that create the temp directory first and then mounts blobfuse.

**Comment by abamure** [comment]
Thank you for the swift response.
