### ISSUE TITLE
Blobfuse take to much memory

### ISSUE THREAD

**Issue by potapuff** [Azure/azure-storage-fuse#454]
### Which version of the blobfuse was used?
1.3.1-beta

### Which OS (please include version) are you using?
Debian GNU/Linux 9.13 (stretch)

### What problem was encountered?
Blobfuse take to much memory

user@server:~$ ps axu | grep blobfuse
user    13787  1.3 19.3 2126332 1184620 ?     Ssl  Aug12 161:01 blobfuse /path/nodes --tmp-path=/mnt/resource/nodes -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=240 --config-file=/other_path/nodes.cfg --log-level=LOG_WARNING --file-cache-timeout-in-seconds=3600

Total storage size 292.59 MiB, append only via blobfuse. ~500 files

Temp folder is 2 GiB file-based block devise.

What is a best way reduce blobfuse memory usage and/or fastest and safeties way to restart it?

**Comment by vibhansa-msft** [comment]
@potapuff can you share more details on this. Memory consumption is higher in terms of memory usage of the process or the temp folder you see disk usage is higher. Temp folder is where the files are cached by blofuse. Any file that you open using blobfuse will be cached for 3600 seconds (--file-cache-timeout-in-seconds). So unless this time elapse they will remain in cache and meanwhile you can see temp directory disk usage is high. 
For your query on restart, this being a mount, only way to restart is unmount and re-mount the container.

**Comment by NaraVen** [comment]
19.3 % memory usage is a high for a 300MiB storage size.  If you don't need to cache files for 1 hour I recommend lowering the --file-cache-timeout-in-seconds. How much available memory does your machine have? I suspect cache eviction due to lack of memory is happening continuously and files are not actually cached for an hour.

**Comment by potapuff** [comment]
@NaraVen problem still present, what additional information I can provide?
- Cache - block-devise on disk, not in memory. Today I'll try new blobfuse with --cache_size_mb option. 
- Repository today: 
![size](https://user-images.githubusercontent.com/40972/91841109-75747680-ec5a-11ea-84e1-939c9f886baf.PNG)
Structure:
- first level -178 folders with names like "1234"
- second level - files with uuid-like names, typical 10-30 per folder 
Before reboot:
![1000](https://user-images.githubusercontent.com/40972/91840874-10208580-ec5a-11ea-8518-0c8ce2f39d9b.PNG)
After reboot:
![1110](https://user-images.githubusercontent.com/40972/91840887-16aefd00-ec5a-11ea-8aca-3a0d8224010b.PNG)
1 hour after reboot
![1210](https://user-images.githubusercontent.com/40972/91840910-21699200-ec5a-11ea-9120-a6d9e726ba26.PNG)

**Comment by NaraVen** [comment]
What value have you set for --file-cache-timeout-in-seconds?

**Comment by potapuff** [comment]
Current value for --file-cache-timeout-in-seconds=600 . Does cached files placed only  in temp directory or both in temp and in memory?

Today stats for mee: blobfuse  grows from 8% of memory  at 00:02 to 21% at 21:00.
![00_00](https://user-images.githubusercontent.com/40972/92020248-87d8d800-ed60-11ea-9d2a-e38cc85f637f.PNG)
![21_00](https://user-images.githubusercontent.com/40972/92020240-85767e00-ed60-11ea-87e0-14a1892ce51a.PNG)

**Comment by NaraVen** [comment]
cached files are placed only on the tmp directory. there is queue maintaining the list of files cached and a processor verifying if the files are ready for cache eviction so memory consumption is higher if file--cache-timeout-in-minutes is high because more files are cached.

**Comment by NaraVen** [comment]
Hi @potapuff,  Blobfuse does caching, so, memory usage will be anywhere from 2 GB to 8 GB. Of course, 8 GB for petabytes of data and frequent upload/ downloads. So, your memory usage above aligns with what we expect it to be. At this time we are not working on optimizations to lower memory below this.  Would it possible for you to upgrade your VM?

**Comment by potapuff** [comment]
Ok., VM  can be upgraded, But in my project I use access to 4 containers inside one project-related storage. So,  4*8 -> up to 32Gb.

**Comment by NaraVen** [comment]
not all processes take 8 gb. if your data is small you can run them all with 12 - 15  GB. With all of caching features we cannot trim memory usage anymore so I am closing this issue for now.
