### ISSUE TITLE
Blobfuse not loading from cache?

### ISSUE THREAD

**Issue by wmpauli** [Azure/azure-storage-fuse#456]
### Which version of the blobfuse was used?
1.2.1

### Which OS (please include version) are you using?
ubuntu bionic

### What problem was encountered?
It seems like blobfuse doesn't ever use cached files. I notice that the files are cached, but the time stamps are from when the files were created in blob storage, rather than when they were cached. 

based on this issue (https://github.com/Azure/azure-storage-fuse/issues/193), my understanding is that blobfuse decides based on 

    Blobfuse will check the cache folder. Find the file and look at its timestamp and compare whether the following is true ( timeout < current_time - file_timestamp)
    If true, it will use the cached file
    If not true, it will download the blob from Blob storage

That would mean that the timestamps would have to be of when the file was cached, not when they are created. Unless I desire a different kind of caching mechanisms than what blobfuse offers. I'm just reading the same files over and over, and was hoping they would be cached.

### Have you found a mitigation/solution?
no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
I'm not sure these are relevant. The URL (which I had to remove) is non-sense.

Aug 22 00:53:51 [...] blobfuse[44462]: Sat Aug 22 00:53:51 2020 ==> RE
QUEST/RESPONSE#012#011HEAD https://[...]#012#011User-Agent: [Azure-Storage-Fuse/1.2.1]#012#011x-ms-date
: [Sat, 22 Aug 2020 00:53:51 GMT]#012#011x-ms-version: [2017-11-09]#012#011Autho
rization: [REDACTED]#012#011Transfer-Encoding: []#012#011-----------------------
---------------------------------------------------------#012#011RESPONSE Status
: 404#012#011Date: [Sat, 22 Aug 2020 00:53:51 GMT]#012#011Server: [Windows-Azure
-Blob/1.0 Microsoft-HTTPAPI/2.0]#012#011Transfer-Encoding: [chunked]#012#011x-ms
-error-code: [BlobNotFound]#012#011x-ms-request-id: [bb19347a-401e-0164-481e-78c
023000000]#012#011x-ms-version: [2017-11-09]
Aug 22 00:53:51 wopauliseekervm blobfuse[44462]: Sat Aug 22 00:53:51 2020 ==> REQUEST/RESPONSE#012#011HEAD [...]#012#011User-Agent: [Azure-Storage-Fuse/1.2.1]#012#011x-ms-date: [Sat, 22 Aug 2020 00:53:51 GMT]#012#011x-ms-version: [2017-11-09]#012#011Authorization: [REDACTED]#012#011Transfer-Encoding: []#012#011--------------------------------------------------------------------------------#012#011RESPONSE Status: 404#012#011Date: [Sat, 22 Aug 2020 00:53:51 GMT]#012#011Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]#012#011Transfer-Encoding: [chunked]#012#011x-ms-error-code: [BlobNotFound]#012#011x-ms-request-id: [3265c795-701e-004a-4d1e-7806b1000000]#012#011x-ms-version: [2017-11-09]

### If relevant, please share your mount command.
blobfuse ~/3d_scans/ --tmp-path=/tmp/blobfusetmp  --config-file=3d_scans.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --file-cache-timeout-in-seconds=1800

**Comment by vibhansa-msft** [comment]
@wmpauli your observations are correct. When user requests to open a file, it will be served from the cache if the cache is valid otherwise it will be refreshed from blob storage. Cache validity depends on whether 'file-cache-timeout-in-seconds' has elapsed since file's last modified time or change time. When the file is open for the first time, it will be retrieved from storage account and cached. During this blobfuse will set the last modified time of cached file to the modified time given by storage and not the current time of caching.
