### ISSUE TITLE
Update link containing supported OS platforms

### ISSUE THREAD

**Issue by rishabpoh** [Azure/azure-storage-fuse#457]
Update: https://docs.microsoft.com/en-us/windows-server/administration/Linux-Package-Repository-for-Microsoft-Software

**Comment by msLinuxNinja** [comment]
Also update https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux#configure-the-microsoft-package-repository as it is extremely vague as to what versions are supported.

**Comment by NaraVen** [comment]
done
