### ISSUE TITLE
Missing libraries for install on Ubuntu 20.04 

### ISSUE THREAD

**Issue by atiro** [Azure/azure-storage-fuse#460]
### Which version of the blobfuse was used?

1.2.1 (just released for 20.04)

### Which OS (please include version) are you using?

Ubuntu 20.04 (Pro)

### What problem was encountered?

Missing shared libraries:

ldd /usr/bin/blobfuse 
	linux-vdso.so.1 (0x00007ffd6d5f7000)
	libcurl-gnutls.so.4 => /lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f946485a000)
	libgnutls.so.26 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9464837000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f946482e000)
	libfuse.so.2 => /lib/x86_64-linux-gnu/libfuse.so.2 (0x00007f94647ef000)
	libgcrypt.so.11 => not found
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f946460

### Have you found a mitigation/solution?

No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

n/a

**Comment by vibhansa-msft** [comment]
You need to install the libraries manually before running blobfuse. Use below command and try again

sudo apt-get update --fix-missing
sudo apt-get install pkg-config cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev libboost-all-dev gcc g++ -y

**Comment by atiro** [comment]
Cheers, have done. Could you perhaps add them as dependencies on the package so apt installs them ?
