### ISSUE TITLE
typo in release notes for 1.3.1

### ISSUE THREAD

**Issue by potapuff** [Azure/azure-storage-fuse#461]
>6. Added options to make cache configurable in bytes. Optional commandline param --cache_size_mb=1000 will specify a cache size of 1 GB
should be "configurable in **mega**bytes. " and "--cache**-**size**-**mb=1000"

>7. Added options to specify concurrency. Optional commandline param --max_concurrency=14 will reset the default concurrency of 12.
should be "--max**-**concurrency=14"

**Comment by NaraVen** [comment]
Thank you. Corrected them
