### ISSUE TITLE
blobfuse mount error

### ISSUE THREAD

**Issue by lixiaodong20170710** [Azure/azure-storage-fuse#462]
### Which version of the blobfuse was used?
blobfuse 1.0.2

### Which OS (please include version) are you using?
CentOS Linux release 7.6.1810 (Core)

### What problem was encountered?
I put blobfuse start scirpt into /etc/rc.local file, and then I put the app start script after blobfuse script in rc.local file, because the app log write logs into the dir that blobfuse mount dir, and the blobfuse mount failed.
the error message is follow:
Sep  2 00:54:11 RDC-SMP kernel: blobfuse[1613]: segfault at 9 ip 00007f11a157e7f9 sp 00007ffed2c391a0 error 4 in libc-2.17.so[7f11a14fe000+1c3000]

### Have you found a mitigation/solution?
Between the blobfuse and app start script , I put into "sleep 10s"  script, the blobfuse mount success.
I don't know the blobfuse mount need how long time to mount? Is it related with the Data volume in blob that mount to VM by blobfuse command.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Sep  2 00:54:11 RDC-SMP kernel: blobfuse[1613]: segfault at 9 ip 00007f11a157e7f9 sp 00007ffed2c391a0 error 4 in libc-2.17.so[7f11a14fe000+1c3000]

### If relevant, please share your mount command.
blobfuse /var/log/applog/ --tmp-path=/mnt/resource/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/etc/fuse/connection.cfg --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120

**Comment by vibhansa-msft** [comment]
To your query regarding the timing, on blobfuse mount it makes a connection to your storage account, does authentication checks and tries to read a few entries from the container to validate the connection. Once this process is done you can start with your regular operations. So having a small delay shall hold good. It is not related to data volume in your container as such. You can upgrade to 1.2.4 or our latest version 1.3.1 and see if the problem persists.

**Comment by vibhansa-msft** [comment]
Did the problem persists with the new version as well ?

**Comment by vibhansa-msft** [comment]
Closing the issue as there is no update. Feel free to re-open if the issue persists.
