### ISSUE TITLE
Blobfuse hangs when using customDNS and privatelink on Azure

### ISSUE THREAD

**Issue by mabicca** [Azure/azure-storage-fuse#464]
### Which version of the blobfuse was used?
**fuse-2.9.2-11.el7.x86_64
blobfuse-1.0.2-1.x86_64
fuse-libs-2.9.2-11.el7.x86_64**

### Which OS (please include version) are you using?
Tested on Red Hat 7.8 (default kernel) and Ubuntu 18.04. It looks like this is not related to OS.

### What problem was encountered?
When mounting the blobfuse folder, it mounts correctly but we noticed that if you try doing let's say an ls -l or an ls -latr, it will hang and not complete.

### Have you found a mitigation/solution?
We found out that the issue was fixed by changing the DNS servers to use the Azure servers, in this case the environment is using Azure Private Link with their own DNS servers:
Azure Private Link reference: https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns
DNS reference: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances#name-resolution-that-uses-your-own-dns-server

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Not really.

### If relevant, please share your mount command.
`/bin/blobfuse /store --tmp-path=/mnt/resource/blobfusetmp --config-file=/opt/blob/fuse_connection.cfg --container-name=linux -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG`

I think the bottom line for this issue is indicate or maybe document what is needed for blobfuse to work with PrivateLink and CustomDNS servers. It looks like the resolution was indeed slower with the custom DNS servers but it would resolve. Changing DNS servers to Azure worked right away.

==
**Are there any specific things we need to do differently when using Azure Private Links in regards of Blobfuse setup, besides required DNS configuration to forward privatelink queries appropriately to Azure DNS servers?**

**Comment by NaraVen** [comment]
@mabicca , What value does accountName have in the fuse_connection.cfg. Is it the FQDN with the suffic privatelink.blob.core.windows.net?

**Comment by mabicca** [comment]
Hi @NaraVen thanks for the response. I figured it out that the issue was indeed due to DNS configuration. They did not have the proper forwarding zones setup in their own DNS to forward requests to the Azure resolver (168.63.129.16). I guess the main reason for this ticket would be to make sure we mention usage of private links in our setup documents and make the reference to make sure customers have their custom DNS servers setup properly.

I think it would be useful to have at least some reference in there since the setup might fail if they did not configure DNS correctly.

**Comment by NaraVen** [comment]
Cool, I will add private link setup to the wiki.

**Comment by NaraVen** [comment]
Glad everything works. I updated the Wiki with a new section for Private links. I also added a troubleshooting section for private links.

**Comment by mabicca** [comment]
Awesome, thank you @NaraVen
