### ISSUE TITLE
Mounting the blob storage using Service Principal fails with an error

### ISSUE THREAD

**Issue by sihegde** [Azure/azure-storage-fuse#466]
### Which version of the blobfuse was used?
1.3.1

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
I am trying to mount the Azure Blob Storage container to my Linux VM using blobfuse and using Service Principal. The Service Principal has been given sufficient permissions in the Azure Storage account.
I referred the article : https://github.com/Azure/azure-storage-fuse/blob/master/README.md#config-file-options
And have mentioned below details in the config file.
accountName storageaccount
authType MSI
servicePrincipalClientId 16de41d*********cb
servicePrincipalTenantId 7f9************7b47
containerName testcontainer

However, when I try to mount the storage using the command : **sudo blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other**
I am getting below error : URI token request URL printed out http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A//storage.azure.com/
OAUTH Token : **Refresh token failed Failed to retrieve OAuth Token from IMDS endpoint (CURLCode: 0, HTTP code: 400): {"error":"invalid_request","error_description":"Identity not found"}Unable to retrieve OAuth token: Failed to retrieve OAuth Token from IMDS endpoint (CURLCode: 0, HTTP code: 400): {"error":"invalid_request","error_description":"Identity not found"}
Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.**

If I enable System Managed Identity and try to mount it using Managed Identity, the set up works fine. 
Can you please help in resolving the issue?

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Sep  5 12:36:43 blobfusesihegde blobfuse[28765]: Account name found
Sep  5 12:36:43 blobfusesihegde blobfuse[28765]: Auth type set as msi
Sep  5 12:36:43 blobfusesihegde blobfuse[28765]: Container name found
Sep  5 12:36:43 blobfusesihegde blobfuse[28765]: Setting logging level to : LOG_WARNING
Sep  5 12:36:48 blobfusesihegde blobfuse[28765]:  ==> REQUEST/RESPONSE :: GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A//storage.azure.com/?&Metadata=true&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 400 ::
Sep  5 12:36:48 blobfusesihegde blobfuse[28765]: OAUTH Token : Refresh token failed Failed to retrieve OAuth Token from IMDS endpoint (CURLCode: 0, HTTP code: 400): {"error":"invalid_request","error_description":"Identity not found"}
Sep  5 12:36:48 blobfusesihegde blobfuse[28765]: Unable to retrieve OAuth token: Failed to retrieve OAuth Token from IMDS endpoint (CURLCode: 0, HTTP code: 400): {"error":"invalid_request","error_description":"Identity not found"}
Sep  5 12:36:48 blobfusesihegde blobfuse[28765]: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.

### If relevant, please share your mount command.
sudo blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Comment by NaraVen** [comment]
authType should be SPN  and not MSI if you want to use Service principal. Also remember to set the servicePrincipalClientSecret either in your environment variable or in your config file

**Comment by sihegde** [comment]
Thank you @NaraVen , using SPN I was able to mount the blob storage.

**Comment by hanrimJO** [comment]
@sihedge Please let me know how to set authtype from MSI to SPN

**Comment by NaraVen** [comment]
you should create an SPN in Azure and give your storAge account permissions so that this user is a storage contributor, your config file for mounting should look like this
accountName storageaccount
authType SPN
servicePrincipalClientId 16de41dcb
servicePrincipalClientSecret <secret>
servicePrincipalTenantId 7f9***7b47
containerName testcontainer
