### ISSUE TITLE
How to upgrade Blobfuse version from 1.0.2 to 1.3.1

### ISSUE THREAD

**Issue by Rajan3542** [Azure/azure-storage-fuse#467]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Red Hat enterprise Linux server v7.5

### What problem was encountered?
Want to upgrade Blobfuse version from 1.0.2 to 1.3.1 or any latest version

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Not applicable

**Comment by NaraVen** [comment]
1.3.2 is the latest. At this time you can clone the source could and build it, command git clone https://github.com/Azure/azure-storage-fuse. It will create an azure-storage-fuse directory,  if you run ./build.sh from this dir it will create a blobfuse binary in the build directory. you can mount just like an installed version Eg: ./build/blofuse ~/blobfusemntdir --tmp-path=< your path>

**Comment by rishabpoh** [comment]
Feel free to re-open this issue if it persists! Thank you.
