### ISSUE TITLE
Unable to Build Binary on Oracle Linux 8.2

### ISSUE THREAD

**Issue by abamure** [Azure/azure-storage-fuse#468]
### Which version of the blobfuse was used?
1.3.2

### Which OS (please include version) are you using?
Oracle Linux 8.2

### What problem was encountered?
Followed the steps on the wiki page (https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation#option-2---build-from-source) but keep throwing errors:

[amure@Linux82VM azure-storage-fuse]$ ./build.sh
./build.sh: line 6: [: =: unary operator expected
./build.sh: line 21: [: =: unary operator expected
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/amure/azure-storage-fuse/cpplite/build.release/CMakeFiles/CMakeOutput.log".
No such file or directory
CMake Error: Generator: execution of make failed. Make command was: ""
************************ CPPLite build Failed *****************************

### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
There is some issue with the build tool on system. C++ compiler might be missing. Install gcc & g++, and try again.

**Comment by NaraVen** [comment]
that build.sh works on Oracle Linux 8.2
