### ISSUE TITLE
Can not upload file to Azure datalake storage gen2

### ISSUE THREAD

**Issue by PengleiShi** [Azure/azure-storage-fuse#469]
### Which version of the blobfuse was used?

1.3.2
### Which OS (please include version) are you using?

ubuntu
### What problem was encountered?

I can mount successfully and cp files from container to local. But when i cp/mv local files to container, it occurs error:
`cp: failed to close 'mount/1.txt': Input/output error`,  Anyone can help me?

**Comment by vibhansa-msft** [comment]
Kindly share the blobfuse logs around the time this operation failed.

**Comment by PengleiShi** [comment]
@vibhansa-msft yes, when i cp local file to container, here is the log in syslog
![image](https://user-images.githubusercontent.com/23723660/93106465-e1d38900-f6e2-11ea-8083-f2d2539aa560.png)

**Comment by vibhansa-msft** [comment]
Version 1.3.3 should fix this problem. Feel free to re-open if the issue persists.

**Comment by PengleiShi** [comment]
> Version 1.3.3 should fix this problem. Feel free to re-open if the issue persists.

hi @vibhansa-msft , i found the same error with blobfuse 1.3.4.

**Comment by NaraVen** [comment]
@PengleiShi , Could you please share your mount command and config file?

**Comment by PengleiShi** [comment]
![image](https://user-images.githubusercontent.com/23723660/95963746-a5f32700-0e3a-11eb-904f-05308bf62803.png)

config file:
![image](https://user-images.githubusercontent.com/23723660/95963668-8eb43980-0e3a-11eb-9889-3bd40e184603.png)

command:
`blobfuse /home/azureuser/data --tmp-path=/home/azureuser/tmp --config-file=/home/azureuser/fuse-connection.cfg`

**Comment by NaraVen** [comment]
the config values are correct. This is a bug in 1.3.4 . Our upcoming release has a fix for this. The latest source code has the fix too.

**Comment by PengleiShi** [comment]
ok， thank you Nara.

**Comment by NaraVen** [comment]
We will accommodate non-public cloud for adls in our upcoming release.

**Comment by NaraVen** [comment]
@PengleiShi Version 1.3.5 was released today. This release should support non-public cloud in ADLS Gen 2. Please comment if it does not. Closing this issue for now.
