### ISSUE TITLE
blobfuse > 1.1.1 = transport endpoint disconnected at random times

### ISSUE THREAD

**Issue by cris-b** [Azure/azure-storage-fuse#470]
### Which version of the blobfuse was used?

1.3.2

I'm starting this as a follow on from some of the questions in issue 463.

### Which OS (please include version) are you using?

ubuntu 18.04

### What problem was encountered?

When running our data processing app using blobfuse as the storage location blobfuse dies and I get "transport endpoint disconnected"

### Have you found a mitigation/solution?

Use blobfuse 1.1.1 - after this I got the random errors.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

last thing in log before error is:

Sep 11 12:12:49 xxxx1 blobfuse[11212]: Successfully uploaded file /logs/2020-06-18/runval.sh.2020-06-18.1.log to blob logs/2020-06-18/runval.sh.2020-06-18.1.log.
Sep 11 12:12:49 xxxx1 blobfuse[11212]: Function azs_flush, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 259: azs_flush called with path = (null), fi->flags = 0, (((struct fhwrapper *)fi->fh)->fh) = 25.

**Comment by vibhansa-msft** [comment]
Have you manually modified any info in the logs ? if no then I see some issue  as per the logs. 
"azs_flush called with path = (null), fi->flags = 0, (((struct fhwrapper *)fi->fh)->fh) = 25."
'path = (null)' is not expected. It should have been the file name being flushed. Can you give more details on what operations were going on when this happened.

**Comment by cris-b** [comment]
all I modified was the hostname in the log, everything else was the same.  the code does seem to say that sometimes null can be received.

thats the only time I see it called with null in my log.

At the time it has just finished a scan of some data and is writing command result to the logs by the looks of it from the blobfuse calls just before.

**Comment by vibhansa-msft** [comment]
Yes the log above the flush is pointing to successful upload of your log file. But last log being that of flush, I am suspecting, caused the disruption. If flush was going through fine there shall have been other logs. Can you share logs of last 10-15 minutes just want to analyze what other operations were going on in the system.

**Comment by cris-b** [comment]
[blobfuse-10-15.log.gz](https://github.com/Azure/azure-storage-fuse/files/5223479/blobfuse-10-15.log.gz)

attached last 15 min log.

**Comment by vibhansa-msft** [comment]
azs_flush do have a bug with null path, causing blobfuse to crash. Will be fixed in the next release.

**Comment by cris-b** [comment]
great! any clues as to why <= 1.1.1 was ok?

**Comment by vibhansa-msft** [comment]
This is due to new changes that went in 1.3.2, so releases before these versions are not having it.

**Comment by cris-b** [comment]
hmm this must mean it is something else in versions before 1.3.2 then..

**Comment by vibhansa-msft** [comment]
azs_flush issue is fixed in version 1.3.3

**Comment by cris-b** [comment]
sweet! will repeat my test with 1.3.3
