### ISSUE TITLE
blobfuse build fails on building cpplite

### ISSUE THREAD

**Issue by yuras68** [Azure/azure-storage-fuse#471]
### Which version of the blobfuse was used?

1.3.2-Linux (repository as of 9/16/2020)
### Which OS (please include version) are you using?

RHEL 7.8 3.10.0-1127.el7.x86_64
### What problem was encountered?
build.sh fails when building cpplite:

First:
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
Then:
-- Build files have been written to: azure-storage-fuse/cpplite/build.release
Scanning dependencies of target azure-storage-lite
[  2%] Building CXX object CMakeFiles/azure-storage-lite.dir/src/logging.cpp.o
[  4%] Building CXX object CMakeFiles/azure-storage-lite.dir/src/base64.cpp.o
[  6%] Building CXX object CMakeFiles/azure-storage-lite.dir/src/constants.cpp.o
[  9%] Building CXX object CMakeFiles/azure-storage-lite.dir/src/hash.cpp.o
[ 11%] Building CXX object CMakeFiles/azure-storage-lite.dir/src/utility.cpp.o
azure-storage-fuse/cpplite/src/utility.cpp: In function ‘std::string azure::storage_lite::get_ms_date(azure::storage_lite::date_format)’:
azure-storage-fuse/cpplite/src/utility.cpp:103:19: error: ‘put_time’ is not a member of ‘std’
             ss << std::put_time(pm, constants::date_format_rfc_1123);
                   ^
gmake[2]: *** [CMakeFiles/azure-storage-lite.dir/src/utility.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/azure-storage-lite.dir/all] Error 2
gmake: *** [all] Error 2

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
N/A

### If relevant, please share your mount command.
N/A

**Comment by vibhansa-msft** [comment]
Fixed in version 1.3.3
