### ISSUE TITLE
Root folder getting created under  --tmp-path

### ISSUE THREAD

**Issue by Rajan3542** [Azure/azure-storage-fuse#474]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Red Hat enterprise Linux server v7.5

### What problem was encountered?
After mounting blobfuse containers in our server, there's a root folder which got created under the folder which are using as our --tmp-path. We need to know why this folder getting created even though we are not using root user to mount the containers.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No errors in related to this issue.

### If relevant, please share your mount command.

blobfuse /home/my_user/blobfuse/containers/container_name --container-name=container_name --file-cache-timeout-in-seconds=0 --config-file=/home/my_user/blobfuse/config/container_connection.cfg --tmp-path=/home/my_user/blobfuse/temp_store/container_temp -o allow_other

**Comment by vibhansa-msft** [comment]
'root' directory creation is not dependent on user privileges. It's by design assuming container is 'root' directory. It will be removed when container is unmounted,
