### ISSUE TITLE
Standard procedure to unmount blobfuse containers

### ISSUE THREAD

**Issue by Rajan3542** [Azure/azure-storage-fuse#475]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Red Hat enterprise Linux server v7.5

### What problem was encountered?
We need to know the standard procedure along with the exact steps to unmount a blobfuse containers in Linux. We need this to avoid any unnecessary errors while remounting the containers from our production server. 

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Not applicable

### If relevant, please share your mount command.
blobfuse /home/my_user/blobfuse/containers/container_name --container-name=container_name --config-file=/home/my_user/blobfuse/config/container_connection.cfg --tmp-path=/home/my_user/blobfuse/temp_store/container_temp -o allow_other

**Comment by vibhansa-msft** [comment]
To unmount a container use "fusermount -u <mount path>"
Running this command from within the mounted directory will fail with "Device or resource busy" error, so makesure you are not in mounted path.
