### ISSUE TITLE
blobfuse taking time to mount and doenst list files

### ISSUE THREAD

**Issue by pnkumaresh** [Azure/azure-storage-fuse#478]
### Which version of the blobfuse was used?

# blobfuse -v
blobfuse 1.0.2

### Which OS (please include version) are you using?
Linux ******00 3.10.0-693.58.1.el7.x86_64 #1 SMP Tue Aug 13 11:39:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### What problem was encountered?
Taking too long to mount and doesn't list the files when used command ls

### Have you found a mitigation/solution?
Not yet

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
blobfuse[1492]: Failed to list blobs under directory /app/storagetmp/root/ on the service during readdir operation.  errno = -1.
Failed to map storage error code -1 to a proper errno.  Returning EIO = 5 instead.

### If relevant, please share your mount command.
blobfuse /app/storage --tmp-path=/app/storagetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120  --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 --config-file=connection.cfg

# more connection.cfg
accountName account00
accountKey ****
containerName log
authType Key
blobEndpoint https://account00.blob.core.usgovcloudapi.net

**Comment by NaraVen** [comment]
It appears that list is timing out? How log does it take to mount? Also 1.0.2 is a really old version. Which distro and  version of Linux are you on? If you are on Ubuntu you can upgrade.

**Comment by pnkumaresh** [comment]
Redhat Linux. Any repo you recommend.

************************************
Best Regards
Kumaresh

**Comment by NaraVen** [comment]
We have uploaded a few RHEL rpms at https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux. Could you please try if any of them fits your distro and version?

**Comment by NaraVen** [comment]
closing this since the link https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux has rpms multiple RHEL versions.
