### ISSUE TITLE
RPM Build for blobfuse 1.3.2

### ISSUE THREAD

**Issue by adkadmin** [Azure/azure-storage-fuse#480]
Feel free to re-open this issue if it persists! Thank you.

_Originally posted by @rishabpoh in https://github.com/Azure/azure-storage-fuse/issues/467#issuecomment-692854068_

Thanks for answering the first query regarding blosfuse build. Though, there are too many dependencies sometimes. Is there a way to generate RPM package since we have the whole GIT repos cloned to build the binary in the first place.  This will help is migration without other dependencies to be resolved.

Thanks,
AK

**Comment by NaraVen** [comment]
Yes, there is . Run the generaterpm.sh in the same directory

**Comment by adkadmin** [comment]
Thanks! But getting below error:
Looked into the generaterpm.sh code as  well.. nothing seems wierd (date command to run same in rhel 7.8 or 8.2)

[root@servr1 blobfuse]# ./generaterpm.sh -srcdir ../build -distrover rhel78
Source dir:  ../build
Linux distro and version: rhel78
Version:  1.3.2
Building RPM package for blobfuse version 1.3.2
From:  /root/Azure_blob/2/azure-storage-fuse-master/blobfuse
created dir /root/rpmbuild
created dir /root/rpmbuild/SOURCES
created dir /root/rpmbuild/SPECS
Creating Tar from: ../build
cp: cannot stat ‘README.md’: No such file or directory
cp: cannot stat ‘LICENSE’: No such file or directory
blobfuse-1.3.2/
blobfuse-1.3.2/blobfuse
Copying Tar to: ~/rpmbuild/SOURCES
/root/Azure_blob/2/azure-storage-fuse-master/blobfuse
Building target platforms: ./
Building for target ./
error: bad date in %changelog: Wed Sep 23 10:22:47 UTC 2020 Blobfuse Dev blobfusedev@microsoft.com> 1.3.2
/root/Azure_blob/2/azure-storage-fuse-master/blobfuse
cp: cannot stat ‘/root/rpmbuild/RPMS/x86_64/blobfuse-1.3.2-*x86_64.rpm’: No such file or directory
mv: cannot stat ‘blobfuse-1.3.2-*x86_64.rpm’: No such file or directory

Could you please help!


Thanks
AK

**Comment by vibhansa-msft** [comment]
'date' put in %changelog is containing time as well and that is leading to failure in parsing this. Can you make below changes in generaterpm.sh file manually and try agian.

-------------------------------------------------------------------------------------
-cp README.md blobfuse-${version}/
-cp LICENSE blobfuse-${version}/
+cp ../README.md blobfuse-${version}/
+cp ../LICENSE blobfuse-${version}/


-* $(date) Blobfuse Dev blobfusedev@microsoft.com> ${version}
+* $(date +"%a %b %d %Y") Blobfuse Dev blobfusedev@microsoft.com> ${version}
-------------------------------------------------------------------------------------

**Comment by vibhansa-msft** [comment]
Did the above change solve the problem. 1.3.2 has some known issues. You can take the latest code base, above failure is also fixed in that.

**Comment by adkadmin** [comment]
Hello Vikas,

I happen to fix this  %changelog by just commenting everything and RPM package is generated. Though this RPM package is of no use!! The reason being it failed to copy the required lib.
libboost_filesystem-mt.so.1.53.0()(64bit) is needed by blobfuse-1.3.2-1.el7.x86_64
libboost_system-mt.so.1.53.0()(64bit) is needed by blobfuse-1.3.2-1.el7.x86_64
libboost_thread-mt.so.1.53.0()(64bit) is needed by blobfuse-1.3.2-1.el7.x86_64

These dependent lib is needed even after we have fuse-2.9.2-11.el7.x86_64 installed. Other the list of lib would be longer. These libs are added as part of build in /usr/lib64

Also, the blobfuse version supplied of MS Repos 1.0.2 still seems to be the most stable version. Upon mounting containers using this version 1.3.2 (Just by using binary generated in build and copying lib manually), we are not able list it and it  is hanging with below error in syslog:

**blobfuse[26226]: list_blobs failed for the 5 time with errno = 35.**
 
The reason for trying higher version was a bug in 1.0.2 where sometime we need to remount the container as it stops working and to handle more files per hour. However, we are not clear now what to do! The mount is done using the recommended method, that is, the command given in mount.sh and also tried on the server, where the actual build is performed.

Do you we are missing anything?
Do we have a stable version, after 1.0.2.? If so, could you please give the code base link to build this, or the RPM package for RHEL 7

Thanks a lot for reverting.


Kind Regards,
AK

**Comment by vibhansa-msft** [comment]
You can take code base from tag 1.3.3 or the latest one (its just 1.3.3 + the fix discussed above) and build it. 
If you had problem building it earlier due to the dependencies you can do the following :

sudo yum install git make cmake gcc gcc-c++ curl-devel gnutls-devel libuuid-devel boost-devel libgcrypt-devel -y
sudo yum install fuse-devel -y

**Comment by NaraVen** [comment]
@adkadmin Your error indicates a wrong version of Curl because it is failing in the SSL validation stage and timing out. Could you please try our pre-built rpms at https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux?

**Comment by adkadmin** [comment]
Thank you! Let me try and get back to you.

Kind Regards,
AK

**Comment by NaraVen** [comment]
closing this one since we have a release for RHEL 7.8 in the link above.
