### ISSUE TITLE
Unable to upload/download files from adls mount (Azure Data Lake gen2)

### ISSUE THREAD

**Issue by Michal-Danko** [Azure/azure-storage-fuse#481]
### Which version of the blobfuse was used?

1.3.3

### Which OS (please include version) are you using?

CentOS Linux 8 (Core) Linux 4.18.0-147.8.1.el8_1.x86_64

### What problem was encountered?

When mounted with adls option, I am unable to copy files from/to Azure Data Lake gen2 storage.
It seems the problem is that blobfuse is using wrong fqdn when accessing Azure storage; should always try to access <account>.dfs.core.windows.net (it's correct when doing HEAD call - see logs), but for some reason it's accessing <account>.blob.core.windows.net when doing PUT and GET calls.

If this is expected behavior, can you please explain how to force blobfuse to always use <account>.dfs.core.windows.net ?

### Have you found a mitigation/solution?

no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

Sep 23 08:53:39 ecs-warp-edge2 blobfuse[39864]: ==> REQUEST/RESPONSE :: HEAD https://censored.dfs.core.windows.net/mdanko/100mb.test?&User-Agent=Azure-Storage-Fuse/1.3.3&x-ms-date=Wed, 23 Sep 2020 08:53:39 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 404 :: REQ ID : feb8b0b2-801f-0115-7a87-9136c9000000
Sep 23 08:53:39 ecs-warp-edge2 blobfuse[39864]: File does not currently exist on the storage or cache
Sep 23 08:53:39 ecs-warp-edge2 blobfuse[39864]: Successfully created file /100mb.test in file cache.
Sep 23 08:53:39 ecs-warp-edge2 blobfuse[39864]: ==> REQUEST/RESPONSE :: PUT https://censored.blob.core.windows.net/mdanko/100mb.test?blockid=MDAwMDAwMDAwMDAwYzkzMTM2MmYtZmEwOC00YjRiLWJmM2ItZTZiMzE2MjZmNzMy&comp=block?&Content-Length=16777216&User-Agent=azure-storage-fuse/1.3.3&x-ms-date=Wed, 23 Sep 2020 08:53:39 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 0 ::

### If relevant, please share your mount command.

./blobfuse /mnt/azure --tmp-path=/mnt/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=connection.cfg --log-level=LOG_DEBUG --use-adls=true

**Comment by NaraVen** [comment]
This -> blob.core.windows.net is the expected/recommended endpoint for upload and download. Which tool did you use to upload files? If the files were uploaded using the ADLS dfs.core endpoint then it will have issues while getting downloaded from blobfuse. It is recommended to use the same endpoint for upload and download. For eg: if you use dfs.core.windows.net for upload it is recommended to download too using dfs.core.windows.net. Same is the case if you use blob.core.windows.net for upload, use blob.core.windows.net for download.

**Comment by NaraVen** [comment]
For upload and download the blob endpoint is recommend by storage over the dfs endpoint. I am trying to reproduce your issue. Are you copying a file from a folder to the mount folder or are you creatign the file by editing?

**Comment by vibhansa-msft** [comment]
Blobfuse does not have an option to override this as blob endpoint is preferred over dfs. Upload/Download will always use blob endpoint by design and it works for ADLS account as well. Can you try uploading a file to this container directly through portal, suspecting some user privileges issue here. Also the file you are trying to upload, is it a copy operation to mounted directory or file was created in mounted directory directly.

**Comment by Michal-Danko** [comment]
Explicitly setting blob endpoint to dfs solved my problem. Thanks for hints!

**Comment by vibhansa-msft** [comment]
Can you share bit more details on what changes you did exactly.

**Comment by Michal-Danko** [comment]
In the end, it was a combination of two things, I had to add these two lines to connection.cfg file:

accountType adls
blobEndpoint censored.dfs.core.windows.net

Then and only then I was able to successfully mount Azure Datalake gen2 Storage and transfer files between mount/localsystem.


1.      When I did not explicitly set blob endpoint, I was not able to transfer files (original post).


2.      When adls was not set, I was getting this error:

Sep 24 04:40:38 ecs-warp-edge2 blobfuse[40759]: Setting logging level to : LOG_DEBUG
Sep 24 04:40:38 ecs-warp-edge2 blobfuse[40759]: release is 4.180000, Kernel version is 4.18.0-147.8.1.el8_1.x86_64
Sep 24 04:40:38 ecs-warp-edge2 blobfuse[40759]: ==> REQUEST/RESPONSE :: GET https://censored.dfs.core.windows.net/mdanko?comp=list&delimiter=/&include=metadata&maxresults=1&restype=container?&User-Agent=azure-storage-fuse/1.3.3&x-ms-date=Thu, 24 Sep 2020 04:40:38 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 400 :: REQ ID : 8219649a-f01f-00a9-662c-921e05000000
Sep 24 04:40:38 ecs-warp-edge2 blobfuse[40759]: Unable to start blobfuse.  Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key/sas token/OAuth access token and container name. errno = 400

Hope this helps!

Kind regards / Mit freundlichen Grüßen / S pozdravom
Michal Danko

Deutsche Telekom IT Solutions Slovakia
Deutsche Telekom Systems Solutions Slovakia
Public Cloud Managed Services
Senior Solution Designer Big Data
Moldavska 8/A, 040 11 Košice, Slovakia
+421 901 707 180 (Mobile)
+421 55 785 4879 (Phone)
E-mail: michal.danko@t-systems.com<mailto:michal.danko@t-systems.com>
Web: www.deutschetelekomitsolutions.sk<https://www.deutschetelekomitsolutions.sk/>

LIFE IS FOR SHARING.

The compulsory statement can be found here<https://www.deutschetelekomitsolutions.sk/en/compulsory-statement>

**Comment by NaraVen** [comment]
Thank so much for the information. Which region is your storage account in?
