### ISSUE TITLE
Can't delete mounted datalake directories 

### ISSUE THREAD

**Issue by vervynckt** [Azure/azure-storage-fuse#483]
### Which version of the blobfuse was used?

1.2.1

### Which OS (please include version) are you using?

Debian 4.19.118-2+deb10u1 (2020-06-07)

### What problem was encountered?

Can't delete directories I made on the mounted datalake.
![image](https://user-images.githubusercontent.com/58850425/94124834-cfc9b700-fe55-11ea-8e92-c3bc6a41fba2.png)

### Have you found a mitigation/solution?

•	Creating / deleting a **file** works fine
•	Deleting a directory ‘hangs’ the console and eventualy throws error above
•	When I do stat on the directory I have rwx (0777)
•	When I check the Blobfuse local cache the directory **did get deleted**
•	When looking at the datalake (on azure) the directory is still there

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

Notice the 500 response

•	When looking at the Blobfuse error logs (/var/log/syslog) I found the following error:
Sep 23 14:03:48 PROD-a-a blobfuse[3516]: Wed Sep 23 14:03:48 2020 ==> REQUEST/RESPONSE#012#011DELETE https://dummyname.blob.core.windows.net/datal
ake/test/test#012#011x-ms-delete-snapshots: [include]#012#011User-Agent: [Azure-Storage-Fuse/1.2.1]#012#011x-ms
-date: [Wed, 23 Sep 2020 14:03:31 GMT]#012#011x-ms-version: [2017-11-09]#012#011Authorization: [REDACTED]#012#011Transfer-Encoding: []#012#011----------------
----------------------------------------------------------------#012#011RESPONSE Status: 500#012#011Connection: [close]#012#011Content-Length: [253]#012#011Co
ntent-Type: [application/xml]#012#011Date: [Wed, 23 Sep 2020 14:03:47 GMT]#012#011Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]#012#011x-ms-error-cod
e: [InternalError]#012#011x-ms-request-id: [8e13785b-101e-0042-51b2-91116f000000]#012#011x-ms-version: [2017-11-09]

### If relevant, please share your mount command.

#!/bin/bash
BLOBFS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $BLOBFS_DIR/build
blobfuse $1 --tmp-path=/tmp --config-file=/home/support/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

### fuse_connection.cfg

accountName dummyname
accountKey dummykey
containerName datalake
authType Key
accountType adls

I have also tried with only:

accountName <name>
accountKey <key>
containerName datalake

**Comment by vibhansa-msft** [comment]
'accountType adls' is supported only version 1.3.1 onward. If you are accessing an ADLS account kindly upgrade to our latest version.

**Comment by vervynckt** [comment]
Thank you for the reply, as stated I also tried with accountName, accountKey and containerName I suppose this should be sufficient?

**Comment by TheMP** [comment]
Same issue, tried with SAS token with dlrwa permissions - mount works, cp/touch etc. commands as well. I have no issues removing files, but when I try to remove empty directory I get 

`Sep 24 13:07:56 AZRVM1 blobfuse[60109]:  ==> REQUEST/RESPONSE :: DELETE https://mystoragename.blob.core.windows.net/dropzone/top_dir/dir?se=2020-09-29&sp=rawdl&spr=https&sv=2018-11-09&sr=c&skoid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&sktid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&skt=2020-09-24T13%3A06%3A15Z&ske=2020-09-29T00%3A00%3A00Z&sks=b&skv=2018-11-09&sig=REDACTED?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.3.3&x-ms-date=Thu, 24 Sep 2020 13:07:38 GMT&x-ms-version=2018-11-09&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 6116482f-201e-0101-6973-92adfa000000
Sep 24 13:08:19 AZRVM1 blobfuse[60109]:  ==> REQUEST/RESPONSE :: DELETE https://mystoragename.blob.core.windows.net/dropzone/top_dir/dir?se=2020-09-29&sp=rawdl&spr=https&sv=2018-11-09&sr=c&skoid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&sktid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&skt=2020-09-24T13%3A06%3A15Z&ske=2020-09-29T00%3A00%3A00Z&sks=b&skv=2018-11-09&sig=REDACTED?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.3.3&x-ms-date=Thu, 24 Sep 2020 13:07:56 GMT&x-ms-version=2018-11-09&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 6e13930e-701e-008c-7d73-927a68000000
Sep 24 13:08:40 AZRVM1 blobfuse[60109]:  ==> REQUEST/RESPONSE :: DELETE https://mystoragename.blob.core.windows.net/dropzone/top_dir/dir?se=2020-09-29&sp=rawdl&spr=https&sv=2018-11-09&sr=c&skoid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&sktid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&skt=2020-09-24T13%3A06%3A15Z&ske=2020-09-29T00%3A00%3A00Z&sks=b&skv=2018-11-09&sig=REDACTED?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.3.3&x-ms-date=Thu, 24 Sep 2020 13:08:19 GMT&x-ms-version=2018-11-09&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : c6304b9d-801e-004b-6273-922f22000000
Sep 24 13:08:46 AZRVM1 blobfuse[60109]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 120: azs_getattr called with path = /
Sep 24 13:08:46 AZRVM1 blobfuse[60109]: Function azs_statfs, in file /home/vsts/work/1/s/blobfuse/directoryapis.cpp, line 258: azs_statfs called with path = /.
Sep 24 13:08:46 AZRVM1 blobfuse[60109]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 120: azs_getattr called with path = /`

**Comment by vibhansa-msft** [comment]
Kindly share your config details and the command line options you have used to mount.

**Comment by NaraVen** [comment]
@TheMP , it appears from the error that your mount command does not have --use-adls=true. I could repro the above error only when I skipped this mount option.

**Comment by NaraVen** [comment]
> Thank you for the reply, as stated I also tried with accountName, accountKey and containerName I suppose this should be sufficient?
@vervynckt , vibhansa was telling that ADLS Gen2 itself is supported only from 1.3.1 and after.  1.2.1 did not have adls integrated in it.

**Comment by TheMP** [comment]
> @TheMP , it appears from the error that your mount command does not have --use-adls=true, could you also make sure the config file has accountType adls? I could repro the above error only when I skipped this mount option.

Hi @NaraVen - you were right, many thanks for your help and sorry for the noise under this issue.
