### ISSUE TITLE
Need a stable Blobfuse version for RHEL 7.5

### ISSUE THREAD

**Issue by Rajan3542** [Azure/azure-storage-fuse#491]
### Which version of the blobfuse was used?
Blobfuse 1.0.2

### Which OS (please include version) are you using?
Red Hat enterprise Linux server v7.5

### What problem was encountered?
Need to know which Blobfuse version prior to v1.3.2 is a working and stable version because we tried to use v1.3.2, 1.3.3 and even 1.3.4 but all these versions are causing issues in our system reported in Issue #484 so we need to know which standard/stable Blobfuse version can be used for RHEL 7.5. If we get as RPM it would be really helpful to address our issue.

Also please note, at this moment, we can't upgrade our OS due to organisation level decisions and we need to have a stable Blobfuse in our system as soon as possible. 

Is there anyway to have a newer Blobfuse code in Microsoft repository because currently only version 1.0.2 is available there. 

### Have you found a mitigation/solution?
Not applicable.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Not applicable.

### If relevant, please share your mount command.
Not applicable.

**Comment by NaraVen** [comment]
The latest release blobfuse 1.3.4 for RHEL 7.5 can be found here. https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux
