### ISSUE TITLE
blobfuse with immutable blob storage access policy results in 0 byte files in the blob

### ISSUE THREAD

**Issue by hphuhtin** [Azure/azure-storage-fuse#495]
### Which version of the blobfuse was used?
1.3.4 (updated as per suggestion)

### Which OS (please include version) are you using?
Ubuntu 18.04.05 LTS

### What problem was encountered?
After enabling an immutable blob storage-type access policy (time-based, append allowed) on the blob container, files written via the blobfuse-mounted blob are all 0 bytes long. Also, on input/output error is displayed in the shell. Apparently WORM is not compatible with blobfuse. However it would be quite useful if it was.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No lines seem to relate

### If relevant, please share your mount command.
blobfuse /mnt/wormtest1 --config-file=/root/fuse_connection.cfg --tmp-path=/logs/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
�

**Comment by hphuhtin** [comment]
Updated to 1.3.4. Same behaviour. File creation causes an error, see below. After creation the file is shown locally with data despise the error, but in the Azure container there is just an empty file. The WORM policy should close file 30 seconds after the write lock has been closed, and also allow some sort of appending, but I'm not even trying to append yet. 

For reference, tmp-path I have tried both on xfs and ext4 filesystems.

root@host:/mnt/wormtest1# ls -la > testfile2.txt
ls: write error: Input/output error
root@host:/mnt/wormtest1# touch testfile3.txt
touch: failed to close 'testfile3.txt': Input/output error
root@host:/mnt/wormtest1# ls -l testfile2.txt
-rwxrwx--- 1 root root 769 Oct  2 08:29 testfile2.txt

**Comment by NaraVen** [comment]
I tested with WORM policy - time retention and let me share what I am seeing.
1) Append blobs are not supported in blobfuse.
Blobfuse only creates block blobs at this time. "x-ms-blob-type: BlockBlob" is the default when a blob is created.  
2) cp commands succeed and upload all the bits to blob, so you could try this as an alternate.
3) Editing any file including new files fails so new files are uploaded as zero bytes. The reason for this is As per the WORM policy blockblobs cannot be edited so it is in fact adhering to the WORM policy.

We cannot support Append blobs at this time , I will add an enhancement tag to this issue and add support later no ETA at this time however.

**Comment by hphuhtin** [comment]
Thank you for the quick investigation. So blobfuse would first create the file and the edit it always? Then I agree, WORM will not work.

**Comment by NaraVen** [comment]
yes blobfuse creates the file first.

**Comment by hphuhtin** [comment]
It seems to work with copying the files over (instead of redirecting STDIO to create files like I did before). Thank you for your help 👍
