### ISSUE TITLE
Blobfuse - Permissions problem in Linux

### ISSUE THREAD

**Issue by anudeepsista** [Azure/azure-storage-fuse#496]
### Which version of the blobfuse was used?
blobfuse 1.0.2-1

### Which OS (please include version) are you using?
RHEL 7.8

### What problem was encountered?
I am using the option user_allow_other in /etc/fuse.conf file while mounting the blob on linux system. But unable to change the directory permissions on blobstorage from linux. 
1. Is there any way to change the permissions of container from linux system using chmod, chown, etc commands ?
2. Is there any way to provide access based on linux secondary group for Blob containers?

### Have you found a mitigation/solution?
No. 

### If relevant, please share your mount command.
blobfuse /data/blob/sastech --tmp-path=/mnt/resource/sastech -o allow_other -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --container-name=sas-tech --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120

**Comment by vibhansa-msft** [comment]
Blobfuse does support 'chmod' but that functionality is available only on ADLS accounts. On block blob accounts we do not support these features.

**Comment by NaraVen** [comment]
For changing permissions you will need to use an ADLS storage account aka Hierarchical namespace enabled. When you use ADLS , you have to set the accountType to adls in the config file and use the commandline param --use-adls=true

**Comment by vibhansa-msft** [comment]
As you are using '-o allow_other' all users will have access to your mounted container. Secondary group is unable to access with this option in place ?

**Comment by anudeepsista** [comment]
> 
> 
> As you are using '-o allow_other' all users will have access to your mounted container. Secondary group is unable to access with this option in place ?

Hi Vibhansa-msft,
I don't know how to use the group option, if you are aware, could you please let me know how to use group option while mounting

**Comment by vibhansa-msft** [comment]
Fuse has two options "allow_root" and "allow_other". There is no option to allow only a selective user or group to have access to mounted path, as per my knowledge. When 'allow_other' is used, blobfuse defaults the file/dir permissions to 0777 so others shall be able to access any file or directory.

**Comment by vibhansa-msft** [comment]
Closing this issue as fuse does not have any option to allow a specific user or group.

**Comment by ArunPeri007** [comment]
Hi  @vibhansa-msft 

   We are encountering the same issue with " blobfuse defaults the file/dir permissions to 0777 so others shall be able to access any file or directory."
  This 777 allows anyone to remove files from Linux directory. Is there an option to provided restricted access on the mount,  based on Linux group?.
 
Our Linux Machine is not integerated with Windows Active Directory, so access on mount to be provided based on Linux group privileges. In production environment , having 777 privilege on the VM is a problem as there is a chance of accidental deletion of files due to FULL permission.

Thanks
Arun

**Comment by vibhansa-msft** [comment]
From blobfuse end we can not control this however fuse has its way for user to control it. “-o umask=0003 -o default_permissions” you can add this additional cli options to your mount command. Here 'umask' value shall be inverse of what permissions you want.  For .e.g. here umask=003 means default permission will be "774"

**Comment by ranieuwe** [comment]
It took me a while to figure this out: 
> Here 'umask' value shall be inverse of what permissions you want." 

Can we document this somewhere? I couldn't find it anywhere in the blobfuse documentation. Thank you @vibhansa-msft

**Comment by Ankur-Srivastava-Cloudtechizone** [comment]
Hi Vibhansa,

We are using Blobfuse2 to mount a storage container on an RHEL 8.2 server. The mount operation is performed using a YAML configuration file with the following command: 

sudo blobfuse2 mount /hhome/appdata2 --config-file=/var/fuse_connection.yaml

The customer has requested that each user should only have access to their own data and not be able to view or access data belonging to other users. Could you please provide guidance on how to configure Blobfuse2 or set appropriate permissions to achieve this?

**Comment by vibhansa-msft** [comment]
This kind of control is not possible via Blobfuse directly. You have two options here:
1. Each user has their own directory and while mounting you can just mount their specific directory for them
2. Have different spn/mis assigned to each user and mount with their auth for them. This way if they try to touch someone else data they get auth failure.

**Comment by Ankur-Srivastava-Cloudtechizone** [comment]
Thank you, Vibhansa, for your guidance.

Could you please let us know if there is any documentation available that includes detailed commands and steps for support?

Looking forward to your assistance.

**Comment by vibhansa-msft** [comment]
Our README covers most of it and there is public documentation on Microsoft learn portal as well which can be found [here](https://learn.microsoft.com/en-us/azure/storage/blobs/blobfuse2-what-is). If you have any specific question me and my team can help with that.

**Comment by Ankur-Srivastava-Cloudtechizone** [comment]
I will go through your documentation. thanks a lot
