### ISSUE TITLE
unable to mount using authType MSI

### ISSUE THREAD

**Issue by geloua** [Azure/azure-storage-fuse#497]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Red Hat Enterprise Linux Server release 7.8

### What problem was encountered?
receive the error message below:
Unable to start blobfuse. Exactly one of Account Key and SAS token must be specified in the config file, and the other line should be dele
ted.

I'm able to mount only when using Storage Access Key,  but need to use VM MSI only

### Have you found a mitigation/solution?
no

### If relevant, please share your mount command.

blobfuse ~/data-staging-mis  --tmp-path=/mnt/resource/data-staging-msi-tmp  -o attr_timeout=240 -o en
try_timeout=240 -o negative_timeout=120  --config-file=blobfuse/connection-staging-msi.cfg  --use-adls=true  --log-level=LOG_DEBUG --file-
cache-timeout-in-seconds=120

==cat blobfuse/connection-staging-msi.cfg
accountName mystorageaccount9999
authType MSI
containerName data-staging
accountType adls
identityClientId XXXXXXXXXXXXXXXXX

**Comment by vibhansa-msft** [comment]
'accountType adls' and 'authType MSI' are not supported in  version 1.0.2. Kindly upgrade to our latest version 1.3.4. 
You can find RHEL 7.8 rpm at below link.

https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux

**Comment by vibhansa-msft** [comment]
Feel free to re-open if issue persists with latest version.
