### ISSUE TITLE
Misconfiguration in Packages repo rpm for SLES 15

### ISSUE THREAD

**Issue by Mangaleshwar** [Azure/azure-storage-fuse#499]
### Which version of the blobfuse was used? 
This is related to microsoft packages repo where blobfuse is available
packages-microsoft-prod-1.0-1.noarch

### Which OS (please include version) are you using?
SLES 15 SP1

### What problem was encountered?
Packages repo rpm in SLES 15 creates repo config file under /etc/yum.repos.d
But SUSE uses zypper and hence the path should be /etc/zypp/repos.d

Troubleshooting:
sles15sp1:~ # wget https://packages.microsoft.com/config/**sles/15**/packages-microsoft-prod.rpm

sles15sp1:~ # rpm -ql packages-microsoft-prod.rpm
/etc/**yum.repos.d**/microsoft-prod.repo

### Have you found a mitigation/solution?
cp -p /etc/yum.repos.d /etc/zypp/repos.d
zypper ref
Then we will be able to install blobfuse in SLES 15

### Ask:
Please configure the package repo rpm to create repo config file under /etc/zypp/repos.d for SLES VMs

**Comment by johanburati** [comment]
Looks more like an issue with the **packages-microsoft.prod.rpm** than **blobfuse**, @asinn826 any idea who manage this package ?

The package for SLES15 create the repo in the wrong dir:
```
$ rpm -ql https://packages.microsoft.com/config/sles/15/packages-microsoft-prod.rpm
/etc/yum.repos.d/microsoft-prod.repo
```

The package for SLES12 create it in the correct one:
```
$ rpm -ql https://packages.microsoft.com/config/sles/12/packages-microsoft-prod.rpm
/etc/pki/rpm-gpg/RPM-GPG-KEY-microsoft-prod
/etc/zypp/repos.d/microsoft-prod.repo
```

**Comment by NaraVen** [comment]
you can download rpm for SUSE at https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux
@johanburati ping me offline for packages repo owner. narven (alias for offline ping )

**Comment by johanburati** [comment]
Just for info for those interested, I am pushing internally to have the packages repo corrected !

**Comment by johanburati** [comment]
I've fixed the package, if you want you can grab it from my storage and then use zypper to install bloblfuse:
 
```
sudo rpm -Uvh https://fdisk.blob.core.windows.net/pub/sles15/packages-microsoft-prod.rpm
sudo zypper install blobfuse
```

**Comment by NaraVen** [comment]
Could you please pull the latest blobfuse-1.3.6 from SLES 15 . It is published to packages.microsoft.com
