### ISSUE TITLE
problems compiling

### ISSUE THREAD

**Issue by astateofmind01** [Azure/azure-storage-fuse#503]
### Which version of the blobfuse was used?

Latest, git cloned

### Which OS (please include version) are you using?

Oracle Linux 6.10

### What problem was encountered?

Compiling

### Have you found a mitigation/solution?

Yes:

Install scl-utils and devtoolset-3 to add support for c++11

And the error:

[  2%] Building CXX object CMakeFiles/azure-storage-lite.dir/src/logging.cpp.o
In file included from /root/azure-storage-fuse/cpplite/src/logging.cpp:1:
/root/azure-storage-fuse/cpplite/include/logging.h:18: error: ‘constexpr’ does not name a type
/root/azure-storage-fuse/cpplite/include/logging.h: In static member function ‘static void azure::storage_lite::logger::log(azure::storage_lite::log_level, const std::string&, Args ...)’:
/root/azure-storage-fuse/cpplite/include/logging.h:47: error: ‘nullptr’ was not declared in this scope
/root/azure-storage-fuse/cpplite/include/logging.h:51: error: ‘MAX_LOG_LENGTH’ was not declared in this scope
gmake[2]: *** [CMakeFiles/azure-storage-lite.dir/src/logging.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/azure-storage-lite.dir/all] Error 2
gmake: *** [all] Error 2
************************ CPPLite build Failed *****************************

**Comment by astateofmind01** [comment]
But now i get in another problem:

Status 0. Another post stated that upgrading curl will solve it. It didn't :(

**Comment by vibhansa-msft** [comment]
@astateofmind01 : So if I got it correctly the steps are 
- Install scl-utils and devtoolset-3 to add support for c++11
- upgrade cURL to higher version
- re-compile blobfuse

Post this things are working fine or you are still stuck with the compilation.
We publish RPM for Oracle 8.1 as of now. Will investigate if we can do for Oracle 6.10 as well.

**Comment by astateofmind01** [comment]
> @astateofmind01 : So if I got it correctly the steps are
> 
> * Install scl-utils and devtoolset-3 to add support for c++11
> * upgrade cURL to higher version
> * re-compile blobfuse
> 
> Post this things are working fine or you are still stuck with the compilation.
> We publish RPM for Oracle 8.1 as of now. Will investigate if we can do for Oracle 6.10 as well.

Correct. 

curl can be upgraded first.
I followed the instructions on this link for c++11 support in oracle 6:
https://blogs.oracle.com/opal/getting-a-c11-compiler-for-node-4,-5-and-6-on-oracle-linux-6

Post this things everything works fine (so far at least).

Before upgrading curl it would successfully compile  but will not function correct (would not be able to access the container).

**Comment by vibhansa-msft** [comment]
Closing this issue report as things are working fine at your level. If you face any issue with functionality you can open another one.
We will put Oracle 6 rpm support to our backlog.
