### ISSUE TITLE
Cannot mount Azure blob on CentOS7

### ISSUE THREAD

**Issue by mfata972** [Azure/azure-storage-fuse#504]
### Which version of the blobfuse was used?
1.3.4

### Which OS (please include version) are you using?
CentOS 7 release is 5.800000, Kernel version is 5.8.7-1.el7.elrepo.x86_64

### What problem was encountered?
After OS kernel upgrade I was unable to mount the blob container.
Before kernel upgrade I was running Blobfuse installed from Microsoft distribution (https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm - an old version indeed), installed and configured following their installation and configuration guide (https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux#configure-the-microsoft-package-repository).

I'm using the blob container to store archives from a Graylog node.

### Have you found a mitigation/solution?
No. Tried removing/reinstalling package from Microsoft source, re-configuring everything from scratch, but no solution.

Then, I found this (https://github.com/Azure/azure-storage-fuse/issues/395) and this (https://github.com/Azure/azure-storage-fuse/issues/428) and I decided to give a try installing latest Blobfuse version by building it from source and configuring it again from scratch. Still no solution.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
***NOTE: SACUSTOMNAME replaces the real SA name.
***NOTE: ADMIN replaces the real user name.

Below from /var/log/blobfuse.log:
----------------------------------------------------------------------------------------------------------------
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Auth type set as key
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Account name found
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Account Key found
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Container name found
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Setting logging level to : LOG_DEBUG
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: release is 5.800000, Kernel version is 5.8.7-1.el7.elrepo.x86_64
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Function ensure_files_directory_exists_in_cache, in file /home/ADMIN/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /mnt.
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Function ensure_files_directory_exists_in_cache, in file /home/ADMIN/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /mnt/blobfusetmp.
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Function ensure_files_directory_exists_in_cache, in file /home/ADMIN/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /mnt/blobfusetmp/root.
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Initializing blobfuse using BlockBlob
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Setup storage client
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Authenticating using account key
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: ==> REQUEST/RESPONSE :: GET https://SACUSTOMNAME.blob.core.windows.net/graylog-archives?comp=list&delimiter=/&include=metadata&maxresults=1&restype=container?&User-Agent=azure-storage-fuse/1.3.4&x-ms-date=Thu, 08 Oct 2020 15:15:28 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 200 :: REQ ID : 07e3f0b0-801e-00a0-2b85-9d96a2000000
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: Successfully Authenticated!
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: azs_init ran
Oct  8 15:16:39 be-emgraylog001 blobfuse[9277]: Function azs_statfs, in file /home/ADMIN/azure-storage-fuse/blobfuse/directoryapis.cpp, line 258: azs_statfs called with path = /.
Oct  8 15:16:39 be-emgraylog001 blobfuse[9277]: Function azs_getattr, in file /home/ADMIN/azure-storage-fuse/blobfuse/utilities.cpp, line 120: azs_getattr called with path = /
Oct  8 15:16:44 be-emgraylog001 blobfuse[9277]: Function azs_statfs, in file /home/ADMIN/azure-storage-fuse/blobfuse/directoryapis.cpp, line 258: azs_statfs called with path = /.
Oct  8 15:16:44 be-emgraylog001 blobfuse[9277]: Function azs_getattr, in file /home/ADMIN/azure-storage-fuse/blobfuse/utilities.cpp, line 120: azs_getattr called with path = /
Oct  8 15:17:16 be-emgraylog001 blobfuse[9277]: Function azs_destroy, in file /home/ADMIN/azure-storage-fuse/blobfuse/utilities.cpp, line 459: azs_destroy called.
----------------------------------------------------------------------------------------------------------------

Below from /var/log/blobfuse-rest.log
----------------------------------------------------------------------------------------------------------------
Oct  8 15:15:28 be-emgraylog001 blobfuse[9277]: ==> REQUEST/RESPONSE :: GET https://SACUSTOMNAME.blob.core.windows.net/graylog-archives?comp=list&delimiter=/&include=metadata&maxresults=1&restype=container?&User-Agent=azure-storage-fuse/1.3.4&x-ms-date=Thu, 08 Oct 2020 15:15:28 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 200 :: REQ ID : 07e3f0b0-801e-00a0-2b85-9d96a2000000
----------------------------------------------------------------------------------------------------------------

The following from -d option:
----------------------------------------------------------------------------------------------------------------
FUSE library version: 2.9.2
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.31
flags=0x03fffffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000031
   max_readahead=0x00400000
   max_write=0x00020000
   max_background=128
   congestion_threshold=96
   unique: 2, success, outsize: 40

unique: 4, opcode: GETXATTR (22), nodeid: 1, insize: 68, pid: 969
getxattr / security.capability 24
   unique: 4, error: -38 (Function not implemented), outsize: 16
unique: 6, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 969
statfs /
   unique: 6, success, outsize: 96
unique: 8, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 969
statfs /
   unique: 8, success, outsize: 96
----------------------------------------------------------------------------------------------------------------

Storage Account name DNS resolution is OK.
Connection and authentication seems ok from the log, but no successful mount.

### If relevant, please share your mount command.
sudo blobfuse /opt/fscontainer --tmp-path=/mnt/blobfusetmp --config-file=/home/ADMIN/fuse_connection.cfg -o allow_other -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG -d

fuse_connection.cfg:
authType Key
accountName SACUSTOMNAME
accountKey ***********
containerName graylog-archives

Thank you
Regards

Michele

**Comment by NaraVen** [comment]
Can you upgrade to CentOS and take our latest rpm from here. 1.3.4 is the latest so far and it is here. https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux

**Comment by mfata972** [comment]
Hi, you mean 1.3.4 (the ver I'm running) is not expected to run on CentOS7 in any case?

**Comment by NaraVen** [comment]
We haven't tested 1.3.4 on CentOS 7 . We have tested it on CentOS 8 though so if you can upgrade to CentOS 8, you mounting issue will be resolved.

**Comment by mfata972** [comment]
hi, so testing latest version 1.3.5 on CentOS8 I got: error: Failed dependencies: libboost_filesystem.so.1.66.0()(64bit) is needed by blobfuse-1.3.5-1.el8.x86_64
then, found this: https://github.com/Azure/azure-storage-fuse/issues/381
so,now what,need to build in any case?

**Comment by vibhansa-msft** [comment]
This is due to missing dependencies. You can install libboost using below command. 
"sudo yum install boost-devel -y"

If you get more such errors after libboost installation, you can use below command to install other dependencies :
"sudo yum install curl-devel gnutls-devel libuuid-devel boost-devel libgcrypt-devel fuse-devel -y"

**Comment by NaraVen** [comment]
@mfata972 , if you follow the below steps and isntall Curl 7.54 you should be able to get blobfuse mounted.
yum install gnutls gnutls-devel libssh2 libssh2-devel
yum install gcc
wget https://curl.haxx.se/download/curl-7.54.0.tar.gz
sudo tar -xvzf curl-7.54.0.tar.gz && cd curl-7.54.0/
sudo ./configure --with-gnutls --with-libssh2 --prefix=/usr/local
make
make install
sudo rm /usr/bin/curl
sudo ln -s /usr/local/bin/curl /usr/bin/curl

**Comment by mfata972** [comment]
Ok, i'll give it a try. Otherwise I'll need to move to CentOS8 (where it's working), but it's a huge work. Thank you

**Comment by NaraVen** [comment]
1.3.6 will be released next week. In 1.3.6 we have fixed the root issue itself. If you want to wait for a week you can pull that.

**Comment by vibhansa-msft** [comment]
1.3.6 is now available. Kindly download the latest rpm from below link and upgrade.
https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.6
