### ISSUE TITLE
blobfuse downloading files from azure into local cache 

### ISSUE THREAD

**Issue by kthangar** [Azure/azure-storage-fuse#506]
### Which version of the blobfuse was used?
rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
blobfuse-1.0.2-1.x86_64

### Which OS (please include version) are you using?
CentOS Linux release 7.8.2003 (Core)
3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### What problem was encountered?
trying to use blobfuse to backup new files daily to azure storage.
1. mount blobfuse folder
2. rsync files to blobfuse folder
3. fusermount -u blobfuse folder

After few minutes blobfuse is downloading files from azure storage including previous days and causing high  'data transfer out'/bandwidth cost. This setup is for oneway transfer to azure, not sure which process triggering to downloads.
Daily uploads takes longer and longer, because of downloads which is also continuing after finishing rsync.
Is that expected behavior or is there any other config which prevents downloads? 
### Have you found a mitigation/solution?
NO,  tried few blobfuse options, including --file-cache-timeout-in-seconds=0. 

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
/var/log/messages:
Oct  8 00:01:46 san-xxx blobfuse[13476]: Successfully uploaded file  date_of_record=2020-10-06/part-00217-xxx to blob 2020/date_of_record=2020-10-06/part-00217-xxx
Oct  8 00:01:46 san-xxx blobfuse[13476]: Successfully created file /2020/date_of_record=2020-10-06/part-00049-xxx in file cache.
Oct  8 00:01:47 san-xxx blobfuse[13476]: Successfully downloaded blob 2020/date_of_record=2020-10-01/part-00009-xxx into file cache as /blobfuse_cache/root/2020/date_of_record=2020-10-01/part-00009-xxx

### If relevant, please share your mount command.
fusermount -u /home/svc_user/app-uswest2

/bin/blobfuse /home/svc_user/app-uswest2 --tmp-path=/blobfuse_cache -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_root --config-file=/home/svc_user/config/fuse_connection.cfg --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=0

**Comment by vibhansa-msft** [comment]
'file-cache-timeout-in-seconds' controls when to delete the cached files, it does not stop the download.
Also Blobfuse does not download any file unless the user application send an open request for it. As of now there is no option to just block the download part. You need to explore 'rsync' command options if there is a way.

**Comment by NaraVen** [comment]
could you please share your rsync command. It maybe touching the files prompting a download. I recommend the -u option.

**Comment by kthangar** [comment]
This is the command i am using :
find $SDIR -type f -mtime -$DAYS -exec rsync --inplace -acPR {} $DDIR \;

we need to keep these options
--inplace to avoid multiple version of files in storage account if you execute rsync second time.
-R(relative) to keep directory structure in storage account
-r(recursive)

After reviewing the commands i dont see any benefits keeping below options 

-a (rlptgoD) -p permission, -t modification time, -g group, -o owner, -D devices
-c checksum
-P partial

Is there anyway to capture the open requests from client side? more logging ? 

Please let me know if you have any other recommendation for  rsync with blobfuse
thank you

**Comment by kthangar** [comment]
i am using this now which works well for us :     rsync --inplace -uR --info=all
removing '-a' option reduced small part of downloads from azure, but most of the downloads are triggered by  our security tool which was running middle of rsync jobs and  scanning the directory.  
Problem solved.  closing this.
