### ISSUE TITLE
the mounted blob-storage seems to be dependent on the ubuntu server own filesystem size.

### ISSUE THREAD

**Issue by magnuszetterberg** [Azure/azure-storage-fuse#510]
### Which version of the blobfuse was used?
Latest as of 2020-10-05(sorry, dont know the exact version)

### Which OS (please include version) are you using?
ubuntu 20.04

### What problem was encountered?
Background:
I use nextcloud to easily share and store files to and from collegues. This nextcloud runs in docker, which have the blob mount mapped as a volume into the docker container running nextcloud. Thus when (through nextcloud), I place files into the mount ,it indicates that the filesystem is getting full(even though I use the blobstorage mount as a destination for my files coming into the nexcloud environment)

When login onto the server hosting the docker, and running 'df -h' in the console on the server(not the docker container) I get this result below.
![image](https://user-images.githubusercontent.com/6301904/95963508-0e74e080-0e08-11eb-8d33-204389920e5b.png)

This tells me that the mount somehow is dependent on the actual filesystem on the server, and thus indicates for the nextcloud docker container that the filesystem is full when it actually is not.

### Have you found a mitigation/solution?
I have tried to look at the other mount options which would remedy the limitation, but I have not found a way around this.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No, the actual mounting and working with the mount seems to work, but only with the problem that the servers filesystem size seems to be mapped to mounted blobstorage, thus indicating to the server that it's full.

### If relevant, please share your mount command.
cat /etc/rc.local
#!/bin/sh -e

sudo -u www-data blobfuse /home/ubuntu/azure_blob_storage --tmp-path=/tmp -o uid=33 -o gid=33  -o allow_other -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/blobfuse/blob.cfg  --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120

**Comment by vibhansa-msft** [comment]
Your observation is correct. Blobfuse does return back stats of actual file system.
As your mount path and tmp path reside on actual "/" mount, blobfuse returns back stats of the same.

**Comment by magnuszetterberg** [comment]
Yup, thank you for the confirmation on my observation. 
I noticed this behavior my self after writing the issue here, by mounting the --tmp-path on a different drive, and the "df -h" showed that it now had a new size on the file-system matching the size of the new drive.

**Comment by snorlaxe** [comment]
I need to install nextcloud on azure container and store in blob storage can you send me a dockerfile you will save my life best regarde.

**Comment by vibhansa-msft** [comment]
We do not have any sample docker file as such with us.
@andyzhangx can you share if you have one.

**Comment by andyzhangx** [comment]
> I need to install nextcloud on azure container and store in blob storage can you send me a dockerfile you will save my life best regarde.

@snorlaxe try this example: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/pkg/blobplugin/Dockerfile
That Dockerfile could build blob csi driver which could run on a Kubernetes cluster.
