### ISSUE TITLE
"Transport endpoint is not connected" error on parallel writes

### ISSUE THREAD

**Issue by calebrob6** [Azure/azure-storage-fuse#511]
### Which version of the blobfuse was used?
1.2.4

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
I have a script that writes ~100MB of data to files on the blobfuse mount. This happens roughly in parallel for batches of 64 files at a time. Eventually, this results "Transport endpoint is not connected" error and the mount locking up.

The machine is a large VM with 64 VCPUs and 252GB of RAM. The temporary space (`/path/to/temp`)  is 1.5TB disk and does not fill up while the above script runs.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
There are many entries in the following format:
```
blobfuse[5893]: Unknown failure in list_blobs_hierarchial.  ex.what() = std::bad_alloc, container = CONTAINER_HIDDEN, prefix = FILENAME_HIDDEN.pass.
```

### If relevant, please share your mount command.
blobfuse /path/to/mount --tmp-path=/path/to/temp --container-name=CONTAINER_HIDDEN -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

**Comment by vibhansa-msft** [comment]
Versions prior to 1.3.1 had intermittent "Transport Disconnected" issue. Can you try the latest 1.3.4 version. Its not updated in the packages yet but you can take the .deb file from below location. Let us know if 1.3.4 solves your problem.
https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.4-Linux

**Comment by calebrob6** [comment]
Yep I think that fixed it, thanks!

**Comment by vibhansa-msft** [comment]
Closing this as issue is not observed with latest version.
