### ISSUE TITLE
persistent blobfuse temp directory

### ISSUE THREAD

**Issue by lbabay** [Azure/azure-storage-fuse#515]
### Which version of the blobfuse was used?
1.4.2

### Which OS (please include version) are you using?
ubuntu server 18.04 

### What problem was encountered?
if I power down my VM or restart it, the temp path is gone as well as the connection to my storage account, I know its because its an ephemeral disk but is there a way that I can make this persistent? so I can restart and powerdown VM and not have to set the temp path everytime?

### Have you found a mitigation/solution?
no

**Comment by vibhansa-msft** [comment]
This is not an issue from Blobfuse end, rather due to ephemeral disk. From blobfuse side we do not create the temp directory structure. You can look for systemd/rules.d script for creating the required structure when the ephemeral disk is mounted.

**Comment by vibhansa-msft** [comment]
Closing as its not an issue in blobfuse.
