### ISSUE TITLE
Mount is successful but failed to run git clone command : Function not implemented

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-storage-fuse#516]
### Which version of the blobfuse was used?
1.3.5

### Which OS (please include version) are you using?
Ubuntu in Azure

### What problem was encountered?

One customer used blob fuse to mount a storage account to his linux box(Ubuntu VM in azure), the mount operation was successful. When he tried to use git clone command to download files to the linux folder and met an error.

    
error: chmod on /presistentdata/data/mvh/test_git/AAD/.git/config.lock failed: function not implemented
   
![image](https://user-images.githubusercontent.com/71274085/96670322-a129f800-1391-11eb-9d87-b04bda01c297.png)

Again cx tried to run chmod command inside the blob folder

chmod 756 test1
chmod: changing permissions of 'test1': Function not implemented

chmod outside of blob folder 
sudo chmod 766 packages-microsoft-prod.deb – Working Fine

### Have you found a mitigation/solution?
No, I setup an environment and cannot reproduce.

**Comment by NaraVen** [comment]
for git clone to work you need an adls account. Do you have --use-adls=true in the command line or accountType=adls in the config. Also, you will need a storage account with HNS enabled. HNS stands for Hierarchical namespace which is the same as adls for azure

**Comment by yangchengs** [comment]
Cx is using ADLS Gen 1 and I tried to use ADLS GEN 1 account and there is no problem with git clone in the mount folder.

**Comment by NaraVen** [comment]
Gen 1 did not have container support so all the blob APIs worked. For gen2 it will check for permissions so it has to go through adls endpoint, in order go thru that you ahve to specify --use-adls=true in the command line. Did you specify that?

**Comment by yangchengs** [comment]
I did not specify --use-adls=True but I use a connection.cfg

accountName yangshendls021
# Please provide either an account key or a SAS token, and delete the other line.
accountKey 7AdeW9xkfPNfgkU5JJgFK/XOcfVV0CdHaXXXXXXXXXXXXXXXXXXXXXXXX
authType Key
containerName mount1

I tried ADLS Gen1/ADLS Gen 2  with HNS enabled/ADLS Gen 2 with HNS disabled, all are working
I used the following command to mount folder
blobfuse /home/jesse/to6 --tmp-path=/mnt/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/home/jesse/connection.cfg --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 --use-adls=true

Cx is using ADSL Gen 1 account, I haven't ask him to try ADLS Gen 2 yet.

**Comment by NaraVen** [comment]
I understand everything is working now right after specifying --use-adls=true? Can we close the issue?

**Comment by yangchengs** [comment]
Nara, it is working in my environment but NOT for cx, and I did not specify -use-adls=true (I have corrected previous post), any suggestion on cx's issue?

**Comment by NaraVen** [comment]
Ok So the real issue is that it is not working for ADLS Gen 1 in the client machine but it is working for you in your machine?

**Comment by yangchengs** [comment]
yes, we are both on Ubuntu VM in Azure.

**Comment by NaraVen** [comment]
I tried it now and it works. This is not a blobfuse problem. It is a git permission problem. I read the git error at the bottom of the screenshot you have attached. your client probably needs a username and pataccesstoken for that repo. It is not an open repo.

**Comment by yangchengs** [comment]
I will ask cx to try git clone in a different folder, but I asked him to try chmod or chown command only, it returned the same error.

chmod 756 test1
chmod: changing permissions of 'test1': Function not implemented

**Comment by NaraVen** [comment]
there is no permissions on the git repo your cx is git cloning from. you can test by asking the Cx to our repo "git clone https://www.github.com/Azure/azure-storage-fuse"

**Comment by yangchengs** [comment]
Cx said that he can use git clone outside the mount folder.

**Comment by NaraVen** [comment]
If they can use it outside the mount folder and they are not getting the "fatal: cannot read from remote repository" error then they have something wrong in mounting. Unless you share the Cx's mount command ( not yours) we cannot troubleshoot anything.

**Comment by yangchengs** [comment]
Provided by cx

Standard_D14_V2, 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

blobfuse command with parameters.

sudo blobfuse /data/persistantdata --tmp-path=/mnt/ramdisk/blobfusetmp  --config-file=/mnt/fuse_amesaiscpblob.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o nonempty -o allow_other

**Comment by NaraVen** [comment]
The mount command is correct. The repo permissions is an issue . Can the Cx try out our open repo as I asked earlier?

**Comment by yangchengs** [comment]
will ask cx to do the test and get back to you.

**Comment by yangchengs** [comment]
The issue is now auto-fixed after the cluster is rebuilt.
