### ISSUE TITLE
URL encoded filenames are automatically decoded before writing to remote mount

### ISSUE THREAD

**Issue by AvivAvital2** [Azure/azure-storage-fuse#517]
### Which version of the blobfuse was used?
1.3.5

### Which OS (please include version) are you using?
Ubuntu 16.04.7 LTS

### What problem was encountered?
Writing files to a blobfuse mount while filename is encoded with URL encoding is written to remote directory with decoded name. 
I.e.
Writing a filename called `%282%29+class_history_by_item.log` to a mount will write a file called `(2)+class_history_by_item.log` at the remote path.

### Have you found a mitigation/solution?
In my humble opinion, splitting the URL by `/` and individually URL encoding each cell, will mitigate this.
For instance, a URL with `http://path_to_storage_account/%282%29+class_history_by_item.log` 
would be sent as `http://path_to_storage_account/%25282%2529%2Bclass_history_by_item.log`

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Reading such filenames from ADLS results in an error:
`ls: cannot access '%282%29+class_history_by_item.log': No such file or directory`

### If relevant, please share your mount command.
N/A

**Comment by AvivAvital2** [comment]
Hi @vibhansa-msft 
Thank you for taking the time to review and acknowledge the issue :)
We're currently in the process of integrating FUSE into our solution and the issue delays our progress.
As it would be optimal to have some "breathing room" to explore other alternatives, will it be OK to ask what is the expected time for the issue to be resolved?

Thanks again

**Comment by vibhansa-msft** [comment]
"splitting the URL by / and individually URL encoding each cell" : blobfuse calls REST api for every single operation done on the container and parsing the file names this way may create performance issues. We need to investigate this thoroughly before deciding on the solution. One question though, why the files names are URL encoded ?

**Comment by AvivAvital2** [comment]
Files reside on multiple systems, which requires an encoding of some sort. If we change the naming convention, we'll be losing support of these systems.

**Comment by AvivAvital2** [comment]
Hi @vibhansa-msft 
Any news?

**Comment by vibhansa-msft** [comment]
@AvivAvital2 : I have a potential fix for this and its under testing. This shall come in our next release in some time.

**Comment by AvivAvital2** [comment]
@vibhansa-msft I'd be more than happy to offer my help validating the fix.
Let me know if there's anything I can do.
Thanks

**Comment by vibhansa-msft** [comment]
@AvivAvital2 : Thanks for offering a helping hand. Will let you know once I am done with my testing.

**Comment by vibhansa-msft** [comment]
@AvivAvital2 : Fix for this has been merged into master. If you wish to try out your test case, you can pull the latest code and build. We will be releasing this as v1.3.6 shortly.

**Comment by AvivAvital2** [comment]
Thank you very much! :)

**Comment by vibhansa-msft** [comment]
File name encoding issues have been fixed in version 1.3.6. Kindly download upgraded version from below link. For ubuntu you can upgrade using apt-get as well.

https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.6

**Comment by AvivAvital2** [comment]
@vibhansa-msft Thanks for your help
Saw there was a handle to enable/disable the feature, and it is currently not in the Readme.
Does that mean you have enabled it by default?

**Comment by vibhansa-msft** [comment]
Yes we decided to remove as other customers were also having similar issue with file name encoding. Do let us know your test case works fine with 1.3.6

**Comment by AvivAvital2** [comment]
The fix works, thank you for taking the time for this.
Will also conduct several benchmarks to see there's no degradation, will update here once done

**Comment by AvivAvital2** [comment]
Noticed a ~10% drop in performance
If this seems more than intended let me know

**Comment by vibhansa-msft** [comment]
This is compared to which version ? Between 1.3.5 and 1.3.6 there have been very small fixes so shouldn't have impacted the performance.

**Comment by AvivAvital2** [comment]
This is between 1.3.5 and 1.3.6, yes.
Using Ubuntu 18.04 LTS and the following config:
```blobfuse --tmp-path=/mnt/blobfusetmp --config-file=/home/user/fuse_connection.cfg --file-cache-timeout-in-seconds=240 --no-symlinks=true -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other```
