### ISSUE TITLE
issue installing on rhel8

### ISSUE THREAD

**Issue by danherrom** [Azure/azure-storage-fuse#520]
### Which OS (please include version) are you using?
CIS Red Hat Enterprise Linux 8 Benchmark L1 from Azure marketplace

### What problem was encountered?
I am getting the following when installing the  latest blobfuse on rhel8

 Problem: conflicting requests
  - nothing provides libboost_filesystem-mt.so.1.53.0()(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libboost_system-mt.so.1.53.0()(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libboost_thread-mt.so.1.53.0()(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libgcrypt.so.11()(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libgcrypt.so.11(GCRYPT_1.2)(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libgnutls.so.28()(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libgnutls.so.28(GNUTLS_1_4)(64bit) needed by blobfuse-1.1.1-1.el7.x86_64
  - nothing provides libgnutls.so.28(GNUTLS_2_10)(64bit) needed by blobfuse-1.1.1-1.el7.x86_64

### Have you found a mitigation/solution?
no

**Comment by NaraVen** [comment]
1.1.1 is a really old version. Please upgrade to the latest which is 1.3.5
