### ISSUE TITLE
random download blob error

### ISSUE THREAD

**Issue by davidhendi** [Azure/azure-storage-fuse#522]
### Which version of the blobfuse was used?
blobfuse 1.2.1

### Which OS (please include version) are you using?
Linux version 5.3.0-1020-azure (buildd@lgw01-amd64-055) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #21~18.04.1-Ubuntu SMP Wed Apr 15 09:35:56 UTC 2020

### What problem was encountered?
i get random "FileNotFoundError: [Errno 2] No such file or directory:" I have made sure the files do exist and are not being modified during the call.

### Have you found a mitigation/solution?
no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Nov  6 05:36:18 314c41db6ef8477fa3d2fbe272053433000000 blobfuse[4360]: Unknown failure in download_blob_to_file.  ex.what() = std::bad_alloc, container = data, blob = sandbox/experiments/machine_learning/output/output_look_18075.pkl, destPath = /mnt/batch/tasks/fsmounts/datablobfusetmp/root/sandbox/experiments/machine_learning/output/output_look_18075.pkl.
Nov  6 05:36:18 314c41db6ef8477fa3d2fbe272053433000000 blobfuse[4360]: Failed to download blob into cache.  Blob name: sandbox/experiments/machine_learning/output/output_look_18075.pkl, file name = /mnt/batch/tasks/fsmounts/datablobfusetmp/root/sandbox/experiments/machine_learning/output/output_look_18075.pkl, storage errno = 1600.

### If relevant, please share your mount command.
new MountConfiguration(
                        new AzureBlobFileSystemConfiguration(
                            config.STORAGE_ACCOUNT_NAME,
                            "data",
                            "data",
                            AzureStorageAuthenticationKey.FromAccountKey(config.STORAGE_ACCOUNT_KEY)
                            , "--log-level=LOG_INFO"
                                                   ))

**Comment by vibhansa-msft** [comment]
Kindly upgrade to version 1.3.5 and retry your test case. You can get deb package from below link
https://github.com/Azure/azure-storage-fuse/releases

**Comment by davidhendi** [comment]
version 1.2.1 is the one automatically installed by azure when creating a pool. I don't see a way to specify the version number. is there a way to do this without having to manually install?

**Comment by vibhansa-msft** [comment]
Due to some technical challenge we are not able to publish our latest version to Microsoft Repos. Hence you can not get the latest version using apt-get or yum install. As pointed earlier in our "Release" section you can find .deb and .rpm files for all the latest version.

**Comment by vibhansa-msft** [comment]
@davidhendi : were you able to upgrade to 1.3.5 and try out your test case ?

**Comment by davidhendi** [comment]
yes, version 1.3.5 fix the issue. however it seems to much slower than 1.2.1. when i have time, i will run a test and update this thread.

**Comment by vibhansa-msft** [comment]
As original issue is fixed with 1.3.5, I am closing this issue. If you test figures out some other problem, you can open a new one.
