### ISSUE TITLE
Perform an Umount command without losing data in blob storage

### ISSUE THREAD

**Issue by alexislg-ov** [Azure/azure-storage-fuse#528]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Red Hat Enterprise Linux Server 7.9 (Linux 3.10.0-1160.el7.x86_64)

### What problem was encountered?
We want to umount the blob fuse mounting point created in the VM without losing data in the blob container.
Is the 'umount' command secure enough to do this; otherwise what reliable handling can be performed?

### Have you found a mitigation/solution?
Maybe remove the configuration file containing the secrets to cut the connection?

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No.

### If relevant, please share your mount command.
blobfuse /opt/adls_container --tmp-path=[]  --config-file=[] -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

**Comment by vibhansa-msft** [comment]
Blobfuse does not delete any data unless user asks it explicitly to do so. Unmount option is completly safe. You can use "fusermount -u <mount path>" to unmount.

**Comment by alexislg-ov** [comment]
Hello,

I can’t performan an Umount because the disk is busy:
_umount: /opt/adls_container: occupied target._

Is there another way?

**Comment by vibhansa-msft** [comment]
Are you trying to do unmount from the mounted directory itself. If there is any terminal/window working on the mounted directory then you need to exit from the mounted path first before unmount.

**Comment by alexislg-ov** [comment]
That was the problem.
Thanks for your help!
