### ISSUE TITLE
When mounted on Linux VM, the attached blob shows size less than the actual blob storage size, why it is only 252 GB as the size of blob is not defined

### ISSUE THREAD

**Issue by ujwalkasth** [Azure/azure-storage-fuse#535]
### Which OS (please include version) are you using?

cent os
### What problem was encountered?
today

### Have you found a mitigation/solution?
no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

no
### If relevant, please share your mount command.
df -hTP | grep -i blobFilesystem              Type      Size  Used Avail Use% Mounted on
blobfuse                                                                                   fuse      252G  2.1G  237G   1% /root/backup_azure

will it extend automatically when the data stored goes beyond 256 GB, or should we extend manually?

**Comment by ujwalkasth** [comment]
@vibhansa-msft Can you comment on this ?

**Comment by vibhansa-msft** [comment]
df command for mounted directory does not tell the total amount of data stored in your storage container, rather it just tells the disk usage where the temp directory resides i.e. your local disk or ramdisk. Temp directory in case of blobfuse is just a caching directory where files are cached for some time and then wiped out. Let me know if that answers your query,

**Comment by ujwalkasth** [comment]
Thanks a lot Vikas. So how can i get the total size of my azure storage mounted ? like how do i check the available storage size ? lets say i need to check the amount of space used and the total amount of space available in mounted blob storage.

**Comment by vibhansa-msft** [comment]
Sorry but blobfuse can not help in that. Blobfuse only mounts a container from your storage account. Azure Portal has some option for this. You can follow below link if it helps answering your query -
https://techcommunity.microsoft.com/t5/azure-paas-blog/calculate-the-size-capacity-of-storage-account-and-it-services/ba-p/1064046

**Comment by vibhansa-msft** [comment]
Closing this as 'df' output is as per expectation. Feel free to reach out to us for any further queries.
