### ISSUE TITLE
SLES 15 seems to be the minimum need for latest blobfuse 1.3.6, might need to be updated

### ISSUE THREAD

**Issue by vick-git** [Azure/azure-storage-fuse#538]
### Which version of the blobfuse was used?

1.3.6

### Which OS (please include version) are you using?

SUSE SLES 12

### What problem was encountered?

Unable to install blobfuse

### Have you found a mitigation/solution?
 
May be.

ASK: 

This documentation might need to be updated to say SLES 15.

https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation#option-2---build-from-source

SLES 15 seems to be the minimum need for latest blobfuse 1.3.6, might need to be updated. Please correct me if I am wrong.

**Comment by vibhansa-msft** [comment]
Can you share what kind of error you are facing while building.

**Comment by vibhansa-msft** [comment]
Kindly refer to updated wiki on how to build on SLES 11/12/15 instructions. Also you can try SLES 15 RPM on your SLES 12.

**Comment by vibhansa-msft** [comment]
Feel free to reopen the issue, if you face any issue with respect to installation or build on SLES 12.
