### ISSUE TITLE
Update documentation for SUSE 12 - Manual Build

### ISSUE THREAD

**Issue by mabicca** [Azure/azure-storage-fuse#539]
Hi Everyone,

The documentation here:
https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation#option-2---build-from-source

Might need an extra step for SUSE 12, if we execute the zypper command, a lot of packages will fail to install, this is the line:

```
# zypper install git cmake fuse-devel libcurl-devel gcc gcc-c++ gnutls-devel libgcrypt-devel fuse libuuid-devel boost-devel
```

You need to add an extra repository which sometimes is not enabled by default.

```
# SUSEConnect -p sle-sdk/12.4/x86_64
````
We might want to check for other versions , such as SUSE 15 to confirm it works.

**Comment by NaraVen** [comment]
Thank you mabicca. We added it to the wiki. I tried the rpm in SUSE 15 it just worked for me.
