### ISSUE TITLE
Allow file names greater than 255 character

### ISSUE THREAD

**Issue by chanaka-jostle** [Azure/azure-storage-fuse#54]
Hello,

Azure blob storage can support file names of 1,024 characters long. Even though Linux may support 255 characters file names only, can you remove the 255 character limit in the code because for example I would want transfer a file with a name greater than 255 characters from another file system (S3FS) to azure-storage-fuse directly.

**Comment by seguler** [comment]
I'm not sure if this will be possible. We store blobs on local disk in blobfuse, and keep the filename as is. Therefore 255 file name length applies to blobfuse's cache directory..  @AlexanderYukhanov and @asorrin-msft  for thoughts.

**Comment by seguler** [comment]
We are not considering supporting this due to architectural challenges. Blobfuse uses local file system for the cache, hence cannot support anything a file system on Linux can't support.
