### ISSUE TITLE
Blobfuse 1.3.6 with Auth Type SPN or MSI does not mount ADLS Gen 2 correctly. 

### ISSUE THREAD

**Issue by NaraVen** [Azure/azure-storage-fuse#540]
### Which version of the blobfuse was used?

1.3.6
### Which OS (please include version) are you using?
Ubuntu 20.04

### What problem was encountered?
ADLS Gen 2 does not list using Auth SPN or MSI

### Have you found a mitigation/solution?
Yes, use Storage Key

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No errors But output:  REQUEST/RESPONSE :: GET https://narapersonaladls.dfs.core.windows.net/blobfusetest?directory=/&maxResults=1&recursive=false&resource=filesystem?&User-Agent=azure-storage-fuse/1.3.6&x-ms-date=Wed, 09 Dec 2020 21:47:46 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 0 ::
Dec  9 13:47:47 surf1604 blobfuse[17612]:  ==> REQUEST/RESPONSE :: GET https://narapersonaladls.dfs.core.windows.net/blobfusetest?directory=/&maxResults=1&recursive=false&resource=filesystem?&User-Agent=azure-storage-fuse/1.3.6&x-ms-date=Wed, 09 Dec 2020 21:47:47 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 0 ::

### If relevant, please share your mount command.
blobfuse  /home/nara/mntblobfuse --tmp-path=~/tmpblobfuse --config-file=connectionpersonaladls.cfg --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 --use-attr-cache=true -o attr_timeout=120 -o entry_timeout=120 -o negative_timeout=120 --use-adls=true

**Comment by NaraVen** [comment]
For information OAuth Token 2 returned for resource https://storage.azure.com/.default does not allow ADLS storage account listing and GetProperty . This will be fixed in Dev soon. Recommended work around is to use Storage Key authentication.

**Comment by NaraVen** [comment]
@Madhuriv23 , @kk921dbg, Please follow this issue since this is  related to the latter half of the discussion in #537

**Comment by vibhansa-msft** [comment]
Kindly upgrade to 1.3.7.
