### ISSUE TITLE
Repetitive reads takes longer and longer

### ISSUE THREAD

**Issue by ValentinB10** [Azure/azure-storage-fuse#541]
### Which version of the blobfuse was used?

blobfuse 1.3.5

### Which OS (please include version) are you using?

Debian 9

### What problem was encountered?

I use a Python library called xarray to read files that are stored in containers. It does partial reads of files to extract the necessary information.
I have a cron job that runs several times a day and reads these files.
It works fine the first time I run the job, but it takes longer and longer to execute.
What is weird is that the required files are in cache after the first execution, so it should be faster the next times you execute the scripts.
For instance, the first time the job run, it takes 10 minutes, then 15 minutes, then 10 minutes, then 20 minutes, up to .... several hours. It is not predictable but it is sure that the execution time is increasing.

### Have you found a mitigation/solution?

The only way to troubleshoot the issue is to unmount the blobfuse mount and remount it after a while.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

No errors in the logs

### If relevant, please share your mount command.

`blobfuse /mnt/external_storage/protected_data/GFS --container-name=gfs --tmp-path=/tmp/blobfuse-gfs -o allow_other -o uid=0 -o gid=0 --file-cache-timeout-in-seconds=600`

For more information, the job run in a docker container and use a bind mount to read the blobfuse mount.

I tried to increase the `--file-cache-timeout-in-seconds` so that cached files persist longer but it makes no difference.
I cannot set the `--file-cache-timeout-in-seconds` to 0, as the xarray Python library does partial read of files and it will return an error as it uses MMAP operations.

**Comment by vibhansa-msft** [comment]
With respect to file caching there was a bug in 1.3.5. If the file is not modified then every open request was going to the container instead of using the cache. This has been fixed in 1.3.6 which is our latest release. Kindly upgrade to 1.3.6 and retry.

**Comment by vibhansa-msft** [comment]
"I cannot set the --file-cache-timeout-in-seconds to 0, as the xarray Python library does partial read of files and it will return an error as it uses MMAP operations." : sorry but I did not understood this part clearly. When file-cache-timeout is set to 0, it means file will be evicted from cache as soon as it is closed. So if the application keep the file handle open till its processing data there shall be no issue.

**Comment by ValentinB10** [comment]
Thank you for the information. @vibhansa-msft I will upgrade to version 1.3.6 and I give you an update.

**Comment by vibhansa-msft** [comment]
@ValentinB10 : Did 1.3.6 work as per your expectation ?

**Comment by ValentinB10** [comment]
I installed the version 1.3.6 on Thursday and it works fine so far. The execution time of my corn jobs are stable. Thank you. I close the issue.
