### ISSUE TITLE
Blobfuse libnutls.so.26 cannot open shared object file 

### ISSUE THREAD

**Issue by Dtiggs** [Azure/azure-storage-fuse#542]
### Which version of the blobfuse was used?
I am new to linux not exactly sure but it was loaded with this command 
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
blobfuse: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory

### Have you found a mitigation/solution?
no

**Comment by NaraVen** [comment]
Could you please do a lsb_release -a and make sure you indeed have Ubuntu 18.04. The above error is related to using the wrong blobfuse version for the OS.
Also Ubuntu 18.04 had a Kernel upgrade issue two months ago so if you have not restarted your VM in 2 months I recommend you do so.

**Comment by Dtiggs** [comment]
Hello NaraVen this is Ubuntu 18.04  and the vm was provisioned 3 days ago. It has been restarted at least 3 times since encountering the error message.

**Comment by NaraVen** [comment]
what does the lsb_release -a output show? Could you please cut paste the output here

**Comment by vibhansa-msft** [comment]
Closing the issue as there is no update on this. Reopen if the issue persists.
