### ISSUE TITLE
blobEndpoint for Azure Stack

### ISSUE THREAD

**Issue by btklein** [Azure/azure-storage-fuse#547]
### Which version of the blobfuse was used?
blobfuse 1.3.6

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
Used the blobconfig file `--config-file=/path/to/connection.cfg`

The `blobEndpoint` parameter in `connection.cfg` was being overwritten, not sure if `blobfuse` or Azure Stack naming constructs cause issue.  

Azure Stack desired endpoint:
`storageaccountname.blob.region.azurestack.company.com/container`

Tried:
`blobEndpoint blob.region.azurestack.company.com`

Result:
Failed request 

Checked `/var/log/syslog` and appeared `blobfuse` parsed the `blobEndpoint` with the `accountName` variable to build a request URL missing the region: 
`https://storageaccountname.blob.azurestack.company.com/container`  <--missing region in URL

### Have you found a mitigation/solution?
Yes

Updated `blobEndpoint` in `connection.cfg` as:
`blobEndpoint blob.region.region.azurestack.company.com` <mark><--added region twice</mark>

Result:
`https://storageaccountname.blob.region.azurestack.company.com/container` <--correctly has region in URL

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
With failed attempt `/var/log/syslog` revealed `blobfuse` parsed the `blobEndpoint` with the `accountName` variable to build a request URL missing the region: 
`https://storageaccountname.blob.azurestack.company.com/container` <--missing region in URL

**Comment by vibhansa-msft** [comment]
Kindly use 'storageaccountname.blob.region.azurestack.company.com' as the 'blobEndpoint' value.

**Comment by btklein** [comment]
Thanks.  On winter vacation right now, will test/check in a week and report back ASAP

**Comment by vibhansa-msft** [comment]
@btklein : Kindly update whether suggested change worked or not.

**Comment by btklein** [comment]
Apologies for the delay, time off and work schedules.  The proposed `storageaccountname.blob.region.azurestack.company.com` as the `blobEndpoint` value worked perfectly.  Would we be able to update the `blobEndpoint` example to this solution (under the `Config file options` section within the project's `README.md` file) to help the community going forward?

**Comment by vibhansa-msft** [comment]
Sure will update readme. Closing this issue as the suggested change worked for you case.
