### ISSUE TITLE
Errno 400 during uploading means the request was throttled

### ISSUE THREAD

**Issue by AlexanderYukhanov** [Azure/azure-storage-fuse#55]
Blobfuse doesn't propagate throttling error correctly during large (>64MB) files uploading. If put block fails with 503 blobfuse still trying to commit the blob and gets 400 response. So, client code see 400 instead of 503 or more appropriate 16  ( Device or resource busy)

**Comment by seguler** [comment]
Fixed in dev branch with PR #68

**Comment by seguler** [comment]
@AlexanderYukhanov is this fixed ?

**Comment by AlexanderYukhanov** [comment]
yes

**Comment by igroene** [comment]
I also ran into this. Any chance you can incorporate the fix into master branch?
