### ISSUE TITLE
Blobfuse storage getting disconnected with transport end point error

### ISSUE THREAD

**Issue by bala143225** [Azure/azure-storage-fuse#550]
### If relevant, please share your mount command.

blobfuse /mount-point-name --tmp-path=/mnt/resource/mount-point-name --config-file=/root/blobfusecfg/config-file -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Comment by vibhansa-msft** [comment]
Kindly enable LOG_DEBUG and share the logs. Can you also confirm what operation is causing this.

**Comment by vibhansa-msft** [comment]
Are you still hitting the issue ? Kindly share the requested logs if so.

**Comment by vibhansa-msft** [comment]
Closing this as there has been no update. Feel free to re-open and update if the issue persist.
