### ISSUE TITLE
Blobfuse documentation does not explicitly state limitation for named pipes (fifo files) 

### ISSUE THREAD

**Issue by yichungyu** [Azure/azure-storage-fuse#551]
### Which version of the blobfuse was used?
1.3.6

### Which OS (please include version) are you using?
Ubuntu 18.04.5 LTS

### What problem was encountered?
When executing "mkfifo test1", I encounter the following error:
![image](https://user-images.githubusercontent.com/69343984/104142581-281dc800-53f7-11eb-88f2-4b4e3a9ffa5a.png)

Our documentation should be updated to include this limitation https://github.com/Azure/azure-storage-fuse/wiki/4.-Limitations-%7C-Differences-from-POSIX

### Have you found a mitigation/solution?
No. This is a limitation for blobfuse.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

### If relevant, please share your mount command.
Not relevant

**Comment by vibhansa-msft** [comment]
Added limitation to wiki. Kindly refer updated section : 
https://github.com/Azure/azure-storage-fuse/wiki/4.-Limitations-%7C-Differences-from-POSIX
