### ISSUE TITLE
Expose the HIGH_THRESHOLD_VALUE as parameter in mount option

### ISSUE THREAD

**Issue by cloga** [Azure/azure-storage-fuse#552]
### What problem was encountered?
We are using temp storage in VM for blobfuse, meanwhile it also used by docker runtime and docker image cache. By default, k8s will evict pod when the disk usage is more than 85%, but the HIGH_THRESHOLD_VALUE of blobfuse is hard code for 90%. Which means when user using huge data storge than local cache disk will always be failed.

### Have you found a mitigation/solution?
We may use file_cache_timeout_in_seconds equal to a little value try to mitigate.

**Comment by vibhansa-msft** [comment]
Kindly upgrade to 1.3.7 and refer README on how to configure the thresholds.
