### ISSUE TITLE
Disabling cache

### ISSUE THREAD

**Issue by UnoSD** [Azure/azure-storage-fuse#553]
### Which version of the blobfuse was used?
1.3.6

### Which OS (please include version) are you using?
Arch Linux

### What problem was encountered?
Not a problem/lack of feature/missing documentation

### Have you found a mitigation/solution?
No

Is it possible to disable the local cache? If so, how can I achieve this? Would setting the cache size to 0 work? I would like the data to be written/read directly to blob storage skipping the intermediate layer. Thank you.

**Comment by UnoSD** [comment]
@NaraVen thanks. In my case is stored on disk and not in RAM, but yes.

I am just uploading data to blob and the cache is just adding an extra hop and messing up the stats of the moving tools (rsync/FM/etc), they believe that 100% is when the file lands in the cache whereas it takes way longer to then upload to blob.

**Comment by UnoSD** [comment]
@NaraVen I presume that was a typo: `cache_size_in_mb` should be `cache_size_mb`? I tried setting that to 0 but it keeps writing to the cache first. By any chance does 0 mean "no size constraint" instead of "don't cache"?

**Comment by NaraVen** [comment]
If you want disk cache then you have to give file_cache_timeout_in_seconds=0

**Comment by UnoSD** [comment]
I tried: `blobfuse /mnt/B --config-file=credentials --file-cache-timeout-in-seconds=0 --tmp-path=/home/U/.blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o uid=1000 -o gid=1000` and then rsync, but it still gets to 100% quickly (copying the file to the cache) and then it stops for a while at 100% while it uploads alll to Azure. Is there a way to avoid this?

**Comment by vibhansa-msft** [comment]
--file-cache-timeout-in-seconds=0 means files will be evicted from cache as soon as they are closed. Files will stay in cache till upload is complete and for that duration you will see disk usage. As of now there is no option to avoid local cache completly. However using  --cache-size-mb parameter you can control how much disk blobfuse shall be using.

For the other question '--cache-size-mb=0' means there is no constraint on disk usage.

**Comment by UnoSD** [comment]
@vibhansa-msft thank you for the clarification, would it make sense to open an issue here on GitHub for a feature request (if this is something that others may also require)?

**Comment by vibhansa-msft** [comment]
We can tag this issue itself as enhancement request instead.

**Comment by UnoSD** [comment]
Thank you.

**Comment by vibhansa-msft** [comment]
Blobfuse-1.4.1 has streaming feature for read-only mounts. Once enable it completely by-pass local cache. Kindly refer README for respective cli options.

**Comment by UnoSD** [comment]
@vibhansa-msft as you mentioned, that would only apply to read cache and read-only mounts. Should this be still open?

**Comment by vibhansa-msft** [comment]
For now we have no immediate plans to support write streaming, hence closed. We have added an item to our backlog for the same.

**Comment by arpit-rubrik** [comment]
@vibhansa-msft Is the support for write stream added to completely avoid local cache? What are the plans for that?

**Comment by vibhansa-msft** [comment]
Yes plan is to totally avoid local cache when write streaming mode is enabled. We are also working on a feature where small files are locally cache while big files are streamed (no local caching). However, all this is part of our next generation blobfuse called "blobfuse2", we have no plans to support write streaming on legacy blobfuse.

**Comment by arpit-rubrik** [comment]
Thanks for confirming.
Is there any page where I can find more about blobfuse v2? What is the expected date of release for v2?
