### ISSUE TITLE
Error messages assumes lack in config file or missing AZURE_STORAGE_ACCOUNT when forbidden 403 is sent

### ISSUE THREAD

**Issue by trymkb** [Azure/azure-storage-fuse#554]
It is a minor issue, but adding a message either in the program or in the documentation about failing credential can also be caused by firewall.

### Which version of the blobfuse was used?
1.3.6-1.el8

### Which OS (please include version) are you using?
Centos 8

### What problem was encountered?
Firewall on storage causes 403 message, and having the AZURE_STORAGE_ACCOUNT environment variables it outputs:
> Unable to start blobfuse.  No config file was specified and the AZURE_STORAGE_ACCOUNTenvironment variable was empty

With config it outputs:
> Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.

### Have you found a mitigation/solution?
Allow IP in firewall :-)
Both methods worked after.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Jan 19 08:57:38 xxxxxx blobfuse[668518]: ==> REQUEST/RESPONSE :: GET https://xxxxxxxxx.blob.core.windows.net/xxxxxxxxxx?comp=list&delimiter=/&include=metadata&maxresults=1&restype=container?&User-Agent=azure-storage-fuse/1.3.6&x-ms-date=Tue, 19 Jan 2021 08:57:38 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 403 :: REQ ID : xxxxxxxxxx

**Comment by vibhansa-msft** [comment]
I acknowledge the suggestion however firewall blocking connection is more of a user error. Also from the code side there is no way to be certain that connection failed due to firewall filters. We can add this information to our troubleshooting wiki.
Closing this bug report.
