### ISSUE TITLE
Failed to download blob into cache, storage errno = 11

### ISSUE THREAD

**Issue by ExeErik** [Azure/azure-storage-fuse#556]
### Which version of the blobfuse was used?

blobfuse-1.3.6-Linux

### Which OS (please include version) are you using?

Red Hat Enterprise Linux Server 7.9 (Maipo)

### What problem was encountered?

We try to mount an Azure storage account using blobfuse and then send the data to a Graylog instance using Filebeat.
The storage account itself contains application logs in JSON format.
If the application is now under load and the files are larger than approx. 15-20MB, we get the following error in the blobfuse:

`Jan 21 00:53:42 XXX-XXX-XXX-log-be01 blobfuse[32480]:  ==> REQUEST/RESPONSE :: GET https://storage0218XXX.blob.core.windows.net/XXX-ref/XXX_XXX-ref-8584686dcb-lpzsl_2021-01-21.log?&x-ms-range=bytes=16777216-18732643&User-Agent=azure-storage-fuse/1.3.6&x-ms-date=Wed, 20 Jan 2021 23:53:42 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 206 :: REQ ID : 40fff3c7-401e-008f-2a87-ef393c000000
Jan 21 00:53:42 XXX-XXX-XXX-log-be01 blobfuse[32480]: Failed to download blob into cache.  Blob name: XXX_XXX-ref-8584686dcb-lpzsl_2021-01-21.log, file name = /vol1/mnt/XXX-ref/root/XXX_XXX-ref-8584686dcb-lpzsl_2021-01-21.log, storage errno = 11.
Jan 21 00:53:42 XXX-XXX-XXX-log-be01 blobfuse[32480]: Failed to map storage error code 11 to a proper errno.  Returning EIO = 5 instead.
Jan 21 00:53:42 XXX-XXX-XXX-log-be01 blobfuse[32480]: Function azs_getattr, in file`

We have tried numerous other blobfuse mount configurations.

Our filebeat has the following configuration:

filebeat.inputs:
- type: log
  paths:
    - /insight-logs/XXX-ref/*.log
  json.keys_under_root: true
  json.add_error_key: true
  close_inactive: 1m
  file_identity.path: ~
  scan_frequency: 30s

output.logstash:
    hosts: ["XXX.XXX.XXX.XXX:5044"]

Filebeat error:

`2021-01-20T23:53:42.464Z        ERROR   log/input.go:542        Harvester could not be started on existing file: /insight-logs/XXX-ref/XXX-ref-8584686dcb-lpzsl_2021-01-21.log, Err: error setting up harvester: Harvester setup failed. Unexpected file opening error: Failed opening /insight-logs/XXX-ref/XXX-ref-8584686dcb-lpzsl_2021-01-21.log: open /insight-logs/XXX-ref/XXX-ref-8584686dcb-lpzsl_2021-01-21.log: input/output error`

**Used Azure Disk (VM that running blobfuse):**

1024 GiB (Premium SSD) - P30 - 5000 IOPS, 200 MBps

**Azure Storage Account:** 

Account kind
StorageV2 (general purpose v2)

Replication
Zone-redundant-storage

### Have you found a mitigation/solution?

no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
x

### If relevant, please share your mount command.

`/usr/bin/blobfuse $1 -o allow_other --tmp-path=/vol1/mnt/$(basename $1) -o attr_timeout=0 -o entry_timeout=0 --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=0 --config-file=/vol1/blobfuse/fuse_connection_$(basename $1).cfg
`

`/usr/bin/blobfuse $1 -o allow_other --tmp-path=/mnt/$(basename $1) -o attr_timeout=5 -o entry_timeout=5 --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=5 --config-file=/vol1/blobfuse/fuse_connection_$(basename $1).cfg`

`/usr/bin/blobfuse $1 -o allow_other --tmp-path=/vol1/mnt/$(basename $1) -o attr_timeout=5 -o entry_timeout=5 --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=5 --config-file=/vol1/blobfuse/fuse_connection_$(basename $1).cfg`

`/usr/bin/blobfuse $1 -o allow_other --tmp-path=/ephemeral/blobfuse_tmp/$(basename $1) -o attr_timeout=5 -o entry_timeout=5 --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=5 --config-file=/vol1/blobfuse/fuse_connection_$(basename $1).cfg`

`/usr/bin/blobfuse $1 -o allow_other --tmp-path=/vol1/mnt/$(basename $1) -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG --config-file=/vol1/blobfuse/fuse_connection_$(basename $1).cfg `

**Comment by vibhansa-msft** [comment]
As per the response status from REST call (RESPONSE Status :: 206), file contents are getting downloaded. Failure is post that point which means blobfuse is not able to write it to the cache. Can you confirm user mounting blobfuse has sufficient read/write permissions on the temp directory (--tmp-path). 

Also "If the application is now under load and the files are larger than approx. 15-20MB, we get the following error in the blobfuse:" : does this mean only under load you hit the error otherwise it work fine.

**Comment by ExeErik** [comment]
> As per the response status from REST call (RESPONSE Status :: 206), file contents are getting downloaded. Failure is post that point which means blobfuse is not able to write it to the cache. Can you confirm user mounting blobfuse has sufficient read/write permissions on the temp directory (--tmp-path).
> 
> Also "If the application is now under load and the files are larger than approx. 15-20MB, we get the following error in the blobfuse:" : does this mean only under load you hit the error otherwise it work fine.

Yes, blobfuse has sufficient read/write permissions on the temp directory. 
The function is given up to a certain point (for example file size).

We assume that the error also occurs when the log files reach the corresponding size without heavy load. 
However, we could only cause this with load tests.

**Comment by vibhansa-msft** [comment]
Filesize in MBs shall not be an issue with blobfuse. We do support files upto few GBs in size. Can you check the disk usage of the temp directory when the error is hit. Are there operations running in parallel with respect to container access like reading/writing files ?

**Comment by ExeErik** [comment]
> Filesize in MBs shall not be an issue with blobfuse. We do support files upto few GBs in size. Can you check the disk usage of the temp directory when the error is hit. Are there operations running in parallel with respect to container access like reading/writing files ?

We monitored the disk usage with an iostat and could not find any problems here.

Yes, there are parallel accesses to the container.
Our application continuously send its logs to the container.
Filebeat reads this in at the same time.

**Comment by NaraVen** [comment]
@ExeErik. It appears that your VM is running out of memory. Could you please do a "free -m" and verify if you have enough memory to download that file.

**Comment by ExeErik** [comment]
> @ExeErik. It appears that your VM is running out of memory. Could you please do a "free -m" and verify if you have enough memory to download that file.

Sorry for the late reply, in the meantime we have tried to evaluate another method - this one also failed.

So back to blobfuse:
We checked the memory: while and before the error occures we had no load increase. 

We also tried a manual copy of the file from the blobfuse mount location to another. Same problem:
`/bin/cp: cannot open ‘/XXX/log/XXX-XXX/XXX_XXX-XXX-XXX-qpkg8_2021-02-10.log’ for reading: Input/output error`

**Comment by vibhansa-msft** [comment]
Does the issue still persist ?

**Comment by NaraVen** [comment]
@ExeErik Could you please check how many open files you have? Is   lsof  | wc -l  more than ulimit -S -n?  . Since you said memory is not an issue the open file handles could have exceeded the limit blocking any more file opens for read?

**Comment by NaraVen** [comment]
closing this since it appears you are not pursuing this anymore, feel free to comment and we will reopen.
