### ISSUE TITLE
ls: cannot access 'mycontainer': Permission denied

### ISSUE THREAD

**Issue by athanell** [Azure/azure-storage-fuse#559]
Hello,  
I followed the steps provided in  [https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux](url) to mount a container as a file system to my linux VM.  The VM and the storage account are in the same resource group.

### Which version of the blobfuse was used?
1.3.6

### Which OS (please include version) are you using?
Ubuntu 18.04.5 LTS

### What problem was encountered?
I cannot access the mounted container

### If relevant, please share your mount command.
``` bash
sudo mkdir /mnt/resource/blobfusetmp -p
sudo chown <myusername> /mnt/resource/blobfusetmp
touch ~/fuse_connection.cfg #provided with the proper storage account name, the key1 of the storage account and the container name
chmod 600 fuse_connection.cfg
mkdir ~/mycontainer
sudo blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/<myusername>/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
ls mycontainer
ls: cannot access 'mycontainer': Permission denied

```
Any suggestions?
Thank you

**Comment by kaiyuezhou** [comment]
`sudo ls mycontainer` may help.

**Comment by athanell** [comment]
Thanks for the assistance @kaiyuezhou. It did resolve the matter.
