### ISSUE TITLE
Sync files even if the handle is still open

### ISSUE THREAD

**Issue by Jendker** [Azure/azure-storage-fuse#561]
### Which version of the blobfuse was used?
1.3.6

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
If I am using blobfuse to sync output of the script with blobfuse and the script stalls I am not able to access the updated log file. Upload only happens if the file handle will be closed, but that does not happen and I am unable to investigate the log file.

### Have you found a mitigation/solution?
One possible solution would be that even the files with open handle will get syncs every N seconds. Is it possible?

### If relevant, please share your mount command.
    sudo blobfuse /vm_tmp \
        --tmp-path=/mnt/resource/blobfusetmp \
        --config-file=/home/vm/fuse_connection.cfg \
        -o attr_timeout=240 \
        -o entry_timeout=240 \
        -o negative_timeout=120 \
        -o allow_other

**Comment by vibhansa-msft** [comment]
As of now blobfuse does not have any option to sync an open file or a periodic sync. All writes are redirected to the cache that it maintains and only on close we upload the entire file. It has been designed this way to save on the calls made to azure container.

**Comment by Jendker** [comment]
Thank you for your answer.
Could you tell what would be another possible solution to sync/mount a Azure container besides blobfuse so that a sync could be forced periodically?

I know that this is not blobfuse specific, but since this repo is owned by Azure I wanted to continue asking about this in this issue. Maybe it will also help others.

**Comment by NaraVen** [comment]
Have you tried 
1)NFS V3. instead of blobfuse
OR
2) blobfuse +rsync where rsync copies to a non mounted dir from the blobfuse mount and you read your files from the rsync destination

**Comment by Jendker** [comment]
I see, so there isn't anything specifically for Azure containers for periodic sync. Thanks!

**Comment by CatchSandeepVaid** [comment]
Any updates on when this feature will be available?

**Comment by vibhansa-msft** [comment]
As of now there is no plan to add such a feature. As conveyed in above comments files will be flushed only when handle is closed.
Blobfuse2 has write streaming support and you can configure the system in direct streaming mode where every write operation will end up updating the content on storage container. This will bring down the performance though, but even if you keep the file handle open for ever you can see the changes are getting reflected.

**Comment by CatchSandeepVaid** [comment]
Our kubernetes version (in AKS) is 1.23.12 and it seems [NFS V3 is supported only from kubernetes version 1.25  ](https://learn.microsoft.com/en-us/azure/aks/azure-blob-csi?tabs=NFS). So this means we cant use NFS V3 with our kuberenetes version as if we try to do that we get error as :

` Unable to attach or mount volumes: unmounted volumes=[our-volume-name], unattached volumes=[...]: timed out waiting for the condition`

**Comment by vibhansa-msft** [comment]
Blobfuse + Rsync shall work for you, if you wish to periodically sync up the files to storage container. 
For long standing file handles you can keep the handle open but call Flush() periodically. That shall trigger upload of files to container in between.
