### ISSUE TITLE
mount size not in accordance with cache settings

### ISSUE THREAD

**Issue by j-baron** [Azure/azure-storage-fuse#562]
### Which version of the blobfuse was used?
blobfuse 1.0.3
dpkg - 1.1.1

### Which OS (please include version) are you using?
Ubuntu 18.04.5 LTS

### What problem was encountered?
when setting cache size on pv like:   - cache-size-mb=10000, this is not respected in the mount when seen on the pod. 
/dev/sda1             63G   19G   42G  31% /mnt (shouldn't be more than 10GB used, in accordance with the cache size flag mentioned above)
### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
no issues shown or errors shown

### If relevant, please share your mount command.
Handled by Kubernetes using Blob CSI Drivers - https://github.com/kubernetes-sigs/blob-csi-driver

**Comment by vibhansa-msft** [comment]
Can you confirm blobfuse version again. As mentioned above, if you are using 1.0.3 then cache-size parameter is not supported. Kindly upgrade to latest blobfuse version 1.3.6.

**Comment by j-baron** [comment]
Hi, thank you for the quick reply, I updated to 1.3.6 but its still ignoring the flag and using much more than it is meant to, when I set the flag to: - --cache-size-mb=6000 I still see usage for prometheus running of more than 18GB on the node on the /mnt. This is three times more than the expected figure. Thank you

**Comment by vibhansa-msft** [comment]
Kindly try "--file-cache-timeout-in-seconds=0" cli option to speed up the cache eviction. Also cache eviction works only after application has closed the file handle. If application needs too many files to be open for some time then sufficient cache will be required by blobfuse.

**Comment by j-baron** [comment]
Hi, it has had no effect whatsoever. Thank you

**Comment by NaraVen** [comment]
@j-baron, it appears that your cache is not getting evicted at all. Could you please try these mount options --use-attr-cache=false -o attr_timeout=10 -o entry_timeout=10 -o negative_timeout=10  --file-cache-timeout-in-seconds=0 --no-symlinks=true

For a list of what these mount options do please refer to this link: https://github.com/Azure/azure-storage-fuse/blob/master/README.md

**Comment by j-baron** [comment]
Hi, thank you @NaraVen for responding, I have tried the mount options you have specified with and without setting a cache size, and yet it has not worked, it's still using it and not evicting at all. Please let me know how to proceed. Thank you

**Comment by NaraVen** [comment]
@j-baron , I recommend using a heavier VM to do this job :-) I ran blobfuse with minimal cache and I do see eviction happening.

**Comment by j-baron** [comment]
I am using a heavy VM already, its running prometheus, it may be that prometheus doesn't close files and that whatever size the Prometheus data is, that's how much cache size it will be. Does this sound normal and if so what are my options?

**Comment by vibhansa-msft** [comment]
If you suspect files are not closed then amount of cache needed will depend on total size of files that are kept open.

**Comment by NaraVen** [comment]
Please upgrade to 1.3.7 and reopen if this issue still persists.
