### ISSUE TITLE
data lost during write

### ISSUE THREAD

**Issue by AlexanderYukhanov** [Azure/azure-storage-fuse#57]
Simple repro:
f1 = open('/mnt/hi.txt', 'w')
f2 = open('/mnt/hi.txt', 'w')
f2.close()
... sleep long enough for hi.txt to be removed from cache
f1.write("I am lost")
f1.close()

Expected behavior is hi.txt contains "I am lost", actual - empty file.

**Comment by AlexanderYukhanov** [comment]
If the previous example seems stupid, here is a much more realistic and confusing scenario (caused by the same bug):
I have a long running job which writes a log file. Some time later after job started I want to check its progress by calling 'stat filename' and 'tail filename'. Should work ? Nope, tail will delete the file.

**Comment by seguler** [comment]
Alright this is an issue with multiple file handles. I believe the issue was a regression on blobfuse 0.2.

Let's fix it immediately

**Comment by seguler** [comment]
This is now fixed in blobfuse 0.2.2. Thanks for reporting and identifying the issue Alex.
https://github.com/Azure/azure-storage-fuse/releases/tag/v0.2.3
