### ISSUE TITLE
The blobfuse is asking for tokens when the auth type is set to MSI

### ISSUE THREAD

**Issue by hpaknia** [Azure/azure-storage-fuse#570]
### Which version of the blobfuse was used?
~~1.0.2~~ 1.3.6

### Which OS (please include version) are you using?
CentOS Linux release 7.9.2009 (Core)

### What problem was encountered?
Unable to mount using managed identities:
This is the config file:
```
authType MSI
accountName mystorage
containerName mycontainer
```
This is the command:

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Same stderr in the system logs

### If relevant, please share your mount command.
```
$ sudo blobfuse /tmp/mycontainer --tmp-path=/mnt/blobfusetmp  --config-file=/home/myuser/blobfuse.config -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG
Unable to start blobfuse. Exactly one of Account Key and SAS token must be specified in the config file, and the other line should be deleted.
$
```

I am sure the managed identity is already set. Why blobfuse is asking for tokens when the auth type is set to MSI?
I even tried setting `AZURE_STORAGE_IDENTITY_CLIENT_ID`, no avail.

**Comment by NaraVen** [comment]
Could you please put authType MSI below accountName

**Comment by hpaknia** [comment]
I did, the same error:
```
Unable to start blobfuse. Exactly one of Account Key and SAS token must be specified in the config file, and the other line should be deleted.
```

**Comment by vibhansa-msft** [comment]
Can you move to latest 1.3.6 version and check, 1.0.2 is pretty old version. You can get 1.3.6 from below location : https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.6

**Comment by hpaknia** [comment]
Thanks for prompt responses. After installation of the most recent version, this is the error in the system logs:
```log
Feb 22 05:02:23 new-vm blobfuse[2176]: Setting logging level to : LOG_DEBUG
Feb 22 05:02:23 new-vm blobfuse[2176]: release is 3.100000, Kernel version is 3.10.0-1160.15.2.el7.x86_64
Feb 22 05:02:23 new-vm blobfuse[2176]: CURL Version is 7.29.0
Feb 22 05:02:23 new-vm blobfuse[2176]: ** Delaying tls init to post fork for older libcurl version
Feb 22 05:02:23 new-vm blobfuse[2176]: ** Delaying authentication to post fork for older curl versions
Feb 22 05:02:23 new-vm blobfuse[2179]: ** Post fork authentication for older libcurl version
Feb 22 05:02:23 new-vm blobfuse[2179]: refresh callback set
Feb 22 05:02:23 new-vm blobfuse[2179]: calling refresh token
Feb 22 05:02:28 new-vm blobfuse[2179]: INFO not WARNING: Printing Json Token as string for visibility{"access_token":"A_LON_TOKEN************************","client_id":"***********","expires_in":"86016","expires_on":"1614056164","ext_expires_in":"86399","not_before":"1613969464","resource":"https://storage.azure.com/","token_type":"Bearer"}
Feb 22 05:02:28 new-vm blobfuse[2179]: INFO: After adding specified expires_in token expiry time in utc Tue Feb 23 04:56:04 2021
Feb 22 05:02:28 new-vm blobfuse[2179]: OAUTH Token : Refresh token succeeded expiry time is: Tue Feb 23 04:56:04 2021
Feb 22 05:02:29 new-vm blobfuse[2179]: ==> REQUEST/RESPONSE :: GET https://mystorage.blob.core.windows.net/mycontainer?comp=list&delimiter=/&include=metadata&maxresults=1&restype=container?&User-Agent=azure-storage-fuse/1.3.6&x-ms-date=Mon, 22 Feb 2021 05:02:28 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 403 :: REQ ID : 2ff391b9-001e-000c-21d7-083b35000000
Feb 22 05:02:29 new-vm blobfuse[2179]: Unable to start blobfuse.  Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key/sas token/OAuth access token and container name. errno = 403
Feb 22 05:02:29 new-vm blobfuse[2179]: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
```
The storage account access is public, so no problem there. I double checked the access, there's a role assignment which has read write access to the storage account )and implicitly on the containers)
My VM has that identity set as user assigned identy.
Any idea?

**Comment by NaraVen** [comment]
you need to give the user identity "storage blob contributor" permissions.

**Comment by hpaknia** [comment]
@NaraVen, the managed identity has "Contributor" access for the storage account. It's the only permission which should be sufficient. I checked the IAM permissions on the containers. The role **does** have Contributor access to the container.

**Comment by hpaknia** [comment]
The permission did have `Contributor` access, I added `Storage Account Contributor`. The same error. Something might really be wrong with the container....
```
Feb 22 17:12:24 new-vm blobfuse[7641]: Unable to start blobfuse.  Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key/sas token/OAuth access token and container name. errno = 403
```

**Comment by NaraVen** [comment]
you need Contributor and Storage Blob contributor not Storage Account contributor.

**Comment by hpaknia** [comment]
Thanks for patiently helping me through the setup process. 
For the people who end up by searching here:
1. Install blobfuse by downloading the most recent stable version from:
https://github.com/Azure/azure-storage-fuse/releases
2. I had to add `Storage Blob contributor` to gain access to the blob contents.
