### ISSUE TITLE
Enhancement request: CPK support

### ISSUE THREAD

**Issue by hcordobest** [Azure/azure-storage-fuse#571]
### Which version of the blobfuse was used?
I checked for this capability up to release 1.3.6, and searched in the issues list / PRs.

### Which OS (please include version) are you using?
Linux Ubuntu 20.04 (Azure image)

### What problem was encountered?
blobfuse does not support CPK encryption. CPK is a per-file concept, but the option where all files in the same container share a CPK would be very useful.

### Have you found a mitigation/solution?
Not as a mount point, so other programs may use the information in the container without being aware of the underlying Azure Blob-CPK layer. We tried to implement the functionality on a fork (https://github.com/Telefonica/azure-storage-fuse), although the base code has changed significantly from the version we used.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Not applicable, as it is an Enhancement Request.

### If relevant, please share your mount command.
Not applicable.

**Comment by vibhansa-msft** [comment]
We will not be adding CPK support in blobfuse. However, we are working on next generation of blobfuse and this item is there in our backlog.

**Comment by hcordobest** [comment]
OK, I'll stay tuned!
