### ISSUE TITLE
OS hangs when attempting to create/copy files from storage account

### ISSUE THREAD

**Issue by minhtrieu-aemo** [Azure/azure-storage-fuse#574]
### Which version of the blobfuse was used?
blobfuse-1.3.6-RHEL-7.8-x86_64.rpm

### Which OS (please include version) are you using?
RHEL 7.7 (Azure Marketplace Image)
        "Publisher": "RedHat",
        "Offer": "RHEL",
        "SKU": "7.7",
        "Version": "7.7.2020110315"

### What problem was encountered?
The storage account container mounts correctly. I can see files in the container. When I try to create a dummy file in the container or copy a file out of the container the OS hangs. I have to reboot the VM to restore functionality.
I have tried using keys and managed identities, not appears to be working. Have also tried just blob storage account instead of adls gen2. 

### Have you found a mitigation/solution?
None

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
The following error appears in the serial console.

[  360.109130] INFO: task omiengine:1570 blocked for more than 120 seconds.
[  360.118785] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  360.132322] omiengine       D ffff9f65ffc1ac80     0  1570   1565 0x00000080
[  360.146193] Call Trace:
[  360.149483]  [<ffffffff90582299>] schedule+0x29/0x70
[  360.157273]  [<ffffffff90096f55>] fanotify_handle_event+0x265/0x3a0
[  360.165026]  [<ffffffff8fec7450>] ? wake_up_atomic_t+0x30/0x30
[  360.172384]  [<ffffffff90093328>] fsnotify+0x388/0x460
[  360.178855]  [<ffffffff90104e2e>] security_file_open+0x6e/0x70
[  360.188208]  [<ffffffff90048339>] do_dentry_open+0xb9/0x2c0
[  360.195309]  [<ffffffff90104882>] ? security_inode_permission+0x22/0x30
[  360.204843]  [<ffffffff900485da>] vfs_open+0x5a/0xb0
[  360.211630]  [<ffffffff90056b8a>] ? may_open+0x5a/0x120
[  360.219412]  [<ffffffff900592b6>] do_last+0x1f6/0x1290
[  360.227544]  [<ffffffff9005c14d>] path_openat+0xcd/0x5a0
[  360.236424]  [<ffffffff9004a1ab>] ? do_sync_readv_writev+0x7b/0xd0
[  360.246490]  [<ffffffff9005dabd>] do_filp_open+0x4d/0xb0
[  360.254669]  [<ffffffff9006b877>] ? __alloc_fd+0x47/0x170
[  360.262738]  [<ffffffff90049a64>] do_sys_open+0x124/0x220
[  360.270512]  [<ffffffff90049b7e>] SyS_open+0x1e/0x20
[  360.277561]  [<ffffffffc07c6e72>] cb_sys_open+0xd2/0x260 [event_collector_1_10_10180]
[  360.289081]  [<ffffffff9058fede>] system_call_fastpath+0x25/0x2a
[  360.297999] INFO: task output.rb:140:2178 blocked for more than 120 seconds.
[  360.308396] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  360.319869] output.rb:140   D ffff9f65ffd1ac80     0  2178      1 0x00000080
[  360.330994] Call Trace:
[  360.334421]  [<ffffffff90582299>] schedule+0x29/0x70
[  360.341138]  [<ffffffff90096f55>] fanotify_handle_event+0x265/0x3a0
[  360.354091]  [<ffffffff8fec7450>] ? wake_up_atomic_t+0x30/0x30
[  360.362696]  [<ffffffff90093328>] fsnotify+0x388/0x460
[  360.369197]  [<ffffffff90104e2e>] security_file_open+0x6e/0x70
[  360.377505]  [<ffffffff90048339>] do_dentry_open+0xb9/0x2c0
[  360.391758]  [<ffffffff90104882>] ? security_inode_permission+0x22/0x30
[  360.401869]  [<ffffffff900485da>] vfs_open+0x5a/0xb0
[  360.408418]  [<ffffffff90056b8a>] ? may_open+0x5a/0x120
[  360.415031]  [<ffffffff900592b6>] do_last+0x1f6/0x1290
[  360.421646]  [<ffffffff9005c14d>] path_openat+0xcd/0x5a0
[  360.428417]  [<ffffffff90187a96>] ? radix_tree_tag_set+0x86/0x110
[  360.437292]  [<ffffffff9005dabd>] do_filp_open+0x4d/0xb0
[  360.444369]  [<ffffffff8ff3db2c>] ? audit_alloc_name+0x9c/0x160
[  360.456222]  [<ffffffff900498a8>] file_open_name+0xf8/0x140
[  360.463199]  [<ffffffff90049923>] filp_open+0x33/0x50
[  360.470427]  [<ffffffffc07c62a0>] get_mode_from_file+0x440/0x490 [event_collector_1_10_10180]
[  360.487383]  [<ffffffffc07c7b48>] cb_sys_rename+0x248/0x6f0 [event_collector_1_10_10180]
[  360.501463]  [<ffffffff9058fede>] system_call_fastpath+0x25/0x2a
[  360.509275] INFO: task in_syslog.rb:1*:2179 blocked for more than 120 seconds.
[  360.520837] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  360.531289] in_syslog.rb:1* D ffff9f65d6751070     0  2179      1 0x00000080
[  360.608510] Call Trace:
[  360.681981]  [<ffffffff90582299>] schedule+0x29/0x70
[  360.757747]  [<ffffffff90096f55>] fanotify_handle_event+0x265/0x3a0
[  360.833719]  [<ffffffff8fec7450>] ? wake_up_atomic_t+0x30/0x30
[  360.911731]  [<ffffffff90093328>] fsnotify+0x388/0x460
[  360.987246]  [<ffffffff90104e2e>] security_file_open+0x6e/0x70
[  361.063039]  [<ffffffff90048339>] do_dentry_open+0xb9/0x2c0
[  361.136860]  [<ffffffff90104882>] ? security_inode_permission+0x22/0x30
[  361.210117]  [<ffffffff900485da>] vfs_open+0x5a/0xb0
[  361.282037]  [<ffffffff90056b8a>] ? may_open+0x5a/0x120
[  361.354780]  [<ffffffff900592b6>] do_last+0x1f6/0x1290
[  361.425910]  [<ffffffff9005c14d>] path_openat+0xcd/0x5a0
[  361.497756]  [<ffffffff8ff3eb1f>] ? __audit_inode+0x1cf/0x3e0
[  361.566533]  [<ffffffff9005dabd>] do_filp_open+0x4d/0xb0
[  361.637008]  [<ffffffff9006b877>] ? __alloc_fd+0x47/0x170
[  361.710237]  [<ffffffff90049a64>] do_sys_open+0x124/0x220
[  361.782269]  [<ffffffff90049b7e>] SyS_open+0x1e/0x20
[  361.851488]  [<ffffffffc07c6e72>] cb_sys_open+0xd2/0x260 [event_collector_1_10_10180]
[  361.923383]  [<ffffffff9058fede>] system_call_fastpath+0x25/0x2a
[  361.993524] INFO: task in:imjournal:2101 blocked for more than 120 seconds.
[  362.065420] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  362.141808] in:imjournal    D ffff9f65ceb65230     0  2101      1 0x00000080
[  362.226287] Call Trace:
[  362.298545]  [<ffffffff90582299>] schedule+0x29/0x70
[  362.375091]  [<ffffffff90096f55>] fanotify_handle_event+0x265/0x3a0
[  362.452911]  [<ffffffff8fec7450>] ? wake_up_atomic_t+0x30/0x30
[  362.530294]  [<ffffffff90093328>] fsnotify+0x388/0x460
[  362.604215]  [<ffffffff90104e2e>] security_file_open+0x6e/0x70
[  362.682871]  [<ffffffff90048339>] do_dentry_open+0xb9/0x2c0
[  362.757069]  [<ffffffff90104882>] ? security_inode_permission+0x22/0x30
[  362.833635]  [<ffffffff900485da>] vfs_open+0x5a/0xb0
[  362.906938]  [<ffffffff90056b8a>] ? may_open+0x5a/0x120
[  362.979723]  [<ffffffff900592b6>] do_last+0x1f6/0x1290
[  363.051769]  [<ffffffff9005c14d>] path_openat+0xcd/0x5a0
[  363.123907]  [<ffffffff9005dabd>] do_filp_open+0x4d/0xb0
[  363.197337]  [<ffffffff8ff3db2c>] ? audit_alloc_name+0x9c/0x160
[  363.268284]  [<ffffffff900498a8>] file_open_name+0xf8/0x140
[  363.341291]  [<ffffffff90049923>] filp_open+0x33/0x50
[  363.411750]  [<ffffffffc07c62a0>] get_mode_from_file+0x440/0x490 [event_collector_1_10_10180]
[  363.487709]  [<ffffffffc07c7b48>] cb_sys_rename+0x248/0x6f0 [event_collector_1_10_10180]
[  363.565154]  [<ffffffff9058fede>] system_call_fastpath+0x25/0x2a
[  363.640038] INFO: task blobfuse:2117 blocked for more than 120 seconds.
[  363.717497] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  363.795226] blobfuse        D ffff9f65f5bb62a0     0  2117      1 0x00000080
[  363.874841] Call Trace:
[  363.947027]  [<ffffffff90582299>] schedule+0x29/0x70
[  364.025039]  [<ffffffff90096f55>] fanotify_handle_event+0x265/0x3a0
[  364.103200]  [<ffffffff8fec7450>] ? wake_up_atomic_t+0x30/0x30
[  364.180363]  [<ffffffff90093328>] fsnotify+0x388/0x460
[  364.255356]  [<ffffffff90104e2e>] security_file_open+0x6e/0x70
[  364.331726]  [<ffffffff90048339>] do_dentry_open+0xb9/0x2c0
[  364.405495]  [<ffffffff90104882>] ? security_inode_permission+0x22/0x30
[  364.478070]  [<ffffffff900485da>] vfs_open+0x5a/0xb0
[  364.548559]  [<ffffffff90056b8a>] ? may_open+0x5a/0x120
[  364.619523]  [<ffffffff900592b6>] do_last+0x1f6/0x1290
[  364.687465]  [<ffffffff9005c14d>] path_openat+0xcd/0x5a0
[  364.759712]  [<ffffffff8ff3eb1f>] ? __audit_inode+0x1cf/0x3e0
[  364.832061]  [<ffffffff9005dabd>] do_filp_open+0x4d/0xb0
[  364.901727]  [<ffffffff9006b877>] ? __alloc_fd+0x47/0x170
[  364.973196]  [<ffffffff90049a64>] do_sys_open+0x124/0x220
[  365.044846]  [<ffffffff90049b7e>] SyS_open+0x1e/0x20
[  365.115990]  [<ffffffffc07c6e72>] cb_sys_open+0xd2/0x260 [event_collector_1_10_10180]
[  365.190078]  [<ffffffff9058fede>] system_call_fastpath+0x25/0x2a
[  365.266926] INFO: task crond:2166 blocked for more than 120 seconds.
[  365.340908] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  365.417179] crond           D ffff9f63795ec1c0     0  2166      1 0x00000080
[  365.493072] Call Trace:
[  365.564079]  [<ffffffff90582299>] schedule+0x29/0x70
[  365.639511]  [<ffffffff90096f55>] fanotify_handle_event+0x265/0x3a0
[  365.718284]  [<ffffffff8fec7450>] ? wake_up_atomic_t+0x30/0x30
[  365.794050]  [<ffffffff90093328>] fsnotify+0x388/0x460
[  365.868501]  [<ffffffff90104e2e>] security_file_open+0x6e/0x70
[  365.944929]  [<ffffffff90048339>] do_dentry_open+0xb9/0x2c0
[  366.019364]  [<ffffffff90104882>] ? security_inode_permission+0x22/0x30
[  366.094631]  [<ffffffff900485da>] vfs_open+0x5a/0xb0
[  366.165941]  [<ffffffff90056b8a>] ? may_open+0x5a/0x120
[  366.240288]  [<ffffffff900592b6>] do_last+0x1f6/0x1290
[  366.311199]  [<ffffffff9005c14d>] path_openat+0xcd/0x5a0
[  366.382355]  [<ffffffff8ff30007>] ? cpuset_can_attach+0x7/0xf0
[  366.454151]  [<ffffffff8ffbddbb>] ? unlock_page+0x2b/0x30
[  366.525734]  [<ffffffff9005dabd>] do_filp_open+0x4d/0xb0
[  366.596451]  [<ffffffff9006b877>] ? __alloc_fd+0x47/0x170
[  366.667979]  [<ffffffff90049a64>] do_sys_open+0x124/0x220
[  366.739283]  [<ffffffff90049b7e>] SyS_open+0x1e/0x20
[  366.807697]  [<ffffffffc07c6e72>] cb_sys_open+0xd2/0x260 [event_collector_1_10_10180]
[  366.880976]  [<ffffffff9058fede>] system_call_fastpath+0x25/0x2a
[  366.951286] INFO: task python:2268 blocked for more than 120 seconds.
[  367.025114] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  367.100095] python          D ffff9f65ffd1ac80     0  2268   2087 0x00000080
[  367.178993] Call Trace:
[  367.258743]  [<ffffffff90582299>] schedule+0x29/0x70
[  367.330058]  [<ffffffff90096f55>] fanotify_handle_event+0x265/0x3a0
[  367.404726]  [<ffffffff8fec7450>] ? wake_up_atomic_t+0x30/0x30
[  367.477818]  [<ffffffff90093328>] fsnotify+0x388/0x460
[  367.549668]  [<ffffffff90104e2e>] security_file_open+0x6e/0x70
[  367.621944]  [<ffffffff90048339>] do_dentry_open+0xb9/0x2c0
[  367.691986]  [<ffffffff90104882>] ? security_inode_permission+0x22/0x30
[  367.769390]  [<ffffffff900485da>] vfs_open+0x5a/0xb0
[  367.838926]  [<ffffffff90056b8a>] ? may_open+0x5a/0x120
[  367.908696]  [<ffffffff900592b6>] do_last+0x1f6/0x1290
[  367.979166]  [<ffffffff9005c14d>] path_openat+0xcd/0x5a0
[  368.051429]  [<ffffffff8ff3eb1f>] ? __audit_inode+0x1cf/0x3e0
[  368.120118]  [<ffffffff9005dabd>] do_filp_open+0x4d/0xb0
[  368.186895]  [<ffffffff9006b877>] ? __alloc_fd+0x47/0x170
[  368.260478]  [<ffffffff90049a64>] do_sys_open+0x124/0x220
[  368.330302]  [<ffffffff90049b7e>] SyS_open+0x1e/0x20
[  368.397422]  [<ffffffffc07c6e72>] cb_sys_open+0xd2/0x260 [event_collector_1_10_10180]
[  368.467501]  [<ffffffff9058fede>] system_call_fastpath+0x25/0x2a
[  368.538112] INFO: task rrdtool:2626 blocked for more than 120 seconds.
[  368.610010] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  368.685411] rrdtool         D ffff9f65ffd1ac80     0  2626   2622 0x00000080
[  368.765572] Call Trace:
[  368.835246]  [<ffffffff90582299>] schedule+0x29/0x70
[  368.908302]  [<ffffffff90096f55>] fanotify_handle_event+0x265/0x3a0
[  368.986129]  [<ffffffff9057b937>] ? avc_compute_av+0x1ec/0x1fe
[  369.060415]  [<ffffffff8fec7450>] ? wake_up_atomic_t+0x30/0x30
[  369.133968]  [<ffffffff90093328>] fsnotify+0x388/0x460
[  369.205373]  [<ffffffff90104e2e>] security_file_open+0x6e/0x70
[  369.285898]  [<ffffffff90048339>] do_dentry_open+0xb9/0x2c0
[  369.354799]  [<ffffffff900485da>] vfs_open+0x5a/0xb0
[  369.425226]  [<ffffffff90056b8a>] ? may_open+0x5a/0x120
[  369.495827]  [<ffffffff900592b6>] do_last+0x1f6/0x1290
[  369.564469]  [<ffffffff9005c14d>] path_openat+0xcd/0x5a0
[  369.632109]  [<ffffffff9004db21>] ? __sb_end_write+0x31/0x70
[  369.701638]  [<ffffffff9005dabd>] do_filp_open+0x4d/0xb0
[  369.768520]  [<ffffffff9006b877>] ? __alloc_fd+0x47/0x170
[  369.838023]  [<ffffffff90049a64>] do_sys_open+0x124/0x220
[  369.905992]  [<ffffffff90049b7e>] SyS_open+0x1e/0x20
[  369.972396]  [<ffffffffc07c6e72>] cb_sys_open+0xd2/0x260 [event_collector_1_10_10180]
[  370.044272]  [<ffffffff9058fede>] system_call_fastpath+0x25/0x2a
[  370.112481] INFO: task python:2651 blocked for more than 120 seconds.
[  370.180969] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  370.252211] python          D ffff9f65ffd1ac80     0  2651      1 0x00000080
[  370.326159] Call Trace:
[  370.393949]  [<ffffffff90582299>] schedule+0x29/0x70
[  370.466681]  [<ffffffff90096f55>] fanotify_handle_event+0x265/0x3a0
[  370.538872]  [<ffffffff8fec7450>] ? wake_up_atomic_t+0x30/0x30
[  370.616161]  [<ffffffff90093328>] fsnotify+0x388/0x460
[  370.685210]  [<ffffffff90104e2e>] security_file_open+0x6e/0x70
[  370.756797]  [<ffffffff90048339>] do_dentry_open+0xb9/0x2c0
[  370.831889]  [<ffffffff90104882>] ? security_inode_permission+0x22/0x30
[  370.901776]  [<ffffffff900485da>] vfs_open+0x5a/0xb0
[  370.969224]  [<ffffffff90056b8a>] ? may_open+0x5a/0x120
[  371.037532]  [<ffffffff900592b6>] do_last+0x1f6/0x1290
[  371.104838]  [<ffffffff9005c14d>] path_openat+0xcd/0x5a0
[  371.172873]  [<ffffffff8ff3eb1f>] ? __audit_inode+0x1cf/0x3e0
[  371.241749]  [<ffffffff9005dabd>] do_filp_open+0x4d/0xb0
[  371.311176]  [<ffffffff9006b877>] ? __alloc_fd+0x47/0x170
[  371.379058]  [<ffffffff90049a64>] do_sys_open+0x124/0x220
[  371.446146]  [<ffffffff90049b7e>] SyS_open+0x1e/0x20
[  371.511701]  [<ffffffffc07c6e72>] cb_sys_open+0xd2/0x260 [event_collector_1_10_10180]
[  371.582996]  [<ffffffff9058fede>] system_call_fastpath+0x25/0x2a
[  371.651738] INFO: task mdsd:2763 blocked for more than 120 seconds.
[  371.724490] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  371.800277] mdsd            D ffff9f65ffc1ac80     0  2763   2651 0x00000080
[  371.875582] Call Trace:
[  371.945871]  [<ffffffff90582299>] schedule+0x29/0x70
[  372.016978]  [<ffffffff90096f55>] fanotify_handle_event+0x265/0x3a0
[  372.089328]  [<ffffffff8fec7450>] ? wake_up_atomic_t+0x30/0x30
[  372.162681]  [<ffffffff90093328>] fsnotify+0x388/0x460
[  372.231547]  [<ffffffff90104e2e>] security_file_open+0x6e/0x70
[  372.307128]  [<ffffffff90048339>] do_dentry_open+0xb9/0x2c0
[  372.378025]  [<ffffffff90104882>] ? security_inode_permission+0x22/0x30
[  372.452340]  [<ffffffff900485da>] vfs_open+0x5a/0xb0
[  372.521615]  [<ffffffff90056b8a>] ? may_open+0x5a/0x120
[  372.591077]  [<ffffffff900592b6>] do_last+0x1f6/0x1290
[  372.660662]  [<ffffffffc047f089>] ? xfs_iunlock+0xa9/0x120 [xfs]
[  372.730134]  [<ffffffff9005c4c3>] path_openat+0x443/0x5a0
[  372.799664]  [<ffffffff9005dabd>] do_filp_open+0x4d/0xb0
[  372.873478]  [<ffffffff9006b877>] ? __alloc_fd+0x47/0x170
[  372.941518]  [<ffffffff90049a64>] do_sys_open+0x124/0x220
[  373.009547]  [<ffffffff90049b7e>] SyS_open+0x1e/0x20
[  373.076674]  [<ffffffffc07c6e72>] cb_sys_open+0xd2/0x260 [event_collector_1_10_10180]
[  373.148444]  [<ffffffff9058fede>] system_call_fastpath+0x25/0x2a

### If relevant, please share your mount command.
/etc/mount_rdata.sh contains
/usr/bin/blobfuse /rdata --tmp-path=/mnt/resource/blobfusetmp_rdata --use-attr-cache=true -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/etc/connection-rdata.cfg --log-level=LOG_DEBUG --use-adls=true -o allow_other

/etc/fstab contants
/etc/mount_rdata.sh /rdata fuse _netdev

**Comment by vibhansa-msft** [comment]
As per the shared dmesg lot of processes are getting blocked for 120 seconds (blobfuse, syslog, imjournal, python, mdsd ...)
You need to check your cpu usage and disk usage while this is hit. This indicate a resource crunch on the VM and processes are starving mostly.

**Comment by minhtrieu-aemo** [comment]
Turned out the problem was due to the "Microsoft Defender Advanced Threat Protection"

After excluding the cache directory from scanning it fixed the issue. 
mdatp exclusion folder add --path "/mnt/resource/"
