### ISSUE TITLE
Failure to mv file if sas token is used with ADLS

### ISSUE THREAD

**Issue by cris-b** [Azure/azure-storage-fuse#577]
### Which version of the blobfuse was used?

1.3.6

### Which OS (please include version) are you using?

rhel 7.8

### What problem was encountered?

When mounting with an account sas token with full permissions, mv failed to work ('permission denied').  When same share is mounted with an account key the mv works.   With both schemes doing a cp and then a rm works fine.

Using --use-adls=false or omitting the option makes the rename work.

### Have you found a mitigation/solution?

No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

with acount key:

Mar  9 16:17:42 baseautomation2devhighmem blobfuse[5745]: ==> REQUEST/RESPONSE :: PUT https://xxx.dfs.core.windows.net/data/j?&Content-Length=0&User-Agent=azure-storage-fuse/1.3.6&x-ms-date=Tue, 09 Mar 2021 16:17:42 GMT&x-ms-version=2018-11-09&x-ms-rename-source=/data/i&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 201 :: REQ ID : b8378e50-f01f-0019-02ff-14229b000000

with sas token:

Mar  9 16:16:54 baseautomation2devhighmem blobfuse[25947]: ==> REQUEST/RESPONSE :: PUT https://xxxx.dfs.core.windows.net/data/j?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacupx&se=2021-03-09T23:15:22Z&st=2021-03-09T15:15:22Z&spr=https&sig=REDACTED?&Content-Length=0&User-Agent=azure-storage-fuse/1.3.6&x-ms-date=Tue, 09 Mar 2021 16:16:54 GMT&x-ms-version=2018-11-09&x-ms-rename-source=/data/i&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 403 :: REQ ID : 26d993f1-a01f-0004-58ff-142f27000000
Mar  9 16:16:54 baseautomation2devhighmem blobfuse[25947]: :
Mar  9 16:16:54 baseautomation2devhighmem blobfuse[25947]: Failure to rename source file /i in container.  Errno = 403.
Mar  9 16:16:54 baseautomation2devhighmem blobfuse[25947]: Failed to rename /i, err : 403

one thing I have noticed is that when doing a cp the PUT goes via the blob.core.windows.net service, even though use-adsl=true.  When doing mv the PUT codes via dfs.core.windows.net

Mar  9 16:31:24 baseautomation2devhighmem blobfuse[5745]: ==> REQUEST/RESPONSE :: PUT https:/xxxx.blob.core.windows.net/data/k?&Content-Length=0&x-ms-blob-type=BlockBlob&User-Agent=azure-storage-fuse/1.3.6&x-ms-date=Tue, 09 Mar 2021 16:31:24 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 201 :: REQ ID : eb19bfc2-e01e-0077-0101-1577b4000000
Mar  9 16:31:24 baseautomation2devhighmem blobfuse[5745]: Successfully uploaded file /k to blob k.

Mar  9 16:32:55 baseautomation2devhighmem blobfuse[10231]: ==> REQUEST/RESPONSE :: PUT https://xxxx.blob.core.windows.net/data/l?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacupx&se=2021-03-09T23:15:22Z&st=2021-03-09T15:15:22Z&spr=https&sig=REDACTED?&Content-Length=0&x-ms-blob-type=BlockBlob&User-Agent=azure-storage-fuse/1.3.6&x-ms-date=Tue, 09 Mar 2021 16:32:55 GMT&x-ms-version=2018-11-09&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 201 :: REQ ID : c18d4d83-901e-001f-2e01-151124000000

**Comment by NaraVen** [comment]
@cris-b, This is a bug in the SAS token service. The SAS Tokens do not support ADLS Gen 2 very well. you will get the same error for AccountSAS token or ServiceSAS token or blobSASToekn. . The workaround is to cp to a new file and delete the old file.
