### ISSUE TITLE
TwinBERT training failure when saving checkpoints

### ISSUE THREAD

**Issue by Calotte** [Azure/azure-storage-fuse#579]
### Which version of the blobfuse was used?
blobfuse 1.1.1

### Which OS (please include version) are you using?
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

### What problem was encountered?
When save checkpoint, mv to the mount blob will always failed in the last, showing "Input/output error"
The relative log is here:
save model to /home/jianjzh/tmp/model.checkpoint_0_43381s5UdIG
move model to /databloboutput/jianjzh/aether/dac7d943-ce68-4bc8-8cbd-b987f6a284c1_14f05ac7_a171f3ad-caec-4831-90ee-aa98d08420c3_1614783439.3954065/output//model.checkpoint_0_43381
mv: failed to close '/databloboutput/jianjzh/aether/dac7d943-ce68-4bc8-8cbd-b987f6a284c1_14f05ac7_a171f3ad-caec-4831-90ee-aa98d08420c3_1614783439.3954065/output//model.checkpoint_0_43381': Input/output error

### Have you found a mitigation/solution?
No
### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

**Comment by vibhansa-msft** [comment]
Kindly move to latest blobfuse v1.3.6 and let me know if you still hit the case.

**Comment by NaraVen** [comment]
Input/Output error suggests you are not able to write, does the storage key you are using have write permissions to your storage account. Does the user account in Linux have write permissions to the blobfuse mount. If not did you mount with the -o allow_other option?

**Comment by vibhansa-msft** [comment]
Closing this as we have not received any input on this. Feel free to reopen if the issue persists.
