### ISSUE TITLE
I can't mount containers anonymously

### ISSUE THREAD

**Issue by AntonioND** [Azure/azure-storage-fuse#588]
### Which version of the blobfuse was used?

blobfuse 1.3.6

### Which OS (please include version) are you using?

Ubuntu 18.04. This is all done inside WSL2. I'm running it inside Docker using the Docker Desktop WSL 2 backend.

### What problem was encountered?

I can't mount containers in an anonymous way. By searching the codebase I've found the class ``anonymous_credential`` here https://github.com/Azure/azure-storage-fuse/blob/d9e05f454a9cd9cee5060daed47472c36b7e6d99/cpplite/include/storage_credential.h#L81-L85 but it isn't actually used anywhere. The other ``***_credential`` classes are used in some files inside ``blobfuse/src``. It looks like anonymous connections aren't supported: https://github.com/Azure/azure-storage-fuse/blob/b85faed5caf873c0ada1485732dc9d8678e19a87/blobfuse/src/BlockBlobBfsClient.cpp#L8-L28

In case I'm completely wrong, how is the ``fuse_connection.cfg`` supposed to look like in this case? My file looks like this:
```
accountName myaccountname
authType
containerName publiccontainer
```
I've also tried like this without success:
```
accountName myaccountname
containerName publiccontainer
```
My Dockerfile is:
```
FROM ubuntu:18.04

RUN apt update && apt install -y wget

RUN wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

RUN dpkg -i packages-microsoft-prod.deb
RUN apt update && apt install -y blobfuse fuse libcurl4-gnutls-dev

COPY fuse_connection.cfg /
RUN chmod 600 fuse_connection.cfg

COPY test.sh /
RUN chmod 755 /test.sh
ENTRYPOINT ["/test.sh"]
```
And the test.sh script is:
```
#!/bin/bash

mkdir /mnt/resource/blobfusetmp -p
mkdir ~/mycontainer -p

blobfuse --version

blobfuse ~/mycontainer \
    --tmp-path=/mnt/resource/blobfusetmp \
    --config-file=/fuse_connection.cfg \
    -o attr_timeout=240 \
    -o entry_timeout=240 \
    -o negative_timeout=120

# Has it worked?
ls ~/mycontainer
```

### Have you found a mitigation/solution?

I can mount the container if I use some kind of authentication, but this is not really a solution, I used authentication just to make sure that everything else was working.

**Comment by vibhansa-msft** [comment]
Your observation is correct. Blobfuse does not support "anonymous" mounting. Can you describe in what use case you need anonymous access to the container.

**Comment by vibhansa-msft** [comment]
This was supported earlier but due to non-traceability in case of billing or security related concerns raised by customers this has been discontinued.
