### ISSUE TITLE
Is there any way to mount a container without setting a cache directory or any decent way to drop fuse caches?

### ISSUE THREAD

**Issue by hpaknia** [Azure/azure-storage-fuse#589]
### Which version of the blobfuse was used?
```
1.3.6
```

### Which OS (please include version) are you using?
```
Centos 7
```

### What problem was encountered?
A container is mounted in a Centos 7 machine using blobfuse. A file is being updated externally. While tailing the file, updates to the file arrives every couple of minutes, even thought the file is updated every second.
I used `auto_cache` to mount the volume, hoping on each open the caches are invalidated, no avail. 
Because the aforementioned mount is going to be used in a read-only manner, it's fine to invalidate the caches frequently.

### Have you found a mitigation/solution?
The only working solution is if the file in the blobfuse directory is deleted.  For example to invalidate the cache of `/path/file.txt`, I have to delete `/tmp/blobfuse_cache/root/path/file.txt`.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
This is a question, not a bug.

### If relevant, please share your mount command.
In fstab:
```
blobfuse /mnt/mycontainer fuse defaults,_netdev,auto_cache,entry_timeout=10,negative_timeout=10,--tmp-path=/tmp/blobfuse_cache,--config-file=/etc/.blobfuse,allow_other 0 0
```

**Comment by vibhansa-msft** [comment]
Default time out for cache is 120 seconds and hence the delay in updates. Kindly add "--file-cache-timeout-in-seconds=0" in your mount command.

**Comment by hpaknia** [comment]
I should have double checked the main readme. Thanks, it worked.
