### ISSUE TITLE
Blob fuse set-content-type error

### ISSUE THREAD

**Issue by AmpliNet** [Azure/azure-storage-fuse#592]
### Which version of the blobfuse was used?
blobfuse 1.3.6

### Which OS (please include version) are you using?
Ubuntu 18

### What problem was encountered?
When upload files conten-type of files are changed to application/octet-stream and when i use option --set-content-type=true fails, return this error:

sudo blobfuse /homr/sitebr --tmp-path=/home/blobfusetmp  --config-file=/home/fuse.cfg  -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --set-content-type=true

fuse: unknown option `--set-content-type=true'

I need help.

**Comment by vibhansa-msft** [comment]
--set-content-type CLI option is not available in 1.3.6. To try out this feature you need to move to our 1.3.7-beta release.
https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.7-beta
