### ISSUE TITLE
Avoiding listBlob calls

### ISSUE THREAD

**Issue by saswatac** [Azure/azure-storage-fuse#596]
### Which version of the blobfuse was used?

1.3.6

### Which OS (please include version) are you using?

```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### What problem was encountered?

 I was investigating into why there are high number of list container calls in our storage account. There seems to be a list  call called for each blob downloaded.

The attached log shows the debug output of blobfuse when running  "cat" on a single file. 
According to the logs, there is an initial list call with the prefix key, followed by the get api call.

Our workload has high rate of I/O , and these list container calls are contributing quite a lot to our billing as List apis are 10x the cost of get. When i look at the storage account metrics, the number of ListBlob calls are  greater than number of GetBlob calls which is not consistent with what i would expect.

I am wondering if the list container calls can be avoided, as any metadata that may be needed from the list calls can also be obtained by get blob api itself or through get blob metadata.

### Have you found a mitigation/solution?

no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

[blobfuse.log](https://github.com/Azure/azure-storage-fuse/files/6415018/blobfuse.log)

### If relevant, please share your mount command.

```
blobfuse $mount_dir --container-name=$BUCKET --tmp-path=TMP_PATH -o allow_other
```

**Comment by NaraVen** [comment]
To avoid frequent lists please add the following mount options --use-attr-cache=true - -o attr_timeout=240 - -o entry_timeout=240 - -o negative_timeout=240 
blobfuse 1.3.7 is the latest, upgrading to 1.3.7 will give you an extra option to prevent the initial list on mount. --cancel-list-on-mount-seconds=0

**Comment by saswatac** [comment]
Thank you for the quick reply, I upgraded to 1.3.7 and tried these option and this does reduce the lists when reading data. But for writes, i still see the lists. 

Here are the logs when i copy a single file

[blobfuse_write.log](https://github.com/Azure/azure-storage-fuse/files/6416209/blobfuse_write.log)

Mount command used

```
blobfuse $MOUNT_DIR --container-name=$BUCKET --tmp-path=/mnt/data/blobfusetmp1 -o allow_other --use-attr-cache=true -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=240 --log-level=LOG_DEBUG
```

Is there any settings to prevent the list on each write call?

**Comment by saswatac** [comment]
Wrt to the reads, if i use option "use-attr-cache" , are the timeouts important ? I tried changing the timeout values, but it looks like attributes gets cached, there are no further list calls, which looks desirable to me. I am using blob fuse for running deep learning training where the files are accessed multiple times, but the frequency at which it will be accessed depends on the dataset, so it is tricky to figure out the right timeouts. But it should be all good if the cache does not expire.

**Comment by NaraVen** [comment]
--use-attr-cache caches the attributes in the memory, so if memory is repurposed it will get cleared, the other timeouts refer to fuse kernel cache. It is recommended to use both. List call for writes is happening to get the latest file content in order to make sure it overwrites the latest version of the file not the attributes so it cannot be avoided. There is a --file-cache-timeout-in-seconds that caches the file contents to the disk. In the log you have attached I see that it is a new file so anyway it will not be in the cache, it will list from storage to verify if it is indeed a new file.

**Comment by saswatac** [comment]
Thank you for the explanation. i am still curious to know why list from storage is necessary to verify if it is a new file. Is it possible to use get blob properties or get blob metadata instead?

**Comment by NaraVen** [comment]
those GET properties won't work for directory blobs that's why list.

**Comment by saswatac** [comment]
ok i see , thank you.
