### ISSUE TITLE
Unable to start blobfuse due to a lack of credentials

### ISSUE THREAD

**Issue by mkea-coder** [Azure/azure-storage-fuse#597]
### Which version of the blobfuse was used?

1.3.6

### Which OS (please include version) are you using?

Ubuntu 18.04.1

### What problem was encountered?
3 VM's all setup the same way 1 is able to mount, 2 fail to mount with "Unable to start blobfuse due to a lack of credentials"

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

Do not see a syslog file

### If relevant, please share your mount command.
sudo blobfuse /azure-archive --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/ionadmin/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Comment by NaraVen** [comment]
Could you please upgrade to 1.3.7 and set log level to --log-level=LOG_DEBUG. This way it will show the errorno and we can identify network issues if any.

**Comment by mkea-coder** [comment]
Haven't had a chance to run the upgrades, but one of the non mounting ones now errors with "
fuse: if you are sure this is safe, use the 'nonempty' mount option"

**Comment by NaraVen** [comment]
you can specify --empty-dir-check=false to overcome your latest issue and surface your original issue but please mount with --log-level=LOG_DEBUG and share the log otherwise we wont be able to provide any insights.

**Comment by mkea-coder** [comment]
Thanks for steering me in the right direction, this one turned out to be a DNS issue on the two non working ones.
