### ISSUE TITLE
Cannot mount with blobfuse using service principal auth

### ISSUE THREAD

**Issue by taoisu** [Azure/azure-storage-fuse#598]
### Which version of the blobfuse was used?
1.3.7

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
Basically I have a service principal that is "Contributor" of our subscription, there's a storage account in that subscription that I want to mount, I'm trying to do something like this:

AZURE_STORAGE_SPN_CLIENT_SECRET="$SP_PASSWORD" \
AZURE_STORAGE_SPN_CLIENT_ID="$SP_CLIENT_ID" \
AZURE_STORAGE_SPN_TENANT_ID="$SP_TENANT_ID" \
AZURE_STORAGE_AUTH_TYPE="SPN" \
blobfuse /tmp/vdimodels_jobs --tmp-path=/mnt/ramdisk/bfjobstmp --config-file=/tmp/vdimodels_jobs.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

The cfg file looks like this:
accountName vdimodels
containerName jobs
authType SPN

When I run the command above, I got error: "Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups."

### Have you found a mitigation/solution?

No.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

![image](https://user-images.githubusercontent.com/30015018/117493765-466c7e00-af28-11eb-85d8-6ccdb91aba6a.png)

### If relevant, please share your mount command.

In the "problem encountered" section

**Comment by NaraVen** [comment]
environment variables for SPN client Id is not getting picked up. Are they accessible to the user mounting blobfuse?

One more point also,  Once your auth starts working you still need both contributor and storage blob contributor permissions.

**Comment by taoisu** [comment]
Thanks @NaraVen! I've tried adding clientId into the cfg and also checked the permissions. Looks like I need also make my sp a "Storage Blob Data Contributor", after I followed the steps suggested it's now working! Thanks Nara!
