### ISSUE TITLE
Blobfuse create invalid files when create a folder on Static Web Site Blob

### ISSUE THREAD

**Issue by AmpliNet** [Azure/azure-storage-fuse#601]
### Which version of the blobfuse was used?
Blobfuse 1.3.7

### Which OS (please include version) are you using?
Linux Debian 

### What problem was encountered?
Blobfuse create a file with same name as directory in blob used by static webpages and file created not disponible for deletion in mounted directory

### Have you found a mitigation/solution?
I need help to solve yhis issue 

![image](https://user-images.githubusercontent.com/51324273/118007171-47cfe900-b322-11eb-979f-fb22eaf181bf.png)

**Comment by NaraVen** [comment]
First let me understand your scenario. you are trying to go to http://mysite.azure.com/page-data and instead of showing the index.html in that website directory it is showing you the zero byte direcory-blob marker that blobfuse creates when the directory is empty.
The workaround for this is to open storage explorer or go to the Azure portal and delete the zero byte blob file. Since your directory is not empty it will keep the directory. Please note that if have an empty directory and no zero byte blob marker the directory won't mount to your file system. It is not advisable to delete it if your directory is empty. 
From a blobfuse/ Azure Storage perspective we need to create this empty zero byte directory-blob markers so this is a feature of blobfuse and we cannot remove it.

**Comment by AmpliNet** [comment]
Our scenario is as follows: 

We have a virtual linux machine running an application that calls a gatsby html generator, when it finishes generating files, we copy the files to the folder where the azure blob is mounted.

when gatsby generate files in another folder i copy files by cp -a command.

The problem is when copy it generates a0 byte file and after creating the folder and  when we open the browser instead of presenting the website and calling the index.html that is in the created folder it downloads the file with same name of the folder

**Comment by NaraVen** [comment]
thank you confirming your scenario. It is in line with what I understood it as. Yes so, the workaround is deleting the zero byte directory-blob marker from Azure portal or Azure Storage explorer.

**Comment by AmpliNet** [comment]
the problem is that we are using this linux server to automate the process of publishing the site we need to delete or copy the files and generate new folders with random names that are not foreseen ie we need a parameter in the mount command so that it does not generate this 0byte file or one flag to see these files for i delete.

**Comment by NaraVen** [comment]
There is no parameter for this. you can automate the deletion of these zero byte directory-blob markers by writing a piece of code that will go to the blob and list all the files with the metadata hdi_isfolder= true. 
you can use this for reference https://pypi.org/project/azure-storage-blob/
Sample python code would be 
  try:
        blob_name_list = []
// refer to the link above to create a a blob_client
        source_blob_list = blob_client.list_blobs(name_starts_with==None, include=["metadata"])
        
        for blob in source_blob_list:
            if(blob.metadata['hdi_isfolder"] != 'None'):
                 delete_blob(blob);
    except Exception as ex:
        print ("Error: " + str(ex))

**Comment by AmpliNet** [comment]
ok, but if i try to use the azure-storage-blob pypi, i don't need to use the right blobfuse? because it has a function to upload files directly as well.

**Comment by NaraVen** [comment]
Yes, Azure Storage SDK's python or .Net are excellent alternatives to blobfuse. you will not have the zero byte marker file issues there. The purpose of blobfuse is to have a virtual filesystem available . It is not the best choice for purely uploading or downloading files from blob.

**Comment by NaraVen** [comment]
closing this zero directory marker is a blobfuse feature and we suggested a workaround and an alternate for blobfuse.
