### ISSUE TITLE
libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fscavo** [Azure/azure-storage-fuse#603]
### Which version of the blobfuse was used?
1.3.7

### Which OS (please include version) are you using?
ubuntu:20.04 (Docker image)

### What problem was encountered?
blobfuse: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

### Have you found a mitigation/solution?
It works fine with ubuntu:16.04 and https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

**Comment by NaraVen** [comment]
Did you do a sudo apt install blobfuse or did you compile it from source code? It appears that the libcurl_gnutls.so.4 is not pointing to the latest library version. Could you do a ls -al /usr/lib/x86_64-linux-gnu/libcurl* and see if there is a symlink libcurl_gnutls.so.4 pointing to the latest 4.4 of 4.5 of libcurl_gnutls?  If you dont then uninstall blobfuse, do a sudo apt update and then install blobfuse again.

Also what did you mean by docker image?

**Comment by fscavo** [comment]
> Did you do a sudo apt install blobfuse or did you compile it from source code?
I have used apt install with privileged=true. It works fine on ubuntu:20.04 WSL2 but not in the docker or k8s.

This is the script that I've used to mount the blob container
```bash
export AZURE_STORAGE_ACCOUNT=xxxxx \
export AZURE_STORAGE_ACCESS_KEY=xxxxx \
&& apt-get update -y \
&& apt-get install --no-install-recommends -y ca-certificates wget \
&& wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb \
&& dpkg -i packages-microsoft-prod.deb \
&& apt-get update -y \
&& apt-get install -y --no-install-recommends blobfuse \
&& mkdir -p /mnt/container /tmp/$AZURE_STORAGE_ACCOUNT && blobfuse /mnt/container \
  --container-name=container \
  --tmp-path=/tmp/$AZURE_STORAGE_ACCOUNT \
  -o attr_timeout=240 \
  -o entry_timeout=240 \
  -o negative_timeout=120
```

**Comment by NaraVen** [comment]
Understood so you are installing blobfuse. Are you running the above script on the host and sharing it with the docker container? or 
are running the above to create a docker image and run the last linein the above script in a privileged docker mode.

For K8 the best solution is to use our blob-csi-driver https://github.com/kubernetes-sigs/blob-csi-driver. you can install it using helm charts or kubectl

**Comment by fscavo** [comment]
> Understood so you are installing blobfuse. Are you running the above script on the host and sharing it with the docker container? or
> are running the above to create a docker image and run the last linein the above script in a privileged docker mode.
I need to run this script from init container. The following setup works fine with the version 16.04 of blobfuse but never with 18.04 and 20.04!
```yaml
initContainers:
      - name: init-logstash
        imagePullPolicy: Always
        image: ubuntu:16.04
        command:
        - sh
        - -c
        - |
          export AZURE_STORAGE_ACCOUNT=nextplatform \
          export AZURE_STORAGE_ACCESS_KEY=Ncjeq3YJc7dmqBBg3T9uvvJs560qgVNNmGh1sNAwBruCm2rwaWoj62gR0TWIvYpOAQPtNwTDk4PEC0xfa4f96g== \
          && apt-get update -y \
          && apt-get install --no-install-recommends -y ca-certificates apt-transport-https wget \
          && wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb \
          && dpkg -i packages-microsoft-prod.deb \
          && apt-get update -y \
          && apt-get install -y --no-install-recommends blobfuse \
          && mkdir -p /mnt/deployment-c4htest /tmp/$AZURE_STORAGE_ACCOUNT && blobfuse /mnt/deployment-c4htest \
          --container-name=deployment-c4htest \
          --tmp-path=/tmp/$AZURE_STORAGE_ACCOUNT \
          -o attr_timeout=240 \
          -o entry_timeout=240 \
          -o negative_timeout=120
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
```

**Comment by NaraVen** [comment]
Could you please add this line 
****
RUN apt-get update && clean-install ca-certificates pkg-config libfuse-dev cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev wget
***
before the wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb

**Comment by fscavo** [comment]
> Could you please add this line
> 
> RUN apt-get update && clean-install ca-certificates pkg-config libfuse-dev cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev wget
> 
> before the wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb

Is **clean-install** a command line? Because I could not find it

**Comment by NaraVen** [comment]
Ignore clean-install, it isa local script so I call it in my image 
RUN apt-get update && apt-get install ca-certificates pkg-config libfuse-dev cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev wget

**Comment by fscavo** [comment]
> Ignore clean-install, it isa local script so I call it in my image
> RUN apt-get update && apt-get install ca-certificates pkg-config libfuse-dev cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev wget

It now gives this error `fuse: device not found, try 'modprobe fuse' first`

**Comment by NaraVen** [comment]
cool, it went past that error, pls change this line "apt-get install -y --no-install-recommends blobfuse \ "to
"apt-get install -y --no-install-recommends blobfuse fuse \"

**Comment by NaraVen** [comment]
then please check what error modprobe fuse gives.

**Comment by fscavo** [comment]
> then please check what error modprobe fuse gives.

no config filedone reading env vars

**Comment by NaraVen** [comment]
these

> > then please check what error modprobe fuse gives.
> 
> no config filedone reading env vars

this is the blobfuse output.
My request is to add modprobe fuse as a line to the script and share the output. It will tell why fuse is failing

**Comment by NaraVen** [comment]
Since the original problem is resolved with the extra apt-gets closing this one. Please feel free to open a new bug for newer issues if any.
