### ISSUE TITLE
Linux file list commands is only showing 5000 files in a folder

### ISSUE THREAD

**Issue by minhtrieu-aemo** [Azure/azure-storage-fuse#604]
### Which version of the blobfuse was used?

blobfuse-1.3.7-1.el7_9.x86_64

### Which OS (please include version) are you using?

Azure - Red Hat Enterprise Linux Server release 7.7 (Maipo)

### What problem was encountered?

We have several folders, some containing 12000 files (according to Storage Explorer), yet when i do a "ls -la | wc -l" in Linux it says I only have 5000 files. How do I get a listing of the remaining of files outside of 5000? 

### Have you found a mitigation/solution?

No

### If relevant, please share your mount command.

/usr/bin/blobfuse /xxxxxx --tmp-path=/mnt/resource/blobfusetmp_xxxxxx  --use-adls=true --use-attr-cache=true -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/etc/blobcredentials/connection-xxxxxx.cfg --log-level=LOG_DEBUG -o allow_other

**Comment by vibhansa-msft** [comment]
Can you enable LOG_DEBUG and share the log which appear when you do the 'ls' operation.

**Comment by minhtrieu-aemo** [comment]
I takes a few minutes for "ls -la" to run and return something. During that time I dont see anything in the messages log other then the following. 

Jun  1 23:31:01 SERVERXXX systemd: Created slice User Slice of root.
Jun  1 23:31:01 SERVERXXX systemd: Started Session 15059 of user root.
Jun  1 23:31:01 SERVERXXX systemd: Removed slice User Slice of root.
Jun  1 23:31:06 SERVERXXX journal: Suppressed 1725 messages from /system.slice/nop\x2dtrace\x2dlibrary\x2dsit.mount
Jun  1 23:31:36 SERVERXXX journal: Suppressed 2784 messages from /system.slice/nop\x2dtrace\x2dlibrary\x2dsit.mount
Jun  1 23:32:01 SERVERXXX systemd: Created slice User Slice of root.
Jun  1 23:32:01 SERVERXXX systemd: Started Session 15060 of user root.
Jun  1 23:32:01 SERVERXXX systemd: Removed slice User Slice of root.
Jun  1 23:32:06 SERVERXXX journal: Suppressed 2815 messages from /system.slice/nop\x2dtrace\x2dlibrary\x2dsit.mount

The logs appear to be working, when i attempt to 'cd' into a folder that doesn't exists, the following shows up.

Jun  1 23:35:48 SERVERXXX blobfuse[8729]: ==> REQUEST/RESPONSE :: HEAD https://xxxxxxxxxx.dfs.core.windows.net/nop-trace-library/test?&User-Agent=Azure-Storage-F
use/1.3.7&x-ms-date=Tue, 01 Jun 2021 13:35:48 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------
------------RESPONSE Status :: 404 :: REQ ID : c40a65d3-601f-0003-1ceb-568c12000000
Jun  1 23:35:48 SERVERXXX blobfuse[8729]: File does not currently exist on the storage or cache

**Comment by vibhansa-msft** [comment]
Kindly share the entire log while the 'ls' was going on till it completed. There will be some logs when the 'ls' starts and the resultant logs may give hint on what was returned from the store.

**Comment by minhtrieu-aemo** [comment]
Nothing shows up in the log files when I do 'ls'. I have done more testing and found that if I remove "--use-adls=true" and revert back to blob then the file listing will show all files. I notice that 'ls' works much faster when I dont use "--use-adls=true".

The issue is when i dont have  "--use-adls=true" then i can no longer delete directories using rmdir. The rmdir command causes the SSH session to hang. The log files will show the following messages repeated.  

Jun  2 18:04:09 SYDDEVINSRST02 blobfuse[30288]: ==> REQUEST/RESPONSE :: DELETE https://xxxxxxxxx.blob.core.windows.net/nop-trace-library/testfolder?&x-ms-delete-snapshots=inclu
de&User-Agent=azure-storage-fuse/1.3.7&x-ms-date=Wed, 02 Jun 2021 08:04:09 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------
------------------------------RESPONSE Status :: 500 :: REQ ID : 54c23626-801e-00b2-3485-579207000000
Jun  2 18:04:09 SYDDEVINSRST02 blobfuse[30288]: ==> REQUEST/RESPONSE :: DELETE https://foreplxinputs1sitstaaue.blob.core.windows.net/nop-trace-library/testfolder?&x-ms-delete-snapshots=inclu
de&User-Agent=azure-storage-fuse/1.3.7&x-ms-date=Wed, 02 Jun 2021 08:04:09 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------
------------------------------RESPONSE Status :: 500 :: REQ ID : 02929fc4-c01e-0025-1485-57c40a000000
Jun  2 18:04:09 SYDDEVINSRST02 blobfuse[30288]: ==> REQUEST/RESPONSE :: DELETE https://xxxxxxxxx.blob.core.windows.net/nop-trace-library/testfolder?&x-ms-delete-snapshots=inclu
de&User-Agent=azure-storage-fuse/1.3.7&x-ms-date=Wed, 02 Jun 2021 08:04:09 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------
------------------------------RESPONSE Status :: 500 :: REQ ID : c123b76c-101e-0044-5585-57e749000000
Jun  2 18:04:09 SYDDEVINSRST02 blobfuse[30288]: ==> REQUEST/RESPONSE :: DELETE https://xxxxxxxxx.blob.core.windows.net/nop-trace-library/testfolder?&x-ms-delete-snapshots=inclu
de&User-Agent=azure-storage-fuse/1.3.7&x-ms-date=Wed, 02 Jun 2021 08:04:09 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------
------------------------------RESPONSE Status :: 500 :: REQ ID : 27e86c4d-301e-0088-3485-57887f000000

**Comment by vibhansa-msft** [comment]
Is your account a Gen-2 Account ? Only for gen-2 account you need to use "--use-adls=true" CLI option.

**Comment by minhtrieu-aemo** [comment]
It is a Gen-2 Storage account. When we use "--use-adls=true" we fall back into the original problem of being able to only list the first 5000 files in a container/folder. 

Maybe it to do with the maxResults being omitted? 
https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/list

**Comment by vibhansa-msft** [comment]
Service by-default returns back at max 5000 elements in list api. If there are more elements it sends back a token which we need to send back for the next batch of results. If we do not receive any token back then we conclude that listing is over. For that reason I asked for a complete log in debug mode. Only looking at the full logs I can confirm a thing on this.

**Comment by vibhansa-msft** [comment]
I am able to reproduce this issue locally. Will provide a fix soon.

**Comment by minhtrieu-aemo** [comment]
Sorry had to update rsyslog config for debugs to actually show up in the log files. 
Log file is attached to this message
[syslog.txt](https://github.com/Azure/azure-storage-fuse/files/6597739/syslog.txt)

**Comment by vibhansa-msft** [comment]
This has been fixed in 1.3.8, kindly upgrade. 
https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.8
