### ISSUE TITLE
test code review stream

### ISSUE THREAD

**Issue by jianjunliu** [Azure/azure-storage-fuse#606]
rt

[blockfs] lib/file.cc (Lines 32-33)

```

  int64_t ret = FileStore::Instance()->dev()->PwriteDirect(

```

[Open in IDE](https://api.codestream.com/c/YL7fJomVFHOf30TQ/XQVT4az0Sm27G-mJgv0Kcw?marker=60bef4bebfb7ba7520f6657b&ide=default&src=GitHub)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by vibhansa-msft** [comment]
Sorry din't understand, what is this about ? What issue you are facing ?

**Comment by NaraVen** [comment]
@jianjunliu , we are sorry, this issue appears robo generated , so we have to close this.
