### ISSUE TITLE
blobfuse mount with invalid credentials still returns succeed

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#613]
### Which version of the blobfuse was used?
v1.3.7

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
if SAS token is expired, blobfuse mount would also return success, and finally it was mounted to a local disk. I think if it's expired, blobfuse mount should return error directly.

 - Credentials I used:
```
export AZURE_STORAGE_SAS_TOKEN=?sv=2020-02-10&ss=bfqt&srt=c&sp=rwdlacuptfx&se=2021-06-08T19:37:31Z&st=2021-06-08T11:37:31Z&spr=https&sig=7BSNl9EaTed62n0HpXsDnerGZH0xQf5zbZtgI7GmWAQ%3D 
export AZURE_STORAGE_ACCOUNT=xxx
export AZURE_STORAGE_BLOB_ENDPOINT=xxx.blob.core.windows.net
```

**Comment by NaraVen** [comment]
did the mount options have --cancel-list-on-mount seconds

**Comment by andyzhangx** [comment]
> did the mount options have --cancel-list-on-mount seconds



> cancel-list-on-mount

@NaraVen We don't set `--cancel-list-on-mount`, does it matter?

**Comment by andyzhangx** [comment]
similar issue for mounting with account key, no matter what account & key is set, it always returns success, while actually that mount path could not be accessed since account name or key is not correct, I don't think that's a correct behavior. If credential is incorrect, then it should return error directly.

```
mkdir test6
export AZURE_STORAGE_ACCOUNT=xxx
export AZURE_STORAGE_ACCESS_KEY=xxx
blobfuse test6 --container-name=test --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120
# Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Unmounting blobfuse.
Unmounted blobfuse successfully.

# ls test6
ls: cannot access 'test6': Transport endpoint is not connected
```

**Comment by suweichieh** [comment]
Not sure why you say it always returns mount successfully. Maybe a screenshot of what you've seen would help. If the messages are showing as in your last post, then it is indicating the mount fails due to a lack of credentials, which matches what you described, if you used an expired sas token.
![Image 2](https://user-images.githubusercontent.com/86214743/122700650-42997e80-d27e-11eb-83a2-b5b003ba8f52.png)

**Comment by andyzhangx** [comment]
point is after blobfuse mount, it returns 0 exit code which means this command executes successfully, and after blobfuse mount, `test6` dir is actually mounted, you could execute the exact following commands:

```
mkdir test6
export AZURE_STORAGE_ACCOUNT=xxx
export AZURE_STORAGE_ACCESS_KEY=xxx
blobfuse test6 --container-name=test --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120
# Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Unmounting blobfuse.
Unmounted blobfuse successfully.

# echo $?
0
# ls test6
ls: cannot access 'test6': Transport endpoint is not connected
```

![image](https://user-images.githubusercontent.com/4178417/122704515-78dafc00-d286-11eb-9d70-d9ebb8d5f3a7.png)

**Comment by vibhansa-msft** [comment]
Off-late we have seen some customer issues due to cURL, where post mount cURL was not able to connect to storage container if one connection was made pre-mount. To overcome this, we moved to a policy of validating credentials and authenticating user post mount. This behavior depends on kernel version and cURL version. On a system, based on these versions, if blobfuse decides to do authentication post mount then mount will always return success. You can look for syslogs and it shall point to the failure in authentication step.

**Comment by vibhansa-msft** [comment]
Post mount when connection to azure storage is attempted, on failure it shall give an error log saying "Unable to start blobfuse. Failed to connect to the storage container. There might be something wrong about the storage config," and it shall un-mount  gracefully.

**Comment by andyzhangx** [comment]
> Off-late we have seen some customer issues due to cURL, where post mount cURL was not able to connect to storage container if one connection was made pre-mount. To overcome this, we moved to a policy of validating credentials and authenticating user post mount. This behavior depends on kernel version and cURL version. On a system, based on these versions, if blobfuse decides to do authentication post mount then mount will always return success. You can look for syslogs and it shall point to the failure in authentication step.

@vibhansa-msft thanks for the explanation, is it possible to return mount error directly if credentials are invalid? this authentication post mount is inconsistent with other linux fs mount, e.g. `mount -t cifs, nfs`, is there any flag to check credentials before mount? And I think you are changing the original behavior, in prior blobfuse release, it would turn mount error directly if credentials are invalid, shall we change to the original behavior by default? thanks.

**Comment by andyzhangx** [comment]
> Post mount when connection to azure storage is attempted, on failure it shall give an error log saying "Unable to start blobfuse. Failed to connect to the storage container. There might be something wrong about the storage config," and it shall un-mount gracefully.

@vibhansa-msft from the above commands I provided, it's still mounted even with invalid credentials, I think that's a bug

**Comment by vibhansa-msft** [comment]
Problem with moving back to old way is, many customers are hitting the handshake issue caused by cURL.  I do understand your point of doing the validation before hand, but think of situation where validation goes through but post mount blobfuse is not able to connect to storage container at all. We had to choose between these two failures. 
As of now there is no options to disable this, however there is a workaround to this. If the CURL version reported on your system is > 7.76 then blobfuse will still do the authentication pre-mount.

@andyzhangx : Graceful un-mount is expected if credentials were wrong. Can you share your blobfuse logs in debug mode when this did not go through.

**Comment by andyzhangx** [comment]
```
mkdir test6
export AZURE_STORAGE_ACCOUNT=xxx
export AZURE_STORAGE_ACCESS_KEY=xxx
blobfuse test6 --container-name=test --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120 --log-level=LOG_DEBUG
```

```
Jun 21 14:13:47 andydev blobfuse[23882]: CURL Version is 7.58.0
Jun 21 14:13:47 andydev blobfuse[23882]: ** Delaying tls init to post fork for older libcurl version
Jun 21 14:13:47 andydev blobfuse[23882]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 96: Making cache directory /tmp.
Jun 21 14:13:47 andydev blobfuse[23882]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 96: Making cache directory /tmp/blobfuse.
Jun 21 14:13:47 andydev blobfuse[23882]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 96: Making cache directory /tmp/blobfuse/root.
Jun 21 14:13:47 andydev blobfuse[23882]: Initializing blobfuse using BlockBlob
Jun 21 14:13:47 andydev blobfuse[23882]: Setup storage client
Jun 21 14:13:47 andydev blobfuse[23882]: Kernel version is 5.400000
Jun 21 14:13:47 andydev blobfuse[23882]: libcurl version is 7.580000
Jun 21 14:13:47 andydev blobfuse[23882]: ** Delaying authentication to post fork for older curl versions
Jun 21 14:13:47 andydev blobfuse[23884]: azs_init ran
Jun 21 14:13:47 andydev blobfuse[23884]: ** Post fork authentication for older libcurl version
Jun 21 14:13:47 andydev blobfuse[23884]: Authenticating using account key
Jun 21 14:13:47 andydev blobfuse[23884]: Failed to create blob client.  ex.what() = length of base64 string is not an even multiple of 4.
Jun 21 14:13:47 andydev blobfuse[23884]: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Jun 21 14:13:47 andydev blobfuse[23884]: Unmounting blobfuse.
Jun 21 14:13:47 andydev blobfuse[23884]: Unmounted blobfuse successfully.
```

**Comment by vibhansa-msft** [comment]
@andyzhangx : As per the above logs, blobfuse detected the problem with account key and unmounted. What issue are you facing ?

**Comment by andyzhangx** [comment]
if account key is incorrect, the mounted dir is broken after blobfuse mount:

```
blobfuse test6 --container-name=test --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120
# Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Unmounting blobfuse.
Unmounted blobfuse successfully.

# echo $?
0
# ls test6
ls: cannot access 'test6': Transport endpoint is not connected
# mount | grep blobfuse
/tmp/blobfuse on /tmp/test6 type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
```

**Comment by andyzhangx** [comment]
I think you could just try above command on your linux machine, and see what's broken after blobfuse mount

**Comment by vibhansa-msft** [comment]
I have tried with invalid account key on my Ubn-18 and it is getting unmounted successfully. Do you see a log of azs_destroy towards the end of your logs. It shall be after "Unmounted blobfuse successfully." Enable LOG_DEBUG when you try the mount.

**Comment by andyzhangx** [comment]
looks like there is unmount issue in Ubuntu 16.04, even on Ubuntu 18.04, how do I know whether blobfuse mount succeeded, it always return `0` code which is successful.

```
# mkdir test6
# export AZURE_STORAGE_ACCOUNT=xxx
# export AZURE_STORAGE_ACCESS_KEY=xxx
# blobfuse test6 --container-name=test --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120 --log-level=LOG_DEBUG
# Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Unmounting blobfuse.
# echo $?
0
# ls -lt test6
total 0
```

**Comment by andyzhangx** [comment]
I think the only way to check whether blobfuse mount succeeded or not is check whether there is output `Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups`, current blobfuse mount always returns success even credentials are incorrect, that's not expected behavior with linux `mount` command.

**Comment by vibhansa-msft** [comment]
Mount will always be successful as I explained earlier because the storage connection is tried post mount. If you have cURL version > 7.76 then it will do connection attempt before mount and then you can use the return status of mount command. You can rely on the error message as you mentioned above.

**Comment by andyzhangx** [comment]
@vibhansa-msft do you know how to upgrade cURL version to 7.76+? thanks.

**Comment by vibhansa-msft** [comment]
Earlier this version check was cURL version 7.67, but few months back customers reported connection issue with 7.76 as well hence we bumped up min-version check to 7.76. Another possible path for you is to take the blobfuse source and rebuild with this curl version check relaxed. I can help you with that if you want to follow that path.

**Comment by vibhansa-msft** [comment]
I can add a cli option in our next release where user can force to attempt storage connection before the mount and skip the cURL version check completely.

**Comment by andyzhangx** [comment]
> I can add a cli option in our next release where user can force to attempt storage connection before the mount and skip the cURL version check completely.

@viananth that would be great, thanks! FYI, I am from AKS team, we rely on the official deb package to install blobfuse in our  csi driver, so it's better provide an option to force checking storage connection before the mount. Currently after users do the blobfuse mount, they are actually not aware whether blobfuse mount succeed or not, and if it failed, csi driver is actually writing data to local disk, that's a breaking behavior.  
And do you know which blobfuse version brings this breaking change?

**Comment by vibhansa-msft** [comment]
A cli knob has been added, where user can choose to do pre-validation. Upgrade to 1.3.8 and refer README for the same.

**Comment by andyzhangx** [comment]
> knob

thanks, so I should set `--pre-mount-validate=true` in blobfuse mount, is that correct? @vibhansa-msft

**Comment by vibhansa-msft** [comment]
Yes you can use this knob.

**Comment by andyzhangx** [comment]
thanks, I could verify `--pre-mount-validate=true` works:
```console
# blobfuse test6 --container-name=test --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120 --log-level=LOG_DEBUG --pre-mount-validate=true
Unable to start blobfuse due to authentication or connectivity issues. Please check the readme for valid auth setups.
no config filedone reading env vars
# echo $?
255
```

**Comment by vibhansa-msft** [comment]
Thanks for the verification.

**Comment by ysendra** [comment]
Hello, I had the same issue and the " --log-level=LOG_DEBUG --pre-mount-validate=true" helped me resolve the issue that was actually related to a wrong DNS setup so that the Blob end point was not resolved properly. After correcting the DNS configuration it worked. A simple nslookup <end-point> was showing the problem
