### ISSUE TITLE
Writing/Copying does not upload files and silently drops them from the cache

### ISSUE THREAD

**Issue by munael** [Azure/azure-storage-fuse#616]
### Which version of the blobfuse was used?
1.3.5 (whole machine crashed when updating to 1.3.7 so haven't tested that yet).

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
- Writing a file `seq 10 > foo.txt`
- And copying `cp ~/foo.txt /mnt/blob/nested/path/foo.txt

do not seem to work. _Sometimes_ I get Zero Byte files created in the locations I would expect the full files, but not always. If you wait for the specified cache duration, you can also see that the files disappear from the local view of the blob. So anything written there is just lost. Nothing is printed to stderr even when mounting with `--log-level=LOG_DEBUG`. Both operations return status code 0.

### Have you found a mitigation/solution?
No :/

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
I'll try to look once the machine is back up.

### If relevant, please share your mount command.
```sh
MOUNT_DIR=/mnt/az/$ACCOUNT/$CONTAINER
BlobfuseTempDir=$HOME/some/symlink
sudo env AZURE_STORAGE_ACCOUNT="$ACCOUNT" AZURE_STORAGE_SAS_TOKEN="$SAS_TOKEN" \
      blobfuse "$MOUNT_DIR"  \
      --tmp-path="$BlobfuseTempDir/$CONTAINER"  \
      --container-name=$CONTAINER  \
      -o allow_other  \
      -o attr_timeout=240  -o entry_timeout=240  -o negative_timeout=120  \
      --log-level=LOG_DEBUG  \
      --file-cache-timeout-in-seconds=240
```

**Comment by vibhansa-msft** [comment]
Are you using a symlink as a temp directory ? Can you try using a physical path for that and see if that work.
Also upgrade to blobfuse 1.3.7, that is the latest version released.

For your query on local view : Blobfuse works with local caching mode and all files that you read/write are present in local cache only until the cache-time expires.

**Comment by munael** [comment]
Hi @vibhansa-msft - Just tried it with 1.3.7 and it's the same.

Resolved the temp dir to realpath and it now works fine. So symlinks do seem to be an issue. Any idea why?

**Comment by vibhansa-msft** [comment]
Will investigate on that and update.

**Comment by vibhansa-msft** [comment]
I tried this test case on my local vm and for me blobfuse 1.3.7 works fine with temp-dir being a symlink too. Can you check if there is any permissions related issues with symlink and the target path. I just had 777 on both and for me both are on the same mount point something like /usr/ABC/temp.lnk -> /usr/ABC/temp_dir

**Comment by vibhansa-msft** [comment]
As mentioned in above comments, temp-path provided as symlink is working fine in our test setups, provided we have sufficient permissions. As I do not see any problem from blobfuse end here closing this issue. Kindly re-open if the issue persists.
