### ISSUE TITLE
MSI Auth not working for US Government Cloud

### ISSUE THREAD

**Issue by Phydeauxman** [Azure/azure-storage-fuse#617]
### Which version of the blobfuse was used?
1.3.6

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
When attempting to use System MSI, blobfuse is still trying to reach out to commercial endpoint. Have defined the following environment variables:
`export AZURE_STORAGE_BLOB_ENDPOINT=*.blob.core.usgovcloudapi.net`
`export AZURE_STORAGE_AUTH_TYPE=MSI`
`export AZURE_STORAGE_AAD_ENDPOINT=https://login.microsoftonline.us`
`export AZURE_STORAGE_IDENTITY_OBJECT_ID=<redacted>`

### Have you found a mitigation/solution?
Yes, use access key but this is less secure than using MSI

**Comment by NaraVen** [comment]
Could you try after removing the AZURE_STORAGE_ADD_ENDPOINT env variable?  Also could you please share what error you are getting. Also, 13.7 is the latest version

**Comment by Phydeauxman** [comment]
> Could you try after removing the AZURE_STORAGE_ADD_ENDPOINT env variable? Also could you please share what error you are getting. Also, 13.7 is the latest version

I can but I started out not using that and when I saw that it was still trying to go to Azure Commercial, I added that to try to force it to go to the Azure Government login endpoint.

**Comment by NaraVen** [comment]
After adding the permissions and removing the AZURE_STORAGE_IDENTITY_OBJECT it is confirmed that everything is working now.  So closing this issue.
