### ISSUE TITLE
In-place app updates suddenly stop working

### ISSUE THREAD

**Issue by munael** [Azure/azure-storage-fuse#618]
### Which version of the blobfuse was used?
1.19.1

### Which OS (please include version) are you using?
Win10 19042

### What problem was encountered?
When updating to 1.20.0, Azure Storage Explorer _exits_ and opens a webpage to download the latest version, while it used to download and automatically install the update.

### Have you found a mitigation/solution?
No.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
N/A

### If relevant, please share your mount command.
N/A

**Comment by vibhansa-msft** [comment]
I see its in the wrong bucket. You need to file this bug on Stroage Explorer not on blobfuse.

**Comment by munael** [comment]
👀 How did I miss that...

Thanks for the heads up!
