### ISSUE TITLE
Unable to write to container with authtype MSI 

### ISSUE THREAD

**Issue by Madhuriv23** [Azure/azure-storage-fuse#619]
### Which version of the blobfuse was used?
blobfuse 1.3.6

### Which OS (please include version) are you using?
RHEL 7.9

### What problem was encountered?
I am trying to use MSI with System assigned Identity to mount blobfuse.
I granted "Storage Blob Data Reader" role at the storage account level to the VM and "Storage Blob Data Contributor" role at the container level to the VM.

Blobfuse seems to mount the container right, however when I try to create a file in the container using "touch a.txt", it gives me an error:

cat "hello" > a.txt
-bash: a.txt: No such file or directory
 
### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
/var/log/messages:
Jun 30 07:38:57 vm-biv3test blobfuse[10091]: Failure to open cache file /.a.txt.swp in azs_open. errno = 2#012.

**Comment by vibhansa-msft** [comment]
Can you try the same test case with 1.3.7. We have some MSI related fixes done in latest release.

**Comment by Madhuriv23** [comment]
Hello Vikas,

I see the same behaviour on 1.3.7 as well.
I am able to create a directory but not a file. commands like
cat "hello" > a.txt and touch a.txt fail with "file not found errors"

**Comment by vibhansa-msft** [comment]
Kindly enable log_debug and share the log file.

**Comment by Madhuriv23** [comment]
Hello,

please find the logs. Directory creation works but file creation does not work

Jul  9 14:35:24 vm-bi2test blobfuse[24422]: refresh callback set
Jul  9 14:35:24 vm-bi2test blobfuse[24422]: calling refresh token
Jul  9 14:35:29 vm-bi2test blobfuse[24422]: INFO not WARNING: Printing Json Token as string for visibility{"access_token":"","client_id":"405159ee-c63d-4ee3-9ec8-9786430a6b1d","expires_in":"86400","expires_on":"1625920529","ext_expires_in":"86399","not_before":"1625833829","resource":"https://storage.azure.com/","token_type":"Bearer"}
Jul  9 14:35:29 vm-bi2test blobfuse[24422]: INFO: After adding specified expires_in token expiry time in utc Sat Jul 10 13:35:29 2021
Jul  9 14:35:29 vm-bi2test blobfuse[24422]: OAUTH Token : Refresh token succeeded expiry time is: Sat Jul 10 11:35:29 2021
Jul  9 14:35:29 vm-bi2test blobfuse[24422]: OAUTH Token : Token expiry monitor started
Jul  9 14:35:56 vm-bi2test blobfuse[24422]: Failure to open cache file /hello.txt in azs_open.  errno = 2#012.
Jul  9 14:36:01 vm-bi2test systemd: Started Session 257 of user root.
Jul  9 14:36:01 vm-bi2test systemd: Started Session 257 of user root.
Jul  9 14:37:01 vm-bi2test systemd: Started Session 258 of user root.
Jul  9 14:37:03 vm-bi2test blobfuse[24422]: Successfully uploaded zero-length directory marker for path testcreatedir.
Jul  9 14:37:03 vm-bi2test blobfuse[24422]: Successfully created directory path: /testcreatedir.
Jul  9 14:37:17 vm-bi2test blobfuse[24422]: Failure to open cache file /testcreatedir/hello.world in azs_open.  errno = 2#012.

**Comment by vibhansa-msft** [comment]
These logs are not log_debug level blobfuse logs. Kindly share the complete log file. To collect debug logs use --log-level=LOG_DEBUG

**Comment by Madhuriv23** [comment]
@vibhansa-msft 

I used the following to mount the container and generte logs, is there any other way to enable debug?.
blobfuse ./mycontainer --tmp-path=./blobfusetmp --config-file=config.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG

**Comment by vibhansa-msft** [comment]
Yes that's correct. Did you filter the logs before sharing ? just search for blobfuse in your log messages and share them. Logs you shared above were not complete.

**Comment by vibhansa-msft** [comment]
Also from the log snippet that you have shared, it says "Failure to open cache file". Can you check you have sufficient permissions on the the temp-path "./blobfusetmp".

**Comment by Madhuriv23** [comment]
@vibhansa-msft 

Changed permissions of blobfusetmp and re-mounted, however it did not change the behaviour.

I checked the following logs in /var/logs
-rw-r--r--. 1 root   root   1402572652 Jul 12 07:53 lastlog
-rw-r--r--. 1 root   root       195369 Jul 12 07:53 waagent.log
-rw-------. 1 root   root       604444 Jul 12 07:54 messages
-rw-------. 1 root   root       349109 Jul 12 07:54 cron

but the messaged are the only ones that I see relevant for blobfuse.

**Comment by vibhansa-msft** [comment]
In /var/log/messages you can grep for "blobfuse" and redirect that to a file and share those. If you are mounting a gen-2 account, once the directory is created can do "ls -l" on the mounted directory and see what permissions are there by default on the newly created folder (both in mount path and in temp path)

"Storage blob data contributor" permission that you have for your identity is just at container level or storage account level ? You need those privileges at account level I believe.

**Comment by Madhuriv23** [comment]
@vibhansa-msft 

Permissions are "drwxrwx---." on both container and blobfusetmp directories.
Also, all files by default seem to inherit the same permission.

I gave "Storage blob data contributor" at the account level , however I wish to use this at the container level if it works that way.

These are the only logs I could get when I search for "Jul 12"

[root@vm-bi2test tmp]# cat blobfuse.txt | grep "Jul 12"
cron:Jul 12 07:38:21 vm-bi2test CROND[1849]: (root) CMD (sleep 20 && blobfuse /datadrive/vr336/notebooks/public-datasets --tmp-path=/datadrive/vr336/notebooks/public-datasets-tmp --config-file=/datadrive/vr336/notebooks/public_ds.cfg -o allow_other --use-adls=true )
cron:Jul 12 07:38:21 vm-bi2test CROND[1850]: (root) CMD (sleep 20 && blobfuse /datadrive/vr336/notebooks/blobstorage --tmp-path=/datadrive/vr336/notebooks/blobfusetmp --config-file=/datadrive/vr336/notebooks/fuse_connection.cfg -o allow_other --use-adls=true )
messages:Jul 12 07:38:41 vm-bi2test blobfuse[2352]: Setting logging level to : LOG_WARNING
messages:Jul 12 07:38:41 vm-bi2test blobfuse[2351]: Setting logging level to : LOG_WARNING
messages:Jul 12 07:38:41 vm-bi2test blobfuse[2352]: ** Delaying tls init to post fork for older libcurl version
messages:Jul 12 07:38:41 vm-bi2test blobfuse[2351]: ** Delaying tls init to post fork for older libcurl version
messages:Jul 12 07:38:41 vm-bi2test blobfuse[2352]: ** Delaying authentication to post fork for older curl versions
messages:Jul 12 07:38:41 vm-bi2test blobfuse[2351]: ** Delaying authentication to post fork for older curl versions
messages:Jul 12 07:38:41 vm-bi2test blobfuse[2365]: ** Post fork authentication for older libcurl version
messages:Jul 12 07:38:41 vm-bi2test blobfuse[2366]: ** Post fork authentication for older libcurl version
messages:Jul 12 07:52:08 vm-bi2test blobfuse[4378]: Unable to start blobfuse.  No config file found at config.cfg.
messages:Jul 12 07:52:31 vm-bi2test blobfuse[4427]: Setting logging level to : LOG_DEBUG
messages:Jul 12 07:52:31 vm-bi2test blobfuse[4427]: Disk Thresholds : 90 - 80, Cache Eviction : 1000-0, List Cancel time : 0
messages:Jul 12 07:52:31 vm-bi2test blobfuse[4427]: release is 3.100000, Kernel version is 3.10.0-1160.31.1.el7.x86_64
messages:Jul 12 07:52:31 vm-bi2test blobfuse[4427]: CURL Version is 7.29.0
messages:Jul 12 07:52:31 vm-bi2test blobfuse[4427]: ** Delaying tls init to post fork for older libcurl version
messages:Jul 12 07:52:31 vm-bi2test blobfuse[4427]: ** Delaying authentication to post fork for older curl versions
messages:Jul 12 07:52:31 vm-bi2test blobfuse[4429]: ** Post fork authentication for older libcurl version
messages:Jul 12 07:52:31 vm-bi2test blobfuse[4429]: refresh callback set
messages:Jul 12 07:52:31 vm-bi2test blobfuse[4429]: calling refresh token
messages:Jul 12 07:52:36 vm-bi2test blobfuse[4429]: INFO not WARNING: Printing Json Token as string for visibility{"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL3N0b3JhZ2UuYXp1cmUuY29tLyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2UwMGRkY2RmLTFlMGYtNGJlNS1hMzdhLTg5NGE0NzMxOTg2YS8iLCJpYXQiOjE2MjYwNjg4NTYsIm5iZiI6MTYyNjA2ODg1NiwiZXhwIjoxNjI2MTU1NTU2LCJhaW8iOiJFMlpnWUtnSWE1aXljZjNhSjVQdVA4NXVyWFg0RHdBPSIsImFwcGlkIjoiNDA1MTU5ZWUtYzYzZC00ZWUzLTllYzgtOTc4NjQzMGE2YjFkIiwiYXBwaWRhY3IiOiIyIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZTAwZGRjZGYtMWUwZi00YmU1LWEzN2EtODk0YTQ3MzE5ODZhLyIsIm9pZCI6IjU0YWFiZTQ0LWRhZjAtNGNkOS05YmI0LTJiMzhiYTcxODBlNiIsInJoIjoiMC5BVWNBMzl3TjRBOGU1VXVqZW9sS1J6R1lhdTVaVVVBOXh1Tk9uc2lYaGtNS2F4MUhBQUEuIiwic3ViIjoiNTRhYWJlNDQtZGFmMC00Y2Q5LTliYjQtMmIzOGJhNzE4MGU2IiwidGlkIjoiZTAwZGRjZGYtMWUwZi00YmU1LWEzN2EtODk0YTQ3MzE5ODZhIiwidXRpIjoibUtqd2dOX29Ja2FqbmVlTHRTY25BQSIsInZlciI6IjEuMCIsInhtc19taXJpZCI6Ii9zdWJzY3JpcHRpb25zLzc2ZjkwOWZiLWEwODUtNGUwNi05ODM3LTIwYjQ0MDg1YmU0OS9yZXNvdXJjZWdyb3Vwcy9yZy12cjMzNi9wcm92aWRlcnMvTWljcm9zb2Z0LkNvbXB1dGUvdmlydHVhbE1hY2hpbmVzL3ZtLWJpMnRlc3QifQ.UJeh6f2UM-nylR9-tma0uehvop8UE2l6XMsJ3eQq8DBaz1M1ph6tAnaW5g4bBZ7XlTeX9Uxl6LdhEl-B7gWMZR_1sso03vwlCifjD6fN8Gab_j0o2s292wDLKWFpxSFl8SNIlI64YYzRSAaYiJXdRbgM-8S-OnaieyGgSNTftjBc1DdBAFOcCdXe-WNIfMJhDqLwotJB1plfP0U0D8EHZQ_wp4odwcDjLXyXiaU-J9cRlHk-DAqVol4LQ36ktVwe4hdDoAcCMaUXEhxppTPXtwEoAyJH1tCbvIrijgMWh-b9ZjSDPGY-DxRUlHBFzZCHhior3TJXj7dqnevGgSC4KQ","client_id":"405159ee-c63d-4ee3-9ec8-9786430a6b1d","expires_in":"86400","expires_on":"1626155556","ext_expires_in":"86399","not_before":"1626068856","resource":"https://storage.azure.com/","token_type":"Bearer"}
messages:Jul 12 07:52:36 vm-bi2test blobfuse[4429]: INFO: After adding specified expires_in token expiry time in utc Tue Jul 13 06:52:36 2021
messages:Jul 12 07:52:36 vm-bi2test blobfuse[4429]: OAUTH Token : Refresh token succeeded expiry time is: Tue Jul 13 04:52:36 2021
messages:Jul 12 07:52:36 vm-bi2test blobfuse[4429]: OAUTH Token : Token expiry monitor started
messages:Jul 12 07:52:46 vm-bi2test blobfuse[4429]: Failure to open cache file /a.txt in azs_open.  errno = 2#012.
tmp:cron:Jul 12 07:38:21 vm-bi2test CROND[1849]: (root) CMD (sleep 20 && blobfuse /datadrive/vr336/notebooks/public-datasets --tmp-path=/datadrive/vr336/notebooks/public-datasets-tmp --config-file=/datadrive/vr336/notebooks/public_ds.cfg -o allow_other --use-adls=true )
tmp:cron:Jul 12 07:38:21 vm-bi2test CROND[1850]: (root) CMD (sleep 20 && blobfuse /datadrive/vr336/notebooks/blobstorage --tmp-path=/datadrive/vr336/notebooks/blobfusetmp --config-file=/datadrive/vr336/notebooks/fuse_connection.cfg -o allow_other --use-adls=true )

**Comment by vibhansa-msft** [comment]
As you can see in the above logs are set to LOG_WARNING and not LOG_DEBUG. As per the first line in log 

"cron:Jul 12 07:38:21 vm-bi2test CROND[1850]: (root) CMD (sleep 20 && blobfuse /datadrive/vr336/notebooks/blobstorage --tmp-path=/datadrive/vr336/notebooks/blobfusetmp --config-file=/datadrive/vr336/notebooks/fuse_connection.cfg -o allow_other --use-adls=true )" :    There is not log-level set in this command.

**Comment by Madhuriv23** [comment]
@vibhansa-msft 

Log-level is being set to debug, you can see it from the message here
messages:Jul 12 07:52:31 vm-bi2test blobfuse[4427]: Setting logging level to : LOG_DEBUG

I am running it as user who has permissions to write into the directory. I also tried setting 777 on mycontainer and blobfusetmp but still get the same error.

i do see these additional logs, although may be they are not related to blobfuse.

Jul 12 09:13:06 vm-bi2test python: detected unhandled Python exception in '/opt/microsoft/omsconfig/modules/nxOMSAutomationWorker/DSCResources/MSFT_nxOMSAutomationWorkerResource/automationworker/scripts/register_oms.py'
Jul 12 09:13:06 vm-bi2test abrt-server: Executable '/opt/microsoft/omsconfig/modules/nxOMSAutomationWorker/DSCResources/MSFT_nxOMSAutomationWorkerResource/automationworker/scripts/register_oms.py' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Jul 12 09:13:06 vm-bi2test abrt-server: 'post-create' on '/var/spool/abrt/Python-2021-07-12-09:13:06-15708' exited with 1
Jul 12 09:13:06 vm-bi2test abrt-server: Deleting problem directory '/var/spool/abrt/Python-2021-07-12-09:13:06-15708'
Jul 12 09:13:07 vm-bi2test systemd: Removed slice User Slice of omsagent.
Jul 12 09:14:01 vm-bi2test systemd: Started Session 145 of user root.
Jul 12 09:14:28 vm-bi2test discagnt: SOAP 1.1 fault: SOAP-ENV:Server [no subcode]
Jul 12 09:14:28 vm-bi2test discagnt: "SSL_ERROR_SSL
Jul 12 09:14:28 vm-bi2test discagnt: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown"
Jul 12 09:14:28 vm-bi2test discagnt: Detail: SSL_accept() failed in soap_ssl_accept()
Jul 12 09:14:28 vm-bi2test discagnt: SSL request failed, continue with next call...

**Comment by vibhansa-msft** [comment]
No these logs do not belong to blobfuse, something else only. And yes I re-checked the previous logs, there is a failure in mount first with LOG_WARN and then a success with LOG_DEBUG, hence the confusion. However those logs are still not complete. 

As you are telling even with 777 its not working is weird. 
" Failure to open cache file /a.txt in azs_open. errno = 2#12." : This is clearly pointing to some failure on your local disk and not with the storage container. It has to be some permission issue on the temp directory. 
I verified at code level also and this error is thrown on failure in a 'open' system call where blobfuse is just trying to open a file in temp directory.

**Comment by Madhuriv23** [comment]
@vibhansa-msft : 
I deleted my both container and tmp directories and tried to create them from scratch.

 rm -r blobfusetmp
 rm -r mycontainer

mkdir blobfusetmp
mkdir mycontainer

chmod 777 blobfusetmp
chmod 777 mycontainer

ls -lrt (shows this)
drwxrwxrwx. 2 vr336@deutsche-boerse.com vr336@deutsche-boerse.com 4096 Jul 12 22:49 mycontainer
drwxrwxrwx. 3 vr336@deutsche-boerse.com vr336@deutsche-boerse.com 4096 Jul 12 22:50 blobfusetmp

after I mount,
blobfuse ./mycontainer --tmp-path=./blobfusetmp -
-config-file=config.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG
_DEBUG

the permissions of mycontainer are changed
drwxrwxrwx. 3 vr336@deutsche-boerse.com vr336@deutsche-boerse.com 4096 Jul 12 22:50 blobfusetmp
drwxrwx---. 2 vr336@deutsche-boerse.com vr336@deutsche-boerse.com 4096 Jul 12 22:54 mycontainer

and creating a file after this gives the same error that I described above. 
please let me know if there are any other ways to debug this issue

**Comment by vibhansa-msft** [comment]
There are two things you can try
1. If we suspect there is some MSI related failure in blobfuse or permission issue with the identity, you can mount using account key and try the same test case again
2. To rule out user privileges issue on your test VM, you can mount with sudo and try your test case with sudo as well.

Some points while you try these things out
- Always mount with log level set to log_debug
- We are still missing the logs for some reason, so can you copy "https://github.com/Azure/azure-storage-fuse/blob/master/systemd/10-blobfuse.conf" to "/etc/rsyslog.d/" directory and then do "sudo service rsyslog restart". This will start redirecting all the blobfuse logs to a file /var/log/blobfuse.log and we dont need to do any filter on syslog.

**Comment by Madhuriv23** [comment]
@vibhansa-msft 

Thanks a lot for your guidance.

1. After mounting as root with "allow-other" optional as below, it is allowing to create files.

	sudo blobfuse ./mycontainer --tmp-path=./blobfusetmp --config-file=config.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG 

2. However, I see another problem here. The first letter in the files I am creating is always removed i.e

	echo "helloworld" > **helloasuser.txt** 
	-rwxrwxrwx. 1 user1 user1   11 Jul 14 22:30 **elloasuser.txt**

	Note: It’s the same behavior when I run the commands as root also(the first letter is always removed for directory and file).

3. I downloaded blobfuse.conf and restarted rsyslog, but this did not create any file in /var/log and I do not see blobfuse logging to /var/log/messages anymore.

**Comment by vibhansa-msft** [comment]
Great that it worked. It also prooves that there is indeed some privilage issue on the VM you are using.
For (3), if logs are not coming to /var/log/messages then it shall have created a new file /var/log/blobfuse.log where they are getting redirected. If we logs we can look for possible reasons of failure in (2).
These (2) and (3) also looks like some VM issue only, if possible can you try similar test case on some other VM ?

**Comment by vibhansa-msft** [comment]
Closing the issue as there is no update on this. Feel free to reopen in case issue persists.
