### ISSUE TITLE
Potential race condition causing all blobs to be deleted in mounted container ?

### ISSUE THREAD

**Issue by saswatac** [Azure/azure-storage-fuse#620]
### Which version of the blobfuse was used?
1.3.7

### Which OS (please include version) are you using?
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### What problem was encountered?

All contents of mounted container was deleted, possibly by issue in blob fuse rather than by end user or application.

### Have you found a mitigation/solution?

no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

We see a spike in delete blob api calls -

<img width="1649" alt="Screenshot 2021-07-07 at 15 07 35" src="https://user-images.githubusercontent.com/4872140/124764697-86a2a980-df35-11eb-8ae8-728caac468bd.png">

Around the same time following logs are seen -

```
Jul 6 15:39:58 ws-armando blobfuse[39]: message repeated 108 times: [ Locking mutex failed, so some token is being acquired., so just wait and get that]
Jul 6 15:39:58 ws-armando blobfuse[39]: INFO: After adding specified expires_in token expiry time in utc Tue Jul 6 16:39:57 2021#012
Jul 6 15:39:58 ws-armando blobfuse[39]: OAUTH Token : Refresh token succeeded expiry time is: Tue Jul 6 16:39:57 2021
```

This is followed by logs of multiple failed DELETE API calls like 

```
Jul  6 16:04:27 ws-armando blobfuse[39]:  ==> REQUEST/RESPONSE :: DELETE https://*******.blob.core.windows.net/******/datasets/zipped-sample-data/alive?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.3.7&x-ms-date=Tue, 06 Jul 2021 16:04:27 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 404 :: REQ ID : 2d7284f7-101e-002a-0e80-72ac16000000 
```

The line "message repeated 108 times: [ Locking mutex failed, so some token is being acquired., so just wait and get that]" seems to have been logged only at the time of this incident which makes us think that the deletion could have been triggered by some race condition in blobfuse rather than end user or application deleting the blobs which is quite unlikely.

### If relevant, please share your mount command.

```
blobfuse /mnt/data/gcs-data --container-name=xxxx --tmp-path=/mnt/data/blobfusetmp/ -o allow_other --use-attr-cache=true -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=240
```

**Comment by vibhansa-msft** [comment]
Log that you have shared regarding race-condition, only means user application wanted to access container while blobfuse was in process of refreshing the token. For every request made by user application in this time frame, this log will be emitted once. At the end log about token refresh is there indicating there were no issues and all requests were taken care of. 
For the question on deleting data from container, blobfuse does not trigger any delete on its own unless user-application has requested for it, not even in case of any race conditions. If you can share entire log (with LOG_DEBUG enabled) we can confirm that part.

**Comment by saswatac** [comment]
Thanks for your response. Unfortunately this happened in a production setting and debug logs are not available. I was not able to reproduce either. I think the issue can be closed for now, if we see more occurrences i will get back with debug logs.
