### ISSUE TITLE
after blobfuse unmount, there are empty directories left

### ISSUE THREAD

**Issue by yuyue9284** [Azure/azure-storage-fuse#621]
### Which version of the blobfuse was used?
1.3.7

### Which OS (please include version) are you using?
 Ubuntu 18.04 

### What problem was encountered?
After blobfuse unmount, there are empty directories left, and causing `Mount failed with error: exit status 1, output: fuse: mountpoint is not empty` error for next mount.

### Have you found a mitigation/solution?
Remove the target folder can mitigate the problem.

### If relevant, please share your mount command.
> /var/lib/kubelet/plugins/kubernetes.io/csi/pv/default-amlarccostorage8be1f98b9-azureml-csi/globalmount --tmp-path=/mnt/default-amlarccostorage8be1f98b9-azureml-csi#1625736702 --c     ontainer-name=azureml --file-cache-timeout-in-seconds=0 --tmp-path=/mnt/default-amlarccostorage8be1f98b9-azureml-csi --use-https=true -o allow_other

**Comment by vibhansa-msft** [comment]
If the blobfuse is not unmounted then temp directory will not be wiped out and next mount command will give this error. On successful unmount blobfuse does clear the temp directory. Kindly confirm csi driver does a graceful unmount or not.

**Comment by yuyue9284** [comment]
> If the blobfuse is not unmounted then temp directory will not be wiped out and next mount command will give this error. On successful unmount blobfuse does clear the temp directory. Kindly confirm csi driver does a graceful unmount or not.

Thanks, will confirm if restart CSI causing this issue.

**Comment by vibhansa-msft** [comment]
You can try a manual unmount and confirm that there is no issue from blobfuse end (sudo fusermount -u <mount path>). 
In case CSI driver is not doing a graceful unmount kindly connect the respective team.

**Comment by vibhansa-msft** [comment]
Closing this issue as there is no failure on blobfuse end. If a manual/graceful unmount does not clear the temp directory, kindly re-open the issue.
