### ISSUE TITLE
Blobfuse Mount gets 'Transport endpoint is not connected' error

### ISSUE THREAD

**Issue by sajin-varghese1990** [Azure/azure-storage-fuse#622]
### Which version of the blobfuse was used?
blobfuse 1.0.2

### Which OS (please include version) are you using?
CentOS Linux release 7.7.1908 (Core)

### What problem was encountered?
We have an application backup solution in production, where we need to (1) take backup of application data which is around 500GB-1TB, (2) store it in local storage (3) encrypt, compress and (4) upload to Azure Storage account which is mounted to the local machine via Blobfuse mount. After the blobfuse is successfully mounted, once in 2-3 days the mount becomes inaccessible with below error:
cannot access <mount-path>: Transport endpoint is not connected
And all backups are failed because it cannot access mount path to validate/upload the backups.

We tried to look for error logs in /var/log/messages but could not find any error related to this.

### Have you found a mitigation/solution?
Temporary workaround done whenever issue occur was to unmount the storage account (blobfuse mount) and then mount it back again using blobfuse command and it works. But within 2-3 days the mount connection is lost again and mount becomes inaccessible.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
There is nothing in /var/log/messages or any other syslog which is helpful.

### If relevant, please share your mount command.
Below mount command works successfully:
sudo blobfuse /mountpath --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/centos/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

But mount connection is lost in 2-3 days.

**Comment by NaraVen** [comment]
This issue has been fixed in the later releases. Please upgrade to Blobfuse 1.3.7

**Comment by NaraVen** [comment]
syslog is the best place.

**Comment by sajin-varghese1990** [comment]
Thankyou.

Currently we are mounting blobfuse by adhoc mount command as below:
sudo blobfuse /mountpath --tmp-path=/mnt/resource/blobfusetmp --config-file=/home/centos/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Is there any way to configure the mount automatically using autofs, so that performance is improved?**

**Comment by NaraVen** [comment]
Will this fstab solution work? https://github.com/Azure/azure-storage-fuse/wiki/2.-Configuring-and-Running#persisting .   We do not have autofs examples.

**Comment by NaraVen** [comment]
closing this. If your issue is not resolved do comment and we will reopen.
