### ISSUE TITLE
BLOB Storage mount from Azure VM (ubuntu ) getting disconnected always

### ISSUE THREAD

**Issue by hemantnayan** [Azure/azure-storage-fuse#625]
We have Ubuntu VM and mounting blob storage using blobfuse, The issue we are facing is for the mount point, which is getting disconnected sometimes. 

### Which version of the blobfuse was used?
blobfuse 1.3.6

### Which OS (please include version) are you using?
 Ubuntu 18.04

### What problem was encountered?
We have Ubuntu VM and mounting blob storage using blobfuse, The issue we are facing is for the mount point, which is getting disconnected sometimes. 

### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
Kindly enable debug logs using cli and share the logs.

**Comment by hemantnayan** [comment]
It is AZ vm and ubuntu , Can you please specify how and which log to enable.

**Comment by vibhansa-msft** [comment]
In your mount command add a cli option "--log-level=LOG_DEBUG". This will enable debug logs and it will be directed to syslog.

To filter blobfuse syslog to a separate file you will need a syslog filter file. Filter file can be downloaded from 'https://github.com/Azure/azure-storage-fuse/blob/master/systemd/10-blobfuse.conf'. Just copy this file to "/etc/rsyslog.d/" directory and execute " sudo service rsyslog restart". Post this blobfuse logs will be punted to /var/log/blobfuse.log.

Once this syslog setup is done, just use the mount command with the cli option mentioned above and share the blobfuse.log file when blobfuse fails.

**Comment by hemantnayan** [comment]
I can understand your statement, But my issue as mentioned with the original problem. 
It is connected when I mount without any issue. But sometimes I  find mount getting disconnected automatically. I have configured as service .  If I reconnect, it get's connected. If you still want to have logs I can send. but that will be always success.

**Comment by vibhansa-msft** [comment]
From mount until it fails we need logs for that duration, so that we can validate unmount was requested due to some reason or it was abrupt. Also if you see this behavior with service, can you manually mount it through cli and check if behavior remains same or not.
Also you can upgrade to 1.3.8 and check once, as that's our latest release.

**Comment by vibhansa-msft** [comment]
Does the test case work with 1.3.8. ?
Also if you were able to collect the logs, kindly share.

**Comment by vibhansa-msft** [comment]
Closing this issue as there has been no update. Feel free to re-open if issue persists.
