### ISSUE TITLE
Build fails on raspbian

### ISSUE THREAD

**Issue by ArtemKiyashko** [Azure/azure-storage-fuse#626]
### Which version of the blobfuse was used?
1.3.8

### Which OS (please include version) are you using?
Raspbian GNU/Linux 10 (buster)

### What problem was encountered?
[ 70%] Building CXX object CMakeFiles/azure-storage-lite.dir/src/blob/blob_client_wrapper.cpp.o
/home/pi/repos/azure-storage-fuse-blobfuse-1.3.8/cpplite/src/blob/blob_client_wrapper.cpp: In member function ‘virtual void azure::storage_lite::blob_client_wrapper::upload_file_to_blob(const string&, const string&, std::__cxx11::string, const std::vector<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&, size_t)’:
/home/pi/repos/azure-storage-fuse-blobfuse-1.3.8/cpplite/src/blob/blob_client_wrapper.cpp:416:25: error: comparison is always false due to limited range of data type [-Werror=type-limits]
             if(fileSize > MAX_BLOB_SIZE)
                ~~~~~~~~~^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/azure-storage-lite.dir/build.make:453: CMakeFiles/azure-storage-lite.dir/src/blob/blob_client_wrapper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/azure-storage-lite.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
************************ CPPLite build Failed *****************************

### Have you found a mitigation/solution?
No

### gcc version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

### Cmake version
3.16.3

**Comment by gaul** [comment]
The Makefile probably should set `-D_FILE_OFFSET_BITS=64` so that `off_t` is 64-bits on 32-bit platforms.

**Comment by vibhansa-msft** [comment]
Are you trying to compile this on a 32bit system ?

**Comment by ArtemKiyashko** [comment]
@vibhansa-msft 
> Are you trying to compile this on a 32bit system ?

yup, `uname -m` show me "armv7l", so it is 32bit

**Comment by vibhansa-msft** [comment]
We have not tried to build or test on such system so not sure about the behavior.

**Comment by ArtemKiyashko** [comment]
So, any chance you will test/fix it on such system to make it possible to run on RPI? I'd like to use it (azure blobs) as a location for my RPI SD card images together with Borg backup system.

**Comment by vibhansa-msft** [comment]
As of now we do not have any concrete plans for the same, will put this in our backlog for future.

**Comment by adgbu** [comment]
@ArtemKiyashko 
I ran into the same problem. I need to run azure-storage-fuse on 32-bit Raspbian. 
Did you solve this problem? 
Did you get it to work, even though it's officially unsupported?

**Comment by vibhansa-msft** [comment]
No its not supported yet.
