### ISSUE TITLE
Does BlobFuse support ADLS Gen 1, or only ADLS Gen 2?

### ISSUE THREAD

**Issue by anthonyaue** [Azure/azure-storage-fuse#627]
### Which version of the blobfuse was used?
1.3.8

### Which OS (please include version) are you using?
Ubuntu 20.04 (via WSL2)

### What problem was encountered?
Tried mounting an ADLS Gen 1 storage account using SPN authType, providing servicePrincipalClientId,TenantId, Secret in config file. 

Blobfuse command line works correctly, but when I attempt to ls the dir I mounted, it hangs for a minute or two, then tells me:

"Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups."

### Have you found a mitigation/solution?
No.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

Seems to be just trying over and over trying to get the requested directory but failing in the end due to DNS lookup error.

Jul 26 10:53:22 ANTHAUE-DSK3 blobfuse[1078]:  ==> REQUEST/RESPONSE :: GET https://msr-machinetranslation-08.dfs.core.windows.net/catalog?directory=/&maxResults=1&recursive=false&resource=filesystem?&User-Agent=azure-storage-fuse/1.3.8&x-ms-date=Mon, 26 Jul 2021 17:53:21 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 0 ::
...
Jul 26 10:59:53 ANTHAUE-DSK3 blobfuse[1078]:  ==> REQUEST/RESPONSE :: GET https://msr-machinetranslation-08.dfs.core.windows.net/catalog?directory=/&maxResults=1&recursive=false&resource=filesystem?&User-Agent=azure-storage-fuse/1.3.8&x-ms-date=Mon, 26 Jul 2021 17:59:04 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 0 ::
Jul 26 10:59:53 ANTHAUE-DSK3 blobfuse[1078]: Couldn't resolve host name:
Jul 26 10:59:53 ANTHAUE-DSK3 blobfuse[1078]: Unable to start blobfuse. DNS server lookup failed errno=6
Jul 26 10:59:53 ANTHAUE-DSK3 blobfuse[1078]: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Jul 26 10:59:53 ANTHAUE-DSK3 blobfuse[1078]: Unmounting blobfuse.
Jul 26 10:59:53 ANTHAUE-DSK3 blobfuse[1078]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 120: azs_getattr called with path = /
Jul 26 10:59:53 ANTHAUE-DSK3 blobfuse[1078]: Function azs_readdir, in file /home/vsts/work/1/s/blobfuse/directoryapis.cpp, line 46: azs_readdir called with path = /
Jul 26 10:59:53 ANTHAUE-DSK3 blobfuse[1078]: Function azs_readdir, in file /home/vsts/work/1/s/blobfuse/directoryapis.cpp, line 79: Reading contents of local cache directory /mnt/bf/root/.
Jul 26 10:59:53 ANTHAUE-DSK3 blobfuse[1078]: Function azs_readdir, in file /home/vsts/work/1/s/blobfuse/directoryapis.cpp, line 145: azs_readdir : About to call list_blobs.  Container = catalog, delimiter = /, continuation = , prefix =
Jul 26 10:59:53 ANTHAUE-DSK3 blobfuse[1078]: Calling List Paths, continuation:, prefix:, delimiter:/

### If relevant, please share your mount command.

blobfuse ~/adlstest4 --log-level=LOG_DEBUG --use-adls=true --tmp-path=/mnt/bf/ --config-file=bf_adls.cfg

**Comment by NaraVen** [comment]
Blobfuse adls supports only Gen 2. In the case above the connection to storage is not established in the first place because blobfuse is looking for the Gen 2 endpoint dfs.core.windows.net.  However, you are not seeing the connection failure error until you do some POSIX operations like ls.

**Comment by anthonyaue** [comment]
Thanks, that makes sense. Are there any plans to support Gen1?

**Comment by NaraVen** [comment]
No plans
