### ISSUE TITLE
Always load from cache if same file size

### ISSUE THREAD

**Issue by georgeliang0821** [Azure/azure-storage-fuse#630]
### Which version of the blobfuse was used?
blobfuse 1.3.8

### Which OS (please include version) are you using?
UbuntuServer 18.04-LTS

### What problem was encountered?
if the file size is same, it would go to cache no matter the value is zero in "--file-cache-timeout-in-seconds"

### Have you found a mitigation/solution?
no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
no relevant error in /var/log/syslog. 

### If relevant, please share your mount command.
blobfuse /home/upload/stage --tmp-path=/data/blobfuse-tmp --config-file=/home/upload/blobfuse-stage.cfg --file-cache-timeout-in-seconds=0 -o attr_timeout=60 -o entry_timeout=60 -o negative_timeout=30 -o allow_root

**Comment by vibhansa-msft** [comment]
File size is not checked to make any decision about caching. If file-cache-timeout is set to '0', once all open handle to a file are closed, file is removed from cache. Follow-up open will re-download file from container to cache. 
In case your application is not closing handles to a given file, it will not be removed from the cache.
Kindly share the debug logs of blobfuse if you observe otherwise.

**Comment by georgeliang0821** [comment]
hi @vibhansa-msft 

customer reported this issue with me and i reproduce it in my environment, here is quick experiment for this issue, i believe that should be certain mechanism or issue for blobfuse

1) 1st time to view the file and it be cached.
![image](https://user-images.githubusercontent.com/69842212/128299613-ea493d09-ed74-4dad-a6f8-3dcdbd3b34b8.png)

2) change the content and re-generate the file, the file size is same as previous, however, it load from cache although  "--file-cache-timeout-in-seconds=0" (the 1st column is incorrect with blob storage)
![image](https://user-images.githubusercontent.com/69842212/128299970-e746fb09-b4a5-475c-b959-f9ad32cf1946.png)

3) change the bigger file size and re-generate the file, it does not load from cache. that's my expectation.
![image](https://user-images.githubusercontent.com/69842212/128300387-b966bc44-339d-4cb1-aefa-1537e3cf321c.png)

**Comment by vibhansa-msft** [comment]
Kindly enable log_debug and share the logs file when these test cases are done.

**Comment by georgeliang0821** [comment]
hi @vibhansa-msft 

after enable log_debug, we have lot information, I just collect "blob" related.
after checking that, still cannot explain my result.


#1 view at 15:47 - create local cache
 
![image](https://user-images.githubusercontent.com/69842212/128316087-837c85d7-93d1-434f-88b7-839012494cf2.png)

**result for "grep blob /var/log/syslog" during  15:47**
--------------------------------------------------------------
Aug  5 15:47:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 120: azs_getattr called wi
th path = /
Aug  5 15:47:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 120: azs_getattr called wi
th path = /test
Aug  5 15:47:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 148: Accessing mntPath = /
data/blobfuse-tmp/root/test for getattr succeeded; object is in the local cache.
Aug  5 15:47:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 173: lstat on file /data/b
lobfuse-tmp/root/test in local cache succeeded.
Aug  5 15:47:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 120: azs_getattr called wi
th path = /test/20210720
Aug  5 15:47:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 148: Accessing mntPath = /
data/blobfuse-tmp/root/test/20210720 for getattr succeeded; object is in the local cache.
Aug  5 15:47:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 173: lstat on file /data/b
lobfuse-tmp/root/test/20210720 in local cache succeeded.
Aug  5 15:47:42 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 120: azs_getattr called wi
th path = /test/20210721
Aug  5 15:47:42 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 180: Object /data/blobfuse
-tmp/root/test/20210721 is not in the local cache during getattr.
Aug  5 15:47:42 vm-test-csp2-stage01 blobfuse[1059]:  ==> REQUEST/RESPONSE :: GET https://satfmprdcsp2stage01.blob.core.windows.net/stage?comp=list&delimiter=
/&include=metadata&maxresults=5000&prefix=test/20210721&restype=container?&User-Agent=azure-storage-fuse/1.3.8&x-ms-date=Thu, 05 Aug 2021 07:47:42 GMT&x-ms-ve
rsion=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 200 :
: REQ ID : 1f204d5e-701e-0006-06ce-89594c000000
Aug  5 15:47:42 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 244: In azs_getattr list_s
egmented_item do loop blob prefix: test/20210721 continuation:
Aug  5 15:47:42 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 265: In azs_getattr list_s
egmented_item 0 file test/20210721/
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 288: In azs_getattr found 
blob in list file test/20210721/TFM_ORDER_20210721.csv
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 327: Blob /test/20210721/T
FM_ORDER_20210721.csv, representing a file, found during get_attr.
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: azs_open called with path = /test/20210721/TFM_ORDER_20210721.csv, fi->flags = 8000.
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data.
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp.
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp/root.
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp/root/test.
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp/root/test/20210721.
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]:  ==> REQUEST/RESPONSE :: GET https://satfmprdcsp2stage01.blob.core.windows.net/stage/test/20210721/TFM_OR
DER_20210721.csv?&x-ms-range=bytes=0-16777215&User-Agent=azure-storage-fuse/1.3.8&x-ms-date=Thu, 05 Aug 2021 07:47:54 GMT&x-ms-version=2018-11-09&Authorizatio
n=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 206 :: REQ ID : f9e75557-201e-0096
-1cce-89cc00000000
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Successfully downloaded blob test/20210721/TFM_ORDER_20210721.csv into file cache as /data/blobfuse-tmp/r
oot/test/20210721/TFM_ORDER_20210721.csv.
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function azs_open, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 134: Opening /data/blobfuse-tm
p/root/test/20210721/TFM_ORDER_20210721.csv gives fh = 18, errno = 0
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function azs_open, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 165: Returning success from az
s_open, file = /test/20210721/TFM_ORDER_20210721.csv
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function azs_flush, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 268: azs_flush called with pa
th = /test/20210721/TFM_ORDER_20210721.csv, fi->flags = 0, (((struct fhwrapper *)fi->fh)->fh) = 18.
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function azs_flush, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 285: Successfully looked up m
ntPath.  Input path = /test/20210721/TFM_ORDER_20210721.csv, path_link_buffer = /proc/self/fd/18, path_buffer = /data/blobfuse-tmp/root/test/20210721/TFM_ORDE
R_20210721.csv
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function azs_flush, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 307: azs_flush: path = /test/
20210721/TFM_ORDER_20210721.csv, upload_on_close = 0, modified only flag config_options.uploadIfModified = 0, .
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function azs_release, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 381: azs_release called wit
h path = /test/20210721/TFM_ORDER_20210721.csv, fi->flags = 32768
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function azs_release, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 403: Adding file to the GC 
from azs_release.  File = /data/blobfuse-tmp/root/test/20210721/TFM_ORDER_20210721.csv#012.
Aug  5 15:47:54 vm-test-csp2-stage01 blobfuse[1059]: Function run_gc_cache, in file /home/vsts/work/1/s/blobfuse/src/BlobfuseGcCache.cpp, line 151: File /test
/20210721/TFM_ORDER_20210721.csv being considered for deletion by file cache GC.

#2 view at 15:47 - file change, however seems load from previous cache
![image](https://user-images.githubusercontent.com/69842212/128317811-30f5a76c-adc7-433e-aded-f2f2e9d06234.png)

**result for "grep blob /var/log/syslog" during  15:51**
--------------------------------------------------------------
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 120: azs_getattr called wi
th path = /test/20210721/TFM_ORDER_20210721.csv
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 180: Object /data/blobfuse
-tmp/root/test/20210721/TFM_ORDER_20210721.csv is not in the local cache during getattr.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]:  ==> REQUEST/RESPONSE :: GET https://satfmprdcsp2stage01.blob.core.windows.net/stage?comp=list&delimiter=
/&include=metadata&maxresults=5000&prefix=test/20210721/TFM_ORDER_20210721.csv&restype=container?&User-Agent=azure-storage-fuse/1.3.8&x-ms-date=Thu, 05 Aug 20
21 07:51:37 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------R
ESPONSE Status :: 200 :: REQ ID : 4349b924-301e-0082-60ce-890f64000000
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 244: In azs_getattr list_s
egmented_item do loop blob prefix: test/20210721/TFM_ORDER_20210721.csv continuation:
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 265: In azs_getattr list_s
egmented_item 0 file test/20210721/TFM_ORDER_20210721.csv
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 288: In azs_getattr found 
blob in list file test/20210721/TFM_ORDER_20210721.csv
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 327: Blob /test/20210721/T
FM_ORDER_20210721.csv, representing a file, found during get_attr.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: azs_open called with path = /test/20210721/TFM_ORDER_20210721.csv, fi->flags = 8000.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp/root.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp/root/test.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp/root/test/20210721.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]:  ==> REQUEST/RESPONSE :: GET https://satfmprdcsp2stage01.blob.core.windows.net/stage/test/20210721/TFM_OR
DER_20210721.csv?&x-ms-range=bytes=0-16777215&User-Agent=azure-storage-fuse/1.3.8&x-ms-date=Thu, 05 Aug 2021 07:51:37 GMT&x-ms-version=2018-11-09&Authorizatio
n=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 206 :: REQ ID : b0f821d4-a01e-008c
-06ce-89e36f000000
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Successfully downloaded blob test/20210721/TFM_ORDER_20210721.csv into file cache as /data/blobfuse-tmp/r
oot/test/20210721/TFM_ORDER_20210721.csv.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_open, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 134: Opening /data/blobfuse-tm
p/root/test/20210721/TFM_ORDER_20210721.csv gives fh = 18, errno = 0
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_open, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 165: Returning success from az
s_open, file = /test/20210721/TFM_ORDER_20210721.csv
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_flush, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 268: azs_flush called with pa
th = /test/20210721/TFM_ORDER_20210721.csv, fi->flags = 0, (((struct fhwrapper *)fi->fh)->fh) = 18.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_flush, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 285: Successfully looked up m
ntPath.  Input path = /test/20210721/TFM_ORDER_20210721.csv, path_link_buffer = /proc/self/fd/18, path_buffer = /data/blobfuse-tmp/root/test/20210721/TFM_ORDE
R_20210721.csv
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_flush, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 307: azs_flush: path = /test/
20210721/TFM_ORDER_20210721.csv, upload_on_close = 0, modified only flag config_options.uploadIfModified = 0, .
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_release, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 381: azs_release called wit
h path = /test/20210721/TFM_ORDER_20210721.csv, fi->flags = 32768
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function azs_release, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 403: Adding file to the GC 
from azs_release.  File = /data/blobfuse-tmp/root/test/20210721/TFM_ORDER_20210721.csv#012.
Aug  5 15:51:37 vm-test-csp2-stage01 blobfuse[1059]: Function run_gc_cache, in file /home/vsts/work/1/s/blobfuse/src/BlobfuseGcCache.cpp, line 151: File /test
/20210721/TFM_ORDER_20210721.csv being considered for deletion by file cache GC.

#3 view at 15:47 - file size change, not go for cache
![image](https://user-images.githubusercontent.com/69842212/128319164-7026a24e-aa31-4420-a7a3-6c2ffeb861c0.png)

**result for "grep blob /var/log/syslog" during  15:55**
--------------------------------------------------------------
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 120: azs_getattr called wi
th path = /test/20210721/TFM_ORDER_20210721.csv
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 180: Object /data/blobfuse
-tmp/root/test/20210721/TFM_ORDER_20210721.csv is not in the local cache during getattr.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]:  ==> REQUEST/RESPONSE :: GET https://satfmprdcsp2stage01.blob.core.windows.net/stage?comp=list&delimiter=
/&include=metadata&maxresults=5000&prefix=test/20210721/TFM_ORDER_20210721.csv&restype=container?&User-Agent=azure-storage-fuse/1.3.8&x-ms-date=Thu, 05 Aug 20
21 07:55:31 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------R
ESPONSE Status :: 200 :: REQ ID : 3b09be83-f01e-0094-73cf-89cefa000000
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 244: In azs_getattr list_s
egmented_item do loop blob prefix: test/20210721/TFM_ORDER_20210721.csv continuation:
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 265: In azs_getattr list_s
egmented_item 0 file test/20210721/TFM_ORDER_20210721.csv
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 288: In azs_getattr found 
blob in list file test/20210721/TFM_ORDER_20210721.csv
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_getattr, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line 327: Blob /test/20210721/T
FM_ORDER_20210721.csv, representing a file, found during get_attr.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: azs_open called with path = /test/20210721/TFM_ORDER_20210721.csv, fi->flags = 8000.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp/root.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp/root/test.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function ensure_files_directory_exists_in_cache, in file /home/vsts/work/1/s/blobfuse/utilities.cpp, line
 96: Making cache directory /data/blobfuse-tmp/root/test/20210721.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]:  ==> REQUEST/RESPONSE :: GET https://satfmprdcsp2stage01.blob.core.windows.net/stage/test/20210721/TFM_OR
DER_20210721.csv?&x-ms-range=bytes=0-16777215&User-Agent=azure-storage-fuse/1.3.8&x-ms-date=Thu, 05 Aug 2021 07:55:31 GMT&x-ms-version=2018-11-09&Authorizatio
n=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 206 :: REQ ID : 219a1cca-301e-0023
-59cf-89c1ff000000
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Successfully downloaded blob test/20210721/TFM_ORDER_20210721.csv into file cache as /data/blobfuse-tmp/r
oot/test/20210721/TFM_ORDER_20210721.csv.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_open, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 134: Opening /data/blobfuse-tm
p/root/test/20210721/TFM_ORDER_20210721.csv gives fh = 18, errno = 0
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_open, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 165: Returning success from az
s_open, file = /test/20210721/TFM_ORDER_20210721.csv
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_flush, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 268: azs_flush called with pa
th = /test/20210721/TFM_ORDER_20210721.csv, fi->flags = 0, (((struct fhwrapper *)fi->fh)->fh) = 18.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_flush, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 285: Successfully looked up m
ntPath.  Input path = /test/20210721/TFM_ORDER_20210721.csv, path_link_buffer = /proc/self/fd/18, path_buffer = /data/blobfuse-tmp/root/test/20210721/TFM_ORDE
R_20210721.csv
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_flush, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 307: azs_flush: path = /test/
20210721/TFM_ORDER_20210721.csv, upload_on_close = 0, modified only flag config_options.uploadIfModified = 0, .
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_release, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 381: azs_release called wit
h path = /test/20210721/TFM_ORDER_20210721.csv, fi->flags = 32768
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function azs_release, in file /home/vsts/work/1/s/blobfuse/fileapis.cpp, line 403: Adding file to the GC 
from azs_release.  File = /data/blobfuse-tmp/root/test/20210721/TFM_ORDER_20210721.csv#012.
Aug  5 15:55:31 vm-test-csp2-stage01 blobfuse[1059]: Function run_gc_cache, in file /home/vsts/work/1/s/blobfuse/src/BlobfuseGcCache.cpp, line 151: File /test
/20210721/TFM_ORDER_20210721.csv being considered for deletion by file cache GC.

**Comment by vibhansa-msft** [comment]
As per the above logs, blobfuse has downloaded a new file every time 'open' was called.  You can see in each test case there is a log
"Successfully downloaded blob test/20210721/TFM_ORDER_20210721.csv" and just few lines above that there is a REST call to download a fresh file in cache. Does not appear to be any issue from blobfuse end.

**Comment by georgeliang0821** [comment]
it is very weird situation for me, from the log file, it reload the file from blob every time, however, we still see the previous version file if the file size is same. The only way to force clean it is unmount and remount blobfuse.

**Comment by vibhansa-msft** [comment]
After your step 2, can you confirm through portal whether the file was updated in container or not.

**Comment by georgeliang0821** [comment]
@vibhansa-msft  yes, confirmed, I re-generate the file via Azure Data Factory and confirmed the file be updated both on Azure Storage Explorer and Azure Portal.

**Comment by vibhansa-msft** [comment]
so file is updated as shown in portal but when blobfuse downloads its still getting an older version you mean ?
There might be a race condition I suspect. Post upload and modification of file try opening the file after couple of seconds (10-20 seconds may be) and validate that you get the latest file.

**Comment by georgeliang0821** [comment]
yes, exactly. By the way, it can show the Last Modified time correct, but the content is older version.

here is my key insight, @vibhansa-msft can you have the simple test in your environment and see if you can reproduce.
1. the new version file size is same: while blobfuse download the file, it will cache forever, unless you unmount,
2. the new version file size is different: always can get the new version data.

**Comment by vibhansa-msft** [comment]
I was looking back at the logs shared earlier and I do not see any file change / upload related logs in that snippet. Are the file changes being done outside the scope of blobfuse ? Blobfuse does not support file-changes being done in parallel through other means. Set file-cache-timeout to  '0' and attr-cache to 'false' if so and try this test case.

**Comment by georgeliang0821** [comment]
after work with @vibhansa-msft  and investigate the cache is not from blobfuse, that's from Linux Kernel cache. thanks Vibhansa.

**Comment by vibhansa-msft** [comment]
Thanks @georgeliang0821 for confirming. As we discussed Blobfuse involves both file and attribute caching and hence it does not support a use-case where file is being updated directly to container without involving blobfuse mount, To make this work we need to disable all kind of attribute and file caching in blobfuse along with cleaning up kernel page cache. Choosing so will impact the performance and shall be avoided.

Mount command used to disable all caching:
blobfuse /mnt/blobfuse_mount --tmp-path=/mnt/blobfuse_tmp --config-file=blobfuse.cfg --file-cache-timeout-in-seconds=0 --use-attr-cache=false -o attr_timeout=0 -o entry_timeout=0 -o negative_timeout=0 -o allow_root

Command used to wipe out kernel cache:
sysctl -w vm.drop_caches=

**Comment by vibhansa-msft** [comment]
With above mentioned steps user is able to get updated file on Open/Read combination. Closing the issue.
