### ISSUE TITLE
Copy to blobfuse without creating temp files

### ISSUE THREAD

**Issue by kamilrotter** [Azure/azure-storage-fuse#632]
### Which version of the blobfuse was used?
blobfuse 1.3.7

### Which OS (please include version) are you using?
CentOS Linux release 7.9.2009

### What problem was encountered?
Hi, apologies if that topic was already discussed, I haven't been able to find anything online. I'm looking into improvements for our backup process (few files ~500G files) and noticed that all files that are being copied to Blob Storage via blobfuse first need a copy in temp space. That looks redundant, as I'm using exactly same mount to store files ready for backup and than blobfuse creates a copy of every one of them in order to move to Storage. This cause issues with disk capacity and performance (extra step to create copy of file). Is there a reason why it works that way, or a procedure to copy files 'directly', omitting temp space? 

### Have you found a mitigation/solution?
No.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
NA

### If relevant, please share your mount command.
NA

**Comment by vibhansa-msft** [comment]
As of now Blobfuse does not have any option to upload file(s) directly. Disk cache can not be avoided completely but you can control the disk usage by setting "--file-cache-timeout-in-seconds=0" in mount command. This will ensure that as soon as all open handles to a given file are closed, it will be removed from disk cache.

**Comment by AvivAvital2** [comment]
Hi @vibhansa-msft ,
Any chance this is resolved in v2 with the virtual directory feature?

**Comment by vibhansa-msft** [comment]
With blobfuse2 we do have a streaming write feature where we can upload the data directly. However, that will have a good performance impact, so you need to try it out and see if the performance requirements are met and suits you or not.

**Comment by vibhansa-msft** [comment]
Streaming write solves this problem of temp copy to disk cache hence closing this issue here. We are also planning to add sequential write support in our new block-cache component which offers higher performance.
