### ISSUE TITLE
Error creating a mount in a dockerfile 

### ISSUE THREAD

**Issue by dipesh747** [Azure/azure-storage-fuse#633]
### Which version of the blobfuse was used?
1.38

### Which OS (please include version) are you using?
Debian 10 

### What problem was encountered?
I was unable to build a docker file which included the mount point. The docker file will run via docker compose. 

Docker file is here: 

`FROM apache/airflow:latest
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY ./airflow.cfg ${AIRFLOW_HOME}/airflow.cfg
#Below used for mounting to azure storage accountsudo apt-get install blobfuse fuse
USER root
RUN   apt-get update && apt-get -y install software-properties-common\
&& apt-get update

RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add - \
&& apt-add-repository https://packages.microsoft.com/debian/10/prod \
&& apt-get update \
&&  apt-get update && apt-get -y install blobfuse fuse dos2unix

RUN mkdir -pv ${AIRFLOW_HOME}/mnt/dags \
&& chown -R airflow ${AIRFLOW_HOME}/mnt/dags

RUN mkdir -pv ${AIRFLOW_HOME}/mnt/cache \
&& chown -R airflow ${AIRFLOW_HOME}/mnt/cache

COPY /fuse_connection.cfg  ${AIRFLOW_HOME}/fuse_connection.cfg
RUN dos2unix  ${AIRFLOW_HOME}/fuse_connection.cfg

RUN blobfuse ${AIRFLOW_HOME}/mnt/dags fuse delay_connect,defaults,_netdev\
 --tmp-path=${AIRFLOW_HOME}/mnt/cache -o attr_timeout=240 -o entry_timeout=240\
 -o negative_timeout=120 --config-file=${AIRFLOW_HOME}/fuse_connection.cfg\
  --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 -o allow_root` 

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

+ blobfuse /opt/airflow/mnt/dags fuse delay_connect,defaults,_netdev --tmp-path=/opt/airflow/mnt/cache -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/opt/airflow/fuse_connection.cfg --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 -o allow_root
fuse: invalid argument `fuse'

**Comment by NaraVen** [comment]
your run blobfuse command is wrong. The parameter "fuse delay_connect,defaults,_netdev" is indeed not a valid param. Please read the blobfuse Readme for a list of valid params.
