### ISSUE TITLE
Segfault when running blobfuse in Kubernetes

### ISSUE THREAD

**Issue by cornel-masson** [Azure/azure-storage-fuse#634]
### Which version of the blobfuse was used?
Tested with 1.3.3 and 1.3.8

### Which OS (please include version) are you using?
Host machine (uname): **4.15.0-153-generic** #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Kubernetes pod on that host (uname): **4.15.0-153-generic** #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 GNU/Linux

The pod is running my custom Docker image, which is based on **python:3.9-slim**, which in turn is based on **debian:buster-slim** (Debian GNU/Linux 10)

### What problem was encountered?
blobfuse fails in the Kubernetes pod on that host, but works everywhere else (e.g. directly on the host machine).

When I issue this command, I get a segfault (yes, both directories and config file do exist):

`blobfuse /images -o rw,allow_other --tmp-path=/tmp/images/imagestore --config-file=/blobfuse.cfg --use-attr-cache=true --use-https=true`

> `Segmentation fault (core dumped)`

I can't see the core dump. _ulimit -c_ is already _unlimited_, so that's not the issue.  It seems the Debian is configured to redirect core dumps to apport:

`cat /proc/sys/kernel/core_pattern`

> `|/usr/share/apport/apport %p %s %c %d %P %E`

However, apport itself is not installed. I tried to install it, but could not get it working. I also can't update core_pattern to get a normal core dump, since it is a kernel protected file.

### Have you found a mitigation/solution?
It only fails in the Kubernetes pod on that host. It _works_ when I issue the same command _on that host machine itself._ It also works when I deploy it in Kubernetes in Docker Desktop for Windows. The only combination that doesn't work is: in Kubernetes on that (Debian) host.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Syslog is not enabled. And I can't seem to enable it with systemd. The contents of /var/log is:

`alternatives.log
apt/
btmp
dpkg.log
exim4/
faillog
lastlog
nginx/
supervisor/
unattended-upgrades/
wtmp`

**Comment by gapra-msft** [comment]
Hi @cornel-masson 

Thank you for reporting this issue. Could you please enable logging by adding `--log-level=DEBUG` to your mount command? This should enable logging and log to syslog. Once you've enabled logging, could you share the logs from syslog in the issue?

**Comment by vibhansa-msft** [comment]
Can you also add "--basic-remount-check=true" to your cli options and give it a try.

**Comment by cometta** [comment]
yes "--basic-remount-check=true" solve the issue for me

**Comment by vibhansa-msft** [comment]
@cometta : Thanks for the confirmation. Closing the issue as suggested option resolves the issue.

**Comment by cornel-masson** [comment]
This does not solve the problem for me, I still get the segfault. I assume --basic-remount-check=true avoids doing the mount again if it already exists? I've seen a segfault in another of my use cases if it tries to mount if it is already mounted - this is not the case at the moment. 

I have also previously tried --log-level=DEBUG: it does nothing in my case. There's no syslog output. Here is my current command, which still result in a segfault:

blobfuse /images -o rw,allow_other --tmp-path=/tmp/images/imagestore --config-file=/blobfuse.cfg --use-attr-cache=true --use-https=true --basic-remount-check=true --log-level=DEBUG

**Comment by vibhansa-msft** [comment]
"--log-level=LOG_DEBUG" is the correct option to collect logs.
"--basic-remount-check=true" : Off late we have observed some fatal failures when we try to check whether folder is already mounted or not using a syscall. On certain systems this syscall results in a crash. So this CLI option was added to avoid that syscall and rather refer to mtab file to figure out folder is mounted or not. Was suspecting same failure in your case hence suggested this option.
Try collecting debug logs and share. If you are not able to collect debug logs, another option is to add "-d" option in your cli and some trace logs will come on your console which you can collect and share.

**Comment by cornel-masson** [comment]
I've added the -d, but still the same, no debug output either. Nothing useful in /var/log either.

`blobfuse -d /images -o rw,allow_other --tmp-path=/tmp/images/imagestore --config-file=/blobfuse.cfg --use-attr-cache=true --use-https=true --basic-remount-check=true --log-level=DEBUG --file-cache-timeout-in-seconds=120 --cancel-list-on-mount-seconds=60 -o attr_timeout=120 -o entry_timeout=120 -o negative_timeout=120`

`Segmentation fault (core dumped)`

**Comment by vibhansa-msft** [comment]
Can you try with below command, and expectation is on the console where you hit this command shall start dumping some fuse logs. By default blobfuse logs with this will go to /var/log/messages (unless you have blobfuse syslog filter installed)

blobfuse /images --tmp-path=/tmp/images/imagestore --config-file=/blobfuse.cfg --use-attr-cache=true --use-https=true --basic-remount-check=true --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120 --cancel-list-on-mount-seconds=60 -o attr_timeout=120 -o entry_timeout=120 -o negative_timeout=120 -o allow_other -d

**Comment by cornel-masson** [comment]
Sorry, I was looking for syslog in the container, here is the segfault in the host's syslog:

Aug 17 08:15:12 s3a-deploy-test-3 kernel: [112519.962647] blobfuse[8945]: segfault at 0 ip 00007f2744c2a3d6 sp 00007ffdaa44d010 error 4 in libc-2.28.so[7f2744bd2000+148000]

**Comment by vibhansa-msft** [comment]
Try generating core dump if possible, without that it will be difficult to root-cause this segfault. Just to re-iterate you are saying this happens only when you run Kubernetes pod on debian host, other combinations are working fine for you ?

**Comment by cornel-masson** [comment]
> Try generating core dump if possible, without that it will be difficult to root-cause this segfault. Just to re-iterate you are saying this happens only when you run Kubernetes pod on debian host, other combinations are working fine for you ?

It works if I run the same Docker image straight under Docker (I usually use docker-compose for this). However, If I run it as a k8s pod, it segfaults.

It works:
- On the Ubuntu host itself
- In the (Debian) container running under straight Docker
- In the (Debian) container under Kubernetes in Docker Desktop (Windows)

It segfaults:
- In the (Debian) container under Kubernetes on the Ubuntu host
  - Using k3s
  - Using minikube
  - Using k0s

**Comment by cornel-masson** [comment]
I see apport.log files on the host, but all the entries are like this:

`ERROR: apport (pid 24240) Tue Aug 17 07:52:09 2021: host pid 24239 crashed in a container without apport support`

As mentioned before, the container has core_pattern configured to redirect dumps to apport, but apport itself is not installed in the container. 

AFAIK apport dumps to /var/crash, but there is only one (oldish) file in there: `_usr_bin_cloud-init.0.crash`

**Comment by andyzhangx** [comment]
our blob csi driver e2e tests on kubenetes work well, it's using `Ubuntu 18.04.5 LTS   5.4.0-1055-azure` kernel.
```
print out all nodes status ...
NAME                        STATUS   ROLES    AGE   VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8s-agentpool1-27450068-0   Ready    agent    16m   v1.18.20   10.240.0.4     <none>        Ubuntu 18.04.5 LTS   5.4.0-1055-azure   containerd://1.4.6+azure
k8s-agentpool1-27450068-1   Ready    agent    16m   v1.18.20   10.240.0.35    <none>        Ubuntu 18.04.5 LTS   5.4.0-1055-azure   containerd://1.4.6+azure
k8s-master-27450068-0       Ready    master   16m   v1.18.20   10.255.255.5   <none>        Ubuntu 18.04.5 LTS   5.4.0-1055-azure   containerd://1.4.6+azure
```

**Comment by vibhansa-msft** [comment]
@cornel-masson : Can you check kernel version matches with the one mentioned by Andy above.

**Comment by cornel-masson** [comment]
> @cornel-masson : Can you check kernel version matches with the one mentioned by Andy above.

My kernel is: **4.15.0-153-generic**

Could that be an issue?

**Comment by sshepel** [comment]
Hi guys,
I'm seeing exactly the same error as @cornel-masson after k8s upgrade from 1.18 to 1.21.
My guess, it might be because of braking changes in version 1.19 where Seccomp been graduated to GA.

**Comment by vibhansa-msft** [comment]
@cornel-masson : I guess you tried this "basic-remount-check" cli option and that did not work in your case ?

**Comment by vibhansa-msft** [comment]
@andyzhangx : Report that you shared earlier in this thread also mention k8s version as 1.18 (1.18.20). Do we have any similar report with 1.21 ?

**Comment by cornel-masson** [comment]
> @cornel-masson : I guess you tried this "basic-remount-check" cli option and that did not work in your case ?

Yes, it still segfaults.

**Comment by vibhansa-msft** [comment]
Is it possible to validate on 1.18, just to confirm the theory that its k8s latest version issue ?

**Comment by cornel-masson** [comment]
I have now tested with k3s server version v1.18.20+k3s1: it still segfaults.

**Comment by vibhansa-msft** [comment]
@andyzhangx : Any suggestions here, it appears to be same with 1.18 as well.
@cornel-masson : Is there a way you can generate core-dump for this fault. Without that it will be difficult to root-cause the issue.

**Comment by andyzhangx** [comment]
> @andyzhangx : Any suggestions here, it appears to be same with 1.18 as well.
> @cornel-masson : Is there a way you can generate core-dump for this fault. Without that it will be difficult to root-cause the issue.

@vibhansa-msft I suspect it's related to kernel version, there are quite a lot blobfuse k8s tests runnong on `Ubuntu 18.04.5 LTS   5.4.0-1055-azure`, all work well.

**Comment by vibhansa-msft** [comment]
@cornel-masson : can you try upgrading kernel version and validate.

**Comment by cornel-masson** [comment]
Waiting on my IT to provision a new Ubuntu 20.04 (kernel 5.4).

**Comment by cornel-masson** [comment]
Meanwhile, I have managed to get a core dump. 
[blobfuse-core-dump.zip](https://github.com/Azure/azure-storage-fuse/files/7037386/blobfuse-core-dump.zip)

**Comment by vibhansa-msft** [comment]
@cornel-masson : I am not able to figure out the stack from core. Can you share what OS version you are using or which rpm/deb pkg you used for blobfuse 1.3.8.

**Comment by vibhansa-msft** [comment]
Also core file show 
"Core was generated by `blobfuse /images -o rw,allow_other --container-name=imagestore --tmp-path=/tmp/'
Does that mean "--basic-remount-check=true" was not present in the command.

**Comment by cornel-masson** [comment]
> Also core file show
> "Core was generated by `blobfuse /images -o rw,allow_other --container-name=XXXXXXX--tmp-path=/tmp/'
> Does that mean "--basic-remount-check=true" was not present in the command.

Yes, for this test I used my existing app image that still uses the old blobfuse (1.3.3): this version doesn't yet support basic-remount-check), but I am 100% sure it happens on first mount - it was not mounted before.

**Comment by vibhansa-msft** [comment]
Fix that was provided with "--basic-remount-check" option is not related to first mount or subsequent mount. To check whether the folder is already mounted or not blobfuse calls a system api to get list of mount points but that system call itself was resulting into SEGFAULT on few systems. Hence we made this change where instead of calling the system api we read the 'mtab' file manually to figure out all current mount points. First suspect for this crash is that api only, so if possible try version 1.3.8 with this cli option. If it cores out there as well then share that core file. Meanwhile I will try to get more info from current core file. For that can you share me the Debian version you are using where blobfuse is being mounted.

**Comment by cornel-masson** [comment]
Host machine (uname): 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Kubernetes pod on that host (uname): 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 GNU/Linux

The pod is running my custom Docker image, which is based on python:3.9-slim, which in turn is based on debian:buster-slim (Debian GNU/Linux 10)

**Comment by cornel-masson** [comment]
UPDATE: I have now tested with blobfuse **1.3.8** on the same host & k3s (v1.18) and now it **WORKS**. No segfault.

**Comment by vibhansa-msft** [comment]
Quick way to ensure its the crash we suspect : you can remove that new cli option of basic-remount-check and try once. It might run into SEGFAULT again.

**Comment by vibhansa-msft** [comment]
Also "-o rw,allow_other" option that you provide is kind of not required. By default our mount is in read-write mode only so you can only keep "-o allow_other". No need to provide "--use-https=true" by default its set to true only. Giving a sample on what shall be used as mount command in your case:

AZURE_STORAGE_ACCOUNT=<account> AZURE_STORAGE_ACCESS_KEY=<account key here> blobfuse /images -o allow_other --container-name=imagestore --tmp-path=/tmp/images/imagestore --use-attr-cache=true --basic-remount-check=true

**Comment by vibhansa-msft** [comment]
If 1.3.8 with remount-check config is working fine for you, shall we close this issue ?

**Comment by cornel-masson** [comment]
> Quick way to ensure its the crash we suspect : you can remove that new cli option of basic-remount-check and try once. It might run into SEGFAULT again.

I've re-tested: with blobfuse 1.3.**8** it works _with or without_ the basic-remount-check.

**Comment by cornel-masson** [comment]
> If 1.3.8 with remount-check config is working fine for you, shall we close this issue ?

Sure, thanks very much for your help.

**Comment by vibhansa-msft** [comment]
Thanks @cornel-masson for your quick try-outs and confirmation.
SEGFAULT is not seen with 1.3.8 version so closing this issue.

**Comment by vibhansa-msft** [comment]
@cornel-masson : can you share steps on how to configure your k8s to generate core-dump.

**Comment by cornel-masson** [comment]
> @cornel-masson : can you share steps on how to configure your k8s to generate core-dump.

Sorry, Vikas, missed your message in between others. The issue I was struggling with is actually quite obvious in hindsight: core dumps are handled at kernel level, and as you know, all containers on the same host share the host's kernel. So, core dump configuration is done on the host, not in the container. The host is Ubuntu 18.04, which by default is set up to use [apport](https://wiki.ubuntu.com/Apport) to intercept and handle core dumps. However, the host only had the core_pattern configured to redirect to apport, it didn't have the apport handler installed. So I installed it on the host, and after that I saw the dumps appearing in `/var/crash` on the host (that's the directory where apport writes dumps to). On a Linux host you can check/configure where core dumps go to by looking at the file: [/proc/sys/kernel/core_pattern.](https://sigquit.wordpress.com/2009/03/13/the-core-pattern/).

**Comment by vibhansa-msft** [comment]
Thanks a lot @cornel-masson for sharing this info.

**Comment by chance2021** [comment]
> Can you also add "--basic-remount-check=true" to your cli options and give it a try.

This works for me! Thanks! @vibhansa-msft 

Below is the testing env
```
# AKS v1.22.6
# Pod
kubectl create -f- <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
    - name: ubuntu
      image: debezium/postgres:14
      command: ["sleep"]
      args: ["infinity"]
      securityContext:
        privileged: true
EOF

# Running command in the pod
apt update && \
    apt-get install wget -y && \
    wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install blobfuse -y && \
    apt-get install libcurl3-gnutls -y

export AZURE_STORAGE_ACCOUNT=<YourAzureStorageAccountName>
export AZURE_STORAGE_ACCESS_KEY=<YourAzureStorageAccessKey>
blobfuse </path/to/folder> --tmp-path=/tmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --basic-remount-check=true --container-name=<containerName> --log-level=LOG_DEBUG
```
