### ISSUE TITLE
Mount blob using Managed Identity or service principal failed in Azure China Cloud

### ISSUE THREAD

**Issue by Ginny130** [Azure/azure-storage-fuse#638]
### Which version of the blobfuse was used?
1.3.7

### Which OS (please include version) are you using?
CentOS 8.2

### What problem was encountered?
I'm trying to mount Azure blob storage container to my linux using Managed Identity or Service Principal. I have checked that the Managed Identity and Service Principal have sufficient permission in the Azure storage account level.

My reference docs: 
1. https://techcommunity.microsoft.com/t5/azure-paas-blog/mount-blob-storage-on-linux-vm-using-managed-identities-or/ba-p/1821744
2. https://github.com/Azure/azure-storage-fuse

**My environment is using Azure China account to mount the blob.**
I tried to use storage account key in the fuse_connection.cfg file, it woks fine. I'm able to mount the blob.
However, when I switch to Managed Identity or Service Principal, it shows cannot mounted.

1) **using Managed Identity**
fuse_connection.cfg file:
accountName accountfiletest1
authType MSI
identityClientId exxxxxx-8653-xxxx-xxxxxxxxxxxxxxxxxxx
identityObjectId e2a55f52-xxx-xxxx-xxxx-xxxxxxxxx
msiEndpoint accountfiletest1.core.chinacloudapi.cn
containerName blobbbcontainer

Errors:
Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Unmounting blobfuse.
Unmounted blobfuse successfully.

2)**using Service Principal**
fuse_connection.cfg file:
accountName accountfiletest1
authType SPN
servicePrincipalClientId xxxxxxxxx-6a40-xxxx-b3a1-xxxxxxxxxxxxx
servicePrincipalTenantId xxxxxxxxxx-0exx-xxxxxxx-axx4-xxxxxxxxxxxx
aadEndpoint login.partner.microsoftonline.cn
containerName blobbbcontainer

Errors:
Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Unmounting blobfuse.
Unmounted blobfuse successfully.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Aug 28 15:20:47 centos8 blobfuse[4010]: OAUTH Token : Refresh token failed Failed to retrieve OAuth Token from IMDS endpoint (CURLCode: 3, HTTP code: 0):
Aug 28 15:20:47 centos8 blobfuse[4010]: Unable to retrieve OAuth token: Failed to retrieve OAuth Token from IMDS endpoint (CURLCode: 3, HTTP code: 0):
Aug 28 15:20:47 centos8 blobfuse[4010]: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Aug 28 15:20:47 centos8 blobfuse[4010]: Unmounting blobfuse.

Aug 28 15:29:26 centos8 blobfuse[5225]: OAUTH Token : Refresh token failed Failed to retrieve OAuth Token (CURLCode: 3, HTTP code: 0):
Aug 28 15:29:26 centos8 blobfuse[5225]: Unable to retrieve OAuth token: Failed to retrieve OAuth Token (CURLCode: 3, HTTP code: 0):
Aug 28 15:29:26 centos8 blobfuse[5225]: Failed to get token using SPN credentials.
Aug 28 15:29:26 centos8 blobfuse[5225]: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Aug 28 15:29:26 centos8 blobfuse[5225]: Unmounting blobfuse.
Aug 28 15:29:26 centos8 blobfuse[5225]: Unmounted blobfuse successfully.

### If relevant, please share your mount command.
 blobfuse ~/mycontainer --tmp-path=/mnt/blobfusetmp  --config-file=/root/fuse_connection.cfg -o allow_other

**Comment by vibhansa-msft** [comment]
Kindly enable LOG_DEBUG through cli option and share the log file for failure case.

**Comment by vibhansa-msft** [comment]
In above logs response code is 0, which means operation is timing out. Might be something wrong with the connection.
One quick way to validate your connection is to try below command and see if you can get an OAuth token or not

curl -X GET -H 'Content-Type: application/x-www-form-urlencoded'
-d 'grant_type=client_credentials&client_id=<your_spn_client-id>&resource=<https://<your_storage_ACCOUNT_NAME>.blob.core.windows.net>&client_secret=<your_spn_secret>'
https://login.microsoftonline.com//oauth2/token -v

**Comment by Ginny130** [comment]
> In above logs response code is 0, which means operation is timing out. Might be something wrong with the connection.
> One quick way to validate your connection is to try below command and see if you can get an OAuth token or not
> 
> curl -X GET -H 'Content-Type: application/x-www-form-urlencoded'
> -d 'grant_type=client_credentials&client_id=<your_spn_client-id>&resource=<https://<your_storage_ACCOUNT_NAME>.blob.core.windows.net>&client_secret=<your_spn_secret>'
> https://login.microsoftonline.com//oauth2/token -v

Hi,  

Thanks for you reply! 

1. Since we are using the blob that in Azure China, I tried 2 different commands: one is "curl -X GET -H 'Content-Type: application/x-www-form-urlencoded'-d 'grant_type=client_credentials&client_id=xxxxxxxxx-xxxx-xxx-bx3a1-6299f8cf9e6f&resource=https://accountfiletest1.core.chinacloudapi.cn&client_secret=xxxxxxxxx~~xxxxxxxxxxxxxxEK.~4W' https://**login.microsoftonline.com**//oauth2/token -v" The result is:
![20210831214948](https://user-images.githubusercontent.com/89697437/131520183-853499cd-4410-4ce9-bd32-5c9e0526faaa.png)

Another one I used was 'curl -X GET -H 'Content-Type: application/x-www-form-urlencoded'-d 'grant_type=client_credentials&client_id=xxxxxxxxx-xxxxx-xxxxx-b3a1-6299f8cf9e6f&resource=https://accountfiletest1.core.chinacloudapi.cn&client_secret=xxxxxxx~~xxxxxxxxxxxxxxK.~4W' https://**login.partner.microsoftonline.cn**//oauth2/token -v'. But it seems like we got the same result.
![20210831214135](https://user-images.githubusercontent.com/89697437/131520265-079174f9-9b3c-4636-b8f8-7f4286b59134.png)

2. We also captured tcpdump logs when we were mounting the blob. Here we also tried two approaches for that. 
    1) In my fuse_connection.cfg, I didn't add the aadEndpoint info, there are only 'accountName, authType, servicePrincipalClientId, servicePrincipalTenantId and containerName' in the config file. From the  logs picture that I uploaded as the below, we are able to see that there is a login message, which means when I didn't fill the aadEndpoint parameter in the configure file, it will automatically turn to login.microsoftonline.com to authenticate. However, it doesn't apply to Azure China environment. Even I skipped the aadEndpoint, still cannot mount the blob by using blobfuse.
![20210831215115](https://user-images.githubusercontent.com/89697437/131519964-bbbc46ea-d221-4687-b479-dcd6c183257f.png)

2)Then we added an endpoint (aadEndpoint login.partner.microsoftonline.cn) to the fuse_connection.cfg file. From the log, I don't see any requests for authentication. Are there any problems between blob and blobfuse? 
![20210831215212](https://user-images.githubusercontent.com/89697437/131520443-9915da41-2c98-4dbc-96bc-8acbbf4b37a4.png)

Please advise, thanks in advance!

**Comment by vibhansa-msft** [comment]
When you are using CUrl command with "https://login.partner.microsoftonline.cn//oauth2/token -v" as msi_endpoint why is that returning "404 error". That is outside blobfuse and if connection and credentials are correct that shall have worked ?
For you config msiEndpoint or aadEndpoint shall be present in config file otherwise OAuth token request will go to login.microsoftonline.com only by default. Can you upgrade to blobfuse version 1.3.8 and try once. Have below SPN parameters in your config along with account and container
--------
servicePrincipalClientId
servicePrincipalTenantId
servicePrincipalClientSecret
aadEndpoint
-----
Client secret can also be configured using AZURE_STORAGE_SPN_CLIENT_SECRET env variable, just in case you dont want to dump it to a file.

**Comment by Ginny130** [comment]
> When you are using CUrl command with "https://login.partner.microsoftonline.cn//oauth2/token -v" as msi_endpoint why is that returning "404 error". That is outside blobfuse and if connection and credentials are correct that shall have worked ?
> For you config msiEndpoint or aadEndpoint shall be present in config file otherwise OAuth token request will go to login.microsoftonline.com only by default. Can you upgrade to blobfuse version 1.3.8 and try once. Have below SPN parameters in your config along with account and container
> "
> servicePrincipalClientId
> servicePrincipalTenantId
> servicePrincipalClientSecret
> aadEndpoint
> "
> Client secret can also be configured using AZURE_STORAGE_SPN_CLIENT_SECRET env variable, just in case you dont want to dump it to a file.

Thanks for providing this, that works for me. Upgrade to version 1.3.8 solved this issue.

I really appreciate!!!

**Comment by vibhansa-msft** [comment]
Thanks for confirmation. Closing this issue. Feel free to reopen if you hit the issue.
