### ISSUE TITLE
Feature Request: CLI & Portal integration

### ISSUE THREAD

**Issue by mustafakasap** [Azure/azure-storage-fuse#64]
Would be great to have CLI integration. So when creating an Unix VM, it will be possible to enable/preinstall blobfuse drive and attached to a blob container

**Comment by seguler** [comment]
Would it be enough if this was part of the Azure Linux distros so it comes preinstalled ?

**Comment by mkiernan** [comment]
I think it would be great if it was embedded in the linux distro to start with. Later it would be great to be able to select one or many storage accounts/containers to mount during installation.

**Comment by rishabpoh** [comment]
This is a part of the linux distributions, let us know if you still want portal integration.
