### ISSUE TITLE
Metadata Conservation

### ISSUE THREAD

**Issue by wikiBee** [Azure/azure-storage-fuse#642]
### Which version of the blobfuse was used?
1.3.8

### Which OS (please include version) are you using?
Linux Ubuntu 20.04

### What problem was encountered?
Metadata is not being conserved when moving files among folders

### Have you found a mitigation/solution?
Not yet

**Comment by vibhansa-msft** [comment]
Can you provide little more details on what is your exact testcase and what command you are using.
When blobfuse uploads a file back to container, it does not preserve any metadata.

**Comment by vibhansa-msft** [comment]
What kind of storage account you have ? For block-blob account there is no direct rename API on store end so we blobfuse does a data copy and then delete the source file, hence metadata is not preserved. For Gen-2 account (HNS enable) store has a rename API and in that case metadata is preserved across rename operation.

**Comment by vibhansa-msft** [comment]
I just verified with the block blob account and in that case as well I see metadata is preserved when file is moved to a different folder using 'mv' command. Can you give more details on your exact test case.

**Comment by vibhansa-msft** [comment]
Kindly share more details on this to look further.

**Comment by vibhansa-msft** [comment]
Closig this issue as there is no update. Feel free if the issue persists.
