### ISSUE TITLE
permission on reading / writing on blob-fused folder denied

### ISSUE THREAD

**Issue by JochemBoersma** [Azure/azure-storage-fuse#643]
### Which version of the blobfuse was used?
blobfuse 1.3.8

### Which OS (please include version) are you using?
Ubuntu 20.04 LTS

### What problem was encountered?
After following the steps in the [manual](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux), I couldn't access the fresh mounted container. It consequently states 'permission denied.'
Performing `ls -alh` on the parent directory returns:
![image](https://user-images.githubusercontent.com/17458761/132574838-e27dd542-1e87-4e59-a543-6dba35b08200.png)

### Have you found a mitigation/solution?
Nope, couldn't find a solution by myself. 

### If relevant, please share your mount command.
Mount command was:
```
sudo blobfuse ~/blobcontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/<user>/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow-other
```
(with in fuse_connection.cfg filled with what is in the manual: accountName, accountKey and containerName)

**Comment by vibhansa-msft** [comment]
Mount path and temp folder shall be in users ownership and shall have full access to user. Can you ensure that and mount without 'sudo'. Also you can add "--log-level=LOG_DEBUG" in your mount cli, which dumps blobfuse logs to syslog. If there is any error at blobfuse level we can figure out from those logs.

**Comment by vibhansa-msft** [comment]
Kindly share issue still persists or not post permissions validations. Kindly share blobfuse logs if not.

**Comment by JochemBoersma** [comment]
Just provisioned a 'brand-new' Azure vm, and repeated the processes.

- **Installed** according the [manual](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux)
- **Prepared for mouning**: didn't used a RAM disk; used an SSD, which has the /mnt/ folder:
```
kara@ant:~$ cd /mnt/
kara@ant:/mnt$ ls
DATALOSS_WARNING_README.txt  lost+found
```
and
```
mkdir /mnt/blobfusetmp -p
mkdir: cannot create directory ‘/mnt/blobfusetmp’: Permission denied
```
so i did:
```
sudo mkdir /mnt/resource/blobfusetmp -p
sudo chown kara /mnt/blobfusetmp/
```
(according the manual). Further I've made an fuse_connection.cfg, made access strict, and made a new dir.

- **Mounting**:
without `sudo`
```
kara@ant:~$ blobfuse ~/pet-analysis --tmp-path=/mnt/blobfusetmp --config-file=/home/kara/fuse_connection.cfg -o attr_timeout=240 -o entry-timeout=240 -o negative_timeout=120
fuse: unknown option `entry-timeout=240'
kara@ant:~$ blobfuse ~/pet-analysis --tmp-path=/mnt/blobfusetmp --config-file=/home/kara/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
```

**Comment by JochemBoersma** [comment]
And in addition: That worked! Omitting `sudo` was the key, i think?

**Comment by vibhansa-msft** [comment]
Great. When mount is done with sudo then mounted directory will be accessible to sudo user only and in such scenario doing a read/write to a file on that path without sudo access will fail.

Closing this issue as removing 'sudo' worked for you. Feel free to reopen if you are still facing problem with the mount.

**Comment by JochemBoersma** [comment]
Thanks for support and clarification. 

Would be nice if the manual (https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux) will be changed accordingly.

**Comment by vibhansa-msft** [comment]
Sure will raise a request for the same,
