### ISSUE TITLE
[Question] Is it possible to mount to RAGRS storage account secondary endpoint.

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-storage-fuse#645]
One cx wants to mount to storage account secondary endpoint, is it possible? I understand that storageaccount-secondary is not a valid storage account, but the API storageaccount-secondary.blob.core.windows.net exists.

accountName storageaccount-secondary
accountKey xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
containerName bfusectn1

**Comment by vibhansa-msft** [comment]
This has not been tried but it shall work. However is there a rational to try this ? When primary end-point is down, secondary will be having good amount of load and secondary are generally recommended for read work-loads.

**Comment by vibhansa-msft** [comment]
Let me know if it worked for you.

**Comment by yangchengs** [comment]
@vibhansa-msft I have a workaround to mount secondary endpoint and it is readonly.

accountName myaccount-secondary
sasToken sasToken
containerName mycontainer

**Comment by vibhansa-msft** [comment]
With 'key' its not working and user is getting a "bad-request" reply from storage. Current workaround is to use SAS instead.
Thanks @yangchengs to figure this out.
