### ISSUE TITLE
Can't read file in folder mounted with blobfuse

### ISSUE THREAD

**Issue by doxt3r** [Azure/azure-storage-fuse#647]
### Which version of the blobfuse was used?
blobfuse 1.4.1

### Which OS (please include version) are you using?
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

### What problem was encountered?
unable to read existing blob file after mounting

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

### If relevant, please share your mount command.
`blobfuse --log-level=LOG_DEBUG mine/ --tmp-path=/mnt/resource/blobfusetmp  --config-file=/home/beebz/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o gid=33`

### More infos:

```
 $ ls -la mine/

 drwxrwx---  2 beebz www-data 4096 Sep 21 17:52 .
 drwxr-xr-x 19 beebz beebz 4096 Sep 20 17:56 ..
 drwxrwx---  2 beebz www-data 4096 Jan  1  1970 files
```
If i try to read an existing file, created by Blob rest api:
```
$ ls -la mine/files/file.html
-rwxrwx--- 1 beebz www-data 7146 Sep 21 16:49 /home/beebz/mine/files/file.html
$ cat /home/beebz/mine/files/file.html
cat: /home/beebz/mine/files/file.html:  Permission denied
```
If i create a new file, this works fine:
```
$ echo "test"  > mine/files/test.txt
$ ls -la mine/files/test.txt 
-rwxrwx--- 1 beebz www-data 5 Sep 21 18:25 mine/files/test.txt
$ cat mine/files/test.txt 
test
```

Thanks

**Comment by vibhansa-msft** [comment]
Can you try below mount cli and check it works for you. (first argument has to be mount path)

blobfuse mine/ --tmp-path=/mnt/resource/blobfusetmp --config-file=/home/beebz/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_DEBUG -o allow_other

Also the mount path and temp-path that are provided, user mounting blobfuse shall have full-access to those otherwise it will not work.

Any specific reason to include -o gid=33 parameter in mount ?

**Comment by doxt3r** [comment]
Hi,
Thanks, this worked for me ,I can read files now,  i think the solution was the allow_other option.
All files in the folder are now with 777 permissions, how to make whole folder read only ?

PS: The option gid=33 was for www-data group, so apache can read files.

**Comment by vibhansa-msft** [comment]
What kind of account you are using ? if its gen-2 account then files will represent the permissions as per ACLs, for block blob account its only two options. If "allow_other is there it will be 777, if its not there it will be 775.

Blobfuse does not have a way to control permissions directly. If your use-case is just to make everything read-only, one way to do this is to add "-o ro" option in mount command which will mount the file-system itself in read-only mode.

**Comment by doxt3r** [comment]
Hi, the ro option did the trick, thank you very much.
I used -o allow_other + -o ro, this fit our needs.
