### ISSUE TITLE
The Installation page has an outdated RHEL repository (https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation)

### ISSUE THREAD

**Issue by richardlm57** [Azure/azure-storage-fuse#649]
Hello everyone! I'm filling the template automatically loaded as "placeholder":

### Which version of the blobfuse was used?
1.3.6

### Which OS (please include version) are you using?
RHEL 7.8

### What problem was encountered?
I was trying to install blobfuse>=1.3.7 in my RHEL 7.8 VM from RPM repository as shown in https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation because I wanted to use the flag --upload-modified-only=false, but the installed version was blobfuse 1.3.6

### Have you found a mitigation/solution?
The repository link contained in the Installation page is for RHEL 7, which is out of support. That link contained in the Installation page should be pointing to some other up-to-date repository, like RHEL 7.8 repository (I discussed with a Microsoft member and this repository exists, with version 1.3.7, 1.3.8 and 1.4.1 for RHEL 7.8)

**Comment by vibhansa-msft** [comment]
Wiki has been updated, kindly check.
