### ISSUE TITLE
Mount blobfuse on host volume via container

### ISSUE THREAD

**Issue by bo44arov** [Azure/azure-storage-fuse#655]
### Which version of the blobfuse was used?
1.4.1

### Which OS (please include version) are you using?
Ubuntu 20.04

### What problem was encountered?
I have setup blobfuse inside of docker container (let's say Container1), it works fine and I can see files from my Azure Blob Storage account in mounted directory inside of Container1.
But I need another Container2 to write data into this mounted folder of Container1. So I tried to create a shared volume - it does not work. It's always empty and files I create in Container2 are not reflected on Container1 blobfuse directory.

If I bind shared volume to any other directory of Container1 - it works as expected.

I've also tried to mount docker host's directory to the Container1 mounted blobfuse directory - does not work either.

### Have you found a mitigation/solution?
No

### If relevant, please share your mount command.
sudo blobfuse /root/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=/root/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o nonempty

**Comment by andrescodas** [comment]
> So if I understood your problem statement correctly, you want to write to container2 and expect the files to be synced in container1 automatically ? If so, this kind of setup is not supported. Blobfuse only responds to file-system calls such as open/read/write/close/flush. Also the shared volume kind of setup where you want to mount two containers to same volume is not supported. If you want data from container2 to be copied to container1 you need to mount them to two different folders and do a manual copy of files from one to another.

hi @vibhansa-msft, can you elaborate what do you mean with *do a manual copy of files from one to another*

In my scenario I have container1 with blobfuse2 mounting a given container.  Then, I want to read (read-only) few mounted files from container2.  How could I access these few files from the blob without having to copy them beforehand in the host system in a shared volume between container1 and container2?
