### ISSUE TITLE
File permission

### ISSUE THREAD

**Issue by francescocamussoni** [Azure/azure-storage-fuse#657]
### Which version of the blobfuse was used?
1.4.1

### Which OS (please include version) are you using?
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

### What problem was encountered?
I´ve mounted a Data Lage gen2 with blobfuse. The authType was SPN (service principal). I've specified some permissions on a file as readonly, but when I do a "vi file" I can modify it and save it. Then I go to Azure Storage Explorer and I see that the permissions have changed.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

### If relevant, please share your mount command.
blobfuse /home/fcamussoni/mountpoint_test --tmp-path=/mnt/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=/home/fcamussoni/connection.cfg --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=120

**Comment by vibhansa-msft** [comment]
Did this resolve the issue or you are still hitting it.

**Comment by vibhansa-msft** [comment]
Closing as there is no update on this. Feel free to reopen if issue persists.
