### ISSUE TITLE
Blobfuse Support Lifecycle

### ISSUE THREAD

**Issue by chekuchose** [Azure/azure-storage-fuse#659]
### Question
Is there the official support lifecycle document or policy for blobfuse? Some System Integrator companies plan their system update/upgrade based on Support Lifecycle. So, if there are some issue at the old version blobfue, it is difficult for System Integrators to upgrade/update it soon for a workaround of issues. Thefore, they need to know the support lifecycle in advance.

### Which version of the blobfuse was used?
```
[tkvmuser@tkvmredhat78 ~]$ blobfuse --version
blobfuse 1.0.2
```

### Which OS (please include version) are you using?
Red Hat Enterprise Linux Server 7.8 (Maipo)

### What problem was encountered?
When blobfuse tries to mount/unmount a blob container, it sometimes encounters the following segmentation fault:
```Aug 18 01:35:51 temasv01 kern.info: kernel: blobfuse[25729]: segfault at 29 ip 00007fd01fb747a3 sp 00007ffea42ae310 error 4 in libc-2.17.so[7fd01faf4000+1c4000]```

### Have you found a mitigation/solution?
Upgrading the blobfuse version from 1.0.2 to the latest version.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
```Aug 18 01:35:51 temasv01 kern.info: kernel: blobfuse[25729]: segfault at 29 ip 00007fd01fb747a3 sp 00007ffea42ae310 error 4 in libc-2.17.so[7fd01faf4000+1c4000]```

**Comment by vibhansa-msft** [comment]
@chekuchose : What kind of information you are looking for by support lifecycle. If its about bug fixes and new releases, then we do fix bugs and add new features as per customer demands. Latest binaries are posted on github as well as official linux repos are updated accordingly. As per the description you are using 1.0.2 which is pretty old version. Kindly upgrade to latest version 1.4.1, if you are still hitting the intermittent mount issues.

**Comment by chekuchose** [comment]
@vibhansa-msft 
Thank you for prompt reply!
I am looking for information about which blobfuse versions are supported and when they become sunset. For example, users sometimes an old version blobfuse and faces some issue. In this case, the user may ask the root cause analyis, normally a too old version blobfuse are not investigated by Developer. So, I want to get information which versions are supported.

Thanks!

**Comment by vibhansa-msft** [comment]
Any issue reported by customer we do investigate but first attempt is to reproduce that on our latest builds. If the issue is not consistent in nature or not reproducible on latest version then we suggest customers to upgrade. Sometimes fixing one bug resolves others too and hence this approach. For the information part, I agree, we do not any documentation on when a particular version is declared EOL. However for the latest version and supported platforms one can always refer to our release section in github. Also each new release is published on respective linux repos as well.

**Comment by chekuchose** [comment]
Thank you for telling me the support policy, which is duly noted. It is very clear.
