### ISSUE TITLE
Cannot remove folder in hierarchical namespace enabled containers

### ISSUE THREAD

**Issue by killa1218** [Azure/azure-storage-fuse#661]
### Which version of the blobfuse was used?
blobfuse 1.4.1

### Which OS (please include version) are you using?
Ubuntu 20.04.3 LTS

### What problem was encountered?
After I mounted my container, I created a folder in the mounted point, then I tried to remove the folder by running `rm -rf folder_name`. The command hangs. And during this time, any operation to this mount point won't respond. e.g. I call `ls` from another tty window.
After several minutes the rm command will finish running but the folder is not deleted.

### Have you found a mitigation/solution?
Nope

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Nov  3 13:53:50 blobfuse[3635900]: Using syscall to detect directory is already mounted or not
Nov  3 13:53:50 blobfuse[3635900]: Account name found
Nov  3 13:53:50 blobfuse[3635900]: Account Key found
Nov  3 13:53:50 blobfuse[3635900]: Container name found
Nov  3 13:53:50 blobfuse[3635900]: Setting logging level to : LOG_WARNING
Nov  3 13:53:50 blobfuse[3635900]: ** Delaying tls init to post fork for older libcurl version
Nov  3 13:53:50 blobfuse[3635900]: ** Delaying authentication to post fork for older curl versions
Nov  3 13:53:50 blobfuse[3635901]: ** Post fork authentication for older libcurl version
Nov  3 13:54:13 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:13 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 60f4bf79-f01e-0098-68ba-d09853000000
Nov  3 13:54:13 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:13 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 31df1e13-b01e-005c-1fba-d0b01f000000
Nov  3 13:54:13 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:13 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : ca5e857a-501e-0016-27ba-d06d1b000000
Nov  3 13:54:13 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:13 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : e9488a2e-701e-00e8-5dba-d06a53000000
Nov  3 13:54:13 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:13 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : a111882a-101e-007a-4eba-d0db20000000
Nov  3 13:54:14 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:13 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 5f86ffc5-501e-0052-40ba-d01202000000
Nov  3 13:54:15 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:14 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : f5d48abc-d01e-00f2-52ba-d0d464000000
Nov  3 13:54:16 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:15 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 36ad4506-801e-00ab-63ba-d0c444000000
Nov  3 13:54:18 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:16 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 7f30298e-a01e-0079-10ba-d0a626000000
Nov  3 13:54:21 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:18 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 97507835-601e-00f1-4eba-d0a962000000
Nov  3 13:54:25 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:20 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 155670c0-e01e-0051-7bba-d06f04000000
Nov  3 13:54:30 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:25 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : c1d8519f-101e-0046-55ba-d00e28000000
Nov  3 13:54:36 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:30 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : a254c7c3-f01e-00b4-1aba-d0fd79000000
Nov  3 13:54:43 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:36 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 7a2cbb13-c01e-0113-12ba-d0b5cd000000
Nov  3 13:54:52 blobfuse[3635901]:  ==> REQUEST/RESPONSE :: DELETE https://STORAGEACCOUNTNAME.blob.core.windows.net/common/emptydir?&x-ms-delete-snapshots=include&User-Agent=azure-storage-fuse/1.4.1&x-ms-date=Wed, 03 Nov 2021 13:54:43 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 500 :: REQ ID : 876914cd-001e-010f-4dba-d0f1f6000000

Telling from the log it seems like az storage rest api fails to respond.

### If relevant, please share your mount command.
`sudo blobfuse /blobcontainer --tmp-path=/mnt/cache --config-file=/home/USERNAME/yitian_test.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --max-concurrency=40 --file-cache-timeout-in-seconds=30 --upload-modified-only=true`

Also tried `sudo blobfuse /blobcontainer --tmp-path=/mnt/cache --config-file=/home/yitian/yitian_test.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other` and the same problem.

**Comment by killa1218** [comment]
One more information: I'm using "Zone-redundant storage (ZRS)" replication for my storage account.

**Comment by gapra-msft** [comment]
Hi @killa1218 

Does the account have hierarchical namespace enabled? If so, you need to specify --use-adls=true as a CLI param for blobfuse to support hierarchical namespace accounts.

**Comment by killa1218** [comment]
> Hi @killa1218
> 
> Does the account have hierarchical namespace enabled? If so, you need to specify --use-adls=true as a CLI param for blobfuse to support hierarchical namespace accounts.

Thanks! This is exactly the case for me. Solving my problem.

**Comment by vibhansa-msft** [comment]
Thanks for the update @killa1218. For HNS enabled account always use "--use-adls=true" while mounting.
