### ISSUE TITLE
Getting permission denied when listing the files in storage blob

### ISSUE THREAD

**Issue by emmanuelgeorge86** [Azure/azure-storage-fuse#662]
### Which version of the blobfuse was used?
blobfuse-1.3.6-1.el7.x86_64

### Which OS (please include version) are you using?
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"

### What problem was encountered?
When listing the blob mount getting permission denied

ls: reading directory .: Permission denied

### Have you found a mitigation/solution?
no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Getting below logs

list_blobs_hierarchical failed for the 7 time with errno = 403.
Nov  4 05:52:01  blobfuse[17048]: list_blobs_hierarchical failed for the 18 time with errno = 403.
Nov  4 05:52:01  blobfuse[17048]: list_blobs_hierarchical failed for the 4 time with errno = 403.
Nov  4 05:52:01 blobfuse[17048]: list_blobs_hierarchical failed for the 8 time with errno = 403.
Nov  4 05:52:01  blobfuse[17048]: list_blobs_hierarchical failed for the 19 time with errno = 403.
Nov  4 05:52:01 blobfuse[17048]: list_blobs_hierarchical failed for the 5 time with errno = 403.

### If relevant, please share your mount command.
blobfuse /mnsfod-foas-root fuse defaults,_netdev,--tmp-path=/blobvolume/mnsfod-foas-root,--config-file=/root/stgaccmount/fodeunprodfoasta0001.mnsfod-foas-root.cfg,nonempty,allow_other 0 0

**Comment by gapra-msft** [comment]
Hi @emmanuelgeorge86 

Could you please share what type of authentication you have provided? It looks like the requests to storage are failing with a 403 indicating improper permissions.

**Comment by gapra-msft** [comment]
Also if the account is an ADLS account, you will need to specify that by passing --use-adls=true

**Comment by emmanuelgeorge86** [comment]
We are using storage key for authentication and using storage accounts not ADLS account

**Comment by gapra-msft** [comment]
Could you please confirm the storage key is correct? The key may have been rotated. 

If that doesnt work, could you enable LOG_DEBUG in blobfuse and grab a request id from the syslog?

**Comment by emmanuelgeorge86** [comment]
Its not about the storage key. we had crosschecked and was having no issues. We had resolved the issue by rebooting the VM. This issue is now coming for the 2nd time and need to know if any issue on the blobfuse end

**Comment by gapra-msft** [comment]
If you can share the blobfuse syslog with LOG_DEBUG enabled, we can take a look

**Comment by vibhansa-msft** [comment]
Are you still hitting the issue ? if so, kindly share the logs.

**Comment by vibhansa-msft** [comment]
Closing this issue as there is no update. Feel free to reopen if issue persists and we have the required logs.
