### ISSUE TITLE
Blobfuse very slow and High CPU consumption when execution RMAN CROSSCHECK BACKUP

### ISSUE THREAD

**Issue by AL-EASYTEAM** [Azure/azure-storage-fuse#664]
### Which version of the blobfuse was used?
1.3.6

### Which OS (please include version) are you using?
Oracle Enterprise Linux 7.9

### What problem was encountered?
When executing a CROSSCHECK BACKUP command with RMAN, the operation is very slow and blobfuse consumes more than 1000% CPU (top) on the server.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No error is syslog

### If relevant, please share your mount command.
blobfuse /backup --tmp-path=/mnt/resource/blobfusetmp --config-file=/u01/app/blobfuse/fuse_connection.cfg -o allow_other -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

**Comment by vibhansa-msft** [comment]
Kindly enable debug logs and share blobfuse logs. Also you can try upgrading to 1.4.1 and add below options to your cli options : "--upload-modified-only=true --file-cache-timeout-in-seconds=0"

**Comment by AL-EASYTEAM** [comment]
Thanks. I updated blobfuse to version 1.4.1, enabled logs and use the mount command:

blobfuse /backup --tmp-path=/mnt/resource/blobfusetmp --config-file=/u01/app/blobfuse/fuse_connection.cfg -o allow_other -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --upload-modified-only=true --file-cache-timeout-in-seconds=0 --log-level=LOG_DEBUG

the server still consumes a lot of CPU and the CROSSCHECK remains very long.
[blobfuse.log](https://github.com/Azure/azure-storage-fuse/files/7498158/blobfuse.log)
.

**Comment by vibhansa-msft** [comment]
This log file is pretty small and does not give any clue on high cpu usage.  Were the logs trimmed manually ?, because though LOG_DEBUG is enable its not dumping all debug level logs.

**Comment by AL-EASYTEAM** [comment]
Hello,
it is strange indeed. The log (/ var/ log/messages) was not truncated on my side.
Thanks

**Comment by vibhansa-msft** [comment]
Then there is something wrong with the logs, they are not complete and do not give any info on what was happening in the system. Kindly collect new logs and share.

**Comment by AL-EASYTEAM** [comment]
Hello, we did a new test of CROSSCHECK BACKUP with the LOG_DEBUG option.
Thank y
[blob_storage_azure_DEBUG.log](https://github.com/Azure/azure-storage-fuse/files/7560056/blob_storage_azure_DEBUG.log)
ou

**Comment by vibhansa-msft** [comment]
Blobfuse is overwhelmed with getattr and statfs calls for the root directory (mount path). I can see tons of requests coming for that. Below are the logs you can see repeating almost every second.
----------------------------------
Nov 18 05:48:05 oralinux01 blobfuse[599]: Function azs_getattr, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 120: azs_getattr called with path = /
Nov 18 05:48:06 oralinux01 blobfuse[599]: Function azs_statfs, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/directoryapis.cpp, line 274: azs_statfs called with path = /.
----------------------------------
There might be something wrong with the system resulting into this or CROSSCHECK is firing too many requests. I can see you have attribute-timeout and entry-timeout set in your mount command which means kernel shall have cached the attributes of "/" and should not have sent so many requests.

**Comment by vibhansa-msft** [comment]
Closing as no updates from submitter. Feel free to reopen if the issue persists.
