### ISSUE TITLE
Unable to write files in mounted directory even with read/write permissions and ownership

### ISSUE THREAD

**Issue by simonlee184** [Azure/azure-storage-fuse#667]
Blobfuse version: blobfuse version 1.3.8
OS: Ubuntu
Issue: I can enter into my mounted directory and see all the files using the ls command. However I cannot edit any of the files, touch files, even just a less command doesn't work. I have Ownership of the storage account, and have read/write/execute permissions on the files and directories.

I'm not entirely sure why this issue is happening unfortunately. Any help would be greatly appreciated.

**Comment by simonlee184** [comment]
Nevermind, I only realize I can't interact with resources outside the VM including the containers that i'm mounted to because I am using a sandbox environment.

**Comment by vibhansa-msft** [comment]
So you are facing any issue or its just because of the sandbox. Kindly close the issue if things are working as expected.
