### ISSUE TITLE
O_DIRECT not working?

### ISSUE THREAD

**Issue by tmagana** [Azure/azure-storage-fuse#673]
### If relevant, please share your mount command.

blobfuse /xxx/Blob_BAK --tmp-path=/mnt/resource/blobfusetmp
--config-file=/etc/blobfuse.cfg -o attr_timeout=240 -o entry_timeout=240 -o
negative_timeout=120 -o allow_other --file-cache-timeout-in-seconds=60
--upload-modified-only=true --max-concurrency=24 -o async -o direct_io

This is the same issue was reported in :

https://github.com/Azure/azure-storage-fuse/issues/118

but seems still not working.   What are we missing?

**Comment by tmagana** [comment]
Hmm.  Just noticed earlier issue filed month back probably from my customer too:

Blobfuse does not support Async IO, RMAN from oracle 19c cannot write file to blobfuse #665 

If I understand correctly from updates there now you saying O_DIRECT not supported.  Not sure why it was stated differently in issue 118.   Anyways thanks for clarifying.      As 1.4.2 masks out those options I guess that would fix the issue we are seeing (indirectly).

**Comment by vibhansa-msft** [comment]
O_DIRECT flag was never supported by blobfuse but earlier it was not being suppressed resulting into failures in read/write operation. In our latest release we are started suppressing the flag so even if application passes it down to blobfuse, it will not be honored and read/write operation will not fail. Kindly upgrade to 1.4.2 and try out your test case.
