### ISSUE TITLE
CONTENT-TYPE is not applied on big files >= 100Mb

### ISSUE THREAD

**Issue by bo44arov** [Azure/azure-storage-fuse#674]
### Which version of the blobfuse was used?
1.4.2

### Which OS (please include version) are you using?
ubuntu 18.04

### What problem was encountered?
When using option --set-content-type=true the content type is not applied for large files and still is "application/octet-stream".

I tried it on .mp4 files 10-50 Mb - it works properly and in blobstorage I see file content-type as video/mp4.
But if I use file 100 Mb and more - content-type is application/octet-stream

![image](https://user-images.githubusercontent.com/54901472/145236631-d0c83571-a688-447f-9c30-01fc097af82b.png)

and

![image](https://user-images.githubusercontent.com/54901472/145236761-c684e33c-1297-4394-b7d0-03bc64955d19.png)

### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
In cpplite sdk that we are using I see for files > 64MB in size content-type is not set in the put-block-list rest api call.

**Comment by vibhansa-msft** [comment]
This issue is fixed in 1.4.3, kindly upgrade
https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.4.3

**Comment by bo44arov** [comment]
> This issue is fixed in 1.4.3, kindly upgrade https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.4.3

Great, thank you!
