### ISSUE TITLE
df command does not show correct space on mounted blob filesystems.

### ISSUE THREAD

**Issue by a087110** [Azure/azure-storage-fuse#685]
### Which version of the blobfuse was used?
1.4.3-1xx86_64

### Which OS (please include version) are you using?
SuSE 15.2

### What problem was encountered?
df command does not show correct space on mounted blob filesystems.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

**Comment by vibhansa-msft** [comment]
'df' command does not show usage of your storage account, instead in case of blobfuse it will just show you usage of your temp-cache path with respect to its mount point as that is the space used by blobfuse on physical disk. So if your temp directory is /mnt/blobfusetemp then it will show % usage of /mnt or whatever is the actual mount point for your temp directory.

**Comment by vibhansa-msft** [comment]
Closing this as I do not see any bug here. 'df' is working as expected from blobfuse end. If you have any further queries you can post them here.
