### ISSUE TITLE
Files not synced properly between cache and target mount

### ISSUE THREAD

**Issue by jrauschenbusch** [Azure/azure-storage-fuse#686]
### Which version of the blobfuse was used?

1.4.3

### Which OS (please include version) are you using?

Ubuntu-18.04

### What problem was encountered?

Files are not synced properly between tmp path (cache) and target mount.

New files are synced properly, but already existing files where only the content is updated with no change in file size (e.g. replacement of SHA value) aren't updated in the target mount (only modified timestamp is updated, but content remains the old one). When opening a file handle on the target mount then a new cache version is created within the tmp path which contains the correct content, but the mounted version still contains the old content.

### Have you found a mitigation/solution?

Deletion of file in mounted directory leads to immediate recreation from correctly updated cached version
`rm /home/admin/mycontainer/<file>`

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

no

### If relevant, please share your mount command.

fstab entry
```
blobfuse /home/admin/mycontainer  fuse defaults,_netdev,--tmp-path=/mnt/resource/blobfusetmp,--config-file=/home/admin/fuse_connection.cfg,--log-level=LOG_DEBUG,allow_other,ro 0 0
```

**Comment by vibhansa-msft** [comment]
Can you share little more details on what is your observation.
"When opening a file handle on the target mount then a new cache version is created within the tmp path which contains the correct content, but the mounted version still contains the old content" : from this what I understand is 'tmp-path' is having correct data but when you open the file you still see older contents ?

Files are synced from tmp-path to cotainer only on close so unless you close/flush the file after writing it will not be uploaded to container. If you are updating the file in parallel from some other source (other then your blobfuse mount) then sync is not guaranteed.

**Comment by jrauschenbusch** [comment]
@vibhansa-msft 

> from this what I understand is 'tmp-path' is having correct data but when you open the file you still see older contents

Correct. The file content within the tmp-path (`/mnt/resource/blobfusetmp/<file>`) is up-to-date, but opening the file via the mount directory (/home/admin/mycontainer/<file>) it still has its old content.

> Files are synced from tmp-path to cotainer only on close so unless you close/flush the file after writing it will not be uploaded to container. If you are updating the file in parallel from some other source (other then your blobfuse mount) then sync is not guaranteed.

That is not the case. The blobs are uploaded/updated via an `az storage blob upload` from another host. The blobfuse mount will be a read-only mount in the next step, as files should not be modified. In a second step the files are `rsync`ed to their target location.

I now also found the reason for the behavior. It's related to small files and kernel caching, which is really annoying. Since I'm trying to load configuration files (which are mostly small files) the kernel seems to cache these files, their content is never updated as blobfuse seems not to get informed of the open filehandle. Executing `sudo sysctl -w vm.drop_caches=3` resolved the issue.

**Comment by vibhansa-msft** [comment]
Was about to suggest that only to clear the kernel page cache. There is no option in blobfuse to do that. You need to do it explicitly only. As files are getting synced from another location you shall keep your file-cache-timeout=0 so that blobfuse does not cache a file for long.

**Comment by jrauschenbusch** [comment]
@vibhansa-msft 
 
Doing both `file-cache-timeout=0` (blobfuse configuration) and `sudo sysctl -w vm.drop_caches=3` via crontab triggered each minute my rsync operation now works as expected.

Thanks for you support.
