### ISSUE TITLE
Does not work from within /etc/fstab

### ISSUE THREAD

**Issue by rkblackwell** [Azure/azure-storage-fuse#687]
### Which version of the blobfuse was used?
1.4.1

### Which OS (please include version) are you using?
Red Hat Enterprise Linux release 8.1 (Ootpa)

### What problem was encountered?
blobfuse used in /etc/fstab does not work.

LINE ADDED TO /etc/fstab

/usr/bin/blobfuse /mnt/ACO_Inbound fuse delay_connect,defaults,_netdev,--tmp-path=/mnt/resource/blobfusetemp,--configfile=/etc/blobfuse/ACO_Inbound_fuse_connect.cfg,--log-level=LOG_DEBUG,allow_root 0 0

same results with allow_other

ERROR=>>>>>>>>>>>>>>>>
Error: No config file provided and --container-name is not set.
no config fileUsage: blobfuse <mount-folder> --tmp-path=</path/to/fusecache> [--config-file=</path/to/config.cfg> | --container-name=<containername>]    [--use-https=true] [--file-cache-timeout-in-seconds=120] [--log-level=LOG_OFF|LOG_CRIT|LOG_ERR|LOG_WARNING|LOG_INFO|LOG_DEBUG] [--use-attr-cache=true]

In addition to setting --tmp-path parameter, you must also do one of the following:
1. Specify a config file (using --config-file]=) with account name (accountName), container name (containerName), and
        a. account key (accountKey),
        b. account SAS token (sasToken),
        c. valid service principal credentials (servicePrincipalClientId, servicePrincipalTenantId, and environment variable AZURE_STORAGE_SPN_CLIENT_SECRET) with access to the storage account or,
        d. valid MSI credentials (one or none of identityClientId, identityObjectId, identityResourceId) with access to the storage account. Custom endpoints w/ secrets can be used via msiEndpoint and MSI_SECRET
2. Set the environment variables AZURE_STORAGE_ACCOUNT and (AZURE_STORAGE_ACCESS_KEY or AZURE_STORAGE_SAS_TOKEN), and specify the container name with --container-name=

See https://github.com/Azure/azure-storage-fuse for detailed installation and advanced configuration instructions, including SPN and MSI via environment variables.
<<<<<<<<<<<<<<<<<<<<<<

Following instructions found here: https://github.com/Azure/azure-storage-fuse/wiki/2.-Configuring-and-Running#persisting
>>>>>
Add the following line to run without mount.sh

blobfuse /home/azureuser/mntblobfuse fuse delay_connect,defaults,_netdev,--tmp-path=/home/azureuser/tmppath,--config-file=/home/azureuser/connection.cfg,--log-level=LOG_DEBUG,allow_other 0 0

<<<<<

This works fine when executed manually, but using mount-a after adding to /etc/fstab, it is failing.

### Have you found a mitigation/solution?

besides manually running, no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

no

**Comment by vibhansa-msft** [comment]
Easier way would be to run a shell script from /etc/fstab and let that shell script has the complete mount command. This makes it easier to change the CLI parameters also in future.
Also sometimes the mount happens from /etc/fstab before the network has come up and in that case the mount will fail as it will not be able to connect to stroage. You shall add delay_connect in /etc/fstab to get over that situation

Sample /etc/fstab command for blobfuse
/home/myuser/mnt.sh /home/myuser/blobfusemount fuse _netdev,allow_other,delay_connect 0 0
mnt.sh is the one having the actual mount command.

**Comment by rkblackwell** [comment]
Hi, thanks for the reply
I do have delay connect:

/usr/bin/blobfuse /mnt/ACO_Inbound fuse **delay_connect**,defaults,_netdev,--tmp-path=/mnt/resource/blobfusetemp,--configfile=/etc/blobfuse/ACO_Inbound_fuse_connect.cfg,--log-level=LOG_DEBUG,allow_root 0 0

**Comment by vibhansa-msft** [comment]
As you have log_debug enable, kindly share the logs.

**Comment by rkblackwell** [comment]
Hi - thanks for your time - I discovered that this was a result of missing the dash in the --config-file option.  I had --configfile
