### ISSUE TITLE
High Number of ListBlob Transactions every 24 hours

### ISSUE THREAD

**Issue by llk7rt** [Azure/azure-storage-fuse#710]
### Which version of the blobfuse was used?
1.3.8

### Which OS (please include version) are you using?
I am using blobfuse indirectly by using mount option of Azure App Service 

### What problem was encountered?

Currently I use the “mount” feature of the webapp service which hides the blobfuse configuration to me.
I am not sure how and on which layer blobfuse is setup in that process.

In my storage from blob statistics I have roughly 270k blobs:
raw: Finished calculating statistics for 'xdrmeasurements/raw/'. Active blob stats: 1.291 blobs, 30.774.395.301 bytes. Completed 1.2.2022, 18:41:16.
curated: Finished calculating statistics for 'xdrmeasurements/curated/'. Active blob stats: 222.932 blobs, 806.663.463.286 bytes. Completed 1.2.2022, 18:44:28.
cleaned: Finished calculating statistics for 'xdrmeasurements/cleansed/'. Active blob stats: 47.228 blobs, 417.718.067.189 bytes. Completed 1.2.2022, 18:45:33.
                                                                                                                                                                                 
With 5k list blobs per transaction one full scan should result into something like 
ceil((222932 + 47228 + 1291 ) / 5000) = 55 transactions per full scan.

However, I do have many subfolders and from Microsoft Storage support I already learned that we have to expect individual many more list blob activities for directory in nested path, so if listing is done for 'ls A/B' then list call will be repeated for both 'A' & 'A/B'.
This is limiting the option of using the mount feature as due to the high number of transactions I face now storage gets quite expensive.

However, one issue that neither I, nor the Storage/WebApp support understand is why I see transactions raising dailybetween 6AM and 8AM and not equally distributed over time. In my case that means that I get 300k transaction peaks in that time frame and <<100 during the rest of the day.

### Have you found a mitigation/solution?
No. Currently it looks like the solution is to not use blobfuse and connect to data either using other means.

**Comment by llk7rt** [comment]
Hi @vibhansa-msft 

thanks for your answers - they may help once I may use blobfuse manually. 
As none of those settings are under my control when I use the Azure Webapp mount feature, I kindly forwarded your comments to the Azure Storage and Webapp teams and kindly asked them to get in contact with github team directly.

Thanks
Oliver

**Comment by vibhansa-msft** [comment]
As there is no update on this closing this issue. If Webapp needs any help in choosing the correct mount options, we can start a new thread.
