### ISSUE TITLE
Misleading message when blob storage is unreachable

### ISSUE THREAD

**Issue by jbauerrfid** [Azure/azure-storage-fuse#713]
### Which version of the blobfuse was used?
Latest blobfuse for RHEL8 from yum package manager

### Which OS (please include version) are you using?
RHEL8.2

### What problem was encountered?
Error Message "Unable to start blobfuse due to a lack of credentials" encountered, when in fact the blob storage was unreachable.

Expectation is that there is a different error message for authentication failures (bad credentials), and network related issues (in this case it was a missing virtual network setup, because my blob storage uses a private endpoint).

When there is a condition like host unreachable or connection refused, this should be clearly noted in the error message.

### Have you found a mitigation/solution?
None, just fix the network connection and firewall. But getting the right error message would have saved a lot of time. My blobfuse worked after fixing the network issue.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
N/A

### If relevant, please share your mount command.
```
sudo blobfuse /var/lib/pgsql/postgres-backup --tmp-path=/mnt/blobfusetmp --config-file=/var/lib/pgsql/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other
```

**Comment by vibhansa-msft** [comment]
I agree to the part that "lack of credential" is not the correct error message here. However from blobfuse end when the connection fails, its not aware of the reason. As a generic message we just ask user to check the configuration and retry, Will discuss internally on how to improve our error logging here.

**Comment by vibhansa-msft** [comment]
Wil close the issue here and add an item to our backlog.
