### ISSUE TITLE
GTK FileChooserDialog browing folder triggers download of all files in the folder to the local cache

### ISSUE THREAD

**Issue by cwang2002** [Azure/azure-storage-fuse#715]
### Which version of the blobfuse was used?
1.4.1

### Which OS (please include version) are you using?
RHEL 7.9

### What problem was encountered?
A GUI program using GTK+ FileChooserDialog browses the mounted folder, triggered all files under the folder downloaded to the local SSD cache, make UI unresponsive

### Have you found a mitigation/solution?
No

**Comment by cwang2002** [comment]
Also tried version 1.4.3 on RHEL 8, same problem.

**Comment by vibhansa-msft** [comment]
Blobfuse does not download any file on its own. If user application issues a open command for any file it will be downloaded to local cache. Kindly check your application flow, it might be issuing open call for all those files during browsing. Not an issue from blobfuse end.

**Comment by cwang2002** [comment]
Thanks for the response. The issue is very likely GTK+ side, application doesn't do anything other than start a file chooser dialog.

**Comment by vibhansa-msft** [comment]
From blobfuse end whoever is accessing the mount path is user application for us :)

**Comment by cwang2002** [comment]
@vibhansa-msft I used strace for a simple python program using pygtk to open the file chooser dialog and navigate to the blobfuse mounted location. I don't see any file open system call, however, the dialog took a long to show the list of files. I am expecting to have the same response time using "ls -l". Do you have any idea what could be the cause? Any help is appreciated. thanks

**Comment by vibhansa-msft** [comment]
While mounting blobfuse you can enable log_debug. blobfuse logs will show that file open was indeed called. As I told in last comment, blobfuse does not download any file on its own, it acts only on kernel calls.

**Comment by cwang2002** [comment]
thanks for the suggestion. Some interesting findings after further debugging, only files with certain extensions (.iso and .dta so far)are downloaded to the local cache.

**Comment by cwang2002** [comment]
gnome-text-editor and nautilus have the same issue

**Comment by vibhansa-msft** [comment]
@cwang2002 : As you are observing only few files are getting cached and behavior is also dependent on the tool being used. So from blobfuse end it depends on what command application issues us. If they are trying to open those files then blobfuse will end up downloading them.

**Comment by vibhansa-msft** [comment]
Blobfuse does not download any file untill open() for that file is called. As far as statfs and getattr are concerned : statfs just check the stats from local system for the temp path user has configured. And getattr checks the local file stats and if not present gets the stats from your container. In either case they do not trigger any sort of download or caching. As you are looking at the code, you can see there is no open or download related api call in either of these methods. Only when azs_open is triggered, it ends up downloading the file from container into local cache.
