### ISSUE TITLE
Support Azure default environment variable credentials

### ISSUE THREAD

**Issue by saswatac** [Azure/azure-storage-fuse#716]
### Which version of the blobfuse was used?

blobfuse 1.4.1

### Which OS (please include version) are you using?

```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### What problem was encountered?

Blobfuse does not support the same default environment variables https://docs.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#environment-variables . For example, the service principal client id must be set with `AZURE_STORAGE_SPN_CLIENT_ID` instead of `AZURE_CLIENT_ID`.

It will be nice if blobfuse can support the default env var names.

**Comment by vibhansa-msft** [comment]
I understand your point of having uniformity across tools, but as of now these names differ from tool to tool and SDK to SDK.

**Comment by vibhansa-msft** [comment]
Will add an item to our backlog regarding the same. Closing this issue here.
