### ISSUE TITLE
runuser cannot mount it for the specified user

### ISSUE THREAD

**Issue by SimonLiuhd** [Azure/azure-storage-fuse#723]
### Which version of the blobfuse was used?
blobfuse 1.3.6

### Which OS (please include version) are you using?
azure centos 7.9

### What problem was encountered?
under root, after run the command **runuser -l <not_root_user_name> -c "blobfuse ....."**, the mount point group and owner still root-root, not <not_root_user_name>'s group and <not_root_user_name>

**Comment by vibhansa-msft** [comment]
I tried this locally and all looks good to me. Let me know what part you feel is inconsistent. 

Here is a snippet from my trial:

"
sudo runuser -l nonsudo -c 'blobfuse ~/blob_mnt --tmp-path=~/blobfusetemp --config-file=/home/faltoo/myblob.cfg'
su - nonsudo
whoami
   nonsudo
df
  blobfuse       130552900 38207384  85670780  31% /home/nonsudo/blob_mnt  
stat ~/blob_mnt
    File: /home/nonsudo/blob_mnt
   Size: 4096            Blocks: 0          IO Block: 4096   directory
   Device: 34h/52d Inode: 1           Links: 2
  Access: (0770/drwxrwx---)  **Uid: ( 1001/ nonsudo)   Gid: ( 1001/ nonsudo)**

ls -l ~/blob_mnt
  total 0
  -rwxrwx--- 1 **nonsudo nonsudo**       9 Nov  2 20:05 abc.txt
"

**Comment by vibhansa-msft** [comment]
Kindly reply on this thread. I have shared my observations above, if there is something I have missed let me know.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Feel free to create a new issue if you face any further issue with blobfuse.
