### ISSUE TITLE
Not able to mount blobfuse as a filesystem

### ISSUE THREAD

**Issue by sreeharisreenath** [Azure/azure-storage-fuse#724]

**Comment by PlatformExtraslice** [comment]
> 
![164677011211951114569559318998](https://user-images.githubusercontent.com/100336633/157316727-6ecd18c4-6e23-4a66-805e-22d44777388e.jpg)

I'm getting this error message with " glibc_2.29 not found "

**Comment by PlatformExtraslice** [comment]
The OS is Ubuntu 18.04

**Comment by sreeharisreenath** [comment]
![e9e1451f-6597-471c-889e-724650c93142](https://user-images.githubusercontent.com/44381353/157317398-bc17c004-5a86-40cc-9782-f5e2ba1d5a8d.jpg)

**Comment by gapra-msft** [comment]
It looks like there is a dependency issue with glibc. Could you try uninstalling then reinstalling blobfuse?

**Comment by vibhansa-msft** [comment]
Is this dependency issue resolved? We will close this issue in case of no update.

**Comment by sreeharisreenath** [comment]
I'm really sorry . I don't get the notifications.
I have reinstalled the blobfuse but dint solve the issue.

**Comment by vibhansa-msft** [comment]
There is some lib missing in the system. Try using following command and it shall work fine:

sudo apt-get update --fix-missing
sudo apt-get install pkg-config cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev libboost-all-dev gcc g++ -y
