### ISSUE TITLE
Release Date for Blobfuse2

### ISSUE THREAD

**Issue by sim-san** [Azure/azure-storage-fuse#728]
### Which version of the blobfuse was used?
/

### Which OS (please include version) are you using?
/

### What problem was encountered?
Is there a Roadmap/Release Date for the new Blobfuse2 ?

### Have you found a mitigation/solution?
/

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
/

### If relevant, please share your mount command.
/

**Comment by vibhansa-msft** [comment]
Blobfuse2 GA is planned for Aug-Sept timeframe. Meanwhile if you are interested you can give our preview version a try.
https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview.1
