### ISSUE TITLE
[blobfuse2] cannot install deb file inside a container image

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#733]
### Which version of the blobfuse was used?
blobfuse v2 preview

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?

 - Dockerfile is like following, it works for blobfuse v1(`packages-microsoft-prod.deb`)
```
FROM k8s.gcr.io/build-image/debian-base:bullseye-v1.1.0

ARG ARCH=amd64
COPY ./_output/${ARCH}/blobplugin /blobplugin

RUN apt update && apt-mark unhold libcap2
RUN clean-install ca-certificates uuid-dev util-linux mount udev wget e2fsprogs nfs-common netbase
# install updated packages to fix CVE issues
RUN clean-install libgmp10 bsdutils
RUN mkdir /blobfuse-proxy/
COPY ./_output/blobfuse-proxy.deb /blobfuse-proxy/
ARG ARCH=amd64
RUN if [ "$ARCH" = "amd64" ] ; then \
  clean-install libcurl4-gnutls-dev && \
  wget -O /blobfuse-proxy/packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb && \
  wget -O /blobfuse-proxy/blobfuse2.deb https://github.com/Azure/azure-storage-fuse/releases/download/blobfuse2-2.0.0-preview.1/blobfuse2-2.0.0-preview.1-ubuntu-18.04-x86-64.deb && \
  dpkg -i /blobfuse-proxy/packages-microsoft-prod.deb /blobfuse-proxy/blobfuse2.deb && apt update && apt install blobfuse fuse -y && apt remove wget -y; fi
LABEL maintainers="andyzhangx"
LABEL description="Azure Blob Storage CSI driver"

ENTRYPOINT ["/blobplugin"]
```

 - when building image with the above Dockerfile, it failed with following error:
```
#12 4.802 Selecting previously unselected package blobfuse2.
#12 4.809 (Reading database ... 7134 files and directories currently installed.)
#12 4.809 Preparing to unpack /blobfuse-proxy/blobfuse2.deb ...
#12 4.817 /var/lib/dpkg/tmp.ci/preinst: 1: sudo: not found
#12 4.817 /var/lib/dpkg/tmp.ci/preinst: 2: sudo: not found
#12 4.817 dpkg: error processing archive /blobfuse-proxy/blobfuse2.deb (--install):
#12 4.817  new blobfuse2 package pre-installation script subprocess returned error exit status 127
#12 4.848 Errors were encountered while processing:
#12 4.848  /blobfuse-proxy/blobfuse2.deb
```

### Have you found a mitigation/solution?
 - remove all `sudo` in `preinst` and `postinst` files:
```
# cat preinst
sudo rm -rf /usr/share/blobfuse2/
sudo mkdir /usr/share/blobfuse2
```

**Comment by gapra-msft** [comment]
@andyzhangx thanks for reporting this issue. We will look into this issue and get back to you in case we need some more info

**Comment by andyzhangx** [comment]
@gapra-msft just use this Dockefile:
```
FROM k8s.gcr.io/build-image/debian-base:bullseye-v1.1.0

RUN apt update && apt-mark unhold libcap2
RUN clean-install ca-certificates uuid-dev util-linux mount udev wget e2fsprogs nfs-common netbase

ARG ARCH=amd64
RUN if [ "$ARCH" = "amd64" ] ; then \
  clean-install libcurl4-gnutls-dev && \
  https://github.com/Azure/azure-storage-fuse/releases/download/blobfuse2-2.0.0-preview.1/blobfuse2-2.0.0-preview.1-ubuntu-18.04-x86-64.deb && \
  dpkg -i /blobfuse-proxy/packages-microsoft-prod.deb /blobfuse-proxy/blobfuse2.deb && apt update && apt install blobfuse fuse -y && apt remove wget -y; fi
```

btw, where is the `preinst` file in this repo? once you fixed this issue, I think you could use this Dockerfile in build test, thanks.

**Comment by gapra-msft** [comment]
Here is the preinstall file in the repo
https://github.com/Azure/azure-storage-fuse/blob/main/tools/preinstall.sh

**Comment by andyzhangx** [comment]
thanks, could you remove `sudo` in `preinstall.sh` and `postinstall.sh`?

**Comment by gapra-msft** [comment]
It may not be as simple as removing sudo since we will not be able to copy to or create certain files without sudo access. We may have to just remove the post and pre install scripts

**Comment by andyzhangx** [comment]
I have updated the Dockerfile in https://github.com/Azure/azure-storage-fuse/issues/733#issuecomment-1068669562, I think you could add this test in your CI? Thanks.

**Comment by gapra-msft** [comment]
@andyzhangx I have merged the above PR which should resolve the issue. It also includes a small test to ensure it works in our nightly pipeline. Are there any other e2e tests you would like us to test with it? I can share the latest binary to double check it still works on your end. It is slightly different from the last one I shared but it should still work as the unit test passes

**Comment by andyzhangx** [comment]
> @andyzhangx I have merged the above PR which should resolve the issue. It also includes a small test to ensure it works in our nightly pipeline. Are there any other e2e tests you would like us to test with it? I can share the latest binary to double check it still works on your end. It is slightly different from the last one I shared but it should still work as the unit test passes

@gapra-msft thanks, just share me the deb file, and then I could conduct the blob csi driver e2e test.

**Comment by gapra-msft** [comment]
@andyzhangx Sent the binary via Teams chat. Please conduct the e2e test and let us know how that goes

**Comment by andyzhangx** [comment]
> @andyzhangx Sent the binary via Teams chat. Please conduct the e2e test and let us know how that goes

@gapra-msft thanks, the new deb file works well in blob csi driver e2e test.

**Comment by gapra-msft** [comment]
Awesome! I will go ahead and close this issue then
