### ISSUE TITLE
[blobfuse2] provide a containerized solution

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#734]
### Which version of the blobfuse was used?
blobfuse v2 preview

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
when I try to blobfuse2 mount, it would fail with following error:
```
# blobfuse2 mount blob --container-name=public --tmp-path=/tmp/blobfuse/ --config-file=/usr/share/blobfuse2/config.yaml
Mount: error initializing logger [failed to create syslog object]
```

it depends on syslog, it works well for blobfuse v1 (does not depend on `rsyslog` service)
need to create a containerized solution for blobfuse2?

**Comment by vibhansa-msft** [comment]
Do you have rsyslog running in your container ? Was v1 logging working earlier.

**Comment by vibhansa-msft** [comment]
v1 also uses syslog only, so if rsyslog is not working v1 logs might also be getting ignored. Can you verify /var/log/syslog has any blobfuse (v1) logs when it runs?

**Comment by vibhansa-msft** [comment]
Also in v2 we have a file based logging option, however default is syslog so to use file based logging you need to set the config accordingly.

**Comment by andyzhangx** [comment]
use `type: base` works, it does not depend on syslog service, thanks.

**Comment by vibhansa-msft** [comment]
How was v1 working without syslog? Were we missing logs for v1 all this time?

**Comment by vibhansa-msft** [comment]
We have fixed this part and if syslog does not exist on system, blobfuse2 will fall back to file-based logging.
