### ISSUE TITLE
How can blobfuse disk is mounted before any applications eg. ngix. Persisting doc problem.

### ISSUE THREAD

**Issue by v-yaneli** [Azure/azure-storage-fuse#736]
1. My question is that how blobfuse disk can be mounted before any applications eg. ngix. These applications need to read/write the the mounted disk.

I found persisting section in wiki. Can it work? or any other function fuse can support for this purpose?

2. As to the Note of persisting section wiki: https://github.com/Azure/azure-storage-fuse/wiki/2.-Configuring-and-Running#persisting

(Note: you can omit the delay_connect option after fuse if you do not want to wait for any dependent services, I left it there to prevent race conditions where sometimes **_fuse services_** take a while to load and fstab executes before that)

Looks like **_fuse services_** in the Note does not make sense. As I understand, fstab calls fuse. Should it be _**fuse dependent services such as network**_?

**Comment by vibhansa-msft** [comment]
To answer (1) if you need very fine control over the order and timming, it will be better to run a script from fstab and in the script you manage the order of mounting or control the timmings.

for (2) delay_connect was suggested to solve a particular problem where blobfuse was mounted before the network devices came up, if it goes in that order connection to storage will not go through and blobfuse mount will fail.

**Comment by v-yaneli** [comment]
@vibhansa-msft thanks for your prompt answer!

for answer (1), do you mean: 
step 1) Create a script, call blobfuse firstly and then dependency service eg. ngix in the same script
step 2) Run the script from fstab

**Comment by v-yaneli** [comment]
for (2), would you revise the Note, 
from 
where sometimes **_fuse services_** take a while to load and fstab executes before that
to
where sometimes **_network devices_** take a while to load and fstab executes before that

**Comment by vibhansa-msft** [comment]
"step 2) Run the script from fstab" : Correct. Create a script that mounts and sets up the things in the order you intend and then just run the script from fstab so that you have finer control on the order and timing both.

" sometimes network devices take " : we will consider rephrasing it to make it more clear.

**Comment by vibhansa-msft** [comment]
Let me know if you have any further queries/concerns.

**Comment by v-yaneli** [comment]
cx uses blobfuse version 1.3.6 and got error message: unknown option delay_connect.
is this a version problem?
thanks.

**Comment by vibhansa-msft** [comment]
delay_connect is not a blobfuse option, its rather standard linux fstab option. Can you share how you are using this ?
Its not blobfuse mount option, you need to put this in /etc/fstab changes.

**Comment by vibhansa-msft** [comment]
Kindly update you are still hitting the issue or not. We will close this ticket in case of no updates.

**Comment by v-yaneli** [comment]
Thanks for your prompt and valuable asssistance :)
