### ISSUE TITLE
Plans for Ubuntu 22.04 and Mariner support? 

### ISSUE THREAD

**Issue by jaypatel-37** [Azure/azure-storage-fuse#738]
Hi, are there plans to expand blobfuse support to Ubuntu 22.04 and/or Mariner? If so, are there approximate timelines?

**Comment by gapra-msft** [comment]
Hi @jaypatel-37 

Thank you for your request. We do have plans to support Mariner in upcoming previews. We can also consider Ubuntu 22.04 as a feature request.

**Comment by gapra-msft** [comment]
@jaypatel-37 are you looking for support on those OSes in blobfuse? If so, I misspoke and we do not have plans to release Mariner and Ubuntu 22.04 support. 

We just released preview 1 of blobfuse2, and will plan to release support for those OSes in future previews.
