### ISSUE TITLE
E: Unable to locate package blobfuse in Ubuntu 21.10

### ISSUE THREAD

**Issue by joolz** [Azure/azure-storage-fuse#742]
### Which version of the blobfuse was used?
None

### Which OS (please include version) are you using?
Ubuntu 21.10

### What problem was encountered?
I followed these steps: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux but blobfuse seems not to exist.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

### If relevant, please share your mount command.
None

**Comment by vibhansa-msft** [comment]
We do not release for ubuntu-21 as of now (only ubn-18 and 20 are officially released).
Either you can clone the repo and build it for ubn-21 or use ubn-20 binaries and use them (should work fine on ubn-21)
