### ISSUE TITLE
modified data on azure storage account did not sync on the mount path on azure HDInsight

### ISSUE THREAD

**Issue by Baiys1234** [Azure/azure-storage-fuse#743]
### Which version of the blobfuse was used?
1.4.3

### Which OS (please include version) are you using?
18.04.1

### What problem was encountered?
modified data on azure storage account did not sync on the mount path on HDInsight.
I am 100% reproduce in lab.

What ever I changed on storage, but always confirm the old contents for even 24 hours.
even set  file-cache-timeout=0 on mount, it does not work.

Customer needs to upload data from on-premise to the cloud, which is why they use blobfuse to synchronize
they don't allow user to direct access storage on HDI.

Customer wants to know
1) Is it the bug/limitation of tool ?
2) What can blobfuse side do to avoid this issue?
3) Need a best practice to solve the issue.

### Have you found a mitigation/solution?
seems like a similar issue below
https://github.com/Azure/azure-storage-fuse/issues/686

But customer cannot accept clear the kernel page cache. Because it's a hadoop hdinsight cluster, so many i/o.
this will have a big impact on their os performance.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

No syslog

### If relevant, please share your mount command.
sudo blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp  --config-file=/path/to/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

#Ref
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux

Thanks

**Comment by vibhansa-msft** [comment]
You mean you are observing old meta (like LMT, file-size etc) or old data. 
- If it's about old meta info "-o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120" this in your mount command means attributes of each file will be cached for 240 seconds by kernel and before that it will not try to refresh the properties.
- file-cache-timeout=0 means if a file is locally cached by blobfuse, then evict it from cache as soon as all the handles are closed on that file.

Now looking at your description, I assume you mean old data (and not meta), Based on that assumption here is something to look for. From blobfuse end any file locally cached will be served from cache as long as its valid. file-cache-timeout defines for how long cache is valid. However, if user application keeps a file handle open blobfuse will never evict the file from cache. From you application end you need to confirm you close the handles for each open file. One way to confirm this is to enable log_debug in blobfuse and dig in the logs.

Another possibility is, if the file content is smaller, kernel will use its page cache to cache to content and it will remain there for pretty long time depending on kernel caching. You may need to manually clean-up the kernel cache to refresh the content on next open.

**Comment by Baiys1234** [comment]
Thanks very much! @vibhansa-msft. sounds meta info "-o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120"
setting is the problem. below are Cx's mount example.
===============
# use blobfuse to mount blob storage to file system
sudo blobfuse /datagrid/cloud_pool --tmp-path=/mnt/azureblobtmp/cloud_pool 
--config-file=/opt/blobfuse_config/blobfuse_cloud_pool.cfg 
--file-cache-timeout-in-seconds=0 -o 
attr_timeout=240 -o 
entry_timeout=240 -o 
negative_timeout=120 -o allow_other
===============

After change attr_timeout=0 and entry_timeout=0 and delete negative_timeout, now I can see data on mount path on HDI can sync with data on Azure blob.

**Comment by vibhansa-msft** [comment]
Closing this as suggested config change works.

**Comment by Baiys1234** [comment]
Hi @vibhansa-msft 
Sorry to reopen the case.

Today I did some test, with the attr_timeout=0 and entry_timeout=0,
I still find changes on Azure portal can not sync on the data in HDI mount path.

for example,
if I made some changes on Azure portal: 
AAA,AAA
BBB,AAA
111
222
333

But still can confirm old data on HDI mount path

root@hn0-xinzsu:/home/sshuser/mycontainer1# cat test2.csv
999,999
111
222
333

Do you know what we can do to prevent this. Customer wants to use azcopy to change data on AzurePortal and then read the latest data on HDI to do their application?

Thanks

**Comment by vibhansa-msft** [comment]
If the files are smaller in size, Kernel will have them in its page cache and any read will be served from there only. When you face this issue try cleaning up the kernel page cache manually and read the file again. 
To wipe out kernel page cache manually you can use below command 
sysctl -w vm.drop_caches=3

**Comment by Baiys1234** [comment]
Hi Vibhansa,
Thanks for your quick reply. I got it. Seems no better day except sysctl -w vm.drop_caches=3 to wipe out the cache data.
