### ISSUE TITLE
2 different mounted containers showing same files(all files)

### ISSUE THREAD

**Issue by kovacevicit** [Azure/azure-storage-fuse#746]
### Which version of the blobfuse was used?
1.3.6
### Which OS (please include version) are you using?
RHEL 7.9

### What problem was encountered?
When mounting multiple container, every container shows every file

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

/
### If relevant, please share your mount command.
blobfuse /containers/snapshots defaults,_netdev, --tmp-path=/tmp,--config-file=/root/fuse_connection.cfg,--container-name=snapshots,--log-level=LOG_DEBUG,allow_other 0 0
blobfuse /containers/logs defaults,_netdev, --tmp-path=/tmp,--config-file=/root/fuse_connectionLog.cfg,--container-name=logs,--log-level=LOG_DEBUG,allow_other 0 0

**Comment by vibhansa-msft** [comment]
-tmp-path=/tmp : temp cache path and mount path shall be unique and non-overlapping for each mount. 
Kindly correct the paths and retry.
