### ISSUE TITLE
Error 400 occasionally happens in ubuntu 20.04

### ISSUE THREAD

**Issue by cris-b** [Azure/azure-storage-fuse#753]
### Which version of the blobfuse was used?
 1.4.3

### Which OS (please include version) are you using?
ubuntu 20.04

(same operations were not failing with 1.4.3 on RHEL 8)

### What problem was encountered?

Error 400 occasionally seen when doing file operations.

### Have you found a mitigation/solution?

no, have tried --file-cache-timeout-in-seconds=0 to no avail.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

Mar 30 13:14:22 atria9775000006 blobfuse[3038]:  ==> REQUEST/RESPONSE :: GET https://blabla.blob.core.windows.net/run-bla-core-810656?comp=list&delimiter=/&include=metadata&maxresults=5000&prefix=data/output/2021032800000/piv-attribution-algo-log.psv.dir/.0.crc&restype=container?&User-Agent=azure-storage-fuse/1.4.3&x-ms-date=Wed, 30 Mar 2022 13:14:22 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 400 ::
Mar 30 13:14:22 atria9775000006 blobfuse[3038]: Failed to get info on data/output/2021032800000/piv-attribution-algo-log.psv.dir/.0.crc, errno : 400
Mar 30 13:14:22 atria9775000006 blobfuse[3038]: Failure when attempting to determine if data/output/2021032800000/piv-attribution-algo-log.psv.dir/.0.crc exists on the service.  errno = 400.
Mar 30 13:14:22 atria9775000006 blobfuse[3038]: Failed to map storage error code 400 to a proper errno.  Returning EIO = 5 instead.
Mar 30 13:14:22 atria9775000006 blobfuse[3038]: Successfully uploaded file /data/output/2021032800000/piv-attribution-algo-log.psv.dir/.2.crc to blob data/output/2021032800000/piv-attribution-algo-log.psv.dir/.2.crc.
Mar 30 13:14:22 atria9775000006 blobfuse[3038]: Directory is not empty, cannot delete: data/output/2021032800000/piv-attribution-output-ov-BE0260.tablet.final.piv-psv/_temporary errno = 0

### If relevant, please share your mount command.

 blobfuse $DATA --log-level=INFO --tmp-path=$BLOB_TEMP/$WORKING_CONTAINER_NAME --file-cache-timeout-in-seconds=0 --container-name=$WORKING_CONTAINER_NAME -o allow_other -o uid=1000 -o gid=1000 -o umask=0002

**Comment by vibhansa-msft** [comment]
As per the logs above this is happening for the listing calls. We have not seen any such failures in recent past. Can you post complete logs along with the request ids?

**Comment by cris-b** [comment]
sure, attached full log.

this is from a try after converting the storage account to ADLS and enabling --enable-adls, its seems not to be listing calls causing the issue this time.

[blob400.gz](https://github.com/Azure/azure-storage-fuse/files/8393670/blob400.gz)

**Comment by vibhansa-msft** [comment]
Sory was stuck with other issues so could not look at this. Are you still hitting the issue?

**Comment by cris-b** [comment]
yeah still hitting this issue.

**Comment by vibhansa-msft** [comment]
In logs I see there are only three PUT requests and only those have failed with 400. For all these requests there is no request-id is generated from server end, which hints there was something wrong with the request. What kind of auth you are using, does it have a upload permission. 
When you say "after converting storage account to adls" what do you mean by that?

**Comment by cris-b** [comment]
auth being used is account key, plenty of data is uploaded during the process so we do have upload permission.

after converting storage account to adls -> basically enabling HNS on the storage account.

**Comment by vibhansa-msft** [comment]
With Auth key permissions shall not be the issue. Also, as you are saying not all PUT requests are failing. As HNS is enable you shall always have "--enable-adls=true" cli option.

From blobfuse logs we are not getting any request-id for these requests so we cannot search from server logs on why it failed. If you see other requests that are coming back with 404 or other, then 400 we do have request-ids logged for them.

By any chance does it fail for certain files always or behavior is completely random?

**Comment by vibhansa-msft** [comment]
Kindly share your mount command and config file as well, just to check if we are missing something obvious here.

**Comment by cris-b** [comment]
we dont have a config file in this case as we just set the below command and the env vars

AZURE_STORAGE_ACCOUNT
AZURE_STORAGE_ACCESS_KEY

mount command:

blobfuse $DATA --log-level=INFO --tmp-path=$BLOB_TEMP/$WORKING_CONTAINER_NAME --file-cache-timeout-in-seconds=0 --container-name=$WORKING_CONTAINER_NAME --enable-adls=true -o allow_other -o uid=1000 -o gid=1000 -o umask=0002

its random on what files it fails on.

**Comment by vibhansa-msft** [comment]
And this fails on PUT only or different operations?
In last logs that you shared only PUT requests are failing, can you share some more logs where we can see some PUT success and some PUT failures in same log. Just want to compare if anything is changing in request itself.

**Comment by vibhansa-msft** [comment]
You can bump it up to LOG_DEBUG so that we have more details.

**Comment by vibhansa-msft** [comment]
Is this issue still hit ?

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Feel free to reopen if issue persists.
