### ISSUE TITLE
Persistent read-only caching

### ISSUE THREAD

**Issue by gtrubach-iballistix** [Azure/azure-storage-fuse#760]
### Which version of the blobfuse was used?
blobfuse-1.4.3 (Latest)

### Which OS (please include version) are you using?
Ubuntu 20.04 LTS

### What problem was encountered?
Not a problem but a question:

I have a big set of files in the blob storage which are created once and never going to be changed. I need to cache them on the local SSD of VM and I don't want them to be re-downloaded each time they are accessed. At the same time I want new files which will be created in the blob storage (externally, not using blobfuse) to be synced to the local SSD.

From my understanding, at the current moment, I only can achieve something like this with the following arguments
`-o attr_timeout=<set a big number - max double?> -o entry_timeout=<set a big number - max double?> -o negative_timeout=0 --file-cache-timeout-in-seconds=<set a big number - max double?> -o ro`
So with the big timeout the cache is not going to expire soon (until space is needed - then it's okay to evict some of the files to clear the space). And negative-timeout=0 should ensure I can access new files which were not cached before.

Can you please suggest if this is how I achieve desired behavior with blobfuse? Or are there any other better ways?

**Comment by vibhansa-msft** [comment]
Your understanding is correct, setting bigger value of file-cache-timeout ensures that file remains in cache for longer duration. However, the other part, of syncing newly created files, will not work on its own. Blobfuse only responds to filesystem calls so unless user application tries to open any of those newly created files, they will never be downloaded.

**Comment by gtrubach-iballistix** [comment]
@vibhansa-msft - Thanks a lot for the reply!

> Blobfuse only responds to filesystem calls so unless user application tries to open any of those newly created files, they will never be downloaded.

Yes, I understand. This is expected, the application will try to open the files, so blobfuse will be aware that the file is requested.

One more question before I close this question - is it possible to avoid or reduce list calls before downloading blobs with some set of arguments? Currently when I try to open, suppose, 1000 files it ends up with 1000 list requests. Or maybe there is a more effective way to do a list on a whole container without any prefixes?

**Comment by vibhansa-msft** [comment]
If application opens the file, then yes it will get downloaded.
When application opens a file, a REST call goes for list-api, are you asking about that?
If so, that list call goes with prefix set and will retrieve only that particular file info. This is in response to "getattr" call done by kernel before "open" call is fired on filesystem. Using that list call, blobfuse tries to retrieve the meta information about the file like size, last modified time etc. This cannot be avoided at the moment, however there are ways for kernel to not do this 'getattr' very frequently. Try setting "--use-attr-cache=true -o -o attr_timeout=<some big value>" in your mount cli.

**Comment by gtrubach-iballistix** [comment]
Thanks @vibhansa-msft!
