### ISSUE TITLE
provide CoreOS support

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#766]
### Which version of the blobfuse was used?
v1.4

### Which OS (please include version) are you using?
coreos

### What problem was encountered?
The default operating system of OpenShift cluster machines is [Red Hat Enterprise Linux CoreOS (RHCOS)](https://docs.openshift.com/container-platform/4.8/architecture/architecture-rhcos.html), which is not using yum to manage RPM software packages. We should find a way to package and install blobfuse in CoreOS Linux.

related to https://github.com/kubernetes-sigs/blob-csi-driver/issues/546#issuecomment-1099988894

### Have you found a mitigation/solution?
maybe blobfuse2 would support coreos?

### If relevant, please share your mount command.

cc @cvvz

**Comment by vibhansa-msft** [comment]
We will evaluate if this can be supported in V2.

**Comment by andyzhangx** [comment]
CoreOS is Linux distribution that is completely about containers. The idea behind CoreOS is that OS itself doesn't have any package manager, instead when some software is needed you make a container for it and install it in that container.

**Comment by vibhansa-msft** [comment]
With preview.4 of blobfuse2 we have started posting a docker container image where blobfuse2 is pre-installed.
You can go through [this](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Docker-Container) and let us know if this solves given scenario on CoreOS.

**Comment by vibhansa-msft** [comment]
@andyzhangx : can you comment on this. blobfuse2 is published as a container image also on Azure container registry. User can download that docker image and run blobfuse2 as container.

**Comment by cvvz** [comment]
I've done some investigation on openshift and coreos, here is the conclusion:

CoreOS doesn't support install software after the node up. Although you can use [rpm-ostree install](https://coreos.github.io/rpm-ostree/administrator-handbook/#hybrid-imagepackaging-via-package-layering) to install rpm package (add additional “layered” packages), it will only take effect when you reboot. And the version of the rpm-ostree on ARO worker node is too old to support live-apply.

CoreOS provides the mechanism called [igition](https://coreos.github.io/ignition/rationale/) to set up the machine, but it runs only on the first boot. And it's not able to create an ARO cluster with custom ignition configuration.

Openshift provides the mechanism called [Machine Config Operator](https://docs.openshift.com/container-platform/4.8/post_installation_configuration/machine-configuration-tasks.html#understanding-the-machine-config-operator), which support "manages and applies configuration and updates of the base operating system", but we cannot use it to install software on the node neither.

IMO, there is only one way to achieve the goal (which is install blobfuse/blobfuse2/blobfuse-proxy and other dependencies and start the blobfuse-proxy service on the node): Build a base system image which includes all the software we need( blobfuse, blobfuse2, blobfuse-proxy and other dependencies), and use it to create ARO worker node pool, sounds like VHD to AKS worker nodes.

**Comment by vibhansa-msft** [comment]
Blobfuse2 is also released as a container image, can that be used in CoreOS case?

**Comment by andyzhangx** [comment]
> Blobfuse2 is also released as a container image, can that be used in CoreOS case?

@vibhansa-msft blob csi driver already installs blobfuse2 in the driver image, the problem is that as long as driver image restarts, existing blobfuse2 mount would in invalid, so we need a standalone blobfuse-proxy running as a process on the host, seems coreos does not support that. And if Blobfuse2 is installed in another separate container, the blob csi driver cannot call that blobfuse2 mount, so it does not work, also if containerd restarts, since blobfuse2 is also in a container, existing blobfuse2 mounts would be also invalid.

In brief, blob csi driver already supports coreos without blobfuse-proxy, while there is a limitation without using blobfuse-proxy, 
details: https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/deploy/blobfuse-proxy

**Comment by vibhansa-msft** [comment]
So there is no clear solution here? I doubt from blobfuse end also there is hardly anything we can do?

**Comment by cgwalters** [comment]
> so we need a standalone blobfuse-proxy running as a process on the host, seems coreos does not support that. 

I think it'd work to ship the `blobfuse-proxy` binary inside a container image, but then copy it to the host system and use `systemd-run` to execute it - then the process lifecycle "escapes" the daemonset (and it logs to the journal etc. in the same way any binary run via systemd will by default).  That's a pattern we use elsewhere.

**Comment by andyzhangx** [comment]
> > so we need a standalone blobfuse-proxy running as a process on the host, seems coreos does not support that.
> 
> I think it'd work to ship the `blobfuse-proxy` binary inside a container image, but then copy it to the host system and use `systemd-run` to execute it - then the process lifecycle "escapes" the daemonset (and it logs to the journal etc. in the same way any binary run via systemd will by default). That's a pattern we use elsewhere.

@cgwalters  do you have any example? thanks.

**Comment by cgwalters** [comment]
> @cgwalters do you have any example? thanks.

Yep, we do this in [the OpenShift MCO](https://github.com/openshift/machine-config-operator/)

- See https://github.com/openshift/machine-config-operator/blob/3d84f653e08d760d446442ddc80c3da21d8d7e59/cmd/machine-config-daemon/start.go#L61 where we do "copy self to host"
- https://github.com/openshift/machine-config-operator/blob/3d84f653e08d760d446442ddc80c3da21d8d7e59/pkg/daemon/daemon.go#L211 is a different place where we use `systemd-run` (while `chroot`ed into the host note)

We actually execute that binary directly from a systemd unit already on host, but the idea is to combine these two things.

**Comment by rh-aelgendy** [comment]
@andyzhangx This issue is in closed status currently. Do we expect any active work and re-opening for this issue based on Colin comment and examples above to have support for OpenShift CoreOS via MCO?  Thanks

**Comment by gillesde** [comment]
Same question @andyzhangx , this issue is closed but it is not clear if the issue was resolved or the support for Azure Blob was added to RedHat OpenShift. Would it be possible to have a clarification, please?

**Comment by vibhansa-msft** [comment]
@andyzhangx Is it something we need to support from blobfuse end or it's more of a AKS support issue ?

**Comment by cvvz** [comment]
@cgwalters Thanks for your advice. I have another question is that we need to install blobfuse2 package in coreOS after the node is up, how can we do that?

**Comment by vibhansa-msft** [comment]
If you are using AKS then blobfuse2 will be preinstalled.

**Comment by andyzhangx** [comment]
> If you are using AKS then blobfuse2 will be preinstalled.

it's not on AKS, it's on OpenShift(coreos)

**Comment by vibhansa-msft** [comment]
CSI Driver in your case will have it. @andyzhangx can you help with this one.

**Comment by andyzhangx** [comment]
> CSI Driver in your case will have it. @andyzhangx can you help with this one.

@vibhansa-msft not sure how to install blobfuse2 on coreos since on ubuntu, we only need to run `apt install blobfuse2`, while install blobfuse2 on coreos requires a reboot, that's not acceptable since it would impact existing applications on the same node.

**Comment by travier** [comment]
You don't need to install it in RHEL CoreOS systems. As Colin suggested in https://github.com/Azure/azure-storage-fuse/issues/766#issuecomment-1600775906 & https://github.com/Azure/azure-storage-fuse/issues/766#issuecomment-1600846770 you can get the binary from a container image, copy and run it on the host.

**Comment by vibhansa-msft** [comment]
If there is no open workitem for blobfuse here, can we close this report.

**Comment by jsafrane** [comment]
I've looked at CoreOS and what [blob-csi-driver](github.com/kubernetes-sigs/blob-csi-driver) needs on the host. Please correct me if I am wrong. This is the ideal state:

* The CSI driver runs as a DaemonSet Pod and in NodeStage/NodePublish it connects to `blobfuse-proxy` unix domain socket that is present in the driver container as a HostPath volume.
* `blobfuse-proxy` runs as a systemd service **on the host** and exposes its unix domain socket somewhere for the driver. `blobfuse-proxy` gets a mount request via the socket to mount a volume and execs `blobfuse2` to actually mount the volume.
* `blobfuse2` is installed **on the host**. AFAIK it does not run as a systemd service, but it spawns a fuse daemon for each mount.

I can also see that the `blobfuse-proxy` already has [init.sh script](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/pkg/blobfuse-proxy/init.sh) to put (or update) the `blobfuse-proxy` binary from a container to the host + create a systemd service for it + run it. The script is Debian / Ubuntu based and uses `.deb` package for `blobfuse2` package, you just need something very similar for CoreOS:

1. Adapt init.sh for CoreOS (or write a new one).
    1. `/usr` is read-only. Install (or update) both  `blobfuse2`and `blobfuse-proxy` binaries on the host to say `/var/lib/blobfuse2/`. Not a great location, but it is write-able and it will survive reboot. It's not possible to use yum / rpm directly, because of read-only `/usr`, you can either decompress RPMs manually or use any other trick. Luckily, all `blobfuse2` dependencies are already installed in CoreOS.
        * I would personally put `blobfuse2` and `blobfuse-proxy` binaries directly to the container image with the init.sh script and just copy them to the host. Just in case a cluster does not have access to the internet and thus can't access Microsoft yum repos.
    3. Host's `/etc` is fully write-able and survives reboot too, so you can create any systemd services and config files if you need so. There is nothing special there. Please do not put binaries to `/etc` - it's possible, but IMO it looks worse that `/var/lib`.
2. Adapt `blobfuse-proxy` systemd service to run blobfuse-proxy from `/var/lib/blobfuse2/`. IMO it will be necessary to update PATH in the service too, so `blobfuse-proxy` can exec `blobfuse2` in `/var/lib/blobfuse2/`.

I hope I did not miss anything obvious.

**Comment by vibhansa-msft** [comment]
***@***.*** Zhang ***@***.***> to reply from CSI driver and AKS side.

Regards
Vikas Bhansali

**Comment by travier** [comment]
You can install binaries locally in `/usr/local/bin` or `/opt` on RHCOS.

**Comment by vibhansa-msft** [comment]
Closing this as there is no action item on blobfuse here. Feel free to reopen if you feel otherwise.

**Comment by jsafrane** [comment]
Indeed, there is nothing to do in blob fuse driver. @andyzhangx we can continue discussion in the CSI driver repo if we need to, because the work needs to be done there.

**Comment by jsafrane** [comment]
You know what, I reopened https://github.com/kubernetes-sigs/blob-csi-driver/issues/791 right away.
