### ISSUE TITLE
Data Lake NFS mount is not compatible with blobfuse mount

### ISSUE THREAD

**Issue by secret104278** [Azure/azure-storage-fuse#774]
### Which version of the blobfuse was used?
1.4.3

### Which OS (please include version) are you using?
ubuntu 20

### What problem was encountered?
I've created a storage account with data lake enabled and mount it on two different locations with nfsv3 and blobfuse.
And i found some unexpected behavior:
- The blob created in blobfuse mount cannot be modify in nfsv3 mount.
- The `block list` return from api of the blob created in nfsv3 is always empty.

Is there any difference between the underlying implementation of nfsv3 support and blobfuse?
Is there any way i can work smoothly between these two types of mounting?

**Comment by vibhansa-msft** [comment]
To mount a gen2 account you need to provide some extra parameter in your blobfuse mount cli. Refer to our README for the same. 
For the NFSv3 compliance part: officially it's not a supported feature. It has never been tried from end to mount the same container using blobfuse and nfsv3.

**Comment by secret104278** [comment]
@vibhansa-msft thanks for quick reply.
I did use the `--use-adls=true` flag for blobfuse. The reading part works well, probably because the reading api doesn't involve the "block" concept. However, the writing part doesn't work well together.

**Comment by vibhansa-msft** [comment]
Yes the writing part in blobfuse uses blob end-point and involves block and block-list concepts.

**Comment by vibhansa-msft** [comment]
As discussed in above thread, blobfuse and NFS are not cross-compatible. Closing this thread. Feel free to reopen in case you have any further queries on this topic.
