### ISSUE TITLE
Publish motidy events in inotify when file changes on server

### ISSUE THREAD

**Issue by elestedt** [Azure/azure-storage-fuse#775]
### Which version of the blobfuse was used?
1.4.3

### Which OS (please include version) are you using?
Ubuntu 20.04

### What problem was encountered?
I'm trying to monitor a blob storage for changes, mounted with blobfuse, but I'm not getting the modify events.
It would be really helpful if it's possible for those events to be emitted when a file in remote blob is updated.

### Have you found a mitigation/solution?
Calculating checksum and polling for change

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No error, missing functionality

### If relevant, please share your mount command.
```
    sudo blobfuse /data/blob --tmp-path=/mnt/resource/blobfusetmp \
        -o allow_other -o uid=$(id -u) -o gid=$(id -g) \
        --config-file=fuse_connection.cfg -o attr_timeout=240 \
        -o entry_timeout=240 -o negative_timeout=120
```
Started mounting as root to get other inotify events, don't know if it's strictly needed.
```
inotifywait --recursive --monitor /data/blob/
```

**Comment by vibhansa-msft** [comment]
Blobfuse is a file-system driver, and it responds only to kernel call on filesystem like open/close/read/write. It does not, in the background, monitor the container for changes. If user application tries to open a file and it's not in our local cache, we will download the file from container and that's the only way to get the new changes reflected. As of now there is no event notification model where it can emit file changes on container.
If you are looking for blobfuse to show new contents when you open a file, you can set the file-cache-timeout to 0, which means blobfuse will remove the locally cached copy as soon as handle is closed.
