### ISSUE TITLE
Blobfuse directory permissions issue

### ISSUE THREAD

**Issue by ashokmukkara** [Azure/azure-storage-fuse#776]
### Which version of the blobfuse was used?

blobfuse 1.4.3

### Which OS (please include version) are you using?

NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"

### What problem was encountered?

I used below mount command and ran it as root since other users not allowed to execute

sudo blobfuse /globe/security/agilesi/ --tmp-path=/mnt/resource/blobfusetmp --config-file=/globe/security/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

Whn i used -o allow_other mount directory permissions changing  to "drwxrwxrwx"  recursively 

drwxrwxrwx 2 azureuser users 4.0K Apr 27 11:51 agilesi

If i am not using -o allow_other, other users can't access mount point 

How to avoid giving full permission(drwxrwxrwx) on mount point when we use -o allow_other
due to this all my files and folders in permissions changing to executable 

### If relevant, please share your mount command.

sudo blobfuse /globe/security/agilesi/ --tmp-path=/mnt/resource/blobfusetmp --config-file=/globe/security/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Comment by ashokmukkara** [comment]
@vibhansa-msft Thank you it worked!

I am trying to add fstab entry as below, not working can you help me right pattern for fastab entry

blobfuse /globe/security/agilesi/ fuse delay_connect,defaults,_netdev,--tmp-path=/mnt/resource/blobfusetmp,--config-file=/globe/security/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o umask=003 -o default_permissions  0 0

**Comment by vibhansa-msft** [comment]
You will have much better control over params and other stuff if you just run a shell script from fstab and in your script you have your regular mount cli. Makes it much easier to change the mount command later.

You can just give below line in fstab. use ~/mnt.sh to host your mount command for blobfuse.
"~/mnt.sh /home/user1/blobfuse_mnt fuse _netdev,allow_other,delay_connect,uid=10000,gid=000 0 0 "

**Comment by ashokmukkara** [comment]
@vibhansa-msft Thanks for update!

I observed a issue with params umask=003 -o default_permissions 0 0,  below full command

sudo blobfuse /globe/security/agilesi/ --tmp-path=/mnt/resource/blobfusetmp --config-file=/globe/security/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o umask=003 -o default_permissions


When use it i see only default permissions how even normal user do not have write permission in mount point, we need use 'sudo' if use sudo then mount point permission changing to root, and user loosing all permissions 


azureuser@blobfuse:/globe/security/agilesi> cd ashok/
azureuser@blobfuse:/globe/security/agilesi/ashok> ls
azureuser@blobfuse:/globe/security/agilesi/ashok> touch ashok.txt
touch: setting times of 'ashok.txt': Permission denied
azureuser@blobfuse:/globe/security/agilesi/ashok> sudo touch ashok.txt
azureuser@blobfuse:/globe/security/agilesi/ashok> ls
ls: cannot open directory '.': Permission denied
azureuser@blobfuse:/globe/security/agilesi/ashok> cd ..
azureuser@blobfuse:/globe/security/agilesi> ls -ltrh
total 4.0K
drwxrwxr-- 2 azureuser users 4.0K Jan  1  1970 test
drwxrwxr-- 2 root      root  4.0K May  2 05:41 ashok
