### ISSUE TITLE
Getting old versions of mounted files

### ISSUE THREAD

**Issue by tengl** [Azure/azure-storage-fuse#785]
### Which version of the blobfuse was used?
1.4.3

### Which OS (please include version) are you using?
CentOS Linux release 8.1.1911 (Core)

### What problem was encountered?
I have a VM in Azure that mounts files from Azure storage using blobfuse, but the files in the mount is not the latest versions. 

I downloaded the file from storage using Azure Portal and did a binary compare with the original, they were identical. Then I did the same with the file from the VM and they differ. I even mount with streaming = true, see command below. 

This error occurs frequently. but not always. The modified date seems to be correct, but the data is not.

### Have you found a mitigation/solution?
A work around is to unmount and mount again. 

When I unmount the storage I got the error "target is busy", so I did unmount with `umount -l /mnt/files` and mounted the storage again. Could that be the issue? That an application is locking the file so it doesn't get the latest version? The only application that access the file has been restarted multiple times, without any update of the file. 

### If relevant, please share your mount command.

```shell
blobfuse /mnt/files --tmp-path=/mnt/filestmp -o ro --streaming=true --config-file=/home/user/fuse_connection.cfg
```

**Comment by tengl** [comment]
Yes, I'm uploading the blob to storage using Azure CLI. The storage is mounted in read-only mode and streaming, it is not possible to modify it using the mount. What is the use case for read-only streaming mounts if they don't get the latest version? 

And how come the attributes (modified date) is updated, but not the data?

**Comment by vibhansa-msft** [comment]
Linux kernel has its own page cache where contents of the file are cached. In such cases read requests will be served directly by kernel and it will not even reach blobfuse. You need to manually clean kernel page cache to refresh the content.
Here is the shell command for the same "sysctl -w vm.drop_caches=3"

**Comment by vibhansa-msft** [comment]
Also, if you intend to refresh the contents often then you shall have entry-timeout and negative-timeouts set to 0 in your mount cli. Refer to our README for exact cli options.

**Comment by tengl** [comment]
Thanks  @vibhansa-msft, I will try the command. We don't refresh often and we read the file once every night. When we do an update we read the file directly. But everything is scripted so if the commands works we're happy.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Feel free to reopen if issue persists.
