### ISSUE TITLE
[Question] Unmounting immediately after write

### ISSUE THREAD

**Issue by Adelzu** [Azure/azure-storage-fuse#797]
Hi

We are using blobfuse to mount a drive to a server which runs a database backups. The purpose is to have a cold backup space on the cloud of our database. What we do is the following:

1. Mount the container.
2. Backup the database (full or incremental based on logic) to the mount location.
3. Unmount

The question is, does the unmount affect writing to the blob storage? What happens if the data is not yet fully uploaded and the drive is unmounted?

Thanks,

**Comment by vibhansa-msft** [comment]
Unmount command will fail with "Device or resource busy" till upload is in progress.

**Comment by vibhansa-msft** [comment]
Closing this as its more of question then bug. Feel free to open another item if you observe some issue in this regard or add here if you have any further queries.
