### ISSUE TITLE
Rename folder failed

### ISSUE THREAD

**Issue by cwang2002** [Azure/azure-storage-fuse#798]
### Which version of the blobfuse was used?
1.4.3

### Which OS (please include version) are you using?
RHEL 7.9

### What problem was encountered?
command "mv f1 folder1" getting Input/Output error and the folder renaming doesn't occur

### Have you found a mitigation/solution?
yes. Use storage explorer or the azure portal to rename

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
```
May 31 12:37:04 blobfuse[3963]: ** Post fork authentication for older libcurl version
May 31 12:43:26 blobfuse[3963]: In GetProperties list_segmented_item 0 file f1/
May 31 12:43:26 blobfuse[3963]: In GetProperties found blob in list hierarchical file f1/
May 31 12:43:26 blobfuse[3963]: ==> REQUEST/RESPONSE :: PUT https://xxxx.xxx.xxx/container/folder1?&Content-Length=0&User-Agent=azure-storage-fuse/1.4.3&x-ms-date=Tue, 31 May 2022 12:43:26 GMT&x-ms-version=2018-11-09&x-ms-copy-source=https://xxxx.xxx.xxx/container/f1&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 400 :: REQ ID : aa054d5b-301e-0081-32ec-74caed000000
May 31 12:43:26 blobfuse[3963]: Attempt to call start_copy from f1 to folder1 failed.  errno = 400#012.
May 31 12:43:26 blobfuse[3963]: Failed to rename /f1, err : 400_

```
### If relevant, please share your mount command.
systemd service mounted with root, but allow others

**Comment by vibhansa-msft** [comment]
What kind of auth you are using? Validate you have required permissions to rename the folder.

**Comment by cwang2002** [comment]
All users have 777 on folders and files

**Comment by gapra-msft** [comment]
@cwang2002 what kind of auth are you using to access the storage account?

**Comment by cwang2002** [comment]
account key

**Comment by vibhansa-msft** [comment]
Is this account HNS enabled (Gen2 account)?

**Comment by cwang2002** [comment]
I just checked the systemd service file. it doesn't have use-adls option. I guess I missed it when I converted the configuration from fstab to systemd service. I'll test it out, thanks

**Comment by gapra-msft** [comment]
Great! Thank you, I will go ahead and resolve this then.
