### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-fuse#80]
@andyzhangx  plans to implement a flex volume driver:
User brings account name/key & container name, and use flex volume driver to mount a container to a directory on Host, and all pods on that Host could consume the mounted directory.

An example is here: https://github.com/khenidak/dysk/tree/master/kubernetes

**Comment by sreenir** [comment]
It will be great to have this feature just like how we can mount azureFile shares in kubernetes deployments.

**Comment by andyzhangx** [comment]
@sreenir Do you mean k8s built-in (also called in-tree) volume? As I know, k8s is encourging dev to use [CSI](https://github.com/container-storage-interface/spec/blob/master/spec.md) to implement new volumes, while CSI is still in alpha in k8s v1.10, so in current stage, I would like to implement a flex volume driver for blobfuse first. And when CSI is in beta, I would implement CSI driver for blobfuse. And flex volume driver could be used in k8s v1.7, that's another advantage vs CSI.

**Comment by andyzhangx** [comment]
I have worked out the first version:
https://github.com/Azure/azure-storage-fuse/pull/104

**Comment by seguler** [comment]
See the following link for Kubernetes support for blobfuse: https://github.com/andyzhangx/kubernetes-drivers/tree/master/flexvolume/blobfuse
