### ISSUE TITLE
Support blobfuse on minimal linux distros for docker

### ISSUE THREAD

**Issue by sreenir** [Azure/azure-storage-fuse#81]
It will be great to see blobfuse working with minimal linux distros (like Alpine and Centos Atomic) for docker.

**Comment by ramSeraph** [comment]
the following change in https://github.com/Azure/azure-storage-fuse/blob/master/blobfuse/fileapis.cpp#L275 makes it build against musl in alpine
```diff
diff --git a/blobfuse/fileapis.cpp b/blobfuse/fileapis.cpp
index d80d826..588db15 100644
--- a/blobfuse/fileapis.cpp
+++ b/blobfuse/fileapis.cpp
@@ -272,7 +272,7 @@ int azs_flush(const char *path, struct fuse_file_info *fi)
     snprintf(path_link_buffer, 50, "/proc/self/fd/%d", (((struct fhwrapper *)fi->fh)->fh));

     // canonicalize_file_name will follow symlinks to give the actual path name.
-    char *path_buffer = canonicalize_file_name(path_link_buffer);
+    char *path_buffer = realpath(path_link_buffer, NULL);
     if (path_buffer == NULL)
     {
         AZS_DEBUGLOGV("Skipped blob upload in azs_flush with input path %s because file no longer exists.\n", path);
```

I haven't actually used it yet, so don't know if there will be any runtime problems.

**Comment by molinch** [comment]
I see that the issue is still opened. Do you know if blobfuse is now available on Alpine ?

**Comment by vibhansa-msft** [comment]
The above changeset was not integrated in blobfuse main line. We have not tested on distros like Alpine ourselves, however you can take the latest code base and make above mentioned changeset manually and give it a try.

**Comment by sicet7** [comment]
I tried compiling the latest release(of time of writing) for alpine in a docker container with the following RUN command:
```Dockerfile
RUN apk add borgbackup sshfs bash && \
    apk add --update --no-cache --virtual buildDeps \
    git \
    cmake \
    fuse-dev \
    curl-dev \
    gnutls-dev \
    util-linux-dev \
    libgcrypt-dev \
    boost-dev \
    make \
    go \
    gcc \
    g++ && \
    mkdir /build && \
    git clone --depth="1" --branch="blobfuse-1.4.2" https://github.com/Azure/azure-storage-fuse.git /build/blobfuse && \
    cd /build/blobfuse && \
    bash ./build.sh && \
    cp /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    echo "Etc/UTC" > /etc/timezone && \
    echo "[Date]\ndate.timezone=Etc/UTC" > /usr/local/etc/php/conf.d/timezone.ini && \
    apk del buildDeps
```
and i am not a guru at this stuff but i have hit a roadblock which i dont know how to fix maybe someone know more than i do? :sweat_smile: 
```
build/blobfuse/blobfuse/src/BlobfuseGcCache.cpp: In member function 'void gc_cache::run_gc_cache()':
/build/blobfuse/blobfuse/src/BlobfuseGcCache.cpp:180:40: error: 'O_WRONLY' was not declared in this scope
  180 |                 int fd = open(mntPath, O_WRONLY);
      |                                        ^~~~~~~~
/build/blobfuse/blobfuse/src/BlobfuseGcCache.cpp:180:26: error: 'open' was not declared in this scope; did you mean 'popen'?
  180 |                 int fd = open(mntPath, O_WRONLY);
      |                          ^~~~
      |                          popen
/build/blobfuse/blobfuse/src/BlobfuseGcCache.cpp:183:45: error: 'O_RDONLY' was not declared in this scope; did you mean 'ST_RDONLY'?
  183 |                     int fdr = open(mntPath, O_RDONLY);
      |                                             ^~~~~~~~
      |                                             ST_RDONLY
make[2]: *** [CMakeFiles/blobfuse.dir/build.make:104: CMakeFiles/blobfuse.dir/blobfuse/src/BlobfuseGcCache.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/blobfuse.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by vibhansa-msft** [comment]
@sicet7 : compilation goes fine with the current code on RHEL and Ubn distros so it shall be some dependency issue on the container. You can try one thing, in file blobfuse/src/BlobfuseGcCache.cpp, on the top where #includes are there try adding #include<fcntl.h> and recompile.

**Comment by vibhansa-msft** [comment]
both legacy blobfuse and next generation 'blobfuse2' work on docker container. You can directly install the binary instead of building code on container, and it shall work seamlessly. Feel free to reopen or open another bug if you have any further issue in this regard.

**Comment by dekiesel** [comment]
Do you have any plans for supporting alpine out of the box? I might be mistaken, but blobefuse2 doesn't  work on alpine, right?

**Comment by dvanwissen** [comment]
> both legacy blobfuse and next generation 'blobfuse2' work on docker container. You can directly install the binary instead of building code on container, and it shall work seamlessly. Feel free to reopen or open another bug if you have any further issue in this regard.

I'm not sure why you think so @vibhansa-msft ; there is no published binary for Alpine, which is what this issue is about. Still not after two more years. Can you elaborate which binary should be used to be able to install this within a alpine based dockercontainer?

**Comment by vibhansa-msft** [comment]
Due to Microsoft security guidelines, we are not supposed to release container images on Alpine. We are publishing Ubuntu-22 and Mariner based container images as of now. If you wish to build for Alpine, you can take our Ubuntu docker file as reference and build. Below is the link for the same:

https://github.com/Azure/azure-storage-fuse/blob/main/docker/Dockerfile

Same folder also contains a script that can help you build the image.
