### ISSUE TITLE
Intermittent error: Remote address changed

### ISSUE THREAD

**Issue by j-hudecek** [Azure/azure-storage-fuse#814]
### Which version of the blobfuse was used?
blobfuse2 2.0.0-preview.2, built from source, main branch, commit 0b9b909d so that we can use streaming with block cache

### Which OS (please include version) are you using?

RHEL 8.5

### What problem was encountered?

Intermittently when accessing files:
```Couldn't open myfile.tif: Remote address changed```

### Have you found a mitigation/solution?
no

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
no, nothing. Log level is set to LOG_WARNING though

### If relevant, please share your mount command.

./blobfuse2 mount /mntAzure --config-file=fuseconfig_stream.yaml --log-level LOG_WARNING --read-only

Here is the config:

	allow-other: true
	 
	logging:
	  type: syslog
	 
	components:
	  - libfuse
	  - stream
	  - attr_cache
	  - azstorage
	 
	libfuse:
	  attribute-expiration-sec: 120
	  entry-expiration-sec: 120
	  negative-entry-expiration-sec: 240
	 
	stream:
	  read-only: true
	  block-size-mb: 32
	  disk-persistence: true
	  disk-cache-path: /tmp/fusecache
	  disk-cache-size: 3000
	 
	 
	 
	attr_cache:
	  timeout-sec: 7200
	 
	azstorage:
	  type: block
	  endpoint: https://act.blob.core.windows.net
	  account-name: act
	  account-key: BtqMz……..=
	  mode: key
	  container: cont

**Comment by souravgupta-msft** [comment]
Can you set the log level to debug mode and share the log?

**Comment by j-hudecek** [comment]
I don't know how to trigger it - when I try to read the file it opens. But I saw the failure in the logs of my application once 1 in ~2 weeks so that would be a lot of debug logs

**Comment by souravgupta-msft** [comment]
You can run the following command to enable debug logs
./blobfuse2 mount /mntAzure --config-file=fuseconfig_stream.yaml --log-level=LOG_DEBUG --read-only

Or, you can also enable log debug by replacing logging section in the config with below (and remove --log-level flag from cli)
logging:
  type: syslog
  level: log_debug

The logs will be dumped to /var/log/syslog or /var/log/messages

**Comment by j-hudecek** [comment]
I'll update it (and change the block size to 1mb as we saw better perf), set the level to DEBUG and log to a separate file and report back if we see it again.
