### ISSUE TITLE
[Blobfuse2] Unable to list directories twice.

### ISSUE THREAD

**Issue by rijos** [Azure/azure-storage-fuse#815]
| Version      | blobfuse2-2.0.0-preview2                                                                      |
|----------- |--------------------------------------------------------------------|
| OS              | Ubuntu 20.04.4 LTS 5.13.0-1028-azure                                                |
| Command  | blobfuse2 mountv1 mnt/ --tmp-path=/tmp--config-file=config.cfg  |
| libfuse3      | 3.9.0-2                                                                                                     |

Using 'ls' twice within the same directory results in the following message:
ls: cannot open directory '.': No such file or directory

You can reproduce it using the following steps:
```bash
user@local:/# cd /myshare/subfolder
user@local:/myshare/subfolder# ls
test.txt
user@local:/myshare/subfolder# ls
ls: cannot open directory '.': No such file or directory
```

**Comment by vibhansa-msft** [comment]
We have not observed this behavior in our local tests. Can you enable log-debug and share the log file to understand what is going wrong here?

**Comment by rijos** [comment]
I've pinned it down further, issue does not occur on the root folder. eg: '/' however it does happen in subfolders.
Here is the log
```
FUSE library version: 3.9.0
nullpath_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.34
flags=0x33fffffb
max_readahead=0x00020000
   INIT: 7.31
   flags=0x0041f039
   max_readahead=0x00400000
   max_write=0x00100000
   max_background=128
   congestion_threshold=96
   time_gran=1
   unique: 2, success, outsize: 80
unique: 4, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 564388
getattr[NULL] /
   unique: 4, success, outsize: 120
unique: 6, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 564388
   unique: 6, error: -38 (Function not implemented), outsize: 16
unique: 8, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 565494
opendir flags: 0x18800 /
   opendir[824635531488] flags: 0x18800 /
   unique: 8, success, outsize: 32
unique: 10, opcode: READDIRPLUS (44), nodeid: 1, insize: 80, pid: 565494
readdirplus[824635531488] from 0
   unique: 10, success, outsize: 1072
unique: 12, opcode: READDIRPLUS (44), nodeid: 1, insize: 80, pid: 565494
readdirplus[824635531488] from 6
   unique: 12, success, outsize: 16
unique: 14, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
releasedir[824635531488] flags: 0x0
   unique: 14, success, outsize: 16
unique: 16, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 564388
getattr[NULL] /
   unique: 16, success, outsize: 120
unique: 18, opcode: OPENDIR (27), nodeid: 3, insize: 48, pid: 565495
opendir flags: 0x18800 /ortho
   opendir[824635532160] flags: 0x18800 /ortho
   unique: 18, success, outsize: 32
unique: 20, opcode: READDIRPLUS (44), nodeid: 3, insize: 80, pid: 565495
readdirplus[824635532160] from 0
   unique: 20, success, outsize: 1536
unique: 22, opcode: READDIRPLUS (44), nodeid: 3, insize: 80, pid: 565495
readdirplus[824635532160] from 8
   unique: 22, success, outsize: 16
unique: 24, opcode: RELEASEDIR (29), nodeid: 3, insize: 64, pid: 0
releasedir[824635532160] flags: 0x0
   unique: 24, success, outsize: 16
unique: 26, opcode: OPENDIR (27), nodeid: 3, insize: 48, pid: 565506
opendir flags: 0x18800 /ortho
   opendir[824633854704] flags: 0x18800 /ortho
   unique: 26, success, outsize: 32
unique: 28, opcode: GETATTR (3), nodeid: 3, insize: 56, pid: 565506
getattr[NULL] /ortho
   unique: 28, error: -2 (No such file or directory), outsize: 16
unique: 30, opcode: RELEASEDIR (29), nodeid: 3, insize: 64, pid: 0
releasedir[824633854704] flags: 0x0
   unique: 30, success, outsize: 16
```

In addition, trying to access /mnt/ortho immediately shows an directory not found. but first accessing /mnt, listing the directory and aftewards accessing /mnt/ortho works file. I'll check if including attr-cache solves the problem and will resume debugging this afternoon.

**Comment by souravgupta-msft** [comment]
Is your account Hierarchical namespace (HNS) enabled?

Also, the logs you shared are libfuse logs, not blobfuse logs. If your logging type is syslog, then the logs will be stored in /var/log/syslog. Can you share the config file you are using?

**Comment by rijos** [comment]
HNS is disabled, as for blobfuse2 mountv1 fuse/ --tmp-path=tmp/ --config-file=config.cfg --log-level=LOG_DEBUG I cant see any output in /var/log/syslog.. i'll check what happens on a fresh VM.

**Comment by rijos** [comment]
With HNS enabled everything works  perfectly.

**Comment by rijos** [comment]
Hi @tasherif-msft, correct these are pre-existing dirs. For our use case we can easily migrate to HNS enabled accounts, i'd say lets close this issue if this is an unsupported use case.

**Comment by tasherif-msft** [comment]
Yes migrating to an HNS enabled account should resolve the issue for you! I will go ahead and close this and feel free to create a new issue if something comes up.
