### ISSUE TITLE
Tips on improving performance of streaming cached access?

### ISSUE THREAD

**Issue by j-hudecek** [Azure/azure-storage-fuse#816]
### Which version of the blobfuse was used?
blobfuse2 version 2.0.0-preview.2, commit 590bd54f9c14d1b752368888d7f452c968329fe4 (new) vs
blobfuse2 version 2.0.0-preview.1, commit 0b9b909dbceb8441735dff2f450cc746f3fa341e (old)

### Which OS (please include version) are you using?
Ubuntu 20.04

### What problem was encountered?
the performance of the new cached streaming is 3x worse than old disk-based cache for some files.
Biggest difference is for large (~1GB) BigTIFF TIFF files, command
```openslide-write-png $f 0 0 0 256 256  o.png```
would take about 4s with the disk-based caching. The new (memory only?) caching causes it consistently to jump to around 12s.
This command reads blocks from beginning of the file and few "random" places in the middle of the file (TIFF has internal directories as linked list so to traverse them you need to read all of them). It opens and closes the file for every read it does which locally isn't a problem.

Here are the relevant parts of the configs:

old:

	stream:
	  read-only: true
	  block-size-mb: 1
	  disk-persistence: true
	  disk-cache-path: /tmp/cfmpb2.1
	  disk-cache-size: 3000

new:

	read-only: true

	stream:
	  block-size-mb: 1
	  handle-limit: 5
	  handle-buffer-size-mb: 80

We would prefer having a total number of cached blocks limit instead of number of handles * per handle limit. We need to access different file types - some will need lots of blocks cached and some just one, but if I'm reading this correctly if we need lots of blocks we can only cache a few files. 

It feels like the disk-based cache was a better solution for us as it can hold way more blocks.

### Have you found a mitigation/solution?
get stuck on the old one?

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
lots of logs, here are the last few entries (they are repeating) 

the old one:

	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [libfuse_handler.go (550)]: Libfuse::libfuse_open : 2019/00000-10000/file.svs
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [stream.go (167)]: Stream::OpenFile : name=2019/00000-10000/file.svs, flags=32768, mode=-rwxrwxrwx
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [azstorage.go (288)]: AzStorage::OpenFile : 2019/00000-10000/file.svs
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [block_blob.go (390)]: BlockBlob::GetAttr : name 2019/00000-10000/file.svs
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [libfuse_handler.go (658)]: Libfuse::libfuse_flush : 2019/00000-10000/file.svs, handle: 3019
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [libfuse_handler.go (701)]: Libfuse::libfuse_release : 2019/00000-10000/file.svs, handle: 3019
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [stream.go (268)]: Stream::CloseFile : name=2019/00000-10000/file.svs, handle=3019
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [azstorage.go (308)]: AzStorage::CloseFile : 2019/00000-10000/file.svs
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [libfuse_handler.go (550)]: Libfuse::libfuse_open : 2019/00000-10000/file.svs
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [stream.go (167)]: Stream::OpenFile : name=2019/00000-10000/file.svs, flags=32768, mode=-rwxrwxrwx
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [azstorage.go (288)]: AzStorage::OpenFile : 2019/00000-10000/file.svs
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [block_blob.go (390)]: BlockBlob::GetAttr : name 2019/00000-10000/file.svs
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [libfuse_handler.go (658)]: Libfuse::libfuse_flush : 2019/00000-10000/file.svs, handle: 3020
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [libfuse_handler.go (701)]: Libfuse::libfuse_release : 2019/00000-10000/file.svs, handle: 3020
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [stream.go (268)]: Stream::CloseFile : name=2019/00000-10000/file.svs, handle=3020
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [azstorage.go (308)]: AzStorage::CloseFile : 2019/00000-10000/file.svs
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [libfuse_handler.go (701)]: Libfuse::libfuse_release : 2019/00000-10000/file.svs, handle: 3018
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [stream.go (268)]: Stream::CloseFile : name=2019/00000-10000/file.svs, handle=3018
	Jun 16 11:36:05 do-linux-test blobfuse2[1496837]: LOG_TRACE [azstorage.go (308)]: AzStorage::CloseFile : 2019/00000-10000/file.svs

new one:

	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [libfuse_handler.go (586)]: Libfuse::libfuse_open : 2019/00000-10000/file.svs
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [read.go (87)]: Stream::OpenFile : name=2019/00000-10000/file.svs, flags=32768, mode=-rwxrwxrwx
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [azstorage.go (288)]: AzStorage::OpenFile : 2019/00000-10000/file.svs
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [block_blob.go (390)]: BlockBlob::GetAttr : name 2019/00000-10000/file.svs
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [block_blob.go (592)]: BlockBlob::ReadInBuffer : name 2019/00000-10000/file.svs
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [libfuse_handler.go (621)]: Libfuse::libfuse_open : 2019/00000-10000/file.svs, handle 2801
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [libfuse_handler.go (690)]: Libfuse::libfuse_flush : 2019/00000-10000/file.svs, handle: 2801
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [libfuse_handler.go (736)]: Libfuse::libfuse_release : 2019/00000-10000/file.svs, handle: 2801
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [read.go (187)]: Stream::CloseFile : name=2019/00000-10000/file.svs, handle=2801
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [azstorage.go (308)]: AzStorage::CloseFile : 2019/00000-10000/file.svs
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [libfuse_handler.go (586)]: Libfuse::libfuse_open : 2019/00000-10000/file.svs
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [read.go (87)]: Stream::OpenFile : name=2019/00000-10000/file.svs, flags=32768, mode=-rwxrwxrwx
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [azstorage.go (288)]: AzStorage::OpenFile : 2019/00000-10000/file.svs
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [block_blob.go (390)]: BlockBlob::GetAttr : name 2019/00000-10000/file.svs
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [block_blob.go (592)]: BlockBlob::ReadInBuffer : name 2019/00000-10000/file.svs
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [libfuse_handler.go (621)]: Libfuse::libfuse_open : 2019/00000-10000/file.svs, handle 2802
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [libfuse_handler.go (690)]: Libfuse::libfuse_flush : 2019/00000-10000/file.svs, handle: 2802
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [libfuse_handler.go (736)]: Libfuse::libfuse_release : 2019/00000-10000/file.svs, handle: 2802
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [read.go (187)]: Stream::CloseFile : name=2019/00000-10000/file.svs, handle=2802
	Jun 16 11:30:22 do-linux-test blobfuse2[1496498]: LOG_TRACE [azstorage.go (308)]: AzStorage::CloseFile : 2019/00000-10000/file.svs

(note the high PID).

### If relevant, please share your mount command.
./blobfuse2 mount /mntAzure --config-file=fuseconfig_stream.yaml --log-level LOG_DEBUG --read-only

**Comment by vibhansa-msft** [comment]
Do you open the same file multiple times sequentially or in parallel?

**Comment by tasherif-msft** [comment]
Hi @j-hudecek,

Thank you very much for opening the issue and giving us feedback as we continue developing Blobfuse2.
Given your workload - it makes sense that the old version worked better. Since you open and close the handle on each read disk persistence came into effect when the block got evicted from memory -> disk and a new handle opened the same file (grabbing the data from disk).

The reason we removed disk persistence - for now - from preview 2 is due to us working on write streaming support (i.e, being able to edit huge files on the fly without downloading the entire file locally).
For that reason we decided to simplify our logic and focus on the simplest approach for now - and minimizing config options. This is also the reason we decided to go with a handle level caching approach. We may consider bringing back the option of filename based caching + max blocks (for read only modes) down the line (with read/write mode only  applicable with handle level caching)

As for setting max blocks vs handle limit and blocks per handle, it should still be reasonable in the context of handles as they are continuously opened and closed - so a small file would typically be opened and closed fairly quickly giving up that handle space to another - potentially larger - file.

With all that said **given your workload is opening fairly small files (~1GB) you can actually use the file cache instead which should be more optimal for your use case. The file cache simply downloads the file in its entirety to disk and all read/writes access it directly.**



Please continue providing us with feedback as it lets us know what future implementations we should consider :) we will make sure to answer you promptly!

**Comment by j-hudecek** [comment]
Hi Tamer, thanks again for the quick and comprehensive answer.
Do you have implementing disk-based cache on your roadmap? Will it return in a month, a year or never?
Or could you suggest any alternative for us? We started looking into blobfuse as an alternative to deploying to Azure (we can't use our security infrastructure there) or making a tunnel to Azure (that would not be acceptable for security reasons) 

We've tried the file caching first but moved away from it because: 
1/ some of the files are closer to 10GB and it would take ~20s to download them on our connection 
2/ Sometimes we need to read metadata from 100s of these 1GB (small, as you say) files, that would take way too long (and unnecessarily download tons of data) 
3/ Downloading large files all the time would reduce internet speed for everyone at our institute.

**Comment by tasherif-msft** [comment]
Your use case actually gives us great incentive to bring back support as soon as we can. I will discuss the exact timeline with my colleagues and get back you by early next week. I will keep this issue open in the meantime!

**Comment by tasherif-msft** [comment]
Hi @j-hudecek, we decided to ship this feature once again post GA (end of year). This gives us time to make sure our code is stable with the new write streaming features that are coming up. I will keep this issue open to track.

**Comment by vibhansa-msft** [comment]
In our next version 2.1.0, we will be launching our adaptive prefetch based read-only streaming component called "block-cache". This will have option to store the streamed data locally for some time for high throughput in case of re-read by same or multiple handles.
