### ISSUE TITLE
Mouting via /etc/fstab using uid/gid does not work

### ISSUE THREAD

**Issue by mortenjoenby** [Azure/azure-storage-fuse#819]
### Which version of the blobfuse was used?
1.4.3

### Which OS (please include version) are you using?
CentOS 7.9 (and Oracle Linux)

### What problem was encountered?
We want to use blobfuse for Oracle RMAN backups. So I want to make the backup directory accessible to the oracle user only.
When mounting "manually" using the command line / script that works fine, but I want to use /etc/fstab which is at the root level.
When mounting via /etc/fstab, the filesystem (and tmp-path) is only visible and accessible as root _even_ when using the "-o uid=xxx -o gid=xxx" or setting these as mount options in fstab.

I am not sure if this is a bug or intended behavior, but if it's the last, then please tell me how to achieve what I am trying to do.
"-o allow_other" is of course an option, but that allows everyone to see it.

Permissions on tmp-path (using Azure tmp disk on /mnt):
[root@demo-lwdb-step-db-1 ~]# ls -l /mnt/blobfuseimmutable/
total 4
drwxrwx---. 2 root root 4096 Jun 20 09:34 root

### Have you found a mitigation/solution?
Only by using "-o allow_other".

### If relevant, please share your mount command.
Mount script:
#!/bin/bash
BLOBFS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#cd $BLOBFS_DIR/build
blobfuse $1 --tmp-path=/mnt/blobfuseimmutable --use-attr-cache=true -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o uid=501 -o gid=501 --config-file=/home/oracle/blobfuse/blobfuseImmutableStorage.cfg --ignore-open-flags=true --log-level=LOG_INFO

**Comment by souravgupta-msft** [comment]
The default permission that we have for the mounted directory is 0770. If you want other users to do operations in the mounted directory, the only option we support is using the allow_other flag. 
If you want the mounted directory to be accessible only from your non-root user, you will have to run mount command as that user.

From your root user, try adding these flags in mount command, -o umask=003 -o default_permissions
Let us know if this works for you.

**Comment by gapra-msft** [comment]
Hi @mortenjoenby, As another option, if you would like to mount as another user, you could explore this option https://github.com/libfuse/libfuse/issues/144#issuecomment-280940790 as a workaround.

**Comment by gapra-msft** [comment]
Hi @mortenjoenby Could you please share how you validated that s3fuse supports uid+gid? 

My understanding is that the -o uid, gid params are simply to override the field set by the filesystem. Beyond this, even when I set these parameters, and perform filesystem calls as the uid user that did not mount blobfuse, I see no calls from libfuse to blobfuse. In other words, it seems like the filesystem/libfuse is making the permission denied determination, so there is nothing blobfuse can do to service the calls.

**Comment by gapra-msft** [comment]
Since there has been no update in a couple weeks, I will go ahead and close this issue. There seems to be a limit from the libfuse end on supporting this. If you have any further questions, feel free to continue the thread here.
