### ISSUE TITLE
Second mount throws errror

### ISSUE THREAD

**Issue by mkiernan** [Azure/azure-storage-fuse#82]
I have a server with a blob container mounted already; when I try to mount another one, using a second temp directory, it throws the following error: 

[cycleadmin@cycleserver BlobFUSE]$ blobfuse /mnt/hpcpoc/ --temp-path=/mnt/resource/blobfusetemphpc  --file-cache-timeout-in-seconds=120 --config-file=./hpcpoc.cfg
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted

Is it not supported to have two mounts on the same system ?

**Comment by seguler** [comment]
It is because you use temp-path instead of tmp-path. This happens to many; we should recognize and throw a better error. Sorry about that.

**Comment by mkiernan** [comment]
got it. whoops. So to be clear this is caused by a typo in the command line option: --temp-path instead of --tmp-path.
