### ISSUE TITLE
RFE: symbolic link support

### ISSUE THREAD

**Issue by mkiernan** [Azure/azure-storage-fuse#83]
Many of the datasets I'm interacting with use symbolic links heavily, and I'm unable to copy these datasets to the blob storage mount. I realize there are probably many constraints with translating posix to blob - is it going to be possible at all to add symbolic link support ?

**Comment by seguler** [comment]
I think this is doable. We need to implement logic to mark a blob as symlink... perhaps we can mark these blobs with metadata symlink=true. @AlexanderYukhanov @asorrin-msft what do you think ?

**Comment by AlexanderYukhanov** [comment]
but what if symlink links to a file located on another filesystem?

**Comment by seguler** [comment]
We should do it same as NFS does. I believe these soft symlinks are just path pointers, and allows cross device paths as well

**Comment by AlexanderYukhanov** [comment]
but would not it be confused to customers?

**Comment by sivagms** [comment]
+1 for this feature. please.

**Comment by genloz** [comment]
+1 this would be very helpful, thanks!

**Comment by krezreb** [comment]
+1 for this feature. please.

**Comment by vibhansa-msft** [comment]
symlink support has been added in version 1.3.1
