### ISSUE TITLE
[package install request]upgrade to blobfuse 1.4.4 on Mariner OS

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#834]
### Which version of the blobfuse was used?

We want to support blob csi driver on Mariner OS, while we found that the latest package version on Mariner OS is still 1.3.6 which is too old, would you add 1.4.4 on Mariner OS package? thanks.
```
root@aks-mariner-32162698-vmss000000 [ / ]# blobfuse -v
blobfuse 1.3.6
root@aks-mariner-32162698-vmss000000 [ / ]# uname -a
Linux aks-mariner-32162698-vmss000000 5.10.117.1-2.cm1 #1 SMP Thu Jun 9 05:20:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vibhansa-msft** [comment]
Blobfuse binary has never been published for Mariner OS so far. Even 1.3.6 was not published by blobfuse team.
We have taken up Mariner as a supported OS for 'blobfuse2'.

**Comment by vibhansa-msft** [comment]
Closing this as from blobfuse end we do not officially release for Mariner
