### ISSUE TITLE
Segmentation fault occurs when trying to mount container by running blobfuse.

### ISSUE THREAD

**Issue by kitoyomi** [Azure/azure-storage-fuse#836]
### Which version of the blobfuse was used?

$ blobfuse --version
blobfuse 1.4.4
$

### Which OS (please include version) are you using?

$ uname -s -r -v -p -o -i
Linux 4.14.248-189.473.amzn2.x86_64 #1 SMP Mon Sep 27 05:52:26 UTC 2021 x86_64 x86_64 GNU/Linux
$

### What problem was encountered?

Segmentation fault.

When I create an instance in aws and run blobfuse on the created instance, I get a segmentation fault.

No segmentation fault occurs when I run blobfuse on an instance created 3 months ago with the same instance type, same OS, and same configuration.

### Have you found a mitigation/solution?

No.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

blobfuse[17077]: Using syscall to detect directory is already mounted or not
blobfuse[17077]: Setting logging level to : LOG_WARNING
kernel: blobfuse[17077]: segfault at 7fd21fa5df37 ip 00007fd21c5ca278 sp 00007ffe3f0c8f20 error 4 in libboost_filesystem-mt.so.1.53.0[7fd21c5bc000+13000]

### If relevant, please share your mount command.

sudo blobfuse /var/Data --tmp-path=/mnt/resource/blobfusetmp_01  --config-file=/var/etc/fuse_connection_01.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o gid=1001 -o allow_other

**Comment by souravgupta-msft** [comment]
Kindly set the log level to debug and share the logs. For enabling debug level logs, add this to your mount command, **--log-level=LOG_DEBUG**.

If possible, create a core dump and share it as well. 

You mentioned that no segmentation fault occurs when blobfuse is run on the instance created 3 months ago. Which version of blobfuse you are running in that instance? If it is not 1.4.4, try running 1.4.4 on that instance and see if you are getting the same error.

**Comment by souravgupta-msft** [comment]
We have neither tested nor do we release officially for this distro, Linux 4.14.248-189.473.amzn2.x86_64.
Can you share which rpm you are using for blobfuse here?

**Comment by kitoyomi** [comment]
Thanks for the reply.

I installed blobfuse 1.4.4 on an instance created 3 months ago.

I installed blobfuse with the following command line

```
$ sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
$ sudo yum install blobfuse
```
The yum output shows that the repository is "packages-microsoft-com-prod"
The rpm file name looks like "blobfuse-1.4.4-CentOS-7.0-x86_64.rpm".

Where is the log output if I add "--log-level=LOG_DEBUG"?" The following is output in "/var/log/messages".

```
Jul 14 06:12:31 ip-172-31-19-220 blobfuse[18319]: Using syscall to detect directory is already mounted or not
Jul 14 06:12:31 ip-172-31-19-220 blobfuse[18319]: Setting logging level to : LOG_DEBUG
Jul 14 06:12:31 ip-172-31-19-220 kernel: blobfuse[18319]: segfault at 7ff5f2852f77 ip 00007ff5f105b278 sp 00007ffe65513190 error 4 in libboost_filesystem-mt.so.1.53.0[7ff5f104d000+13000]
```

regards.

**Comment by souravgupta-msft** [comment]
@kitoyomi, can you try building the blobfuse binary by cloning the repo. You can run the following commands.

For setup,
```
sudo apt-get install pkg-config cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev libboost-all-dev gcc g++ -y
sudo apt-get install libfuse-dev -y
```

For building the blobfuse binary,
```
git clone https://github.com/Azure/azure-storage-fuse.git
cd azure-storage-fuse
./build.sh
```

Run the blobfuse mount command,
```
sudo ./build/blobfuse /var/Data --tmp-path=/mnt/resource/blobfusetmp_01 --config-file=/var/etc/fuse_connection_01.cfg --log-level=LOG_DEBUG -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o gid=1001 -o allow_other
```

Coming to the part for the logs, you are correct. The logs will be stored in the "/var/logs/messages".

**Comment by kitoyomi** [comment]
@souravgupta-msft 

Thanks for the presentation on how to create a blobfuse from a source code compilation.

I was able to mount the container by using the blobfuse created from the source code.

The contents of /var/log/messages are as follows

```
Jul 20 01:33:33 ip-172-31-19-220 blobfuse[25775]: Using syscall to detect directory is already mounted or not
Jul 20 01:33:33 ip-172-31-19-220 blobfuse[25775]: Setting logging level to : LOG_DEBUG
Jul 20 01:33:33 ip-172-31-19-220 blobfuse[25775]: Disk Thresholds : 90 - 80, Cache Eviction : 1000-0, List Cancel time : 0 Retry Policy (0, 60.000000, 1.200000), Background Download 0, Evict on sync 0
Jul 20 01:33:33 ip-172-31-19-220 blobfuse[25775]: Blobfuse version : 1.4.4
Jul 20 01:33:33 ip-172-31-19-220 blobfuse[25775]: release is 4.140000, Kernel version is 4.14.248-189.473.amzn2.x86_64
Jul 20 01:33:33 ip-172-31-19-220 blobfuse[25775]: CURL Version is 7.79.1
```

**Comment by souravgupta-msft** [comment]
Thanks for the confirmation. I am closing this issue since the option suggested above resolves it.
