### ISSUE TITLE
Invalid storage account types should be rejected

### ISSUE THREAD

**Issue by mkiernan** [Azure/azure-storage-fuse#84]
This is very low priority, but just wanted to document it. So I mistakenly attempted to mount a general purpose storage account v2 container. It all works, but then I couldn't work out why 'mkdir' was failing. Perhaps there is a way to check whether the storage account is of type blob, and if not reject it with an error.

**Comment by seguler** [comment]
GPV2 account should work fine. Did you mean you tried to use a premium storage account which won't support block blobs ?
