### ISSUE TITLE
--cache-size-mb results in intermittent broken caching

### ISSUE THREAD

**Issue by ocoleman-cordel** [Azure/azure-storage-fuse#853]
### Which version of the blobfuse was used?
1.4.4

### Which OS (please include version) are you using?
Host: Ubuntu 18.04
Docker container: Ubuntu 20.04

### What problem was encountered?
When --cache-size-mb is set we see an intermittent fault where after several hours (anything from 1 to 5+ hours) most of the cache files disappear and are not repopulated, and every file read access appears to invoke a GET request to the blob container.

We first noticed the issue when our storage bill suddenly became ~5 times the usual. Looking at the plots of container requests we see that they went from perhaps 1000 per hour to 500,000 per hour, specifically blob GET requests. Stopping the process that was requesting file reads immediately stopped the requests (the process is machine learning training jobs, making requests for image and other files located in blob storage).

We monitored the cache using repeated calls to `du -sh *` in the cache folder being used by blobfuse. Initially we saw the cache being populated with the expected files. These files would persist for several hours. When the fault occurs most of these files would be removed, including the ones being frequently accessed by the ML training process, and the extreme number of blob GET requests would begin.

We removed most options from the blobfuse mount command and found that the issue did not occur after several days, over multiple invocations of the blobfuse mount command. We re-introduced options one-by-one and re-tested. When the --cache-size-mb option was re-introduced the problem re-appeared.

### Have you found a mitigation/solution?

Yes, removing the --cache-size-mb option, however this is not a good long-term solution as the local disk eventually fills up resulting in system instability.

### If relevant, please share your mount command.
blobfuse /workspace/data --container-name="..." --use-https=true -o allow_other --tmp-path=/workspace/temp/blobfusecache/axml_server --use-attr-cache=true --cache-size-mb=10000 --file-cache-timeout-in-seconds=86400

**Comment by vibhansa-msft** [comment]
I see in your mount command you have "--file-cache-timeout-in-seconds=86400". This means any file downloaded by blobfuse will persist on local cache for 24 hours. Any file that is not modified in this 24hr time slot will be removed after the timer expires. Any file modified will stay for 24 hours from its last modified time. This explains why you see initially cache is empty and lot of files pile up which exists for long duration (~24 hours shall be the time).

Once timer expires these files will be wiped out and later when you try to open the file (for read/write) they will be downloaded again. While setting "--cache-size-mb" you need to consider this 24 hour window and see whether all required files can fit in that or not. If you want to conserve your disk-space then you can set a lower file-cache-timeout (expiring the files early).

Other than this, blobfuse also keep monitoring the local disk usage. If usage goes to 90% of the disk capacity, then it will start removing files from local disk to make more space available. As you have configured "--cache-size-mb", 90% is what will be marked as high threshold and until disk usage reaches below 80% it will keep deleting. One point here is only files for which no handle is open are eligible for deletion.

"the extreme number of blob GET requests would begin.": if required file is not in local cache then blobfuse is doing this to download the file to local-cache, which is expected. There are no files downloaded/uploaded by blobfuse on its own, only when user application requests to open a file its downloaded and on close if file was modified it will be uploaded. You may need to check your application behavior here to validate this.

**Comment by ocoleman-cordel** [comment]
The 24 hour cache time is intentional: all files accessed are quite static, the only changes that occur are creation of new files.

We have not reached 90% of the disk capacity.

Does the blobfuse cache algorithm keep files based on frequency of access and/or time since last access? If not, perhaps once the cache reaches 10GB the frequently accessed files are being discarded and not cached again on subsequent accesses.

The training process creates large files that are also stored in the same container. These end up in the cache (not unexpected), but they are never accessed by the process again. If these large files are "pushing out" the frequently accessed files from the cache, despite never actually being read, it would explain the behaviour we're seeing. However this would seem like sub-optimal behaviour for a caching system?

**Comment by vibhansa-msft** [comment]
Whenever a file is closed, blobfuse notes the time and expiry is calculated from that time (24 hours after last close). So blobfuse does take care of last accessed file in that sense. However, if the disk utilization hits the high threshold, then this is ignored and whatever file is closed is attempted for eviction. Here you may see file being closed by application and immediately removed by blobfuse to free up cache space.  If there are large number of files already cached and application is creating more and more new files, then you are likely to hit this situation.

**Comment by vibhansa-msft** [comment]
By disk usage I mean, if disk-cache-size is not configured then entire disk size is considered, but if that config is provided and 90% of the configured size is considered a mark for force eviction.

**Comment by vibhansa-msft** [comment]
"We first noticed the issue when our storage bill suddenly became ~5 times the usual.": Can you share what configuration was changed that triggered this. When you say "then usual" just wanted to understand what the benchmark was here for comparison.

**Comment by vibhansa-msft** [comment]
One more point to add to our eviction logic, whenever a file is closed, we take that timestamp, and these are pushed as an entry for eviction. So, it might happen that file was used 24 hrs. before and just 2 min back, still file will get evicted based on the first event that says it was closed 24 hours back once.
We are working on next generation of blobfuse called "blobfuse2" (in preview mode as of now) and that has better eviction policies. If you wish you give it a try, you can get the binary from this link : https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2
Blobfuse2 has different cli and config model so you can refer our readme @ https://github.com/Azure/azure-storage-fuse/tree/main#readme

**Comment by vibhansa-msft** [comment]
@ocoleman-cordel: Will you be able to give blobfuse2 a try?

**Comment by ocoleman-cordel** [comment]
"Can you share what configuration was changed that triggered this"
The config that changes was adding the --cache-size-mb option. I can still reproduce the problem behaviour by simply adding or removing this option.

Is blobfuse2 considered stable?

**Comment by vibhansa-msft** [comment]
"--cache-size-mb" is causing an early eviction in files as cache size is limited now. When it's not provided, blobfuse considers entire free disk space is at its disposal. 
For you query on "blobfise2" aka v2, it has better eviction logic compared to "blobfuse" aka v1. V2 is in preview mode as of now, however we do support customers trying it out. We have not found any major issue in v2 so far and feature wise v2 is feature-rich compared to v1, refer to README for more details. There is also a migration guide which assist you in moving from v1 to v2.

**Comment by vibhansa-msft** [comment]
Were you able to give v2 a try?

**Comment by ocoleman-cordel** [comment]
I'll give v2 a go over the next few days

**Comment by ocoleman-cordel** [comment]
I've been unable to get v2 to work, posted an issue: https://github.com/Azure/azure-storage-fuse/issues/864

**Comment by vibhansa-msft** [comment]
#864 is closed as it was confirmed that it's working. Closing this as caching in v1 is working as per design and as mentioned above v2 has better caching algorithm and performance. Feel free to create new item if you have any further queries in this regard.
