### ISSUE TITLE
BFSMountError: Unable to mount blob fuse file system

### ISSUE THREAD

**Issue by iddqdiddqd** [Azure/azure-storage-fuse#862]
### Which version of the blobfuse was used?
I do not install blobfuse explicitly as well as it's not being displayed in `pip install` logs.

### Which OS (please include version) are you using?
Ubuntu 22.04 & Ubuntu 20.04.4

### What problem was encountered?
I am submitting a job to ML workspace via Azure CLI. The compute target for the job is STANDARD_NC6 AML compute.

The job was being executed successfully for a couple of weeks already. The last successful run was ~19 hours ago. ~1.5 hr ago I started receiving the following error message ~5-10 seconds after submitting the job to AML compute:
```
AzureMLCompute job failed.
BFSMountError: Unable to mount blob fuse file system
	Info: Selected VM image doesn't support containers mounting
	Info: Failed to setup runtime for job execution: Job environment preparation failed on 10.0.0.4 with err exit status 1.
```

### Have you found a mitigation/solution?
Switching to STANDARD_DS12_V2 resolved the issue.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No logs (except the one from above) are available for such the failed jobs.

**Comment by vibhansa-msft** [comment]
blobfuse is not officially supported on Ubuntu-22. Ubn-20 is supported even with the containers.

**Comment by vibhansa-msft** [comment]
@andyzhangx : can you help providing some steps on what we need to do to mount it on container.

**Comment by andyzhangx** [comment]
We have a CSI driver solution for mounting blob storage on a k8s cluster: https://github.com/kubernetes-sigs/blob-csi-driver
Per the above context, I think AML compute is mounting blobfuse inside container, that's different scenario.

**Comment by paulamaranon** [comment]
Same situation here. Two days ago gpu  STANDARD_NC6  stop working.

AzureMLCompute job failed.
BFSMountError: Unable to mount blob fuse file system
	Info: Selected VM image doesn't support containers mounting
	Info: Failed to setup runtime for job execution: Job environment preparation failed on 10.0.0.4 with err exit status 1.

**Comment by vibhansa-msft** [comment]
Was this working earlier and now has stopped working or this is some new scenario?

**Comment by vibhansa-msft** [comment]
You can check if this thread helps. There are some sample config files posted in this thread regarding containers: https://github.com/Azure/azure-storage-fuse/issues/250

**Comment by paulamaranon** [comment]
It was working before. I dont use blob use in my dependencies.  it is failing with  STANDARD_NC6, CPU it is working ok.

**Comment by ad2354** [comment]
I'm facing the same problem with STANDARD_NC6,
**AzureMLCompute job failed.**
BFSMountError: Unable to mount blob fuse file system
	Info: Selected VM image doesn't support containers mounting
	Info: Failed to setup runtime for job execution: Job environment preparation failed on 10.0.0.4 with err exit status 1.

**Comment by iddqdiddqd** [comment]
> Was this working earlier and now has stopped working or this is some new scenario?
It was working before Aug 11 on GPU AML instances. STANDARD_NC6 to be precise.

The execution script, pip dependencies & conda environments remained the same for about 2 months.

**Comment by iddqdiddqd** [comment]
It seems to me like storage fuse is included in the base conda environment that GPU AML instances utilize. And some update had been published for either storage fuze or that base conda env prior the things got broken for users above including myself.

**Comment by vibhansa-msft** [comment]
Post June we have not posted any new release for blobfuse. Latest release was done just 8 days back. Can you check what blobfuse version you have in your envrionment.

**Comment by iddqdiddqd** [comment]
@vibhansa-msft , I do not set blobfuse manually as a dependency for my env neither I use it in the code. I think that it's being used by AML under the hood. So I cannot see any logs with blobfuse installation during my custom ML env docker build stage.

**Comment by ad2354** [comment]
blobfuse  Version: 1.4.4
I'm trying to run a AutoML job for Image classification task and, as @iddqdiddqd mentioned there are no blobfuse logs when the job is executed.

**Comment by XavierGeerinck** [comment]
Same issue here, any idea on how to resolve this? It's when submitting the experiment

**Comment by vibhansa-msft** [comment]
"BFSMountError: Unable to mount blob fuse file system" is pointing towards some issue with fuse driver itself where we are not able to mount. As blobfuse is not mounted we may not get any logs. Our best bet is to try manually mount blobfuse on the system and see system logs if they point to the root-cause. Also, if you are able to mount it manually then mount with "-d" cli option that shall give us libfuse logs as well.

**Comment by XavierGeerinck** [comment]
@vibhansa-msft could you provide some more details on how to do so? As currently I am just running an experiment as a Python script where it already fails.

**Comment by ad2354** [comment]
I'm able to run jobs from my end now

**Comment by vibhansa-msft** [comment]
@ad2354: Can you please share what resolved the issue for you. Might be helpful to other users as well.
Also, for those mounting blobfuse inside a container you can follow another thread #864, a blog has been shared there on what options to use while creating your container.

**Comment by deruyvero** [comment]
I am facing the same issue when trying to run a pipeline in Azure ml (on a GPU compute). Using the .as_mount() method to mount a DataSet that is being used a input in the first stage of the Azure ML pipeline. This used to work. Are there already any ideas on how this could be solved?

**Comment by vibhansa-msft** [comment]
@ad2354: Kindly share your resolution steps. It appears there are many hitting this issue now.
From blobfuse end, we have not released any update for the containers as such and last few releases have been only about some bug fixes. This might have broken from the AML workspace side. If anyone has found the workaround, do share it in this thread.

**Comment by Barmin93** [comment]
Having the exact same issue. Training pipeline stopped working like 10-12 days ago on STANDARD_NC6. Trying to fix it ever since. Any one have any further clue?

PS. Changing from GPU image to CPU image is not a solution (mentioned in first comment, that author changed to STANDARD_DS12_V2).

**Comment by vibhansa-msft** [comment]
When you say it stopped working 10-12 days ago, can you share what has changed. From blobfuse end we have not done any such change. Also, in this thread earlier it was shared that blobfuse version is 1.4.4 in such environment, which is a couple of month old binary. 
By any chance has fuse library version or integration is impacted due to some other change in the system?

**Comment by Barmin93** [comment]
It's really hard to say. It is a production training pipeline. We didn't introduce any changes into it for a long time. Few days ago it just stopped working. Firstly, it stopped working because of newest version of PIP, that couldn't install packages requirements (some problem with python dependency resolver). We downgraded it and I see this error `BFSMountError: Unable to mount blob fuse file system`. I have no idea how downgrading pip could change anything on the AzureML side. It shouldn't. 

Also, we didn't introduce any changes into training flow, AzureML image etc. It's the same for last 12 months (at least).

**Comment by iddqdiddqd** [comment]
@vibhansa-msft it'd be better to make AML guys to take a look at this since blob fuse (according to all the reporters) is used by AML under the hood with no custom interaction, don't you think? Or maybe you can cross-reference this issue in an appropriate repository.

**Comment by moriyoshi** [comment]
Not a MSFT person, but I have identified the process that writes the error message in question to the log file, and did the comparison between the VMs.

* VM with successful runs:
    * DS1v2
    * Ubuntu 20.04
    * SHA256 sums of the executables xnd configuration files involved:
        ```
        899bc0ead6ca6734d52c7757764c93164685660763558b2e221f0625f6b10350  /opt/batch/bin/node_agent
        43c7c39411b01ca4e43e903a055dcebc267c091dcad9f296da1d5f930cbdccae  /opt/batch/config/azbatchconf.json
        d8a529bcc897230f5431e40cc9a93ea6ba8f15e20634abdbcd38517d62e75424  /opt/batch/config/dynamicconf.json
        ```
     * `/dev/sda1` mounted as `/`, `/dev/sdb1` mounted as `/mnt`
* VM with jobs ending with BFSMountError:
     * NC4asT4v3
     * Ubuntu 20.04
     * SHA256 sums of the executables xnd configuration files involved: 
         ```
         899bc0ead6ca6734d52c7757764c93164685660763558b2e221f0625f6b10350  /opt/batch/bin/node_agent
         43c7c39411b01ca4e43e903a055dcebc267c091dcad9f296da1d5f930cbdccae  /opt/batch/config/azbatchconf.json
         d8a529bcc897230f5431e40cc9a93ea6ba8f15e20634abdbcd38517d62e75424  /opt/batch/config/dynamicconf.json
         ```
     * `/dev/sda1` mounted as `/mnt`, `/dev/sdb1` mounted as `/`

I didn't see any notable difference except for the CPU architecture and block devices.

**Comment by XavierGeerinck** [comment]
I think it has something to do with the standard images on Azure ML. I am using my own container now and I manually mount blob fuse and that works for me

**Comment by Barmin93** [comment]
@XavierGeerinck what do you mean by "my own container"? You create custom VM image on your own machine (not using the AzureML images)?

**Comment by XavierGeerinck** [comment]
I create custom containers that I run on the VM (https://xaviergeerinck.com/2022/08/23/utilizing-your-dataset-from-blob-storage-with-azure-ml/) I find it easier and I have more control. Disadvantage is that I still need to figure out how to correctly start monitoring them from the Job window as currently I just run them in the Terminal

Tbh AML has a lot of work to do I feel in documenting custom training with a user specific dataset. Currently, I'm working on a blog series and I will tackle it there :)

**Comment by vibhansa-msft** [comment]
We are trying to reach out to AML team to understand if there was a change from their end which might have caused this failure.

**Comment by moriyoshi** [comment]
As I mentioned in the (edited) above comment, running blobfuse manually from the command line works equally for both (successful and failing) instances, and this I guess further reinforces the idea this is a AML problem.

**Comment by vibhansa-msft** [comment]
We had a discussion with the AML team. As per their update, they are aware of this issue and fix is already rolling out.

**Comment by moriyoshi** [comment]
Just confirmed it was working flawlessly. You folks are awesome.

**Comment by vibhansa-msft** [comment]
Can someone in the thread confirm that its working fine post AML workspace update?

**Comment by deruyvero** [comment]
For me it now works again. Thanks for the help!

**Comment by iddqdiddqd** [comment]
@vibhansa-msft I confirm that the issue is resolved now. I've switched back to `STANDARD_NC6` AML compute and see no errors during ML job execution. All jobs passed successfully. Shout out to AML & Storage Fuse teams.
