### ISSUE TITLE
Limit file cache size

### ISSUE THREAD

**Issue by asorrin-msft** [Azure/azure-storage-fuse#87]
blobfuse assumes there is enough disk space for the file cache.  If disk space is exhausted, operations may fail in mysterious ways.  We should at minimum detect this and error out intelligently, or (better) GC some items in the cache until there's enough space.

**Comment by Tatsinnit** [comment]
👍 for this bug 

💡  Note: please also update `min` or `max` limit (if there is any) in the documentation here: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux#optional-use-a-ramdisk-for-the-temporary-path

**Comment by syagev** [comment]
One of the points of having a network (e.g. "blob") storage is for storing big amounts of data that don't fit on local disks... I think this issue deserves more attention.

I'm using Premium Blobs to store datasets for deep-learning. This means my worker-nodes are iterating the entire storage. It's therefore quite critical that the cache is elegantly cleaned up every now and then.

**Comment by vibhansa-msft** [comment]
--cache-size-mb command line parameter can be used to control the amount of cache. Kindly refer to README. This is available version 1.3.1 onwards.

**Comment by j-baron** [comment]
Hi, thank you for the quick reply, I updated to 1.3.6 but its still ignoring the flag and using much more than it is meant to, when I set the flag to:  - --cache-size-mb=6000 I still see usage for prometheus running of more than 18GB on the node on the /mnt. This is three times more than the expected figure. Thank you
