### ISSUE TITLE
cannot install blobfuse2 in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-storage-fuse#878]
### Which version of the blobfuse was used?
Note: If you are using blobfuse 1.X.X, we would like to encourage you to try out the next generation of blobfuse, [blobfuse2](https://github.com/Azure/azure-storage-fuse/tree/main) which is currently in preview. The latest preview binaries can be found [here](https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2) and more information on how to convert config options can be found [here](https://github.com/Azure/azure-storage-fuse/blob/main/MIGRATION.md#blobfuse-v2-guide-for-mapping-options-from-v1xx-to-v2xx). We will continue to respond to bug reports for blobfuse 1.X.X, however, no more feature requests will be considered.

### Which OS (please include version) are you using?
Ubuntu 22.04 LTS

### What problem was encountered?

`apt install blobfuse2` failed (cannot get blobfuse2 package) with https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb, while it works with https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb

```
wget -O /tmp/packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
sudo dpkg -i /tmp/packages-microsoft-prod.deb
sudo apt update
sudo apt install blobfuse2
```

### Have you found a mitigation/solution?
use 20.04 deb path works, while we would like to get https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb since AKS would only use this deb path for all packages install in Ubuntu 22.04 image.

**Comment by vibhansa-msft** [comment]
Yes Andy, I see preview-2 was not released for Ubn-22. I checked and I see we have added Ubn-22 support post preview-2. Our preview-3 binary will be officially released on ubn-22 as well.

**Comment by vibhansa-msft** [comment]
We are about to release blobfuse2-preview-3 in a day or two and it will be officially released for ubuntu-22 as well.
Closing this issue here. Feel free to post your queries here or open another item, if you see any other issue on this topic.

**Comment by andyzhangx** [comment]
@vibhansa-msft I see blobfuse2 is still not updated in https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb, do you know when it would be available? thanks.

**Comment by vibhansa-msft** [comment]
@andyzhangx : We had some issue with updating ubn-22 repo so it's not available as of now. We are working on uploading the bits there.

**Comment by gapra-msft** [comment]
Hi @andyzhangx The Ubuntu 22 package should be available now https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/b/blobfuse2/

**Comment by andyzhangx** [comment]
@gapra-msft thanks, it works now
