### ISSUE TITLE
errors when building on PI 

### ISSUE THREAD

**Issue by Anuj79** [Azure/azure-storage-fuse#879]
### Which version of the blobfuse was used? 2
Note: If you are using blobfuse 1.X.X, we would like to encourage you to try out the next generation of blobfuse, [blobfuse2](https://github.com/Azure/azure-storage-fuse/tree/main) which is currently in preview. The latest preview binaries can be found [here](https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2) and more information on how to convert config options can be found [here](https://github.com/Azure/azure-storage-fuse/blob/main/MIGRATION.md#blobfuse-v2-guide-for-mapping-options-from-v1xx-to-v2xx). We will continue to respond to bug reports for blobfuse 1.X.X, however, no more feature requests will be considered.

### Which OS (please include version) are you using?
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

### What problem was encountered?
errors while bulding the code

### If relevant, please share your mount command.
these are the errors while building the code on pi. 

go version go1.19 linux/arm

pi@raspberrypi:~/Documents/bobfuse2/azure-storage-fuse $ ./build.sh 
# github.com/Azure/azure-storage-fuse/v2/component/file_cache
component/file_cache/file_cache.go:413:20: cannot use stat.Mtim.Sec (variable of type int32) as type int64 in argument to time.Unix
component/file_cache/file_cache.go:413:35: cannot use stat.Mtim.Nsec (variable of type int32) as type int64 in argument to time.Unix
component/file_cache/file_cache.go:414:20: cannot use stat.Atim.Sec (variable of type int32) as type int64 in argument to time.Unix
component/file_cache/file_cache.go:414:35: cannot use stat.Atim.Nsec (variable of type int32) as type int64 in argument to time.Unix
component/file_cache/file_cache.go:415:20: cannot use stat.Ctim.Sec (variable of type int32) as type int64 in argument to time.Unix
component/file_cache/file_cache.go:415:35: cannot use stat.Ctim.Nsec (variable of type int32) as type int64 in argument to time.Unix
component/file_cache/file_cache.go:732:25: cannot use stat.Ctim.Sec (variable of type int32) as type int64 in argument to time.Unix
component/file_cache/file_cache.go:732:40: cannot use stat.Ctim.Nsec (variable of type int32) as type int64 in argument to time.Unix
# github.com/Azure/azure-storage-fuse/v2/component/azstorage
component/azstorage/config.go:242:83: cannot use azblob.BlockBlobMaxStageBlockBytes (untyped int constant 4194304000) as int value in argument to log.Err (overflows)
# github.com/Azure/azure-storage-fuse/v2/component/libfuse
In file included from component/libfuse/libfuse_wrapper.h:57,
                 from libfuse_handler.go:43,
                 from _cgo_export.c:4:
component/libfuse/native_file_io.h: In function ‘release_native_file_object’:
component/libfuse/native_file_io.h:69:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   69 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
component/libfuse/native_file_io.h: In function ‘native_read_file’:
component/libfuse/native_file_io.h:119:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  119 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
component/libfuse/native_file_io.h: In function ‘native_write_file’:
component/libfuse/native_file_io.h:134:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  134 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
component/libfuse/native_file_io.h: In function ‘native_flush_file’:
component/libfuse/native_file_io.h:149:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  149 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
# github.com/Azure/azure-storage-fuse/v2/component/libfuse
In file included from component/libfuse/libfuse_wrapper.h:57,
                 from component/libfuse/libfuse_handler.go:43:
component/libfuse/native_file_io.h: In function ‘release_native_file_object’:
component/libfuse/native_file_io.h:69:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   69 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
component/libfuse/native_file_io.h: In function ‘native_read_file’:
component/libfuse/native_file_io.h:119:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  119 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
component/libfuse/native_file_io.h: In function ‘native_write_file’:
component/libfuse/native_file_io.h:134:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  134 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
component/libfuse/native_file_io.h: In function ‘native_flush_file’:
component/libfuse/native_file_io.h:149:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  149 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
# github.com/Azure/azure-storage-fuse/v2/component/libfuse
In file included from component/libfuse/libfuse_wrapper.h:57,
                 from component/libfuse/libfuse_handler_test_wrapper.go:40:
component/libfuse/native_file_io.h: In function ‘release_native_file_object’:
component/libfuse/native_file_io.h:69:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   69 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
component/libfuse/native_file_io.h: In function ‘native_read_file’:
component/libfuse/native_file_io.h:119:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  119 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
component/libfuse/native_file_io.h: In function ‘native_write_file’:
component/libfuse/native_file_io.h:134:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  134 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
component/libfuse/native_file_io.h: In function ‘native_flush_file’:
component/libfuse/native_file_io.h:149:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  149 |     file_handle_t* handle_obj = (file_handle_t*)fi->fh;
      |                                 ^
# github.com/Azure/azure-storage-fuse/v2/component/libfuse
component/libfuse/libfuse_handler.go:311:21: cannot use _Ctype_long(attr.Size) (value of type _Ctype_long) as type _Ctype_longlong in assignment
component/libfuse/libfuse_handler.go:426:10: cannot use _Ctype_ulong(uintptr(unsafe.Pointer(handle))) (value of type _Ctype_ulong) as type _Ctype_ulonglong in assignment
component/libfuse/libfuse_handler.go:499:55: cannot use idx + 1 (value of type _Ctype_long) as type _Ctype_longlong in variable declaration
component/libfuse/libfuse_handler.go:556:21: cannot use _Ctype_ulong(attr.Blocks) (value of type _Ctype_ulong) as type _Ctype_ulonglong in assignment
component/libfuse/libfuse_handler.go:557:21: cannot use _Ctype_ulong(attr.Bavail) (value of type _Ctype_ulong) as type _Ctype_ulonglong in assignment
component/libfuse/libfuse_handler.go:558:20: cannot use _Ctype_ulong(attr.Bfree) (value of type _Ctype_ulong) as type _Ctype_ulonglong in assignment
component/libfuse/libfuse_handler.go:559:20: cannot use _Ctype_ulong(attr.Files) (value of type _Ctype_ulong) as type _Ctype_ulonglong in assignment
component/libfuse/libfuse_handler.go:560:20: cannot use _Ctype_ulong(attr.Ffree) (value of type _Ctype_ulong) as type _Ctype_ulonglong in assignment
component/libfuse/libfuse_handler.go:588:46: cannot use _Ctype_ulong(uintptr(unsafe.Pointer(handle))) (value of type _Ctype_ulong) as type _Ctype_ulonglong in argument to (_Cfunc_allocate_native_file_object)
component/libfuse/libfuse_handler.go:594:10: cannot use _Ctype_ulong(uintptr(unsafe.Pointer(ret_val))) (value of type _Ctype_ulong) as type _Ctype_ulonglong in assignment
component/libfuse/libfuse_handler.go:594:10: too many errors

**Comment by vibhansa-msft** [comment]
If this is an ARM platform, blobfuse does not support that as of now. Were you building legacy blobfuse on ARM earlier, or this is something new you are trying?

**Comment by Anuj79** [comment]
Yup it’s an ARM platform.  
Something new. Haven’t tried the earlier version.

**Comment by vibhansa-msft** [comment]
We have not tried building on ARM platform so far, so it might have issues.

**Comment by vibhansa-msft** [comment]
We will add this item to our backlog and support ARM platform sometime in future, if you are able to figure out the changes required to build on ARM, feel free to fire a PR here.

**Comment by Anuj79** [comment]
Sure. Thanks.

**Comment by vibhansa-msft** [comment]
We have added this to our backlog item, however it's not a high priority item for now. Closing this as we will track it separately.
Meanwhile, if you make it work on ARM, you can submit a PR for the same.
