### ISSUE TITLE
Doubt about MD5 validation

### ISSUE THREAD

**Issue by felipemoz** [Azure/azure-storage-fuse#882]
### Which version of the blobfuse was used?
Note: If you are using blobfuse 1.X.X, we would like to encourage you to try out the next generation of blobfuse, [blobfuse2](https://github.com/Azure/azure-storage-fuse/tree/main) which is currently in preview. The latest preview binaries can be found [here](https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2) and more information on how to convert config options can be found [here](https://github.com/Azure/azure-storage-fuse/blob/main/MIGRATION.md#blobfuse-v2-guide-for-mapping-options-from-v1xx-to-v2xx). We will continue to respond to bug reports for blobfuse 1.X.X, however, no more feature requests will be considered.

### Which OS (please include version) are you using?
RHEL 7

### What problem was encountered?
Uncomplete chunks, files corrupted between source (on prem) and storage account blob.

### Have you found a mitigation/solution?
Exporting MD5 from source and validation after pipeline copy

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
NA

### If relevant, please share your mount command.
NA

-- This is a feature request: Would be nice have a feature to validate chunks using MD5, specifically when you are copying files between mounts.

**Comment by felipemoz** [comment]
Another question: When this will achieve GA stage?

**Comment by vibhansa-msft** [comment]
We have the code to support MD5 sum complete, and it will be part of our preview-3 which shall most likely be released this week.

**Comment by vibhansa-msft** [comment]
"Uncomplete chunks, files corrupted between source (on prem) and storage account blob.": are you hitting this issue or just in such case you need md5 sum to help out.

**Comment by vibhansa-msft** [comment]
Can you confirm if you are facing any data corruption issue with blobfuse ?

**Comment by vibhansa-msft** [comment]
Ad MD5 sum set and compare have been added as a feature in v2, we will close this issue here. You can give our blobfuse2-preview3 a try and see if it works well for your test case or not. If the issue persists, you can open another thread here.
For legacy blobfuse we are not going to add md5 sum related features.
