### ISSUE TITLE
If the command of blobfuse2 is not supported, the cmd should return non-zero. 

### ISSUE THREAD

**Issue by cvvz** [Azure/azure-storage-fuse#892]
### Which version of the blobfuse was used?
blobfuse2

### What problem was encountered?
If the command of blobfuse2 is not supported, the cmd should return non-zero. 

### If relevant, please share your mount command.
![image](https://user-images.githubusercontent.com/44308864/188681732-5d34715d-1824-434c-bfad-b1fcea9f54cc.png)

**Comment by gapra-msft** [comment]
This issue should be resolved by #893, which was just merged. Closing this item.
