### ISSUE TITLE
blobfuse2 failed to mount when specify `AZURE_STORAGE_BLOB_ENDPOINT` explicitly

### ISSUE THREAD

**Issue by cvvz** [Azure/azure-storage-fuse#894]
### Which version of the blobfuse was used?
blobfuse2

### What problem was encountered?
blobfuse2 failed to mount when specify `AZURE_STORAGE_BLOB_ENDPOINT` explicitly, while blobfuse v1 can mount successfully.

### Have you found a mitigation/solution?
unset `AZURE_STORAGE_BLOB_ENDPOINT` or change the endpoint to `account.dfs.core.windows.net`

### If relevant, please share your mount command.
```shell
export AZURE_STORAGE_ACCESS_KEY=xxx
export AZURE_STORAGE_ACCOUNT=acount
export AZURE_STORAGE_BLOB_ENDPOINT=acount.blob.core.windows.net

blobfuse2 mount /test --cancel-list-on-mount-seconds=0 --file-cache-timeout-in-seconds=120 --use-adls=true -o allow_other --pre-mount-validate=true --use-https=true --empty-dir-check=false --tmp-path=/mnt/tmp-test --container-name=xxxx
failed to mount : failed to authenticate credentials for azstorage
```

**Comment by gapra-msft** [comment]
Resolved as the PR has been merged.
