### ISSUE TITLE
Blobfuse2 install issue on Ubuntu 20.04 - libfuse3.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by bnapora** [Azure/azure-storage-fuse#903]
### Which version of the blobfuse was used?
blobfuse2_2.0.0-preview.3_amd64.deb

### Which OS (please include version) are you using?
Ubuntu 20.04.4 LTS

### What problem was encountered?
$ blobfuse2 --help
blobfuse2: error while loading shared libraries: libfuse3.so.3: cannot open shared object file: No such file or directory

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No...nothing has been recorded to sys

### If relevant, please share your mount command.
Haven't gotten to mount command.  I followed instructions for blobfuse2 here:
https://github.com/Azure/azure-storage-fuse/blob/main/MIGRATION.md#blobfuse-v2-guide-for-mapping-options-from-v1xx-to-v2xx

Compute is a freshly instantiated Azure Container Instance - nothing has been updated or changed on the container prior to running the installation steps.

**Comment by gapra-msft** [comment]
Hi @bnapora, 

Thank you for reporting this issue. This looks like a docs issue. Could you please run `sudo apt-get install fuse3 blobfuse2`  instead?

**Comment by bnapora** [comment]
Thanks for the quick reply.  Yes, specifying fuse3 got it running.

**Comment by gapra-msft** [comment]
Thank you for verifying, linking the PR that will resolve this here https://github.com/Azure/azure-storage-fuse/pull/904
