### ISSUE TITLE
SAS token support

### ISSUE THREAD

**Issue by asorrin-msft** [Azure/azure-storage-fuse#91]
blobfuse should be able to mount with a SAS token, not just an account name + key.

**Comment by Tatsinnit** [comment]
+1 for this feature enhancement.

**Comment by seguler** [comment]
It's coming! @rickle-msft

**Comment by seguler** [comment]
Yay!!! #132 PR that adds the SAS support submitted :)

**Comment by seguler** [comment]
Support added in blobfuse 0.4 release
