### ISSUE TITLE
need blobfuse2 for ARM64 Ubuntu 22.04

### ISSUE THREAD

**Issue by chengliangli0918** [Azure/azure-storage-fuse#910]
### Which version of the blobfuse was used?
blobfuse2/jammy 2.0.0-preview.3

Note: If you are using blobfuse 1.X.X, we would like to encourage you to try out the next generation of blobfuse, [blobfuse2](https://github.com/Azure/azure-storage-fuse/tree/main) which is currently in preview. The latest preview binaries can be found [here](https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2) and more information on how to convert config options can be found [here](https://github.com/Azure/azure-storage-fuse/blob/main/MIGRATION.md#blobfuse-v2-guide-for-mapping-options-from-v1xx-to-v2xx). We will continue to respond to bug reports for blobfuse 1.X.X, however, no more feature requests will be considered.

### Which OS (please include version) are you using?
ARM64 Ubuntu 22.04

### What problem was encountered?
apt list | grep blobfuse2
blobfuse2/jammy 2.0.0-preview.3 **amd64**

uname -a
Linux 5.15.0-1017-azure #20-Ubuntu SMP Fri Aug 5 12:03:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Have you found a mitigation/solution?
no

**Comment by gapra-msft** [comment]
Hi @chengliangli0918 

We have added this to our backlog and will look into prioritizing it appropriately. 

In the meantime have you attempted to build [Blobfuse2 from source](https://learn.microsoft.com/en-us/azure/storage/blobs/blobfuse2-how-to-deploy#option-2-build-from-source) in your env?

**Comment by vibhansa-msft** [comment]
Closing this as we do not have this task on high priority for now. We have added an item to our backlog regarding the same.
If you were able to build it for ARM, feel free to put a PR for the changeset.
