### ISSUE TITLE
Blobfuse2 with System Assigned Managed Identity

### ISSUE THREAD

**Issue by tusharg1993** [Azure/azure-storage-fuse#912]
### Which version of the blobfuse was used?
blobfuse2

### Which OS (please include version) are you using?
Ubuntu 20.04

### What problem was encountered?
Does blobfuse2 support auth with System Assigned Managed Identity?
I gave VM's identity access to the storage account. But I am unsure how to use it with System Assigned Managed Identity. Please advise

**Comment by tusharg1993** [comment]
If I am understanding Azure docs correctly, it looks like the blobfuse2 process will need to hit IMDS url for the token. I see some examples at https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-go and https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity

**Comment by gapra-msft** [comment]
Hi @tusharg1993, Currently we support Azure AD managed identities only (application ID and resource ID). We are currently looking into the possibility of adding support for the System Assigned Managed Identity. We will be sure to update this Github issue as we get further in our investigation.

**Comment by tasherif-msft** [comment]
Hi @tusharg1993, I have put out a pr to support this in our next release https://github.com/Azure/azure-storage-fuse/pull/926
thanks for your patience
