### ISSUE TITLE
Blobfuse does not work with custom MSI endpoint having dev cert

### ISSUE THREAD

**Issue by rduser** [Azure/azure-storage-fuse#913]
### Which version of the blobfuse was used?
blobfuse 1

### Which OS (please include version) are you using?
ubuntu 18

### What problem was encountered?
I want to use MSI auth using a custom MSI endpoint. The endpoint I am using is insecure. (TLS cert is test cert)

Is it possible to configure blobfuse to ignore this instead of erroring out? (Similar to curl --insecure option)

Any other alternative?

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
N/A

### If relevant, please share your mount command.
N/A

**Comment by vibhansa-msft** [comment]
If you have your certificate file, you can provide its path on cli and that shall work. Also, in blobfuse config you need to clearly define your custom AAD endpoint as well. Kindly share your config and mount command.

**Comment by vibhansa-msft** [comment]
Closing this as there have been no updates. Feel free to reopen if you are still facing the issue. Also, you can give blobfuse2 a try as it has improved performance and features. Let us know if your use case works well with blobfuse2 or not.
