### ISSUE TITLE
Blobfuse2 failed to mount: temp directory not empty

### ISSUE THREAD

**Issue by AGELadviseurs** [Azure/azure-storage-fuse#931]
### Which version of the blobfuse was used?
Note: If you are using blobfuse 1.X.X, we would like to encourage you to try out the next generation of blobfuse, [blobfuse2](https://github.com/Azure/azure-storage-fuse/tree/main) which is currently in preview. The latest preview binaries can be found [here](https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2) and more information on how to convert config options can be found [here](https://github.com/Azure/azure-storage-fuse/blob/main/MIGRATION.md#blobfuse-v2-guide-for-mapping-options-from-v1xx-to-v2xx). We will continue to respond to bug reports for blobfuse 1.X.X, however, no more feature requests will be considered.
blobfuse2 version 2.0.0-preview.3

### Which OS (please include version) are you using?
Ubuntu Server 20.04.5 LTS

### What problem was encountered?
When rebooting VM, blobfuse2 will not mount until I manually empty the temp directory

### Have you found a mitigation/solution?
Manually empty temp directory after reboot

**Comment by francoisdutoit** [comment]
@AGELadviseurs Have you tried adding the below to your config file?

file_cache:
  allow-non-empty-temp: true

See full config example here : https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml

**Comment by AGELadviseurs** [comment]
> @AGELadviseurs Have you tried adding the below to your config file?
> 
> file_cache: allow-non-empty-temp: true
> 
> See full config example here : https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml

Ah this works! 
Also in conjunction with 'cleanup-on-start', which seems to be dependent on allow-non-empty-temp.

**Comment by francoisdutoit** [comment]
@vibhansa-msft There is still an issue. In version 1 of Blobfuse - We could pass the 'o - nonempty' option when mounting. At the moment - if files gets written to the mount directory and mounting only happens later - the mount will fail.  In our case we mount on startup - but in case a mount fails a script that runs every 15 minutes will try and mount the directory again. But files can be written to the directory in this case - before a successful mount.  Any workaround for tis issue? Even with the above configuration as indicated in the previous posts - the mount will still fail.

As can be seen from the below - there is no 'o - nonempty'  option.

`Error: invalid FUSE options. Allowed FUSE configurations are: `-o attr_timeout=TIMEOUT`, `-o negative_timeout=TIMEOUT`, `-o entry_timeout=TIMEOUT` `-o allow_other`, `-o allow_root`, `-o umask=PERMISSIONS -o default_permissions`, `-o ro``

**Comment by vibhansa-msft** [comment]
@francoisdutoit If expectation in such case is that post mount blobfuse will sync up the files to storage which were written to mount directory before the mount, then that is wrong. Only files created/opened after the mount will be synced. 
In case of v2 we have two config parameters one to allow non-empty mount path and another to clean up the mount directory on mount (so that those extra files are not shown in ls command as they are not going to be synced anyway). You can refer to our base config file's file-cache section for the same [here](https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml)

**Comment by vibhansa-msft** [comment]
Can you try providing "--empty-dir-check=false" cli parameter and see if that works for you.

**Comment by vibhansa-msft** [comment]
@francoisdutoit : Can you open another bug to track this nonempty mount path issue for blobfuse2, because this current bug was talking about non empty temp cache directory and not the mount point.
