### ISSUE TITLE
Unable to access the large files from blob storage

### ISSUE THREAD

**Issue by Udayendu** [Azure/azure-storage-fuse#937]
### Which version of the blobfuse was used?
- 1.4.4-1

### Which OS (please include version) are you using?
- RHEL 8.4

### What problem was encountered?
- Unable to access the large file

### Have you found a mitigation/solution?
- No

### If relevant, please share your mount command.
![image](https://user-images.githubusercontent.com/1809177/195577628-e57bc70b-47f7-471f-9de7-2f7098bbc280.png)

This is working fine for small size software but not for the ISO.
But I can see the ISO properly in the blob storage and size has been reported correctly as well.

- Mount server information:
![image](https://user-images.githubusercontent.com/1809177/195577766-5fe5b105-1591-4f5a-acd0-cb6e89fe39e6.png)

- MS Azure Storage Explorer:
![image](https://user-images.githubusercontent.com/1809177/195578345-43440649-d935-4603-a026-de4ac3fd6763.png)

**Comment by vibhansa-msft** [comment]
Version "1.4.4-1". There is no such official release, is this a private build you are using?

How much free space does mount point of "/opt/devops/.fusecache" have?
As per above info the ISO is 5.16GB in size and if disk does not have that much free space it will fail in download.

**Comment by vibhansa-msft** [comment]
Also, you can try next generation of blobfuse aka blobfuse2 which has read/write streaming support. Using this feature, you don't need to download entire file locally and can still do read/write operation on such huge files.

**Comment by vibhansa-msft** [comment]
Blobfuse works in local caching mode. "--tmp-path" that you specify points to location which blobfuse uses for local caching. Any file you open for read/write, blobfuse will download the entire file in local cache first and then allow user to do read/write operation. On closing the file, if it was updated blobfuse will upload the entire file again to storage container. As per your "df" command output above, I doubt you have only 1.6GB worth space in local cache and that is the reason blobfuse fails to download the file.
Only way to escape from full file download is to use streaming.

**Comment by vibhansa-msft** [comment]
When you say you are not able to access the large file, what do you mean? If you are trying to read the file or open the file then that implies blobfuse is downloading the file.

**Comment by Udayendu** [comment]
> When you say you are not able to access the large file, what do you mean? If you are trying to read the file or open the file then that implies blobfuse is downloading the file. If I understood correctly you are trying "md5sum" on the iso file which means you are reading the file.

I am trying to copy a file from the mount point of the blob store. But I can see that the side of the blob's mount is not correct and its complaining that there is no file with that name in the mounted location but I can see the file and its size using 'ls -lh'.

**Comment by vibhansa-msft** [comment]
Can you collect the debug logs and share them. In the output above it shows "ls -l" is showing the 'iso' file. So there might be something wrong when you are trying to open the file for read.

**Comment by Udayendu** [comment]
Hi @vibhansa-msft,

I have switched to file based storage for now and hence wont be able to reproduce this. May be the mount size could be the problem as you mentioned earlier. Hence we can close this issue and in future when I will start using blob again, I will use v2 and let you know if will face any issue.

Thanks.
