### ISSUE TITLE
Failed to create directory on cache directory

### ISSUE THREAD

**Issue by mustafakasap** [Azure/azure-storage-fuse#94]
What is wrong with below installation steps (as described in the blobfuse doc)? It gives error:
	“Failed to create directory on cache directory: /mnt/blobfusetmp/root/placeholder, errno = 13.”

fuse_stg_cont='face'
fuse_stg_acc='dataset'
fuse_stg_key='MyScretKey=='

cd ~/Downloads
wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install blobfuse fuse

sudo mkdir /mnt/blobfusetemp
sudo chown -R mksa /mnt/blobfusetemp/
sudo chmod 777 /mnt/blobfusetemp/

cd ~
echo -e \"accountName $fuse_stg_acc \naccountKey $fuse_stg_key \ncontainerName $fuse_stg_cont\" > connection.cfg
mkdir facedataset
blobfuse ./facedataset --tmp-path=/mnt/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=./connection.cfg

**Comment by seguler** [comment]
typo: blobfuset**e**mp

**Comment by satyam88** [comment]
]# sudo -u  satyam blobfuse /home/satyam/mycontainer --tmp-path=/mnt/resource/blobfusetmp --config-file=/home/satyam/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
fuse: device not found, try 'modprobe fuse' first

**Comment by vibhansa-msft** [comment]
What linux distro you are using ? This error points to fuse not being available in your system. Kindly install libfuse using 'sudo apt-get install libfuse-dev -y' and try again.
