### ISSUE TITLE
blobfuse mounts with multiple storage accounts

### ISSUE THREAD

**Issue by tusharg1993** [Azure/azure-storage-fuse#946]
I wanted to ask if using blobfuse (not blobfuse2 since it’s not GA yet) to mount containers across different storage accounts is supported. I was thinking it’s a matter of setting up different config files. Wanted to confirm.

I couldn’t find any documentation to tell me if it’s supported or not.

**Comment by vibhansa-msft** [comment]
Yes, to mount different containers you need to run blobfuse explicitly for those many times.
There are two ways to configure this thing. 
1. If you wish to mount 10 containers create 10 config files and mount  one blobfuse instance with one config at a time
2. If authentication keys are common across all then you can create one config file and not specify container name in it. While mounting blobfuse you can specify the container name on cli (as cli parameter). This saves you from creating those many files but works only if account and authentication keys are same across all those containers.

Blobfuse2 (preview version) has a feature where you can just fire one command and it will do all this implicitly. There will be 'n' instances of blobfuse2 running, one for each container, but you don't need to fire multiple commands to mount them explicitly. Though this is a preview version, we are fully supporting this and in case of any issue/query/concerns you can reach out to us here on github. If you feel this is easier way to mount multiple containers, I will advise to try out blobfuse2.

**Comment by tusharg1993** [comment]
Thanks @vibhansa-msft.

My question was more intended towards using different storage accounts. For example, say I want to mount container foo from storage account storageaccount1.blob.core.windows.net and container bar from storage account storageaccount2.blob.core.windows.net.

They both will be using same authentication (service principal or managed identity) so I can share the config file wrt authentication, however using the different account (storageaccount1 vs storageacount2) would require me to create two config files as there is no CLI argument for customizing storage account name/endpoint. Is that correct?

**Comment by vibhansa-msft** [comment]
Your understanding is correct. Account name cannot be sent as cli argument. If you wish to mount containers from different accounts, then you need to create those many config files.

**Comment by vibhansa-msft** [comment]
One more option you have is to have a common config file/environment variable holding authentication related config that works for all accounts. Spawn multiple shells and have account name configured as environment variable there and mount blobfuse by passing down container name as cli argument. This saves you from creating those many config files. However, for use case just creating multiple config files might be a simpler solution.

**Comment by vibhansa-msft** [comment]
Closing this as there is no action item on blobfuse end here. Feel free to post your queries here or re-open if you need any change from blobfuse side.
