### ISSUE TITLE
Packages for RHEL9

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-storage-fuse#949]
Please release packages for RHEL9.  it has been available since May 2022.

**Comment by vibhansa-msft** [comment]
Our build systems do not yet fully support RHEL 9. We are waiting for that to go through so that we can run our pipelines on that and release RHEL-9 formally. For now, you can use RHEL8.2 binaries or locally build.

**Comment by vibhansa-msft** [comment]
We already have this item in our backlog and once the build systems start supporting it we will release.
