### ISSUE TITLE
How to mount a VHD Blob exported from Azure VM Disk?

### ISSUE THREAD

**Issue by maitre-matt** [Azure/azure-storage-fuse#951]
Azure VM [disk export](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/download-vhd?tabs=azure-cli#generate-sas-url) gives access to VM VHDs through Blob SAS URLs along the lines of
```
https://md-c3h12q4n3dmz.z8.blob.storage.azure.net/qkgxzq2h4lcl/abcd?sv=2018-03-28&sr=b&si=c96e6b9c-5f32-49c2-94d7-b352bf8840a6&sig=<snip>
```
Is it possible to mount it? I am not sure how to configure things given this is a single Blob instead of a Container.

**Comment by gapra-msft** [comment]
Hi @maitre-matt Is your blob a page blob? If so, we don't support page blobs in blobfuse (read-only should work but we provide no guarantees)

In blobfuse2, we support mounting to a subdirectory, which means you could mount to a virtual directory in the container, however we don't support only mounting to a single blob.

**Comment by maitre-matt** [comment]
Thanks for the info!
