### ISSUE TITLE
if i change the file content in storage account, the changes are not reflecting in mount path file. Please suggest

### ISSUE THREAD

**Issue by ArulkumarPonnusamy** [Azure/azure-storage-fuse#954]

**Comment by gapra-msft** [comment]
Hi @ArulkumarPonnusamy are you changing the file content via the blobfuse mount or through some other method?

**Comment by ArulkumarPonnusamy** [comment]
I have a container called - myapplogs
the container is mounted in my linux vm (i can able to see the log file with content)

my application continuously sending logs into above mentioned container as a txt file. but i am not able to see the the latest logs into mount path

For Ex. the **log1.txt** file contains below
2022-10-31 06:15:30 Some text
2022-10-31 07:01:30 Some text

**Comment by gapra-msft** [comment]
> my application continuously sending logs into above mentioned container as a txt file

When you say this, are you directly modifying the file in the container or through the blobfuse mount location?

**Comment by ArulkumarPonnusamy** [comment]
modifying the content in container

**Comment by gapra-msft** [comment]
Unfortunately, blobfuse and blobfuse2 do not guarantee showing changes of a file in a container that have been modified outside the blobfuse mount. You could try to reduce the file cache timeout to 0, and close and reopen the file you are trying to see changes for, but again there is no guarantee you will see the changes unless they have been modified in the same blobfuse mount.

**Comment by ArulkumarPonnusamy** [comment]
file_cache:
  path: /root/home
  **timeout-sec: 120**
  max-size-mb: 4096

above one right?

**Comment by ArulkumarPonnusamy** [comment]
what if i add a new file or folder into container. will it be available in mounted folder?

**Comment by vibhansa-msft** [comment]
What version of blobfuse are you using?

**Comment by ArulkumarPonnusamy** [comment]
blobfuse2-2.0.0-preview.3-Ubuntu-22.04-x86-64.deb

**Comment by vibhansa-msft** [comment]
kernel also caches the data along with metadata of a file, and if its doing so calls to read the file or its meta will not even reach blobfuse, in such case there is hardly anything it can do.

**Comment by vibhansa-msft** [comment]
Closing this as there are no updates. Feel free to reopen once you have verified with the suggested changes.
