### ISSUE TITLE
Avilable space is 788G

### ISSUE THREAD

**Issue by guysoft** [Azure/azure-storage-fuse#96]
Hey,
So I opened a container and mounted and I can see that the available space is 788G.

Is there a way to increase this?  I see no limitation in Azure documentation.

In the docs it says "up to 500TB containers":
https://docs.microsoft.com/en-us/azure/storage/common/storage-decide-blobs-files-disks

**Comment by seguler** [comment]
Yes - the space reported to you in df is the space available in cache (/mnt). You can ignore that. That is only there to show you the local cache space. E.g. you cannot simultaneously open files that are larger than 788G because the cache dir would fill up.

**Comment by seguler** [comment]
So you can go up to 500TB data storage in Blob... and access all of it through blobfuse.. just at 788G at a time.

**Comment by guysoft** [comment]
So when you write the free space will go down or remain the same? Or Indicate the renaming cache?

**Comment by guysoft** [comment]
So when you write the free space will go down or remain the same? Or Indicate the renaming cache?

**Comment by guysoft** [comment]
Ok, great. Started using it here. If it crashes over 788G I'll reopen.
