### ISSUE TITLE
create-delete-close issue

### ISSUE THREAD

**Issue by AlexanderYukhanov** [Azure/azure-storage-fuse#97]
Actual behavior:
>>> f=open('test.txt', 'w')
>>> f.write('hello')
>>> os.unlink('test.txt')
>>> f.close()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 2] No such file or directory
 
expected f.close() to finish without exceptions and no file to be created

**Comment by seguler** [comment]
We're fixing this next week.

**Comment by asorrin-msft** [comment]
Finally looked into this.  I'm unclear as to exactly what's going on.  Similar code in C does not have an error:

```
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
int main()
{
    char *filepath = "/mountpoint/tmpfile.txt";
    char *filetext = "some text here";
    fprintf(stdout, "filepath = %s\n", filepath);

    int fd = open(filepath, O_RDWR | O_CREAT | O_EXCL);
    fprintf(stdout, "fd = %d, errno = %d\n", fd, errno);

    ssize_t size = write(fd, filetext, 10);
    fprintf(stdout, "size = %d, errno = %d\n", size, errno);

    int unlinkret = unlink(filepath);
    fprintf(stdout, "unlinkret = %d, errno = %d\n", unlinkret, errno);

    int closeret = close(fd);
    fprintf(stdout, "closeret = %d, errno = %d\n", closeret, errno);
}
```
for me, outputs:
```
fd = 3, errno = 0
size = 10, errno = 0
unlinkret = 0, errno = 0
closeret = 0, errno = 0
```
for both a file system directory and a blobfuse mounted directory.

However, like you pointed out, in Python, I do repro the failure:

```
        run_flush = False
        filepath = os.path.join(self.blobstage, "file1")
        print(filepath)
        file1blob = open(filepath, 'w')
        print('closed = ' + str(file1blob.closed) + ', fileno = ' + str(file1blob.fileno()) + ', writable = ' + str(file1blob.writable()))
        file1blob.write("Some file1 text here.")
        print('closed = ' + str(file1blob.closed) + ', fileno = ' + str(file1blob.fileno()) + ', writable = ' + str(file1blob.writable()))

        if run_flush:
            file1blob.flush()

        os.remove(filepath)

        print('closed = ' + str(file1blob.closed) + ', fileno = ' + str(file1blob.fileno()) + ', writable = ' + str(file1blob.writable()))
        file1blob.close()  # <--- Throws FileNotFoundError
        self.assertEqual(False, os.path.exists(filepath))
```
Weirdly, though, when I set run_flush to true in the above code, and flush the blob before close, it doesn't throw and everything works fine / as expected.  Running the above code on a non-fuse directory produces the expected results, both including the flush and not.

When I have time, I'll build the sample passthrough FUSE file system and run these tests where as well, maybe that'll illuminate what's going on.

**Comment by seguler** [comment]
@AlexanderYukhanov can we close this ?

**Comment by AlexanderYukhanov** [comment]
let me try to repro it in c++?

**Comment by AlexanderYukhanov** [comment]
test.c
#include <error.h>
#include <stdio.h>
#include <unistd.h>

int main(int argc, char** argv) {
    if (argc != 2) {
        fprintf(stderr, "Please provide a file name\n");
        return -1;
    }
    FILE *fp = fopen(argv[1], "w");
    unlink(argv[1]);
    fprintf(fp, "hello");
    if (-1 == fclose(fp)) {
        perror("fclose failed");
        return -1;
    }
    printf("OK\n");
    return 0;
}

$ cc test.c
$ ./a.out blobfuse/t.txt
fclose failed: No such file or directory
$ ./a.out /tmp/t.txt
OK

**Comment by AlexanderYukhanov** [comment]
According to strace, the error is coming in both cases not from close but from write call (which is triggered by fclose in c and file.close in python).
