### ISSUE TITLE
Not able to run the BLobfuse on RHEL 7.6

### ISSUE THREAD

**Issue by ArulkumarPonnusamy** [Azure/azure-storage-fuse#976]
### Which OS distribution and version are you using? RHEL-7.6
wget https://github.com/Azure/azure-storage-fuse/releases/download/blobfuse2-2.0.0-preview.3/blobfuse2-2.0.0-preview.3-RHEL-7.8-x86-64.rpm

### What was the issue encountered?
When i run the command **blobfuse2 -h**. It shows below error
blobfuse2: error while loading shared libraries: libfuse3.so.3: cannot open shared object file: No such file or directory

**Comment by vibhansa-msft** [comment]
You are missing the required dependency on your system. Kindly install "fuse3" on your system using "sudo yum install fuse3"
