### ISSUE TITLE
unable to list the directory 

### ISSUE THREAD

**Issue by dipakmadhavi** [Azure/azure-storage-fuse#978]
### Which version of blobfuse was used?

blobfuse2 version 2.0.0-preview.5
### Which OS distribution and version are you using?

RHEL 7.9
### If relevant, please share your mount command.
 blobfuse2 mount all /test1  --read-only --config-file=./config.yaml

### What was the issue encountered?

I am able to mount all container with recent build. but unable to list the directory on mounted blob, can see only files

if we do cd and change the directory I am able to get in.

Also linux find command not working on mounted container
Is there any option to use 1 container in read/write mode  and rest all in read only mode
### Have you found a mitigation/solution?

No

**Comment by vibhansa-msft** [comment]
Blobfuse expects a directory stub for non-HNS accounts, because there is no concept of directory in such accounts at the backend. If your account is non-HNS try adding "virtual-directory: true" under 'azstorage' section in your config file and mount.

**Comment by vibhansa-msft** [comment]
Were you able to try out the suggested config?

**Comment by dipakmadhavi** [comment]
It worked for me. But I have requirement to use other Unix native command on top of this mount so now started using v1

**Comment by vibhansa-msft** [comment]
Sorry, dint understand the last part. What command dependency you have that can not work with v2 ?

**Comment by dipakmadhavi** [comment]
I am unable to use find command on v2 mounted blob

**Comment by vibhansa-msft** [comment]
even with ""virtual-directory: true" ?

**Comment by dipakmadhavi** [comment]
yes after adding virtual-directory true and not see directory in list also. if we do cd it allow to go in
