### ISSUE TITLE
blobfuse reports wrong permissions

### ISSUE THREAD

**Issue by AlexanderYukhanov** [Azure/azure-storage-fuse#98]
$ ls -l /mnt/batch/tasks/shared/LS_root/mounts/bfs
total 4
drwxrwx--- 2 root root 4096 Feb 16 00:03 folder

$ echo hi > /mnt/batch/tasks/shared/LS_root/mounts/bfs/hello.txt
alex@8dffb6b3017a4cfe9cb5e88d67803a73000000:~$ ls -l /mnt/batch/tasks/shared/LS_root/mounts/bfs
total 8
drwxrwx--- 2 root root 4096 Feb 16 00:03 folder
-rw-rw-r-- 1 root root    3 Feb 16 00:07 hello.txt

So, file attributes tell that only root has access to folders and files, but in practice any user has full access

**Comment by seguler** [comment]
PR ? :)

**Comment by seguler** [comment]
Test the PR I've sent. It now assigns the correct user as the owner. However if you mount as allow_other, then this is still bypassed because we haven't implemented azs_access yet.

**Comment by AlexanderYukhanov** [comment]
are there any challenges with azs_access?

**Comment by seguler** [comment]
Yes rw-rw is now fixed. Azs_create was creating it with 660.

No challenge for azs_access. It can be implemented by saving ACLs in blob metadata... However I'd prefer to wait for the service side solution for this

**Comment by seguler** [comment]
Fixed in blobfuse 0.3
