### ISSUE TITLE
Certificate authority error while accessing storage account url

### ISSUE THREAD

**Issue by ArulkumarPonnusamy** [Azure/azure-storage-fuse#989]
### Which version of blobfuse was used?
blobfuse2-2.0.0-preview.4-RHEL-7.8-x86-64

### Which OS distribution and version are you using?
REDHAT 7.6

### What was the issue encountered?
facing certificate error

### Have you found a mitigation/solution?
No

### Please share logs if available.
Dec  1 17:16:12 myserver1 blobfuse2[32585]: LOG_ERR [block_blob.go (227)]: BlockBlob::TestPipeline : Failed to validate account with given auth %!s(func() string=0xc05c00)
Dec  1 17:16:12 myserver1 blobfuse2[32585]: LOG_ERR [azstorage.go (154)]: AzStorage::configureAndTest : Failed to validate credentials [-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/cloudtest/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157#012HTTP request failed#012#012Get "https://stgaccount.blob.core.windows.net/assets?comp=list": x509: certificate signed by unknown authority#012]
Dec  1 17:16:12 myserver1 blobfuse2[32585]: LOG_ERR [azstorage.go (100)]: AzStorage::Configure : Failed to validate storage account [failed to authenticate credentials for azstorage]
Dec  1 17:16:12 myserver1 blobfuse2[32585]: LOG_ERR [pipeline.go (69)]: Pipeline: error creating pipeline component azstorage [failed to authenticate credentials for azstorage]
Dec  1 17:16:12 myserver1 blobfuse2[32585]: LOG_ERR [mount.go (363)]: mount : failed to initialize new pipeline [failed to authenticate credentials for azstorage]

**Comment by vibhansa-msft** [comment]
There is something wrong with the certificate. If you are using private endpoint for OAuth make sure you have required proxy and aad endpoints configured properly. Also validate your certificate file through other means.

**Comment by ArulkumarPonnusamy** [comment]
No I am not using any private endpoints. the same blobfuse configuration is wokring in other server.

**Comment by vibhansa-msft** [comment]
This authentication error "HTTP request failed#012#012Get "https://stgaccount.blob.core.windows.net/assets?comp=list": x509: certificate signed by unknown authority#012]" is coming from server. There is something wrong with the authentication here. What kind of auth mode are you using.  Can you try switching to use account key or SAS.

**Comment by ArulkumarPonnusamy** [comment]
![image](https://user-images.githubusercontent.com/104942908/205237870-70f72cd3-e8cd-438e-92c2-eac638599bc5.png)

Attached the configuration for your reference

**Comment by ArulkumarPonnusamy** [comment]
![image](https://user-images.githubusercontent.com/104942908/205238026-43a34390-7256-412a-a54a-757e321dd526.png)

attached the configuration for your reference

**Comment by vibhansa-msft** [comment]
Kindly avoid using your credentials as this is public forum. Are you using exactly the same SAS on other servers as well?
Can you share what difference is there between this and other environments where it works. You can also enable log_debug and sdk-trace to get more details logs around the failure. in 'setup/baseconfig.yaml' file you can see how to configure these options in this repo.

**Comment by ArulkumarPonnusamy** [comment]
Yes. The Same SAS used in other server. Also i have enabled the log_debug. This is the error i am getting - request failed#012#012Get "https://stgaccount.blob.core.windows.net/assets?comp=list": x509: certificate signed by unknown authority#012]

**Comment by ArulkumarPonnusamy** [comment]
Is there any settings in config.yaml file to skip the certification error

**Comment by vibhansa-msft** [comment]
No, you cannot skip this, because this is coming from server and not a local validation happening on your client. There is something wrong with the connection which is resulting into this failure. Can you try sending this same request using some other tool like wget or postman and see if they also result into similar failure or not. Also, you can try switching to other form of authentication if possible.
