### ISSUE TITLE
cannot put executable for regular user on blobfuse

### ISSUE THREAD

**Issue by AlexanderYukhanov** [Azure/azure-storage-fuse#99]
$ echo 'echo hi' > /mnt/batch/tasks/shared/LS_root/mounts/bfs/script
$ chmod +x /mnt/batch/tasks/shared/LS_root/mounts/bfs/script
$ /mnt/batch/tasks/shared/LS_root/mounts/bfs/script
-bash: /mnt/batch/tasks/shared/LS_root/mounts/bfs/script: Permission denied
$ ls -l /mnt/batch/tasks/shared/LS_root/mounts/bfs/script
-rwxrwx--- 1 root root 8 Feb 16 00:14 /mnt/batch/tasks/shared/LS_root/mounts/bfs/script

At the same time,
$ echo 'echo hi' > /mnt/batch/tasks/shared/LS_root/mounts/bfs/notrunnable
$  /mnt/batch/tasks/shared/LS_root/mounts/bfs/notrunnable
-bash: /mnt/batch/tasks/shared/LS_root/mounts/bfs/notrunnable: Permission denied
$ sudo /mnt/batch/tasks/shared/LS_root/mounts/bfs/notrunnable
hi

**Comment by seguler** [comment]
PR ? :)

**Comment by seguler** [comment]
Can you test the PR I sent ?

**Comment by seguler** [comment]
Fixed in blobfuse 0.3
