### ISSUE TITLE
blobfuse2 is not able to fetch files & directories as required

### ISSUE THREAD

**Issue by pingtouskar** [Azure/azure-storage-fuse#990]
### Which version of blobfuse was used?
```
# rpm -qi blobfuse2
Name        : blobfuse2
Version     : 2.0.0
Release     : 1
Architecture: x86_64
Install Date: Fri 02 Dec 2022 06:18:16 AM UTC
Group       : default
Size        : 28531700
License     : unknown
Signature   : RSA/SHA256, Wed 30 Nov 2022 06:46:03 AM UTC, Key ID eb3e94adbe1229cf
Source RPM  : blobfuse2-2.0.0-1.src.rpm
Build Date  : Wed 30 Nov 2022 06:20:41 AM UTC
Build Host  : 6d525b56c000000
Relocations : /
Packager    : Blobfuse v-Team <blobfusevteam@microsoft.com>
Vendor      : none
URL         : https://github.com/Azure/azure-storage-fuse
Summary     : An user-space filesystem for interacting with Azure Storage
Description :
An user-space filesystem for interacting with Azure Storage
```

### Which OS distribution and version are you using?
```
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.4 (Ootpa)
```

### If relevant, please share your mount command.
```
# cat /etc/fstab | egrep -i blobfuse2
tmpfs        /mnt/blobfuse2tmp  tmpfs    defaults,size=32G                                                      0 0
blobfuse2    /artifacts fuse     defaults,_netdev,--config-file=/etc/blobfuse2/FileCacheConfig.yaml,attr_timeout=240,entry_timeout=240,negative_timeout=120     0 0
```

Also tried with the following:

```
# cat /etc/fstab | egrep -i blobfuse2
tmpfs        /mnt/blobfuse2tmp  tmpfs    defaults,size=32G                                                      0 0
blobfuse2    /artifacts fuse     defaults,_netdev,--config-file=/etc/blobfuse2/FileCacheConfig.yaml    0 0
```

Here is my filecache config file:

```
# cat /etc/blobfuse2/FileCacheConfig.yaml
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /mnt/blobfuse2tmp
  timeout-sec: 120
  max-size-mb: 32768

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: datashare2
  account-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  endpoint: https://datashare2.blob.core.windows.net
  mode: key
  container: artifacts
```

My mount points:

```
# df -PTh | egrep 'blob|Filesystem'
Filesystem                Type      Size  Used Avail Use% Mounted on
tmpfs                     tmpfs      32G     0   32G   0% /mnt/blobfuse2tmp
blobfuse2                 fuse       32G     0   32G   0% /artifacts
```

### What was the issue encountered?

- Files & directories are not cached in the client system
- To access the files, every time need to get into the mount point and need to run "ls -l" multiple times and then have to wait for few mins to access those

### Have you found a mitigation/solution?
- Yes, swithcing to NFS is working well.

### Please share logs if available.
```
Dec  2 06:26:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 06:27:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 06:27:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 06:27:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 06:27:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [lru_policy.go (271)]: lruPolicy::Clear-timeout monitor
Dec  2 06:27:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [lru_policy.go (342)]: lruPolicy::updateMarker
Dec  2 06:27:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [lru_policy.go (365)]: lruPolicy::deleteExpiredNodes : Starts
Dec  2 06:28:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 06:28:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 06:28:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 06:29:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 06:29:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 06:29:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 06:29:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [lru_policy.go (271)]: lruPolicy::Clear-timeout monitor
Dec  2 06:29:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [lru_policy.go (342)]: lruPolicy::updateMarker
Dec  2 06:29:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [lru_policy.go (365)]: lruPolicy::deleteExpiredNodes : Starts
Dec  2 06:30:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 06:30:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 06:30:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 06:31:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 06:31:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 06:31:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 06:31:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [lru_policy.go (271)]: lruPolicy::Clear-timeout monitor
Dec  2 06:31:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [lru_policy.go (342)]: lruPolicy::updateMarker
Dec  2 06:31:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [lru_policy.go (365)]: lruPolicy::deleteExpiredNodes : Starts
Dec  2 06:32:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 06:32:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 06:32:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 06:33:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 06:33:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 06:33:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 06:33:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [lru_policy.go (271)]: lruPolicy::Clear-timeout monitor
Dec  2 06:33:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [lru_policy.go (342)]: lruPolicy::updateMarker
Dec  2 06:33:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [lru_policy.go (365)]: lruPolicy::deleteExpiredNodes : Starts
Dec  2 06:34:09 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [libfuse_handler.go (548)]: Libfuse::libfuse_statfs :
Dec  2 06:34:09 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 06:34:09 AnsibleWorkerDev2 blobfuse2[929192]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 06:34:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 06:34:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 06:34:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 06:35:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 06:35:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 06:35:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 06:35:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [lru_policy.go (271)]: lruPolicy::Clear-timeout monitor
Dec  2 06:35:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_TRACE [lru_policy.go (342)]: lruPolicy::updateMarker
Dec  2 06:35:31 AnsibleWorkerDev2 blobfuse2[929192]: LOG_DEBUG [lru_policy.go (365)]: lruPolicy::deleteExpiredNodes : Starts
```

**Comment by pingtouskar** [comment]
I am using ansible for the deployment some software and expectation is to have the software available via blobfuse2 mount.
But its not available as required and need to run "ls -l" manually in the mount point to make it available. As a result whole automation is breaking. As a workaround, with NFS things are working fine:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [localhost] (item=dummyfile.zip) => {"ansible_loop_var": "item", "attempts": 20, "changed": false, "item": "dummyfile.zip", "msg": "Could not find or access '/artifacts/SOFTWARESTORE/VMWARE/DUMMY/dummyfile.zip' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

I already have the retry logic in my code. But still no luck:

```
register: result
until: result is not failed
delay: 6
retries: 20
```

**Comment by vibhansa-msft** [comment]
Sorry I did not get your query. Blobfuse does not do any caching on its own. It just responds back to kernel calls. So yes, file attributes will not be cached until you do a readdir (ls) or getstat (stat) command on that file/directory.
If your file is not available on the root and inside some sub-directory, then it's possible that you are missing the directory marker files. Can you validate if you have a flat-namespace account (HNS is not enabled or not).  If HNS is not there, can you add "--virtual-directory=true" cli parameter and try.

**Comment by pingtouskar** [comment]
HNS is not enabled.

![image](https://user-images.githubusercontent.com/110250427/205236041-21943796-d09a-4c08-9b59-6901964c6192.png)

I am not using CLI. My entry is in fstab. Should I add "virtual-directory=true" to fstab entry. Here is what I have as of now:

```
$ cat /etc/fstab | egrep -i blobfuse2
tmpfs        /mnt/blobfuse2tmp  tmpfs    defaults,size=32G                                                      0 0
blobfuse2    /artifacts fuse     defaults,_netdev,--config-file=/etc/blobfuse2/FileCacheConfig.yaml,attr_timeout=240,entry_timeout=240,negative_timeout=120     0 0
```

**Comment by vibhansa-msft** [comment]
"virtual-directory: true" you can add this to your config file under "azstorage" section and try.

**Comment by pingtouskar** [comment]
> "virtual-directory: true" you can add this to your config file under "azstorage" section and try.

Do we have any option to flush the blobfuse2 cache so that I can test again quickly instead of waiting for the default  cache expire time ?

**Comment by pingtouskar** [comment]
Seems like "virtual-directory: true" option is working but why I am getting the following logs in the log file:

```
Dec  2 07:54:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 07:54:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 07:54:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 07:55:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 07:55:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 07:55:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
Dec  2 07:55:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_TRACE [lru_policy.go (271)]: lruPolicy::Clear-timeout monitor
Dec  2 07:55:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_TRACE [lru_policy.go (342)]: lruPolicy::updateMarker
Dec  2 07:55:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_DEBUG [lru_policy.go (365)]: lruPolicy::deleteExpiredNodes : Starts
Dec  2 07:56:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_TRACE [cache_policy.go (82)]: cachePolicy::getCacheUsage : /mnt/blobfuse2tmp
Dec  2 07:56:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exec: "du": executable file not found in $PATH]
Dec  2 07:56:01 AnsibleWorkerDev2 blobfuse2[937584]: LOG_DEBUG [cache_policy.go (135)]: cachePolicy::getUsagePercentage : current cache usage : 0.000000%
```

And how exactly this "virtual-directory: true" works. Could you please explain a bit ?

**Comment by vibhansa-msft** [comment]
In Azure Storage world FNS account do not have any notion of a directory, there are just blobs with "/" in their name. However, blobfuse represents it as a filesystem on Linux so we need a concept of a directory. To overcome this whenever user creates a directory blobfuse will create a special marker file with directory name on container (0 byte in size). This will help us identify a directory, If data is uploaded through other tools to container, then these files will be missing. To handle such accounts, we have this flag to look for directory through other means. 
Other issue about the log that you have pointed out, we try to check the cache usage using "du" command which is a standard linux command. As per logs this command utility is not present in your system and hence the error. Either you can ignore it or install "du" command explicitly on the system. I will prefer installing it as that's one way for blobfuse to calculate its cache consumption and delete the files from local system if we are overusing it or filling the disk.

**Comment by vibhansa-msft** [comment]
Set "timeout-sec:0" in "file_cache" section in your config file, if you wish blobfuse to delete files from local cache immediately after you close the handle.

**Comment by pingtouskar** [comment]
> In Azure Storage world FNS account do not have any notion of a directory, there are just blobs with "/" in their name. However, blobfuse represents it as a filesystem on Linux so we need a concept of a directory. To overcome this whenever user creates a directory blobfuse will create a special marker file with directory name on container (0 byte in size). This will help us identify a directory, If data is uploaded through other tools to container, then these files will be missing. To handle such accounts, we have this flag to look for directory through other means. Other issue about the log that you have pointed out, we try to check the cache usage using "du" command which is a standard linux command. As per logs this command utility is not present in your system and hence the error. Either you can ignore it or install "du" command explicitly on the system. I will prefer installing it as that's one way for blobfuse to calculate its cache consumption and delete the files from local system if we are overusing it or filling the disk.

Thanks for the explanation.

My vm is a stadnard rhel8 vm and its having du in it.

![image](https://user-images.githubusercontent.com/110250427/205271710-38622885-22db-4e11-ab91-eaa3b2f5cd6b.png)

but not sure why blobfuse is not able to get the path for du. Could you please check from which location its trying to get the du path  in the code ?

**Comment by vibhansa-msft** [comment]
We do not execute from any specific path, we just execute "du" command assuming PATH variable is already set to point to binaries.

**Comment by pingtouskar** [comment]
> We do not execute from any specific path, we just execute "du" command assuming PATH variable is already set to point to binaries. This is what log has been pointing out as well "error running du [exec: "du": executable file not found in $PATH]"

But in my system its available and working well as well:

![image](https://user-images.githubusercontent.com/110250427/205272997-00706b2a-020f-4ff0-9d34-125caeeb79e0.png)

And as you can see, path has already been mapped correctly.

**Comment by vibhansa-msft** [comment]
Is blobfuse mounted from same shell, just in case path was set later or blobfuse does not have the same env variable it might fail. You can try remounting from your current shell where path is set and 'du' is working.
Also, if you keep file-cache timeout to 0 you can just ignore this error message. It will not make any difference if 'du' works or not in that case.

**Comment by pingtouskar** [comment]
Here is the function checking the usage: https://github.com/Azure/azure-storage-fuse/blob/main/component/file_cache/cache_policy.go#L80

And as per the syntax, the exact same command is working well:
![image](https://user-images.githubusercontent.com/110250427/205274234-bec15153-b92f-45b2-b9ec-fda8911d55ed.png)

**Comment by vibhansa-msft** [comment]
Yes, that what I am trying to convey too. Its issue with the PATH and not the command. It's not able to find the 'du' executable. Some glitches on the system not with blobfuse.

**Comment by vibhansa-msft** [comment]
Again, you can just ignore if file-cache-timeout is set to 0 as even if this command works, cache usage will always remain 0 and there will be no action taken by blobfuse on this result.

**Comment by pingtouskar** [comment]
> Is blobfuse mounted from same shell, just in case path was set later or blobfuse does not have the same env variable it might fail. You can try remounting from your current shell where path is set and 'du' is working. Also, if you keep file-cache timeout to 0 you can just ignore this error message. It will not make any difference if 'du' works or not in that case.

I have installed the blobfuse2 using root and PATH is set there correctly. Thats why i can execute the commands and its working well as well. But strange is blobfuse2 is not able to get the correct value of PATH. Not sure why. It supposed to use the same environment variable. And no customization in the environment as well:

![image](https://user-images.githubusercontent.com/110250427/205274886-3df77c9f-291c-44e3-9564-e7b5a5c354df.png)

**Comment by pingtouskar** [comment]
> Again, you can just ignore if file-cache-timeout is set to 0 as even if this command works, cache usage will always remain 0 and there will be no action taken by blobfuse on this result.

Okay.

**Comment by pingtouskar** [comment]
Seems like after few hrs its not able to get the files again even after setting "virtual-directory: true". I tried running, 'stat  /artifacts' and 'du -sh /artifacts'. Still no improvement. Is there any other way we can make sure that the share has been cached before we use it ?

**Comment by vibhansa-msft** [comment]
What you mean by caching the share? blobfuse cannot cache the data on its own, for listing only way to create the cache is to use the list operation, i.e. 'ls' command. If it has worked with virtual-directory flag once then it shall work always, it cannot happen that after few hours it did not list. Can you enable log-debug and share the log files where you encounter the failure.

**Comment by pingtouskar** [comment]
@vibhansa-msft 
After adding  "virtual-directory: true", a reboot was required to reflect the changed properly. And its been 3 days and its working well.

So may be adding that parameter did the trick. Hence I am closing this issue. Thanks alot for all your help.

**Comment by vibhansa-msft** [comment]
Thanks for the verification.

**Comment by vibhansa-msft** [comment]
Yes by default when a binary is started from /etc/fstab it might not have the correct env variables set. To solve this you need to follow the below steps:
- Instead of mounting from /etc/fstab directly, start a script from there. This can be done by replacing the blobfuse mount command in fstab with a path to script to run
- Inside the script first do "Export PATH="$PATH"
- next statement in the script shall be your blobfuse mount command as if you are executing it on the cli

Give this a try and it shall work fine for you.

**Comment by psinghof** [comment]
You can't run scripts from /etc/fstab and there is no blobfuse mount command in it. An fstab entry looks like this:

blobfuse2 /data/blob fuse umask=755,--tmp-path=... 0 0

and the parameters you see are:

**File system specifier:** blobfuse2
**Mount point:** /data/blob
**File system type:** fuse
**Mount options:**  umask=755,--tmp-path=...
**Dump frequency:** 0 
**File system check order:** 0

So no script or command call.

**Comment by vibhansa-msft** [comment]
You can run scripts from /etc/fstab.
Add an entry in fstab like
"/home/<your user name>/blobfuse.sh /usr/blob_mnt fuse defaults,_netdev 0 0


In file "/home/<your user name>/blobfuse.sh"
export PATH="$PATH
blobfuse2 <mount path> --config-file=<config file> <other mount options>   >>> Whatever mount command works for you


Once this is done, just run "sudo mount -a" and it shall mount blobfuse2.

**Comment by psinghof** [comment]
Thanks for your quick reply. You are right, it works like you described.

**Comment by vibhansa-msft** [comment]
Glad to hear it worked for you.
