### ISSUE TITLE
Libfuse::initFuse : failed to mount fuse

### ISSUE THREAD

**Issue by ArulkumarPonnusamy** [Azure/azure-storage-fuse#992]
### Which version of blobfuse was used?
blobfuse2-2.0.0-preview.4-RHEL-7.8-x86-64
fusermount version: 2.9.2

### Which OS distribution and version are you using?
RHEL7.6

### What was the issue encountered?
Libfuse::initFuse : failed to mount fuse

### Have you found a mitigation/solution?
NO

### Please share logs if available.
Dec  7 20:55:45  blobfuse2[11393]: LOG_ERR [libfuse_handler.go (177)]: Libfuse::initFuse : failed to mount fuse
Dec  7 20:55:45  blobfuse2[11393]: LOG_ERR [libfuse.go (148)]: Libfuse::Start : Failed to init fuse [failed to mount fuse]
Dec  7 20:55:45  blobfuse2[11393]: LOG_ERR [mount.go (457)]: mount: error unable to start pipeline [failed to mount fuse]

**Comment by vibhansa-msft** [comment]
Can you share mount command and your config. This appears to be some issue with your libfuse in the system.

**Comment by ArulkumarPonnusamy** [comment]
blobfuse2 mount /app/data --config-file=config.yaml

**Comment by vibhansa-msft** [comment]
RHEL 7.8 is fuse3 compliant, have you installed "libfuse3" on the system. You can confirm your fuse version using "fusermount --v" and "fusermount3 --v" commands. Let me know what output you get with these 2 commands.

**Comment by ArulkumarPonnusamy** [comment]
"fusermount --v" : fusermount version: 2.9.2
"fusermount3 --v": fusermount3: command not found

**Comment by vibhansa-msft** [comment]
it will be available in standard RHEL repo you just need to execute this command and it shall work.

**Comment by ArulkumarPonnusamy** [comment]
fusermount3 version: 3.6.1
fusermount version: 2.9.2
 can you pelase confirm the version of the package is correct?

**Comment by gapra-msft** [comment]
Yes it looks like you now have fuse3 in your system. Are you still experiencing the failed to mount fuse issue?

**Comment by ArulkumarPonnusamy** [comment]
in my local development envrionment the mount command is working without **fusermount3 --v**. the error is in other server. but both are **Rhel 7.6** and the package is **blobfuse2-2.0.0-preview.4-RHEL-7.8-x86-64**
