### ISSUE TITLE
Add blobfuse2-2.0.1 to Microsoft RHEL repo

### ISSUE THREAD

**Issue by sysadm216** [Azure/azure-storage-fuse#993]
Please add blobfuse2-2.0.1 to Microsoft RHEL repo
https://packages.microsoft.com/rhel/8/prod

Currently getting blobfuse2-2.0.0_preview.4-1.x86_64 when installing from repo

**Comment by gapra-msft** [comment]
Hi @sysadm216, The Blobfuse2 2.0.1 package is now in the RHEL 8 microsoft repo. Thank you again for bringing this to our attention
