### ISSUE TITLE
Bash completion not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by toggenation** [Azure/azure-storage-fuse#995]
### Which version of blobfuse was used?
```
blobfuse2 -v
blobfuse2 version 2.0.1

bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

### Which OS distribution and version are you using?
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

### If relevant, please share your mount command.
n/a

### What was the issue encountered?
After I created the completion script and pipe it to a file, source it and then try and trigger auto completion and I get a current directory listing instead of command options.
```
blobfuse2 completion bash  > blobfuse2
source ./blobfuse2
blobfuse2 {TAB} {TAB}
# outputs a directory list instead of blobfuse2 commands
```
### Have you found a mitigation/solution?
No

### Please share logs if available.
This is the output when I do `export BASH_COMP_DEBUG_FILE=bcdf1.log` and then `blobfuse2 {TAB} {TAB}`

[bcdf1.log](https://github.com/Azure/azure-storage-fuse/files/10191024/bcdf1.log)

**Comment by vibhansa-msft** [comment]
To suport /etc/fstab based mounting we had to pick "mount" as the default command. Due to this now there is ambiguity in completion script. As "/etc/fstab" is used by huge number of customers we preferred to support that and break shell completion.

**Comment by toggenation** [comment]
Perhaps add that to the documentation...

**Comment by madratman** [comment]
I am getting the same issue on 20.04 too

**Comment by vibhansa-msft** [comment]
@madratman : As pointed out earlier there was a breakage in mounting from /etc/fstab and for that we made some changes because of which autocompletion is broken. As /etc/fstab is more trivial case to support, we decided to take this hit.
