### ISSUE TITLE
Logging not working properly

### ISSUE THREAD

**Issue by lefabian-lab** [Azure/azure-storage-fuse#997]
### Which version of blobfuse was used?
blobfuse 2.0.1

### Which OS distribution and version are you using?
RH7.9 (Maipo)

### If relevant, please share your mount command.
not relevant 

### What was the issue encountered?
logging type in the config file set to base, and still some data are going to syslog.

### Have you found a mitigation/solution?
disable logging only :(

### Please share logs if available.
syslog records:
....
Dec  9 10:21:26 node1 blobfuse2[65406]: 2022/12/09 10:21:26 ==> REQUEST/RESPONSE (Try=1/9.933013496s[SLOW >3s], OpTime=17.459240227s) -- RESPONSE SUCCESSFULLY RECEIVED#012   PUT https://xxxxxx.blob.core.windows.net/logger-input/xxx/.xxxxxx&blockid=%2BfHeAFPYToh78NUJKArGYg%3D%3D&comp=block&timeout=901#012   Authorization: REDACTED#012   Content-Length: [4194304]#012   User-Agent: [Azure-Storage-Fuse/2.0.1 (Red Hat Enterprise Linux Server 7.9 (Maipo)) Azure-Storage/0.14 (go1.16.2; linux)]#012   X-Ms-Client-Request-Id: [acd8d598-0d35-43e5-7a6f-3ded49af7e79]#012   X-Ms-Version: [2020-08-04]#012   --------------------------------------------------------------------------------#012   RESPONSE Status: 201 Created#012   Content-Length: [0]#012   Date: [Fri, 09 Dec 2022 10:21:34 GMT]#012   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]#012   X-Ms-Client-Request-Id: [acd8d598-0d35-43e5-7a6f-3ded49af7e79]#012   X-Ms-Content-Crc64: [qZhppk7OeRo=]#012   X-Ms-Request-Id: [a05e18d0-f01e-0067-1bb7-0b0758000000]#012   X-Ms-Request-Server-Encrypted: [true]#012   X-Ms-Version: [2020-08-04]

**Comment by vibhansa-msft** [comment]
Can you point out which part you have problem with here?

**Comment by lefabian-lab** [comment]
`logging:
  type: base
  level: log_err
  file-path: /var/log/blobfuse2.log
  max-file-size-mb: 100
  file-count: 10
  track-time: true`

Why, when I have logging set to base, still some logs are going syslog?

**Comment by ArulkumarPonnusamy** [comment]
Yes. I am also faced the same issue. Even if you give the file path, logs are not written intot the specified path.. its still writing into /var/log/messages path

**Comment by vibhansa-msft** [comment]
One suggestion based on the above discussion. If objective is to dump blobfuse logs to a seperate file and keep it in /var/log then base logging is not the optimal way. You shall use syslog as logging strategy and use a syslog filter for blobfuse2 (shared in our setup directory)

**Comment by lefabian-lab** [comment]
After changing the path for logging nothing has changed.

**Comment by vibhansa-msft** [comment]
@lefabian-lab : Can you confirm your syslog filters. We have validated from our end and we do not see any logs going to syslog if base logging is configured. Also, as suggested in above comments if logs needs to be dumped at /var/log location use syslog as logging type and install correct syslog filters.

**Comment by lefabian-lab** [comment]
Thanks Vikas for workaround. Nevertheless, from my point of view this is a workaround and not a solution but sure, it fix the issue with filtering blobfuse messages from syslog.
